### ISSUE TITLE
知乎上没法私信。期待API封装、编译、使用方面的教程。

### ISSUE THREAD

**Issue by guzongyuan** [vnpy/vnpy#1]
多谢开源项目。期待API封装、编译、使用方面的教程，比如可以加入非类ctp的某些纯c api封装教程，再次感谢。

**Comment by vnpy** [comment]
可能得先注册个知乎号吧，给我在github上发私信也可以。教程正在做了，估计两周会全发出来。然后你提到的纯c api指哪些，据我所知恒生、飞创、易盛应该都是C++的吧，纯C的似乎只有quantbox的那个封装？

**Comment by guzongyuan** [comment]
我应该是登录知乎账户的但无法发送私信给你。要不你给我个邮箱？

**Comment by guzongyuan** [comment]
对方没有关注你，你不能给他发私信-------来自于知乎

**Comment by vnpy** [comment]
是个私信设置的问题，我改掉了，现在应该可以发。其实我更建议在知乎发问题邀请我回答，这样更方便社区一起讨论。
