### ISSUE TITLE
回测引擎的一个bug

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#100]
因为在库中，有的时候只有 lastPrice,而没有买一，卖一价。
按目前的逻辑，出来的成交价都是 0了，因为它取小的那个。

            buyCrossPrice = self.tick.askPrice1
            sellCrossPrice = self.tick.bidPrice1
            buyBestCrossPrice = self.tick.askPrice1
            sellBestCrossPrice = self.tick.bidPrice1

改成这样了
            if(self.tick.askPrice1>0.01  or self.tick.bidPrice1>0.01):
                buyCrossPrice = self.tick.askPrice1
                sellCrossPrice = self.tick.bidPrice1
                buyBestCrossPrice = self.tick.askPrice1
                sellBestCrossPrice = self.tick.bidPrice1
            else:
                buyCrossPrice = self.tick.lastPrice
                sellCrossPrice = self.tick.lastPrice
                buyBestCrossPrice = self.tick.lastPrice
                sellBestCrossPrice = self.tick.lastPrice

**Comment by vnpy** [comment]
嗯，这个情况确实是会存在，不过写成这样因为每个TICK都多了一个IF判断会拖慢整个回测速度。

我作为一个技术记录保存下来，遇到的朋友可以自己改，就不更新到代码里了。

谢谢
