### ISSUE TITLE
安装mongodb时一直报错

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1000]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question

## 预期程序行为
安装mongodb时一直报错， 在安装的进度时一直弹出窗口提示如下：
he installer has encountered an unexpected error installing this package.this may indicate a problem with package.the error code is 2502.

**Comment by vnpy** [comment]
可能是你的系统配置问题，参考这个方法试试：http://www.beihaiting.com/a/XTJC/XTJQ/2015/0709/7149.html
