### ISSUE TITLE
python3.x 不支持 

### ISSUE THREAD

**Issue by FutunnOpen** [vnpy/vnpy#1002]
## 环境

* 操作系统:  win10
* vn.py版本:  dev 

## Issue类型
三选一：Bug 

## 实际程序行为
\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaHistoryData.py", line 87, in loadMcCsv
    reader = csv.DictReader(file(fileName, 'r'))
NameError: name 'file' is not defined  

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cclauss** [comment]
https://travis-ci.com/vnpy/vnpy/builds/80961646

**Comment by cclauss** [comment]
The __dev__ branch is 144 commits ahead of the __master__ branch and there are tons of Python 3 compatibility fixes in the __dev__ branch that are not yet merged into __master__.

**Comment by vnpy** [comment]
已修复，Python 3合并预计会有较多需要修改的地方，后续发现bug请继续开issue，谢谢。
