### ISSUE TITLE
coinbase价格显示有问题，bitmex和okex订阅不到行情

### ISSUE THREAD

**Issue by xinjishiprojects** [vnpy/vnpy#1004]
![6ca11fc1343a258c0ae7c5f1c0eaa15](https://user-images.githubusercontent.com/40164981/43304077-23a0d874-91a5-11e8-9030-8b2810d75b4b.png)
![a8a29aaab243bb8baeef29e070ebf6d](https://user-images.githubusercontent.com/40164981/43304078-23e39498-91a5-11e8-9d29-d41025611df5.png)
![c6249066617413c67111a3775a37595](https://user-images.githubusercontent.com/40164981/43304081-2422fc78-91a5-11e8-9bb8-edd6510a7398.png)

**Comment by vnpy** [comment]
已修复，接口层的重连代码之前做测试给注释掉忘记改回来了

**Comment by xldistance** [comment]
搞好了行情记录里面应该设置为 ["XBTUSD.BITMEX", "BITMEX"]
