### ISSUE TITLE
价差算法的顺序

### ISSUE THREAD

**Issue by rhermit** [vnpy/vnpy#1008]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8

## Issue类型
三选一：Question

## 预期程序行为
1.8版本中的价差套利，
价差行情和价差持仓，品种的名字都是倒序，有规律可查如下图，12,11,10,9……

但是，价差算法中品种的顺序无序的，重新加载时品种的位置总是变化，
如下图，请问，如何也能让他按照一定规律显示啊，谢谢！

请看链接

http://www.vnpie.com/forum.php?mod=viewthread&tid=2824&page=1&extra=#pid8388

-

**Comment by vnpy** [comment]
使用OrderedDict代替普通字典，解决算法顺序问题
