### ISSUE TITLE
不同目录下的策略不能导入

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1010]
启动的时候，按理应该是自动导入策略的。
结果只有导入 安装的那些。  'vnpy.trader.app.ctaStrategy.strategy. 这自带的这些才能导入。

自己写的那些导不了。
我的目录结构是这样的

d:\vnpy-my 
d:\vnpy-my\run.py                                在这里启动， 只有放在run同个目录的才能导入。下级目录不行。
d:\vnpy-my\my_strategy\strategyTest     策略放在这里 
结果里面的策略都不行。
Failed to import strategy file xxxxxxx  

d:\vnpy-my\my_strategy\长线策略\xxxx策略xxxx
d:\vnpy-my\my_strategy\短线策略\xxxx策略xxxx
d:\vnpy-my\my_strategy\日内策略\xxxx策略xxxx

假如策略这样放在各种不同的目录下，导入不了啊。

目前的策略只能导入两个目录下的：
一，安装目录  'vnpy.trader.app.ctaStrategy.strategy.
二，跟run.py同个位置。即使下级目录也不行。

**Comment by KobeZhao** [comment]
策略的引擎是要到ctaStrategy/strategy下午寻找策略文件的，如果自己不修改路径，策略就要放在strategy文件夹下

**Comment by viponedream** [comment]
其实它是有去当前目录寻找策略的，只是导进去出错了。

**Comment by viponedream** [comment]
把策略所在的路径加入到系统中去就可以导入了。

# 遍历工作目录下的文件
workingPath = os.getcwd()
for root, subdirs, files in os.walk(workingPath):
    for name in files:
        # 只有文件名中包含strategy且以.py结尾的文件，才是策略文件
        if 'strategy' in name and name[-3:] == '.py':
            # 模块名称无需前缀
            moduleName = name.replace('.py', '')
            sys.path.append(root)                   # 加入模块所在位置----》  加这一句就可以了。
            loadStrategyModule(moduleName)

**Comment by vnpy** [comment]
修改strategy/__init__.py里的遍历目录逻辑就好
