### ISSUE TITLE
请问作者运行策略时，DrEngine是自动被调用么。是在哪里被调用的啊。 

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#1011]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by KobeZhao** [comment]
请前往文件夹examples/DataRecording/runDataRecording
