### ISSUE TITLE
多合约的技术难度

### ISSUE THREAD

**Issue by daisypupu** [vnpy/vnpy#1016]
vnpy的ctaEngine提供多策略的实盘交易，ctaBacktestingEngine提供单策略多合约的功能(multiprocessing实现）
实盘如果要实现多合约，目前只能通过对接JAQS. 看了zhihu对于不开发多合约的解释与对vnpy的定位，大概理解为什么开发方选择JAQS。不过这里想问的是，从技术的角度来说，除了写一个multiprocessing / Threading wrapper，并修改相应逻辑（比如让dataEngine的dictionary能处理多合约），还有什么技术上的障碍？
一个相关的问题是，Threading concurrency有GIL的问题，如果用multiprocessing实现真正的parallelization, 对性能有什么影响？multiprocessing的语法接近Threading, 换到这个框架的改动其实不会很大

**Comment by vnpy** [comment]
1. 没有任何技术上的障碍，毕竟都是Python，只是出于项目定位没有在VnTrader的CTA策略模块中做单策略多合约的支持。
2. 多进程和多线程最大的区别，就是需要做额外的数据通讯工作，多线程可以直接访问同一进程内的数据，而多进程则需要通过RPC模块来回传输数据，整个系统的架构会变复杂得多，不是专业用户不建议折腾。
