### ISSUE TITLE
FCOIN 是不是限制下单啊，我5秒下一次单，下了20次左右就下不了了。

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#1017]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
FCOIN的流控非常严，官网号称10秒100次，实际可能10秒只有2-3次，而且频繁超过会被禁IP
