### ISSUE TITLE
VNPY安装出现问题，打不开VNTRADER

### ISSUE THREAD

**Issue by Royle0** [vnpy/vnpy#1018]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Question
我已经按照步骤安装。但是运行VNTrader目录下的run.py还是打不开VNPY界面。

## 预期程序行为
本来应该安装好了，直接可以打开界面。

## 实际程序行为
C:\vnpy\examples\VnTrader>python run.py
F:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\api\ib\__in
it__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi
::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<
class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from vnpy.trader.gateway import (femasGateway, xspeedGateway,
  File "F:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\tra
der\gateway\futuGateway\__init__.py", line 4, in <module>
    from futuGateway import FutuGateway
  File "F:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\tra
der\gateway\futuGateway\futuGateway.py", line 14, in <module>
    import futuquant as ft
  File "F:\ProgramData\Anaconda2\lib\site-packages\futuquant\__init__.py", line
20, in <module>
    from futuquant.quote.open_quote_context import OpenQuoteContext
  File "F:\ProgramData\Anaconda2\lib\site-packages\futuquant\quote\open_quote_co
ntext.py", line 11, in <module>
    from futuquant.common.open_context_base import OpenContextBase, ContextStatu
s
  File "F:\ProgramData\Anaconda2\lib\site-packages\futuquant\common\open_context
_base.py", line 334
    def on_activate(self, conn_id, now: datetime):
                                      ^
SyntaxError: invalid syntax

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请在run.py里移除futuGateway

**Comment by Royle0** [comment]
谢谢 已经解决了
