### ISSUE TITLE
algoTrading内停止算法时保存的算法命错误

### ISSUE THREAD

**Issue by asxzy** [vnpy/vnpy#1019]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

dev分支内的vnpy/trader/app/algoTrading/algo文件夹下多个算法在读取算法配置时变量错误

blAlgo.py:6841
sniperAlgo.py:6481
icebergAlgo.py:7087

**Comment by vnpy** [comment]
已修复
