### ISSUE TITLE
建议加一个参数

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#102]
现在策略有 oninit,onstart,ontrade这几个。
好像还少一个。 当前是否是实时行情。 这样跟回测来的tick分开。
肯定有用处，只是还没想好。

**Comment by viponedream** [comment]
想到了，实盘用到的参数是最优好了的。并且各个品种不同。
平时回测就是其它参数。
所以有一个判断是否实盘的变量会比较好。（是否实盘或者是否收到实时行情）

**Comment by vnpy** [comment]
等于是一个引擎的参数，实盘用的是CtaEngine，回测用的是BacktestingEngine，可以考虑加一个。

**Comment by viponedream** [comment]
回测优化的参数目前只有一种情况， 如一个步长值从10到20的，
还有一种情况是只有一个固定值的，如setSetting("vtSymbol") = 'RB0000"  并且传递给策略，在策略中判断目前是什么样的品种。 setSetting('RUNMODE") = 'BACKTESTING' 等这种只有一个值的。

**Comment by vnpy** [comment]
就是说你可能在策略里写了具体的配置？比如IF用一个，RB用一个？

**Comment by viponedream** [comment]
恩。同一个策略，针对不同品种，使用不同的参数。

**Comment by vnpy** [comment]
你这个要求有点特别的，就是想遍历回测多个品种的业绩表现？

**Comment by viponedream** [comment]
不是这个意思。回测的时候已经找出最优参数了。然后写在策略中，
模拟的时候，策略自己可以依据不同的品种采用不同的参数。

**Comment by vnpy** [comment]
我大概明白你的需求了，想想怎么弄

**Comment by vnpy** [comment]
已经添加
