### ISSUE TITLE
api & gateway 一个问题和两个建议

### ISSUE THREAD

**Issue by daisypupu** [vnpy/vnpy#1020]
关于vnpy/api/* 和 vnpy/app/gateway/*的结构有一个问题和两个建议

以huobi为例
1. 目前的结构是 vnpy/api/gateway/HuobiGateway.HuobiGateway继承vtGateway, HuobiGateway.TradeApi/DataApi 继承vnpy/api/vnhuobi

vnhuobi和HuobiGateway.TradeApi/DataApi各自的职责看得很头疼: vnhuobi主要是负责具体 restapi/websocket的连接, TradeApi/DataApi是负责wrap vnhuobi methods to 实现mainEngine.gateway.(connect, subscribe, sendOrder, cancelOrder, qryAccount, qryPosition, close)这些函数以供调用?

从代码结构来说, 是不是写一个另写一个base class for HuobiGateway.(HuobiGateway, TradeApi, DataApi) 定义一下必须实现的函数, 让代码更容易维护一点? 

2. vnhuobi的exception是直接print XXXX. 用child class onError/writeLog, 写入log的处理方式更好一点; 这个可以放到前面提到的base class里去

**Comment by vnpy** [comment]
1. 各个类功能的理解完全正确，vnpy.api中包含的是各个交易接口最接近原生的API实现（包含所有的基础功能），而vnpy.trader.gateway下的gateway则是包含了vnpy.api中接口到VnTrader的业务对接（或者说转换）。以HuobiGateway为例，基类就是VtGateway，而底层的TradeApi/DataApi的继承实现是没有办法标准化的（本质就是各个接口到VnTrader数据结构转化的地方）
3. vnhuobi中的回调函数中的代码，都是最简单的输出，如果有更复杂的需求可以继承后修改
