### ISSUE TITLE
加载一个月的tick数据出现pymongo.errors.OperationFailure

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1026]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 3.6 64位
* vn.py版本: v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
![qq 20180806104904](https://user-images.githubusercontent.com/29418474/43694544-6cb11056-9966-11e8-8c7d-c9b6fc525bd8.png)

**Comment by vnpy** [comment]
MongoDB内存爆了。。。哈哈哈，你这是弄了多少数据。

解决方案他也说了，给数据库加上索引，或者少弄点数据排序。

**Comment by xldistance** [comment]
群主能修改tick回测支持分段回测吗
