### ISSUE TITLE
一直报 No module named websocket 安装也安装不了

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#1029]
## 环境

* 操作系统: Ubuntu 16.04 （阿里云）
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by psj6335490** [comment]
软件源，换了清华的 163的，阿里的都不行

**Comment by vnpy** [comment]
pip install websocket-client

requirements.txt里有需要安装的包名字
