### ISSUE TITLE
一拖N，

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#103]
有机会也可以实现一下。
就是开单时，同时发出止损止盈。只要止损触发，止盈就自动撤销，反之同理。

**Comment by vnpy** [comment]
你要的这个类似外汇里的OCO订单吧，可以在策略代码里实现的，回头我来补充个例子。

**Comment by vnpy** [comment]
准备增加一个5分钟级别的趋势突破策略，展示：
1. OCO委托
2. 5分钟线聚合逻辑

**Comment by ideaplat** [comment]
期待，不知什么时候可以看到

**Comment by akeyong** [comment]
很期待！

**Comment by vnpy** [comment]
已经添加了新的策略演示代码：
https://github.com/vnpy/vnpy/blob/dev/vn.trader/ctaAlgo/strategy/strategyKingKeltner.py

**Comment by silent494529371** [comment]
感觉群主实现的sendOcoOrder只是实现2个方向的开单，我想楼主的意思是开单成交后同时发出止损止盈单子，所以要实现这样的功能还是需要需要在ontrade里面实现sell/cover的两个方向止损止盈单子，不知道对否，不过这样的逻辑就复杂很多了，只要这张单子还在，止损和止盈的单子就不能再取消了，至少onfarbar里面不能一开始就取消未成交的单子了.
    def onFiveBar(self, bar):
        """收到5分钟K线"""
        # 撤销之前发出的尚未成交的委托（包括限价单和停止单）
        for orderID in self.orderList:
            self.cancelOrder(orderID)

**Comment by silent494529371** [comment]
感觉群主实现的sendOcoOrder只是实现2个方向的开单，我想楼主的意思是开单成交后同时发出止损止盈单子，所以要实现这样的功能还是需要需要在ontrade里面实现sell/cover的两个方向止损止盈单子，不知道对否，不过这样的逻辑就复杂很多了，只要这张单子还在，止损和止盈的单子就不能再取消了，至少onfarbar里面不能一开始就取消未成交的单子了.
def onFiveBar(self, bar):
"""收到5分钟K线"""
# 撤销之前发出的尚未成交的委托（包括限价单和停止单）
for orderID in self.orderList:
self.cancelOrder(orderID)- @viponedream@vnpy #318
