### ISSUE TITLE
IB里面的 vtSymbol 重复

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1030]
目前使用的是  symbol + exchange的，这样是重复的。
比如说象期权，期货等有到期日那种。他们的 symbol  exchange 都是相同的。
在IB感觉还是直接采用他的 localSymbol 比较好。这样才不会重复。
或者使用  localSymbol + exchange

**Comment by LishanZhong** [comment]
vnpy里面ib的接口是怎么使用的？需要下载tws吗？

**Comment by viponedream** [comment]
肯定要啦。要先开tws或 ibgateway

**Comment by LishanZhong** [comment]
请问tws或 ibgateway都是单独的软件吗？

**Comment by LishanZhong** [comment]
ibgateway是直接从程序连接到交易所，不需要在本机软件中转？是这样吗

**Comment by vnpy** [comment]
本地程序 -> IbGateway -> IB的服务器 -> 交易所

**Comment by LishanZhong** [comment]
楼主可以给个联系方式吗？有关ib api的问题想要请假。比较急

**Comment by viponedream** [comment]
其实我也不太会用。玩而已。我现在用的是 ib 的官方 api。是py3的。

**Comment by LishanZhong** [comment]
你是用vnpy了吗？我运行ib启动成功但是找不到合约wti

**Comment by viponedream** [comment]
你的合约写错了。

**Comment by LishanZhong** [comment]
我的qq513151396,可以详细请教一下大哥吗？

**Comment by LishanZhong** [comment]
请问这个地方应该怎么设置？这样对吗？还是报错找不到合约。
![ibquestion](https://user-images.githubusercontent.com/26140370/44897105-1e66fe80-ad2d-11e8-884f-3e1731a7e4b2.jpg)

**Comment by viponedream** [comment]
你写错了。到论坛看一下，我写上去了。

**Comment by vnpy** [comment]
2.0的ib_gateway已经完成，合约代码改为使用IB系统内每个交易所中独立的conId，以后跟大部分接口一样，只要conId和exchange两个字段就能确定合约了
