### ISSUE TITLE
最近研究基于tick级别的策略回测，总是出现以下错误？？？

### ISSUE THREAD

**Issue by winner1986** [vnpy/vnpy#1032]
## 环境

* 操作系统: 如Windows 8或者
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9发行版
## Issue类型
Question

## 实际程序行为
之前查阅vnpie论坛，有个昵称叫 视线宽点 的朋友开了个帖子，按照他的说明讲策略内关于Bar的设置修改为Tick设置，也对本地的数据进行了检查，但是还是出现
AttributeError: 'NoneType' object has no attribute 'lastPrice'  的错误，使用IDE环境进行调试，初步判断是数据已经加载，但在回测引擎不能运算，这是怎么回事？

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![default](https://user-images.githubusercontent.com/21015172/43934839-c2dddc14-9c83-11e8-8753-c8eafa8cd5e2.png)
vnpie论坛上的修改介绍，楼主已经解决，我按照其说明没有解决问题，已抓狂N次！
![_20180810094711](https://user-images.githubusercontent.com/21015172/43934844-cc898286-9c83-11e8-8892-c682a81aeb46.jpg)
本机调试出现的问题，我推断数据问题的可能性极大，请各位大神不吝赐教！

**Comment by vnpy** [comment]
从回测输出看，应该是你的数据量不足，只满足了初始化的部分，而没有足够的部分用于回放，导致回测引擎中的self.tick（最新tick对象）为None，请调整你的初始化天数，或者去获取更多的数据。
