### ISSUE TITLE
对新版回测引擎中HistoryDataServer的“按任意键退出”功能的建议

### ISSUE THREAD

**Issue by cooooo** [vnpy/vnpy#1034]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 最新

## Issue类型
三选一：Question

## 预期程序行为
新版回测引擎提供了一个HistoryDataServer。其中有一个“按任意键退出”功能，方便退出HistoryDataServer。

## 实际程序行为
按任意键并不能退出。

## 修改建议
增加'hds.stop()'调用。
```
def runHistoryDataServer():
    """"""
    repAddress = 'tcp://*:5555'
    pubAddress = 'tcp://*:7777'

    hds = HistoryDataServer(repAddress, pubAddress)
    hds.start()

    print(u'按任意键退出')
    raw_input()
    hds.stop()
```

**Comment by vnpy** [comment]
已修复
