### ISSUE TITLE
tick级别数据在vnpy1.8.1版本下无法回测，原因是源码中filter的参数错误

### ISSUE THREAD

**Issue by Liyunfan1998** [vnpy/vnpy#1035]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
无报错

## 实际程序行为
报错NoneType object does not have attribute 'lastPrice'

## 重现步骤
tick策略的回测
问题出在/vnpy/trader/app/ctaStrategy/ctaBacktesting.py——loadHIstoryData()
![image](https://user-images.githubusercontent.com/22017570/44001111-47a2bba0-9e5e-11e8-98a8-055cb2334ecd.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
该错误是因为回测的数据量无法满足初始化数据需求，导致回放测试数据为空，增加了统计回测结果前对回测成交记录的检查，不再抛出异常
