### ISSUE TITLE
futuquant有版本限制

### ISSUE THREAD

**Issue by Liyunfan1998** [vnpy/vnpy#1036]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
无报错

## 实际程序行为
依赖报错

## 重现步骤
（暂无截图）
问题是futuquant有版本限制，vnpy支持的版本为版本2（个人使用2.3.14）
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
v1.9中已经升级到最新版本的futuquant
