### ISSUE TITLE
新版的上期所平今平昨还是有问题。

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#104]
白天开的，白天可以平出去。
夜盘开的，夜盘平不了。如夜盘9点半开的仓，10点多平不出。显示平昨仓位不足。

要不pos干脆加上开仓时间来计算？就容易算了。

**Comment by vnpy** [comment]
9点半开的仓，10点多平应该是平今吧？你是用CTA模块触发的这个问题还是手动交易导致的？

**Comment by viponedream** [comment]
是策略自己平的，平不出。
就是 SELL, COVER这两个平仓命令。
没有手动操作。

**Comment by vnpy** [comment]
有空提供下具体问题的重现方式，我这里之前试了下弄不出来。
