### ISSUE TITLE
WebTrader功能连接CTP没有反应

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1040]
## 环境

* 操作系统:LINUX
* Anaconda版本: anaconda-21.48.22.121-1.el7.centos.x86_64
* vn.py版本: 最新版本的master

## Issue类型
Bug

## 预期程序行为
连接WebTrader网页版，点击“连接CTP”可以正常连接成功

## 实际程序行为
没有反应。

## 重现步骤

N/A

**Comment by ShellMount** [comment]
目前定位到：

vnrpc.py中 RpcServer 中，   
 #----------------------------------------------------------------------
    def run(self):
        """服务器运行函数"""
        print "RPC-SERVER RUN"
        while self.__active:
            # 使用poll来等待事件到达，等待1秒（1000毫秒）
            if not self.__socketREP.poll(1000):        **<-----这一步，收到不 RpcClient self.__socketREQ.send(reqb) 发出的请求**
                continue

            print "RPC-SERVER监听中"

**Comment by ShellMount** [comment]
奋战N天，找到原因/BUG（见笑，对WEBSOCKET不熟悉）：

examples/WebTrader/templates/index.html 中：

var socket = io.connect(host, { transports: ['websocket'] });

**Comment by ShellMount** [comment]
浏览器中调式信息中，有如下报错：
WebSocket connection to 'ws://yes.imqk.com:5000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400


此外：修改index.html 中数据传送方式后正常，但实时数据传递功能也没有了：
var socket = io.connect(host + "", {transports:['polling', 'websocket']});

**Comment by vnpy** [comment]
请使用
