### ISSUE TITLE
huobi,bian,okex行情服务器连接失败

### ISSUE THREAD

**Issue by yfjelley** [vnpy/vnpy#1044]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
win10
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
要科学上网的，懂了吗（手动斜眼）

**Comment by yfjelley** [comment]
当然是科学上网了， 不然网站都不开？

**Comment by vnpy** [comment]
数字货币相关接口，请使用VPN翻墙（SS不行），或者海外的云服务器
