### ISSUE TITLE
strategy.vtSymbol

### ISSUE THREAD

**Issue by daisypupu** [vnpy/vnpy#1045]
ctaEngine.py 在设置tickStrategyDict的时候用到strategy.vtSymbol. 
然而vtSymbol既没有出现在ctaTemplate, 也没有出现在strategy[...].py里(准确来说, 只出现在了paramList里). 请问vtSymbol在runBackting和runCtaTrading是怎么把这个参数传给strategy的?

**Comment by stabledistribution** [comment]
在vtObject里，你可以在pycharm里右键goto找到

**Comment by vnpy** [comment]
通过paramList配置后，策略初始化加载参数配置的时候回自动绑定该属性，这里使用的主要是Python语言的动态属性绑定功能
