### ISSUE TITLE
ta-lib安装问题

### ISSUE THREAD

**Issue by shorizons** [vnpy/vnpy#1046]
## 环境

* 操作系统: 如Windows 10 Home
* Anaconda版本: Anaconda2-4.0.0-Windows-x86
* vn.py版本: vnpy-1.9.0发行版（下载日期20180816）

## Issue类型
三选一：Question

## 预期程序行为
成功安装ta-lib

## 实际程序行为
无法安装ta-lib

## 重现步骤
在command window执行conda install -c quantopian ta-lib=0.4.9 -y 时报错如下：
(base) D:\vnpy-1.9.0>conda install -c quantopian ta-lib=0.4.9 -y
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - mkl_fft
  - ta-lib=0.4.9
Use "conda info <package>" to see the dependencies for each package.

**Comment by czbzgl** [comment]
我遇到了同样的问题，最终我从https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib这个网站离线安装TA_Lib‑0.4.17‑cp27‑cp27m‑win32.whl解决了问题

**Comment by sixkingdoms** [comment]
it works..
