### ISSUE TITLE
CtaEngine: settingfilePath 和 StEngine: settingFilePath 

### ISSUE THREAD

**Issue by Nimloth1** [vnpy/vnpy#1047]
![image](https://user-images.githubusercontent.com/29222344/44245447-49206580-a20b-11e8-8f20-d3114a0f1791.png)
不同app中settingfilePath这个变量的命名方式不一样，在代码复用的过程中出现了找不到settingfile的问题，建议统一命名方式

**Comment by vnpy** [comment]
已修复
