### ISSUE TITLE
vnpy1.9版本不是支持海龟吗？

### ISSUE THREAD

**Issue by zha0yangchen** [vnpy/vnpy#1050]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

请问一下海龟什么时候能够支持呢

**Comment by vnpy** [comment]
v1.9.1保证支持，这次绝对不拖了，我保证~~！

**Comment by xldistance** [comment]
急什么，我从去年年中等到现在(*^▽^*)

**Comment by vnpy** [comment]
已完成
