### ISSUE TITLE
大商所日期处理逻辑可能导致临近24:00的tick出现日期错误

### ISSUE THREAD

**Issue by szsa** [vnpy/vnpy#1052]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

处理大商所的tick日期，使之是正确的交易发生时间的日期

## 实际程序行为

    目前在ctpGateway中，大商所tick的日期直接取本地机器，本地机器时钟与交易所时钟必然存在差异，
加上网络传输时间，处理tick的时候，可能在处理2月1日23:59:900的tick数据时候，本地时间已经是2月2日，导致tick数据错误，2月1日的数据成了2月2日的夜盘数据
        if tick.exchange is EXCHANGE_DCE:
            tick.date = datetime.now().strftime('%Y%m%d')

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by viponedream** [comment]
没考虑放假什么的。

**Comment by ShellMount** [comment]
# 大商所日期转换
        if tick.exchange is EXCHANGE_DCE:
            tick.date = datetime.now().strftime('%Y%m%d')
        

这个逻辑中，有一个前提条件：本地时间跟远程时间一至，但这通常是不可能的。

更好的方案：
# 大商所日期转换
        if tick.exchange is EXCHANGE_DCE and 当时分秒 < time(0:05:00):
            tick.date = datetime.now().strftime('%Y%m%d')

**Comment by xldistance** [comment]
![qq 20181011133156](https://user-images.githubusercontent.com/29418474/46782767-15b90d80-cd5a-11e8-83f9-26b9bf9debd1.png)

**Comment by smartgang** [comment]
> 放假是另外一个情况了 需要单独考虑 如果要自动化 就要有交易日历 太麻烦了
> 放假还是在放假前一个工作日的日盘收盘后手动停止程序较好

不明白放假会有什么问题，放假前不都是没有夜盘的吗？

**Comment by vnpy** [comment]
最安全的方案是记录原始数据后，每天执行清洗脚本自行清洗数据。

但由于大部分人没有该运维能力，当前选择了最傻瓜的折中方案，如果希望保证数据质量可以取消这里的转换，自行开发清洗脚本。

或者直接购买付费的数据服务。
