### ISSUE TITLE
WebTrader 的 WebSocket 连接不正常

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1056]
## 环境

* 操作系统: CENTOS/WINDOWS
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 最新版本master

## Issue类型
三选一：Bug

## 预期程序行为
WebTrader 网页登陆前/后，正常连接。

## 实际程序行为
登陆前产生报错：
WebSocket connection to 'ws://xxx.yyy.zzz:5000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

但将 index.html 中传输模式变更为下面代码的时候，则不报错，但也不能即时推送信息了：
异常行：
`var socket = io.connect(host + "", { transports: ['websocket'] });
`
变更后无报错，但不能实时推送数据到客户端
`
var socket = io.connect(host + "", {transports:['polling', 'websocket']}); 
`

## 重现步骤
网页访问即可。

**Comment by vnpy** [comment]
请使用chrome再试试
