### ISSUE TITLE
logger的一个想法

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1057]
象这样，我在整个系统任意地方，
self.logger.info(  msg  )
然后它自动显示在三个地方：
1，UI显示的 onlog 
2, console显示 
3，文件输出。

目前对于ui上的显示是需要输入 4 行的。能不能简化成只要以上那样的一行？
            log = VtLogData()
            log.gatewayName = self.gatewayName
            log.logContent = text.CONFIG_KEY_MISSING
            self.onLog(log)

**Comment by vnpy** [comment]
OK，我来增加这么个全局的日志记录函数

**Comment by vnpy** [comment]
考虑后决定不增加该功能，原因如下：
1. VnTrader中的日志分为三类：核心GUI日志信息，模块GUI日志信息，后台日志信息（多为debug）
2. 前两种日志的主要目的是显示在界面上，同时对应的事件类型不同，gatewayName也不同（模块为AppName）
3. 第三种日志则主要为了便于debug，常规情况下无需显示

因此还是分开处理比较好。
