### ISSUE TITLE
主界面的 错误时间，委托时间目前只有时间，没有月，日，

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#106]
对于挂机时间比较长的，感觉加上月，日比较好。

**Comment by vnpy** [comment]
我个人建议是每天的交易结束后一定要重启，防止各种奇怪的问题。做夜盘的人建议下午收盘重启一次，早上开盘前再重启一次。长时间开着系统运行不是很安全。

**Comment by viponedream** [comment]
重启又会丢失一些变量等信息。
假如做日线的话，要怎么做方便？
还有目前的回测，建议加上胜率，盈亏比这些。

**Comment by vnpy** [comment]
胜率和盈亏比我记下来了，回头放进去

其实vn.py的CTA模块主要是为了日内交易设计的，日线这种比较慢的交易方式当时还真没考虑。。。

**Comment by vnpy** [comment]
已经添加。
