### ISSUE TITLE
天勤数据无法下载

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1060]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug

## 预期程序行为
我安装了天勤数据终端，然后 进入了 终端的rb1901的日K线图界面， 然后执行了 python downloadData.py，然后 cmd终端就一直停在 “开始下载合约数据”。

**Comment by vnpy** [comment]
天勤接口之前主要由天勤那边在帮忙维护，请联系他们看看吧
