### ISSUE TITLE
请问是否有模拟盘模块

### ISSUE THREAD

**Issue by kevinhuangwl** [vnpy/vnpy#1061]
我知道仿真交易也能起到类似模拟盘的作用。但仿真盘测的是角度与模拟盘毕竟不一样，我看文档没有发现模拟盘相关说明，目前若想做模拟盘的话请问有何变通手段？未来是否有计划开发一下模拟盘模块？

**Comment by vnpy** [comment]
目前暂无计划，建议使用simnow
