### ISSUE TITLE
安装1.9后无法启动

### ISSUE THREAD

**Issue by handsomehu** [vnpy/vnpy#1062]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9发行版或者dev branch 20180824（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
正常启动，安装没有报错。

## 实际程序行为
安装成功，但运行run.py出错
ImportError: No module named vnctpmd
pip show vnpy显示依然为1.8.0
1.8并没有卸载， 只是将目录重命名了一下。

## 重现步骤
启动报如下错误：
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by handsomehu** [comment]
anaconda下旧的vnpy目录重新命名后，重新安装可以用了。 不过pip show vnpy还是显示1.8

**Comment by cooooo** [comment]
先卸载旧版本，再安装新版本

**Comment by handsomehu** [comment]
如何卸载？unbuntu上有uninstall的脚本吗？

**Comment by handsomehu** [comment]
谢谢，解决了， pip uninstall vnpy就可以， 重新安装没有问题了，可以登录ctp了。
Thanks!
