### ISSUE TITLE
python3 版本中 workingStopOrderDict报错：RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by yangqie** [vnpy/vnpy#1066]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 3.6.5 64位
* vn.py版本: 如v1.9发行版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![vnpy1](https://user-images.githubusercontent.com/22360637/44648979-3bda5680-aa15-11e8-91ce-4eff968190c1.png)

**Comment by cooooo** [comment]
用py3之前了解一下py2到py3有哪些改变就知道怎么处理这个问题了

**Comment by vnpy** [comment]
已修复
