### ISSUE TITLE
回测速度

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#107]
现在的回测是单线程的，速度没那么理想。
记得有一个回测模式可以选服务器，客户模式的。好像是pyalgotrade

这样可以同时开几台电脑起来跑回测了。即使同台电脑，多开几个客户端也会把CPU用满。
速度直接翻几倍啊。

**Comment by vnpy** [comment]
回测的命令是可以采用multiprocessing的来跑多进程进行回测的，需要用户自己写几行启动多进程的配置代码，回头有时间我给加上吧。

**Comment by vnpy** [comment]
已解决
