### ISSUE TITLE
vnpy 1.9.0安装后VnTrader启动报错

### ISSUE THREAD

**Issue by kumapy** [vnpy/vnpy#1070]
## 环境

* 操作系统: 如Windows 7 64位
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0（下载日期2018.08.26）

## Issue类型
三选一：Question

## 预期程序行为
VnTrader正常启动

## 实际程序行为
VnTrader启动报错

## 重现步骤
双击VnTrader.bat一闪关闭，于是在cmd窗口下运行VnTrader.bat，信息拷贝如下：
C:\vnpy>cd C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\examples\VnTrader

C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\examples\VnTrader>VnTrader.bat

C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\examples\VnTrader>python run.py
C:\Anaconda2\lib\site-packages\vnpy\api\ib\__init__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    from vnpy.trader.app import (riskManager, ctaStrategy,
ImportError: cannot import name algoTrading

C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\examples\VnTrader>

**Comment by vnpy** [comment]
这里报错是因为algoTrading载入失败，请在C:\vnpy\examples\VnTrader目录下运行python run.py试试

**Comment by DingTobest** [comment]
这个问题我今天遇到了，发现是由于保留了1.8的包导致引入错误，删除Anaconda2\Lib\site-packages下多余的vnpy的包解决了这个问题
