### ISSUE TITLE
Mac build problem

### ISSUE THREAD

**Issue by yihuang** [vnpy/vnpy#1072]
## 环境

* 操作系统: macOS High Sierra
* Anaconda版本: Python3.7
* vn.py版本: HEAD

尝试在Mac上编译，遇到一些问题，一些编译路径的问题我自己都搞定了，目前遇到硬坎是 ``vnpy/api/ctp/ctpapi/x64_linux/libthosttraderapi.so`` 没有mac版本。

**Comment by vnpy** [comment]
1. MAC上无法使用CTP等接口 
2. 目前对Python 3的移植还在进行中，非开发者建议还是用2
