### ISSUE TITLE
windows下安装不成功

### ISSUE THREAD

**Issue by dengwen168** [vnpy/vnpy#1077]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 最新版

按官方的教程，双击运行C:\vnpy\vn.trader\vtMain.py，找不到vtMain.py这个文件，vn.trader这个文件夹也找不到。我的只有C:\vnpy\vnpy\trader  这样的文件夹。

执行example下的run.py，出现如下信息：
C:\vnpy\examples\VnTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    from vnpy.event import EventEngine
ImportError: No module named vnpy.event

请问怎么弄啊？谢谢。

**Comment by vnpy** [comment]
请根据[这里](https://github.com/vnpy/vnpy)的QuickStart来安装，www.vnpy.org网站已经较老，后续准备重新更新。
