### ISSUE TITLE
上海所 昨平仓位不足 （代码按照之前#801 解决方案修改后，还是出现今开仓位，报昨平仓位不足）

### ISSUE THREAD

**Issue by cyzwwszw** [vnpy/vnpy#1078]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.72

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

代码按照之前#801 解决方案修改后，还是出现今开仓位，报昨平仓位不足

![image](https://user-images.githubusercontent.com/3972297/44803989-a2689b80-abf2-11e8-9237-b23edf595c16.png)

"tdPenalty": ["IF", "IH", "IC"] 为默认

**Comment by cyzwwszw** [comment]
![default](https://user-images.githubusercontent.com/3972297/44804381-c4165280-abf3-11e8-97bb-1d462ad58895.PNG)

**Comment by vnpy** [comment]
夜盘开始前重启程序了么？

**Comment by nanoric** [comment]
我在学习algoTrading的时候也遇到了这个问题，看了一下代码，应该是没有调用convertOrderReq导致的。
查找了一下convertOrderReq的引用，发现只有CtaEngine和stAlgoEngine里面才会调用到这个函数。
问题应该就是出在这里了吧。

顺便问一下， @cyzwwszw  你的策略使用的是哪个app模块运行的呢？

**Comment by cyzwwszw** [comment]
这个问题，我在vtEngine  里面做了些判断convertOrderReq ，如果是上海交易所的，就重新设置了  self.mode， 后面交易就正常了

**Comment by cyzwwszw** [comment]
ctp 模块

**Comment by cyzwwszw** [comment]
@vnpy 问题在self.mode 不对

**Comment by vnpy** [comment]
1. simnow的今昨仓数据有问题，如果用的simnow出现上述情况正常
2. 需要提供具体执行时的日志记录了
