### ISSUE TITLE
请问vnpy如何投资组合回测？

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1079]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question
请问vnpy能投资组合回测吗？ 如何组合回测呢？

**Comment by cooooo** [comment]
参见vnpy\examples\CtaBacktesting\backtesting_portfolio.ipynb
