### ISSUE TITLE
策略界面在surface/win10高分辨率模式下显示不整齐

### ISSUE THREAD

**Issue by WeizhongDai** [vnpy/vnpy#108]
![image](https://cloud.githubusercontent.com/assets/1499519/16709470/31f3a1da-4644-11e6-89a3-0b728f208d0d.png)

**Comment by vnpy** [comment]
因为目前CTA模块的GUI组件里，这几个长条形QTableWidget的高度是写死的，所以分辨率不同可能导致些奇怪的问题，最简单的方案是自己改下代码里的高度了。

欢迎对PyQt开发更有经验的人提供动态调整高度的方案。
