### ISSUE TITLE
server-client调用算法交易闪退

### ISSUE THREAD

**Issue by longmumin** [vnpy/vnpy#1081]
## 环境

* 操作系统: 如Windows Server2008
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9.0

## Issue类型
Question

## 预期程序行为
Server-Client模式通过rpc模式启动算法交易服务，出现闪退，设置断点是画界面过程出现问题

## 实际程序行为
出现算法交易界面

## 重现步骤
在server.py文件加入
me.addApp(algoTrading)
通过client调用算法交易服务，出现算法交易界面闪退

是否无法通过rpc模式调用算法交易服务？

**Comment by vnpy** [comment]
目前无法实现，希望支持Server-Client模式的话，要对AlgoTrading的引擎和界面通讯做个解耦，这种情况不如直接使用AlgoEngine的RPC服务功能给外部程序做算法交易了
