### ISSUE TITLE
vn.crypto项目 - 阶段2

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#1082]
vn.crypto项目 - 阶段2的开发计划如下，预计将在v1.9.1中完成：

- [ ] API接口
    - [ ] 新接口
        - [ ] Bitstamp
        - [ ] Gemini
        - [x] OKEX期货
        - [ ] BitMax
        - [x] 火币新Websocket
    - [ ] 功能改进
        - [ ] 流控处理逻辑
        - [ ] 委托状态机
        - [ ] 统一各交易所的合约代码
- [ ] 算法交易
    - [ ] 算法
        - [ ] Volume Inline（成交量参与率）
- [x] 数据服务
    - [x] CryptoCompare数据服务（免费历史数据）
- [ ] 海龟策略
    - [x] 策略数据自动更新和运维管理
    - [x] 买卖信号生成系统
    - [x] 多标的回测框架
    - [ ] 和AlgoTrading模块对接的实盘交易功能
    - [ ] 基于数字货币市场的完整策略DEMO
- [ ] 管理功能
    - [ ] 针对数字货币的独立风控模块
    - [ ] 每日交易报表统计功能
- [ ] 文档
    - [ ] 数字货币接口特性说明
    - [x] AlgoTrading模块使用文档

**Comment by KobeZhao** [comment]
1. 最感兴趣的还是海龟，策略数据自动更新这个相当于每天自动更新指数数据，然后基于此生成信号，那么多标的回测框架是什么形式呢？难道是类似于ricequant这种的横截面回测

2. 每日报表这个我自己以前做了一个，也是蛮期待的

**Comment by eachout** [comment]
数字货币能不能提供跨交易所进行套利的Demo

**Comment by vnpy** [comment]
@KobeZhao 
1. 确实是需要用到一些横截面回测的设计，不错和zipline这种还是不太一样的
2. 报表功能愿意分享下的话欢迎发个PR，这块我第一次做没啥经验

@eachout 
1. 套利Demo我这边准备下
2. symbol统一已经加入计划

**Comment by vnpy** [comment]
@studynon 确实在计划中，后续将会将项目所有权移交过去

**Comment by vnpy** [comment]
2.0开了新的issue安排计划，关闭本issue
