### ISSUE TITLE
spread Trading

### ISSUE THREAD

**Issue by rhermit** [vnpy/vnpy#1083]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0（下载日期）

## Issue类型
三选一：Enhancement

## 重现步骤
http://www.vnpie.com/forum.php?mod=viewthread&tid=2824&extra=page%3D5

价差算法的顺序是随机的，
虽然也知道是d = OrderedDict()的问题， 自己水平有限，但没改过来，
还请帮忙更正

**Comment by rhermit** [comment]
我试了一下，没效果，应该不对，还请再次查看一下，谢谢！

**Comment by vnpy** [comment]
已完成，之前是倒序。

**Comment by rhermit** [comment]
价差行情和价差持仓的顺序是一样的都是倒序，
但是“价差算法”，显示的顺序还是混乱的，两三个价差可能会出现巧合，十几个一般就很明显了
我知道您改的地方也是“价差算法”，但是细节应该有些出入，麻烦再次确认一下，谢谢
我这照片传不上去，麻烦多加一些套利对应该很明显了

**Comment by rhermit** [comment]
![default](https://user-images.githubusercontent.com/37691055/50400698-a46af180-07c3-11e9-9dc0-d21251fa7abb.jpg)

**Comment by vnpy** [comment]
![demo](https://user-images.githubusercontent.com/11263900/50418791-6a076000-0868-11e9-9d80-8e18583cf562.JPG)

请检查下你是否更新了正确版本的代码
