### ISSUE TITLE
数字货币交易所连接时能否提供proxies入参

### ISSUE THREAD

**Issue by chenchensheng** [vnpy/vnpy#1085]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0

## Issue类型
Enhancement

## 预期程序行为
数字货币交易所rest api和websocket api连接时能提供proxies入参来设置http的代理端口吗
毕竟国内被墙了

**Comment by xldistance** [comment]
用香港云稳，代理的话随时可能掉线，数据质量没保障

**Comment by vnpy** [comment]
楼上正解
