### ISSUE TITLE
from vnpy.api.ctp import MdApi, TdApi, defineDict

### ISSUE THREAD

**Issue by Wc30** [vnpy/vnpy#1086]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by Wc30** [comment]
from vnpy.api.ctp import MdApi, TdApi, defineDict 出现这个问题

**Comment by luhongkai** [comment]
怎么没看到问题。

**Comment by Wc30** [comment]
MdApi和TdApi怎么找不到啊，我用的window10

**Comment by luhongkai** [comment]
看py版本。这个是2.7的，你3的没法读到他的dll

**Comment by Wc30** [comment]
能方便加个微信聊嘛？

**Comment by luhongkai** [comment]
不方便 上班事多。你去加vnpy群

**Comment by Wc30** [comment]
ok
