### ISSUE TITLE
[Enhancement]增加初始化状态

### ISSUE THREAD

**Issue by nanoric** [vnpy/vnpy#1088]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: v1.9.0

## Issue类型
三选一：Enhancement

连接gateway之后，DataEngine会开始自动从服务器拉取诸如资金、仓位、委托单等等信息。
可否增加一个或者多个状态表示这些信息是否拉取完成？

**Comment by vnpy** [comment]
可以增加，但因为不是通用需求，暂时不添加到框架中
