### ISSUE TITLE
CTP API封装的一个小问题

### ISSUE THREAD

**Issue by tfiasco** [vnpy/vnpy#109]
`vn.trader/ctpGateway/ctpGateway.py`文件，
`class CtpTdApi(TdApi)`的`onRspUserLogin(self, data, error, n, last)`方法，
登陆成功有一个`self.gateway.mdConnected = True`，
是不是应该为`self.gateway.tdConnected = True` ？

还有`class CtpMdApi(MdApi)`的`onRspUserLogout(self, data, error, n, last)`方法，
登出成功是`self.gateway.tdConnected = False`，
是不是应该是`self.gateway.mdConnected = False`？

**Comment by vnpy** [comment]
对的，这个问题之前有人提过，应该在dev里面已经修改掉了。
