### ISSUE TITLE
两个一般问题/疑问

### ISSUE THREAD

**Issue by w1dexa2p34** [vnpy/vnpy#1094]
由于不知是ubuntu升级还是anaconda升级的原因，我在conda install numpy=1.11.0后vnpy恢复正常。
我搜索了代码，在代码里没有明确找到安装语句。除了指定特定版本外，在安装过程中vnpy是怎么找安装依赖的呢？自己没有多少编程经验，不知道怎么google相关内容，希望有人指点一二。另外是不是加那个qq群好点？我的一点点经验是对这类群不报多少希望，有什么问题在github上说出来不是更好，方便更多人搜索。或者说把讨论问题写个简要wiki?  比如说在wiki上专门列出各个大版本所有依赖的version？

另外一个更为严重，每次vnpy版本更新和原有版本冲突。自己的代码和更新的代码会有混乱之处，比如我看到dev的环境换成了anaconda 5.1.0，自己真是担心自己能力有限遇到麻烦问题;再比如专注一些功能（比如期货），在有新版本的情况下自己怎么只更新自己的模块？我的理解是程序可以尽量解偶和，但是我觉得这是个（漫长的）过程，大家有什么好的经验呢？

**Comment by vnpy** [comment]
1. python所有的库依赖是通过包管理工具pip或者conda来自动实现的，一般用不着专门指定版本，v1.9来说直接使用Anaconda 5.2.0，安装几个三方库就行
2. 现在的CTA策略模块更新，基本都保持了较好的向后兼容性，2.0后的版本会通过核心和组件拆分的模式，轻量化实现比较好的解耦
