### ISSUE TITLE
WebTrader: 无法订阅，显示交易合约IC1802无法找到

### ISSUE THREAD

**Issue by yinchuandong** [vnpy/vnpy#1096]
## 环境

* 操作系统: Docker - Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9.0 master branch

## Issue类型
三选一：Question

## 预期程序行为
使用WebTrader 运行CTP, 能够连接上Maket服务器和Trading服务器。点击订阅之后，虽然界面显示订阅成功，但实际上并没有订阅上。此外，加载策略也是不成功。
![image](https://user-images.githubusercontent.com/3993196/45157919-030c5f80-b215-11e8-8972-ecf6f56fd5ab.png)

![image](https://user-images.githubusercontent.com/3993196/45157688-73ff4780-b214-11e8-882d-6bed530f09c4.png)

![image](https://user-images.githubusercontent.com/3993196/45157869-e96b1800-b214-11e8-98bc-d9d8c2a8c085.png)

**Comment by cooooo** [comment]
现在是9月，1802早没了，换个新的就好了
