### ISSUE TITLE
策略演示中列表中追 加最后一位这么写比较容易。

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1097]
t.ticks[:-1] = t.ticks[1:]  # 全部往前移一位  a[:-1] = a[1:]  [:-1] 表示从头开始到最后（不含最后一个），a[-1]表示最后一个。
 t.ticks[-1] = tick

**Comment by vnpy** [comment]
这是对什么地方代码的改进？

**Comment by viponedream** [comment]
记错了，老版本的才有这么写过。

**Comment by viponedream** [comment]
找到了
class ArrayManager(object):
      self.openArray[0:self.size-1] = self.openArray[1:self.size]
可以改为     self.openArray[:-1] = self.openArray[1:]
