### ISSUE TITLE
iceberg算法交易拒单问题

### ISSUE THREAD

**Issue by Mingyue-Zhang** [vnpy/vnpy#1100]
## 环境

* 操作系统: 如Windows server2008
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9

## Issue类型
Question

## 预期程序行为
iceberg算法输入参数：SR901 方向：多 数量：100 挂出数量：5 运行间隔：5
预期系统每隔5秒发单，“委托”一栏内出现相应委托信息，“委托状态”为“未成交”，“部分成交”等等

## 实际程序行为
每个委托都被“拒单”，错误信息：委托总量或委托总额有误

## 重现步骤

![image](https://user-images.githubusercontent.com/42638248/45201568-98a4ff00-b2a8-11e8-855a-ea23a08ccbf8.png)
![image](https://user-images.githubusercontent.com/42638248/45201594-b4a8a080-b2a8-11e8-8edd-ede78b24714c.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
CTP接口的委托数量没有强制转化为整数，dev分支已修复
