### ISSUE TITLE
价差模块展示信息错位

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1102]
## 环境

* 操作系统: 如Windows10
* Anaconda版本: 如Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: 如v1.9.0，最新版本

## Issue类型
三选一：Bug

## 预期程序行为
正常显示价差相关的信息

## 实际程序行为
信息错位

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/12572507/45255303-063f5100-b3b7-11e8-97e7-e6fe54ef4462.png)

**Comment by vnpy** [comment]
已修复
