### ISSUE TITLE
冰山算法提交委托异常

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1103]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: 1.9.0

## Issue类型
三选一：Bug

## 预期程序行为
冰山算法，可以正常提交委托

## 实际程序行为
委托失败，无数量信息。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/12572507/45255372-1f94cd00-b3b8-11e8-9209-8b7f04f10beb.png)

**Comment by vnpy** [comment]
已修复
