### ISSUE TITLE
class ArrayManager(object):

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1105]
里面有一个指标 SMA，似乎只是计算最后的平均值吗？
如果我要当前的3个月均值，跟半年前的3个月均值来比较，可以吗？
不是短均线，长均线来比较，同样是3个月的均线，只是当前跟半年前的来比较。可以吗

**Comment by viponedream** [comment]
一，重新看了一下这个类。class ArrayManager，似乎就是存放K线的库。既如此，不如弄成一个df表。功能也更强大。也兼容其它的做法。
二，导入历史数据中。使用了onBar,
        for bar in initData:
            self.onBar(bar)
从逻辑上来说，历史数据并不参与下单操作，只是为了充实K线，计算指标而已。
所以， 载入历史数据觉得只要单纯存入上面那个表，来计算指标就行。不要通过onbar, ontick。

**Comment by vnpy** [comment]
DataFrame对象的创建、销毁的开销很大，而且无法高效的动态增加数据，实盘中会严重拖慢速度，所以如非必要并不建议使用。
