### ISSUE TITLE
载入历史K线的天数 loadbar  days

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1107]
目前是单纯减去多少天的，如我历史数据为10天，放假好几天的话，就可能没剩多少天了。
感觉可以用读到的日期的数量来判断，数量不够再往前，一天凑齐 10天为止，而不是单纯减去10。

**Comment by cooooo** [comment]
setStartDate有一个initDays参数，可以试着设定

**Comment by vnpy** [comment]
更简单的方法是加载20天以上的数据就肯定够了，反正多点数据也只是初始化时多花几秒而已
