### ISSUE TITLE
VnTrader持仓界面在仓位归零是不会更新

### ISSUE THREAD

**Issue by tfiasco** [vnpy/vnpy#111]
![image](https://cloud.githubusercontent.com/assets/8169725/16797123/9cdb69de-4918-11e6-9174-bdebcbd8348a.png)

如上图，持仓界面显示当前持仓有1手白糖，1手螺纹，但是看成交记录，当天交易白糖和螺纹的结果应该是没有持仓。重启VnTrader之后持仓消失。

**Comment by vnpy** [comment]
这是个老的bug，新的dev版本已经修复了该问题。
