### ISSUE TITLE
bitmex 市价下单后报错

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#1110]
## 环境

* 操作系统: 如Windows 2012
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8
## Issue类型
三选一：Bug

## 预期程序行为
市价下单

## 实际程序行为
市价下单成功后（订单下成功），报错（）
  File "C:\Anaconda2\vnpy-1.8.1-or_test\vnpy\trader\vtEngine.py", line 953, in calculateFrozen
    frozenVolume = order.totalVolume - order.tradedVolume
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![bitmex](https://user-images.githubusercontent.com/7878171/45480245-25edc500-b77b-11e8-964d-a89236c9a3d8.png)

**Comment by linyaohui** [comment]
@nanoric  你好啊，市价下单不能有price那个字段我知道的，我也修改了代码的，我那个问题是，时间开单后，返回成交信息后，更新持仓信息时报错的

**Comment by nanoric** [comment]
你更新到1.9.0试一试吧。
我在1.9.0下是可以正常发单的，没法重现你的错误哦。

**Comment by vnpy** [comment]
似乎totalVolume的内容为None导致的，我来看下

**Comment by vnpy** [comment]
已从master分支合并PR#1123，并修复了totalVolume为None的问题
