### ISSUE TITLE
火币链接报错

### ISSUE THREAD

**Issue by terryxsq** [vnpy/vnpy#1111]
## 环境

* 操作系统: Windows 10，时区NZST
* Anaconda版本: Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: v1.9

## Issue类型
三选一：Bug

## 预期程序行为
没有报错

## 实际程序行为
报错：
![image](https://user-images.githubusercontent.com/3322642/45495849-3a0be380-b7c8-11e8-8d95-5eb5fcb8af58.png)

## 重现步骤
设置链接火币API以后，日志里面不停的报错。猜测是时区不对，我是+12时区，可能火币API只能接受时区是+8的timestamp。

**Comment by vnpy** [comment]
火币的时间确实和时区有关，请使用+8的北京时间
