### ISSUE TITLE
调用CtpGateway中mdApi或tdApi中的close方法，无法真正关闭连接

### ISSUE THREAD

**Issue by jed057** [vnpy/vnpy#1113]
## 环境

* 操作系统: Any
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.5 至今

## Issue类型
三选一：Bug

## 预期程序行为
调用CtpGateway中mdApi或tdApi中的close方法，期待交易服务器或行情服务器被正常断连，重新发起连接和登录等操作应成功。

## 实际程序行为
无法真正关闭连接。查阅API文档，貌似应该使用release方法而不是exit？将exit改为release后，在调用close方法后，可收到onFrontDisconnected()回调。重连也顺利成功。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
exit的作用，是安全销毁CTP的API对象，而非断开连接，直接用release可能导致API问题出现内存崩溃
