### ISSUE TITLE
ctaBacktesting：使用同样参数runOptimization结果与单独回测结果不一致

### ISSUE THREAD

**Issue by Nimloth1** [vnpy/vnpy#1114]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 5.6.1 Python 2.7 64位
* vn.py版本: v1.9

## Issue类型
三选一：Bug

## 预期程序行为
ctaBacktesting.py → 使用同样参数runOptimization结果应与单独backtesting的结果一致

## 实际程序行为
runOptimization的结果较单独backtesting的结果大的多

## 原因分析
runOptimization中使用的clearBacktestingResult()没有清空backtestingEngine.dailyResultDict
导致接下来在calculateDailyResult中 dailyResult.addTrade(trade)函数会反复向这个未被清空的dailyResultDict增加trade。
![image](https://user-images.githubusercontent.com/29222344/45587448-30a18900-b938-11e8-864e-8d17567d8830.png)

**Comment by vnpy** [comment]
尽快修复，谢谢

**Comment by linbozhong** [comment]
原来已经有这个issue了，我今天也刚刚发现。正想来反馈。

**Comment by vnpy** [comment]
已修复

**Comment by xldistance** [comment]
你现在回测和优化的结果一致了吗
