### ISSUE TITLE
模拟时候初始化天数是10天，是否至少需要10天才有开仓信号，还有回测每笔开平仓记录保存在哪里啊

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1117]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 初始化天数可以调整，但你必须有大于初始化天数的数据量，才能够正常回测
2. 每笔的交易记录在回测引擎的tradeDict中
