### ISSUE TITLE
策略发单后，死机，退出，重开。还能不能收到 ontrade?

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1118]
假如发单后死机了，在死机的过程，这个单子成交了。
等下我们再开策略，还能不能收到 ontrade? 或者重新启动策略之后才成交。

或者说，只要是我们策略的单子，下单，成交，不管死机，明天，一直都是能够跟踪到的状态。

**Comment by vnpy** [comment]
收不到，目前策略和委托之间的映射关系，只保存在CTA引擎内存中的，关闭后这个映射关系就没有了。

但是底层模块（MainEngine, DataEngine）可以会受到这笔推送。如果需要的话，可以自己扩展一个查询机制

**Comment by viponedream** [comment]
象这种数据，重要变量等能不能实时存进数据库？载入策略再重新读入？

**Comment by vnpy** [comment]
对于CTA策略来说，一般没有这种需求，CTA策略的特点意味着只要有历史数据和仓位记录，应该就能还原出退出前策略的运行状态。

如果确实是某些复杂类型的策略，可以自己在策略中调用数据库连接或者shelve等持久化工具来实现数据的持久化，但这更多属于个性化需求，无法在针对公共性需求的框架里提供了。

**Comment by lipan0722** [comment]
我也遇到了这个问题，主要是在夜盘下的单在日盘成交的情况。我的思路是当根据vtOrderID匹配不到策略的时候，我就会当前的orderStrategyDict中另外匹配一个策略，根据我的策略特点应该是可以匹配到唯一的一个策略。各位也可以尝试一下。
