### ISSUE TITLE
ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by 799964990** [vnpy/vnpy#1124]
## 环境

* 操作系统: macos
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7.13 |Anaconda 4.0.0 (x86_64)
* vn.py版本: Version: 1.9.0
 python run.py
Traceback (most recent call last):
File "run.py", line 28, in 
from vnpy.trader.gateway import (ctpGateway, ibGateway)
File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/init.py", line 5, in 
from .ctpGateway import CtpGateway
File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in 
from vnpy.api.ctp import MdApi, TdApi, defineDict
File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/api/ctp/init.py", line 4, in 
from .vnctpmd import MdApi
ImportError: No module named vnctpmd

进入vnpy/api/ctp目录，运行bash build.sh，build目录 下 找不到vnctpmd.so和vnctptd.so

**Comment by cooooo** [comment]
运行bash build.sh报错了吗？

**Comment by 799964990** [comment]
> 运行bash build.sh报错了吗？

sudo bash build.sh
Password:
~/LH/chinahadoop/vnpy-master/vnpy/api/ctp/build ~/LH/chinahadoop/vnpy-master/vnpy/api/ctp
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Under unix: 8
CMake Warning at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:577 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:83 (find_package)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:83 (find_package)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CTPAPI_MD_LIBRARY
    linked by target "vnctpmd" in directory /Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp
CTPAPI_TD_LIBRARY
    linked by target "vnctptd" in directory /Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp

-- Configuring incomplete, errors occurred!
See also "/Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".
☁  ctp

**Comment by cooooo** [comment]
not available for Boost version(all versions older than 1.33)

**Comment by 799964990** [comment]
直接 brew install boost 这个吗 还是
下面哪个
brew search boost
==> Formulae
boost                 boost-build           boost-python          boost-python@1.59     boost@1.57            boost@1.60
boost-bcp             boost-mpi             boost-python3         boost@1.55            boost@1.59

==> Casks
boostnote                 focus-booster             iboostup                  mongobooster              turbo-boost-switcher
☁  ~

**Comment by 799964990** [comment]
brew install boost 按装之后 
又运行
sudo bash build.sh
Password:
~/LH/chinahadoop/vnpy-master/vnpy/api/ctp/build ~/LH/chinahadoop/vnpy-master/vnpy/api/ctp
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Under unix: 8
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:83 (find_package)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CTPAPI_MD_LIBRARY
    linked by target "vnctpmd" in directory /Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp
CTPAPI_TD_LIBRARY
    linked by target "vnctptd" in directory /Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp

-- Configuring incomplete, errors occurred!
See also "/Users/fanren/LH/chinahadoop/vnpy-master/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".

**Comment by vnpy** [comment]
CTP的API不支持MACOS

**Comment by hello886** [comment]
mini的2个gateway好像也的注释到，和ctp互斥，否则也会报错ImportError: No module named vnctpmd
