### ISSUE TITLE
想请问下回测和模拟交易时候，策略变量序列怎么保存下来方便检查信号正确与否；还有vntrader需要每天开盘前自动重启吗

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1125]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 回测完成后，可以访问Backtesting.tradeDict来获取所有的逐笔成交信息，以及Backtesting.orderDict来获取所有的逐笔委托信息，在Jupyter Notebook中通过几行代码可以很方便的输出为CSV或者shelve数据，用于后续查询
2. 每天的交易时段结束后建议关闭程序（期货的话是下午收盘，夜盘可以不管），后续重启
