### ISSUE TITLE
CTA引擎初始化界面延迟更新

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1126]
## 环境

* 操作系统: ALL
* Anaconda版本: ALL
* vn.py版本: 最新版本

## Issue类型
三选一：Enhancement

## 预期程序行为
CTA引擎初始化结束时，CTA-UI界面 inited 立即更新为 True。

## 实际程序行为
延迟一分钟更新。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

应该增加立即更新界面的操作：
`  
    def initStrategy(self, name):
        """初始化策略"""
        if name in self.strategyDict:
            strategy = self.strategyDict[name]
            
            if not strategy.inited:
                self.callStrategyFunc(strategy, strategy.onInit)
                strategy.inited = True
                self.putStrategyEvent(name)      <----缺少立即刷新（刷新动作在策略中，漏掉了inited=True的刷新)
                
                self.loadSyncData(strategy)                             # 初始化完成后加载同步数据
                self.subscribeMarketData(strategy)                      # 加载同步数据后再订阅行情
            else:
                self.writeCtaLog(u'请勿重复初始化策略实例：%s' %name)
        else:
            self.writeCtaLog(u'策略实例不存在：%s' %name)        
`

**Comment by vnpy** [comment]
时间消耗在了策略初始化数据的加载和策略初始化计算的过程上

**Comment by ShellMount** [comment]
并不是。
需要立即： self.putStrategyEvent(name)

数据加载及初始化结束时，还是需要等一分钟，由onBar中的刷新来执行（onInit中的self.put并未生效，因为执行它的时候 self.inited = Flase），才会在GUI界面刷新策略相关的数据。

**Comment by ShellMount** [comment]
CTAENGINE中，先执行 onInit,
再执行的 strategy.inited = True
所以 onInit 中的 putEvent 不会生效。所以初始化结束时CTA-UI界面的 inited = Flase.
直到下一分钟 onBar 中 的 putEvent 被执行时，才会变化。

解决的办法是：
在引擎中 执行完初始化，设置 strategy.inited = True 后，
立即 执行一个刷新 事件： self.putStrategyEvent(name)

**Comment by vnpy** [comment]
看来确实值得调整下CtaTemplate模板的工作机制了
