### ISSUE TITLE
请问价差交易里，策略交易实现有计划吗

### ISSUE THREAD

**Issue by mailtostanley** [vnpy/vnpy#1127]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
请问对于策略套利功能，比如统计套利策略，在vnpy里用rpc实现，或者在现有的价差模块里实现，哪个更方便一些，现在有实现计划吗

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
统计套利类的策略，涉及到比价复杂的策略逻辑原理，建议可以自己在外部通过脚本来运行策略，然后通过算法交易组件AlgoTrading的RPC功能来调用vn.py的交易服务

**Comment by mailtostanley** [comment]
vnpy官方可以实现一个简单的价差套利参考一下吗，比如布林线套利？
