### ISSUE TITLE
ibgateway 增加

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#113]
似乎目前只适用于 tws，而不适合于 gateway

1，增加一个accountName
def sendOrder(self, orderReq):
order.m_account = self.accountName  # 加这个。使用 ibgateway经常发单时会提示，没有指定帐号
这个 accountName我是在回调味函数时赋值的。
    def updateAccountValue(self, key, value, currency, accountName):
        """更新账户数据"""
        # 仅逐个字段更新数据，这里对于没有currency的推送忽略
        if currency:
            name = '.'.join([accountName, currency])
            if not self.gateway.accountName:                        # 在这里赋值。
                self.gateway.accountName = accountName

2，主界面持仓，资金不显示。
可能是帐号不同。我的不显示。要下面增加一个。
    def managedAccounts(self, accountsList):
        """ generated source for method managedAccounts """
        if accountsList:                  # 在这里增加，原来是空的。
            name = accountsList
            # 请求账户数据主推更新
            self.gateway.connection.reqAccountUpdates(True, name)

**Comment by shaoupipi** [comment]
IB调用reqMktData()获得的tick数据不是固定周期的快照，只有reqRealTimeBars()才是固定周期的，对相关的策略算法实现有影响

**Comment by vnpy** [comment]
你是用的投资管理人账户吧？也就是一个母账户带多个子账户的？

**Comment by viponedream** [comment]
也不是，普通的帐户。
但是用 ibgateway就不能用。一定要带帐户名才行

**Comment by vnpy** [comment]
问题1对应的情景猜测可能是涉及到CTA管理人分配持仓到各个子账户的情况，目前不在vn.trader的设计范围内（和其他接口兼容难度太大），所以有需求的请自己修改吧。

问题2已经按照建议的方法做出了修改。

不好意思拖了挺久。
