### ISSUE TITLE
linux deepin系统下订阅CTP行情不成功

### ISSUE THREAD

**Issue by dofish** [vnpy/vnpy#1131]
## 环境

* 操作系统: deepin15.5
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8

## Issue类型
三选一：Question

## 实际程序行为
CTP行情订阅成功，但是没有返回行情数据

## 重现步骤
ctpGateway.py:
    def subscribe(self, subscribeReq):
        """订阅合约"""
        if self.loginStatus:
            a=self.subscribeMarketData(str(subscribeReq.symbol))
            print(str(subscribeReq.symbol),a)
        self.subscribedSymbols.add(subscribeReq)

增加了订阅返回输出：log为：
2018-09-24 15:05:36,285  INFO: CTP	行情服务器登录完成
('j1901', 0)
('j1901', 0)
('j1901', 0)

但是GUI没有显示行情
error id="NONE" value="0" prompt="CTP:正确"

后续不知道怎么查回调有没有触发

**Comment by dofish** [comment]
def onRtnDepthMarketData(self, data):
        """行情推送"""
        # 过滤尚未获取合约交易所时的行情推送
        symbol = data['InstrumentID']
        print(symbol,"data in")
        if symbol not in symbolExchangeDict:
            print("data lose")
            return

log显示有数据进来
('j1901', 'data in')
data lose
('j1901', 'data in')
data lose
('j1901', 'data in')
data lose

 # 过滤尚未获取合约交易所时的行情推送
这句是什么意思？？

**Comment by cooooo** [comment]
非交易时间

**Comment by dofish** [comment]
> 好的啊，欢迎

好的，我先初步整理下，你告诉我发哪里，我打包发上来。
