### ISSUE TITLE
自己创建策略notebook运行报错

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1134]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤
ImportError                               Traceback (most recent call last)
<ipython-input-2-10a3f1b18e69> in <module>()
      2 from __future__ import division
      3 from vnpy.trader.app.ctaStrategy.ctaBacktesting import BacktestingEngine
----> 4 from vnpy.trader.app.ctaStrategy.strategy.strategyStock import StockStrategy
      5 if __name__ == '__main__':
      6 

ImportError: No module named strategyStock

**Comment by vnpy** [comment]
请将strategyStock放到你的运行时目录下，然后直接

from strategyStock import StockStrategy
