### ISSUE TITLE
tradeDic记录策略变量序列报错

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1136]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

Traceback (most recent call last):
  File "dual_thrust.py", line 47, in <module>
    print 'TradeID: %s, Time: %s, Direction:%s, Price: %s, Volume: %s, LongEntry: %s' 
% (d['tradeID'],d['dt'],d['direction'],d['price'],d['volume'],d['longEntry'])
KeyError: 'longEntry'

**Comment by vnpy** [comment]
tradeDict中保存的是VtTradeData对象，具体的可用字段可以在vtObject.py中查看，没有longEntry字段
