### ISSUE TITLE
为什么日志系统设计成为单件且只有一个输出文件？

### ISSUE THREAD

**Issue by leodo** [vnpy/vnpy#1137]
日志系统目前设计为单件且只有一个输出文件
如果想独立记录交易日志、持仓日志、发出指令、策略日志怎么办
现在都记录在一个文件里

**Comment by vnpy** [comment]
可以根据需求创建多个LogEngine（位于vnpy/trader/vtEngine.py中），然后使用不同的LogEngine来记录日志就行
