### ISSUE TITLE
支持CTP双中心Fens模式

### ISSUE THREAD

**Issue by jed057** [vnpy/vnpy#1140]
## 环境

* 操作系统: All

## Issue类型
三选一：Enhancement

## 预期程序行为
部分期货公司已启用支持CTP双中心Fens模式

## 实际程序行为
VNPY不支持此模式

## 重现步骤
N/A

**Comment by vnpy** [comment]
请问下有什么具体的参考资料吗？

**Comment by jed057** [comment]
[guide to support fens in clients.docx](https://github.com/vnpy/vnpy/files/2431670/guide.to.support.fens.in.clients.docx)
![md](https://user-images.githubusercontent.com/7314522/46258927-79466e00-c504-11e8-82f1-1a9e760324e4.png)
![td](https://user-images.githubusercontent.com/7314522/46258929-79466e00-c504-11e8-8e5c-100b2c96858b.png)

**Comment by jed057** [comment]
FENS大概的说明请参加第一个docx文档，应该就是主要是支持RegisterFensUserInfo和RegisterNameServer这两个接口，然后按照上面example那样注册FENS和Name Server就可以了。支持FENS模式接入的期货公司会提供相应的FENS服务器地址和端口。

**Comment by vnpy** [comment]
收到，我先看下

**Comment by vnpy** [comment]
1. 目前vnpy.api.ctp中支持期权交易的CTP API版本并未提供FENS功能
2. 和若干期货公司交流后，均未要求客户使用该功能
因此暂不进行开发，有需要的请自行扩展。
