### ISSUE TITLE
ctaEngine中对于没有初始化的策略未做保护

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#1142]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

加载策略的时候，全部的策略都加载进了self.tickStrategyDict中
在processTickEvent时，直接从self.tickStrategyDict中读策略类推送tick信息，无论该类的inited和trading状态是否为true，都会收到tick信息。
当配置的策略里有两个策略是订阅相同的合约，只要一个有初始化（初始化就会订阅合约），那么另一个策略有没有初始化，都会收到tick信息
建议：
processTickEvent加入判断：inited为true时才推送

**Comment by vnpy** [comment]
已修改
