### ISSUE TITLE
send_order 错误，麻烦绑我看下哪里错了谢谢

### ISSUE THREAD

**Issue by moukunok** [vnpy/vnpy#1143]
mybuy = send_order(1,"eosusdt",buy-limit,price=5.5)
print(mybuy)

Traceback (most recent call last):
  File "C:/Users/huobi/实验代码.py", line 6, in <module>
    mybuy = send_order(1,"eosusdt",buy-limit,price=5.5)
NameError: name 'buy' is not defined

**Comment by vnpy** [comment]
以上代码和vn.py无关
