### ISSUE TITLE
按模板编写策略出错

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1144]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![_20180930230936](https://user-images.githubusercontent.com/43107743/46259044-0a6a1480-c506-11e8-8b43-45b19e59c1b7.png)

**Comment by xldistance** [comment]
先在def __init__(self, ctaEngine, setting):里面定义个self.closeArray = np.zeros(self.bufferSize)   # K线收盘价的数组

**Comment by wkpzwy** [comment]
谢谢你的解答。。。想请问下怎么把cmd运行的print显示结果保存下来

**Comment by vnpy** [comment]
可以直接在cmd中选定后回车，就会复制选中的内容。
