### ISSUE TITLE
想请问下1：回测double_ma均线策略时候，5,10日均线值等变量序列保存在哪里:2；日志系统的输出文件位置在哪里，就是temp吗

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1145]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
\vnpy\trader\temp

**Comment by wkpzwy** [comment]
谢谢。。那均线变量序列怎么保存呢

**Comment by xldistance** [comment]
要保存干嘛，策略直接调用不就可以了

**Comment by vnpy** [comment]
均线变量的序列是没有保存的，每次调用ArrayManager.ma方法时会重新计算，如果需要访问每次计算的序列数据，可以采用

ay = am.ma(20, array=True)

来获得
