### ISSUE TITLE
ctaEngine.py里面定义的self.stopOrderDict[stopOrderID]除了保存stopoder之外看不出有什么实际用途吧

### ISSUE THREAD

**Issue by silent494529371** [vnpy/vnpy#1148]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
主要就是保存StopOrder用于回测完成后的数据分析
