### ISSUE TITLE
bitfinex API 错误

### ISSUE THREAD

**Issue by ling93** [vnpy/vnpy#1149]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: 如v1.9.0

## Issue类型
三选一：Bug

## 预期程序行为
运行时提示No Module named queue
把import 代码修改为from Queue import * 后运行又提示'module ' object has no attribute 'create_connection'

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/33561869/46513691-6b8a4300-c88c-11e8-9e01-02d454b04b8d.png)
![image](https://user-images.githubusercontent.com/33561869/46513703-75ac4180-c88c-11e8-86d0-0f034fdd5e61.png)

**Comment by jasonjfxu** [comment]
安装future库， pip install future

**Comment by vnpy** [comment]
请确保你安装的是websocket-client
