### ISSUE TITLE
trade data float type only show 4 bit

### ISSUE THREAD

**Issue by NoodlesYang** [vnpy/vnpy#1156]
## 环境

* 操作系统: mac
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 64位
* vn.py版本: 如v1.9

## Issue类型
三选一：Bug/

## 预期程序行为
* 行情窗口的数据可以显示8位小数。

## 实际程序行为
* 行情窗口的数据只能4为小数。

## 重现步骤

![image](https://user-images.githubusercontent.com/10631739/46599659-75c17100-cb1a-11e8-81f7-d1e4fe7de1d3.png)

**Comment by vnpy** [comment]
VT_setting.json里有个decimals配置，改这个到8就行
