### ISSUE TITLE
self.sell() 一直开做空仓单

### ISSUE THREAD

**Issue by fangsidian** [vnpy/vnpy#1163]
## 环境

* 操作系统: Ubuntu 16.04 on Docker
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9.0

## Issue类型
三选一：Question

## 预期程序行为
螺纹钢 rb1901
self.buy -> 开多1手
self.sell -> 平多1手

## 实际程序行为
螺纹钢 rb1901
self.buy -> 开多1手
self.sell -> 实际一直在开开空1手 相当于执行了short

VT_Setting.json 中添加了tdPenalty 螺纹钢 rb1901， 不知是否和这个问题有关联？

**Comment by xldistance** [comment]
一直发self.sell应该是你的mongodb数据库里面有多单，而账户上没有多单（手动平了），所以一直发平仓指令

**Comment by fangsidian** [comment]
If the contact is settled on penalty list, then no sell will be triggered on the same. 
Solution: remove your contact from penalty list.

**Comment by starliuhao** [comment]
问下楼主怎么解决这个问题的，我也遇到了
