### ISSUE TITLE
vnpy 重构

### ISSUE THREAD

**Issue by nanoric** [vnpy/vnpy#1166]
下面是对vnpy重构的一些想法和建议：
- [x] VtObject：
    - [x] 删减不需要的字段。
    - [x] 用@property减少创建VtObject所需的工作
    - [x] 使用辅助函数或者__init__帮助创建VtObject----同样是减少创建VtObject所需的工作
    - [x] ID存储改为对象引用：例如从一个已经完成的VtOrderReqeust最好能直接引用到VtOrderData，从VtOrderData最好也能直接引用到VtTradeData。而不需要通过orderId，tradeId之类的东西进行重新索引。
- [x] constant & text 
    - [x] constant使用object或者Enum替代：便于查询，减少出错机会。
    - [x] 取消对constant的翻译。
- [x] 按层次划分文件结构：最好能让人一眼就知道自己想要找的东西在哪儿。

**Comment by xldistance** [comment]
希望VNPY早日对接跨期套利，跨交易所套利，嘿嘿

**Comment by Gwill** [comment]
当前的翻译和常量确实很不好用，过度设计了一点

**Comment by Gwill** [comment]
对于各个 VtObject 类型，可以使用  https://docs.python.org/3/library/dataclasses.html 来实现

**Comment by aQuaYi** [comment]
vnpy 会不会考虑换一种语言编写，比如 Go 或者 Rust？

**Comment by vnpy** [comment]
2.0中以上提议基本都已经采纳实施：
1. vnpy/trader/object.py中的数据结构通过dataclass来实现
2. 删除了基础数据结构中的冗余字段，比如date, time等
3. 对于常用的撤单请求CancelRequest，可以直接通过OrderData的辅助函数来创建
4. 索引依旧需要，这是为了保证每个组件收到的数据推送流的完整性
5. 因为enum到GUI渲染需要额外转化开销，constant依旧采用int和str实现
6. 所有GUI相关文件放到每个应用的ui目录下，程序可以根据是否开了图形功能决定是否要加载

**Comment by Gwill** [comment]
@vnpy 看了一下当前 v2.0-DEV 分支的文件组织，感觉 event 文件夹里的相关逻辑不需要单独放出来，放在在 trader/event.py 就好

或者，trader 目录下的相关模块直接放到上一个目录层级
