### ISSUE TITLE
IB接口香港证券交易所代码有误，部分代码不能正确获取交易所信息

### ISSUE THREAD

**Issue by sun0x00** [vnpy/vnpy#1167]
## 环境

* 操作系统: ALL
* Anaconda版本: ALL
* vn.py版本: 1.9

## Issue类型
Bug

## 描述
1. ibGateway.py第48行，香港证券交易所的IB代码应为SEHK

2. 代码中部分 contract.exchange 不能得到正确的交易所信息，例如在回调方法updatePortfolio中，获取到的交易所信息为空，使用contract.primaryExch可正确获取。但此问题涉及到IB的SMART智能路由问题，待验证，此问题是我在持有港交所股票仓位时发现。

**Comment by vnpy** [comment]
1. 已完成修改
2. 暂时不确定怎么弄
