### ISSUE TITLE
多交易账户登录怎么做？

### ISSUE THREAD

**Issue by yjxxin** [vnpy/vnpy#1168]
想要实现多交易账户同时登录，能不能提供一个思路，主界面要不要进行更改，比如可以从账户A切换到账户B

**Comment by fangsidian** [comment]
CtaTrading 应该没有这个问题 ， 程序化可以启动多个实例。   界面没有研究过

**Comment by vnpy** [comment]
在VnTrader目录下复制几个ctpGateway，然后gatewayName命名为CTP1/CTP2/CTP3，在run.py中一起加载就行了

**Comment by vnpy** [comment]
1. 对的，放在多个json里
2. 不用，接口名CTP1、CTP2等就标识了每个账户了

**Comment by yjxxin** [comment]
1. CtpGateway类实际上已提供了非常好的接口封装，简单说，一个该类的实例即为一个账户，所以这里面的改动并不多（其他交易接口由于没有用到所以没有试，但相信大同小异）
    a) 修改构造函数接口，增加一个参数以区分要实例化的接口是行情账户接口还是交易账户接口，若是前者，只需创建mdAPI，否则mdAPI和tdAPI都需要创建（原因很简单，我们的多账户系统只需要针对交易部分，而行情部分完全是统一的，当然如果要统一对待也可以，多点开销而已）

2. 相应的，定义一个数据结构（如list）来存储账户，如行情账户1个和交易账户若干，每个账户的信息，如地址、账号、密码、brokerID等，可进一步定义第二层数据结构（如dict）来存放。定义好以后可将其存于文件（如有安全性顾虑可考虑以加密方式存储而在登录时动态解密等设计）；

3. 在mainEngine的initGateway方法中读取上述定义的数据结构（或从文件中读取），遍历并通过addGateway方法依次实例化ctp gateway，最终存储于该类的一个字典中（如self.gatewayDict）

4. 连接行情服务器时可以直接调用mainEngine中的connect方法，但mainEngine中需要定义另一个方法来实现仅连接交易服务器的功能。当然事实上也可以通过修改connect方法的接口来达到同样的目的。此外，关于account、position的轮询方式我根据自己的需求做了一些微调，这不是重点就不叙述了。
您好，我想问一下，如果我以上面这种方法做多账户登录可不可以，还是要做一些其他方面的修改，谢谢！
