### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by 4ever911** [vnpy/vnpy#117]
1.对于程序创建的一些文件路径, 是不是可以统一用一个类来管理, 目前在使用中有一些问题.
    a) linux用//, 用\\在我的ubunt上报错 
    b) tdconnection和mdconnection 创建失败, 需要手动先创建好, 并且要可写
    c) os.getcwd 程序运行时没问题, 可是如果我用IDE调试, 比如ATOM, 返回的不是程序路径,而是当前活动项目的路径
    如果用一个统一的接口来管理会更好.

2. 我最近看了几套开源的 Back Testing代码, 发现一个后起之秀,  BackTrader 做得很棒! 不过唯一的问题是, 这个项目作者才开始做不久, 很多东西还在陆续添加. 但是就目前的功能和文档的完善程度以及作者的代码质量看, 个人觉得比 ZipLine, AlgoTrader之流不知道高到哪儿去了. :)   策略部分可以借鉴一下这个项目.
     http://www.backtrader.com/

感谢无私奉献这么好的代码框架, 持续关注中.

**Comment by vnpy** [comment]
兼容性确实是一个比较麻烦的问题：
a. 你用的ubuntu是哪个版本？目前master里的我在16.04上测试过没问题
b. 这个目录在程序里有代码是可以自动创建的，不过可能需要比较高的权限？
c. IDE方面，我个人建议用WingIDE，很多烦恼和痛苦都不会有了

统一接口是个不错的思路，随着整个程序慢慢稳定下来可以往这个方向修改。

backtradre我看看，谢谢。

**Comment by 4ever911** [comment]
我用的16.04， 这几个问题大部分都是跟写权限有关， 比如 我用git clone 取下来是read only，包括文件夹的写权限也不够。 不过这也不算是个问题， 我可以手动来修改权限。

程序创建的文件， 可以统一放在一个目录好管理， 比如目前有 .con 临时文件， 有 contract对应的文件， 有配置的json文件， 都是散落在不同的地方。

另外一个小问题就是每个gateway编译脚本里面有做 ln 命令操作， 如果不在本地编译，通常都会找不到.so 文件。 我看网上有一些问这个问题的， 提示找不到 xxx.so

**Comment by snake3342** [comment]
路径分隔符最好都改成os.sep，会根据不同平台选择。

**Comment by vnpy** [comment]
目录地址问题已解决
