### ISSUE TITLE
如何实现对手价交易？

### ISSUE THREAD

**Issue by fangsidian** [vnpy/vnpy#1172]
## 环境

* 操作系统:Ubuntu 16.04 on docker
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0

## Issue类型
三选一：Question

## 实际程序行为
vnpy是否支持对手价发单？ 如果不支持的话该如何自己实现？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
在CtaTemplate的onTick回调函数里，收到tick推送后记录当前的bidPrice1, askPrice1，后面发单以此价格发就行

**Comment by fangsidian** [comment]
非常感谢！
