### ISSUE TITLE
CTP GATEWAY 未记录成交金额(turnover)字段

### ISSUE THREAD

**Issue by immrb** [vnpy/vnpy#1173]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9

## Issue类型
Enhancement

## 预期程序行为
获取并记录成交金额（turnover）字段

## 实际程序行为
没有成交金额（turnover）字段

**Comment by cooooo** [comment]
自己增加这个字段就好
