### ISSUE TITLE
CTP交易服务器连接成功但合约代码查询接口不存在

### ISSUE THREAD

**Issue by anchen1011** [vnpy/vnpy#1174]
## 环境
完全按照《Ubuntu环境安装》Wiki 安装
* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 62位
* vn.py版本: v1.9发行版

## Issue类型
Bug

## 预期程序行为
VnTrader CTP输入合约代码回车查询应显示行情

## 实际程序行为
<img width="777" alt="screen shot 2018-10-17 at 14 26 07" src="https://user-images.githubusercontent.com/22991557/47066808-d8e98c80-d219-11e8-9f36-4c622dd2fef3.png">
查询 MA706 和 IF1706 皆显示接口不存在

## 重现步骤
连接 CTP 后行情、交易服务器都连接成功
SimNow 密码更改过
查询合约代码还是结构不存在...

**Comment by vnpy** [comment]
今年是2018年，IF1706早就过期了，用IF1811
