### ISSUE TITLE
阿里云安装出现问题

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1175]
![_20181017205522](https://user-images.githubusercontent.com/43107743/47087609-07ce2580-d24f-11e8-8a44-d4edd02368c6.png)
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
网络问题，请自行翻墙
