### ISSUE TITLE
如何实现2秒钟内无法成交撤单重发

### ISSUE THREAD

**Issue by fangsidian** [vnpy/vnpy#1177]
## 环境

* 操作系统:Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0

## Issue类型
Question

请问如何实现以下逻辑
1 按对手价发单
2 2秒之内没有成交就撤单
3 立即按最新的对手价重新发单

**Comment by xldistance** [comment]
1.多开按对手价发单，self.buy(tick.askPrice1,self.open_pos)
2.未成交两秒撤单可以拿tick.datetime和order.datetime相减做比较，order.datetime需要自己去ctpgateway加
3.def onOrder(self,order):
    self.order = order

   if tick.datetime-order.datetime>2:
        if not self.order:
            pass
        elif self.order['satus'] == '未成交' (还有方向判断)：
            self.cancleAll()
            XXXXXXXX

**Comment by fangsidian** [comment]
基本明白

第3步骤
if tick.datetime-order.datetime>2:
if not self.order:
pass
elif self.order['satus'] == '未成交' (还有方向判断)：
self.cancleAll()
XXXXXXXX


这一段应该是放在onTick里面对吧？
