### ISSUE TITLE
安装mongodb出错

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1178]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![_20181018095140](https://user-images.githubusercontent.com/43107743/47126504-7517a000-d2bb-11e8-8b1d-3703503e2f61.png)

**Comment by joans321** [comment]
在 docker 里面不需要 sudo 命令， 直接 apt-get update 即可

**Comment by wkpzwy** [comment]
apt-get install mongodb
还是不行啊。。。

**Comment by joans321** [comment]
错误日志呢？

**Comment by wkpzwy** [comment]
command not found

**Comment by joans321** [comment]
你 Docker 跑的系统不对， docker 运行参考一下这个文档 [VNPY GUI Docker](https://github.com/vnpy/vnpy/blob/dev/docker/gui/README.md)

**Comment by wkpzwy** [comment]
参考教程vnpy安装没有这一步啊

**Comment by wkpzwy** [comment]
谢谢你的解答啊。。。

**Comment by wkpzwy** [comment]
[root@iZwz959be577h6bi0s6hsjZ ~]# docker build . -t vnpy
-bash: docker: command not found

**Comment by joans321** [comment]
能问下你用什么系统吗？

**Comment by wkpzwy** [comment]
Aliyun Linux

**Comment by joans321** [comment]
Linux 什么发行版的， ubuntu 还是 centos ？

**Comment by wkpzwy** [comment]
应该是centos吧

**Comment by joans321** [comment]
那就对了，系统不对。 能换成 ubuntu 16.04 系统吗？

能换系统的话，再参考官方文档操作即可。
如果不能换的话参考 [Docker Install](https://docs.docker.com/install/linux/docker-ce/centos/) 安装 Docker，安装完之后参考上面文档操作。

**Comment by wkpzwy** [comment]
![_20181018130656](https://user-images.githubusercontent.com/43107743/47132510-cb460c80-d2d6-11e8-835b-8aaaa6421310.png)

**Comment by wkpzwy** [comment]
我选的是这个啊。。Aliyun Linux，可以更换吗，，还有要翻墙的话地区是选香港等地吗

**Comment by vnpy** [comment]
新手请不要折腾Linux，老老实实用Windows
