### ISSUE TITLE
okexFutureGateway' has no attribute 'gatewayName'

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1179]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 3.6 64位
* vn.py版本: 如v1.9发行版

## Issue类型
三选一：Bug

## 预期程序行为
![qq 20181018104341](https://user-images.githubusercontent.com/29418474/47128245-0d655300-d2c3-11e8-830d-f0fd76fcb409.png)

**Comment by vnpy** [comment]
该接口还在开发中，请等待其完成

**Comment by xldistance** [comment]
期待中
