### ISSUE TITLE
strategyAtrRsi策略改进

### ISSUE THREAD

**Issue by hitblackjack** [vnpy/vnpy#118]
只把平仓停止单放到orderList里，不把开仓限价单放进去。开仓信号产生的限价单没能成交而不及时删除的话，可能会失去时效性而变得非常不利。改为pos>0或pos<0之后，每次平仓开单数量都是1手，如果平不干净的话，pos!=0会造成没法根据信号开新单，会错过很多机会吧

**Comment by vnpy** [comment]
这个策略代码只是用于参考，针对实盘交易的一些边际情况处理建议用户自己弄明白后做进去，vn.py项目里的策略都做的比较模糊一些，鼓励大家自己去研究。

**Comment by hitblackjack** [comment]
好的，策略开发多进程优化参数之类的，目前还是pyalgotrade做的比较好啊，期待一起改进
