### ISSUE TITLE
CryptoTrader:"QHeaderView' Object has no attribute 'setSectionResizeMode

### ISSUE THREAD

**Issue by osmondliu95** [vnpy/vnpy#1181]
## 环境

* 操作系统:Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 64
* vn.py版本: 1.9

## Issue类型
Bug

## 重现步骤
![screenshot from 2018-10-18 19-22-51](https://user-images.githubusercontent.com/44262236/47151384-29d9ad80-d30c-11e8-958c-f013a0a0b96c.png)

**Comment by vnpy** [comment]
请升级到Anaconda 5.2.0
