### ISSUE TITLE
想给CTP接口的onorder增加order日期该怎么改

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1183]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 3.6 64位
* vn.py版本: v1.9

## Issue类型
三选一：Question

## 预期程序行为
![qq 20181019090852](https://user-images.githubusercontent.com/29418474/47192295-f08e5580-d37e-11e8-8fd3-d9ac01dcfee7.png)

vtobject里面也增加了orderDate和dateTime，还要改哪里呢

**Comment by vnpy** [comment]
搜索ctpGateway.py里，所有有

order = VtOrderData()

的地方，并进行修改

**Comment by xldistance** [comment]
多谢解答
