### ISSUE TITLE
Q How to get Bitmex funding rate in XBT perpetual contract via vnpy API?

### ISSUE THREAD

**Issue by czonghui** [vnpy/vnpy#1185]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2 Python 2.7 32位
* vn.py版本: 1.9.0+ dev branch 20181014（下载日期）

## Issue类型
三选一：Question

## Q
How to get Bitmex funding rate in XBT perpetual contract via vnpy API?

**Comment by vnpy** [comment]
This function is not supported in VnTrader.

But you can use vnpy/api/rest (RestClient) to get funding data folling instructions on this path:
https://www.bitmex.com/api/explorer/#/Funding
