### ISSUE TITLE
CTP 开盘第一根分钟线问题

### ISSUE THREAD

**Issue by fangsidian** [vnpy/vnpy#1189]
## Issue类型
Question

CTP 接口 的onBar  我的理解如下

day 1 ->  22:59 - 23:00: 当日最后一根收盘K线在23:00
day 2 -> 9:00-9:01：  第二天第一根k线在9:01

奇怪的现象：目前在onBar() 中捕捉了8:59和9:00 的K线
1) 这是为什么？
2) 8:59和9:00 两个K线代表了那些时间段？
3）实盘中最后一根k线23:00 能不能被vnpy捕捉到 (还是说需要自己去手动合成)？

**Comment by bigdig** [comment]
集合竟价形成的K线

**Comment by fangsidian** [comment]
竞价的tick  是不是应该剔除掉？ if tick.volume==0 return ?

**Comment by vnpy** [comment]
这个剔除与否更多是个人选择了，可以自己在DataRecorder里加上时间过滤逻辑，或者每天收盘后的清洗脚本中加上该逻辑。

**Comment by fangsidian** [comment]
我目前遇到这个问题： 我从joinquant上下载螺纹钢的历史数据并且计算了MA60/120等数据，  但发现CTP实盘的数据在收盘和开盘的时候与joinquant的历史数据不太一样

比如
比如 螺纹钢 在vnpy 的CTP 合成(分钟bar)以后是 
13：58分 时是 3900元
13：59分 时是 3910元

而joinquant历史显示的是
13：59分 时是 3900元
14：00分 时是 3910元

别人同样的问题在这里可以找到
https://www.joinquant.com/post/10868?tag=algorithm

如此一来会导致ma数据不一直 实盘表现完全是两个世界
 我在想vnpy的分钟bar如何与joinquant的历史行情保持一致？
