### ISSUE TITLE
上期所自动推来的onTrade

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#119]
一连接，就会自动把onTrade推来，即使策略还没有开仓。
在考虑，要不要忽略这些信息？只有自己的策略开仓后才来处理。

比如说，开仓后，关机重启，
一开它就自动推送这些过来。应该忽略比较好吧。
即 onTrade 只响应自己开仓的。而不是上期所自动推来的

**Comment by vnpy** [comment]
对的，正常情况下，建议启动系统后，等所有的数据推送完成，再打开相应的策略模块，防止策略模块收到无关的信息。
