### ISSUE TITLE
策略疑问

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1190]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
我想实盘交易股指，但是需要每天更新的数据是行业或成分股数据，需要在模板哪里怎么添加程序语句。。。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by fangsidian** [comment]
看一下 tushare, 要求不高的话直接放到Strategy里面去就行

**Comment by vnpy** [comment]
可以使用tushare获取数据，但我只能说实盘没人这么干的
