### ISSUE TITLE
1.9版本 币安连接账户那列没显示，报400错误

### ISSUE THREAD

**Issue by samyulam2016** [vnpy/vnpy#1192]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

配好代理，之后运行example文件夹下面CryptoTrader文件夹下面的run.py~ 行情有显示，但是用户数据那一块没有数据，打印出来报400错误
![image](https://user-images.githubusercontent.com/21355452/47405367-c6c09e80-d783-11e8-9950-ce5e334e4ea0.png)

**Comment by samyulam2016** [comment]
发生错误，错误代码:400，错误信息:Timestamp for this request was 1000ms ahead of the server's time.

**Comment by vnpy** [comment]
请将你的电脑本地时间和windows对时服务器时间做一次同步，这个是偏差太大造成的
