### ISSUE TITLE
点击相关交易品种代码，enter 订阅详情报接口不存在问题

### ISSUE THREAD

**Issue by Zephyen** [vnpy/vnpy#1197]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Question

## 预期程序行为

这里我们使用的甲醇合约是MA705，则在交易组件中输入交易合约代码MA705后按回车，则会自动订阅该合约的行情。CTP接口在用户订阅某个合约的行情后，会立即推送当前交易日内最新的一条Tick数据，系统收到后会自动在右侧的行情组件中显示出接收到的该合约实时行情数据，如最新价、买一价量和卖一价量等。

## 实际程序行为
回车以后日志出现
--------------
2018-10-27 22:45:54,437  INFO: MAIN_ENGINE      接口不存在：
---------------
## 重现步骤
输入RB1901 点击enter 
针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/8236466/47605547-96565a00-da3a-11e8-945e-96be8124a59d.png)

**Comment by Zephyen** [comment]
输入MA901也不可以。

**Comment by vnpy** [comment]
1. 请先连接登录CTP接口
2. 你的talib没装，策略模块加载失败

**Comment by Zephyen** [comment]
安装了Ta-lib,并且链接上CTP接口，然后输入RB1901 和IF1901均显示接口不存在

![image](https://user-images.githubusercontent.com/8236466/47654504-ec0b3d80-dbc5-11e8-9561-d9b74b138ece.png)

**Comment by cooooo** [comment]
注意正确填写合约代码

**Comment by Zephyen** [comment]
@cooooo RB1901 是不正确的代码么？

**Comment by vnpy** [comment]
rb1901，看看交易所的合约代码文档
