### ISSUE TITLE
请问vnpy如何对代码和策略进行加密?

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1198]
## 环境

* 操作系统: 如Windows 10
*Anaconda 4.0.0 
* vn.py版本v1.8
## Issue类型
三选一：Question
请问如何把vnpy代码加密，或者说把策略加密，不被反编译

**Comment by vnpy** [comment]
简单的方案可以尝试用nuitka或者cython，将核心的类或者函数编译成二进制的pyd文件，基本就很难破解或者反编译了。

更进一步就是用C++重写核心逻辑，用boost.python封装，虽然麻烦点但是还能带来性能极大的提升。
