### ISSUE TITLE
CTP tick 数据问题

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#1199]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev

## Issue类型
三选一：Bug

## 实际程序行为

从南华期货 CTP 股票期权仿真账号获取的合约 Tick 数据

![image](https://user-images.githubusercontent.com/692980/47693275-024fe280-dc34-11e8-9651-e435e8e188b4.png)

其中很多数据缺失，缺失2-5档报价和量，还缺失 date 字段（这个会导致 datarecorder 奔溃）

请问这是什么原因呢？

通过汇点客户端连接这些数据都是正常的

**Comment by Gwill** [comment]
@vnpy

**Comment by Gwill** [comment]
明白原因了

**Comment by yjxxin** [comment]
请问您这些数据是怎么得来的？
