### ISSUE TITLE
请问vnpy和第三的量化软件mc、tb、文华财经哪个会更快

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1200]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question

请问vnpy和第三的量化软件mc、tb、文华财经哪个会更快

**Comment by vnpy** [comment]
1. 从驱动架构看：vn.py采用事件驱动，收到tick后系统自身的处理逻辑很少，用户写的策略可以立即反应（执行交易、或者去自行合成K线）
2. 从软件功能看：vn.py没有自带K线显示（高CPU开销）和数据采集入库功能（高IO开销），只有交易相关的业务
3. 从编程语言看：MC/TB/文华都是使用自身的脚本，vn.py基于Python，两者可能差别不大，如果会用Cython将核心逻辑转化到C级别，则vn.py优势巨大了

但是以上功能也都有相应的代价：没有K线、需要运维数据服务、需要使用配置文件等等。

以上言论只是作者的个人观点，仅供参考。

**Comment by jxhuliqun138** [comment]
Cython将核心逻辑转化到C级别   指的仅仅是转化 strategy里面的策略吗， 还是说还有其他地方需要转化的？
