### ISSUE TITLE
请问如何往vnpy里面添加一个api接口？

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1204]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question

我这边想添加一个股票交易的 某证券api接口， 请问有相应的demo或者文档可以参考一下吗？  或则你们这边可以帮忙添加支持一下吗？ 可以考虑有偿。

**Comment by jingwei1982** [comment]
正好在做这个事情，而且已经完成了一部分，现在可以在vntrader中显示账户，持仓，下单，成交，可撤，每秒推送一次这些信息。

你需要做的是添加一个券商gateway ，可以直接复制一个ctpgateway，然后function name不用改，直接这里功能实现，然后在主程序里add gateway 就可以了。

**Comment by jxhuliqun138** [comment]
我们目前想加入 络町 平台的券商接口， 所以还需要在vnpy/api 目录下加入自己的 dll库之类的， 但是我们团队没有很擅长C++的人， 请问你们能否帮忙添加一下

**Comment by vnpy** [comment]
如果是用户量比较多的柜台或者交易系统，可以发相关资料到vn.py@foxmail.com，官方团队会加到开发计划里。

如果是比较小众的平台，就请自行联系社区里的开发者付费开发吧。

**Comment by jingwei1982** [comment]
>           我们目前想加入 络町 平台的券商接口， 所以还需要在vnpy/api 目录下加入自己的 dll库之类的， 但是我们团队没有很擅长C++的人， 请问你们能否帮忙添加一下


这个其实不难的，就是python使用ctypes调用dll就可以了，现在券商接口大家大都这么写的，我现在用的通达信的dll.
