### ISSUE TITLE
双均线vnpy demo和自己写的回测 交易次数 不一致，，短期长期窗口都是10和60

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1208]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![1](https://user-images.githubusercontent.com/43107743/47949907-70bed880-df85-11e8-89a7-b67400957f8a.png)
![2](https://user-images.githubusercontent.com/43107743/47949911-79afaa00-df85-11e8-9755-7ab6896ce029.png)

**Comment by wkpzwy** [comment]
麻烦楼主不要那么快关闭问题，，看看有没更多人解答。。跪谢

**Comment by vnpy** [comment]
计算函数不一样，ArrayManager用的是talib的SMA函数计算的，你这里用的Python的mean函数计算

**Comment by wkpzwy** [comment]
我在vnpy编写的例外一个策略回测 交易次数也不一致，，，我怀疑是不是哪个地方逻辑没对

self.highArray[0:1200]=self.highArray[1:1201]
        self.lowArray[0:1200]=self.lowArray[1:1201]
        self.highArray[-1]=bar.high
        self.lowArray[-1]=bar.low
        if not am.inited:
            return
        
        # 计算阻力支撑rsrs指标
        self.high=self.highArray[1:1201]
        self.low=self.lowArray[1:1201]
        self.beta=sts.linregress(self.low,self.high)
        self.rsrs=self.beta[0]
        if self.rsrs>1.01 and self.pos==0:
        	self.buy(bar.close,1)
        elif self.rsrs<0.996 and self.pos>0:
        	self.sell(bar.close,1)

**Comment by LeoK987** [comment]
最好能把不一致的结果贴来看看，或许有人会找到问题

**Comment by vnpy** [comment]
无后续更新，关闭问题
