### ISSUE TITLE
tushare下载数据报错

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1209]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![_20181103163135](https://user-images.githubusercontent.com/43107743/47949949-fd699680-df85-11e8-9e31-eed83b8d2bb0.png)

**Comment by vnpy** [comment]
请问你下载时的日期范围是？

**Comment by vnpy** [comment]
检查后以上错误因为Tushare连接的数据源缺失数据，请检查。
