### ISSUE TITLE
dataRecorder引擎的浮点数精度问题

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#121]
数据引擎存储的bidPrice1、upperLimit等等报价，经常出现类似6471.400000000001，2145.0000000000005这种由于float计算精度导致的错误数据，在做tick级别回测的时候无法正常测试。

考虑使用round（）或者decimal模块截取3位小数，由于每个tick都需要处理多个字段，不知道这两种方式哪种效率更高些呢？或者有更好的处理方式？
tks

**Comment by snake3342** [comment]
用python你就别计较效率，只要结果没错就行。

**Comment by freeitaly** [comment]
担心一个tick的时间处理有延迟，
测试了下，round（）处理tick的时间可以忽略，插入mongo要0.001秒，这都没问题。
不过要处理原来存储的tick就难实现了，一个tick 0.1～0.5秒，可以放弃了

**Comment by vnpy** [comment]
大部分情况应该都是内置库会快一些，具体测下吧。我的建议倒是检查下你的算法，多这种小数点后很多位的情况，不应该导致算法逻辑出错吧。
