### ISSUE TITLE
VNPY连接BITMEX，可以看到行情，但是策略里面ontick接收不到订阅的行情

### ISSUE THREAD

**Issue by goiden** [vnpy/vnpy#1210]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/22718480/47975497-0757da80-e0e9-11e8-8f84-13ff284a58d7.png)
可以在vntrader界面看到行情，但是运行策略无交易，策略里在ontick和onbar里加了日志显示

**Comment by goiden** [comment]
我是用的CCXT接口连接的bitmex

**Comment by vnpy** [comment]
CCXT接口只针对货币做了适配和测试，其他接口未必一致，建议直接用BITMEX接口
