### ISSUE TITLE
在ctpGateway.py中，没看到对VtGateway类中onTick（）方法的调用？

### ISSUE THREAD

**Issue by wyxr** [vnpy/vnpy#1211]
如果不调用onTick（）方法，那么怎么推送市场实时行情到_queue呢，这样不就不能把数据传送到策略了吗？事实上，我debug的时候有数据，是在哪里调用的onTick（）方法，烦请提示一下。

**Comment by Gwill** [comment]
https://github.com/vnpy/vnpy/blob/dev/vnpy/trader/gateway/ctpGateway/ctpGateway.py#L406

**Comment by vnpy** [comment]
onRtnDepthMarketData这个是回调函数，由CTP的底层API自动调用的

**Comment by wyxr** [comment]
感谢
