### ISSUE TITLE
uiBasicWidget.py，这算是bug么？

### ISSUE THREAD

**Issue by dotcream** [vnpy/vnpy#122]
同一个class定义两次，这算是bug么？

########################################################################
class NameCell(QtGui.QTableWidgetItem):
    """用来显示合约中文名的单元格"""

    #----------------------------------------------------------------------
    def __init__(self, text=None, mainEngine=None):
        """Constructor"""
        super(NameCell, self).__init__()
        self.data = None
        if text:
            self.setContent(text)
    
    #----------------------------------------------------------------------
    def setContent(self, text):
        """设置内容"""
        self.setText(text)

########################################################################
class NameCell(QtGui.QTableWidgetItem):
    """用来显示合约中文的单元格"""

    #----------------------------------------------------------------------
    def __init__(self, text=None, mainEngine=None):
        """Constructor"""
        super(NameCell, self).__init__()
        
        self.mainEngine = mainEngine
        self.data = None
        
        if text:
            self.setContent(text)
        
    #----------------------------------------------------------------------
    def setContent(self, text):
        """设置内容"""
        if self.mainEngine:
            # 首先尝试正常获取合约对象
            contract = self.mainEngine.getContract(text)
            
            # 如果能读取合约信息
            if contract:
                self.setText(contract.name)

**Comment by vnpy** [comment]
不小心把测试代码同步上来了，今晚清理掉，多谢。
