### ISSUE TITLE
macOS 碰到 ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by oiwio** [vnpy/vnpy#1220]
## 环境

* 操作系统: macOS 10.13.6
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.0

按照流程安装成功，运行python run_simple.py 完全没问题，弹窗正常且终端无报错，但是想尝试ctp接口，把run_simple.py中from vnpy.trader.gateway import ctpGateway 注释取消，出现这个经常出现的报错
    from .vnctpmd import MdApi
ImportError: No module named vnctpmd

我把之前在其他系统中尝试的方式试了下，比如更新boost，运行./install.sh等，还是没有用，希望能得到解答，感谢耐心看完！

**Comment by oiwio** [comment]
原来是。。ctp不支持macOS。。。打扰了，这个issue可以关了。。。

**Comment by mintisan** [comment]
同路过，同打扰。。。
