### ISSUE TITLE
Propose to add a time filter in drEngine

### ISSUE THREAD

**Issue by LeoK987** [vnpy/vnpy#1221]
Similar time filters as in cleanData can be added in drEngine to filter out troubling tick data from being recorded.  Since the engine is intended for various markets, a template of such filters can be provided as a json file which allows the user to modify or disable/enable.  The json file can probably be something like:
```
{
    "working": true,
    "MORNING_START": "09:00:00"
    "MORNING_REST": "10:15:00"
    "MORNING_RESTART": "10:30:00"
    "MORNING_END": "11:30:00"
    "AFTERNOON_START": "13:30:00"
    "AFTERNOON_END": "15:00:00"
    "NIGHT_START": "21:00:00"
    "NIGHT_END": "02:30:00)
}
```
Any comments and thoughts?  I'd be happy to prepare a PR.

**Comment by LeoK987** [comment]
Furthermore, I think it's better to have one of such json file for each market.  And a default template of such file should be provided for every major markets.

**Comment by vnpy** [comment]
以上过滤规则仅适合中国期货市场，vn.py还同时应用在大量其他市场。
