### ISSUE TITLE
模拟盘发生重复平仓

### ISSUE THREAD

**Issue by KilimanjaroFreeman** [vnpy/vnpy#1228]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9
## Issue类型
三选一：Bug

## 预期程序行为
我的策略发了一次平仓的信号，原来pos是2，结果程序发生了两次平仓pos变成的-2，我把成交记录保存到数据库

## 实际程序行为
![i96w zbhku n r ecj2x](https://user-images.githubusercontent.com/32793518/48323649-1fd77000-e668-11e8-9c70-7b8c1b4b6737.png)
![p by jbpu   @@eae2asc9fh0](https://user-images.githubusercontent.com/32793518/48323650-1fd77000-e668-11e8-9eee-7cd4baea9904.png)
![tc h dy0ldf2_ b u nltbc](https://user-images.githubusercontent.com/32793518/48323651-20700680-e668-11e8-9660-c4e163c3a3a0.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

@vnpy

**Comment by KilimanjaroFreeman** [comment]
我看了一下，因该是策略不知道为什么执行了两次的平仓命令，因为其他策略也持有i1901所以卖出能够执行，但是这就使得所有策略的仓位之和与实际的仓位不同，因该是哪里有bug
@vnpy-dev-01 
@vnpy

**Comment by vnpy** [comment]
请提供下你策略的平仓函数调用代码，以及相关的日志输出

**Comment by KilimanjaroFreeman** [comment]
> 
> 
> 请提供下你策略的平仓函数调用代码，以及相关的日志输出


[vt_20181109.log](https://github.com/vnpy/vnpy/files/2574217/vt_20181109.log)

[strategy.txt](https://github.com/vnpy/vnpy/files/2574222/strategy.txt)
这是策略和日志

**Comment by LeoK987** [comment]
可能是下面的几个条件会相互影响，比如在第一个条件执行完，self.posk可能已变为>0了。
```
        if self.pos == 0 and self.trading:
            if open_long:
                self.buy(bar.close + self.slip, self.fixedSize, False)
            elif open_short:
                self.short(bar.close - self.slip, self.fixedSize, False)
        
        # µ±«∞≥÷”–∂‡Õ∑Õ∑¥Á
        if self.pos > 0 and self.trading:
            #∏¸–¬÷π”Ø÷πÀœﬂ
            self.stop_line = max(self.stop_price, self.mid_line)
            self.sell(self.stop_line, abs(self.pos), True)
            
        # µ±«∞≥÷”–ø’Õ∑Õ∑¥Á
        if self.pos < 0 and self.trading:
            #∏¸–¬÷π”Ø÷πÀœﬂ
            self.stop_line = min(self.stop_price, self.mid_line)
            self.cover(self.stop_line, abs(self.pos), True)

```

**Comment by KilimanjaroFreeman** [comment]
> 可能是下面的几个条件会相互影响，比如在第一个条件执行完，self.pos可能已变为>0了。
> 
> ```
>         if self.pos == 0 and self.trading:
>             if open_long:
>                 self.buy(bar.close + self.slip, self.fixedSize, False)
>             elif open_short:
>                 self.short(bar.close - self.slip, self.fixedSize, False)
>         
>         # µ±«∞≥÷”–∂‡Õ∑Õ∑¥Á
>         if self.pos > 0 and self.trading:
>             #∏¸–¬÷π”Ø÷πÀœﬂ
>             self.stop_line = max(self.stop_price, self.mid_line)
>             self.sell(self.stop_line, abs(self.pos), True)
>             
>         # µ±«∞≥÷”–ø’Õ∑Õ∑¥Á
>         if self.pos < 0 and self.trading:
>             #∏¸–¬÷π”Ø÷πÀœﬂ
>             self.stop_line = min(self.stop_price, self.mid_line)
>             self.cover(self.stop_line, abs(self.pos), True)
> ```
不会的，你可以看日志，第一个条件是上午触发的，而平仓是夜盘发生的，两个不是一起发生

**Comment by vnpy** [comment]
当CTA引擎收到新的TICK后，会先检查停止单是否被触发，如果触发立即发出委托，然后再将TICK推送给策略执行逻辑。

从日志中看，23:13:51的这个TICK可能价格跳动较大，立即触发了你的停止单。所以进入你的策略onTick函数时，cancelAll函数已经无法起到撤单的作用，而进入后续self.pos > 0执行时，你的stop_line价格又是高于当前价格的，导致这个新的停止单委托也被立即触发，所以就出现了同时发出两笔委托的情况。

解决办法就是下达停止单后，要跟踪onStopOrder确认该停止单被触发或者撤销后，才能下达新的停止单，而不是简单使用cancelAll函数后就不管了。

CancelAll函数是为了常规分钟级别以上的策略逻辑提供的简化函数，需要细粒度挂撤单操作的策略请自行跟踪委托状态，并管理好相应的策略状态机。

**Comment by KilimanjaroFreeman** [comment]
谢谢，明白了
