### ISSUE TITLE
linux下CtpTdApi.connect崩溃问题

### ISSUE THREAD

**Issue by q-zhu** [vnpy/vnpy#1229]
## 环境

* 操作系统: centos-7 64位
* Anaconda版本: 如Anaconda 4.3.8 Python 3.6 64位
* vn.py版本: v1.9

## Issue类型
三选一：Question

ctp接口已编译成功，vnpy也已成功安装。如果第一次调用CtpTdApi connect没有连接成功，那么第二次调用connect函数时，函数内self.init()崩溃。

![vnpy1](https://user-images.githubusercontent.com/19502174/48323465-4a74f900-e667-11e8-8001-335d487fca5f.png)

![vnpy2](https://user-images.githubusercontent.com/19502174/48323610-f0286800-e667-11e8-9445-38081b64543c.png)

使用gdb查看core dump时发现，错误来自于MdApi::processRspUserLogout(Task) ()里的any_cast失败。

![vnpy3](https://user-images.githubusercontent.com/19502174/48323656-2b2a9b80-e668-11e8-9014-09470a1ba26b.png)

请问有人碰到过我这种情况吗？或是对vnctpmd.so服务器上的debug有什么好的建议吗？

谢谢！

**Comment by vnpy** [comment]
Python 3目前不在官方支持计划中，自行编译请注意unicode字符串编码的强制转换
