### ISSUE TITLE
VNIB 封装的 TagValue 类存在Bug，对IB order的AlgoParams设置直接崩溃，

### ISSUE THREAD

**Issue by richardWei93** [vnpy/vnpy#1238]
## 环境
Windows 7
* Anaconda Python 2.7 32位
* vn.py版本: 最新版

## Issue类型
BUG:
VNIB 封装的 TagValue 类存在Bug，
相关代码:order.algoParams.append(TagValue("maxPctVol", 0.25))

## 预期程序行为
预期程序可以顺利完成改行代码

## 实际程序行为
崩溃，system exit with error (1)

## 重现步骤

对发给IB的order进行algo strategy的设置，到TagValue相关的代码都会报错

        # order.algoStrategy = "ArrivalPx"
        # # order.algoParams.append(TagValue("maxPctVol", 0.25))
        # # order.algoParams.append(TagValue("riskAversion", "Aggressive"))
        # # order.algoParams.append(TagValue("startTime", startTime))
        # # order.algoParams.append(TagValue("endTime", endTime))
        # # order.algoParams.append(TagValue("forceCompletion",int(1)))
        # # order.algoParams.append(TagValue("allowPastEndTime",int(1)))
        # # order.algoParams.append(TagValue("monetaryValue", 100000))

**Comment by richardWei93** [comment]
经查，AlgoParams 是Order类的附属TagValueList，但这种Order类的附属List的Boost封装都存在问题，对这种List进行append都会导致crash，我尝试着自己编译C++ Lib到pyd文件，安装了Boosts等，编译出来的文件只有921kb，与项目中1mb+的pyd文件有大小差距，而且无法使用，因此我卡在这里没有办法了。

如果方便手头有这个project的话，能不能帮忙把这个Order附属类List问题修复了再编译出一个lib上传即可解决，感谢！

**Comment by vnpy** [comment]
2.0的ib_gateway已经改为使用官方的Python API来实现，可以使用所有的功能了
