### ISSUE TITLE
websocket工作不正常

### ISSUE THREAD

**Issue by chan99e** [vnpy/vnpy#1239]
## 环境

* 操作系统: 如Windows 10
* Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev 

## Issue类型
Bug:

1. ok现货接口，不支持最新版的websocket-client
2. dev版本中，okexfGateway.py中，for d in data['holding'][0]:遍历有误

**Comment by eachout** [comment]
修改下vnpy/api/okex/vnokex.py
    
`    def inflate(self, data):
        decompress = zlib.decompressobj(
            -zlib.MAX_WBITS  # see above
        )
        inflated = decompress.decompress(data)
        inflated += decompress.flush()
        return inflated

    #----------------------------------------------------------------------
    def readData(self, evt):
        """解码推送收到的数据"""
        data = json.loads(self.inflate(evt))
        return data
`

**Comment by vnpy** [comment]
已修复
