### ISSUE TITLE
BITMEX数据插入错误，MONGODB不支持"."开头的合约

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#1240]
## 环境
* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
正常插入数据

## 实际程序行为
Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\trader\app\dataRecorder\drEngine.py", line 50, in run
    self.mainEngine.dbInsert(dbName, collectionName, d)
  File "C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\trader\vtEngine.py", line 217, in dbInsert
    collection = db[collectionName]
  File "C:\Anaconda2\lib\site-packages\pymongo\database.py", line 259, in __getitem__
    return Collection(self, name)
  File "C:\Anaconda2\lib\site-packages\pymongo\collection.py", line 170, in __init__
    "or end with '.': %r" % name)
InvalidName: collection names must not start or end with '.': u'.XBTUSDPI.BITMEX'

## 重现步骤
连接bitmex，下载数据

**Comment by UtorYeung** [comment]
自己改写了一下MainEngine.dbInsert修改合约名的方法:
    def dbInsert(self, dbName, collectionName, d):
        """向MongoDB中插入数据，d是具体数据"""
        if self.dbClient:
            #------------
            # newfunc ∵BITMEX的合约名有'.'开头的，MONGODB对此不支持，而原函数并没有对此进行处理。∴新函数对此进行了处理
            if dbName.startswith("."):
                dbName = dbName.replace(".", "_", 1)
            if collectionName.startswith("."):
                collectionName = collectionName.replace(".", "_", 1)
            if dbName.endswith("."):
                dbName = dbName[:-1] + "_"
            if collectionName.endswith("."):
                collectionName = collectionName[:-1] + "_"
            #------------
            db = self.dbClient[dbName]
            collection = db[collectionName]
            collection.insert_one(d)
        else:
            self.writeLog(text.DATA_INSERT_FAILED)

但有个问题不知道怎么处理：
1.这样修改完之后，需要在其他一切跟mongodb相关的函数都进行同样的修改，以确保不会新增bug
2.在MainEngine上修改，其他模块如果不通过MainEngine连接MongoDB的话，那么读取时会出错

所以这种情况下，在哪个模块修改会比较安全？MainEngine？DataEngine？或者其他模块？

**Comment by vnpy** [comment]
1. BITMEX以.开头的合约为指数行情报价，而非可交易合约，不是vn.py关注的重点，
2. 这些指数行情的价值很低，因为BITMEX的合约标的是多家交易所的价格合成指数，而它自己的这些.开头的合约行情速度肯定是显著慢于用户自行根据其他交易所实时行情合成的指数价格

综上，vn.py的代码就不修改以兼容这些指数了，另外我个人也不建议去收集这类数据，意义不大。
