### ISSUE TITLE
Propose to enhance BarGenerator

### ISSUE THREAD

**Issue by LeoK987** [vnpy/vnpy#1241]
I amended the BarGenerator class, so it now:

- has one single tick handler, 
- supports multiple onTick callbacks based on request,
- has one single 1-minute-bar generator,
- supports multiple onBar callbacks based on request,
- supports multiple x-minute-bars with callbacks based on request,
- has one single day-bar generator based on request,
- supports multiple onDayBar callbacks based on request

Would that be of interest if I added it to a PR?

**Comment by czonghui** [comment]
yes, pls do so

**Comment by viponedream** [comment]
very good.
but not it  is based on 1 minute bar. 
can you change it to different unit?  the default is minute, also can be  specify to  second.
it can generate x-minute-bar or x-second-bar
can you do that?

**Comment by LeoK987** [comment]
OK, second bars can be added

**Comment by LeoK987** [comment]
Made further amendments based on comments.  Now it:

- has one single tick handler,
- supports multiple onTick callbacks based on request,
- has one single 1-second-bar generator based on request,
- supports multiple onSecBar callbacks based on request,
- supports multiple x-second-bar generation based on request, xsec being limited by 3600,
- has one single x-second-bar generator for the each xsec,
- supports multiple callbacks within each x-second-bar based on request,
- has one single 1-minute-bar generator, being on by default but can be turned off based on request, 
- supports multiple onBar callbacks on the 1-minute-bar based on request,
- supports multiple x-minute-bar generation based on request,
- has one single x-minute-bar generator for the each xmin,
- supports multiple callbacks within each x-minute-bar based on request,
- has one single day-bar generator based on request,
- supports multiple onDayBar callbacks based on request,
- auto-updates all bars starting from onTick.

Will do some basic testing when market opens.  All further testing and feedback from the community are encouraged.

**Comment by viponedream** [comment]
it seems nice.   waiting for it

**Comment by hardyfarmer** [comment]
最近我也在比较vnpy data recorder记录下来的数据。发现和通达信还有TradeBlazer的不一样。通达信和TradeBlazer是完全吻合的，只是通达信时间戳会慢一分钟（eg.TB的data只会记录到14：59,通达信会有15：00这个bar，通达信15:00的bar和TB的14:59的bar的数据是完全一样的）然而当我比较vnpy data recorder记录下来的数据，OHLC有时候对不上，Volume也对不上。目前还不知道什么原因，在考虑是不是tick合成1min bar时有问题，一个tick被错误的划分到不一样的min bar造成不一样。

**Comment by hardyfarmer** [comment]
另外楼主能否考虑再加一个Hour Bar的generator？自己写了一个，但是合成起来的结果不正确。还在找原因。

**Comment by LeoK987** [comment]
@hardyfarmer， 谢谢你的信息。能上传几个例子吗？还有，请问你用的是这个新版的BarGenerator吗？

**Comment by hardyfarmer** [comment]
谢谢回复，我大概看了下。记录的差距不大，但是不准确。比如rb1901  2018/11/21 14：59的bar 用data recorder记录下来的O:3727,H:3727,L:3722,C:3725:Volume:23690.TB和通达信的数据为O:3726,H:3728,L:3722,C:3724:Volume:24080.我理解data recorder记录下来的15：00还有一个tick最后没有算到14：59里，但是TB和通达信的数据归到最后一分钟里了。这个可以解释Close不一样。但是Open和High为什么不一样呢。我又另外随便挑了一个分钟rb1901 2018/11/21 13：46，用data recorder记录下来的O:3699,H:3699,L:3694,C:3697:Volume:15010.TB和通达信的数据为O:3698,H:3699,L:3694,C:3697:Volume:15052.又是很细微的差别。所以我就在思考是不是有tick没有划归到对的minute bar。 BTW：我用的是V1.9

**Comment by hardyfarmer** [comment]
BTW:Is there anyway to contact you directly?

**Comment by LeoK987** [comment]
@hardyfarmer 再次感谢你的信息。不知差异是在每根线上都存在，还是只在个别线上？为便于理解，能否把某一天如下时间段来自三个软件的数据都上传来：14.50-15.00
如需单独联系我，gmail: cnbiz850

**Comment by LeoK987** [comment]
几个数据源的一分钟数据，rb1901：

TB：
2018/11/26 9:06,3587,3596,3586,3592,43750,1743576
2018/11/26 9:07,3592,3624,3592,3624,47654,1740032
2018/11/26 9:08,3625,3631,3619,3620,59436,1742486
2018/11/26 9:09,3620,3623,3617,3622,27474,1743048
2018/11/26 9:10,3622,3635,3621,3633,37230,1739662
2018/11/26 9:11,3633,3634,3626,3628,19502,1738240
2018/11/26 9:12,3627,3628,3615,3615,26422,1738174
2018/11/26 9:13,3617,3626,3616,3625,14048,1741450
2018/11/26 9:14,3625,3626,3619,3621,9950,1743620
2018/11/26 9:15,3621,3624,3621,3624,8516,1741976

通达信：
2018/11/26,907,3587,3596,3586,3592,43750,1743576,0
2018/11/26,908,3592,3624,3592,3624,47654,1740032,0
2018/11/26,909,3625,3631,3619,3620,59436,1742486,0
2018/11/26,910,3620,3623,3617,3622,27474,1743048,0
2018/11/26,911,3622,3635,3621,3633,37230,1739662,0
2018/11/26,912,3633,3634,3626,3628,19502,1738240,0
2018/11/26,913,3627,3628,3615,3615,26422,1738174,0
2018/11/26,914,3617,3626,3616,3625,14048,1741450,0
2018/11/26,915,3625,3626,3619,3621,9950,1743620,0
2018/11/26,916,3621,3624,3621,3624,8516,1741976,0

天勤：
2018/11/26-09:06:00.000000,3587,3596,3586,3592,43088,1743588
2018/11/26-09:07:00.000000,3592,3625,3592,3625,48590,1740288
2018/11/26-09:08:00.000000,3625,3631,3619,3620,58500,1742474
2018/11/26-09:09:00.000000,3620,3623,3617,3622,27824,1742832
2018/11/26-09:10:00.000000,3622,3635,3621,3633,37042,1739536
2018/11/26-09:11:00.000000,3633,3634,3626,3627,19368,1738222
2018/11/26-09:12:00.000000,3627,3628,3615,3617,26414,1738156
2018/11/26-09:13:00.000000,3617,3626,3616,3625,14054,1741482
2018/11/26-09:14:00.000000,3625,3626,3619,3621,9914,1743592
2018/11/26-09:15:00.000000,3621,3624,3621,3623,8514,1741956

vnpy：
rb1901,2018-11-26T09:06:00.000Z,20181126,9:06:00,3587,3596,3586,3592,43750,1743576
rb1901,2018-11-26T09:07:00.000Z,20181126,9:07:00,3592,3624,3592,3624,47654,1740032
rb1901,2018-11-26T09:08:00.000Z,20181126,9:08:00,3625,3631,3619,3620,59436,1742486
rb1901,2018-11-26T09:09:00.000Z,20181126,9:09:00,3620,3623,3617,3622,27870,1742832
rb1901,2018-11-26T09:10:00.000Z,20181126,9:10:00,3622,3635,3621,3633,36834,1739662
rb1901,2018-11-26T09:11:00.000Z,20181126,9:11:00,3633,3634,3626,3628,19502,1738240
rb1901,2018-11-26T09:12:00.000Z,20181126,9:12:00,3627,3628,3615,3615,26422,1738174
rb1901,2018-11-26T09:13:00.000Z,20181126,9:13:00,3617,3626,3616,3625,14048,1741450
rb1901,2018-11-26T09:14:00.000Z,20181126,9:14:00,3625,3626,3619,3621,9950,1743620
rb1901,2018-11-26T09:15:00.000Z,20181126,9:15:00,3621,3624,3621,3624,8516,1741976

**Comment by vnpy** [comment]
已关闭PR，相关原因请参考 #1252
