### ISSUE TITLE
提交femas多交易所和主柜台测试版本vnpyAPI请求

### ISSUE THREAD

**Issue by cpyzleo** [vnpy/vnpy#1242]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
Question

目前飞马已经推出多交易所版本，实盘已经运行很久。主柜台也测试运行一段时间。
对接飞马主柜台和多交易所的vnpy demo是否可以提交？

**Comment by vnpy** [comment]
欢迎提交PR

**Comment by vnpy** [comment]
无后续更新，关闭
