### ISSUE TITLE
CTa回测引擎中部分代码可进一步优化

### ISSUE THREAD

**Issue by vippere** [vnpy/vnpy#125]
#----------------------------------------------------------------------
def formatNumber(n):
        """格式化数字到字符串"""
        n = round(n, 2)         # 保留两位小数
        return format(n, ',')   # 加上千分符

这里是一个全局函数，但好像不是很符合PYTHON面向对象的写法，另外变量n和参数n重名，也容易引起混乱。

**Comment by vnpy** [comment]
已解决
