### ISSUE TITLE
策略疑问

### ISSUE THREAD

**Issue by wkpzwy** [vnpy/vnpy#1253]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

1：怎么记录每个策略单独盈亏记录
2：可以用现货指数作为信号生成器，交易期货吗
3：期权模拟交易希腊值未显示出来是怎么回事

**Comment by wkpzwy** [comment]
4：什么时候写个期权简单demo文档

**Comment by KilimanjaroFreeman** [comment]
可以自己每个策略的交易记录进行监控，改一改catTemple,然后就可以实现策略的实时监控了
![tim 20181120153029](https://user-images.githubusercontent.com/32793518/48757918-41c09a80-ecd9-11e8-9d04-b827b3387170.png)

**Comment by wkpzwy** [comment]
请问需要怎么改。。。可以加你微信交流下吗 13760251759

**Comment by vnpy** [comment]
1. 要记录每个策略的盈亏，可以直接在onTrade函数里，往硬盘上写入日志信息
2. CTA策略模块不支持，需要自行修改
3. 请检查是否配置了定价波动率曲线
4. v2.0将提供期权文档
