### ISSUE TITLE
调用futu api接口参数误传 

### ISSUE THREAD

**Issue by FutunnOpen** [vnpy/vnpy#1254]
## 环境

* 操作系统: 如Windows 7 
 

## Issue类型
三选一：Bug 

## 实际程序行为
调用futu api接口参数误传

## 重现步骤
+  futu api 的函数原型
    def deal_list_query(self, code="", trd_env=TrdEnv.REAL, acc_id=0, acc_index=0): 

 + futuGateway.py  的实现 qryTrade 调用代码如下
     code, data = self.tradeCtx.deal_list_query(self.env) 

    self.evn 被当作了code参数 ， 而trd_env参数却使用实际默认值 TrdEnv.REAL

**Comment by vnpy** [comment]
已修复，感谢。
