### ISSUE TITLE
bitmex的balance计算有误

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#1255]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
Bug
bitmex返回的availableMargin以及marginBalance不对
参考CCXT代码如下：

            account = {
                'free': balance['availableMargin'],
                'used': 0.0,
                'total': balance['marginBalance'],
            }
            if currency == 'BTC':
                account['free'] = account['free'] * 0.00000001
                account['total'] = account['total'] * 0.00000001
            account['used'] = account['total'] - account['free']

**Comment by vnpy** [comment]
CCXT接口使用的货币代码是BTC，因此需要对BitMEX返回的原始XBT数据做除法处理。

vn.py这边是直接使用的XBT，因此无需做转换。
