### ISSUE TITLE
okexfGateway.py的调用onQueryPosition()函数中data['holding'][0]为空的bug

### ISSUE THREAD

**Issue by zhouzhuofu** [vnpy/vnpy#1261]
https://github.com/vnpy/vnpy/blob/c3cb62db606eacb89d7408ec290a1def80d924f8/vnpy/trader/gateway/okexfGateway/okexfGateway.py#L391

账户没有持仓时，调用onQueryPosition()函数，data['holding']返回[]，直接执行for语句，会异常。
建议先增加判断data['holding'][0]，即  ”if data['holding'][0]:

**Comment by vnpy** [comment]
已增加对应判断，感谢。
