### ISSUE TITLE
Problem generating x-minute bars in BarGenerator

### ISSUE THREAD

**Issue by LeoK987** [vnpy/vnpy#1264]
The code relies on whether the current minute can evenly divide xmin (ie 15 % 5) to decide if the current x-min bar finishes.  This introduces a problem when the evenly divisible bar is missing.

Added patches in the newly proposed BarGenerator to fix this.  Similar patches were also added for x-second bars.

**Comment by vnpy** [comment]
框架中的组件主要服务于常规操作，不会为了个别少数的需求增加无谓的复杂性
