### ISSUE TITLE
MAIN_ENGINE接口不存在

### ISSUE THREAD

**Issue by kimmyww** [vnpy/vnpy#1265]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## 重现步骤

C:\vnpy\examples\VnTrader>python run.py
C:\Users\Kimbe\Anaconda2\lib\site-packages\qtpy\__init__.py:178: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
C:\Users\Kimbe\Anaconda2\lib\site-packages\vnpy\api\ib\__init__.py:4: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from .vnib import *
2018-11-28 20:23:01,845  INFO: MAIN_ENGINE      接口不存在：

**Comment by kimmyww** [comment]
解决了，谢谢

**Comment by cnydpl** [comment]
> 解决了，谢谢

我也遇到 这个问题，请问怎么解决的啊？谢谢了

**Comment by xycfree** [comment]
我也遇到 这个问题，请问怎么解决的啊？谢谢了
