### ISSUE TITLE
webtrader 无法连接到后端socket服务器

### ISSUE THREAD

**Issue by cly0514** [vnpy/vnpy#1267]
## 环境

* 操作系统: 如Windows 10 pro 1809 子系统 ubuntu 18.04 
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9.1正式版（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
webtrader能正常连接后端socket服务器，
打开浏览器，socket服务器连接：已连接，点击连接ctp，能正常连接上

## 实际程序行为
socket服务器连接：未连接
打开浏览器，socket服务器连接：未连接，点击连接ctp，连不上，日志什么都没有

1-29 14:58:24,384  INFO: 当前时间：2018-11-29 14:58:24.384404
2018-11-29 14:58:24,384  INFO: 当前处于交易时间段
2018-11-29 14:58:24,454  INFO: 启动交易服务器进程
2018-11-29 14:58:24,467  INFO: 服务器进程启动
2018-11-29 14:58:24,468  INFO: 事件引擎创建成功
2018-11-29 14:58:24,515  INFO: 启动WEB服务器进程
2018-11-29 14:58:24,596  INFO: 主引擎创建成功
2018-11-29 14:58:24,596  INFO: 服务器启动成功
127.0.0.1 - - [2018-11-29 14:58:35] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 214 0.001665
127.0.0.1 - - [2018-11-29 14:58:36] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 214 0.002431
127.0.0.1 - - [2018-11-29 14:58:39] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 214 0.000428
127.0.0.1 - - [2018-11-29 14:58:41] "GET //token?username=test&password=test HTTP/1.1" 200 178 0.013819
^C2018-11-29 14:59:14,586  INFO: 安全关闭进程

## 重现步骤

python run.py
打开浏览器，socket服务器连接：未连接，点击连接ctp，连不上，日志什么都没有

**Comment by Yaolinwang** [comment]
同样环境遇到了同样的问题

**Comment by 985153073** [comment]
这个问题什么时候可以解决

**Comment by yangrq1018** [comment]
同样, Ubuntu 18.04，localhost一直显示连接不上socket

**Comment by biggreyhairboy** [comment]
操作系统ubuntu16.04LTS，遇到的情况一模一样

**Comment by vnpy** [comment]
检查了代码，当时的开发是在windows下，网页服务端的一些库没有在ubuntu上测试，导致了不兼容。

WebTrader将在2.0里面彻底重写。
