### ISSUE TITLE
IB 的tick数据时间有问题

### ISSUE THREAD

**Issue by 4ever911** [vnpy/vnpy#127]
我看在tickprice函数里面解析价格时用到local time填充然后发送给ontick, 这里有一个逻辑问题。 如果本地时间和服务器有差别 （基本上肯定有差别）， 那么数据对齐上肯定有问题， 生成的k线数据会不正确。 

我看backtrader 用的  RTVolume 这个参数， 返回的tick数据包含服务器的时间戳。

**Comment by vnpy** [comment]
能更详细的解释下吗，或者把相关的信息网址贴一下。

**Comment by 4ever911** [comment]
大致的问题是：  大多数人的模型应该是这样，补全历史K线数据， 然后根据实时tick来生成Bar计算。

但是如果历史k线从服务器取，那么那部分k线时间用的是服务器时间对齐， 比如 一个5分钟连续k线数据可能这样  9:00:01-9:05:00, 9:05:01:-9:10:00....  09:55:01-10:00

10点程序上线，开始取tick数据， 然后生成bar，10:00:01-10:05:00  然后衔接上之前的历史数据， 看起来好像没问题。但是实际服务器时间和本地有差别， 我看了下大概要差几秒钟到延时， 那么我们取到的bar实际时间可能是 10:01:08 - 10: 05:08   多少会和回测模型有差别。

当然，如果历史数据也用的以前缓存下来的tick数据，相对来说，就如同把服务器上的k线数据整体移动几秒，重新生成k线。 个人觉得，多少可能会有一些影响。

https://www.interactivebrokers.com/en/software/api/apiguide/java/reqmktdata.htm

reqMktData函数有个参数 genericTicklist， 默认好像是用的空，系统会用211， 
我看Backrader代码里传递的233，服务器返回RTVolume数据

https://www.interactivebrokers.com/en/software/api/apiguide/tables/rtvolume.htm

RTVolume is one of the generic tick tags that can be requested as part of a market data request. RTVolume returns the following:

Last trade price
Last trade size
**Last trade time**                                                                                                <--- 服务器时间
Total volume
VWAP
Single trade flag - True indicates the trade was filled by a single market maker; False indicates multiple market-makers helped fill the trade
RTVolume is the API equivalent to opening the Time and Sales Window in Trader Workstation and viewing the updates in real time. To implement this, you must include 233 in the genericTicklist parameter in your market data request.

You will receive the RTVolume update through the tickString() event within field value 48.


我只是简单测试了这部分代码，还没有深入去研究。供参考。

**Comment by viponedream** [comment]
我也觉得不要用本地时间。
接收到的tick全部用服务器时间比较好。要是服务器有 时间戳的就使用服务器的时间戳。
需要时再来转换为本地时间。
同时 tick对象也增加一个时间戳属性，有时还是会方便的。

**Comment by vnpy** [comment]
那么回头还是改为用服务器时间吧。

**Comment by vnpy** [comment]
1. 股票、期货的tick推送基于成交变化（last price/last time）的更新
2. 外汇的tick推送基于bid-ask价格变动（last price/last time使用本地时间）

有空的话请帮忙测试下股票、期货的行情工作是否正常。
