### ISSUE TITLE
运行ServerClient出错

### ISSUE THREAD

**Issue by yjxxin** [vnpy/vnpy#1272]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
我在运行examples里面的ServerClient例子时如果点击风险管理模块会出错，但是CTA策略模块不会出错。请问该怎么解决？

## 重现步骤
![2018-12-04 17-54-37](https://user-images.githubusercontent.com/35714148/49433781-bcb3a600-f7ed-11e8-8c4a-f135ef670eed.png)
![2018-12-04 17-54-53](https://user-images.githubusercontent.com/35714148/49433786-be7d6980-f7ed-11e8-977f-a348bfb3c8f0.png)

**Comment by vnpy** [comment]
风险管理模块并没有支持ServerClient模式，需要自行做重构的，重构方法可以参考CtaStrategy模块

**Comment by vnpy** [comment]
GUI界面不再直接访问引擎组件中的属性数据，而是通过函数调用来访问，同时对应函数的调用参数和返回数据都调整为可以序列化的类型

**Comment by yjxxin** [comment]
风险管理模块我已改完，但我在点击算法交易时会出现TypeError: expected string or Unicode object, NoneType found错误，这个错误应该怎么修改。
![2018-12-06 09-49-29](https://user-images.githubusercontent.com/35714148/49555816-41acd580-f93c-11e8-9104-3198e8152e50.png)
![2018-12-06 09-49-04](https://user-images.githubusercontent.com/35714148/49555820-45405c80-f93c-11e8-95d4-b511a0c76328.png)

**Comment by vnpy** [comment]
打印下你的data是否传了None

**Comment by yjxxin** [comment]
这是我打印出来的data，没有None值啊

![Uploading 2018-12-07 09-33-26屏幕截图.png…]()
![Uploading 2018-12-07 09-33-35屏幕截图.png…]()
![2018-12-07 09-39-38](https://user-images.githubusercontent.com/35714148/49622313-08d83380-fa04-11e8-8171-2a4ca5dbbec1.png)

**Comment by yjxxin** [comment]
![2018-12-07 09-33-26](https://user-images.githubusercontent.com/35714148/49622375-4fc62900-fa04-11e8-886a-167331ec8573.png)
![2018-12-07 09-33-35](https://user-images.githubusercontent.com/35714148/49622377-50f75600-fa04-11e8-9e0e-8dbecffb79ce.png)

**Comment by yjxxin** [comment]
我发现只要有register函数就会报这个错

**Comment by yjxxin** [comment]
点击CTA策略时就不报错，打印的data如下图，没有regist信息。
![2018-12-07 17-00-40](https://user-images.githubusercontent.com/35714148/49637949-bf0e3e00-fa41-11e8-8ea5-e198d72935a7.png)

**Comment by yjxxin** [comment]
我调试了一下，发现CTA策略模块在执行registerEvent函数后并没有跳到vnrpc.py文件，而算法交易时registerEvent函数就直接跳到vnrpc.py文件里了。

**Comment by yjxxin** [comment]
作者您好，这个问题我有点急，希望能得到回复，谢谢

**Comment by vnpy** [comment]
AlgoTrading模块并未提供RPC的支持，如果需要定制请联系购买商业咨询服务
