### ISSUE TITLE
tradeCopy模块出现错误字段

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#1273]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev branch 20181205（下载日期）

## Issue类型
三选一：Bug

最新vnpy分支版本有新的tradeCopy模块，在‘vnpy-dev\vnpy\trader\app’内可以找到。
今天测试一下
新复制一个Vntrader，登录2个SimNow账号。启动发布者和订阅者来测试交易复制功能，正常情况下，发布者任何操作（多开，空开，平多，平空），订阅者都会一一跟踪执行。
今实测在发布者中操作  IF1901 ，方向多 ，开仓
订阅者无任何反应，查看报错信息，显示如下图
![image](https://user-images.githubusercontent.com/45591222/49487800-06989c80-f87f-11e8-9eaa-01dc0ac2179f.png)

报错信息显示，在tradeCopy的tcEngine中，先查询持仓信息（checkAndTrade），然后开始同步，在newOrder中发现命名错误DIRECTION_SHROT。
根据上面的 from vnpy.trader.vtConstant import DIRECTION_SHORT中可以知道，是SHORT拼错了

**Comment by vnpy** [comment]
已修复，非常感谢
