### ISSUE TITLE
tradeCopy模块启动后，订阅者不断发出异常委托（拒单状态）

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#1274]
## 环境

* 操作系统: Windows 8.1
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev branch 20181205（下载日期）

## Issue类型
三选一：Bug

tradeCopy模块修复错误字段后，出现不断发出拒单情况
针对 issues#1273 显示的错误字段进行修复，重启Vntrader后再度测试tradeCopy模块。
启动复制交易前发布者和订阅者的状态为：
a. 发布者：cu1901 空 平昨 ；rb1901 空 平昨 ；rb1901 多 开仓 ；rb1901空 平昨 。当前无持仓（交易数量均为1手）
b. 订阅者：IF1901 多 平昨；IF1901 多 开仓；IF1901 空 平仓。当前无持仓。（交易数量均为1手）

分别点击“启动发布者”和”启动订阅者”按钮后，订阅者不断发出异常委托(拒单状态），错误组件显示‘’CTP：平昨仓位不足”，如图1所示。
订阅者的异常委托，如图2所示，其委托似乎与发布者已成交委托方向相反。然后以4个委托为一组，不断循环。
rb1901 多 平昨 2手
rb1901 多 平昨 2手
cu1901 多 平昨 1手
cu1901 多 平昨 1手

![image](https://user-images.githubusercontent.com/45591222/49494259-0063e980-f89a-11e8-9a03-2ad231bd670a.png)

图1 报错组件显示结果

![image](https://user-images.githubusercontent.com/45591222/49494269-08238e00-f89a-11e8-9866-d55b5a4548b0.png)

图2 订阅者异常委托情况

**Comment by vnpy** [comment]
应该加上一个拒单后不再交易该品种或者直接停止复制引擎运行的限制

**Comment by vnpy** [comment]
已修改，非常感谢
