### ISSUE TITLE
关于CTP合约名、mongodb聚合名规范化的问题

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#1276]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
其他接口的vtSymbol都是'symbol.exchange/gateway'，例如'BTCUSD.BITMEX'
唯独CTP的vtSymbol是'symbol'或者'symbol.HOT'，例如'IF1812'或者主力合约'IF.HOT'
这样在数据处理或者数据导出保存时非常不方便，想要把CTP的格式规范改成跟其他接口的一样。
'IF1812.CTP'或者主力合约'IF888'

## 实际程序行为
直接对vnpy/trader/gateway/ctpGateway/ctpGateway.py的CtpMdApi.onRtnDepthMarketData()的vtSymbol进行修改：
def onRtnDepthMarketData(self, data):
    tick.vtSymbol = '.'.join([tick.symbol, tick.gatewayName])   # new

问题：
1.在修改之后并没有效果，请问是哪一步出错了？
2.如果把CTP的名字规范化后，会对其他模块产生什么影响？需要在哪里模块进行修改以保证不出bug？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
首先，交易代码是要后缀交易所，而不一定要后缀交易接口名。

其次，CTP的行情等推送里是没有交易所字段的，所以你要基于本地缓存的交易合约信息去映射，这块准备在2.0重构的时候在做了。

现在大家都已经习惯了期货类接口的vtSymbol不带交易所后缀。

**Comment by vnpy** [comment]
已经在2.0中重构vt_symbol = symbol.exchange，对于所有接口均采用该模式
