### ISSUE TITLE
vnpy交易股指期货时不能平仓

### ISSUE THREAD

**Issue by studynon** [vnpy/vnpy#1277]
使用simnow账户, vnpy交易股指期货时不能平仓
我simnow账户开了1手IH1812的多仓, 使用ctaEngine的sendOrder来进行平仓, 但是多仓没有平掉, 反而开了1手空仓. 请问这是simnow的问题还是, vnpy的问题?
我用vnpy+simnow交易上期所、大商所的商品都没有问题, 是simnow的中金所品种有什么问题吗?

**Comment by 1122455801** [comment]
中金所具有平今惩罚机制，开仓和平昨交易所收取的手续费为万0.23，平今手续费为万6.9。为了规避高昂的平今手续费，vnpy提供了针对中金所品种（IF，IH，IC）的用锁仓代替平今的底层算法，举2个例子：

- 普通模式：开多仓+平今---->手续费：万0.23+万6.9=万7.13
- 锁仓模式：开多仓+（开空仓+明天的平昨多仓+明天的平昨空仓）---->手续费：4*万0.23=万0.92

在VnTrader的VT_Setting.json中可以看到针对中金所的锁仓设置，如"tdPenalty": ["IF", "IH", "IC"],
锁仓的具体代码在vnpy/trader的vtEngine.py中可以看到，部分如下：


`class PositionDetail(object):
    """本地维护的持仓信息"""
    WORKING_STATUS = [STATUS_UNKNOWN, STATUS_NOTTRADED, STATUS_PARTTRADED]
    
    MODE_NORMAL = 'normal'          # 普通模式
    MODE_SHFE = 'shfe'              # 上期所今昨分别平仓
    MODE_TDPENALTY = 'tdpenalty'    # 平今惩罚

    #----------------------------------------------------------------------
    def __init__(self, vtSymbol, contract=None):
        """Constructor"""
        self.vtSymbol = vtSymbol
        self.symbol = EMPTY_STRING
        self.exchange = EMPTY_STRING
        self.name = EMPTY_UNICODE    
        self.size = 1
        
        if contract:
            self.symbol = contract.symbol
            self.exchange = contract.exchange
            self.name = contract.name
            self.size = contract.size
        
        self.longPos = EMPTY_INT
        self.longYd = EMPTY_INT
        self.longTd = EMPTY_INT
        self.longPosFrozen = EMPTY_INT
        self.longYdFrozen = EMPTY_INT
        self.longTdFrozen = EMPTY_INT
        self.longPnl = EMPTY_FLOAT
        self.longPrice = EMPTY_FLOAT
        
        self.shortPos = EMPTY_INT
        self.shortYd = EMPTY_INT
        self.shortTd = EMPTY_INT
        self.shortPosFrozen = EMPTY_INT
        self.shortYdFrozen = EMPTY_INT
        self.shortTdFrozen = EMPTY_INT
        self.shortPnl = EMPTY_FLOAT
        self.shortPrice = EMPTY_FLOAT
        
        self.lastPrice = EMPTY_FLOAT
        
        self.mode = self.MODE_NORMAL
        self.exchange = EMPTY_STRING
        
        self.workingOrderDict = {}`
