### ISSUE TITLE
tradeCopy模块停止后在点击启动，程序立刻当机

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#1278]
## 环境

* 操作系统: 如Windows 8.1
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本:dev branch 20181205（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
交易复制模块能够随时的启动/停止。而不是需要关掉Vntrader后，重新打开才能继续启动该模块

## 实际程序行为
当在交易复制模块点击“停止后”，想重新启动，如再次点击‘启动发布者’，程序立刻当机，只能关掉Vntrader重新来过。
cmd中出现如下的报错
![image](https://user-images.githubusercontent.com/45591222/49500289-50977780-f8ab-11e8-9747-002a83013229.png)
问题出现于uiTcWidget.py文件。

**Comment by vnpy** [comment]
已修复，非常感谢
