### ISSUE TITLE
运行CtaBacktesing中runBacktesting.py 报错：Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lunajing** [vnpy/vnpy#1279]
## 环境

* 操作系统:  Ubuntu 18.10 x64
* vnpy 1.9.1的docker镜像

## Issue类型
三选一：Question

## 预期程序行为
正常运行回测例子

## 实际程序行为
报错：Segmentation fault (core dumped)

## 重现步骤
conda_python runBacktesting.py

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![1544002946345](https://user-images.githubusercontent.com/5291439/49504685-277be480-f8b5-11e8-8283-9dada7833b42.jpg)

**Comment by vnpy** [comment]
纯命令行模式下docker只支持WebTrader，回测需要启动图形界面的

**Comment by lunajing** [comment]
> 纯命令行模式下docker只支持WebTrader，回测需要启动图形界面的

https://github.com/vnpy/vnpy/wiki/CTA%E7%AD%96%E7%95%A5%E6%A8%A1%E5%9D%97%E7%AD%96%E7%95%A5%E5%9B%9E%E6%B5%8B#%E4%BD%BF%E7%94%A8%E5%9B%9E%E6%B5%8B%E5%BC%95%E6%93%8E
回测wiki中，图片显示失败，可以看下怎么回事吗？

**Comment by vnpy** [comment]
图床挂了，已经在安排新的文档计划。
