### ISSUE TITLE
行情刷新不及时

### ISSUE THREAD

**Issue by kevinhuangwl** [vnpy/vnpy#1280]
今天接上期货公司的CTP真实接口，与文华的手机行情对照了一下，发现VNPY的行情刷新频率平均是一秒一次，比接口实际推送的一秒两次要少。请问这是什么原因导致的呢？

VNPY运行在上海的阿里云服务器，查询的是螺纹行情。

**Comment by vnpy** [comment]
接的是simnow服务器吧，仿真系统的推送有时会有延时
