### ISSUE TITLE
loadCsv速度慢，建议用pandas处理

### ISSUE THREAD

**Issue by nerekihs** [vnpy/vnpy#1282]
CtaBacktesting自带的loadCsv将文本储存进mongodb使用了依次update方法，速度十分之慢。
建议用Pandas一次性读取所有文本内容，转换为json，再一次存入mongodb，通常在几秒内就可以完成。

**Comment by vnpy** [comment]
2.0已经改为使用ORM的模式来存储历史数据，不适合采用pandas方案
