### ISSUE TITLE
回测的那个海龟可以用在实盘或模拟中吗？

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1284]
感觉用在VNPY的模拟或实盘不容易啊。对目前的ctaengine什么都不兼容。
但是，假如一个策略，没法用于实盘，为了回测而回测，又有什么意义呢

**Comment by vnpy** [comment]
好问题：
1. 海龟策略本来就是一套CTA策略的开发理念框架，以及一个基于这套框架的策略研究开发样例。海龟的交易信号生成基于日线，第二天盘中触发后由交易员打电话去执行（上古时代），所以原版的海龟本来就没有自动化交易实盘的成分在里面（毕竟靠手动也能执行的不错）
2. 海龟的实盘执行，和回测一样无法通过常规的通用模块来实现，目前计划在v2.0后推出海龟专用的“海龟算法交易”模块，用于实现其实盘自动化交易的功能
