### ISSUE TITLE
跑回测时，load测试数据到数据库，执行conda_python loadCsv.py 报错：Segementation fault (core dumped)

### ISSUE THREAD

**Issue by lunajing** [vnpy/vnpy#1285]
## 环境

* 操作系统: Ubuntu 18.10 x64
* vn.py版本: vnpy 1.9.1的docker镜像

## Issue类型
三选一：Question

## 预期程序行为
正常读取数据

## 实际程序行为
报错：Segementation fault (core dumped)

## 重现步骤
conda_python loadCsv.py

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1、使用mongod命令启动本地数据库
2、cd vnpy/examples/CtaBacktesting
3、conda_python loadCsv.py   // 将测试数据装载
![image](https://user-images.githubusercontent.com/5291439/49720770-94b7bd00-fc9b-11e8-89de-1731f4e199cc.png)

**Comment by cooooo** [comment]
没有细节吗？

**Comment by lunajing** [comment]
> 没有细节吗？

更新了问题，您看下~

**Comment by cooooo** [comment]
> 
> 
> > 没有细节吗？
> 
> 更新了问题，您看下~

信息好少。
Python版本没问题吧？vnpy正确安装好了吗？

**Comment by lunajing** [comment]
> > > 没有细节吗？
> > 
> > 
> > 更新了问题，您看下~
> 
> 信息好少。
> Python版本没问题吧？vnpy正确安装好了吗？

使用的vnpy 1.9.1的docker镜像啊，不是自己搭的环境，信息不少了吧。。。 用的1.9.1的镜像

**Comment by cooooo** [comment]
这我就不知道了，不好意思。
