### ISSUE TITLE
/vnpy/docker/vnc/run_shell.sh 这个脚本的 pwd目录映射到container中的目录有错误

### ISSUE THREAD

**Issue by asdgh1000** [vnpy/vnpy#1287]
![image](https://user-images.githubusercontent.com/8174747/49809638-666cd700-fd9a-11e8-948a-83c174c9c65a.png)

image 名字是不是应该更新一下，目录更换一下。目前我是写死我自己的目录

**Comment by vnpy** [comment]
无更新，关闭
