### ISSUE TITLE
share/cmake/Modules/FindBoost.cmake:2100 (message):

### ISSUE THREAD

**Issue by moxiaoying** [vnpy/vnpy#1288]
## 环境

* 操作系统: MacOS 10.14.2 
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 64位
* vn.py版本: 1.9.1 20181212（下载日期）

## Issue类型
三选一：Question
当运行bash build.sh文件时，出现以下报错信息：
CMake Error at /usr/local/Cellar/cmake/3.13.1/share/cmake/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.68.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:83 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/dongt/vnpy/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".
maxdongtaodeMBP:ctp dongt$ pwd

请问该如何解决

该问题会导致后续无法安装CTP等工具。

**Comment by cooooo** [comment]
CTP不支持mac

**Comment by vnpy** [comment]
楼上正解
