### ISSUE TITLE
关于VNPY.STENGINE的vtSymbol不能重复的改写问题 & ORDER/TRADE/POS的更新问题

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#1289]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
1.
个人理解的vtSymbol之所以在stEngine里不能重复的原因，
是因为StDataEngine.legDict, StDataEngine.vtSymbolSpreadDict, SniperAlgo.legDict需要根据tick.symbol来更新spread和leg的price,order,trade,pos
不知道这么理解对不对？

2.
问题：
如果第1点理解正确的话，那么有个问题：
processOrderEvent是直接根据order.symbol来更新leg,spread的order
processTradeEvent是直接根据trade.symbol来更新leg,spread的order
也就是说STENGINE没有保存orderID，不是根据orderID来判断是哪个策略的ORDER/TRADE？

那如果同时运行了CTAENGINE和STENGINE，CTAENGINE里运行了IF1812，STENGINE的LEG里也有IF1812。
那么此时CTAENGINE的IF1812下单了的话，在STENGINE.LEG里不是也会把LEG的ORDRE/TRADE给错误更新了吗？？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
没错，目前上层模块中的几个策略模块，是不能同时在一个账户上运行的：CtaStrategy/SpreadTrading/OptionMaster/AlgoTrading/TradeCopy

因为本来也不应该一个账户同时跑这几个完全不同类型的应用
