### ISSUE TITLE
策略回放数据不包括setEndDate设定的最后一天？

### ISSUE THREAD

**Issue by waterkirin** [vnpy/vnpy#129]
以1.0版本strategyAtrRsi.py（1.1还没有试过）为例子，假如在回测脚本那里加上engine.setEndDate(endDate='20100430')，回放数据回测，却不包含20100430这一天。

涉及到 ctaBacktesting.py的 loadHistoryData函数

        # 载入初始化需要用的数据
        flt = {'datetime':{'$gte':self.dataStartDate,
                           '$lt':self.strategyStartDate}}        
        initCursor = collection.find(flt)
        

        # 载入回测数据
        if not self.dataEndDate:
            flt = {'datetime':{'$gte':self.strategyStartDate}}   # 数据过滤条件
        else:
            flt = {'datetime':{'$gte':self.strategyStartDate,
                               '$lte':self.dataEndDate}} 

初始化数据那里是 '$lt' 即为小于，所以初始化数据不包括self.strategyStartDate这一天。
但是回测数据那里是'lte' 即为小于等于，为什么回测的时候不包括self.dataEndDate这一天？

**Comment by vnpy** [comment]
写代码时没注意，接下来修复。

**Comment by vnpy** [comment]
我重新检查了一下代码，这里逻辑上应该没有问题：回测数据那里是'lte' 应该会包括self.dataEndDate这一天的数据的，检查两个问题：
1. 是否那天的数据缺失了
2. 是否那天没有发生任何交易

**Comment by loofahcus** [comment]
self.dataEndDate  这个时间是结束那一天的0点吧（而不是选的那天的23:59:59），所以即使 ‘lte' 也不包含结束那天的数据。

**Comment by vnpy** [comment]
哦哦，有道理，所以可能应该加上日内的时间？

**Comment by loofahcus** [comment]
个人觉得应该加上 :)

**Comment by vnpy** [comment]
已经修改好了
