### ISSUE TITLE
能否提供本地洗价功能?

### ISSUE THREAD

**Issue by zfsamzfsam** [vnpy/vnpy#1290]
期货交易使用期货指数数据(通达信上的IFL9/IHL9/RBL9/...),本地洗价达到触发条件后,下单到具体合约(IF1901/IH1901/...)上去
股票交易用前复权数据,本地洗价达到触发条件后,下单到具体股票上去

**Comment by vnpy** [comment]
可以自行修改下CtaEngine，增加行情和交易合约的映射关系后实现，但这类功能的实际价值很小，官方不会提供。
