### ISSUE TITLE
委托界面‘名称’一栏为空

### ISSUE THREAD

**Issue by yjxxin** [vnpy/vnpy#1291]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
在运行ServerClient例子时发现委托界面名称一栏为空，但运行run文件就是好的，这个请问该怎么解决啊。

## 重现步骤

![2018-12-14 16-06-35](https://user-images.githubusercontent.com/35714148/49990892-4582cc80-ffba-11e8-9b45-f584b3e9a561.png)

**Comment by vnpy** [comment]
ServerClient中，有些不重要的数据没有实现服务端和客户端的同步共享，建议如果只是手动交易就用常规模式，ServerClient更多是对于如何使用RPC模块开发多进程程序的一个示例。
