### ISSUE TITLE
VNTRADER不更新FXCM持仓和委托信息

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#1292]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
在使用FXCM时，VNPY可以正常print出回调msg，但是却无法在vnTrader上更新，也无法对现有未成交委托进行撤单、或者对现有持仓进行平仓

## 实际程序行为
![image](https://user-images.githubusercontent.com/44016591/50000009-35c3b200-ffd3-11e8-9f6a-2ad13bfea941.png)
![image](https://user-images.githubusercontent.com/44016591/50000025-43793780-ffd3-11e8-9d79-6eaf245c6eb0.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
FXCM接口的网络连接非常不稳定，可能需要使用境外的云服务器去测试

**Comment by UtorYeung** [comment]
> FXCM接口的网络连接非常不稳定，可能需要使用境外的云服务器去测试

已经试用了境外云服务器，连接是没有问题的，但是vntrader却没更新。。

**Comment by vnpy** [comment]
检查后是因为FXCM接口升级导致，因为连接不稳定2.0可能不再支持FXCM
