### ISSUE TITLE
回测中的盈亏比可能是算错了

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1294]
不考虑费用的情况下。
buy  3000 1手
buy  3100 1手
buy  3200 1手
buy  3300 1手
共买4手，成本3150

再sell 3140 4手 平仓
按海龟的算法，这样一笔交易就是亏损的。

但是目前的回测好像是拆成4笔独立的来计算盈亏，导致两笔亏损，两笔盈利。而实际上只有一笔亏损的交易。

分批进，一次出。
一次进，分批出。
分批进，分批出。
不管各种情况，以平仓时的总VOLUME来算笔会不会更合理？

**Comment by viponedream** [comment]
buy 1
buy 1
buy 1
sell 3   
分批进，一次出。以上这样就当作一笔交易
buy 3
sell 1
sell 2
一次进，多次出，这样也看作一笔。
buy 1
sell 1
看作一笔
buy 2
buy 1
sell 1
sell 2
分批进，分批出。算2笔。

**Comment by vnpy** [comment]
完整的海龟策略，请查看examples/TurtleStrategy，整个信号、组合、引擎的设计是为了中低频日线级别策略设计的，相关的统计指标也都基于日线逐日盯市来分析。

CtaStrategy模块中的TurtleTradingStrategy只包含了完整海龟策略中交易信号组件，更多作为一个展示的母的，而CtaStrategy模块的逐笔统计规则是以每一笔买卖对冲来统计的，每次加仓都会被算作新的交易，更适合中高频日内策略。

所以本来就是这么设计的，并不是bug。
