### ISSUE TITLE
价差交易中，如果主动腿与11:30成交，被动腿在11:30 至 13:30分中间，不断的发起和撤销订单

### ISSUE THREAD

**Issue by yongfuyang** [vnpy/vnpy#1298]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.1

## Issue类型
三选一：Bug

## 预期程序行为

1. 价差交易中，如果休市前主动腿成交而被动腿没有成交，被动腿应该在开市后发起对冲。
## 实际程序行为

1.价差交易中，如果主动腿与11:30成交，被动腿未成交，被动腿在11:30 至 13:30休市期间，不断的发起和撤销订单。实际上撤销订单次数达20000多笔

## 重现步骤

不太好重现。
![image](https://user-images.githubusercontent.com/15922348/50144424-31a4d680-02ea-11e9-9e6a-5ab9aa277161.png)

在 stAlgo.py中432 行：     self.sendLegOrder(leg, legVolume) ，发起被动腿对冲时，加一个时间判断

**Comment by vnpy** [comment]
可以通过一个交易时间的限制来实现管理，下个版本里来加上吧

**Comment by vnpy** [comment]
因为1.9.2的SpreadTrading功能是针对所有的市场，因此在算法中直接提供交易时间限制并不合适。

推荐两个方案：
1. 用户自行在收盘前30秒停止算法，下午开盘前启动
2. 自行在SniperAlgo中添加相关的时间过滤处理
