### ISSUE TITLE
datarecorder 最后一条K线

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1302]
昨天晚上折腾在windows上安装自动录制K线的服务。
刚刚上数据库去看，发现最后一根K线有问题。
2018-12-25 14:59:00.000Z
2018-12-25 15:00:05.000Z
我查了一下 文华和tb,他们都是只有  14:59:00这一根的。所以最后那根是不是多余的？
并且 14:59:00这一根的开盘价，收盘价都跟他们对不上。

今天MA905 12251459这一根
文华TB是：O: 2321  C: 2317
自己录的是O: 2320  C: 2318

**Comment by vnpy** [comment]
1. 国内期货交易所在收盘后，有时会再推送一些tick
2. DataRecorder是面向所有市场的行情录制工具，如果需要对国内的情况专门做过滤请自行实现
3. 比起自己浪费时间折腾数据，推荐用RQData的数据服务
