### ISSUE TITLE
价差的设置

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1303]
里面的 ratio, multiplier是什么意思呢？
如果有多条被动腿的，该怎么设置啊？

[
    {
    "name": "TA.901-905-909",

    "activeLeg":
        {
            "vtSymbol": "TA901",
            "ratio": 1,
            "multiplier": 1.0,
            "payup": 2
        },

    "passiveLegs": [
        {
            "vtSymbol": "TA905",
            "ratio": -1,
            "multiplier": -1.0,
            "payup": 2
        },
        {
            "vtSymbol": "TA909",
            "ratio": -1,
            "multiplier": -1.0,
            "payup": 2
        }
    ]
}

]

**Comment by vnpy** [comment]
multiplier是计算价差的价格时候，用的乘数，没有考虑合约大小。

ratio是真实下单的时候，用的乘数，需要考虑合约大小。
