### ISSUE TITLE
找不到股票代码

### ISSUE THREAD

**Issue by Wc30** [vnpy/vnpy#1304]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
![1545792337 1](https://user-images.githubusercontent.com/34146988/50429819-6a9d0680-08fb-11e9-8611-8b5d79f50026.png)

* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
无具体内容

**Comment by Wc30** [comment]
请问vnpy支持股票嘛？
