### ISSUE TITLE
关于：南华期货ctp tick LastPrice 时常为0 #1301

### ISSUE THREAD

**Issue by LeoK987** [vnpy/vnpy#1305]
继续#1301 

联系了南华，LastPrice 时常为0的数据来自于他们的新版CTP服务器（他们称之为”CTP行情“服务器，以区别于（旧版的）”Front“服务器）。针对我的问题，他们提议两个选择：
1）连接到他们的”Front“服务器，但他们的”Front“服务器会在不久的将来也切换为”CTP行情“；
2）改用新版的CTP，建议是2018.1版本。

针对建议1），连接”Front“服务器确实没有出现LastPrice 时常为0的情况。

针对建议2），我下载了CTP2018.1版，但发现和vnpy的包装存在很大差异，个人升级看来不很轻松。

但升级看来是必须的，据说明年中旬，ZF要求所有期货商上一款更新的CTP版本，目前它已在测试阶段。

**Comment by vnpy** [comment]
1. 新版本全面上线时，vn.py会及时更新
2. 如果现在着急用，可以尝试自己封装升级
