### ISSUE TITLE
请问日线合成是自己更改BarGenerator对吗

### ISSUE THREAD

**Issue by KilimanjaroFreeman** [vnpy/vnpy#1306]
## 环境

* Windows 7
*Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9发行版

## Issue类型
三选一：Question

## 重现步骤
请问日线的合成是要自己修改BarGenerator函数是吗，目前vnpy没有提供日线合成的算法是吗

**Comment by vnpy** [comment]
是的，日线要么通过RQData之类的数据服务直接下载，要么就自己合成吧
