### ISSUE TITLE
okexf接口获取的tick数据的时间戳与ctaEngine的processtickdata函数有冲突

### ISSUE THREAD

**Issue by JohnHush** [vnpy/vnpy#1315]
## 环境

* 操作系统: MacOS Mojave 10.14.1
* Anaconda版本: Anaconda2- 4.0.0 
* vn.py版本: v1.9.2

## Issue类型
Bug

## 实际程序行为

在启动cta策略后，在处理tick数据时, raise ValueError

## 重现步骤

ValueError: time data '20190101 15:03:01' does not match format '%Y%m%d %H:%M:%S.%f'

def onDepth(self, d):
        data = d['data']
        channel = d['channel']

        symbol = self.channelSymbolDict[channel]
        tick = self.tickDict[symbol]

        for n, buf in enumerate(data['bids']):
            price, volume = buf[:2]
            tick.__setattr__('bidPrice%s' %(n+1), float(price))
            tick.__setattr__('bidVolume%s' %(n+1), int(volume))

        for n, buf in enumerate(data['asks']):
            price, volume = buf[:2]
            tick.__setattr__('askPrice%s' %(5-n), float(price))
            tick.__setattr__('askVolume%s' %(5-n), int(volume))

        **dt = datetime.fromtimestamp(data['timestamp']/1000)**
        tick.date = dt.strftime('%Y%m%d')
        tick.time = dt.strftime('%H:%M:%S')

        tick = copy(tick)
        self.gateway.onTick(tick)
在okexfGateway.py的OnDepth回调函数中把上面加粗代码是否需要进行调整？

**Comment by vnpy** [comment]
已修复，加上时间的毫秒部分就行
