### ISSUE TITLE
Gateway的代码组织？

### ISSUE THREAD

**Issue by baiyanhuang** [vnpy/vnpy#132]
各接口API貌似都重复了，比如okcoin：
https://github.com/vnpy/vnpy/blob/master/vn.okcoin/vnokcoin.py
https://github.com/vnpy/vnpy/blob/master/vn.trader/okcoinGateway/vnokcoin.py

vn.okcoin与vn.trader/okcoinGateway应该是什么关系呢？

**Comment by vnpy** [comment]
vn.okcoin是可以直接使用的一个Python API接口，实现了OKCOIN官方API里提供的所有功能。

vn.trade/okcoinGateway是vn.trader平台和vn.okcoin对接的一个交易接口，把vn.okcoin里面的数据格式和函数调用做了转化抽象，使得vn.trader可以直接用。

两者所处的层面不同。

**Comment by baiyanhuang** [comment]
那为什么有两个重复的vnokcoin API文件？

Gateway里面是不是可以删掉了？
https://github.com/vnpy/vnpy/blob/master/vn.trader/okcoinGateway/vnokcoin.py

**Comment by vnpy** [comment]
不是的，每个vn.开头的文件夹都可以视作一个独立的程序。

比如vn.okcoin这个文件夹下包含的OKCOIN接口，是可以用来直接开发一个新的交易平台。

vn.trader文件夹下则是一个由官方提供的完整的交易平台，带图形界面，整合了很多功能。

**Comment by baiyanhuang** [comment]
恩，所以vn.trader是depends on vn.okcoin的，那是不是直接import vn.okcoin里的vnokcoin会好一些 - 目前这两个文件都是commit在git repo里面的，重复有些confusing，而且维护起来也不方便 - 开发必须记住两个文件都同时要改。

**Comment by vnpy** [comment]
如果你是只用vn.trader的话，所有其他的文件夹都可以删掉。

项目里面保留是为了维持每个文件夹都是一个单独可用的程序的形式。
