### ISSUE TITLE
对部分RQData品种的数据不能正常处理

### ISSUE THREAD

**Issue by listplot3d** [vnpy/vnpy#1320]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.9.2发行版

## Issue类型
三选一：Bug

## 预期程序行为
对于rqdata支持的期货或股票数据, 能使用downloadData.py进行处理

## 实际程序行为
测试过期货,股票市场,对于有一些品种不能正确导入到数据库.比如000003.XSHE, WT9901,等等

## 重现步骤
在vnpy/examples/RQData/文件夹下运行下面代码:

from dataService import *  
import logging
logging.basicConfig(filename='importRQData.log',level=logging.DEBUG)
instrument_list=rq.all_instruments(type=None)
id_list=instrument_list['order_book_id']

for i in range(0,id_list.size):
    print('downloading No.',i)
    try:
        downloadDailyBarBySymbol(id_list[i])
    except AttributeError:
        logging.error(id_list[i])

**Comment by vnpy** [comment]
1. 目前只支持期货数据
2. 请提供下具体的报错截图？

**Comment by listplot3d** [comment]
1.期货数据也报错
用下面代码:
`from dataService import *
import logging
logging.basicConfig(filename='importRQData.log',level=logging.DEBUG)
instrument_list=rq.all_instruments(type='Future')
id_list=instrument_list['order_book_id']

for i in range(0,id_list.size):
    print('downloading No.',i)
try:
    downloadDailyBarBySymbol(id_list[i])
except AttributeError:
    logging.error(id_list[i])
`
2.我的试用期账号结束了,没法拿截图了...

**Comment by vnpy** [comment]
无法重现问题，关闭
