### ISSUE TITLE
vnpy IB api未报错“无法找到相应的证券”但无法获取实时行情

### ISSUE THREAD

**Issue by Chen-IMC** [vnpy/vnpy#1325]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9.2
## Issue类型
三选一：Question

## 预期程序行为

我的IB账号已订阅相应的合约的实时市场数据，通过vnpy，获取外汇数据是没有问题的:
![image](https://user-images.githubusercontent.com/35282216/50807955-58798a00-1337-11e9-9ce3-f4c349da4a35.png)

## 实际程序行为

但是对于其他一些股票、期货数据，输入各个合约代码、交易所等参数后，并未报错说“No security definition has been found for the request”，我十分清楚，如果输入的合约代码/交易所/货币/产品类型/接口有误的话是会报上面的错的，但是我输入如下NYMEX上的GC合约后，自动出现了对应的contract名称，说明输入的参数是没有问题的。但依旧无法获得实时的行情推送，行情和行情记录都没有反应，这是什么原因？？

![image](https://user-images.githubusercontent.com/35282216/50808162-43e9c180-1338-11e9-97b4-1440577ce2b9.png)

**Comment by Chen-IMC** [comment]
看了一下，跟[https://github.com/vnpy/vnpy/issues/631](url) 这里的问题相同，请问怎么解决？？ @vnpy #631

**Comment by vnpy** [comment]
NYMEX的合约是需要付费订阅的，请检查你在IB官网后台有没有订阅

**Comment by Chen-IMC** [comment]
> NYMEX的合约是需要付费订阅的，请检查你在IB官网后台有没有订阅

@vnpy 这个我肯定确认的。（IB它们自己有个小bug，这个合约其实是COMEX下的，但跟NYMEX是一家，anyway）我需要的数据都已经付费订阅了

![image](https://user-images.githubusercontent.com/35282216/50812452-c4ff8380-134d-11e9-90b8-e4299868e9c1.png)

而且我也付费订阅了NASDAQ的行情，然后我试了AMZN和GOOG这些股票代码也是上面同样的问题，输入对应的参数后没有报错，但vnpy界面里订阅行情并不显示有任何行情

![image](https://user-images.githubusercontent.com/35282216/50812653-8ddda200-134e-11e9-9cfa-ce27e204357c.png)

#631 跟这个是同样的问题。。

**Comment by vnpy** [comment]
看来可能是老接口的问题了，我们2.0正在做新的ib接入
