### ISSUE TITLE
关于数据重复出现的问题

### ISSUE THREAD

**Issue by Wc30** [vnpy/vnpy#1326]
假设我获取了1.7号的实盘数据，但是启动策略的时候，里面的self.vtsymbol连续出现十几次，这是为什么呢？

**Comment by LeoK987** [comment]
能否说得清楚点？

**Comment by vnpy** [comment]
请按照issue模板提供信息

**Comment by Wc30** [comment]
> 能否说得清楚点？

就是我启动vnpy本身的一个策略。如atr rsi ，我在onbar中print（self.vtsymbol）会出现15个左右的vtsymbol。这是我在实盘的时候遇到的问题

**Comment by vnpy** [comment]
因为读取了15根历史K线回放给策略，做状态初始化的计算
