### ISSUE TITLE
1.9.2版本中的CTA回测引擎中并行优化功能不能显示优化结果

### ISSUE THREAD

**Issue by zhijianlv** [vnpy/vnpy#1332]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.0 Python 2.7 32位
* vn.py版本: 如v1.9.2

## Issue类型
三选一：Enhancement

## 预期程序行为
将各个参数对和优化目标显示在jutper_noteshang上

## 实际程序行为
没有显示排序后的优化结果

**Comment by vnpy** [comment]
无补充信息，关闭
