### ISSUE TITLE
CTP支持穿透式监管要求的CPI

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#1333]
HI，
最近接到期货公司通知，在2019年6月，要求所有程序化客户接入要符合穿透式监管要求（接入终端要采集客户本地信息），要求使用CTP支持的穿透式监管的cpi。

不知道vnpy会有相应的更新吗

BRs
Billy

**Comment by vnpy** [comment]
已经完成了穿透式SE版本的编译，但由于simnow不支持当前无法测试，2.0依旧先采用2017年发布的生产版本API，将在simnow支持后升级到SE版本
