### ISSUE TITLE
2.0 是否应该使用 PySide2 替代 PyQT5 

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#1335]
PySide2 是 QT 官方维护，而且最近的活跃度也感觉比较好，感觉可以使用 PySide2 替代 PyQt5

https://www.reddit.com/r/learnpython/comments/8rjhzd/as_of_mid_2018_is_it_best_to_use_pyqt5_or_pyside2/

**Comment by Gwill** [comment]
另外 pyside2 在 conda-forge 上就有包，安装也比较方便一些 https://anaconda.org/conda-forge/pyside2

**Comment by sunshe35** [comment]
pyqt5刚开始流行，几年前还是pyqt4，至于pyside以及pyside2还没有建立好自己的生态，你看教材就知道，全是pyqt4/5的。

**Comment by vnpy** [comment]
暂时不会考虑，主要原因：
1. 楼上说的生态和文档问题
2. 经历过一次PySide的死亡后，还是更相信PyQt的生命力
3. PySide为了吸引用户，设计上采用了和PyQt几乎一致的API，未来如果成熟了再支持很容易

综上目前2.0的开发会继续集中在PyQt5上
