### ISSUE TITLE
阿里云Ubunt14 安装vnpy后运行报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1338]
## 环境

* 操作系统: Ubuntu 14
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
运行CrptoTrader.py后 报如下错误：

![default](https://user-images.githubusercontent.com/34559558/51160688-1b2e7280-18ca-11e9-883b-aadf58763795.PNG)

运行VnTrader.py后，报如下错误：

![2](https://user-images.githubusercontent.com/34559558/51160909-174f2000-18cb-11e9-8dda-1d6394d2eb07.PNG)

**Comment by yhmickey** [comment]
boost已经升级到最新，并且按照wiki已安装PyQt4

**Comment by vnpy** [comment]
1. 需要安装boost和自行编译CTP接口（为了链接动态链接库）
2. 请升级到Anaconda 5.2.0
3. pip install typing
