### ISSUE TITLE
阿里云Ubuntu  14.04 64位按照教程安装后，远程桌面连接失败

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1339]
## 环境

* 操作系统: Ubuntu 14.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

阿里云已经开放了端口，如果用vnc登录，在输入用户名密码后，命令行刚走了一段就弹出了，然后就再也进不去了

![111](https://user-images.githubusercontent.com/34559558/51161116-19fe4500-18cc-11e9-9321-7ef68b3fac23.PNG)

![12313](https://user-images.githubusercontent.com/34559558/51161168-4b771080-18cc-11e9-9f7d-e398beb0cee1.PNG)

**Comment by vnpy** [comment]
在terminal里运行vnc4server启动服务器上的VNC服务了吗？

**Comment by yhmickey** [comment]
重启机器后，没有运行vnc4server。。。
