### ISSUE TITLE
v2.0-DEV IB Gateway中持仓价格计算有误

### ISSUE THREAD

**Issue by sun0x00** [vnpy/vnpy#1340]
## 环境

* vn.py版本: v2.0-DEV 2019年1月13日

## Issue类型
三选一：Bug

## 预期程序行为
文件  ib_gateway.py  
方法 updatePortfolio （大概在401行）

averageCost 不应直接赋值给vn.py Position中的Price

在IB中，

对于期货，averageCost = 价格x合约大小。所以这里应该先做一个除法.
对于股票，averageCost = 价格

上述两种类型的averageCost 均与持仓数量无关，实盘测试发现上述问题

**Comment by vnpy** [comment]
已修复，非常感谢
