### ISSUE TITLE
关于 v2.0 中类的命名风格

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#1342]
想法：

- vnpy.trader.object 下的诸如 TickData 数据类，直接去掉 Data 叫 Tick、Order 就好
- vnpy.trader.constant 下的交易相关概念的类型常量，如 Product ，叫做 ProductType 、DirectionType 感觉更好一些，不容易混淆

**Comment by vnpy** [comment]
目前已经确定下了2.0的代码命名方案
