### ISSUE TITLE
关于mdapi的继承

### ISSUE THREAD

**Issue by bzg246** [vnpy/vnpy#1343]
## 环境

* 操作系统: ubuntu18.04
* Anaconda版本: 如Anaconda 5.2.0 Python 2.7 64位
* vn.py版本: 1.9.2

## Issue类型
三选一：Question

## 预期程序行为
我发现CtpMdApi的onRtnDepthMarketData是接受ctp的行情的，但是他接受data处理data的方式并不是我想要的方式，然后我就重新写了一个类来继承CtpMdApi。
然后发现程序运行的时候，总是卡在了继承类的初始化完成阶段。

```
class CtpgatewayExtra(CtpGateway):
    def __init__(self, eventEngine, gatewayName='CTP'):
        super(CtpgatewayExtra, self).__init__(eventEngine, gatewayName)
        self.mdApi = CtpMdApiExtra(self)  # 行情API
        print (2)

class CtpMdApiExtra(CtpMdApi, TickBase):
    def __init__(self, gateway):
        super(CtpMdApiExtra, self).__init__(gateway)
        print (1)
    def onRtnDepthMarketData(self, data):
        """行情推送"""
        # 这里是获得行情的第一入口
        # 过滤尚未获取合约交易所时的行情推送
        symbol = data['InstrumentID']
        if symbol not in symbolExchangeDict:
            return

        last_tick = self.tickDict.get(symbol, None)

        # 创建对象
        tick = VttickdataExtra()
        #以下为其他方法


```
## 实际程序行为
程序，每次都只能print (1),都不会print(2)

## 重现步骤
我是先python setup.py安装了vnpy1.9.2.
然后另外写了一个project来写我的代码，调用vnpy的相关模块，以上代码，都在我自己的project中。

请问，如果我要修改mdapi的行为，是可以用这种新的类继承，然后直接改方法，还是我得要在vnpy的project文件夹内修改，然后重新setup.py install？
还有，我上面的这个是出了是么问题？

**Comment by vnpy** [comment]
你这个方法看着没啥问题啊，print 1完了后程序就崩溃了嘛？
