### ISSUE TITLE
xtp demo 错误

### ISSUE THREAD

**Issue by lzd324** [vnpy/vnpy#1351]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda Python 3.5m 64位
* vn.py版本: 最新版本（20190122）

## Issue类型
Bug

##说明
本人在将vnpy转换为python3.5的过程中，xtp部分编译通过后调试test文件夹下tradertest.py，调用函数setSoftwareCode报错，查看vnxtptrader.cpp后发现应使用setSoftwareKey；不知是否因xtp更新导致的异常，望指正，谢谢！

**Comment by vnpy** [comment]
XTP的Python API之前由中泰证券技术团队负责维护，vn.py这边挺久没更新了，2.0后会做更新
