### ISSUE TITLE
exchange拿不到交易所名称，其他关键字都没问题。调用的的是ctp接口。

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#136]
class getAccoutInfo(object):
    """获取账户信息"""
    #----------------------------------------------------------------------
    def __init__(self, mainEngine):
        self.eventEngine = mainEngine.eventEngine
        # 注册事件监听
        self.accountDic = {}
        self.positionDic = {}
        self.registerEvent()

    def onAccount(self, event):
        info = event.dict_['data']
        # 账号代码相关
        self.accountDic["accountID"] = info.accountID     # 账户代码
        self.accountDic["vtAccountID"] = info.vtAccountID         # 账户在vt中的唯一代码，通常是 Gateway名.账户代码
        # 数值相关
        self.accountDic["preBalance"] = info.preBalance           # 昨日账户结算净值
        self.accountDic["balance"] = info.balance              # 账户净值
        self.accountDic["available"] = info.available            # 可用资金
        self.accountDic["commission"] = info.commission           # 今日手续费
        self.accountDic["margin"] = info.margin               # 保证金占用
        self.accountDic["closeProfit"] = info.closeProfit          # 平仓盈亏
        self.accountDic["positionProfit"] = info.positionProfit       # 持仓盈亏

    def onPosition(self, event):
        p = event.dict_['data']
        # 代码编号相关
        self.positionDic["symbol"] = p.symbol              # 合约代码
        self.positionDic["exchange"] = p.exchange            # 交易所代码
        self.positionDic["vtSymbol"] = p.vtSymbol            # 合约在vt系统中的唯一代码，合约代码.交易所代码  
    
        # 持仓相关
        self.positionDic["direction"] = p.direction           # 持仓方向
        self.positionDic["position"] = p.position               # 持仓量
        self.positionDic["frozen"] = p.frozen                 # 冻结数量
        self.positionDic["price"] = p.price                # 持仓均价
        self.positionDic["vtPositionName"] = p.vtPositionName      # 持仓在vt系统中的唯一代码，通常是vtSymbol.方向
    
        # 20151020添加
        self.positionDic["ydPosition"] = p.ydPosition             # 昨持仓            
        print self.positionDic
        
    def registerEvent(self):
        """注册事件监听"""
        self.eventEngine.register(EVENT_POSITION, self.onPosition)

**Comment by vnpy** [comment]
CTP的原生C++接口，在持仓回报这个函数里就是不提供交易所代码的。
