### ISSUE TITLE
ImportError: cannot import name scimath

### ISSUE THREAD

**Issue by Jade999** [vnpy/vnpy#1365]
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
安装完成vnpy,
cd ./exampleVnTrader/
python run.py
==== 报错 === 
  File "/home/yushe/anaconda2/lib/python2.7/site-packages/vnpy-1.9.0-py2.7.egg/vnpy/trader/vtUtility.py", line 4, in <module>
    import numpy as np
  File "/home/yushe/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/yushe/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/yushe/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath

======看起来像是numpy的问题,修复或升级numpy依然会出现其他错误 === 
完全按照wiki中的安装指导来的, 文档不更新,真是坑啊,搞了一天,要放弃了

尝试了多个版本的anaconda, 安装完anaconda后,numpy,pandas包正常import,但是编译完vnpy后,numpy在import的时候就报错了,而且Ｐｙｔｈｏｎ　ｒｕｎ.py会报如上错误，我看了一下其他ｉｓｕｕe，并没我一人遇到这个问题,亟待修复

**Comment by Jade999** [comment]
终于解决了
＝＝＝＝　
．/install.sh安装编译vnpy的过程中,anaconda会对numpy降级处理
如下:
The following packages will be DOWNGRADED:

    numexpr:         2.5-np110py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/ --> 2.4.6-np19py27_0        quantopian                                                       
    numpy:           1.10.4-py27_1      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/ --> 1.9.2-py27_0            https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/
    scikit-learn:    0.17.1-np110py27_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/ --> 0.16.1-np19py27_0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/
    scipy:           0.17.0-np110py27_2 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/ --> 0.16.0-np19py27_0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/

======== 
安装完成后,启动python run.py会报如上错误
解决方法:
pip install numpy==1.10.4
重新升级回来

**Comment by vnpy** [comment]
这两天也刚发现，可能和conda install ta-lib 有关系，看看后续怎么解决

**Comment by Jade999** [comment]
如果是talib的问题，可以试试独立编译talib，而不用conda install 的方式安装，这样编译过程会依赖于本地环境的numpy，不会出现版本兼容性问题
