### ISSUE TITLE
算法交易的templateName无法通过CSV导入

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy#1366]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
导入CSV文件，启动算法

## 实际程序行为
无法导入

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

如下所示修改后可以正常

    def addAlgo(self, algoSetting):
        """新增算法"""
        templateName = unicode(algoSetting['templateName'])

**Comment by vnpy** [comment]
templateName不支持中文，另外编辑csv时建议使用vscode之类的编辑器，避免编码问题
