### ISSUE TITLE
希望回测加上初始资金

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#137]
一，可以通过资金来判断每次开仓多少。
每次交易后权益可以变动。这样下次开仓可以判断允许开多少手。
目前的回测每次开几手都是固定的，希望可以通过权益来决定。
二，onPosition 目前里面的 成本好像是  平均成本价。
希望增加一个最后进场价。对于有加仓的策略这个好用。第一进场价就可有要无，最后进场价很有用。

**Comment by vnpy** [comment]
1. 这块是希望在回测中实现吗？因为实盘CTA策略模块是没有办法知道账户资金的

2. onPosition推送的数据是从底层接口过来的，没法增加最后进场价这个数据（底层本身就没有）

**Comment by baiyanhuang** [comment]
CTA策略模块实盘没办法知道资金账户，这是目前的设计限制，还是cta的api限制？不能访问自己的资金账户蛮奇怪的

**Comment by vnpy** [comment]
目前的设计，因为实盘交易中，每天在某个策略上分配多少资金或者说风险额度，应该是由交易员在盘前提前设定好的，盘中不会去进行修改。

同时账户的实时资金情况是需要定时查询同步的，并不能保证某一时刻你看到的资金就是真正服务器上账户的资金情况，因此基于相关的资金数值做计算操作，都有可能导致算法的交易状态不同步的问题。

综上，成熟的机构系统里会有另外的风控系统专门用于监控整体账户的资金，而策略交易系统只需要知道自己策略的交易额度，当日盈亏情况等数据就可以。
