### ISSUE TITLE
vntader重新启动后，策略启动，即使符合停止单挂单条件，没有停止单生成

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#1370]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9发行版
## Issue类型
三选一：Bug
## 预期程序行为
vntrader重新启动后，启动策略，回放数据，如果符合停止单挂单条件，应该挂停止单

## 实际程序行为
启动策略，点击onInit回放数据，onStart启动策略，即使符合停止单挂单条件，没有停止单生成。

分析代码，onInit(self) 回放数据，但是此时self.trading 为false，不会发出停止单；而onStart时候，不会重新回放启动。

**Comment by vnpy** [comment]
细粒度的挂撤单控制还是交给用户自行实现了
