### ISSUE TITLE
2.0的一些改进建议

### ISSUE THREAD

**Issue by popil1987** [vnpy/vnpy#1372]
## 环境

* 操作系统: 无关
* Anaconda版本: 无关
* vn.py版本: 2.0

## Issue类型
三选一：Enhancement

## 预期程序行为
结合自己在1.9.2的开发对2.0版本提出一些建议
1.ctp接口,有些期货公司(比如大地期货)接入,行情和交易登录都需要设置UserProductInfo这个字段(非authcode方式,就是普通登录的方式),能否官方提供设置这个字段的方式,便于用户接入测试和使用.
2.提供官方期货主力连续换月工具,并且cta回测和交易引擎中提供根据品种订阅所有合约,并利用主力连续换月工具判断出主力连续合约
3.策略中支持更多信息的获取,比如入场价格,出场价格,实时回撤等
3.回测计算结果提供pickle存储,便于以后用其它工具分析.
4.回测结果用prettytable输出更为美观,改动小.

**Comment by vnpy** [comment]
部分已经采纳，非常感谢
