### ISSUE TITLE
策略程序修改后启动CTA界面运行策略发现还是修改之前的逻辑

### ISSUE THREAD

**Issue by wcsmomo** [vnpy/vnpy#1373]
## 环境

* 操作系统:Windows 8 和 windows server 2008 
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位

## Issue类型
三选一：Bug

## 预期程序行为
策略程序修改后启动CTA界面运行策略，策略变成修改后的逻辑。

## 实际程序行为
策略程序修改后启动CTA界面运行策略，策略运行逻辑并无变化。

**Comment by vnpy** [comment]
策略修改后需要重启VNTrader程序
