### ISSUE TITLE
合约查询页面为空

### ISSUE THREAD

**Issue by jayce1212** [vnpy/vnpy#1376]
## 环境

* Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 19年

## Issue类型
Bug

## 实际程序行为

![image](https://user-images.githubusercontent.com/44791674/52475971-28443600-2bd8-11e9-9a8b-f14a68434ce8.png)

**Comment by vnpy** [comment]
你的CTP服务器没有登录上，一直在断线重连，登录成功后才能获取到合约信息
