### ISSUE TITLE
请教作者大大，如果我需要在策略的onbar函数中使用for遍历列表

### ISSUE THREAD

**Issue by buermen** [vnpy/vnpy#1386]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Question 
## 预期程序行为
首先感谢您的开源，我从去年发现到vnpy，编程基础为0，然后自己开始慢慢磕磕碰碰一点一点研究，感谢您的良苦用心，一点基础都没我一个一个文件挨着看居然看懂了，然后慢慢开始写自己的策略，说出来您可能不信，我策略主体是在ctabacktesting.py里面完成的，因为我第一次发现这里可以打印出bar。。

## 实际程序行为
最近策略写差不多了，准备全部写进策略里面了，然后首先就发现一个问题。。在策略里面的onbar函数里，使用for遍历列表会有大问题。。
```
self.closeArray.append(bar.close)
        array = pd.Series(self.closeArray)
        cumsum = array.cummax()
        compare = cumsum - array
        print compare
        for i in range(len(compare)):
            if compare[i] > 5:
                self.daxiao1.append(i)
        if not self.daxiao1:
            return
```
我这样写，一千多根bar，打印self.daxiao1有35万多个，我知道原因是因为事件引擎，但苦于编程能力一直没找到解决办法，
您看到的时候能否帮我指导一个思路吗，因为我策略里面必须遍历收盘价列表，但是我又不能确定我收盘价需要多少根bar
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 这个写法肯定是不好的，pandas相关的运算还是用pandas自身的矩阵计算比较好
2. 请描述下策略逻辑，感觉你的策略是多标的同时计算的，这种模式下可能不太适合用ctaStrategy模块，推荐用RQAlpha或者Zipline之类的工具

**Comment by buermen** [comment]
> 1. 这个写法肯定是不好的，pandas相关的运算还是用pandas自身的矩阵计算比较好
> 2. 请描述下策略逻辑，感觉你的策略是多标的同时计算的，这种模式下可能不太适合用ctaStrategy模块，推荐用RQAlpha或者Zipline之类的工具

感谢您的回复，我就是想找到收盘价回撤大于一个值的那些bar，为此需要遍历收盘价列表，但是在onbar函数里面不能用for循环，我想到的解决方法最终都需要遍历一个列表，所以就卡在这里了，能否麻烦您提示下我怎么写才能遍历呢
```
self.closeArray.append(bar.close)
        if self.aa < bar.close:
            self.aa = bar.close
        self.bb = self.aa - bar.close
        if self.bb >15:
            self.daxiao1.append(self.bb)
```
这是我下午又想的一个解决办法

**Comment by buermen** [comment]
> 1. 这个写法肯定是不好的，pandas相关的运算还是用pandas自身的矩阵计算比较好
> 2. 请描述下策略逻辑，感觉你的策略是多标的同时计算的，这种模式下可能不太适合用ctaStrategy模块，推荐用RQAlpha或者Zipline之类的工具

感谢您的回复，我就是想找到收盘价回撤大于一个值的那些bar，为此需要遍历收盘价列表，但是在onbar函数里面不能用for循环，我想到的解决方法最终都需要遍历一个列表，所以就卡在这里了，能否麻烦您提示下我怎么写才能遍历呢
```
self.closeArray.append(bar.close)
        if self.aa < bar.close:
            self.aa = bar.close
        self.bb = self.aa - bar.close
        if self.bb >15:
            self.daxiao1.append(self.bb)
```
这是我下午又想的一个解决办法

**Comment by xldistance** [comment]
self.daxiao1Array[0:self.buffersize-1] = self.daxiao1Array[1:self.buffersize] 
self.daxiao1Array[-1]= compare[i]

**Comment by vnpy** [comment]
类似楼上的写法，Pandas的DataFrame有比较取值的功能，看看《Python数据分析》这本书吧
