### ISSUE TITLE
vnpy2.0 删除策略时，报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1387]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 3.7 32位
* vn.py版本: 2.0

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![default](https://user-images.githubusercontent.com/34559558/52987800-9ccc6f80-3437-11e9-8e59-05435627a375.PNG)

**Comment by vnpy** [comment]
已修复
