### ISSUE TITLE
examples/ServerClient

### ISSUE THREAD

**Issue by yjxxin** [vnpy/vnpy#1390]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
作者您好，有一个问题想问一下您，在用examples/ServerClient这个例子时，客户端和服务端各自依赖的环境有什么不同吗

**Comment by vnpy** [comment]
例子中所依赖的环境是没有区别的，理想状态下可以Server放在服务器上无需安装启动GUI界面，Client放在本地电脑
