### ISSUE TITLE
策略参数疑问

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1393]
有些问题请教作者：

1、策略参数和变量为什么要写在策略类里，而不是init里呢？这样做的目的是什么呢？

2、这样如果在配置策略时，当不同的合约配置了同一个策略类，是否会发生不同对象之间参数共享的问题？

但是，vnpy2.0好像在界面添加和修改策略参数时，即使是基于同一个策略类，参数互不影响。 有点糊涂。

**Comment by vnpy** [comment]
1. 写在策略类里面，GUI组件在弹出参数配置框的时候（此时策略对象尚未初始化创建出来），知道应该提供哪些配置字段
2. 不会，每个合约上运行的策略是一个独立的对象

建议看看Python的对象和类概念的基础。
