### ISSUE TITLE
2.0版本回测引擎策略加载时，初始化天数异常

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#1403]
## 环境

* 操作系统: 如Windows 7

* vn.py版本: 如v2.0 dev branch 20190221（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
设置加载10天，最开始交易日期应该从11天开始

## 实际程序行为
2.0的引擎，则最开始交易日期从第16天开始

**Comment by vnpy** [comment]
加载的数据是10个交易日，而非自然日
