### ISSUE TITLE
博主可以为Macosx用户做些适配吗！！！

### ISSUE THREAD

**Issue by haxor337** [vnpy/vnpy#1415]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by haxor337** [comment]
原本以为V2.0可以给Mac用户增加些适配，以便更好安装，但试了试，还是不好装。

**Comment by vnpy** [comment]
后续有更多的Rest类接口后，我们也会推出MAC上的VNConda，估计在下半年才做了
