### ISSUE TITLE
请教:2.0中数字货币功能还未添加?

### ISSUE THREAD

**Issue by LSeiei** [vnpy/vnpy#1417]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Question

**Comment by vnpy** [comment]
接口将会逐步添加，移植工作量比较大
