### ISSUE TITLE
vnpy/vnpy/gateway/ctp/ctp_gateway.py中的字典OFFSET_VT2CTP配置不正确

### ISSUE THREAD

**Issue by xx565763914** [vnpy/vnpy#1418]
## 环境

* 操作系统: Windows 10* 
Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0发行版

## Issue类型
三选一：Bug

## 重现步骤
![image](https://user-images.githubusercontent.com/25703389/53555360-c5154600-3b7c-11e9-980e-2accc292bcd0.png)

如图，将平今和平昨写反。

**Comment by vnpy** [comment]
已修复，非常感谢
