### ISSUE TITLE
回测计算结果有误

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#142]
比如说我的开仓是这样的
开仓  2304.0 方向:  空 开仓  数量: 1
开仓  2282.0 方向:  空 开仓  数量: 1
全平  2450.0 方向:  多 平仓  数量: 2 

不算手续费及滑点及乘数。
按理PNL是这样计算的
平仓价 * 平仓数量 - 每次开仓价 * 它的数量
2450 * 2 - （2304*1+2282*1）= 4900 - 4586 = 314  因为是平空，反过来。即亏314

但是，目前vnpy  是这样计算的。
（平仓价 - 第一笔开仓价）* 平仓数量 
（2450-2304） * 2 = 292  因为是平空，反过来。即亏292

TradingResult 这里应该开仓，平仓分开计算，算好再算结果。

感觉现在是 一次开仓，一次平仓的。
要是：
       1，多次开仓，一次全平，
       2，多次开仓，分次平仓
又要怎么计算？

**Comment by vnpy** [comment]
最近有点忙，估计9月上旬来看这个问题。

**Comment by viponedream** [comment]
现在只有一开一平，才是对的。
加仓的，分次平仓的，就错的。

**Comment by trisongzhu** [comment]
我试着修改了代码，在buy-sell , short-cover中进行了测试，
能够满足每次开平根据实际结果计算。

所修改的函数是Backtesting::caculateBacktestingResult
请 @vnpy 参考指正。谢谢


修改部分：1 将开仓订单根据买卖方向首先分类存入longTrade,shortTrade
 `# 如果是开仓交易
            if trade.offset ==  OFFSET_OPEN:
                # 如果是多头开仓，则加入longTrade列表
                if trade.direction == DIRECTION_LONG:
                    longTrade.append(trade)
                # 如果是空头开仓，则加入shortTrade列表
                elif trade.direction == DIRECTION_SHORT:
                    shortTrade.append(trade)
                # 跳出循环，开始下一轮
                continue
`

 2.  如果平仓订单中还有手数未平仓，则继续读入下一个开仓交易，此时需要保存更新后的平仓订单，
因此将exitTrade 提出到子循坏外

` exitTrade = trade
                while True:`

3.  作者考虑了国内外市场的复杂情况，因此对于未填满的平仓单，转成反向开仓单。不过国内由于锁仓而无法进行此类操作。窃以为如果是做ctp回测，可以将代码修改如下：
`if exitTrade.volume:
                        # 且开仓交易已经全部清算完，则平仓交易剩余的部分
                        # 等于新的反向开仓交易，添加到队列中
                        # 但是国内市场上，平仓总量不能超过开仓总量，因此平仓变成反向开仓的逻辑，会导致计算上的混淆
                        continue`

4. 增加assert 语句确认订单的OFFSET_CLOSE标志，避免开仓平仓单混淆。

测试记录：  在零佣金，零滑点的情况下完成了多次buy, 一次sell的验证计算， 多次short, 一次cover的验证计算。涉及品种为IF, size=300. 满足设计要求。
                    




[calculate.py.zip](https://github.com/vnpy/vnpy/files/528806/calculate.py.zip)

**Comment by vnpy** [comment]
不好意思这么迟才有时间来弄这个问题，我刚检查了代码逻辑，似乎不应该会出现viponedream提到的情况，能否给个bug还原的代码我测试一下？谢谢

**Comment by viponedream** [comment]
原来逻辑有错。原来的只适合一次开仓，一次平仓的情况
万一用海龟的程序就算错了。
因为海龟是多次开仓，一次全平的。

**Comment by vnpy** [comment]
已解决
