### ISSUE TITLE
Ubuntu 18.10 系统上连接CTP时自动退出

### ISSUE THREAD

**Issue by leftychen** [vnpy/vnpy#1421]
## 环境

* 操作系统: Ubuntu 18.10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0发行版

## Issue类型
三选一：Question

## 预期程序行为
连接成功

## 实际程序行为
可以打开Vntrader
![screen shot 2019-02-28 at 10 29 35 pm](https://user-images.githubusercontent.com/11320643/53614586-71b8ed00-3ba8-11e9-88de-b130cb8df391.png)

![screen shot 2019-02-28 at 10 33 38 pm](https://user-images.githubusercontent.com/11320643/53614785-163b2f00-3ba9-11e9-9976-c579fffef26b.png)

但是当输入td ip 和 md ip 尝试连接后，系统会闪退。报的错误是

terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请检查你的Python是否为Python 3.7 64位

**Comment by loveinshare** [comment]
同样的问题

**Comment by leftychen** [comment]
@vnpy 确实是64位的. 我感觉貌似是在写入mogodb时出了错误，但还没有找到错误出在哪里

**Comment by loveinshare** [comment]
![image](https://user-images.githubusercontent.com/29618121/53772961-58ef6500-3f23-11e9-8b14-7d5851caa440.png)
我是单独拆出来的md登陆订阅行情直接报错
python3.7.2
系统是ubuntu16.04  暂时手头没有18.04可以用
同样的代码win下可以运行

**Comment by loveinshare** [comment]
> @vnpy 确实是64位的. 我感觉貌似是在写入mogodb时出了错误，但还没有找到错误出在哪里

你看一下楼下 一样的报错

**Comment by vnpy** [comment]
@nanoric 请帮忙看下

**Comment by nanoric** [comment]
```sudo locale-gen zh_CN.GB18030```

**Comment by nanoric** [comment]
或者直接安装中文操作系统就不会有这样的问题。

**Comment by vnpy** [comment]
所以现在Ubuntu的CTP接口unicode转换存在一个对于操作系统默认编码的依赖？这个我们能指定吗

**Comment by vnpy** [comment]
已添加到文档中
