### ISSUE TITLE
系统标识/产品标识(英文或数字-非程序名称)

### ISSUE THREAD

**Issue by kumapy** [vnpy/vnpy#1422]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda2
* vn.py版本: 如v1.9.1

## Issue类型
三选一：Question

## 预期程序行为
准备用vnpy接某期货公司端口交易，期货公司要求提供：系统标识/产品标识(英文或数字-非程序名称)
期货公司：该标识用来识别程序身份

## 实际程序行为
1、不知道该如何填写“系统标识/产品标识(英文或数字-非程序名称)”？
2、期货公司：识别后，会发给我一个校验码，用于身份识别。
     请问这个校验码，怎样放在vnpy里？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by williamlfang** [comment]
在 ctpGateway 里面的 connect() 函数增加：
![selection_045](https://user-images.githubusercontent.com/5860824/53937438-10cd6f80-40e8-11e9-9c46-0ea9269bbc76.png)

**Comment by vnpy** [comment]
1. 产品标识自己选一个英文名就好
2. 校验码找期货公司申请
3. 可以升级到2.0，登录界面中已经包括该字段
