### ISSUE TITLE
importerror： No 'rqdatac' module

### ISSUE THREAD

**Issue by nice-pythoner** [vnpy/vnpy#1423]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Question

how and where to install rqdatac module.

## 实际程序行为

Traceback (most recent call last):

  File "<ipython-input-12-8f529cffc6c8>", line 13, in <module>
    import rqdatac

ModuleNotFoundError: No module named 'rqdatac'

**Comment by nice-pythoner** [comment]
how and where to install rqdatac module.

**Comment by Severezh** [comment]
> 
> 
> how and where to install rqdatac module.

pip install --extra-index-url https://rquser:ricequant99@py.ricequant.com/simple/ rqdatac==1.0.0a66

**Comment by nice-pythoner** [comment]
OK  thanks a lot.






在2019年03月01 22时23分, "Severezh"<notifications@github.com>写道:



how and where to install rqdatac module.

pip install --extra-index-url https://rquser:ricequant99@py.ricequant.com/simple/ rqdatac==1.0.0a66

**Comment by nice-pythoner** [comment]
success   Oh




在2019年03月01 22时23分, "Severezh"<notifications@github.com>写道:



how and where to install rqdatac module.

pip install --extra-index-url https://rquser:ricequant99@py.ricequant.com/simple/ rqdatac==1.0.0a66

**Comment by cxjpower** [comment]
我把rqdatac注释掉了,期望这种收费模块不要成为主程序的必选项,应该给大家自己选择
