### ISSUE TITLE
余额和可用数据显示不对

### ISSUE THREAD

**Issue by smccjj** [vnpy/vnpy#1425]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0正式版

## Issue类型
三选一：Bug

## 预期程序行为
预期可自行登录账号查看

## 实际程序行为
实际行为不正常

## 重现步骤

UI的资金页面，可用和余额数字显示不对。

**Comment by vnpy** [comment]
哪个接口，请提供下截图

**Comment by vnpy** [comment]
无后续更新，关闭
