### ISSUE TITLE
2.0 版本的策略参数中如果有bool类型的无法写给改为False

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1427]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug
## 预期程序行为
想修改策略参数中的bool类型的值为False

## 实际程序行为
无法修改，始终未True

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢！
