### ISSUE TITLE
CTP不合法的登录

### ISSUE THREAD

**Issue by LimingFang** [vnpy/vnpy#1429]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0
* vn.py版本: v1.9.2LTS

## Issue类型
三选一：Bug

## 预期程序行为
通过`python run.py`进入vntrader的GUI界面，然后点击连接CTP，应该会成功连接到行情
## 实际程序行为
行情和交易服务器都连接成功，数据库也成功了，但是显示不合法的登录，错误代码3
vnpy那个文件夹下的CTP_connet.json应该没什么问题

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请确保你的账号密码正确，第一次注册的SimNow需要修改密码后才能使用

**Comment by LimingFang** [comment]
账号就是investorid,密码也是对的，simnow也是可以登录的，我第一次下载vnpy后成功登录过的，现在第二次安装后不行了

**Comment by LimingFang** [comment]
@vnpy

**Comment by vnpy** [comment]
那么请检查下你的连接服务器地址是否正确了

**Comment by LimingFang** [comment]
我example/Vntrader的CTP_connect.json配置如下：
{
"brokerID":"9999","mdAddress":"tcp://218.202.237.33:10012","tdAddress":"tcp://218.202.237.33:10002",
"userID":"084109","password":（打码）
}

**Comment by vnpy** [comment]
你的brokerid和服务器地址是第三组应该都i没问题，建议先尝试其他组服务器，如果还是不行就重新注册个账号试试
