### ISSUE TITLE
发现  os.getcwd() 不太好用

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#143]
突然发现 os.getcwd() 不太好用，它依靠当前工作目录。不太靠得住。比如你在vs建立项目时，目录要选在vn.trader才正常。建在上一级，或更上一级则会出错。

比如风控的配置文件，因为它是跟 rmEngine.py放在同个目录的，所以发现使用 rmEngine.py的当前目录更好。
`
settingFileName = 'RM_setting.json'
RM_PATH = os.path.abspath(os.path.dirname(__file__))         #当前文件目录，file前后有两下划线  
settingFileName = os.path.join(RM_PATH, settingFileName)
#print  u'风控配置文件名',  settingFileName 

#原来的写法是这样的
settingFileName = os.getcwd() + '/riskManager/' + settingFileName 
`

改成上面的写法，会不会更好一点呢。
--------------------------------------------------------------------
我目前那些配置名就是用上面那个方法。
然后在根目录我又写一个 pathSetting.py，把vn.trader的目录结构都加到环境变量中去。
跟vtMain.py 放在同个目录下
import os, sys
ROOT_PATH =   os.path.abspath(os.path.dirname(__file__))    # 把这个文件放在根目录下面        
CTA_PATH = os.path.join(ROOT_PATH, 'ctaAlgo')
STRATEGY_PATH = os.path.join(CTA_PATH, 'strategy')          # 这个目录放在 ctaAlgo下面
DR_PATH = os.path.join(ROOT_PATH, 'dataRecorder')
RM_PATH = os.path.join(ROOT_PATH, 'riskManager')
CTP_PATH = os.path.join(ROOT_PATH, 'ctpGateway')
if not  ROOT_PATH in sys.path:
    sys.path.append(ROOT_PATH)          
if not  CTA_PATH in sys.path:
    sys.path.append(CTA_PATH)    
if not  DR_PATH in sys.path:
    sys.path.append(DR_PATH)    
if not  RM_PATH in sys.path:
    sys.path.append(RM_PATH)   
if not  STRATEGY_PATH in sys.path:
    sys.path.append(STRATEGY_PATH)  

然后在策略文件中，导入这个 pathSetting.py文件
from os import path
ROOT_PATH = path.dirname(path.dirname(path.dirname(path.abspath(__file__))))      # 根目录，即上上级目录             
if not  ROOT_PATH in sys.path:        
    sys.path.append( ROOT_PATH  )
from  pathSetting import *
这样就不会找不到系统的各种模块了。也不受运行目录的影响了。

**Comment by baiyanhuang** [comment]
这是个很好的改进，你可以发一个PR直接改掉

**Comment by vnpy** [comment]
之前有考虑应该怎么处理vn.trader中的目录结构，能集思广益是最好了。

**Comment by chrjxj** [comment]
os.getcwd() + '/filename' seems doesn't work on my windows (Win7), since os.getcwd() return a string like "C:\\xxx\\bbbb\\'

**Comment by vnpy** [comment]
已完成
