### ISSUE TITLE
请问vnpy支持普通散户作股票吗

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1430]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question

资金小， 无法用里面支持的券商api的方式， 请问vnpy支持普通散户作股票吗

**Comment by vnpy** [comment]
对于小资金的散户推荐使用华宝PI

**Comment by jxhuliqun138** [comment]
你好，我刚致电了华宝的客服，他们表示没有支持vnpy啊。 确定代码里已经支持了吗？ 华宝api没有资金要求限制 是吧，多少钱都能交易？

**Comment by vnpy** [comment]
华宝PI是华宝证券定制的量化交易平台，基于vn.py开发，没有资金要求开户就能用
