### ISSUE TITLE
请问华宝证券的话是否有资金门槛要求？

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1434]
## 环境

操作系统: Windows 10
Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
vn.py版本: v1.8

## Issue类型
三选一：Question
请问vnpy对接的华宝证券，是否有资金门槛要求。为什么我刚电话华宝官方，他们说不支持vnpy程序化交易?

**Comment by vnpy** [comment]
没有资金要求，华宝PI为特殊客户端，华宝客服电话是不知道的，请在vn.py交流群里找华宝的人咨询
