### ISSUE TITLE
setup.py needs PyPI Trove Classifiers

### ISSUE THREAD

**Issue by cclauss** [vnpy/vnpy#1437]
__setup.py__ used to have PyPI [__trove classifiers__](https://pypi.org/pypi?%3Aaction=list_classifiers) but it lost them:
https://github.com/vnpy/vnpy/blob/d5e7533789e5900adf8fb8a1a1ff8ef1cb2eca7e/setup.py#L37-L46

This will help when a new release is added to PyPI:
* https://pypi.org/project/vnpy/ scroll down to bottom left

**Comment by vnpy** [comment]
已添加
