### ISSUE TITLE
策略删除的代码有错误，删除策略后，添加同名的策略会报错

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1439]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 预期程序行为
删除策略后添加同名的策略

## 实际程序行为
无法添加，会报错，但重启后是添加成功了的。
看过源代码后，可修改如下：widget.py文件126行起：
    def remove_strategy(self, strategy_name):
        """"""
        manager = self.managers.pop(strategy_name)
        manager.deleteLater()

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢！
