### ISSUE TITLE
平今时出现平昨仓位不足的问题

### ISSUE THREAD

**Issue by q275343119** [vnpy/vnpy#1442]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
    接入CTP接口进行平仓操作时，希望先平昨在平今

## 实际程序行为
    在平今的时候一直报平昨仓位不足

## 重现步骤
    平昨默认输入的Offset(“平”)
    平今输入的是Offset(“平今”)
   
针对Bug类型Issue，请提供具体重现步骤以及报错截图

    后查看CTP接口代码发现：
    OFFSET_VT2CTP = {
    Offset.OPEN: THOST_FTDC_OF_Open, 
    Offset.CLOSE: THOST_FTDC_OFEN_Close,
    Offset.CLOSETODAY: THOST_FTDC_OFEN_CloseYesterday,
    Offset.CLOSEYESTERDAY: THOST_FTDC_OFEN_CloseToday,
    }
   网上查了下CTP接口的参数，我的问题就是来源于这个字典
   这个字典里面平昨平今的映射做反了

**Comment by vnpy** [comment]
已修复
