### ISSUE TITLE
请问vnpy 哪个版本开始支持 华宝pi的

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1444]
## 环境
操作系统: Windows 10
Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
vn.py版本: v1.8

## Issue类型
三选一：Question
请问vnpy 哪个版本开始支持 华宝pi的， 1.8版本支持吗？

**Comment by vnpy** [comment]
华宝PI是华宝证券专有的vn.py定制版本，用户可以开发策略但不能访问底层API，具体请联系vn.py框架交流群里华宝的人了解。
