### ISSUE TITLE
MainEngine里写log的方法隐藏bug

### ISSUE THREAD

**Issue by cxjpower** [vnpy/vnpy#1446]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0 dev branch 20190303

## Issue类型
Question

## 预期程序行为
class BaseData:
    """
    Any data object needs a gateway_name as source or 
    destination and should inherit base data.
    """

    gateway_name: str

程序里定义了所有data对象都必须有gateway_name属性, 那么LogData对象也应该有这个属性.
    def write_log(self, msg: str):
        """
        Put log event with specific message.
        """
        log = LogData(msg=msg)
        event = Event(EVENT_LOG, log)
        self.event_engine.put(event)
然而在MainEngine里, LogData对象只用msg一个属性来初始化,我很奇怪这里没有报错,是因为MainEngine里很少调用写log的方法吗?好像我使用了几天log文件一直是空白的.

**Comment by vnpy** [comment]
已修复
