### ISSUE TITLE
希望VNConda增加离线登录功能

### ISSUE THREAD

**Issue by qzm** [vnpy/vnpy#1447]
## 环境

* 操作系统: Windows 10
* Anaconda版本: VNConda
* vn.py版本: VNConda 2.0

## Issue类型
三选一：Enhancement

## 预期程序行为
1，希望VNConda增加离线登录功能，成功登录一次，以后可以离线登录。原因在于防止 vnpy.com 出现异常无法登录的情况，用户的VNConda无法使用，造成不必要的资金损失。
2，VNStation的弹窗，增加最小化按钮。

## 实际程序行为
1，需要登录才能使用VNConda
2，VNStation弹窗无法最小化在后台

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. VNConda主要提供图形化启动vn.py交易程序的功能，vnpy.com连不上的情况下用户也可以通过脚本来启动vn.py
2. 已经增加最小化到托盘的功能
