### ISSUE TITLE
ubuntu和mac安装错误

### ISSUE THREAD

**Issue by yurenji** [vnpy/vnpy#1452]
问题同： https://github.com/vnpy/vnpy/issues/1426 

尝试解决：
以上问题由setup.py第50行最后多了一个逗号引起，尝试修复后出现了新的问题： 

`clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/yurenji/.pyenv/versions/3.7.0/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/Users/yurenji/.pyenv/versions/3.7.0/lib build/temp.macosx-10.14-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd/vnctptd.o -Lvnpy/api/ctp/libs -lthostmduserapi -lthosttraderapi -o build/lib.macosx-10.14-x86_64-3.7/vnpy/api/ctp/vnctptd.cpython-37m-darwin.so`

目前这个release版本真的有在ubuntu下测试过吗？

**Comment by vnpy** [comment]
和#1412重复
