### ISSUE TITLE
rqdata 无法获取夜盘数据

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1454]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 预期程序行为
夜盘策略初始化的时候，无法获取夜盘数据。
代码可修改为：engine.py 399行
end = datetime.now() + timedelta(1)
获取的最终时间往后延一天就可以了。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
非常感谢！我们尽快修复
