### ISSUE TITLE
行情订阅中的商品代码和RQDATA中的商品代码不统一

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1460]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Question

## 预期程序行为
行情订阅中的商品代码和RQDATA中的商品代码不统一，
如行情订阅是TA905，而RQDATA中的是TA1905.CZCE，
造成能订阅行情就找不到RQDATA数据，或者有历史数据就
订阅不了行情。
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢
