### ISSUE TITLE
dual_thrust_strategy 行情订阅失败

### ISSUE THREAD

**Issue by cxjpower** [vnpy/vnpy#1461]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

dual_thrust_strategy加载初始化后显示行情订阅失败, 查看代码如下:
            # Subscribe market data
            contract = self.main_engine.get_contract(strategy.vt_symbol)
            if contract:
                req = SubscribeRequest(
                    symbol=contract.symbol, exchange=contract.exchange)
                self.main_engine.subscribe(req, contract.gateway_name)
            else:
                self.write_log(f"行情订阅失败，找不到合约{strategy.vt_symbol}", strategy)

订阅行情依赖于main_engine.get_contract方法,但是main_engine并没有实现该方法,所以报错.
同时发现还有很多依赖于main_engine来实现的方法都没有实现, 比如 
main_engine.get_order
main_engine.cancel_limit_order
main_engine.sendmail
这些方法有些在OmsEngine和EmailEngine里实现了,但是调用方法不对.

**Comment by vnpy** [comment]
请提供报错截图？订阅行情失败可能是因为你还没有连接上CTP接口获取到合约信息。

get_contract, get_order, sendmail等函数是在对应引擎中实现，并通过对象方法绑定的方式注入到main_engine中的

**Comment by cxjpower** [comment]
我对2.0架构还没理解透,定位错误,
订阅行情失败是因为vt_symbol错误, 我在cta_strategy_setting.json里手动把vt_symbol的值改成正确的格式(加上交易所代码)就成功了,所以应该是strategy初始化时保存的vt_symbol不对

**Comment by vnpy** [comment]
2.0后为了保持统一性，所有的vt_symbol都是带交易所后缀的了，慢慢就习惯了
