### ISSUE TITLE
v1.92 Bug: vnpy/trader/vtUtility.py

### ISSUE THREAD

**Issue by dotcream** [vnpy/vnpy#1465]
## Issue类型
Bug

vnpy/trader/vtUtility.py
def updateBar(self, bar):

> self.xminBar.datetime = bar.datetime    # 以第一根分钟K线的开始时间戳作为X分钟线的时间戳
> if not (bar.datetime.minute + 1) % self.xmin:   # 可以用X整除
> self.onXminBar(self.xminBar)

## 预期程序行为
每X分钟生成一个xminBar，执行一次onXminBar()

## 实际程序行为
对流动性差的标的行情会bug，导致每2x min生成1个Bar

**Comment by vnpy** [comment]
流动性差的合约不应该使用BarGenerator，毕竟这是个为CTA策略（只交易活跃合约）设计的组件，本身每分钟都不能产生一笔交易的合约你用小结构的K线分析也没什么意义。
