### ISSUE TITLE
Tqdataservice占用内存过高

### ISSUE THREAD

**Issue by kumaxs** [vnpy/vnpy#1466]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda  Python 2.7 
* vn.py版本: 1.9

## Issue类型
三选一：Bug/
## 预期程序行为
TqDataService所使用的TqApi，随着运行时间&数据下载，内存占用会越来越高，直到不能下载新数据。
我在dataService.py中加入了gc.collect（），有所缓解但还是会发生。
## 重现步骤
较长时间运行
或下载400份/次合约历史数据（2c4g）
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
天勤数据的服务提供方目前已不太维护，所以2.0版本中将不再支持该数据服务
