### ISSUE TITLE
VN Station for ubuntu

### ISSUE THREAD

**Issue by yurenji** [vnpy/vnpy#1467]
![image](https://user-images.githubusercontent.com/5565266/54105833-3bcd0180-440f-11e9-96dc-818ff24627a9.png)

“环境准备”中提到需要安装VNConda，并且提到适配windows和ubuntu。但是提供的下载链接只有exe文件，没有ubuntu的安装包。 

因为无法安装VNConda，所以无法进行“使用指南”中提到启动VN Station的操作。

**Comment by vnpy** [comment]
VNConda目前尚未提供Ubuntu版本（短期内也没计划，喜欢用Linux那我们假设你是爱好折腾的），所以请直接手动安装吧

**Comment by yurenji** [comment]
@vnpy 手动安装不是有bug么？  https://github.com/vnpy/vnpy/issues/1412

**Comment by vnpy** [comment]
v2.0.1已经修复
