### ISSUE TITLE
打算加入sptrader的支持吗？

### ISSUE THREAD

**Issue by sharefantasy** [vnpy/vnpy#147]
sptrader在香港比较流行，能提高国际影响力哦

**Comment by vnpy** [comment]
SPT的架构太老了，性能方面和国外一流的柜台没的比，甚至和IB都没得比，所以肯定是不会支持的。

未来可能考虑接入TT、Stellar之类系统的FIX协议，但是前提是确实看到大家有需求。

**Comment by greatGregLiu** [comment]
其实国内外盘交易者很多是使用易盛接口交易外盘的，因为国内的期货公司在香港开的期货公司大部分使用此接口。接口资料：https://github.com/EsunnyAPI/EsunnyAPI_FAQ/blob/master/EsunnyAPI.md  ，这里的 版本3.0 就是。
VNPY能否考虑一下呢？本人愿意donate money for this. 谢谢
