### ISSUE TITLE
v2.0合约查询显示为空

### ISSUE THREAD

**Issue by foxliu** [vnpy/vnpy#1470]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: VNconda
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/5516728/54124315-f9bab480-443c-11e9-97f5-6b63f8be40fb.png)
手动执行命令 d:\VNConda\python.exe d:\VNConda\Scripts\vnstation-script.py
显示
![image](https://user-images.githubusercontent.com/5516728/54124364-240c7200-443d-11e9-87ec-269ba49f413f.png)

**Comment by vnpy** [comment]
你的交易登录失败了，请检查账号密码，登录成功后打开合约查询组件点击“查询”按钮即可看到

**Comment by foxliu** [comment]
登陆成功后， 同样的查询不到合约

**Comment by vnpy** [comment]
请稍等一会应该会有查询合约成功的通知，如果一直没有的话可能服务器有问题换一个试试
