### ISSUE TITLE
TqDataservice内存占用过大的解决方法

### ISSUE THREAD

**Issue by kumaxs** [vnpy/vnpy#1473]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 2.7 64位
* vn.py版本: 1。9
## Issue类型
三选一：Enhancement

## 预期程序行为
使用tqDATAservice下载数据的时候，tqAPI中数据字典data每次下载都会增加4700k左右占用内存。
解决方法：在vnpy\data\tq\vntq.py，def on_receive_msg最后添加self.data.clear()移除缓存解决问题。
给可能像我一样还在使用tqdataservice的朋友一个解决办法（好像只有我了？

    def on_receive_msg(self, msg):
        """收到数据推送"""
        pack = json.loads(msg)
        
        if 'data' in pack:
            l = pack["data"]
        else:
            print(u'on_receive_msg收到的数据中没有data字段，数据内容%s' %str(pack))
            return

        for data in l:
            # 合并更新数据字典
            self._merge_obj(self.data, data)
            # 遍历更新内容并调用回调函数
            for selector, section in data.items():
                if selector == "quotes":
                    if self.quote_callback_func:
                        for ins_id in section.keys():
                            if ins_id in self.quote_ins_list:
                                self.quote_callback_func(ins_id)
                
                elif selector == "ticks":
                    for ins_id in section.keys():
                        chart_id = self._generate_chart_id(ins_id, 0)
                        sub_info = self.chart_subscribes.get(chart_id, None)
                        tick_serial = self.get_tick_serial(ins_id)
                        if tick_serial and sub_info:
                            while len(tick_serial) > sub_info["view_width"]:
                                tick_serial.popitem(last=False)
                            callback_func = sub_info["callback"]
                            if callback_func:
                                callback_func(ins_id, 0)

                elif selector == "klines":
                    for ins_id, sub_section in section.items():
                        for dur_nanoseconds in sub_section.keys():
                            dur_seconds = int(dur_nanoseconds) / 1000000000
                            chart_id = self._generate_chart_id(ins_id, dur_seconds)
                            sub_info = self.chart_subscribes.get(chart_id, None)
                            kline_serial = self.get_kline_serial(ins_id, dur_seconds)
                            if kline_serial and sub_info:
                                while len(kline_serial) > sub_info["view_width"]:
                                    kline_serial.popitem(last=False)
                                callback_func = sub_info["callback"]
                                if callback_func:
                                    callback_func(ins_id, dur_seconds)
        self.data.clear()

**Comment by vnpy** [comment]
尽管天勤接口现在使用的人已经不多，还是非常感谢这个技巧
