### ISSUE TITLE
vnpy2.0不能订阅标准套利合约

### ISSUE THREAD

**Issue by chdl21cn** [vnpy/vnpy#1479]
## 环境

* 操作系统: 如Windows 7 64bit
* Anaconda版本: VNConda Python 3.7 64位
* vn.py版本: v2.0发行版

## Issue类型
Question

## 预期程序行为
可以订阅大商所和郑商所的标准套利合约行情

## 实际程序行为
安装vnpy2.0后，无法订阅大商所和郑商所的标准套利合约，在合约查询中也查询不到相关合约。但是我在交易面板输入完相关信息，点委托按钮后，是可以进行委托下单的，就是没法标准套利合约订阅行情。
我用的行情、交易CTP服务器地址是从快期上查询来的，在快期上可以看到标准套利合约行情，也可以交易。也就是说服务器是支持标准套利合约的。

## 重现步骤
在交易面板，代码输入如SPD SR905&SR909，回车后没有反应。查询合约面板中也查询不到标准套利合约。
之前在vnpy1.x版本中是可以订阅套利合约行情的的，为什么在vnpy2.0就不行了呢？

**Comment by vnpy** [comment]
已修改，支持价差合约

**Comment by chdl21cn** [comment]
更新的2.0.1版本目前仍然查询不到套利合约。
