### ISSUE TITLE
中信证券行情使用飞创证券的行情，查询510050提示接口不存在

### ISSUE THREAD

**Issue by xycfree** [vnpy/vnpy#1480]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda2
* vn.py版本: 如v1.92
## Issue类型
三选一：Bug/Enhancement/Question

中信证券的行情使用飞创证券的行情，连接后，查询510050 ETF50合约，提示接口不存在，optionMaster初始化时，提示：找不到标的物合约510050，请问该怎么进行配置呢？

**Comment by vnpy** [comment]
中信证券的这个接口没有适配optionMaster模块，后续2.0可能会基于顶点来开发
