### ISSUE TITLE
日志一直刷“撤单失败，找不到委托STOP.123456789"

### ISSUE THREAD

**Issue by raoshuaix1** [vnpy/vnpy#1481]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Question

## 预期程序行为
vnpy\app\cta_strategy\engine.py  381行 cancel_all函数
vt_orderids中包含 stop单和limit单

## 实际程序行为
for vt_orderid in vt_orderids:
            self.cancel_limit_order(strategy, vt_orderid)

stop单没有发送到gateway挂单，只是本地缓存，
导致日志一直刷“撤单失败，找不到委托STOP.{1-n}”
每到xmin时间调用cancel_all就刷一片，并且STOP单还在累加没有remove掉

**Comment by vnpy** [comment]
已修复，非常感谢！
