### ISSUE TITLE
ctp的mdAPI回调函数不能debug？

### ISSUE THREAD

**Issue by snake3342** [vnpy/vnpy#149]
用现成的vnctpmd，没有自己编译，使用pycharm(内置的debug器是pydev)，发现回调函数以及其下游触发的函数(就是在同一个线程内的)都不能debug？

有什么办法可以debug到么？

**Comment by vnpy** [comment]
所有在C++层面API中工作的线程的debug都比较复杂，pydev是100%无法工作的，你设置断点应该没反应。

可以用WingIDE试试，但是我估计希望也不大。我自己主要还是采用print的模式。

**Comment by snake3342** [comment]
那啥，我试出来了，如果用pycharm或者eclipse的话(这两个都用pydev调试)，先定义这个一个函数：

def callback_debug_start_point():
	try:#pycharm有pydevd，anaconda没有，所以try
		import pydevd
		pydevd.settrace(suspend=False, trace_only_current_thread=True)
	except:
		print "pydevd只在debug时可通过ide导入，run时无此库"
		pass
	pass

在回调函数里面先调用它，相当于叫pydev调试器重新开始跟踪，debug执行时在此函数执行处下游的断点就可以停住。

**Comment by vnpy** [comment]
WOW, 这个方法挺好的，我分享到群里
