### ISSUE TITLE
ctp接口login error

### ISSUE THREAD

**Issue by JadenGu0** [vnpy/vnpy#1492]
## 环境

* 操作系统:Ubuntu 16.04
* Anaconda版本: Anaconda3-5.3.1 Python 3.7 64位
* vn.py版本: 如v2.0.1DEV

## Issue类型
三选一：Bug

## 实际程序行为
GatewayManager: connecting [demo]
Invalid port: Success
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

At:
  /home/jaden/anaconda3/envs/py37/lib/python3.7/site-packages/vnpy-2.0-py3.7-linux-x86_64.egg/vnpy/gateway/ctp/ctp_gateway.py(337): login
  /home/jaden/anaconda3/envs/py37/lib/python3.7/site-packages/vnpy-2.0-py3.7-linux-x86_64.egg/vnpy/gateway/ctp/ctp_gateway.py(239): onFrontConnected

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
程序安装后调用ctp_gateway的CtpMdApi.login()函数报错

**Comment by vnpy** [comment]
1. GatewayManager我猜测是你自己写的一个组件模块？
2. 这个报错的意思，是你在登录请求中输入错了字段类型，最常见的是brokerid应该是int而非str，你也可以检查下其他的字段

**Comment by JadenGu0** [comment]
请问接口中的auth code 和product info是必填字段吗

**Comment by JadenGu0** [comment]
@vnpy   经测试发现导致问题的原因和1477的bug一样，import ctp时出错，但程序未抛出异常

**Comment by vnpy** [comment]
不是必填的，我们测试下ubuntu import这个问题
