### ISSUE TITLE
更新的2.0.1版本目前仍然查询不到套利合约

### ISSUE THREAD

**Issue by chdl21cn** [vnpy/vnpy#1498]
已修改，支持价差合约

_Originally posted by @vnpy in https://github.com/vnpy/vnpy/issues/1479#issuecomment-472673146_

更新的2.0.1版本目前仍然查询不到套利合约，请确认，谢谢！

**Comment by vnpy** [comment]
检查后发现应该是SimNow服务器问题，除了期货外就只有个“期转现”的合约，没有套利合约

**Comment by chdl21cn** [comment]
> 检查后发现应该是SimNow服务器问题，除了期货外就只有个“期转现”的合约，没有套利合约

我登录的是实盘账户，也是没有套利合约的，而用这个账户和ip登录快期，是可以获得套利合约行情的。请确认，谢谢！

**Comment by vnpy** [comment]
请查看下vnpy/gateway/ctp/ctp_gateway.py中的头部中PRODUCT_CTP2VT代码是否如下所示

`
PRODUCT_CTP2VT = {
    THOST_FTDC_PC_Futures: Product.FUTURES,
    THOST_FTDC_PC_Options: Product.OPTION,
    THOST_FTDC_PC_Combination: Product.SPREAD
}
`

**Comment by chdl21cn** [comment]
> 请查看下vnpy/gateway/ctp/ctp_gateway.py中的头部中PRODUCT_CTP2VT代码是否如下所示
> 
> ```
> PRODUCT_CTP2VT = {
>     THOST_FTDC_PC_Futures: Product.FUTURES,
>     THOST_FTDC_PC_Options: Product.OPTION,
>     THOST_FTDC_PC_Combination: Product.SPREAD
> }
> ```

是的，是和上面代码一样的。

**Comment by vnpy** [comment]
请试试用v1.9.2来连接你的服务器看看能否获取到组合合约的信息？

**Comment by chdl21cn** [comment]
> 请试试用v1.9.2来连接你的服务器看看能否获取到组合合约的信息？

1.9.2是可以获得组合合约信息，并进行交易的。但就是2.0版本不行。

**Comment by vnpy** [comment]
请加下我的微信vn_trader吧，帮你用你的账号来排查下

**Comment by ieachen** [comment]
我也遇到同样的问题，存在套利合约时会一直提示：

>   Anaconda3\lib\_strptime.py(359): _strptime
>   Anaconda3\lib\_strptime.py(577): _strptime_datetime
>   vnpy\gateway\ctp\ctp_gateway.py(573): onRspQryInstrument
> 
> ValueError: time data '' does not match format '%Y%m%d'
> onRspQryInvestorPosition  KeyError: ('SPC b1905&m1909',)

问题出在 ctp_gateway.py 的 onRspQryInstrument option_expiry=datetime.strptime(data["ExpireDate"], "%Y%m%d")
套利合约的 data["ExpireDate"] 为空字符串，datetime.strptime(data["ExpireDate"]) 会报错，尽管此处的报错不影响程序运行。底下我贴了普通合约、套利合约的 data["ExpireDate"]  截图对比。

一种简单的改法是：
`option_expiry=datetime.strptime(data["ExpireDate"],` "%Y%m%d") if data["ExpireDate"] != '' else pd.NaT

顺便一提，截图最后一张期转现合约的 ProductClass = 5 在 ctp_gateway.py 没有定义，可能需要添加一下？

普通合约
![rb1910](https://user-images.githubusercontent.com/24794105/55619353-15f70a80-57cb-11e9-91ab-0bc7c35db112.png)

套利合约
![spd ma002 ma003](https://user-images.githubusercontent.com/24794105/55619414-3626c980-57cb-11e9-9f01-410487372d87.png)
![spc i2001 jm1909](https://user-images.githubusercontent.com/24794105/55619428-3e7f0480-57cb-11e9-8170-3721e19da1fb.png)

期转现合约
![T1906EFP](https://user-images.githubusercontent.com/24794105/55619442-4343b880-57cb-11e9-82d2-11a9080aecad.png)

**Comment by vnpy** [comment]
@ieachen 非常感谢，我来修复进去

**Comment by vnpy** [comment]
已修复
