### ISSUE TITLE
最新版DEV登录CTP并交易后崩溃

### ISSUE THREAD

**Issue by cooooo** [vnpy/vnpy#1501]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: miniconda， Python 3.7 64位
* vn.py版本: 最新版dev

## Issue类型
三选一：Question

连接ctp之后，手动下单，vnpy崩溃。重新运行vnpy，点击连接ctp时，vnpy崩溃。报错'segment fault'。

**Comment by vnpy** [comment]
请提供你下单的操作细节？

品种、价格、数量等

**Comment by cooooo** [comment]
下单的相关细节：simnow环境，rb1905， 买开1手，价格3808。界面已经显示报单成功，后来报单也成交了。

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy/blob/v2.0.1-DEV/docs/install.md

你是英文系统吧，应该少了中文编码环境，请尝试下这个操作

**Comment by cooooo** [comment]
忘说了，我是中文系统
