### ISSUE TITLE
安装2.0的问题

### ISSUE THREAD

**Issue by eyelivermore** [vnpy/vnpy#1503]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.6 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190320（下载日期）

前面几步安装好后,
进入之前解压文件夹下   并没有发显   examples/VnTrader 目录

**Comment by vnpy** [comment]
2.0不再提供examples目录，可以自己写启动脚本run.py或者通过VNStation来启动
