### ISSUE TITLE
请问vnpy是否有股票数据源的推送模块?

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1504]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 2.7
* vn.py版本: 如v1.8

## Issue类型
三选一：Question
华宝pi，它独立出来一个包，但是它的软件 策略代码框架很不规范， 同时软件不稳定仿真都不通过。
我指的vnpy框架里面是否有对接股票数据源， 如何tushare、新浪数据又或者其他券商的全推送？

**Comment by vnpy** [comment]
1. 证券数据和期货不同，实时行情不经过交易所授权就进行分发，是违法违规行为，交易所有权追究责任
2. 用户自己可以通过tushare访问新浪数据实时行情，但内嵌于vn.py或者华宝PI中就属于上面定义的“违法违规”了
