### ISSUE TITLE
请问大神，我准备连接实盘了

### ISSUE THREAD

**Issue by buermen** [vnpy/vnpy#1506]
但是期货公司的服务器
行情地址和交易地址都是一样的
但是有个啥port = 41213和port=41205，还有个type = 0,type = 1我怎么来连接呢

**Comment by buermen** [comment]
`<hq>
<server server="180.166.183.113" port="41213" type="0"/>
</hq>
<trade>
<server server="180.166.183.113" port="41205" type="1"/>
</trade>`

**Comment by buermen** [comment]
只输入地址的话会提示错误：
Invalid port: No error

**Comment by vnpy** [comment]
你这是什么交易通道的？看两个端口号应该是CTP，直接在服务器地址里写

```
tcp://180.166.183.113:41213
tcp://180.166.183.113:41205

```
就行

**Comment by buermen** [comment]
> 你这是什么交易通道的？看两个端口号应该是CTP，直接在服务器地址里写
> 
> ```
> tcp://180.166.183.113:41213
> tcp://180.166.183.113:41205
> ```
> 就行

您好，我这样加了之后登陆提示ctp登陆不合法，是还需要向期货公司获取什么吗

**Comment by buermen** [comment]
> 你这是什么交易通道的？看两个端口号应该是CTP，直接在服务器地址里写
> 
> ```
> tcp://180.166.183.113:41213
> tcp://180.166.183.113:41205
> ```
> 就行
是ctp的

**Comment by vnpy** [comment]
请检查你的brokerID是否填对了，如果还是不行可能期货公司开了接入验证，就要申请product_info和auth_code了

**Comment by gwall2005** [comment]
帐号没开通ctp吧

**Comment by buermen** [comment]
> 请检查你的brokerID是否填对了，如果还是不行可能期货公司开了接入验证，就要申请product_info和auth_code了

ID账号密码这些没错，好的，谢谢，我向期货公司问下
