### ISSUE TITLE
server 2008启动vntrader 连接bitmex的REAL和TESTNTE有问题，win7就没有问题

### ISSUE THREAD

**Issue by followdao** [vnpy/vnpy#1508]
## 环境

* 操作系统: 如Server 2008 64 和 windows 7 64
* Anaconda版本: 如Anaconda 18.12 Python 3.7.2 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
server和win7都一样正常连接

## 实际程序行为
server不正常：连接bitmex（ctp连接正常）
   REST API启动成功
   触发异常，状态码：<class 'websocket._exceptions.WebSocketProxyException'>，信息：[WinError 10054] 远程主机强迫关闭了一个现有的连接。
 connect_bitmex.json中 proxy_host 和 proxy_port 用的是香港服务器IP和端口
win7正常:
  REST API启动成功
  Websocket API连接成功
   Websocket API验证授权成功
  connect_bitmex.json中 proxy_host 和 proxy_port 用的是    
  "proxy_host": "127.0.0.1",
   "proxy_port": 1080

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
用的是2.0版本还是1.9.2版本的？

如果是2.0版本，走代理服务器需要安装shadowsocks

**Comment by followdao** [comment]
陈老师，我这边是2.0.1-DEV版本，在香港云服务器运行，也需要再安装shadowsocks吗？

**Comment by followdao** [comment]
非常感谢陈老师,biemex正常连接了
