### ISSUE TITLE
成交和委托排序的问题

### ISSUE THREAD

**Issue by crazykuma** [vnpy/vnpy#151]
问题场景：
无界面运行策略，每天盘前启动
界面只用作成交监控，从不关闭

问题现象：
成交监控显示正常，按照成交顺序排序
委托监控显示异常，会排到之前的委托前面去，准确的说是把之前的委托覆盖了

**Comment by vnpy** [comment]
界面上的委托监控的表格，是基于委托号的数据来实现的。如果你隔夜不关闭系统，那么第二天的委托号和前一天的发生重复时就会出现覆盖的情况。
