### ISSUE TITLE
CTP连接异常

### ISSUE THREAD

**Issue by followdao** [vnpy/vnpy#1510]
## 环境

* 操作系统: 如server 2008 64
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.1-DEV 或者dev branch 20190321（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
连接tcp 希望正常联系行情和交易服务器

## 实际程序行为
有时候，弹出python 已停止工作 
隐藏问题详细信息
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	python.exe
  应用程序版本:	3.7.2150.1013
  应用程序时间戳:	5c6f3612
  故障模块名称:	vnctptd.pyd
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5c6ac1b8
  异常代码:	40000015
  异常偏移:	0000000000108b07
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	64cd
  其他信息 2:	64cdc4e7c7b10208034abc7f864dd77a
  其他信息 3:	e12b
  其他信息 4:	e12bf58eee253c2faf2e0b8e360d5a89

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 请描述bug触发的方式
2. 请提供具体的报错截图

**Comment by vnpy** [comment]
无更新，关闭
