### ISSUE TITLE
VN2.0 cancel_limit_order BUG?

### ISSUE THREAD

**Issue by GladosAI** [vnpy/vnpy#1517]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0发行版

## Issue类型
Bug OR Question
## 预期程序行为
app/cta_strategies/engine.py中324行
```
    def cancel_limit_order(self, strategy: CtaTemplate, vt_orderid: str):
        """
        Cancel existing order by vt_orderid.
        """
        order = self.main_engine.get_order(vt_orderid)
        if not order:
            self.write_log(f"撤单失败，找不到委托{vt_orderid}", strategy)
            return

        req = order.create_cancel_request()
        self.main_engine.cancel_limit_order(req, order.gateway_name)
```

`self.main_engine.cancel_limit_order(req, order.gateway_name)`
会发生自我调用，main_engine没有这个方法。

猜测应该改为
`self.main_engine.cancel_order(req, order.gateway_name)`

## 
没有实际测试过，看代码应该是bug。刚接触vnpy可能有误，望指正，谢谢！

**Comment by vnpy** [comment]
2.0.1中已经修复，预计下周发布

**Comment by vnpy** [comment]
2.0.1中已经修复，预计下周发布
