### ISSUE TITLE
log无输出

### ISSUE THREAD

**Issue by jingwei1982** [vnpy/vnpy#1518]
## 环境

Win10, 连接自己的gateway后vntrader界面正常显示log, 但console和file下都无log输出。
## Issue类型
三选一：Bug

## 重现步骤

    self.level = SETTINGS["log.level"]
    self.logger = logging.getLogger("VN Trader")
现在self.logger无level设置导致的， 在上面代码后添加了下面代码后，正常输出。
    self.logger.level = SETTINGS["log.level"]

**Comment by vnpy** [comment]
已修复，非常感谢！
