### ISSUE TITLE
CTA回测模块能不能增加账户资金的实时计算

### ISSUE THREAD

**Issue by aijy** [vnpy/vnpy#1519]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
在用CTA策略回测的时候，有使用到账户资金变化的需求。目前回测系统是在回测完之后，对订单进行总结，计算盈亏，能不能在每个bar的时候，都能获取当前的资金量。

**Comment by aijy** [comment]
我用的回测系统是2.0.1版本的

**Comment by vnpy** [comment]
目前无计划，策略应该负责的是去正确捕捉交易机会执行交易，而资金相关的配置则应在实盘交易时每天由交易员来负责管理。
