### ISSUE TITLE
要是想给vnpy贡献代码的话，按照什么流程？

### ISSUE THREAD

**Issue by snake3342** [vnpy/vnpy#152]
是允许咱们提交新的分支？还是说只允许添加新文件？还是咋个玩法？陈总给科普一下？

**Comment by vnpy** [comment]
目前没有非常正式的流程，整体上欢迎修复bug和提交新的功能代码，我review后没问题就合并进去，有需要修改的地方会和作者沟通，尽量由贡献者修改后我这边来合并，这样可以比较清楚的看到大家的贡献。
