### ISSUE TITLE
ubuntu下ctp连接错误

### ISSUE THREAD

**Issue by JadenGu0** [vnpy/vnpy#1521]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda3  5.3.1  Python 3.7 64位
* vn.py版本:v2.0.1-DEV 20190325（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
In[2]: from vnpy.gateway.ctp.ctp_gateway import CtpGateway
  ...: from vnpy.event import EventEngine
  ...: engine = EventEngine()
  ...: a=CtpGateway(event_engine = engine)
  ...: setting={'username':'','password':'','brokerid':'8070','td_address':'tcp://101.226.253.243:41205','md_address':'tcp://101.226.253.243:41213','product':'','authcode':''}
  ...: 
  ...: 
In[3]: a.connect(setting)
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请问Ubuntu版本是中文还是英文版？

**Comment by JadenGu0** [comment]
@vnpy  英文的

**Comment by nanoric** [comment]
这是同一个issue #1421 
说明文档中已经给出解决方案。
https://github.com/vnpy/vnpy/issues/1421#issuecomment-469510068
