### ISSUE TITLE
请问如何将tushare的实时数据 内嵌到vnpy中实现股票程序化推送

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1526]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question
请问有相应的demo吗？ 或者能否提供些思路。

**Comment by vnpy** [comment]
交易所禁止非授权实时行情的分发，vn.py目前没法提供

**Comment by dragonheadbrother** [comment]
> 交易所禁止非授权实时行情的分发，vn.py目前没法提供

多么痛的领悟~
