### ISSUE TITLE
请问能不能提供一个老版本类似runCTAtrading的代码文件

### ISSUE THREAD

**Issue by RoyCheng1997** [vnpy/vnpy#1528]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
不使用GUI直接运行交易

## 实际程序行为
无

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
接下来将以文档的形式提供

**Comment by handsomehu** [comment]
能不能提供个文档，提示下2.0和1.X的主要差别？我看example目录好像完全没有了。
感觉里面的Data Recording, CtaTrading还是很有用的。
谢谢！

**Comment by studyquant** [comment]
同感

**Comment by zha0yangchen** [comment]
同感，现在这个版本连回测这些都不提供。。。

**Comment by vnpy** [comment]
> 同感，现在这个版本连回测这些都不提供。。。
回测的示例代码在tests/backtesting目录下有

**Comment by vnpy** [comment]
已添加：https://github.com/vnpy/vnpy/tree/dev/examples/no_ui
