### ISSUE TITLE
回测程式的SendOrder方法，返回缺少gatewayName

### ISSUE THREAD

**Issue by msincenselee** [vnpy/vnpy#153]
改进如下：
**init**(self):
+self.gatewayName = u'BackTest'

SendOrder()
 +order.gatewayName = self.gatewayName
- return orderID
  +return u'{0}.{1}'.format(order.gatewayName, orderID)

**Comment by vnpy** [comment]
想问下这么修改的目的是什么？

**Comment by vnpy** [comment]
考虑到这个功能增加对回测引擎意义不大，且额外的运算会拖低回测速度，暂时不添加
