### ISSUE TITLE
登陆CTP后get_all_positions第一时间没有持仓数据，再次运行get_all_positions才有持仓数据

### ISSUE THREAD

**Issue by ieachen** [vnpy/vnpy#1532]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
登陆CTP后，get_all_positions 第一时间就能返回持仓

## 实际程序行为
get_all_positions 第一时间返回空list，无数据；再次 get_all_positions 能正常返回持仓数据

## 重现步骤

截图

![Snipaste_2019-03-29_14-40-41](https://user-images.githubusercontent.com/24794105/55214195-d790a700-5230-11e9-99f6-c6b166d9b70b.png)

**Comment by xldistance** [comment]
![QQ截图20190331083954](https://user-images.githubusercontent.com/29418474/55283223-99aa9480-5390-11e9-8373-401709cd811c.png)我这里一切正常，第一次返回空值你可以加个判断啊

**Comment by ieachen** [comment]
> ![QQ截图20190331083954](https://user-images.githubusercontent.com/29418474/55283223-99aa9480-5390-11e9-8373-401709cd811c.png)我这里一切正常，第一次返回空值你可以加个判断啊

截图里您的版本是vnpy Python 2版？我这边遇到的问题是vnpy Python 3版的

**Comment by xldistance** [comment]
> > ![QQ截图20190331083954](https://user-images.githubusercontent.com/29418474/55283223-99aa9480-5390-11e9-8373-401709cd811c.png)我这里一切正常，第一次返回空值你可以加个判断啊
> 
> 截图里您的版本是vnpy Python 2版？我这边遇到的问题是vnpy Python 3版的

自己改下嘛，有数据才返回

**Comment by vnpy** [comment]
1. get_all_positions是返回内存中已有的持仓数据
2. 刚连接CTP时，由于底层接口查询结果尚未返回，此时内存中的持仓数据为空，就会出现返回结果为空的情况
3. 再命令交易模式下的解决方法，是connect后睡眠5-10秒，等到底层初始化完成
