### ISSUE TITLE
安装过程中，提示'list' object has no attribute 'name'。

### ISSUE THREAD

**Issue by xinjiyuan97** [vnpy/vnpy#1534]
## 环境

* 操作系统: Mac OS 10.13
* Python 3.7.3
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
在运行Python3.7 setup.py install 时，提示'list' object has no attribute 'name'。

## 重现步骤
正常安装步骤，提示安装错误。

**Comment by vnpy** [comment]
请尝试使用v2.0.1版本
