### ISSUE TITLE
能否退出CTP而不退出windows界面

### ISSUE THREAD

**Issue by basicsp** [vnpy/vnpy#1535]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0发行版

## Issue类型
三选一：Enhancement

## 预期程序行为
能否实现退出CTP的时候，不退出windows界面，并且可以再次登录？这样便于控制每天开盘前自动登录，收盘后自动退出而不关闭界面

这个问题困扰很久了，之前用进程的方法解决，但是要做隔离，无奈放弃界面操作了，感谢大神。

**Comment by xldistance** [comment]
用runctatrading

**Comment by vnpy** [comment]
每天重启的意义，在于消除昨日交易的全部内存状态，以一个全新初始化的状态来启动。你想做的这个事情，是量化交易实盘运维中需要避免的一种错误

**Comment by basicsp** [comment]
嗯，在试图改造的过程中，能基本实现自动启动和退出，但是确实要考虑TD、MD的登录状态、订阅状态，还有对象销毁过程中出现的调用问题，估计有其他方面没有涉及到的部分，这方面耗费的精力可能超过策略本身了。全新启动是挺好的思路，多谢！
