### ISSUE TITLE
macOS  oes模块无法正常编译 

### ISSUE THREAD

**Issue by forrestzhang** [vnpy/vnpy#1536]
## 环境

* 操作系统: MacOS
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: dev branch 20190330（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
安装失败, oes模块无法正常编译 

## 实际程序行为
python setup.py install

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

<img width="1024" alt="屏幕快照 2019-03-31 上午9 27 00" src="https://user-images.githubusercontent.com/364708/55283494-28baab00-5397-11e9-9625-38e37539a22a.png">

**Comment by vnpy** [comment]
OES接口只支持Windows和Linux
