### ISSUE TITLE
linux环境下链接CTP出错退出

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1537]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0发行版或者dev 

## Issue类型
三选一：Bug

## 预期程序行为
链接CTP

## 实际程序行为
链接上行情服务器后就退出，报错：
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
查了linux下该问题的解决方案，
但是无效。
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cooooo** [comment]
[解决方案](https://github.com/vnpy/vnpy/issues/1421#issuecomment-469510068)
