### ISSUE TITLE
CTAengine中数据推送的问题

### ISSUE THREAD

**Issue by crazykuma** [vnpy/vnpy#154]
假设在CTAsetting文件中设置了多策略同时使用某一个合约的时候
单独运行其中一个策略，另一个策略也会收到数据推送

修正方法
ctaEngine.py文件中processTickEvent(self,event)
修改：
```
l = self.tickStrategyDict[tick.vtSymbol]
            for strategy in l:
                strategy.onTick(ctaTick)
```
为：
```
l = self.tickStrategyDict[tick.vtSymbol]
            for strategy in l:
                if strategy.trading:
                    strategy.onTick(ctaTick)
```

**Comment by vnpy** [comment]
你说的情况是CTA引擎的设计初衷，所以这个修改有点问题。

目前CTA引擎的设计是允许没有启动交易的策略也实时接收到推送的行情，并进行相关的指标等数据计算，后面需要时用户只需启动交易就可以了。

采用你这里改进的写法，会导致没有启动的策略收不到行情数据。
