### ISSUE TITLE
XKEYBOARD extension not present on the X server

### ISSUE THREAD

**Issue by forrestzhang** [vnpy/vnpy#1540]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: dev branch 20190330（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
键盘输入与屏幕显示不一致,键盘输入OI

## 实际程序行为
显示为1ZL

## 重现步骤

<img width="1909" alt="屏幕快照 2019-04-01 下午6 04 32" src="https://user-images.githubusercontent.com/364708/55319988-b0dca580-54a8-11e9-8afa-abb0cf551552.png">
<img width="569" alt="屏幕快照 2019-04-01 下午6 05 01" src="https://user-images.githubusercontent.com/364708/55319995-b3d79600-54a8-11e9-832b-e1db057bf641.png">

**Comment by vnpy** [comment]
@nanoric 我理解这个应该是X server安装配置的问题？和vn.py无关吧

**Comment by forrestzhang** [comment]
vnc 连过去的，在vnc下面其他界面都没有问题

**Comment by vnpy** [comment]
搜了下这个XKEYBOARD extension应该是扩展模块，我尝试在阿里云用Ubuntu 18.04的GNOME界面没问题，客户端用的REALVNC

请试试禁用XKEYBOARD或者换REALVNC
