### ISSUE TITLE
代码风格，关于 super() 的使用

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#1542]
Python 3 中子类初始化中需要调用父类的初始化方法，可以直接使用 `super().__init__(foo, bar)` ，不需要再 `super(SubClassName, self).__init__(foo, bar)` 。

项目里相关的地方需要修改吗？

**Comment by vnpy** [comment]
下个版本中我们会做这个修改

**Comment by vnpy** [comment]
大部分已经替换为新的写法，少部分遗漏的欢迎告知
