### ISSUE TITLE
tiger_gateway 这里有问题

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1545]
因为异步连接，万一还没有连接成功呢？

    def subscribe(self, req: SubscribeRequest):
        """"""
        self.push_client.subscribe_quote([req.symbol])
        self.push_client.subscribe_asset()
        self.push_client.subscribe_position()
        self.push_client.subscribe_order()

**Comment by vnpy** [comment]
下个版本来修复

**Comment by vnpy** [comment]
已修复，非常感谢
