### ISSUE TITLE
2.01无法从数据库中读取数据

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1551]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda3 Python 3.7 64位
* vn.py版本: 2.01

## Issue类型
三选一：Bug/Enhancement/Question
Question
## 预期程序行为
CTA Engine首先尝试RQData读取历史数据，如果失败，则从数据库读取数据。
## 实际程序行为
实际运行无法从数据库读取数据
https://github.com/vnpy/vnpy/blob/11d9293136ee15773a42787ca195580ba270bf7a/vnpy/app/cta_strategy/engine.py#L544

(DbBarData.interval == interval) 
interval是枚举类型，并不是字符串类型，是否应为interval.value ?

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢
