### ISSUE TITLE
 VNConda v2.01 无法定位ssleay32.dll

### ISSUE THREAD

**Issue by gmx321** [vnpy/vnpy#1553]
## 环境

* 操作系统: 如Windows 10
* VNConda v2.01

## Issue类型
Bug

## 实际程序行为
刚卸载了2.0，安装了2.01。启动时出现了下面的问题，请看截图。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![图片](https://user-images.githubusercontent.com/7112268/55474371-8bd06a00-5643-11e9-8b35-f064a45edfd1.png)

![图片](https://user-images.githubusercontent.com/7112268/55474392-9b4fb300-5643-11e9-8bdb-51b1a89e7c03.png)

![图片](https://user-images.githubusercontent.com/7112268/55474402-a1de2a80-5643-11e9-8183-428d81bb3ff7.png)

![图片](https://user-images.githubusercontent.com/7112268/55474501-e79af300-5643-11e9-8c23-430eb20e4110.png)

**Comment by gmx321** [comment]
另外，刚刚注意到电脑风扇一直在响，是多个 QtWebEngineProcess.exe 进程占满了cpu。

**Comment by vnpy** [comment]
以上情况是因为操作系统中安装了其他的SSL组件，同时还影响了相关的环境变量，导致PyQt载入ssl模块失败，最简单的方法是重装系统了，或者可以在网上搜搜如何去找到这个SSL组件来修复

**Comment by gmx321** [comment]
已经解决。

具体方法是将 \VNConda\Lib\site-packages\PyQt5\Qt\bin 目录的两个动态库 libeay32.dll和 ssleay32.dll拷贝到 \VNConda\ 下即可。

**Comment by vnpy** [comment]
收到，我们添加到文档中，非常感谢

**Comment by hengkx** [comment]
> 已经解决。
> 
> 具体方法是将 \VNConda\Lib\site-packages\PyQt5\Qt\bin 目录的两个动态库 libeay32.dll和 ssleay32.dll拷贝到 \VNConda\ 下即可。

按照这个不报 `找不到序数`了 但是还是有那个异常

**Comment by gmx321** [comment]
仔细看看报错的内容，可能存在其它问题。请向管理员提问。我也是外行。 liang yan (yanliang) 邮箱：gmx321@gmail.com 签名由 网易邮箱大师 定制 在2019年11月18日 02:48，Tom Xu 写道： 已经解决。 具体方法是将 \VNConda\Lib\site-packages\PyQt5\Qt\bin 目录的两个动态库 libeay32.dll和 ssleay32.dll拷贝到 \VNConda\ 下即可。 按照这个不报 找不到序数了 但是还是有那个异常 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
