### ISSUE TITLE
已从期货公司获得“产品名称、授权编码”，但vnpy连接时一直提示“交易授权验证失败、CTP:客户端认证失败”

### ISSUE THREAD

**Issue by ieachen** [vnpy/vnpy#1554]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为

如题，本地配置没有问题，期货公司说他那边没有问题，我不确定到底是期货公司还是vnpy的连接问题，会不会是vnpy在验证CTP“产品名称、授权编码”时有bug？

vnpy版本：v2.0和v2.0.1-DEV都试过

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已合并PR，非常感谢
