### ISSUE TITLE
2.01 csv_loader无法保存到数据库

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1559]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda3 Python 3.7 64位
* vn.py版本: 2.01

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
读取csv文件保存到数据库

## 实际程序行为
提示载入成功，但数据库中并没有写入。
https://github.com/vnpy/vnpy/blob/8cb5e73d6538daedad41db51a07a6e6a16ebc567/vnpy/app/csv_loader/engine.py#L95
此处是否应该添加一条execute()语句？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by Rongnian** [comment]
另外写这个issue的时候正在导入，我自己添加了execute()，23万条1m bar导入用了20多分钟，这个时间算正常吗？

**Comment by vnpy** [comment]
@nanoric 请看下吧，另外插入时是否要加上批量操作的代码，参考：http://docs.peewee-orm.com/en/latest/peewee/querying.html

`
from peewee import chunked

# Insert rows 100 at a time.
with db.atomic():
    for batch in chunked(data_source, 100):
        MyModel.insert_many(batch).execute()
`

**Comment by vnpy** [comment]
已修复，非常感谢
