### ISSUE TITLE
vnpy2.0.1 手动stop order bug 

### ISSUE THREAD

**Issue by GladosAI** [vnpy/vnpy#1560]
## 环境
* vn.py版本: 如v2.0.1

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
通过vntrader手动下stoporder，出bug

## 实际程序行为
ctp_gateway中
```
ORDERTYPE_VT2CTP = {
    OrderType.LIMIT: THOST_FTDC_OPT_LimitPrice, 
    OrderType.MARKET: THOST_FTDC_OPT_AnyPrice
}
```
并没有stop的order类型
所以在提交订单时，会显示缺失字段OrderPriceType = “”，send order发送失败。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
恩，我们来在每个接口中加上订单类型过滤

**Comment by GladosAI** [comment]
具体是怎么改

**Comment by vnpy** [comment]
>             "OrderPriceType": ORDERTYPE_VT2CTP.get(req.type, ""),
>             "Direction": DIRECTION_VT2CTP.get(req.direction, ""),
>             "CombOffsetFlag": OFFSET_VT2CTP.get(req.offset, ""),

CTP接口的字段取值函数已经使用了get，无需修改。

手动下单时，需要清楚每个交易所支持的委托类型（几乎所有的都支持限价和市价，其他的不一定），选择错误的必然会导致下单失败了。
