### ISSUE TITLE
vnpy2.0.1 市价下单问题 marketorder bug

### ISSUE THREAD

**Issue by GladosAI** [vnpy/vnpy#1561]
## 环境

* vn.py版本: 如v2.0.1
## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
手动市价下单直接显示已撤单

## 实际程序行为
疑似send order 中字段问题，market order 的timecondition应该为IOC（参考：https://blog.csdn.net/LuyaoYing001/article/details/76619096）

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
simnow的委托类型支持问题
