### ISSUE TITLE
2.01 查询合约提示错误

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1564]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda3 Python 3.7 64位
* vn.py版本: 2.01

## Issue类型
三选一：Question

## 实际程序行为
查询合约时提示错误
ValueError: time data '' does not match format '%Y%m%d'

At:
  C:\Anaconda3\lib\_strptime.py(359): _strptime
  C:\Anaconda3\lib\_strptime.py(577): _strptime_datetime
  D:\code\vnpy\vnpy\gateway\ctp\ctp_gateway.py(555): onRspQryInstrument

通过debug发现是跨期套利合约，没有ExpireDate字段。
data = {dict} <class 'dict'>: {'InstrumentID': 'SPD WH905&WH909', 'ExchangeID': 'CZCE', 'InstrumentName': '跨期套利-WH905/WH909', 'ExchangeInstID': 'SPD WH905&WH909', 'ProductID': 'SPD WH&WH', 'ProductClass': '3', 'DeliveryYear': 0, 'DeliveryMonth': 0, 'MaxMarketOrderVolume': 1000, 'MinMarketOrderVolume': 1, 'MaxLimitOrderVolume': 1000, 'MinLimitOrderVolume': 1, 'VolumeMultiple': 1, 'PriceTick': 1.0, 'CreateDate': '', 'OpenDate': '', 'ExpireDate': '', 'StartDelivDate': '', 'EndDelivDate': '', 'InstLifePhase': '1', 'IsTrading': 1, 'PositionType': '2', 'PositionDateType': '2', 'LongMarginRatio': 0.0, 'ShortMarginRatio': 0.0, 'MaxMarginSideAlgorithm': '0', 'UnderlyingInstrID': '', 'StrikePrice': 0.0, 'OptionsType': '\x00', 'UnderlyingMultiple': 1.0, 'CombinationType': '0'}
 'InstrumentID' (2445799505776) = {str} 'SPD WH905&WH909'
 'ExchangeID' (2445799504112) = {str} 'CZCE'
 'InstrumentName' (2445799504048) = {str} '跨期套利-WH905/WH909'
 'ExchangeInstID' (2445799505840) = {str} 'SPD WH905&WH909'
 'ProductID' (2445799503856) = {str} 'SPD WH&WH'
 'ProductClass' (2445799503664) = {str} '3'
 'DeliveryYear' (2445799503600) = {int} 0
 'DeliveryMonth' (2445799503536) = {int} 0
 'MaxMarketOrderVolume' (2445752586432) = {int} 1000
 'MinMarketOrderVolume' (2445752586720) = {int} 1
 'MaxLimitOrderVolume' (2445752478432) = {int} 1000
 'MinLimitOrderVolume' (2445752479512) = {int} 1
 'VolumeMultiple' (2445799503472) = {int} 1
 'PriceTick' (2445799503408) = {float} 1.0
 'CreateDate' (2445799503344) = {str} ''
 'OpenDate' (2445799503280) = {str} ''
 'ExpireDate' (2445799503216) = {str} ''
 'StartDelivDate' (2445799503152) = {str} ''
 'EndDelivDate' (2445799503088) = {str} ''
 'InstLifePhase' (2445799502960) = {str} '1'
 'IsTrading' (2445799502896) = {int} 1
 'PositionType' (2445799502768) = {str} '2'
 'PositionDateType' (2445752479080) = {str} '2'
 'LongMarginRatio' (2445799502448) = {float} 0.0
 'ShortMarginRatio' (2445752477784) = {float} 0.0
 'MaxMarginSideAlgorithm' (2445752282616) = {str} '0'
 'UnderlyingInstrID' (2445796625264) = {str} ''
 'StrikePrice' (2445799502832) = {float} 0.0
 'OptionsType' (2445799503024) = {str} '

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
DEV分支已经修复了
