### ISSUE TITLE
okex gateway bug

### ISSUE THREAD

**Issue by qqqlyx** [vnpy/vnpy#1566]
## 环境

* 操作系统: Windows 10
* Anaconda 18.12 Python 3.7 64位
* vn.py dev branch 2019/04/08

## Issue类型
Bug

## 预期程序行为
连接okex

## 实际程序行为
触发异常，状态码：<class 'requests.exceptions.ProxyError'>，信息：HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /api/spot/v3/instruments (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000027805B55A20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

## 重现步骤
已测试阿里云和腾讯云都有该问题，若不填写‘代理地址’则可以正常连接；若填写(127.0.01)则会有以上报错。

**Comment by vnpy** [comment]
收到，我们来把默认的代理参数移除掉

**Comment by vnpy** [comment]
已在DEV分支处理
