### ISSUE TITLE
RQData和vnpy分钟线时间不对应

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1573]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
RQData提供的1分钟数据时间戳是close的时间，而vnpy的BarGenerator提供的1分钟时间戳是open的时间。例如RQData股指期货的时间应该是9:31~15:00，vnpy则是9:30~14:59。对于一些需要使用时间信息的策略，这样会导致用RQData的数据进行回测结果和实际数据不一致。另外在开盘后读取RQData初始化，也会产生一些差异。vnpy内部使用RQData的地方是否需要统一一下?

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
