### ISSUE TITLE
提问，实盘中有用vnpy做日内稳定盈利的吗？

### ISSUE THREAD

**Issue by ssh352** [vnpy/vnpy#1577]
比如做螺纹钢，甲醇日内交易，当日平仓，对市场竞争难度毫无概念，谢谢指教

**Comment by vnpy** [comment]
交易能否赚钱，一个看策略，一个看运维以及管理经验，这些都不是软件能解决的问题，另外想聊策略的话题可以去官方交流QQ群讨论：262656087
