### ISSUE TITLE
关于 cta_strategy backtesting 中回测结果计算的相关问题

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#1579]
我看 vnpy2 中的  cta_strategy backtesting 回测结果计算中，去掉了 vnpy1 中的 tradingResults 的部分，这块是怎么考虑的？

我理解 vnpy1 中 tradingResults 就是做交易配对，把开、平交易配对为交易结果，方便做一些指标核算，比如交易胜率等。是这样吗？

不过如果下单时把单子拆的比较小，用 vnpy1 里的配对方法就会让 tradingResults 变的比较凌乱，我理解没错吧？

@vnpy

**Comment by vnpy** [comment]
1. 去掉的主要原因是发现大家用的不多，另外确实按日统计的模式更容易理解一些，为了简化代码就去了
2. 如果每次下单交易数量不是固定的，存在频繁的加减仓操作，是会导致记录比较乱一些，但不会影响程序的统计（毕竟程序就擅长这个）

**Comment by Gwill** [comment]
Thanks!
