### ISSUE TITLE
why not using Signal to update the StatusBar info in vn.trader?

### ISSUE THREAD

**Issue by 4ever911** [vnpy/vnpy#158]
I don't know if it's a bug here. It doesn't crash either.  I am just curious about that why not using Signal here to update the UI, coz these codes are running within two different threads.

**Comment by vnpy** [comment]
Can you please paste the code here?

**Comment by 4ever911** [comment]
master/vn.trader/uiMainWindow.py

 def initStatusBar(self):
        """初始化状态栏"""
        self.statusLabel = QtGui.QLabel()
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeft)
        
        self.statusBar().addPermanentWidget(self.statusLabel)
        self.statusLabel.setText(self.getCpuMemory())
        
        self.sbCount = 0
        self.sbTrigger = 10     # 10秒刷新一次
        self.eventEngine.register(EVENT_TIMER, self.updateStatusBar)


Please see the code above, especially the last line.

I am not familiar with Python. It seams that the Timer is called from another thread, and the status bar is created in the main UI thread. Can we just call updateStatusBar directly here?

Anyway, it works right now.

**Comment by vnpy** [comment]
This is a bug which has been fixed in the dev branch. Please have a look.
