### ISSUE TITLE
实盘账户组合套利合约显示出错，合约查询中仍然没有郑州和大连的套利合约

### ISSUE THREAD

**Issue by fanchuan8848** [vnpy/vnpy#1580]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.1dev 20190411（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
实盘账户 持仓显示 SP m1905&m1909 套利合约情况

## 实际程序行为
所有持仓情况都未显示 包括rb1910合约，合约查询也未找到套利合约 如：SP m1905&m1909

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

 
At:
  D:\python\vnpy-2.0.1\vnpy\gateway\ctp\ctp_gateway.py(484): onRspQryInvestorPosition

KeyError: ('SP m1905&m1909',)

At:
  D:\python\vnpy-2.0.1\vnpy\gateway\ctp\ctp_gateway.py(484): onRspQryInvestorPosition

KeyError: ('SPD RM905&RM909',)

At:
  D:\python\vnpy-2.0.1\vnpy\gateway\ctp\ctp_gateway.py(484): onRspQryInvestorPosition

KeyError: ('SP m1905&m1909',)

**Comment by vnpy** [comment]
已修复
