### ISSUE TITLE
这个计时器线程没多大用呀，多消耗一个线程

### ISSUE THREAD

**Issue by aki** [vnpy/vnpy#1588]
https://github.com/vnpy/vnpy/blob/ebbc4f2304f5f191bb116246446d0d5f7e469830/vnpy/event/engine.py#L11

def _run_timer(self):
        """
        Sleep by interval second(s) and then generate a timer event.
        """
        while self._active:
            sleep(self._interval)
            event = Event(EVENT_TIMER)
            self.put(event)

**Comment by vnpy** [comment]
有其他实现方案欢迎提供建议

**Comment by sixkingdoms** [comment]
我觉得timer 还是挺有用的。 比如可以根据时间来决定是不是启动相应的命令， 或者退出程序。
