### ISSUE TITLE
一个数据转换的问题

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1590]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

因为RQData过期了，就试着把老版的DataRecord搬到的新系统里，但是在把数据插入到mongo的时候，BarData中的exchange是Exchange类型，无法转换，pymongo报错：
bson.errors.InvalidDocument: Cannot encode object: <Exchange.SHFE: 'SHFE'>，
那个的大神处理过这个问题。

**Comment by jingwei1982** [comment]
后边加个.value就可以了

**Comment by mumuwoyou** [comment]
我做了一个copy，不能直接取d[‘exchange’].value赋值给d[‘exchange’]，但不知是否会拖慢行情记录处理速度，尤其是TickData的插入。
