### ISSUE TITLE
新版本的LogEngine的单例模式无效

### ISSUE THREAD

**Issue by mumuwoyou** [vnpy/vnpy#1594]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 预期程序行为

ee = EventEngine()
me = MainEngine(ee)
le = LogEngine(main_engine=me, event_engine=ee)
le.add_console_handler()
le.info(u'启动行情记录运行子进程')

## 实际程序行为

2019-04-13 22:14:50,522  INFO: 启动行情记录运行子进程
2019-04-13 22:14:50,522  INFO: 启动行情记录运行子进程
2019-04-13 22:14:50,522  INFO: 启动行情记录运行子进程

是否可以回到了老版的LogEngine

**Comment by vnpy** [comment]
无人值守模式我们将在后续版本中提供，不再采用之前的单例方法了
