### ISSUE TITLE
CTA策略无法生成60分钟以上K线

### ISSUE THREAD

**Issue by aijy** [vnpy/vnpy#1604]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

utility.py中BarGenerator生成K线的代码无法产生60分以上周期的K线，问题代码如下：
        if not (bar.datetime.minute + 1) % self.xmin:
            self.xmin_bar.datetime = self.xmin_bar.datetime.replace(
                second=0, microsecond=0
            )
            self.on_xmin_bar(self.xmin_bar)
测试中，最多只能生成60分钟K线，目测是这段代码有问题。

**Comment by vnpy** [comment]
BarGenerator的设计就是为了60分钟以内的K线使用的，我们后续升级支持下更高的周期吧

**Comment by chuckzhao12** [comment]
if bar.datetime >= (self.xmin_bar.datetime + datetime.timedelta(minutes=self.xmin - 1)):

我是这样修改了一下，不过测试了一下，效率比较低，跟旧版相差10倍以上吧。
目前我是在init中判断了一下，60分钟以内用原版的，60分钟以上的合成用timedelta的方法。
期待更好的解决办法。

**Comment by vnpy** [comment]
已添加对小时线合成的支持，1小时线的合成依赖对于时间戳小时变化的判断，N小时的合成依赖于1小时判断的累加
