### ISSUE TITLE
使用vs2015编译发生异常。

### ISSUE THREAD

**Issue by xuwei0455** [vnpy/vnpy#161]
我在使用vs2015编译时，出现以下错误。

![image](https://cloud.githubusercontent.com/assets/12061884/19310711/04ec01ea-90be-11e6-84c8-b4d9c0aac1f2.png)

由于以前没有使用过C++进行编程，并不清楚是怎么回事，网上搜索过以后，猜测是没有包含python的libs，但是在链接器中已经添加了anaconda的libs，按理应该不会出现这样的情况。

请问可能是什么原因呢？

**Comment by vnpy** [comment]
检查下你的工具版本和环境，需要：
1. Anaconda 2.7 32位
2. Windows 7或者以上环境
3. Boost编译时必须选用之前的Anaconda作为python环境

**Comment by xuwei0455** [comment]
Thanks for reply。

我使用的是anaconda 64位，看到教程有提醒使用32位，但本着实践求职的原则，我还是使用了64位，看起来是碰到了兼容性问题，现在我想着手解决这个问题，请问有什么思路么？

**Comment by vnpy** [comment]
先检查下你的编译配置是否设为了64位的，默认是32的。64位编译我自己也没做过，不是特别清楚了。

另外有用户反应VS2013的一些基础库存在兼容性问题，微软做了不向后兼容的升级。

**Comment by xuwei0455** [comment]
@vnpy 
多谢你的意见，经过排查，确定使用VS2015编译64位的API需要注意一下几点。

1.Boost需要重新编译，编译需加上参数address-model=64，另吐槽下全部编译耗时太久了，折腾了好久。

2.Anaconda应使用64位，这个没有试验32是否会异常，不过按理来说使用32位是编译不过的。

3.API的lib/dll需要重新下载64位的版本，不然在链接的时候会报异常。

大概就是这些了，每个模块单独编译太累了，有时间我研究下弄个脚本批量编译，弄出来了再发pull request。

最后，再次感谢你的帮助。

**Comment by vnpy** [comment]
恭喜成功出坑！
