### ISSUE TITLE
是否可以编写介绍函数功能的开发文档?

### ISSUE THREAD

**Issue by arthurire** [vnpy/vnpy#1620]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Python 3.7 Anaconda latest
* vn.py版本: v2.0.2

## Issue类型
三选一：Question

## 预期程序行为
是否有 document 简单介绍每个函数的功能和基本用法(类似Pandas/Numpy 等包的开发文档)?目前认为很难实现功能.

预期行为:

例如:
1. 我自己编写一个CalcPosition()函数,可以输出当前对应的合约和仓位.
2. 从 vnpy 得到持仓列表,从而计算我现在需要下什么样的单.
3. 调用 vnpy 的下单函数进行下单.

当然细节是可以进一步改进的,例如下单方式和挂单,撤单等.

但是我现在遇到的第一个问题是,我不能从 wiki 里面看出 vnpy 这个包括什么函数. 不知道用什么函数挂单, 查成交 etc. 我当然可以去读现成的策略文件,但是这样开发效率极低.

## 实际程序行为

无行为

**Comment by vnpy** [comment]
已在官网提供文档：https://www.vnpy.com/docs/#/
