### ISSUE TITLE
CTA图形化回测模块--数据下载问题

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#1622]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
希望使用RQData下载IF88的1小时数据，程序报错；并且CTA回测模块停止运行（不能继续下载其他数据）
## 原因
RQData里面get_price()函数的frequency字段是对应图形化界面的“K线周期”。
而frequency字段只接受分钟/日线级别，即1m、2m、1d。

## 建议
1）在图形化界面是“K线周期“上规定只能选择1m、1h、1d；并且在cta_backtester里面的engine上加入对K线周期数值进行转换，如1h要转换成60m，frequency=60m是可以使用RQData下载的。

2）使用try--catch来补足字段填写错误的异常，并且显示在日志上。

**Comment by vnpy** [comment]
已修复
