### ISSUE TITLE
富途接口断线重连功能

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1625]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda3 Python 3.7 64位
* vn.py版本: 2.02

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为

如因网络连接等原因导致富途接口断开，等网络恢复后FutuOpenD会恢复重连，但vnpy中不再更新行情。如何在futuGateway中实现断线重连功能？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by loadatom** [comment]
是订阅了什么数据？OpenD用的哪个版本？

**Comment by vnpy** [comment]
请富途团队的人做了测试，无法重现，检查下使用的是否是最新版本吧，然后可以加富途的这个群和他们核心团队交流：108534288

**Comment by Rongnian** [comment]
> 请富途团队的人做了测试，无法重现，检查下使用的是否是最新版本吧，然后可以加富途的这个群和他们核心团队交流：108534288

FutuOpenD，futu-api和vnpy都是用的最新版本。
FutuOpenD是能断线重连的，没有问题。但vnpy已经订阅的合约不再更新行情，如果从主界面中输入一个新合约，新合约还是能正常推送行情的。这说明问题不在FutuOpenD或者futu-api上，而是vnpy的futuGateway中没有处理OpenQuoteContext断线重连后发生的一些变化吧，例如OpenQuoteContext在重连后会进行一次重新订阅，生成新的订阅list，这个操作是否会导致Gateway中注册的行情回调函数失效？
这个问题和现象我观察了很久，相信以后还会有人遇到。富途量化的群里面响应都很慢，一般回答问题也回答不到点上，建议vnpy团队和富途联系是否能改进这个问题？

如果无法改进也无妨，除了重启程序，是否有其他方式能够恢复行情订阅？

**Comment by Rongnian** [comment]
> 是订阅了什么数据？OpenD用的哪个版本？

订阅的A股指数数据。OpenD用的是1.09版

**Comment by FutunnOpen** [comment]
hello，可以加我QQ看看 82317916

**Comment by vnpy** [comment]
确认由FutuOpenD内部修复

**Comment by Rongnian** [comment]
> hello，可以加我QQ看看 82317916

请问修复完了吗？

**Comment by Fly216** [comment]
你好你好，请问找到了除了重启程序之外，其他方式能够恢复行情订阅/断线自动重连的方法吗？
