### ISSUE TITLE
隔夜模式、开盘价成交，如何在vn.py中实现

### ISSUE THREAD

**Issue by haoliang1986** [vnpy/vnpy#1627]
在隔夜模式下，新交易日的开盘价是在第一个tick到达时才能知道吧，这种情况下如何在实盘和回测中怎么实现啊？

**Comment by vnpy** [comment]
这种隔夜立即成交的情况，回测和实盘需要区别处理了：
* 回测：在前一天最后一根K线直接下单，无论限价单、停止单，价格足够远保证能触发就行
* 实盘：在策略on_start函数里处理，启动策略时立即将昨日收盘潜在的委托下出去，并在集合竞价开始后才启动你的策略
