### ISSUE TITLE
关于重构项目的想法

### ISSUE THREAD

**Issue by xuwei0455** [vnpy/vnpy#163]
个人感觉项目的结构只是单纯的区分了各个模块，并没有较好的区分底层的引擎及中层的接口。

所以尝试对整个项目进行了重构，大致目录如下。
![image](https://cloud.githubusercontent.com/assets/12061884/19388357/c88129f2-9251-11e6-9b8d-0982f15034e6.png)

主要有如下改动：
1.将分散在各目录下的DLL/LIB集中起来，放在ext目录下，减少文件的重复，既可以减少空间的占用，又降低了编译的麻烦程度。

2.配置、测试、临时文件等全部放入顶级目录，便于配置和维护。

由于整个项目改动较大，暂时只完成了CTP接口的重构。

另由于重构并没有使用之前的版本，所以也没办法发pull request，就先发个issues吧。

**Comment by vnpy** [comment]
目前vn.trader的架构是面向开源模式，可插拔的模块化结构，比如增加一个XTP接口，就直接添加一个xtpGateway文件夹，然后所有相关文件放在一起。当然如果你有需求可以改成以上的形式，但是短期内目前的目录没有变更的计划。

**Comment by xuwei0455** [comment]
多谢回复。

以上结构同样可以满足模块化设计的要求，只需在gate目录下添加相应接口，然后将对应扩展的DLL/LIB文件放入ext目录即可。

个人认为这个目录更加利于对项目的理解及维护，仅作为参考，以上。

**Comment by solobear** [comment]
感觉想法很好啊, 目录结构会清晰很多,xuwei0455 自己fork一个改下呗

**Comment by vnpy** [comment]
我也建议可以先做一个，然后我们另外开一个vn.py的分支，看看用户的反应。

**Comment by xuwei0455** [comment]
@vnpy @solobear 
目前已经完成了CTP接口的重构，但是由于我用的是最新的64位接口，可能存在一些兼容性的问题，我正在着手处理。

例：
1. EXCHANGE_ID返回值未定义，返回201或203等其他数值。
2. 委托订单数据异常（缺少方向、开平、价格数据，委托数量错误，委托时间乱码等），暂未排查出是哪里出现了异常。
3. 错误日志处，只返回了错误代码，但没有相对应的message。

对于以上问题，我找了一下官方文档，定义只到了接口这一层，再详细的文档就没有了，请问是否有其他文档或相关资料可以参考？

**Comment by vnpy** [comment]
主要是看官方.h头文件里的一些定义。

**Comment by xuwei0455** [comment]
好的，多谢你的提醒，我尝试排查、修复一下。

**Comment by xuwei0455** [comment]
求助！

调用发单接口reqOrderInsert，一直报异常，关键还不是走的正常的回调函数，而是通过onRspError,错误信息如下：

{'ErrorMsg': '', 'ErrorID': 960051513}

被这个问题卡了两天了，找不到相关资料。。想加群交流一下。。无奈不知道加群问题的答案。被拒。

希望能得到一些帮助。

**Comment by vnpy** [comment]
你QQ多少的，我拉你进来吧

**Comment by xuwei0455** [comment]
QQ在知乎私信给你了。

**Comment by gzguozhen** [comment]
QQ：271594070
谢谢您！


在 2016-10-20 09:26:12，"vn.py" <notifications@github.com> 写道： 你QQ多少的，我拉你进来吧

**Comment by alan12140** [comment]
我也碰到了'ErrorID': 960051513，不知道题主最后发现问题了吗，如何解决的。万分感谢
