### ISSUE TITLE
backtesting.py 存在语法错误

### ISSUE THREAD

**Issue by Yoncise** [vnpy/vnpy#1632]
## 环境

* 操作系统: Mac
* Anaconda版本: conda 4.6.11
* vn.py版本: tag 2.0.2

## Issue类型
Bug

## 预期程序行为

可以跑回测

## 实际程序行为

语法错误

## 重现步骤

vnpy/app/cta_strategy/backtesting.py 文件 run_backtesting 函数, ix 变量未正确定义.

![image](https://user-images.githubusercontent.com/4560467/56744880-e6c13100-67ab-11e9-88b7-b819587658d8.png)

**Comment by Rongnian** [comment]
前面 for ix, data in enumerate(self.history_data):
已经定义了ix，当初始化所需要的数据用完时结束循环，后面从第ix个数据开始回测。

**Comment by Yoncise** [comment]
前面定义的 ix 的作用域只到 for 循环体的。 我这边 python 3.7 实际运行会报语法错误

**Comment by Rongnian** [comment]
for循环索引变量作用域是在循环结束后还是存在的。出现未定义错误说明self.history_data是一个空list，也就是回测没有加载到数据。

**Comment by Yoncise** [comment]
你说的不错，是我对python不太了解所以理解错了，确实是因为历史数据为空所以ix未定义。不过针对历史数据为空的这种情况还是应该更优雅的处理下的

**Comment by vnpy** [comment]
已修改，谢谢
