### ISSUE TITLE
2.02版本成交推送过滤

### ISSUE THREAD

**Issue by Rongnian** [vnpy/vnpy#1633]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda3 Python 3.7 64位
* vn.py版本: 2.02
## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
2.02版本在CtaEngine的process_trade_event函数中没有对成交回报进行过滤，但在1.9.2版本中时有过滤的，后续vnpy2是否有计划将1.9.2中的功能移植到新版本上？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修改，谢谢
