### ISSUE TITLE
rqdata的query_bar的价格和交易量漏了浮点转换

### ISSUE THREAD

**Issue by ikale** [vnpy/vnpy#1639]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 实际程序行为
应该加上浮点转换
                open_price=float(row["open"]),
                high_price=float(row["high"]),
                low_price=float(row["low"]),
                close_price=float(row["close"]),
                volume=float(row["volume"]),

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
rqdatac返回的DF里原始数据就是float和int类型的，为什么还需要转换？

**Comment by ikale** [comment]
不知道什么原因一直获取的数据是空的，
调试模式下可以看到RQ是有数据过来的但是最后的返回确是个空的列表
加了浮点转换就正常了

**Comment by ikale** [comment]
今天试了去掉转换又可以获取到正常的返回

**Comment by vnpy** [comment]
好的，可能是服务端调试升级导致的吧
