### ISSUE TITLE
MongoDB 写入数据库出错，名称不应该使用vt_symbol的点连接方式

### ISSUE THREAD

**Issue by ikale** [vnpy/vnpy#1640]
# 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
database的名称是用vt_symbol 造成不能入库失败

## 实际程序行为
无法将数据写入MongoDB数据库

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
pymongo.errors.InvalidName: database names cannot contain the character '.'

**Comment by xldistance** [comment]
我也觉得用_连接symbol和exchange比较好，rb1910_SHFE这样子

**Comment by vnpy** [comment]
什么版本的vn.py？现在2.0.2的数据库范式不是用vt_symbol做数据库名的

**Comment by ikale** [comment]
2.0.2数据库名在哪定义和创建的？

**Comment by xldistance** [comment]
> 什么版本的vn.py？现在2.0.2的数据库范式不是用vt_symbol做数据库名的

vtsymbol也不应该用.连接symbol和exchange。。。。。。

**Comment by vnpy** [comment]
> 2.0.2数据库名在哪定义和创建的？

vnpy/trader/database目录下
