### ISSUE TITLE
今后vnpy要对接股市，那么数据库如何处理复权数据问题，是否应支持自定义添加字段？

### ISSUE THREAD

**Issue by TraderWithPython** [vnpy/vnpy#1645]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: 2.02

## Issue类型
Enhancement

## 疑问
1、根据app.csvloader，vnpy的数据类型构成是"Datetime","Open","High","Low","Close","Volume"。对于股票来说，信号的计算一般使用前复权数据，但若股票发生股票除权，其先的除权数据都应得到全部的更新，是否应该给予一定的数据库自动更新处理机制。
2、是否应添加"adjopen","adjlow"等字段？
另外，vnpy的数据导入是否应借鉴一下backtrader，在数据导入重除了要求的输入之外可以自定义一些其他的数据字段，如宏观数据等？

**Comment by vnpy** [comment]
vn.py核心定位还是交易系统，策略这块重点也是在实盘交易方面，除权除息类的业务逻辑深入来看十分负责，需要专业数据团队或者数据服务商来解决，并不适合在vn.py中处理
