### ISSUE TITLE
convertrer.py -> PositionHolding -> calculate_frozen() 存在问题

### ISSUE THREAD

**Issue by iPoring** [vnpy/vnpy#1646]
## 环境

* 操作系统: Windows 10
* Anaconda版本:  Python 3.7 64位
* vn.py版本: v2.0.1

## Issue类型
Bug

## 预期程序行为
多头平仓，计算多头今仓可平量时，使用self.long_td
空头平仓，计算空头今仓可平量时，使用self.short_td

## 实际程序行为
多头平仓和空头平仓，计算今仓时都使用了self.short_td

## 重现步骤

![image](https://user-images.githubusercontent.com/34330384/56874421-58c79d80-6a6c-11e9-9004-60d4ea8ad8a5.png)

**Comment by vnpy** [comment]
已修复
