### ISSUE TITLE
策略初始化时，可变对象parameters[]和variables[]没有重新创建，似乎导致一些问题

### ISSUE THREAD

**Issue by iPoring** [vnpy/vnpy#1647]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Python 3.7 64位
* vn.py版本: v2.0.1

## Issue类型
Bug

## 重现步骤
同时初始化多个策略，CtaTemplate 中
self.variables.insert(0, "inited")
self.variables.insert(1, "trading")
self.variables.insert(2, "pos")
三个函数被调用多次，导致策略variables[]中 'inited' 'trading' 'pos' 被多次添加

![image](https://user-images.githubusercontent.com/34330384/56874855-50249680-6a6f-11e9-9319-11c7f063483a.png)

**Comment by vnpy** [comment]
每个策略都要在类的定义里自己重新创建parameters和variables的列表啊，这是必须的操作
