### ISSUE TITLE
vnpy2 什么时候集成zipline?

### ISSUE THREAD

**Issue by czonghui** [vnpy/vnpy#1661]
RT

**Comment by vnpy** [comment]
研究了一个多月的时间，目前选型上偏向RQAlpha，设计和适配性都更好，但尚未最终确定

**Comment by KobeZhao** [comment]
quantOS怎么样呢

**Comment by zfsamzfsam** [comment]
对接BackTrader

**Comment by vnpy** [comment]
> quantOS怎么样呢

没人维护了

**Comment by vnpy** [comment]
> 对接BackTrader

看了下BackTrader的策略模块设计和CTA引擎是重复的类型，对接没有意义
