### ISSUE TITLE
Bardata存储方式，造成数据库性能压力

### ISSUE THREAD

**Issue by qzm** [vnpy/vnpy#1662]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Anaconda 5.2.0
* vn.py版本: v2.0.2
## Issue类型
三选一：Enhancement

## 预期程序行为
在数据很多的时候，不会因为表存储方式造成性能压力，希望对不同的合约品种，做分表处理。

## 实际程序行为
所有的合约品种都存储在一个 Table里面，当品种数量比较多的时候，时间跨度比较大的时候，整体的性能就会非常的差。

## 重现步骤
使用MySql数据库，全品种的主连合约分钟数据，有五千多万条，使用vnpy默认的 load_data.py 文件导入，数据全部存储在一个Table里面

![捕获](https://user-images.githubusercontent.com/2801450/57196584-dfaad780-6f90-11e9-9444-3c3ef0a2de24.PNG)

**Comment by nanoric** [comment]
以后会考虑分表的，谢谢你的建议^_^

**Comment by vnpy** [comment]
后续会增加对KDB数据库的支持，如果确实遇到性能瓶颈可以使用这个

**Comment by qzm** [comment]
已经提了一个pr，修复索引的问题，能解决这个瓶颈
