### ISSUE TITLE
锁仓模式下的委托转换offset判断问题？

### ISSUE THREAD

**Issue by zhouzhuofu** [vnpy/vnpy#1664]
https://github.com/vnpy/vnpy/blob/32926f1883b7c97257961af49e4385a568af9f37/vnpy/app/cta_strategy/converter.py#L264
-----------------------------------------------------------
问题：这里的锁仓模式下的委托转换方法，是不是需要判断一下原委托的offset？

e.g.：如果初始化时账户没有任何仓位，并且在锁仓模式下发了开仓委托，最后返回的req_list就是空列表了？

**Comment by vnpy** [comment]
在内部的convert_order_request_shfe和convert_order_request_lock里判断了

**Comment by zhouzhuofu** [comment]
![image](https://user-images.githubusercontent.com/9351159/57864445-79df0b00-782e-11e9-9a33-8f31e09cea4f.png)

convert_order_request_lock() 方法里面没有判断：
“”“
        if req.offset == Offset.OPEN:
            return [req]
”“”

convert_order_request_shfe()方法里面是有判断的。

这应该还是统一一下的吧？
