### ISSUE TITLE
ctp_se ubuntu 编译wheel报错 

### ISSUE THREAD

**Issue by somewheve** [vnpy/vnpy#1665]
## 环境

* 操作系统:Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: ctp_se下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
安装成功

## 实际程序行为
    /home/vnpy/anaconda3/compiler_compat/ld: cannot find -lthosttraderapi
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

## 重现步骤
bash install.sh

安装２．ｘ不会报错　

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
ctp_se分支尚未完成对ubuntu的支持

**Comment by somewheve** [comment]
那大概要等多久?
