### ISSUE TITLE
cmake build files should not be in git control

### ISSUE THREAD

**Issue by ssh352** [vnpy/vnpy#1671]
整个build dir不应该在git repo里 
例子：
<img width="511" alt="Screen Shot 2019-05-07 at 5 12 08 PM" src="https://user-images.githubusercontent.com/41779116/57288054-578d1500-70eb-11e9-8907-443a97f3b7e4.png">

**Comment by vnpy** [comment]
2.0已经转为使用ib官方的Python API，没有这个了
