### ISSUE TITLE
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'

### ISSUE THREAD

**Issue by listplot3d** [vnpy/vnpy#1686]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.2发行版（2019.05.11）

## Issue类型
三选一：Bug

## 预期程序行为
bash install.sh完成安装后可以运行run,py

## 实际程序行为
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'

## 重现步骤
看到vnpy1.9.2版本中的install.sh有编译ctpmd的部分,但是在2.0.2的install.sh中没有了.是不是要加上?

**Comment by hlxstc** [comment]
Linux操作系统需要重新编译一下

**Comment by vnpy** [comment]
2.0之后的linux相关编译都写到了setup.py中
