### ISSUE TITLE
点击VN Station 报错 JSONDecodeError 无法打开界面

### ISSUE THREAD

**Issue by wilsonkrum** [vnpy/vnpy#1687]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.1发行版

## Issue类型
三选一：Bug

## 预期程序行为
点击VN Station,打开界面

## 实际程序行为
报错
![20190512165453](https://user-images.githubusercontent.com/15355021/57579981-baf5b900-74d6-11e9-99e4-bec94b831d55.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
之前是否弹出了某个dll找不到的错误提示？

**Comment by nanoric** [comment]
这个问题在新版本中已修复。
在老版本总出现这个问题一般是网络问题造成的。
