### ISSUE TITLE
orderId in sendOrder()

### ISSUE THREAD

**Issue by chrjxj** [vnpy/vnpy#169]
In sendOrder(), do you just increase orderId twice? 

        self.orderId += 1

        # 查询下一个有效编号
        self.connection.reqIds(1)

Use self.connection.reqIds(1) should be fine. IB host will return a not-used orderID to client, and thus next time when placing an order, sendOrder function doesn't need to self.orderId++

**Comment by vnpy** [comment]
The function "reqIds" is an async function and the next valid id information will be pushed in the callback "nextValidId". 

Just in case that you send orders too fast for the callback to push the new id data, we choose to increase the self.orderId by ourselves.
