### ISSUE TITLE
请问：2.0有linux的CTP的库吗？在ctp里只看到了pyd文件，没有.so文件

### ISSUE THREAD

**Issue by wacquser** [vnpy/vnpy#1709]
请问：2.0有linux的CTP的库吗？在ctp里只看到了pyd文件，没有.so文件

**Comment by williamlfang** [comment]
![Selection_068](https://user-images.githubusercontent.com/5860824/57831802-b0923280-77e8-11e9-86f6-af828e1c0f86.png)

**Comment by williamlfang** [comment]
可以自己编译

![Selection_069](https://user-images.githubusercontent.com/5860824/57831889-e8997580-77e8-11e9-9247-a7e668022bf0.png)

**Comment by vnpy** [comment]
运行setup.py安装的时候会自动编译
