### ISSUE TITLE
在查看净值曲线时return 为0，但是balance 仍在变化，而且由正变成负的

### ISSUE THREAD

**Issue by wilsonkrum** [vnpy/vnpy#1711]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 2.0.2

## Issue类型
三选一：Bug

## 预期程序行为
![%M9LDI(JS6P``LT8 K2@TJN](https://user-images.githubusercontent.com/15355021/57832836-2b5c4d00-77eb-11e9-9925-97c433bcab8a.jpg)

## 实际程序行为
不知为何，图中2016.5.31 return 为0，但是balance 还在变化，而且由正变成负的。。
![TIM图片20190516150054](https://user-images.githubusercontent.com/15355021/57832940-6e1e2500-77eb-11e9-94f9-2f1dc66dbc30.jpg)

## 重现步骤
# =============================================================
import pandas as pd 
import numpy as np 

#%%
from vnpy.app.cta_strategy.backtesting import BacktestingEngine, OptimizationSetting
#from vnpy.app.cta_strategy.strategies.atr_rsi_strategy import (
#    AtrRsiStrategy,
#)
from vnpy.app.cta_strategy.strategies.turtle_signal_strategy import (
    TurtleSignalStrategy,
)

from datetime import datetime

#%%
engine = BacktestingEngine()
engine.set_parameters(
    vt_symbol="IF99.CFFEX",
    interval="1m",
    start=datetime(2015, 1, 1),
    end=datetime(2018, 12, 30),
    rate=0.3/10000,
    slippage=0.2,
    size=300,
    pricetick=0.2,
    capital=1_000_000,
)
engine.add_strategy(TurtleSignalStrategy,{'entry_window': 47, 'exit_window': 10, 'atr_window': 18})
#{'entry_window': 37, 'exit_window': 14}
#%%
engine.load_data()
engine.run_backtesting()
df = engine.calculate_result()
#==============================================================

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by 1122455801** [comment]
bug，
原因是df["return"] = np.log(df["balance"] / df["balance"].shift(1)).fillna(0)。若balance前后为一正一负，则计算结果为None，被0填充
