### ISSUE TITLE
在内部的convert_order_request_shfe和convert_order_request_lock里，判断offset.open问题？

### ISSUE THREAD

**Issue by zhouzhuofu** [vnpy/vnpy#1713]
在内部的convert_order_request_shfe和convert_order_request_lock里判断了

_Originally posted by @vnpy in https://github.com/vnpy/vnpy/issues/1664#issuecomment-492598237_

convert_order_request_lock()方法里面，并没有判断offset.open的情况，
所以，当td_volume和yd_available 都为0的情况下，在锁仓模式下的下开仓委托转化就会返回空[]吧？

convert_order_request_shfe()方法里面确实有判断。
1.9.2版本中的转化也没有这样的逻辑问题。

是我想错了吗（抱歉不是从事交易这个行业），想刨根问底一下：
我认为，锁仓模式是站在股指这种合约的维度而应用的。所以，如果交易的是股指，那么策略中的buy short sell cover方法中参数lock都是为True的。而一开始，账户是没有任何仓位的，因此，convert_order_request_lock()方法里面的td_volume和yd_available 都为0的情况下，在锁仓模式下的开仓委托转化就会返回空[]吧？
所以这是不符合逻辑的吧？

**Comment by vnpy** [comment]
lock模式下，平仓后剩余数量会全部自动使用开仓，你弄个模拟账号自己试试就知道了
