### ISSUE TITLE
为什么我的VN Station行情没有显示出来

### ISSUE THREAD

**Issue by lylovevision** [vnpy/vnpy#1724]
## 环境

* vnconda

## Issue类型
三选一：Question

## 预期程序行为
vn station中显示行情数据

## 实际程序行为
我去注册了SimNow账号和密码，通过tradenow修改了密码，然后登陆vnstation，把simnow所有ip地址都试过了，行情依旧不显示

能不能给我个答案，还没开始就要绝望了

**Comment by vnpy** [comment]
官网有文档：https://www.vnpy.com/docs/#/quickstart
