### ISSUE TITLE
火币报错连接超时，接口不存在

### ISSUE THREAD

**Issue by hello886** [vnpy/vnpy#1727]
## 环境
* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 4.5.2 Python 3.7 64位（实际使用python2.7环境）
* vn.py版本: v1.9.2LTS 稳定版

## 重现步骤
重现步骤
修改火币配置文件，为自己帐号的appid信息，启动vnTrader下的run.py（注释掉xtpgateway相关，否则无法启动）。
点击连接火币，可以看到右侧行情栏有行情过来，点击下单，报错接口不存在以及不断的连接超时的日志
报错截图：
![image](https://user-images.githubusercontent.com/32973375/58063731-fa489780-7bb1-11e9-951e-f92274b65944.png)

![2019-05-21 10-18-20 的屏幕截图](https://user-images.githubusercontent.com/32973375/58063706-ddac5f80-7bb1-11e9-9a8c-f22daca9b943.png)

怀疑点：火币是否做过接口调整or升级，导致字段等发生差异

**Comment by vnpy** [comment]
火币接口进行过了升级，请使用v2.0.3版本

**Comment by hello886** [comment]
ok，多谢
