### ISSUE TITLE
最新1.9.2LTS含穿透版本报错：ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by hello886** [vnpy/vnpy#1728]
最新的1.9.2LTS含有穿透版本安装有遇到报这个错的么？
ImportError: No module named vnctpmd`

报错上下文：
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from vnpy.trader.gateway import (ctpGateway,ctptestGateway, ibGateway, huobiGateway)
  File "/home/john/anaconda3/envs/vnpy27/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/ctpGateway/__init__.py", line 5, in <module>
    from .ctpGateway import CtpGateway
  File "/home/john/anaconda3/envs/vnpy27/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/john/anaconda3/envs/vnpy27/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/api/ctp/__init__.py", line 4, in <module>
    from .vnctpmd import MdApi
ImportError: No module named vnctpmd

检查安装日志，发现ctp安装时报错了
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CTPAPI_MD_LIBRARY
    linked by target "vnctpmd" in directory /home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp
CTPAPI_TD_LIBRARY
    linked by target "vnctptd" in directory /home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp
-- Configuring incomplete, errors occurred!
See also "/home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".
See also "/home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp/build/CMakeFiles/CMakeError.log".

然后看CMakeError文件
make[1]: 进入目录“/home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_f2940.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_f2940.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_f2940
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f2940.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_f2940.dir/CheckFunctionExists.c.o  -o cmTC_f2940 -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_f2940.dir/build.make:97: recipe for target 'cmTC_f2940' failed
make[1]: *** [cmTC_f2940] Error 1
make[1]: 离开目录“/home/john/PYTHON/GITORG/vnpy/vnpy/api/ctp/build/CMakeFiles/CMakeTmp”
Makefile:126: recipe for target 'cmTC_f2940/fast' failed
make: *** [cmTC_f2940/fast] Error 2

然后就不知道该怎么处理了，那位大神知道啊，谢谢啦

_Originally posted by @hello886 in https://github.com/vnpy/vnpy/issues/1626#issuecomment-494228295_

**Comment by lzd324** [comment]
cmakelist的问题，cmakelist中设置了环境变量CTPAPI_PATH ctpapi/x64_linux，但是1.9.2LTS包中的ctpapi下不存在x64_linux。你可以自己创建一下x64_linux，然后把动态库和相关的.h文件拷贝进去，之后就可以编译通过了。
我主要拷贝了pyscript文件夹下的.h文件、libthosttraderapi_se.so、libthostmduserapi_se.so，这两个so只需要将ctp官方的so加个前缀就好了

**Comment by lostleaf** [comment]
赞楼上老哥 @lzd324 
我的解决方法：
环境 Ubuntu 18.04
1. 将 `/vnpy/vnpy/api/ctp/CMakeLists.txt` 28行改为 `set(CTPAPI_PATH ctpapi)`
2. 将 `/vnpy/vnpy/api/ctp/ctpapi` 和 `/vnpy/vnpy/api/ctp` 目录下 `thosttraderapi_se.so`, `thostmduserapi_se` 分别重命名为 `libthosttraderapi_se.so`, `libthosttraderapi_se.so`
3. 可能需要手动把 `/vnpy/vnpy/api/ctp/build/lib` 下两个 .so 文件拷贝到 `/vnpy/vnpy/api/ctp` 目录

**Comment by vnpy** [comment]
已经修复

**Comment by hello886** [comment]
我的也好了，参考另一篇帖子大神@FuZihao的答案
[https://github.com/vnpy/vnpy/issues/1626#issuecomment-495197614](url)

**Comment by hello886** [comment]
多谢楼上各位大佬~

**Comment by xinhuih** [comment]
我做了这样的修改现在可以import ctpGateway但是我在import ctptestGateway的时候还是会报错ImportError: No module named vnctpmd
请问下你们遇到过这样的问题吗

**Comment by lostleaf** [comment]
@xinhuih 
目测 CMake 还是错的

**Comment by xinhuih** [comment]
多谢！

**Comment by xinhuih** [comment]
我用ctpGateway可以连接仿真环境，不过连不上生产环境，报
Decrypt handshake data failed
CThostFtdcUserApiImplBase::OnSessionDisconnected[0x7fd9280008c8][-421920767][ 4097]
有人知道啥情况吗。我用的是ubuntu 16.04。

**Comment by lostleaf** [comment]
@xinhuih 6.3.13 和 6.3.15 API 不可混用

**Comment by xinhuih** [comment]
@lostleaf ，我看了之前的讨论，没有同时import两个gateway。应该不存在这个问题吧。我直接用的1.9.2-LTS
