### ISSUE TITLE
[vnpy.2.0] Ubuntu 封装 xtp 错误：autocxxpy.clang.cindex.LibclangError

### ISSUE THREAD

**Issue by williamlfang** [vnpy/vnpy#1729]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Anaconda Python 3.7 64位
* vn.py版本: 2.0 (vnpy-xtp-margin)

## Issue类型
三选一：Bug

## 预期程序行为
封装 vnpy/api/xtp/ 接口，提供 xtp_gateway 调用

## 实际程序行为
无法通过编译

> autocxxpy.clang.cindex.LibclangError: /home/william/anaconda3/lib/python3.7/site-packages/autocxxpy/core/../clang/libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().

## 重现步骤

![zsh:2:zoom@zsh-@2 -  workstation  1-_104](https://user-images.githubusercontent.com/5860824/58088481-58e33500-7bf5-11e9-8681-359d0ea6b46a.png)

**Comment by vnpy** [comment]
目前2.0.3的XTP接口并未支持linux
