### ISSUE TITLE
回测数据下载不了

### ISSUE THREAD

**Issue by adzcsx2** [vnpy/vnpy#1730]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

18:56:50	初始化CTA回测引擎
18:56:50	策略文件加载完成
18:57:01	----------------------------------------
18:57:01	IF88.CFFEX-1m开始下载历史数据
18:57:01	数据下载失败，无法获取IF88.CFFEX的历史数据
18:57:08	----------------------------------------
18:57:08	IF88.CFFEX-1m开始下载历史数据
18:57:08	数据下载失败，无法获取IF88.CFFEX的历史数据
18:57:33	----------------------------------------
18:57:33	BTC-USDT-1m开始下载历史数据
18:59:30	已有任务在运行中，请等待完成
18:59:30	已有任务在运行中，请等待完成
19:01:31	已有任务在运行中，请等待完成

下载数据一直卡在这里，无法继续进行下去，我用流量监控没有流量下行，是否能提供进度显示？还是我操作方法有误？

**Comment by vnpy** [comment]
BTC-USDT的合约代码有误，没有交易所后缀，所以下载卡住了
