### ISSUE TITLE
请问为什么现在2.0版本的TickData和BarData中不包含OpenInterest持仓量信息？

### ISSUE THREAD

**Issue by nov12** [vnpy/vnpy#1739]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3

## Issue类型
三选一：Question

## 预期程序行为
为什么现在2.0版本的TickData和BarData中不包含OpenInterest持仓量信息？以前1.9还有，请问出于什么原因决定不包含OpenInterest信息的？

**Comment by vnpy** [comment]
主要因为该数据在交易中没有明显的作用

**Comment by nov12** [comment]
> 主要因为该数据在交易中没有明显的作用

咱现在不是有data record 模块了，如果没有持仓量，对合成指数合约主力合约会有点影响吧…

**Comment by vnpy** [comment]
一个是可以基于成交量切换，另一个是自己加一下了

**Comment by followdao** [comment]
持仓量在期货合约中影响还是蛮大的，希望陈老师能添加，谢谢！

**Comment by followdao** [comment]
期货 影响力 ： 价格 > 成交量 > 持仓量

**Comment by vnpy** [comment]
我们下个版本来加上吧

**Comment by followdao** [comment]
谢谢



------------------ 原始邮件 ------------------
发件人: "vn.py"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 上午9:27
收件人: "vnpy/vnpy"<vnpy@noreply.github.com>; 
抄送: "道 黄华刚"<followdao@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [vnpy/vnpy] 请问为什么现在2.0版本的TickData和BarData中不包含OpenInterest持仓量信息？ (#1739)




我们下个版本来加上吧

**Comment by xldistance** [comment]
2.0.3阉割了很多参数，需要自己加

**Comment by nov12** [comment]
> 我们下个版本来加上吧

十分感谢。

**Comment by nov12** [comment]
> 2.0.3阉割了很多参数，需要自己加

自己倒是能添加，只是修改的地方比较多，限于自己水平有限，感觉以后同步至最新代码觉得很麻烦，尤其是现在2.0版本更新很快，我现在自己修改基本都是在原有的基础上重新继承并增加一些方法，替换少量方法。

**Comment by vnpy** [comment]
已添加open_interest字段
