### ISSUE TITLE
参数优化功能无法传入策略的初始化参数

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#174]
部分策略在回测时，需要传入setting进行初始化，回测时可以通过engine.initStrategy(AtrRsiStrategy, d)实现
但是参数优化功能中无法传入策略的初始化参数：

修改如下
	1. ctaBackTesting的class OptimizationSetting中，添加函数

def addInitParameter(self, paras):
    """增加策略初始化参数"""
    for name, value in paras.items():
        self.paramDict[name] = [value]

	2. 策略参数优化加入如下的加粗代码

setting = OptimizationSetting()  # 新建一个优化任务设置对象
setting.setOptimizeTarget('capital')  # 设置优化排序的目标是策略净盈利

**d = {'xxxx': 11}
setting.addInitParameter(d)**

setting.addParameter('atrLength', 11, 20, 1)  # 增加第一个优化参数atrLength，起始11，结束12，步进1
setting.addParameter('atrMa', 20, 30, 5)  # 增加第二个优化参数atrMa，起始20，结束30，步进1

**Comment by vnpy** [comment]
准备在v1.3中修复

**Comment by vnpy** [comment]
已完成，扩展了addParameter函数，例子请参考strategyAtrRsi.py中的代码。
