### ISSUE TITLE
K线图表功能

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#1742]
- [x] 基础功能
    - [x] K线序列显示
    - [x] 单根K线更新
    - [x] 批量K线更新
    - [x] 十字光标轴
- [x] 增强功能
    - [x] 自定义数据显示
- [x] 图表主题
    - [x] 黑色风格

**Comment by Cointiger-TaiOne** [comment]
能加个进出场显示吗？下单的地方标记下，出场的地方标记下，标记上有进出场价格等信息

**Comment by aslan9** [comment]
> 能加个进出场显示吗？下单的地方标记下，出场的地方标记下，标记上有进出场价格等信息

支持，希望能够在展示层结合具体的委托和成交信息

**Comment by UtorYeung** [comment]
希望能同时兼容1.9.2LTS和2.0.3

**Comment by EricYwt** [comment]
强烈支持！！！！

**Comment by 215010wk** [comment]
希望1.9.2也加上

**Comment by vnpy** [comment]
测试后我们发现PyQtChart实现的非常差，决定用PyQt自己重写一个了

**Comment by vnpy** [comment]
> 希望能同时兼容1.9.2LTS和2.0.3

只在2.0.3有，1.9.2不会新增功能了呢

**Comment by newencn** [comment]
> 测试后我们发现PyQtChart实现的非常差，决定用PyQt自己重写一个了

是否考虑直接使用pyechart实现K线功能

**Comment by ypochien** [comment]
有沒有可能在QT中嵌入網頁，然後用Echart ( https://www.echartsjs.com/index.html ) 這個JS 套件

我覺得這個套件 無論是美感 與 效能 都值得肯定，而且為BSD授權

**Comment by UtorYeung** [comment]
> > 测试后我们发现PyQtChart实现的非常差，决定用PyQt自己重写一个了
> 
> 是否考虑直接使用pyechart实现K线功能


我现在就是用pyecharts，虽然实现方便，但是超过一定数量（我这边测试是50000bar）就会非常卡，而且貌似不能动态更新显示。所以非常不推荐用pyecharts......

**Comment by stone3536** [comment]
酒香不怕巷子深呀！

只要功能都牛逼了，star根本就不是问题的呢！

**Comment by hadrianl** [comment]
基于pyqtgraph实现可以考虑一下，技术栈延伸到js的话，tradeview开源的lightweight-charts也是可以考虑一下的

**Comment by vnpy** [comment]
已完成开发，在最新的DEV分支下
