### ISSUE TITLE
VNPY2.0.3执行tests/backtesting/getdata.py时报以下错误：pymongo.errors.ServerSelectionTimeoutError: hour must be in 0..23

### ISSUE THREAD

**Issue by tangsir001** [vnpy/vnpy#1748]
## 环境

* 操作系统: 如Windows 10
* 环境：Python 3.7 64位，Pycharm
* vn.py版本: 2.0.3

## Issue类型
Bug

##问题描述
VNPY2.0.3执行tests/backtesting/getdata.py时报以下错误：pymongo.errors.ServerSelectionTimeoutError: hour must be in 0..23

使用的数据库是MongoDB 4.0.0现已确定不是数据库的问题（因为老版的vnpy可以正常连接MongoDB）

VNPY2.0.3下的MongoDB配置如下图所示：
![image](https://user-images.githubusercontent.com/31811821/58403785-1ce91d80-8096-11e9-887a-31a27bb81cf3.png)

Bug位置如下图所示：
![image](https://user-images.githubusercontent.com/31811821/58403889-60dc2280-8096-11e9-9130-ddc9eebce73f.png)

**Comment by vnpy** [comment]
@nanoric 请帮忙看下原因

**Comment by tangsir001** [comment]
问题解决了

**Comment by tangsir001** [comment]
问题解决了吗？

**Comment by vnpy** [comment]
我们查了下，这个报错确实是pymongo组件内部的，请逐步排查：
1. 是否装了多个Python环境，如果是，卸载干净后重装VN Studio
2. 运行python，然后手动加载pymongo.MongoClient，连接MongoDB服务器看看是否会报错

**Comment by tangsir001** [comment]
vnpy1.8是可以正常连接的

**Comment by tangsir001** [comment]
我装了pymongo和mongoengine两个库，这两个库在一块儿会不会引起冲突

**Comment by vnpy** [comment]
理论上不会，mongoengine底层本来就依赖pymongo，但可能存在版本不一致的导致的问题，所以卸载重装后最容易判断
