### ISSUE TITLE
Bug：rqdata.py 中 RqdataClient 类的 to_rq_symbol 方法对连续和指数合约转换有问题

### ISSUE THREAD

**Issue by nov12** [vnpy/vnpy#1753]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.3

## Issue类型
三选一：Bug

## 预期程序行为
正确将合约名转换至rqdata中的合约名

## 实际程序行为
错误的将郑商所的合约连续和指数合约转换，例如将AP888会转换为AP2888，AP99会转换至AP199导致无法下载到数据。

## 重现步骤
在回测模块中下载AP88数据即可。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
