### ISSUE TITLE
穿透式监管api docker化问题

### ISSUE THREAD

**Issue by lzd324** [vnpy/vnpy#1755]
## 环境

* 操作系统: linux docker
* Anaconda版本: 任意
* vn.py版本: 任意穿透式监管版本

## Issue类型
Question

因为穿透式监管需要获取系统信息（具体哪些信息未知），在docker下无法获取到相关信息导致一直报Decrypt handshake data failed，猜测是因为docker无法获取到系统信息的缘故，实体机测试无异常。
以下问题不知是否有人帮忙解答下，相关问题是否有人得到有效解决：

1. 穿透式监管具体会获取哪些系统信息？
2. 是否有人在docker、阿里云、虚拟机等虚拟环境成功使用ctp穿透式监管版本。（当前我使用的是虚拟机测试通过，虚拟机能成功获取bios等信息）

**Comment by vnpy** [comment]
1. CPU序列号、硬盘序列号、内外网IP、MAC、主分区情况
2. 阿里云可以测试跑通，docker不清楚了，原则上是需要使用实体机器进行测试和记录
