### ISSUE TITLE
CTA模块改进

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#176]
1. 回测结果的图形显示，类似MC／TB的图表功能
2. 入门级交易模板，只要给信号（方向和仓位），模板自动管理交易

**Comment by jeffereylj** [comment]
不知道是否能够输出交易回侧记录文件，文件中包括交易价格，交易时对应的信号。

**Comment by vnpy** [comment]
可以的，回测完成后，把engine.tradeDict、engine.logDict等字典中的内容读取输出就行了，csv也好，txt也好，都可以视乎你自己的需求去保存

**Comment by vnpy** [comment]
1. 量衍投资完成了目标仓位交易模板
2. 经过考虑后，因为vn.trader主要针对的领域是实盘交易，而非策略研究，图形化显示回测效果这块暂时不开发，需要的用户可以自行导出回测的结果后在excel或者使用ipython notebook去做相关分析。
