### ISSUE TITLE
HBDM websocket网络断开

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#1760]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3 发行版（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
一直能收到websocekt数据

## 实际程序行为
在连接5-20分钟之后，会只能收到ping数据，而收不到行情数据。
并且因为连接是好的，不会自动重连。导致策略无法触发onBar

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请用SS翻墙或者使用香港阿里云

**Comment by eachout** [comment]
已SS翻墙， 并在连接时填了代理。

**Comment by vnpy** [comment]
中间有出现过Websocket断开重连的记录吗？

**Comment by eachout** [comment]
重连了，然后就没反应了。感觉是没有重新订阅。

**Comment by eachout** [comment]
我在硅谷机房，没开SS直连跑了半小时，一样的结果。

**Comment by hello886** [comment]
我跑一天没问题，2-3天则需要重新订阅，怀疑时火币的问题，火币没有推送了

**Comment by vnpy** [comment]
我们尝试重现下情况

**Comment by vnpy** [comment]
增加了断线重连后的行情的自动重新订阅 #6513314
