### ISSUE TITLE
能否在项目主页上添加"代码覆盖率徽章（badge）"？

### ISSUE THREAD

**Issue by aQuaYi** [vnpy/vnpy#1769]
我想参与到 vnpy 的开发中来。
现阶段的由于编程能力和 Python 的熟悉程度有限，准备从编写测试文件下手。
发现主页还没有"代码覆盖率徽章（badge）"。
请问能否添加一下"代码覆盖率徽章（badge）"呢？

**Comment by vnpy** [comment]
暂无计划，作为实盘交易系统，vn.py的大量测试无法直接通过单元测试这种简单的方法覆盖
