### ISSUE TITLE
开发价差套利算法模块Spreading Algo

### ISSUE THREAD

**Issue by tesla1060** [vnpy/vnpy#177]
想做白银期货和白银td的跨市场套。怎么样能实现多腿下单呢？自己试了好几次，没成功的写出来，不知道大家能不能跟着讨论一下。

现在主要遇到的困难是，例如，先下白银td的单那么就有以下几个情况
1. 白银td如果没有成交就要cancel
2. 如果全部成交就要立刻追白银期货的单直到两边都完全对冲
3. 如果部分成交，但是白银td没能成交到15的整数倍（白银td对白银期货是15:1），就要一边追白银td的单，让白银td成交至少达到一个整的单位（15手），一边追白银期货的单，以便达到全部对冲的效果，一边cancel掉白银td没成交的单。
4.如果部分成交，白银达到了15的整数倍，就需要一边追白银期货单，一边cancel掉白银td没成交的单。

在所有的cancel中也可能出现
a 全部cancel成功
b 挂单有新的成交，剩余部分cancel成功，或挂单全部成交，cancel失败。

在以上这些过程中，还有可能出现网络丢包的可能。

想请教要怎样设计才能做到这种双腿下单呢？

**Comment by vnpy** [comment]
这个是具体的策略算法设计的问题了，我只能给个简单的思路：
1. 你需要开发一个单独类，监听eventEngine推送的事件（收数据），进行计算后调用mainEngine的函数（发委托），CTA模块不适合这个工作
2. 这种spreading algo涉及比较复杂的状态转换，建议仔细设计自己的状态机模型，设计好后再去写代码，否则容易越写越乱
3. 问题中的3/4意味着你已经思考到最复杂的那几个状态了，建议每次操作都只做一步，受到上一步操作成功的回报后再去做下一步，可能会慢几十个毫秒，但是会避免很多出错的情况

**Comment by tesla1060** [comment]
是啊，求高手有时间帮忙implement一个框架。我自己试了几次了，最后真是越写越乱，就写不下去了。

**Comment by tesla1060** [comment]
体力活我可以做，比如写test case之类的，不过这种与订单回报有关的test case怎么写呢？

**Comment by vnpy** [comment]
我加个issue吧，看社区是否有兴趣来写

**Comment by tesla1060** [comment]
好的，谢了

**Comment by jeffereylj** [comment]
IB 当中有个generic combo的设置，真正实现了跨市场的价差交易。不知道是否可以嫁接到vnpy中。

**Comment by vnpy** [comment]
IB的这个订单是基于它后台系统提供的算法交易服务，属于独家功能，和别的平台不兼容（别的平台直接没有），到时候试着做进去，但不保证能成功。

**Comment by jeffereylj** [comment]
这个真是 TWS独家的功能。 但是在模块设计时，可以参考一下。

**Comment by jeffereylj** [comment]
不知道这个功能什么时候能够完成？ 个人非常期待使用这个功能来交易。

**Comment by vnpy** [comment]
2017年二季度前吧，这个模块比较复杂些，要多花点时间设计。

**Comment by jeffereylj** [comment]
比较期待这个功能的实现，是否有办法能够提前研制这个功能呢？ 物质或精神上的？望回复。

**Comment by vnpy** [comment]
1月上海的线下活动会讨论下2017年的开发计划，到时候会提到这个。

**Comment by tangyouze** [comment]
1月上海的线下活动会 是什么时候~ 可以参加嘛?

**Comment by vnpy** [comment]
不好意思报名已经截止了，一般线下活动之类的信息都会发布在群里

**Comment by zhangshuiyong** [comment]
期待套利的CTA回测和实盘模块

**Comment by vnpy** [comment]
spread trading这块的回测非常复杂，而且根据个人的算法下单偏好回测的框架也较难统一，套利模块不会提供回测功能。

**Comment by jeffereylj** [comment]
发展是逐步的， 我觉得比较重要的是先能够支持两个合约及以上的SPREAD TRADING。 当信号出现时候，能够交易。 相对回测比较复杂，不过这部分很多人都应该已经有自己的模型和测试结果了。

**Comment by vnpy** [comment]
嗯嗯，初期计划是这个

**Comment by wzy2009520** [comment]
期待官方版的，这两天在尝试搞这个，被折腾的欲仙欲死

**Comment by hackerwei** [comment]
催更，哈哈哈

**Comment by jeffereylj** [comment]
同催

hackerwei <notifications@github.com>于2017年4月8日 周六08:26写道：

**Comment by msincenselee** [comment]
我在vnpy上，对套利的相关修改：
1.uiBaseWidgate.py/TradingWidget（手工交易界面）
self.spinPrice.setMinimum(-1000)    # 原来是0，为支持标准套利合约，改为-1000
2、非标准套利合约支持
1）策略模板的vtSymbol，通过;分割多个合约，如vtSymbol = ‘rb1705;hc1705’
2）vtEngine中，加载策略时，分解vtSymbol并订阅多个合约
3）在策略onTick()，对传入的各合约Tick进行价差/比价等处理
4）新建_arbbuy(),_arbSell(),_arbShort(),_arbCover()
5）针对上期所的合约，增加平昨和平今逻辑
3、回测模块，增加单独的套利回测逻辑。，先对两个合约提取数据，逐一合并成有效的套利Tick，灌送至newTick()

**Comment by shouhengzhang** [comment]
希望能早日看到功能上线

**Comment by ideaplat** [comment]
希望早日上线

**Comment by jeffereylj** [comment]
不知道是否能够更新一下项目的进展情况呢？

**Comment by jeffereylj** [comment]
@msincenselee 不知道你开发的非标准合约支持中的3）和4）的代码在那里可以看到呢？

**Comment by vnpy** [comment]
还没开始写呢，模块设计完了，大概会有这些：
1. spread行情计算引擎
2. spread算法交易引擎
3. spread策略引擎（收取从行情引擎过来的数据，计算策略信号，发送给算法引擎去交易）
4. spread回测引擎（支持tick和分钟级别）
5. 手动交易组件
6. 自动策略监控组件

**Comment by wzy2009520** [comment]
赞，被折腾的死去活来的表示，期望早日上线

**Comment by shouhengzhang** [comment]
建议先做出一个最粗糙的可行的版本：允许同一策略监控多个标的的行情，差价比价的公式用户可以自己写，查看是否成交，追单腿这些事情暂时也让用户自己去处理，这样是不是能开发的更快？

**Comment by jeffereylj** [comment]
是否还能 在自动策略监控组件中加入STOP LIMIT，

**Comment by vnpy** [comment]
@jeffereylj 请问你是希望在Spread Trading模块里加上STOP LIMIT委托的功能吗？

**Comment by jeffereylj** [comment]
是的，加入不同类型的订单会使功能更加丰富。 有些订单是交易所支持的，有些订单的类型只能定义到软件中，当软件启动接入市场，被保存的订单也会发送的市场。

我能想到的订单类型都是在Interactive brokers 中提到。但是不知道为什么，对于spread trading, 对于STOP LIMIT, TRAILING LIMIT, MARKET IF TOUCHED. 详细的订单类型描述，请看连接。

https://www.interactivebrokers.co.uk/en/index.php?f=4985

**Comment by jeffereylj** [comment]
我想这些订单类型不仅限于spread trading, 一般的单合约交易，也是很有帮助的。希望VNPY能够支持。

**Comment by wgj117** [comment]
我也在跟踪这个功能
在vnpy论坛上，desont写了《单策略多合约思路---实盘引擎》，moonnejs写了几篇相关的功能，《优化的tick级别精准回测引擎，支持双合约回测》。还有广州大佳msincenselee，实现了很多套利代码功能，已分享在GitHub。
感觉，很多内容都有了，是时机进行整合了。个人代码能力有限，希望能出一份力。

**Comment by ideaplat** [comment]
看这么长的issue，看了需求很强烈啊

**Comment by akeyong** [comment]
非常赞同 @wgj117 的说法 , 是时机进行整合了！！！

**Comment by kingmo888** [comment]
@wgj117 请问github上的套利版本地址是什么？

**Comment by wgj117** [comment]
@kingmo888 https://github.com/msincenselee/vnpy

**Comment by jeffereylj** [comment]
不知道现在这个模块开发的如何了？

**Comment by vnpy** [comment]
已初步完成开发和测试
