### ISSUE TITLE
想参与到 vnpy 的开发中来，请问能否提供规范的参与流程呢？

### ISSUE THREAD

**Issue by aQuaYi** [vnpy/vnpy#1770]
我想参与到 vnpy 的开发中来，请问能否提供规范的参与流程呢？
我前一段时间在看 hyperledger fabric 的资料。
发现他们就提供了非常规范的参与流程，并把操作步骤都总结的很好。

https://github.com/yeasy/blockchain_guide/blob/master/08_hyperledger/contribute.md

**Comment by vnpy** [comment]
项目主页有代码贡献说明
