### ISSUE TITLE
2.0.3版本连接IB,无法订阅合约,无法进行交易.

### ISSUE THREAD

**Issue by strongasahorse** [vnpy/vnpy#1774]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 2.0.3版本内置
* vn.py版本:2.0.3

## Issue类型
三选一：Question

## 预期程序行为
IB连接成功后,输入合约交易所,合约代码回车,显示出合约信息,并通过vnpy面板手动下单.
## 实际程序行为
IB连接成功后,输入合约交易所,合约代码回车,日志报错,也无法手动交易,同时cpu上升到20%浮动.

## 重现步骤
1 打开Trader Workstation (TWS)或者IB Gateway 976
2 全局配置打开api接口,并记下端口号.
3 在常用面板输入nq回车,在弹出窗口中选择期货,在下一步弹出窗口中选择六月,即完成找到合约(查找合约代码的方法,是按照api手册上的说明,如下图1)
4 选中该合约右键,打开描述,记下该合约的交易所合约代码,
GLOBEX,NQM9
5 打开vnpy Pro,连接IB,日志提示连接成功,在面板中输入交易所和合约代码,回车.
问题复现.

**Comment by strongasahorse** [comment]
![api文档](https://user-images.githubusercontent.com/50865840/58763002-75358900-8588-11e9-8a91-c06b62f2ba44.jpg)
![Uploading TWS打开api接口.jpg…]()
![Uploading 常用面板.jpg…]()
![Uploading 输入nq在弹出菜单中选择期货.jpg…]()
![Uploading 选择六月.jpg…]()
![Uploading 打开描述.jpg…]()
![Uploading 产品信息.jpg…]()
![Uploading IB连接成功.jpg…]()
![Uploading VNPY报错.jpg…]()
![Uploading cpu上升.jpg…]()

**Comment by strongasahorse** [comment]
![TWS打开api接口](https://user-images.githubusercontent.com/50865840/58763061-0f95cc80-8589-11e9-8116-f0e400f4fbc1.jpg)
![常用面板](https://user-images.githubusercontent.com/50865840/58763065-1cb2bb80-8589-11e9-870e-82197b31f979.jpg)
![输入nq在弹出菜单中选择期货](https://user-images.githubusercontent.com/50865840/58763068-26d4ba00-8589-11e9-8b00-5c68eb045662.jpg)
![选择六月](https://user-images.githubusercontent.com/50865840/58763071-305e2200-8589-11e9-8a4c-c8c1a6942bcb.jpg)
![打开描述](https://user-images.githubusercontent.com/50865840/58763077-38b65d00-8589-11e9-9997-8d6d9795bd42.jpg)
![产品信息](https://user-images.githubusercontent.com/50865840/58763080-3f44d480-8589-11e9-9ab9-6b499a4f8e1c.jpg)
![IB连接成功](https://user-images.githubusercontent.com/50865840/58763082-453ab580-8589-11e9-9e80-f477e2eb6e0c.jpg)

**Comment by strongasahorse** [comment]
![VNPY报错](https://user-images.githubusercontent.com/50865840/58763149-ddd13580-8589-11e9-98fb-364c5b96277a.jpg)
![cpu上升](https://user-images.githubusercontent.com/50865840/58763153-e6c20700-8589-11e9-866b-3c909aabbb67.jpg)

**Comment by iam36** [comment]
VNPY2.03碰到同样问题，订阅提示无法找到相应代码。

代码确认是tws中的symbol一致的（通过IB自己的python demo可以获取成功）

**Comment by strongasahorse** [comment]
你用IB自己的demo获取的symbol和我截图上弄的是一样的么?@iam36

**Comment by iam36** [comment]
> 你用IB自己的demo获取的symbol和我截图上弄的是一样的么?@iam36

没有错，我尝试了NYSE的aapl等主流代码以及外汇的主体货币对，都是在tws以及API中工作正常的，而在VNPY2.03的行情订阅中一律提示无法找到。。

打算抽空看VNPY的调用代码了。。。只是酱紫效率太低。。。期望官方答复

**Comment by vnpy** [comment]
查了下，应该使用ConId字段，参考如下：

![捕获](https://user-images.githubusercontent.com/11263900/59175812-77e83d80-8b89-11e9-8a17-fb653308ee24.JPG)

**Comment by strongasahorse** [comment]
谢谢,文档希望能写清楚一点.希望有合约字段的对照,或者告诉我去哪里找这个对应表.

**Comment by hello886** [comment]
我也遇到这个问题，有没有一个例子告诉如何成功订阅ib合约呢？，今天整了一天，都没订阅成功，conid从哪里查询到的呢？谢谢啦，对大神来说可能一点就透，小白折腾一天整不明白，谢谢啦

**Comment by vnpy** [comment]
ConId在IB官网的合约信息网页中，可以查看到，需要具体点到某个合约的信息里面才有。

**Comment by jiechic** [comment]
> 打算抽空看VNPY的调用代码了。。。只是酱紫效率太低。。。期望官方答复

你这里使用的是localname吗？如果是这样，那官方的api应该有使用localnameapi查询，而不需要用conid，vnpy的代码是否还有优化的空间？
