### ISSUE TITLE
通过VNPY2.0.3登录宽睿OES，无法显示账户信息。

### ISSUE THREAD

**Issue by gitxjlbjtu02** [vnpy/vnpy#1775]
## 环境

* 操作系统: 如Windows 10 
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3发行版 

## Issue类型
三选一：Bug 

## 预期程序行为
通过宽睿OES接口登录系统后(测试账号)，应该能够显示连入账户，并显示资金量等信息。

## 实际程序行为
通过VNPY Pro登录OES接口后，未显示相应的账户信息

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1)启动VNPY2.0.3
2）通过Pro模式启动OES（宽睿）
3）通过测试账号进行登录
4）登录后，显示不了账户信息
![webwxgetmsgimg](https://user-images.githubusercontent.com/51294139/58763559-b466d880-858e-11e9-8944-99ee7e073b60.jpg)

**Comment by vnpy** [comment]
@nanoric 请帮忙看下吧

**Comment by vnpy** [comment]
DEV分支已修复，服务端规则修改强制要求填写IP地址和MAC信息

**Comment by gitxjlbjtu02** [comment]
不好意思，刚刚下载了最新的gitub的vnpy的代码，使用了一下测试账号登陆，仍然木有资金和账户信息。


尝试了在这种情况下进行交易测试，发现没有办法触发买和卖的消息，还请多多指教。


实盘下我再试一下看看能不能触发交易函数。但是木有模拟盘的测试，还是不敢直接实盘。


使用的交易函数是：
self.buy(bar.last_price+0.01, self.fixed_size, True)

self.short(bar.last_price+0.01, self.fixed_size, True)


使用的测试账户是：
[oes_client]
ordServer = 1 tcp://106.15.58.119:6101
rptServer = 1 tcp://106.15.58.119:6301
qryServer = 1 tcp://106.15.58.119:6401
  
    username = customer389
    password = 2cuued


[mds_client]
udpServer = udp-mcast://239.1.150.100:5300(测试环境UDP不可用)
tcpServer = tcp://139.196.228.232:5103
qryServer = tcp://139.196.228.232:5203
  用户名／密码：
    username = customer389
    password = 2cuued










在 2019-06-03 16:51:41，"vn.py" <notifications@github.com> 写道：


Closed #1775.

**Comment by vnpy** [comment]
@nanoric 请帮忙测试下吧

**Comment by gitxjlbjtu02** [comment]
不好意思，今天用实盘测试了一下，出现了两个新问题：
一是实盘持仓中的显示中有持仓股票未能显示出来（请见附件）；
二是不能触发买和卖的操作（实验策略请见附件）。


同时，模拟盘还是不能直接显示账户信息和资金信息。如果方面的话，还请帮忙看下虚拟盘和实盘能不能触发买和卖的操作吧，多谢！：）






在 2019-06-11 22:19:59，"vn.py" <notifications@github.com> 写道：


@nanoric 请帮忙测试下吧

**Comment by lch0821** [comment]
今天验证了一下，模拟账号连接后不会显示账户信息和资金信息，但交易后会出现。 你现在可以正常用了吗？@gitxjlbjtu02

**Comment by vnpy** [comment]
DEV分支已经更新到最新版，支持战新版的版本，请再试试吧
