### ISSUE TITLE
希望vnpy能够考虑增加在行情中显示当前标的K线图功能

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#1776]
* 操作系统: 如Windows 10
* vn.py版本: v2.0发行版

三选一：Enhancement

希望能够增加支持显示交易标的的时时行情和K线行情（可以切换周期），跟其他通用行情软件功能类似，并且希望在K线图上（多个周期可用）能够叠加多个品种进行分析相关性。
希望交易标的行情都可以显示，包括价差行情也能够在图上显示，并且能够将价差行情与该价差相关标的叠加在一起显示在K线图上。
K线图上能够显示通用的均线、macd、kdj等通用指标功能。

当然，这对于开源的项目来说确实是比较难，因为投入精力确实是比较大而且可能看不到受益，但是最终长远来看还是最终需要的。

期望有这方面需求的伙伴们多顶顶这个需求，谢谢！

感谢群主和各位付出的大佬们！谢谢您们！

如果vnpy不做这个功能，是否可以提供实现以上功能的技术例子以及相关的技术链接，想进行下学习后看是否空了自己增加下这个功能，谢谢！

我觉得性能不是啥问题的，因为现在电脑便宜的，旧的电脑很多，直接扔到旧的电脑上看这个行情就完了，或者自己本机看行情，不在交易的电脑上看行情，就不存在会影响性能的问题的了。

最好是可配置的，就是那个标的或者价差的行情需要在k线图上显示，配置下就可以显示了，k线图窗口可以多个平铺，哪几个标的组合叠加在一个小窗口上可以进行配置。

**Comment by stone3536** [comment]
个人觉得在vnpy2.0.3以上版本实现就好了，感觉不需要再1.9.2版本上折腾的了，1.9.2应该2、3年后就被彻底废弃了，不会再有多少人用的了。

**Comment by vnpy** [comment]
已完成K线图表功能的添加。
