### ISSUE TITLE
建议新版本的价差模块做些优化

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#1777]
操作系统: 如Windows 10
 vn.py版本: v2.0.5

三选一：Enhancement

群主，您好
之前发过类似的关于价差模块和dataRecord模块的增强了，看到价差模块在计划中了，仍旧忍不住再发一次这个需求，因为感觉真的是迫切的需求（我在我目前的基于vnpy的1.9.2的版本中都已经实现的了，方式不是最优的，但是还说的过去。），不在官方版本中实现的话总感觉有缺憾的。
感恩您的付出！
对于您和vnpy团队来说，如何实现盈利并更平稳的走的更长远，我觉得有一个方式是多开些课程，把新的功能介绍下、期权模块介绍下、算法模介绍下，另外也可以把这1、2年线下积攒的精华部分介绍下，期待中！感谢！

=============
建议价差模块做些优化，如下：
1、同一个标的，可以出现在不同的spread中，这样才是比较合理的；
2、spread和algo解耦，就是algo不应该根据spread来，而应该是algo根据spread进行创建，那么就可以针对spread创建对应的多个algo的，就可以对不同的algo设置不同的参数进行交易，这样才是最优的方式的；
3、spread和algo的参数数据保存到数据库中；并且应该是在trade或者pos事件后就保存，而不是在关闭软件的时候；
4、价差模块，期望能够增加看板（当然实际交易的时候看板和实际交易机器最好分开），该看板能够把价差spread的价差值和相关标的同时展示在同一个分时图或者K线图中（可设置1分钟、5分钟、30分钟的K线图，在该K线图中可以实现均线、macd、kdj等通用指标的功能），类似于市面上常用的多个交易标的叠加在一个图中进行展示、分析；
5、另外仓位要分开，就是标的有手工或者cta成交了的，不应该影响价差交易模块的持仓的，否则就算分开物理服务器也收到影响的；（相当于价差模块的持仓根据algo进行更新持仓，平仓根据价差现有仓位平仓）

关于价差数据：
1、期望能够优化dataRecord模块，将价差模块的spread的价差的 “tick” 、“bar”数据保存到数据表中，标的名字是价差名就应该可以；
2、有了 1、保存的数据，才好进行历史数据测试的；

谢谢！

**Comment by stone3536** [comment]
上边写的有些啰嗦的，见谅。
另外上边写了希望您开些课程，是指的收费的课程的，期待中。

**Comment by hello886** [comment]
的确，支持收费课程，如果要走的远，还是需要盈利的，vnpy的确非常棒了

**Comment by vnpy** [comment]
已完成2.0.7的SpreadTrading模块开发，欢迎试用
