### ISSUE TITLE
多语言支持，特别是英语

### ISSUE THREAD

**Issue by wangzhe3224** [vnpy/vnpy#178]
很棒的库，关注很久，也学习了很多经验。
目前有一个想法，就是增加一下多语言支持，特别对于IB等国外的接口，有利于平台推广。
我目前在伦敦工作，现在的算法借鉴了很多，做了一部分英语的支持。想继续做下去，完善这个库
想跟大家请教一下，多语言支持的话，什么样的方式做最方便？

**Comment by vnpy** [comment]
PyQt有个translate功能，用来做界面的翻译应该是比较方便的，参考这里：http://blog.csdn.net/ying_593254979/article/details/10189687

其他一些内置常量字符串的翻译可以手动来做，工作量不大。

另外想问下你们如果用IB的接口，是在windows还是linux？

**Comment by 4ever911** [comment]
我是在Linux和Mac下，windows下量化不方便，也耗资源。

另外，个人感觉IB做美股目前来看在数据上还是不大好解决，历史的分钟级别数据以及实时监控整个市场，都需要买feed，并且用起来也不大方便。

**Comment by wangzhe3224** [comment]
我是Linux做

**Comment by vnpy** [comment]
最近vn.ib的Linux封装遇到点问题，底层的eConnect接口调用时，TWS会收到连接但显示处于pending的状态，估计解决还得花点时间。

计划在完成vn.ib的Linux封装后，先开始vn.ib的国际化计划（代码注释、文档等）。

**Comment by wangzhe3224** [comment]
IB 的API 我相对熟悉一些，可以帮忙贡献国际化方面的工作

**Comment by vnpy** [comment]
IB接口开发已经完成了，接下来需要写个vn.ib的英文介绍文档，有兴趣帮忙做一下吗？

**Comment by wangzhe3224** [comment]
OK的啊，有没有具体的框架要求?

**Comment by vnpy** [comment]
没，目前先直接翻译一下vn.ib的介绍就好，后续还准备加一些其他内容

**Comment by wangzhe3224** [comment]
ok

**Comment by pnfgxw** [comment]
IB接口开发已经完成了,非常赞！大概什么时候发布呢？

**Comment by vnpy** [comment]
v1.5的发布估计会在3月底前，XTP的东西我这边已经完成了，现在在等中泰的一些消息

**Comment by vnpy** [comment]
英文版已增加在DEV中
