### ISSUE TITLE
老虎接口下单成功后状态错误 

### ISSUE THREAD

**Issue by 4693887178** [vnpy/vnpy#1781]
## 环境

* 操作系统: Windows 7
* Anaconda版本: 如Anaconda  Python 3.7 64位
* vn.py版本: 2.03

## Issue类型
Bug

## 预期程序行为
老虎证券用高价单下单后，状态改变，并显示已成交。

## 实际程序行为
状态永远 是提交中，已成交显示0.
但其实这个单子已经成交了，但VNPY状态并没有改变。这个把软件关掉以后，再重新登陆一下就可以确认是VNPY的问题了。

## 重现步骤
用高价单仿真账户对港股进行下单，关掉VNPY再重新登陆。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![QQ截图20190603153659](https://user-images.githubusercontent.com/29080492/58784371-d22b5080-8615-11e9-82c2-719248db6a49.png)

**Comment by vnpy** [comment]
已更新老虎API
