### ISSUE TITLE
bitmex下单错误

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#1788]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.3

## Issue类型
三选一：Bug

## 预期程序行为
正确下单

## 实际程序行为
无法下单

## 重现步骤

![image](https://user-images.githubusercontent.com/9478695/58859740-1a617600-86dd-11e9-99a5-ee886d2e36c0.png)

看log应该是最小价格精度有问题。bitmex是0.5的价格精度。

另外，BITMEX下载回测数据会因为过频访问导致IP被封返回403。

**Comment by vnpy** [comment]
1. 下单用的停止单？
2. 你连接BitMEX的网络环境是？

**Comment by eachout** [comment]
1. 是的，用的停止单。
2. 网络环境是vultr硅谷云主机, ubuntu 18.04

**Comment by 1122455801** [comment]
下单应该注意pricktick问题，如XBTUSD的pricetick是0.5，若下单如7984.1，会直接拒单，报错如上。

**Comment by eachout** [comment]
这个在哪一层处理比较好？gateway里头吗？

**Comment by eachout** [comment]
> 下单应该注意pricktick问题，如XBTUSD的pricetick是0.5，若下单如7984.1，会直接拒单，报错如上。

这个在哪一层处理比较好？我觉得应该在gateway里头增加对price和amount精度的控制？
这样策略可以不用判断在哪个gateway上跑吧

**Comment by 1122455801** [comment]
在下面这种情况，不用处理：
发出交易信号，具体的buy/sell的price是基于ask_price/bid_price，或者open，high，low，close，或者在这些的基础上加价差，如1*pricetick, 2*pricetick

**Comment by eachout** [comment]
> 在下面这种情况，不用处理：
> 发出交易信号，具体的buy/sell的price是基于ask_price/bid_price，或者open，high，low，close，或者在这些的基础上加价差，如1_pricetick, 2_pricetick

嗯，测的是海龟策略，直接按照ATR算出来的停止单，请问在哪一层处理比较好呢？

**Comment by 1122455801** [comment]
参考：
1)在策略参数里面加入self.price_tick。调用cta策略模块创建策略示例时要根据品种来手动输入price_tick
2) 假设发单价格是price0，基于pricetick的调整可以是   （取整(price0 /self.price_tick)）*self.price_tick
3) 取整方法可以是向上取整，向下取整或者四舍五入

**Comment by eachout** [comment]
好的，我再研究一下如何修改。
感谢群主大神，感谢KeKe大神！

**Comment by eachout** [comment]
在cta_strategy/engine.py的send_order中加上精度处理即可：
![image](https://user-images.githubusercontent.com/9478695/59031313-f1381580-8895-11e9-9e64-33b2cb282a48.png)

```
price = round(price/contract.pricetick)*contract.pricetick
volume = round(volume/contract.min_volume)*contract.min_volume
```

**Comment by xldistance** [comment]
用ctaengine里面的round_to函数

**Comment by vnpy** [comment]
已合并PR
