### ISSUE TITLE
可以简要介绍以下，各个分支的作用和目的吗？

### ISSUE THREAD

**Issue by aQuaYi** [vnpy/vnpy#1792]
主要是不明白

chart

tora

dev

这三个分支

**Comment by cooooo** [comment]
dev是主开发分支，chart,tora是开发用临时分支

**Comment by vnpy** [comment]
* master：发布分支
* dev：主开发分支
* 1.9.2-LTS：v1.9.2的长期支持分支
* 其他：对应功能的细分开发分支

**Comment by aQuaYi** [comment]
谢谢
