### ISSUE TITLE
请问vnpy2.0.3能否用python3.6 64位

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1794]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3

## Issue类型
三选一：Question
requirements.txt 中的依赖有： dataclasses; python_version<="3.6" 
是否说vnpy2.0.3 能使用python3.6  64位版本、？

**Comment by vnpy** [comment]
可以使用，请自行安装dataclasses模块
