### ISSUE TITLE
csv载入模块载入的数据库 名称一直都是db_bar_data

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#1797]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3

## Issue类型
三选一：Question
我分别载入了rb， if 等好几给表格，但是vnpy数据下一直只有一个documnet ，名字是db_bar_data.
我记得1.8版本的数据库载入后的document的命名都是相应的symbol名字.
数据库用的是mongodb

**Comment by vnpy** [comment]
2.0的数据库范式已经修改，改为使用ORM模式，每种数据类型一个表，不再是每个合约一个表了
