### ISSUE TITLE
VN Trader 打开后无法链接，log也没有反应，重复链接会报 ‘’python 已停止‘’ 

### ISSUE THREAD

**Issue by zoulei18337120325** [vnpy/vnpy#1799]
打开vn trader后没有任何反应。链接CTP输入SimNow的模拟账户后依旧无反应。第二次输入账号链接就报错 说是 python 已停止。

**Comment by vnpy** [comment]
2.0.3版本目前不支持SimNOW

**Comment by hello886** [comment]
请问有添加sinmon支持计划么？一般来说实盘前都是需要跑测试的，vnpy还有其他测试方案么？还是说只有用19的版本才能进行测试，2.0不提供测试方案
