### ISSUE TITLE
StopOrder类拼写错误

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#1804]
## 环境

* 操作系统: mac
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版
## Issue类型
三选一：Bug

## 重现步骤
cta_strategy/engine.py 第190行

vt_orderid=order.vt_orderid,

调用了./base.py StopOrder类

vt_symbol: str
    direction: Direction
    offset: Offset
    price: float
    volume: float
    stop_orderid: str
    strategy_name: str
    lock: bool = False
    vt_orderids: list = field(default_factory=list)
    status: StopOrderStatus = StopOrderStatus.WAITING

vt_orderids拼写错误。

**Comment by vnpy** [comment]
dev已经修复
