### ISSUE TITLE
arbitrage_algo下单只有方向没有开平

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1805]
![QQ截图20190607122621](https://user-images.githubusercontent.com/29418474/59081403-8122a180-8920-11e9-8469-1dcc318585e6.png)
![QQ截图20190607122746](https://user-images.githubusercontent.com/29418474/59081410-854ebf00-8920-11e9-95fd-fff65397fee3.png)

**Comment by vnpy** [comment]
Arbitrage算法属于轻量级的算法交易实现，没有实现开平仓自动转换的支持，主要针对海外期货、数字货币等没有开平概念的市场。

功能更加强大的SpreadTrading模块将在2.0.6中提供，会和CtaStrategy模块一样，内嵌各种委托自动转换功能。
