### ISSUE TITLE
實作台灣永豐金證券API Gateway

### ISSUE THREAD

**Issue by ypochien** [vnpy/vnpy#1818]
## 环境
* 操作系统:  Windows / Linux
* vn.py版本:  v2.0 之後

## Issue类型
Enhancement

## 预期程序行为
我們釋出Python 版本的API，想申請加入串接VNPY量化交易框架平台 
* [ ]  報價
* [ ]  下單

## 实际程序行为
由我們自行實作永豐金證券API之GateWay

**Comment by vnpy** [comment]
欢迎，请发下你们的文档我们看看？

**Comment by ypochien** [comment]
> 欢迎，请发下你们的文档我们看看？

https://github.com/Sinotrade/Shioaji

目前團隊還在加緊腳步開發中，但基本的『報價』與『下單』，已經可無縫的使用

**Comment by vnpy** [comment]
看了下主动请求功能问题不大，委托、成交、行情的更新推送现在还没有？

**Comment by ypochien** [comment]
行情大致上已克服，團隊正在處理交易委託的callback

![image](https://user-images.githubusercontent.com/625016/59399340-32648400-8dc6-11e9-99e0-f030c7f3cc16.png)

**Comment by vnpy** [comment]
赞，挺好的

**Comment by vnpy** [comment]
@ypochien 请问你们的委托、成交推送，目前完成进度如何？
