### ISSUE TITLE
vnpy1.92LTS无法订阅显示IB的黄金合约GCQ9

### ISSUE THREAD

**Issue by czhangrm** [vnpy/vnpy#1819]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 2 （32位）
* vn.py版本: 1.92LTS

## Issue类型
三选一：Question

## 预期程序行为
IB连接成功后,输入合约信息GCQ9等，回车,行情栏显示出合约信息

## 实际程序行为
IB连接成功后,输入合约信息GCQ9等，回车,行情栏无法显示出合约信息，且无报错

## 重现步骤

1 打开Trader Workstation (TWS)，连接IB，显示连接成功，持仓栏可见账户信息
2 输入合约代码：GCQ9,交易所：NYMEX,货币：USD，产品类型：期货，接口：IB
3 回车，行情栏无显示，报错栏也无报错
4 重新输入USD.CNH的合约信息却可以正常显示IB接口的USD.CNH合约信息

**Comment by stone3536** [comment]
你打电话给ib，这个不是vnpy的问题的，是ib的行情订阅导致的没推数据过来的，也就是你在tws里边可以获得这个标的的数据，但是vnpy接口获取不到，和ib联系，他们会给你解决的。我碰到过这个问题的。只有实盘订阅的才会出现这种情况的。

**Comment by czhangrm** [comment]
可是使用vnpy1.7是可以获取行情，确定不是vnpy的问题吗？

**Comment by stone3536** [comment]
合约都GCQ9的呢，我刚看了下测试系统上的标的的。确定，当时他们还提了message的并且给了我message号的呢。我刚找了下，邮件的垃圾箱被我清空的了。
确定。
打电话跟他们联系下看结果。

**Comment by stone3536** [comment]
我这也是上个月底换合约的时候出的这个问题的呢。以后得早点儿测试的。
另外这种期货合约你注意下，因为跟现货挂钩，会提前一个月被强制清仓的，比如6月份的合约，在5月20记号ib就强平的了，我们上次5月28号就被强平了所有6月份的合约的呢。

**Comment by czhangrm** [comment]
IB回复数据是正常返回的，不是他们问题，纳闷了
![IB答复](https://user-images.githubusercontent.com/51697192/59493571-c06f6600-8ebd-11e9-9bf4-fbee722e4f0b.png)

**Comment by vnpy** [comment]
请尝试v2.0上的版本吧，改为了使用IB官方的Python API，兼容性提高了很多

**Comment by stone3536** [comment]
你把你的账户的订阅行情的，不要用  “专业”  这个选项，否则就拿不到数据的。
