### ISSUE TITLE
CTP 结算单过长时，CTP api 返回结算单错误

### ISSUE THREAD

**Issue by lostleaf** [vnpy/vnpy#1824]
## 环境

* 操作系统: Ubuntu18.04
* vn.py版本: v2.0.3

## Issue类型
三选一：Bug

## bug 原因
vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp 4526行
对 `CThostFtdcSettlementInfoField.Content` 调用了 `toUtf` 函数，
```
data["Content"] = toUtf(task_data->Content);
```
其中 `Content` 字段的类型为 `char[500]`
实盘中，有时结算单过长，ctp 会将结算单拆分为多个字符串，多次回调 `OnRspQrySettlementInfo` 函数返回给用户
但由于结算单以 GBK 编码存储，一个汉字占多个字节，可能某一个汉字会在两次函数回调中，各返回一半（比如一个三字节的汉字，第一次回调的`Content[499]`返回第一个字节，第二次回调的`Content[0...1]`返回第二三个字节），这种情况下 `toUtf` 可能会无法 decode GBK 字符串，而返回空串

## 解决方法
没想到什么特别好的解决方案，我的做法直接不转换丢给上层，在gateway层处理或丢给用户自行解码
即，将 4526 行改为
```
data["Content"] = bytes(task_data->Content);
```

**Comment by vnpy** [comment]
非常感谢，确实算是一个非常有用的经验，后续遇到问题结算单问题的用户可以参考这种解决方案。

但考虑到：

1. 结算单过长的情况比较少见
2. 使用vn.py的用户需要输出和查看结算单的情况更加少见

因此就不在项目代码中进行修改了，需要的用户请自行在自己的代码中修改吧。
