### ISSUE TITLE
VNPY2.0.3，锁仓模式下没有发出委托

### ISSUE THREAD

**Issue by buwqwew** [vnpy/vnpy#1826]
## 环境

* 操作系统: 阿里云Windows Server 2012
* vn.py版本: VN STUDIO-v2.0.3

## Issue类型
三选一：Bug?

##具体情况
策略正常实盘中：
1、buy, short, sell, cover指令都没有加入参数LOCK=TRUE的情况下，可以正常委托成交
2、buy, short, sell,  cover指令都加入参数LOCK=TRUE，达到触发交易的条件也不会进行委托，CTA策略模块可以看到单一下在待命中，然后到时间撤销，下一个依然是待命中-已撤销的循环，不会发出委托
3、buy, short的参数LOCK=FALSE，而sell, cover的参数LOCK=TRUE, 会正常委托成交，平仓时会以开反向仓位来平仓，也就是正常锁仓

以上所有情况，在CTA回测里都正常，只有实盘时出现问题，实盘用的CTP接口
在VNPY论坛也有提出过，当时还截了一张图
[https://www.vnpy.com/forum/topic/627-qing-jiao-2-0-3suo-cang-mo-shi-zai-na-li-she-zhi](url)

第三种情况下不知道第二天会怎么平仓，因为害怕出问题，第二天我都是手动平仓的。
现在希望搞明白第二种情况是怎么回事

**Comment by zhouzhuofu** [comment]
https://github.com/vnpy/vnpy/issues/1713
感觉和我之前觉得有问题的地方类似，请参考

**Comment by buwqwew** [comment]
> #1713
> 感觉和我之前遇到的问题类似，请参考

请问你是实盘中遇到了吗，有解决了没？
我因为没有深入去研究开平仓的代码，还在学习中，所以不知道怎么解决

**Comment by zhouzhuofu** [comment]
> > #1713
> > 感觉和我之前遇到的问题类似，请参考
> 
> 请问你是实盘中遇到了吗，有解决了没？
> 我因为没有深入去研究开平仓的代码，还在学习中，所以不知道怎么解决

我没实盘。
目前是在研究源码。
我觉得你的第3种方法就没有问题；或者在converter.py中convert_order_request_shfe()函数一开始，就判断委托类型，如果是open就直接return [req]就应该没问题了。

**Comment by buwqwew** [comment]
> > > #1713
> > > 感觉和我之前遇到的问题类似，请参考
> > 
> > 
> > 请问你是实盘中遇到了吗，有解决了没？
> > 我因为没有深入去研究开平仓的代码，还在学习中，所以不知道怎么解决
> 
> 我没实盘。
> 目前是在研究源码。
> 我觉得你的第3种方法就没有问题；或者在converter.py中convert_order_request_shfe()函数一开始，就判断委托类型，如果是open就直接return [req]就应该没问题了。

我不知道第二天是设置在什么时间把昨天的锁仓的单平了的，但我用第三种方法，今天开盘5分钟都没有把昨天的单自动平了，最后只能手动平了昨天的仓位

**Comment by vnpy** [comment]
> > > > #1713
> > > > 感觉和我之前遇到的问题类似，请参考
> > > 
> > > 
> > > 请问你是实盘中遇到了吗，有解决了没？
> > > 我因为没有深入去研究开平仓的代码，还在学习中，所以不知道怎么解决
> > 
> > 
> > 我没实盘。
> > 目前是在研究源码。
> > 我觉得你的第3种方法就没有问题；或者在converter.py中convert_order_request_shfe()函数一开始，就判断委托类型，如果是open就直接return [req]就应该没问题了。
> 
> 我不知道第二天是设置在什么时间把昨天的锁仓的单平了的，但我用第三种方法，今天开盘5分钟都没有把昨天的单自动平了，最后只能手动平了昨天的仓位

在锁仓模式下，是第二天开仓的时候，才会去平反向的仓位，而不是开盘就自动给全平了
