### ISSUE TITLE
关于精细化bar回测的一个建议

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#1827]
## 环境
略

## Issue类型
Enhancement

## 存在问题
1.原版回测引擎，使用bar回测时，买入不低于bar的最低价，卖出不高于bar的最高价即判定撮合成功。
2.因此回测时会有很多笔撮合都正好在bar的最低/最高价上，但实际上因为不是对手价，实盘时是无法成交的。

## 改进建议
以上情况下，改用tick回测又比较耗时划不来，建议使用折中的方法，在BAR数据上区分出O/H/L/C的bid和ask，并更改bar回测的算法，买入只在aks，卖出只在bid，从而提高BAR回测的准确性。

**Comment by vnpy** [comment]
这个思路确实不错，但实际情况是除非你自己有TICK数据，去合成这种特殊的K线，否则数据服务商提供的数据是没有这些字段的

**Comment by unlimitnight0** [comment]
是的，用于回测的数据源必须用tick，其实对于不是特别长的策略来说，普通的BAR数据很鸡肋，回测根本不准，对于波动小不活跃的品种就更不准了。
