### ISSUE TITLE
vnpy-1.2\vn.trader\shzdGateway\shzdGateway.py close方法出错，当退出vtMain进程时

### ISSUE THREAD

**Issue by jerryw** [vnpy/vnpy#183]
如标题描述，出错时引起python.exe crash, windows系统出现对话框，python.exe已停止工作。

环境：win10 64位， python 2.7.12 32位

临时解决方式：注释掉出错代码，如下
#self.api.release()  # 释放接口对象

**Comment by vnpy** [comment]
不好意思，这个bug在v1.2发布时没查出来，已经在最新的dev里面修复了。
