### ISSUE TITLE
vnpy/gateway/tiger/tiger_gateway.py的ORDER_STATUS应该是OrderStatus

### ISSUE THREAD

**Issue by muhaozhang** [vnpy/vnpy#1834]
编译报错：(F:\anaconda_envs\vnpy_source) D:\open_project\vnpy\tests\trader>python run.py
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x00003001]
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x0000300a]
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x0000300b]
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x00003001]
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x0000300a]
Error: REGISTER_FIELD, type [ftd], duplicate FieldID [0x0000300b]
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from vnpy.gateway.tiger import TigerGateway
  File "F:\anaconda_envs\vnpy_source\lib\site-packages\vnpy\gateway\tiger\__init
__.py", line 1, in <module>
    from .tiger_gateway import TigerGateway
  File "F:\anaconda_envs\vnpy_source\lib\site-packages\vnpy\gateway\tiger\tiger_
gateway.py", line 22, in <module>
    from tigeropen.trade.domain.order import ORDER_STATUS
ImportError: cannot import name 'ORDER_STATUS' from 'tigeropen.trade.domain.orde
r' (F:\anaconda_envs\vnpy_source\lib\site-packages\tigeropen\trade\domain\order.
py)

(F:\anaconda_envs\vnpy_source) D:\open_project\vnpy\tests\trader>
经过排查，把ORDER_STATUS修改成OrderStatus，就ok了

**Comment by vnpy** [comment]
DEV分支已经修复，谢谢
