### ISSUE TITLE
回测数据读取

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1835]
现在的模式是从数据库中读取数据，再直接发去回测计算。这里有个缺点就是数据量大的话会很慢，从数据库中要读很久了。（比如N年的tick）
从性能和效率的角度来考虑应该分开。一个线程专门来从数据库中读取数据放到队列，队列数据少于1万条就继续读。读完标记完成。
计算方面就可以不停从队列中提，直到为空并且标记完成为止。
从各种数据量来说，这个模式肯定综合性能较佳。

**Comment by viponedream** [comment]
如果回测是外汇，24小时的tick,  简直要死的心都有。

**Comment by vnpy** [comment]
几个方案吧：
1. 直接分段读取，分段回放（比较简单）
2. 独立线程，预热读取完成后就边回放边读取（在Python中因为GIL，线程间来回切换可能会导致回测更慢）
3. 独立进程，专门负责和数据库的请求和数据转发工作（之前1.9.2中我们提供过的回测目录下的HistoryDataServer）模式，但需要进一步扩展

综上来看，2没啥意义，1最简单，可以考虑后续快速支持下，3最彻底但需要投入精力做相当的开发


如果有兴趣的话欢迎贡献代码~

另外除非你是EBS Reuters上的原始ECN行情，否则经纪商那边来的外汇市场的tick回测意义不大。。。

**Comment by aslan9** [comment]
方案1可以单独线程维护数据读取，读完一段backtester可以回放，然后异步继续读取下一段，把io和cpu的消耗通过异步来并行化
