### ISSUE TITLE
同时订阅两百多个标的QT界面很卡，能把TickMonitor改为分页显示吗？

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1837]
能把TickMonitor改为分页显示吗？比如每一页只显示100条记录（每一页显示的记录数量可以由用户设置），超过100条记录则进行多页显示。用户可以通过点击“首页”、“上一页”、“下一页”、末页、“跳转”按钮加载想要显示的记录。

**Comment by vnpy** [comment]
1. 可以啊，自己基于TickMonitor扩展下20分钟的事情
2. 区区200个标的不应该卡，你是不是开了自动调整列宽？

**Comment by xldistance** [comment]
ui相关代码都没改的

**Comment by vnpy** [comment]
是2.0版本的吗？还是之前1.9.2的

**Comment by xldistance** [comment]
是2.0.3版本的，订阅两百以内的标的不卡......

**Comment by vnpy** [comment]
尝试同时订阅CTP的全部合约，没有卡顿现象，请检查是不是做了什么其他操作吧，比如对某些列进行了排序、自动调整列宽等
