### ISSUE TITLE
交互界面的选项问题

### ISSUE THREAD

**Issue by windiepop** [vnpy/vnpy#1839]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Enhancement

## 预期程序行为

1.登录过程中，一个柜员账号要对应多个现货及资金账号，登录时需做一个绑定。
2.VNPY的UI中，交易所对应的代码应为列表选取
3.现货不用填开平方向

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
你用的是什么接口？以上主要是个性化需求，可以自己选择修改或者找我们付费定制，并不会在开源项目中做修改
