### ISSUE TITLE
为什么自己封装出来vnctpmd.pyd和官方自带的pyd大小不一样呢

### ISSUE THREAD

**Issue by buermen** [vnpy/vnpy#1845]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
以前直接拿官方的用的，最近尝试自己按照教程封装API，结果发现自己封出来的小一些，6.3.15也不敢拿实盘账号随便测试啊

**Comment by vnpy** [comment]
可能是编译器问题、pybind11库版本问题、等等。。。确定功能一致就行

**Comment by uspizza** [comment]
@buermen
我也想从vnpy里面自己学着封装ctp的接口，
由于本人刚刚开始学python，有一些不太清楚的地方
想问一下，大神，能否加个qq，向您咨询。。谢谢，我的QQ是11315349，不胜感激
