### ISSUE TITLE
重复授权验证

### ISSUE THREAD

**Issue by cxjpower** [vnpy/vnpy#1848]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

ctp_gateway的connect方法中如下定义
        if not self.connect_status:
            path = get_folder_path(self.gateway_name.lower())
            self.createFtdcTraderApi(str(path) + "\\Td")
            
            self.subscribePrivateTopic(0)
            self.subscribePublicTopic(0)
            
            self.registerFront(address)
            self.init()            
        else:
            self.authenticate()
导致已经在连接状态时再次连接时重复进行授权验证, 给个警示性的提醒不就行了吗?有必要进行重复的授权验证吗?

**Comment by vnpy** [comment]
这里为了简化逻辑代码，重复验证没有影响
