### ISSUE TITLE
macos安装make install错误

### ISSUE THREAD

**Issue by hucs2542** [vnpy/vnpy#1852]
## 环境

* 操作系统: macos 10.14.4

* Anaconda版本:Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

* vn.py版本: 如v2.0.4

## Issue类型
三选一：Question

Requirement already up-to-date: wheel in /Users/hucong/anaconda3/lib/python3.7/site-packages (0.33.4)
/tmp /Users/hucong/python/vnpy
./install.sh: line 13: wget: command not found
tar: Error opening archive: Failed to open 'ta-lib-0.4.0-src.tar.gz'
./install.sh: line 15: cd: ta-lib: No such file or directory
./install.sh: line 16: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
/Users/hucong/python/vnpy

**Comment by vnpy** [comment]
用的是install_osx.sh？

**Comment by hucs2542** [comment]
@vnpy 是的

**Comment by newencn** [comment]
```
"./install.sh: line 13: wget: command not found"
Pls install the wget tools use command "brew install wget" firstly
```

**Comment by hucs2542** [comment]
@newencn 谢谢
