### ISSUE TITLE
订阅的套利合约的tick数据中没有最近交易数据

### ISSUE THREAD

**Issue by lipan0722** [vnpy/vnpy#1857]
环境
操作系统: Windows 7
Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
vn.py版本: v1.9.2 LT/s
Issue类型
三选一：Bug

订阅的套利合约的tick数据中没有最近交易数据，如图：
![clipboard](https://user-images.githubusercontent.com/2306664/59931100-d4473900-9476-11e9-8833-8b42903a6d88.png)
另外，我在onTick事件中将tick打印出来发现lastPrice没有初始化，
lastPrice:1.79769313486e+308

是否是程序中有Bug?怎样才能取到套利合约的tick数据的最近交易价格，望指教，谢谢！

**Comment by vnpy** [comment]
这个数字是溢出了，应该为0，套利合约没有最新成交价，只有两条腿的合成买卖价

**Comment by lipan0722** [comment]
本来我也是这么想的，但一看其他的交易软件有最近的交易记录，难道也是通过基础合约合成的？有点不像啊。

**Comment by vnpy** [comment]
如果是文华之类的话，他们的套利行情是自己另外合成的，而并非完全使用CTP的套利TICK推送数据
