### ISSUE TITLE
在屏幕上显示GUI

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1860]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为

我可以看到下面的GUI，当我通过拖动调整它的大小时，它是隐藏的。 我使用功能“恢复窗口”它显示错误：
` QWindowsWindow::setGeometry: Unable to set geometry 1366x761+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1366x690+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 300x761, maximum size: 16777215x16777215).
QWindowsWindow::setGeometry: Unable to set geometry 1366x820+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1366x690+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 413x820, maximum size: 16777215x16777215).
QWindowsWindow::setGeometry: Unable to set geometry 640x820+0+0 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  646x820+0+0 (frame: 9, 26, 13, 13, custom margin: 0, 0, 0, 0, minimum size: 413x820, maximum size: 16777215x16777215).
QObject::~QObject: Timers cannot be stopped from another thread
`

https://imgur.com/WjHJK0T

https://imgur.com/RMzOapt

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这是因为屏幕分辨率不够导致的，请使用1920x1080的分辨率

**Comment by cbogithub** [comment]
但我的笔记本电脑屏幕没有1920x1080分辨率。 怎么解决？

https://imgur.com/Os7Pwlj
