### ISSUE TITLE
DataRcording错误代码90 CTP：查询未就绪

### ISSUE THREAD

**Issue by kumaxs** [vnpy/vnpy#1864]
## 环境

* 操作系统: 如Windows server 2008
* Anaconda版本: 如Anaconda python2.7
* vn.py版本: 192

## Issue类型
三选一：Bug/Enhancement

## 实际程序行为
DataRecording偶然出现 错误代码90 CTP：查询未就绪
检查数据库出错后数据没有继续录入

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这是CTP柜台还没完成初始化，请在开盘时段连接
