### ISSUE TITLE
关于临时目录 log文件

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1866]
目前的目录是这样的。
vnpy/api
vnpy/trader
我觉得可以再建一个 vnpy/var专门存放各种临时文件
如vnpy/var/log
vnpy/var/temp 等等
这样整个vnpy的文件在哪里一找就明白。
并且这个 var目录可以随意删除。需要的时候它自己建立。

**Comment by vnpy** [comment]
临时文件目前默认位于用户目录下的.vntrader目录中。

以我的Windows为例：
> C:\users\administrator\.vntrader

对于Mac和Linux系统，也会使用默认的用户目录。

同时用户也可以手动在某一文件夹创建.vntrader目录，在此目录下启动VN Trader时就会将该目录作为运行时目录。
