### ISSUE TITLE
EOF occurred in violation of protocol(_ssl.c:2341)

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1869]
![微信图片_20190627080716](https://user-images.githubusercontent.com/29418474/60224366-afa6f300-98b4-11e9-9cf7-c8c943df5a89.png)
初步定位，出错位置在websocket_client.py的_send_text里面的ws.send(text, opcode=websocket.ABNF.OPCODE_TEXT)

**Comment by xldistance** [comment]
做了try处理，这样可以了吗
![QQ截图20190627083350](https://user-images.githubusercontent.com/29418474/60224739-55a72d00-98b6-11e9-99c6-5ed83b5be61a.png)

**Comment by vnpy** [comment]
@nanoric 请看下怎么处理？

这个try...catch是能个捕捉和避免掉异常输出，但也同样会丢包（丢失了该次请求），并不是太好的处理方案

**Comment by xldistance** [comment]
虽然用了try except但是断线重连不稳定，连了三四次后就收不到行情了，help

**Comment by xldistance** [comment]
![QQ截图20190709141436](https://user-images.githubusercontent.com/29418474/60863678-0c5ec200-a254-11e9-8340-d86ec9ac404d.png)

**Comment by vnpy** [comment]
还是1token的接口嘛？

**Comment by xldistance** [comment]
> 还是1token的接口嘛？

是的，难道是他们接口的问题？一到凌晨就抽风......

**Comment by vnpy** [comment]
我估计是有什么切换断线机制，因为所有币圈接口都是通用WebsocketClient组件，其他接口目前从未出现这个问题

**Comment by xldistance** [comment]
> 我估计是有什么切换断线机制，因为所有币圈接口都是通用WebsocketClient组件，其他接口目前从未出现这个问题

现在的onetokengateway断线重连经常无法正常重连或者重复推送行情或者交易连接导致行情堵塞，偶尔也会正常重连，这不是修修补补就能解决的问题了......
