### ISSUE TITLE
发单的时候触发错误：wrapped C/C++ object of type BaseCell has been deleted

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1870]
![QQ截图20190627092805](https://user-images.githubusercontent.com/29418474/60226642-b89cc200-98be-11e9-839a-017478290d43.png)

**Comment by HorsenLi** [comment]
遇到了同样的问题

**Comment by vnpy** [comment]
这是由于委托回报推送状态的乱序导致的，说白了就是一个已经被认为结束的委托，又收到了活动状态的更新。请问下是用的哪个交易接口，我们来查下？

**Comment by xldistance** [comment]
> 这是由于委托回报推送状态的乱序导致的，说白了就是一个已经被认为结束的委托，又收到了活动状态的更新。请问下是用的哪个交易接口，我们来查下？

onetoken接口，确实有交易所已成交或者已撤销的订单在vnpy里面依然保留为未成交订单的情况

**Comment by HorsenLi** [comment]
> > 这是由于委托回报推送状态的乱序导致的，说白了就是一个已经被认为结束的委托，又收到了活动状态的更新。请问下是用的哪个交易接口，我们来查下？
> 
> onetoken接口，确实有交易所已成交或者已撤销的订单在vnpy里面依然保留为未成交订单的情况

我在用Binance接口，也有这个问题

**Comment by xldistance** [comment]
@HorsenLi 我已经修复了，是order里面的取消委托状态判断错误导致已撤销或已成交的订单在active_order里面无法删除

**Comment by vnpy** [comment]
> @HorsenLi 我已经修复了，是order里面的取消委托状态判断错误导致已撤销的订单在active_order里面无法删除

发个PR呗
