### ISSUE TITLE
做出更好的合同查询GUI

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1871]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

太难记住本地代码（vt_symbol），请让GUI可以在查看合同查询时复制本地代码（vt_symbol）
谢谢

**Comment by xldistance** [comment]
你选中查询合约里面的合约ctrl+c不就是复制了......

**Comment by cbogithub** [comment]
> 
> 
> 你选中查询合约里面的合约ctrl+c不就是复制了......

thanks
