### ISSUE TITLE
Limit REST connection

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1873]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
当我使用“龟战略”并大约10分钟我有错误。 我发现ccxt lib的“enableRateLimit”限制连接到交换服务器。 如何使用vnpy启用它
`response:{"code":-1101,"msg":"Too many parameters; expected '1' and received '3'`

**Comment by vnpy** [comment]
1. 建议不要用ccxt接口，成熟度较低问题挺多的
2. 这个报错是请求参数字段错误，具体原因要查ccxt了
