### ISSUE TITLE
请问目前有记录实盘交易记录的功能么？用于核对交易和回测是否一致使用，谢谢啦

### ISSUE THREAD

**Issue by hello886** [vnpy/vnpy#1877]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by lipan0722** [comment]
可以在onTrade中在数据库中记录

**Comment by vnpy** [comment]
1. 目前推荐用主界面的成交、监控组件，导出CSV记录然后做分析
2. 收到了以ORM模式保存数据的PR，但考虑到大部分实盘交易程序并无实时落地成交记录的需求，同时对于委托量较大的策略，实时落地会明显拖慢交易逻辑，因此不合并到代码中，有需要的用户请自行修改吧
