### ISSUE TITLE
vnctpmd.so vnltsmd.so有32位的库版本吗？

### ISSUE THREAD

**Issue by DennisFoo** [vnpy/vnpy#188]
首先谢谢  vnpy提供了如此好的框架。目前正在32位的ubuntu上进行安装。碰到了vnctpmd.so 和vnltsmd.so只支持64位的问题。想问一下 vnctpmd.so vnltsmd.so有32位的库版本吗？ 非常谢谢啦

**Comment by vnpy** [comment]
不好意思，因为官方API只提供了64的so，所以没有32的
