### ISSUE TITLE
fix unicode in write csv file

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1885]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
```
App\lib\site-packages\vnpy\trader\ui\widget.py", line 330, in save_csv
    writer.writerow(row_data)
  File "E:\WARTER\python\App\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 13-14: character maps to <undefined>

```

and line 317 in widget.py should be  :  `with open(path, "w",encoding='utf-8') as f:`

**Comment by vnpy** [comment]
Python3的open函数会直接使用系统默认的编码，对于中文系统就是GBK，所以可以正常显示，改为UTF-8后反而通过EXCEL等软件默认打开都是乱码，需要手动调整编码后才能显示。

你这里报错应该是使用了英文系统，请换成中文系统或者在你的本地代码中自行修改吧。
