### ISSUE TITLE
Too many parameters when use turtle strategy

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1887]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

当我使用Turtle Strategy约20分钟。(Binance Exchange) 它显示错误：
```

response:{"code":-1101,"msg":"Too many parameters; expected '1' and received '3'."}
request : PUT /api/v1/userDataStream?listenKey=UDm78c&timestamp=1561974959471&signature=failed because 400: 
headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json', 'X-MBX-APIKEY': ''}
params: {}
data: {}
response:{"code":-1101,"msg":"Too many parameters; expected '1' and received '3'."}

```
怎么解决？

**Comment by xldistance** [comment]
你用的是哪个交易所接口

**Comment by cbogithub** [comment]
我知道了 Binance api :
-1003 TOO_MANY_REQUESTS
Too many requests queued.
Too many requests; please use the websocket for live updates.
Too many requests; current limit is %s requests per minute. Please use the websocket for live updates to avoid polling the API.
Way too many requests; IP banned until %s. Please use the websocket for live updates to avoid bans.

我认为turtle_strategy向Binance服务器发送限制请求然后被禁止.
我认为我们应该每秒限制请求发送api服务器以避免它

**Comment by cbogithub** [comment]
I see Binance api :

https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md#-1001-disconnected

``°1001 DISCONNECTED
Internal error; unable to process your request. Please try again.```

**Comment by vnpy** [comment]
已修复！非常感谢发现这个bug
