### ISSUE TITLE
用ib接口订阅SMART里的GLD报错

### ISSUE THREAD

**Issue by mousewu** [vnpy/vnpy#189]
报错如下：The contract description specified for GLD is ambiguous.
但是SMART里只有GLD一个代码，错误原因不明

**Comment by vnpy** [comment]
我在IB网站的合约查询里找了下，没有这个SPDR GLD的合约信息，也是奇怪了，有一堆其他类似的黄金ETF（比如有个投资COMEX黄金期货的）。我估计主要问题出在可能GLD在IB上采用的是什么别的名字

**Comment by vnpy** [comment]
IB的合约定义里有个PrimaryExch字段，用于解决潜在的不同交易所合约代码重复的情况。
