### ISSUE TITLE
CTA strategy界面显示不完整

### ISSUE THREAD

**Issue by xinhuih** [vnpy/vnpy#1890]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.04发行版

## Issue类型
三选一：Bug

## 预期程序行为
CTA strategy 界面完整的显示参数

## 实际程序行为
当同时运行的策略超过一定数目，界面被挤在一起，看不见参数了。这个完全是ui的问题因为并不影响运行。但我实在是对qt不熟悉，没找到原因。

## 重现步骤
同时开40个策略，截图如下L
![Screenshot from 2019-07-02 12-23-55](https://user-images.githubusercontent.com/13801052/60482614-d86c2580-9cc4-11e9-9899-8cae9ff69e0d.png)

**Comment by vnpy** [comment]
已修复，调整策略组件为固定高度
