### ISSUE TITLE
Language and Broker

### ISSUE THREAD

**Issue by hpsilva** [vnpy/vnpy#19]
First off, congratulations for the robust code very nicely written.

I am wondering if you are considering to include an **English language version and support for other **brokers**, as i.e. Oanda. Either have a nice API which integrates seamlessly with Python.

As i did not have how to contact you by any other way, i have opened this issue.

Looking for your feedback

Thanks

**Comment by snake3342** [comment]
thanks for your interest.
I also expect good docs of vn.py however Chinese version of the docs are far from complete as well. so I cannot determine when the English version will come out.

considering the trading adapters/channels APIs currently supported by vn.py are all for stocks, future contracts and options in Chinese exchanges. now forex brokers are not contained in it yet(such as Oanda).

**Comment by vnpy** [comment]
Hi, thanks for your interest.

One of main task of the project in 2016 is to complete the docs in Chinese, not sure when i can finish that job at the moment. After that, I would try to spend some time writing English comments in .py files.

Considering brokers outside China, vn.py supports InteractiveBrokers for now and Oanda is a great suggestion. I will include the support of Oanda in the project by the end of May.

Best

**Comment by hpsilva** [comment]
Thank you all for the feedback.

Sounds good, especially because it's free and from my point of view you guys made a really neat implementation.

If i can be of any help to speed up anything, i.e. the translation part or any other, just let me know.

Cheers!

**Comment by vnpy** [comment]
Hi, @hpsilva .

I have just tried to use the REST API of Oanda but I can't find where to get the personal token on my practice account management page.

I followed the instructions on this page http://developer.oanda.com/rest-live/introduction/
and there is no  “Manage API Access” under “Other Actions” in my Account Management Portal (AMP).

Do you know how to get the token?

Thanks.

**Comment by hpsilva** [comment]
Hey @vnpy ,

You shall first create your demo account and have at hand your **username and password** for login. Next, it shall be easy to reach the API management screen, i made a step by step here: 
[Oanda API key.pdf](https://github.com/vnpy/vnpy/files/139778/Oanda.API.key.pdf)


See if this is of help for you.

Helio

**Comment by vnpy** [comment]
Thanks! I need to choose UK when registering the practice account. Working on the api now!

**Comment by hpsilva** [comment]
Glad it was of help!

Allow me to point you to two major tools concerning OANDA broker:
* https://github.com/oanda/oandapy - Oanda API wrapper for Python
* http://hootnot.github.io/oanda-trading-environment/ - Tick/Candle 'factory' Python based

Both of them provide examples on how to work with, and/or can provide with great inside on how the broker API works.

Cheers

**Comment by vnpy** [comment]
Hi, thanks for the info! I have just completed a beta version of vn.oanda. Please have a look.

At the moment there is only Chinese documents and comments in the code. Sorry about that.

**Comment by vnpy** [comment]
Since it's coming close to the release of v1.0 of vn.py project, I think it's the time to close this issue.

There will be more detailed english documents and comments in English about vn.oanda before the end of 2016, which I believe is a better implementation (async function call!) compared with other OANDA python apis.

However, for vn.trader which is a trading platform specifically designed for algo trading in China, there will be only chinese documents at the moment.

Hope you find that helpful.
