### ISSUE TITLE
用IB发单出现这个提示。

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#190]
File "D:\TradeSystem\vnpy\vn.trader\ibGateway\ibGateway.py", line 564, in execDetails
    trade.vtOrderID = '.'.join([self.gatewayName, trade.orderId])
AttributeError: 'VtTradeData' object has no attribute 'orderId'

下单成功。只是出现这个提示。
那个 orderID 大小写 写错了。

**Comment by vnpy** [comment]
已修复！
