### ISSUE TITLE
[Enhancement] check open port before open it RPC module

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1900]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
我认为应该在RPC模块（服务器）中打开之前添加check open port以避免错误“zmq.denies
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前的RpcEngine在启动RPC服务器时，已经使用了try...catch...捕捉，如果因为bind的地址和端口已在使用中，则会自动输出相关的异常信息，用户可以根据此进行调整，因此无需做额外的端口可用性检查，另外在linux上如果使用local socket也不是通过tcp端口通讯。
