### ISSUE TITLE
[question] 如何在“CTA战略”中获得资金

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1901]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

如何在“CTA战略”中获得资金调整秩序，
例如：我交易FTMBNB.BINANCE。我如何得到BNB基金

**Comment by xldistance** [comment]
def register_event(self):
        """       
        注册事件引擎
        """
        self.event_engine.register(EVENT_TICK, self.process_tick_event)
        self.event_engine.register(EVENT_ORDER, self.process_order_event)
        self.event_engine.register(EVENT_TRADE, self.process_trade_event)
        self.event_engine.register(EVENT_POSITION, self.process_position_event)
        self.event_engine.register(EVENT_ACCOUNT, self.process_account_event)
    def process_account_event(self,event: Event):
        """处理账户推送"""
        account = event.data
        for strategy_name in self.strategies.keys():
            strategy = self.strategies[strategy_name]        
            self.call_strategy_func(strategy, strategy.on_account, account)

**Comment by vnpy** [comment]
楼上正解，但官方不建议这么做，因为资金和仓位通知不是实时的
