### ISSUE TITLE
vnpy2.0.5下的各种setting.json文件模板

### ISSUE THREAD

**Issue by ramoslin02** [vnpy/vnpy#1905]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
能否提供一个各个app下的setting.json文件的模板。 另外就是程序入口自己初始参数example能否多点demo呢/

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by ramoslin02** [comment]
另外现在的配置文件路径都放大根目录下的.vntrader/ 目录下， 对于部署上是不是有些不便呢？

**Comment by ramoslin02** [comment]
另外最好提供下各个模块的使用的demo, 这样对于新手入门会更好。谢谢。

**Comment by vnpy** [comment]
直接通过图形界面加载运行一次后，就会在用户目录下的.vntrader中生成（xx_setting.json），比如：

C:\users\administrator\.vntrader\cta_strategy_setting.json

然后参考其中的数据修改。
