### ISSUE TITLE
generated_files/classes_1.cpp: No such file or directory

### ISSUE THREAD

**Issue by liuguangzhong** [vnpy/vnpy#1906]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Python 3.7 64位
* vn.py版本: v2.05（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
 running build_ext
    building 'vnpy.api.ctp.vnctptd' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/vnpy
    creating build/temp.linux-x86_64-3.7/vnpy/api
    creating build/temp.linux-x86_64-3.7/vnpy/api/ctp
    creating build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp
    creating build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd
    gcc -pthread -B /home/caros/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ivnpy/api/ctp/include -Ivnpy/api/ctp/vnctp -I/home/caros/anaconda3/include/python3.7m -c vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd/vnctptd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/caros/anaconda3/compiler_compat -L/home/caros/anaconda3/lib -Wl,-rpath=/home/caros/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd/vnctptd.o -Lvnpy/api/ctp/libs -Lvnpy/api/ctp -Wl,-R$ORIGIN -lthostmduserapi_se -lthosttraderapi_se -o build/lib.linux-x86_64-3.7/vnpy/api/ctp/vnctptd.cpython-37m-x86_64-linux-gnu.so -lstdc++
    building 'vnpy.api.ctp.vnctpmd' extension
    creating build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctpmd
    gcc -pthread -B /home/caros/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ivnpy/api/ctp/include -Ivnpy/api/ctp/vnctp -I/home/caros/anaconda3/include/python3.7m -c vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/caros/anaconda3/compiler_compat -L/home/caros/anaconda3/lib -Wl,-rpath=/home/caros/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.o -Lvnpy/api/ctp/libs -Lvnpy/api/ctp -Wl,-R$ORIGIN -lthostmduserapi_se -lthosttraderapi_se -o build/lib.linux-x86_64-3.7/vnpy/api/ctp/vnctpmd.cpython-37m-x86_64-linux-gnu.so -lstdc++
    building 'vnpy.api.oes.vnoes' extension
    creating build/temp.linux-x86_64-3.7/vnpy/api/oes
    creating build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes
    creating build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files
    gcc -pthread -B /home/caros/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBRIGAND_NO_BOOST_SUPPORT=1 -Ivnpy/api/oes/include -Ivnpy/api/oes/vnoes -I/home/caros/anaconda3/include/python3.7m -c vnpy/api/oes/vnoes/generated_files/classes_1.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/classes_1.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
    gcc: error: vnpy/api/oes/vnoes/generated_files/classes_1.cpp: No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/caros/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-7kjpr9wj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ej7dwzlb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-7kjpr9wj/
(base) caros@caros-S:~/Downloads/vnpy-2.0.5$ 

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已发PR合并，请使用最新Master分支的代码
