### ISSUE TITLE
CTP:缺少ExchangeID字段，请填入ExchangeID

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#1913]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v1.9

## Issue类型
三选一：Bug/Enhancement

## 实际程序行为
ctp发单交易报错，错误信息：
CTP:缺少ExchangeID字段，请填入ExchangeID

## 重现步骤
simnow测试交易即报错，接口修改了，具体信息如下：

【终端开发重要通知】TradeAPI使用微调
各位终端开发商好！
在CTP期货生产交易系统V7.0.0版本及之后版本（预计3~5个月内发布，目前生产最新版本为CTP V6.3.17_P4_20190628），客户端在使用tradeapi时，业务指令中有InvestorID和exchangeID的域都必须填写，之前没有填写的后台将会返回错误。其中：
1）交易所编号ExchangeID全部大写CFFEX、CZCE、DCE、INE、SHFE；
2）此处的业务类指令指交易类，不是查询类；换言之查询类接口无须变动；
3）现有官网TradeAPI都已支持；
4）7月中旬左右，SimNow网站提供Internet测试环境，具体时间请关注本群。
特此提前通知，请各位开发商务必仔细核查系统是否有遗漏或没有填写，并安排开发计划进行修改。

错误截图：
![image](https://user-images.githubusercontent.com/31505150/60930697-36ae8f00-a2e9-11e9-9129-cf79ce234d5f.png)

**Comment by stone3536** [comment]
@vnpy 目前测试环境都没法测试了。

**Comment by lipan0722** [comment]
我报的不是这个错，报的是“CTP：客户端认证失败”，也不知道是不是一个原因

**Comment by smartgang** [comment]
在ctpGateway.py的sendOrder函数里找个地方加这一句就可以了：
req['ExchangeID'] = orderReq.exchange.upper()

**Comment by vnpy** [comment]
已在DEV分支修改

**Comment by hello886** [comment]
> @vnpy 目前测试环境都没法测试了。

目前时可以测试的，sinmow最近改了地址，你可以尝试以下地址，
由于目前SIMNOW前置流量压力激增。在系统设置上进行调整后,决定再进行接入地址修改:
第一组:Trade Front:180.168.146.187:10100,Market Front:180.168.146.187:10110;【电信】(非看穿式前置)
第二组:Trade Front:180.168.146.187:10101,Market Front:180.168.146.187:10111;【电信】(看穿式前置,使用监控中心生产秘钥)
第三组:Trade Front:218.202.237.33 :10102,Market Front:218.202.237.33 :10112;【移动】(看穿式前置,使用监控中心生产秘钥)
（我使用的时第三组）
需要注意
1，sinmow目前没5档行情（至少我使用的第三组时没有的，需要对代码作微调）
2，使用vnpy的ctp接口，而非ctptest，否则报错63

**Comment by hello886** [comment]
> 我报的不是这个错，报的是“CTP：客户端认证失败”，也不知道是不是一个原因

ctp地址修改了，需要修改地址和接口使用ctp而非ctptest

**Comment by wwwzf** [comment]
我的是2.0.5使用CTP，用第三组时，行情服务器连接成功，交易服务器提示断开，4097；用第二组时，行情和交易服务器连接成功，但是提示交易服务器授权验证失败，63；

**Comment by sinreal** [comment]
@vnpy  这个bug fix了吗？ 我按照 [ 这里fix ](https://github.com/vnpy/vnpy/commit/62a0451d418a092a63c9d3b598ac448ee23ce221) 更新了代码之后，在最新版本的vnstation 里 的simnow环境下 下单后（一直不成交），之后撤单，依旧返回交易撤单失败，代码147，CTP 缺少ExchangeID 错误

**Comment by vnpy** [comment]
已经修复了，2.0.6和1.9.2LTS都确认SIMNOW使用没问题
