### ISSUE TITLE
每次我开单（期指IF，对锁各9手）, 系统会自动开现有的持仓量9

### ISSUE THREAD

**Issue by asustnt3** [vnpy/vnpy#1919]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug or Question

## 预期程序行为
期指IF1907合约实盘，发单函数里lock参数全部是True，全部是limit order
我当时持仓是9空9多对锁的， 然后开一手多单，没成交，撤单，然后再开一手。

## 实际程序行为
没想到每次我开一手多单，系统会后面跟着开9手多单。
奇怪之处：
1 跟着我立刻开
2 数量是现有的持仓量，这数据我策略里得不到的，我开仓用1，平仓用abs(self.pos),（平了1手多单后，我下午开空单的时候它会跟着开8手空单）
3 我用的是Lock模式，应该先平掉昨天的再开，它却不平，直接是开

![image](https://user-images.githubusercontent.com/19390719/61055067-4cc06a80-a423-11e9-8446-b276516b8c0c.png)
分别是 策略名：status  direction  offset  traded  price
cta策略里的write_log()截图，是on_order()函数下的order回报数据  volume没有打印出来 我标记了下。

![image](https://user-images.githubusercontent.com/19390719/61055920-1126a000-a425-11e9-9342-d388f96d4dce.png)
Trader主界面的委托栏，这里volume显示出来了

**Comment by asustnt3** [comment]
今天测试下来 问题在cta_strategy里：
send_server_order()里会莫名多开单， 而send_order()函数里就没有.  send_limit_order我没有测。我也搞不懂为什么会不一样。 只能在cta_strategy里新加一个变量，来过滤这个新开的单子
ps  策略文件和template文件里的send_order() 函数write_log()下来都是没有问题的

**Comment by vnpy** [comment]
send_server_order内部，会开平自动转换的逻辑，负责：
1. 锁仓交易模式，适用于：中金所股指这种带有平今惩罚的合约
2. 上期所模式，适用于：上期所品种平今平昨需要分开发出的模式

这两个模式目前我们测试工作正常，但也有可能存在我们未考虑充分的情况，推荐升级到2.0.5试试看

**Comment by asustnt3** [comment]
我在send_server_order()里write_log 这个单子的时候发现 奇怪的地方 
它 lock参数是True的， lock默认都是False的
按理说 self.offset_converter.convert_order_request(original_req, lock)自动转换出来 会平掉昨天的9手空单，但它转换出来还是开仓9手。

**Comment by vnpy** [comment]
lock参数默认皆为False，如果有True的情况必然是策略里某处的委托函数调用中传了lock=True，请检查下吧。
