### ISSUE TITLE
提交委托时小数保留错误

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#1924]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.5（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="565" alt="屏幕快照 2019-07-14 下午4 11 40" src="https://user-images.githubusercontent.com/10345996/61188779-26ccdd00-a652-11e9-824e-e68f4bec0adc.png">

右侧图片分别是 策略委托价格，pricetick，和实际下单价格。
utility.round_to 函数可能有问题。

**Comment by cbogithub** [comment]
相同 https://github.com/vnpy/vnpy/issues/1902
请更新最新版本

**Comment by vnpy** [comment]
这是由于计算机内的浮点数计算精度导致的问题，由于各编程语言的都是同样的设计，所以应当无明显影响，只是对看的人来说不方便：https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by yunnant** [comment]
确实是有影响的，我发现这个问题是因为火币返回 
1038 | 报单价格不符合最小变动价 错误 导致无法下单，
我自己的解决方案是计算好后保留小数转换成字符串再转回float下单就没问题了，另外也可以考虑decimal包。

**Comment by yunnant** [comment]
> 相同 #1902
> 请更新最新版本

确实是有影响的，我发现这个问题是因为火币返回
1038 | 报单价格不符合最小变动价 错误 导致无法下单，
我自己的解决方案是计算好后保留小数转换成字符串再转回float下单就没问题了，另外也可以考虑decimal包。

**Comment by yunnant** [comment]
> 这是由于计算机内的浮点数计算精度导致的问题，由于各编程语言的都是同样的设计，所以应当无明显影响，只是对看的人来说不方便：https://stackoverflow.com/questions/588004/is-floating-point-math-broken

确实是有影响的，我发现这个问题是因为火币返回
1038 | 报单价格不符合最小变动价 错误 导致无法下单，
我自己的解决方案是计算好后保留小数转换成字符串再转回float下单就没问题了，另外也可以考虑decimal包。

**Comment by vnpy** [comment]
哦哦，因为火币是REST接口，直接float转str就发单出去了，方便的话欢迎发个PR我们看看怎么处理的

**Comment by yunnant** [comment]
> 哦哦，因为火币是REST接口，直接float转str就发单出去了，方便的话欢迎发个PR我们看看怎么处理的

我是注释掉原版的保留小数，在策略里改的，方法麻烦了点，不太会发pr就在这回复了。

self.decimal=%.2f（保留两位小数）
self.slip=滑点
self.buy(float(self.decimal%(ta.TicklastPriceArray[-1]*(1+self.slip))), self.fixed_size, False)
