### ISSUE TITLE
onetoken接口有时重复推送行情登录函数导致行情堵塞

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#1925]
OnetokenDataWebsocketApi类里面的on_login函数不知道为什么有时登录成功后还会触发一次导致回调函数on_tick堵塞收不到行情数据。
正常的登录信息是
2019-07-15 09:37:35,663  INFO: 行情Websocket API连接成功
2019-07-15 09:37:35,710  INFO: 交易Websocket API连接成功
2019-07-15 09:37:35,743  INFO: 行情Websocket API登录成功
行情Websocket API登录成功后再触发一次就会堵塞行情，实在是找不到原因

**Comment by xldistance** [comment]
行情堵塞时的登录日志
![QQ截图20190715213927](https://user-images.githubusercontent.com/29418474/61220545-1c413f00-a749-11e9-8467-4f1cf03fcb70.png)

**Comment by xldistance** [comment]
我推测的原因是OnetokenDataWebsocketApi类里面的on_connected函数在正常连接后不知道什么原因又推送了一次，运行了self.login()发送了一次登录请求，on_packet又把tick数据推送到on_login，堵塞了on_tick的行情。只知道原因，目前还没有好的解决办法......

**Comment by xldistance** [comment]
行情api重复登录后OnetokenDataWebsocketApi类里面的on_packet接收到的channel是pong，然后一直刷新，正常情况下接收的channel是single-tick-verbose。
![QQ截图20190718085814](https://user-images.githubusercontent.com/29418474/61421628-82d97f00-a93a-11e9-8109-eede8deab4bf.png)

**Comment by vnpy** [comment]
onetoken_gateway是1token那边团队贡献的代码，按理说应该比较熟悉他们自身API不会出这种问题，回头我来查下吧

**Comment by xldistance** [comment]
暂时的解决办法是记录OnetokenDataWebsocketApi类里面的on_login登录状态次数，登录到两次写入false到本地，再通过cta_trading父进程读取状态重新启动子进程，笨人方法😁😁😁

**Comment by vnpy** [comment]
简单粗暴，果然是vn.py老用户的风格，可以的...
