### ISSUE TITLE
CTP接口的Tick行情数据数字溢出问题

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#1926]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
![117c532b-1a78-46eb-9fd9-9fb4a4169f6b](https://user-images.githubusercontent.com/11263900/61261905-ee461400-a7b5-11e9-966a-44994213d30b.png)

**Comment by unlimitnight0** [comment]
我把数据类型改成了double就好了

**Comment by vnpy** [comment]
和#1916重复
