### ISSUE TITLE
回测引擎的cross_stop_order方法疑似BUG

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#1929]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.5

## Issue类型
Bug

## 实际程序行为
![image](https://user-images.githubusercontent.com/35967505/61347703-7ef12280-a890-11e9-8609-6d9dccca8883.png)

app.ctastrategy.backtesting，def cross_stop_order(self):函数里面
在828-843行，撮合停止单的函数里面出现了limit_order_count、limit_orders这种限价单的变量
是不是BUG？

**Comment by vnpy** [comment]
不是BUG，逻辑本身就是如此，本地停止单被触发后还是要发出限价单去执行委托成交。
