### ISSUE TITLE
IB，如何获得“市场深度”的行情数据？

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#1930]
群主，您好

vnpy是1.9.2的版本，IB，如何获得“市场深度”的行情数据？

在vnpy的 vnib.pi文件里边有函数def reqMktDepth(self, arg0, arg1, arg2, arg3, arg4):的，但是不知道该如何使用，我试着在ibGateway.py文件调用reqMktData的位置也类似调用，但是debug在dr模块中没有看到深度行情数据的，不知道是不是ib的接口没做？

恳请您百忙中增加这部分功能，谢谢！

**Comment by vnpy** [comment]
1. 需要先购买付费行情的授权
2. 修改接口中的部分逻辑，支持多档

**Comment by stone3536** [comment]
基本上是可以解决的了

在订阅位置调用
self.api.reqMktDepth(self.tickerId, contract, 5, TagValueList())

在回调位置通过函数
def updateMktDepth(self, id_, position, operation, side, price, size):
就可以获得深度行情数据的了。
这里就得参照 tickPrice 把数据拼到 5 档上边的了。这个位置处理还是有点儿繁琐的，不仅要考虑怎么更好的加到tick上边，tickPrice的价格好像和深度的1档有时候有点儿差异的，ib技术同事目前现在也确认不了。


感谢群主的指点，谢谢！

**Comment by stone3536** [comment]
可以的话建议在vnpy的2.0.6以上版本支持深度行情数据，放到通用5档上边就好了。

**Comment by stone3536** [comment]
补充下，
IB回复了，回复内容如下：
我们和欧洲的API部门确认了一下，正像电话中所说的一样reqMktDepth返回的1层数据是没有经过处理（非snapshot），所以和reqMktData的数据并不一致。
