### ISSUE TITLE
dev 和 master 分支编译失败

### ISSUE THREAD

**Issue by zhangr011** [vnpy/vnpy#1932]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本:
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
* vn.py版本: dev af37ba8beb946c64f684e3d7feb5556bd59a421c

## Issue类型
三选一：Bug

## 预期程序行为
正常通过编译。

## 实际程序行为
In file included from vnpy/api/oes/vnoes/include/autocxxpy/autocxxpy.hpp:12:0,
                 from vnpy/api/oes/vnoes/generated_files/generated_functions_0.cpp:8:
vnpy/api/oes/vnoes/include/autocxxpy/cross_assign.hpp:11:11: warning: ‘autocxxpy::cross_assign’ declared with greater visibility than the type of its field ‘autocxxpy::cross_assign::_delay_assings’ [-Wattributes]
     class cross_assign
           ^~~~~~~~~~~~
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
error: command 'gcc' failed with exit status 4

8 g 内存 + 10 g 虚拟内存耗尽……
v2.0.4 编译能正常完成

## 重现步骤

运行 bash ./install.sh 或者 python ./setup.py install

**Comment by cbogithub** [comment]
编译时似乎是重载RAM

**Comment by vnpy** [comment]
请尝试重启机器，并且不要启动其他程序，直接进行安装

**Comment by zhangr011** [comment]
可以对比一下 v2.0.4 和 dev 分支，编译的速度下降明显

**Comment by vnpy** [comment]
最新的2.0.5分支升级了autocxxpy封装库，编译耗时是会有上升

**Comment by yunnant** [comment]
[https://ibb.co/dtr5RM2](url)
同样资源耗尽。。

**Comment by zhangr011** [comment]
问题应该出在 oes 的编译上，暂时屏蔽了，可以正常编译。
oes 中确实是耗在了 autocxxpy 的编译上，最终把内存吃完了。
