### ISSUE TITLE
Update GUI

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1935]
![Capture190419](https://user-images.githubusercontent.com/9572613/61522889-7d189200-aa3d-11e9-9b87-cbe61602ecb5.PNG)
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

当我运行策略时，signal_pos没有在GUI上更新，它总是显示{0,0,0}。 只有我按停止按钮然后按开始按钮signal_pos将更新{1,1,1}。
如何更新GUI每个signal_pos更新

**Comment by vnpy** [comment]
在策略内调用put_event函数，通知GUI更新界面
