### ISSUE TITLE
传统时的性能负载条（加密货币交易）

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1936]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

通常，ArrayManager将加载100 bar。 如果使用
   -  BarGenerator（self.on_bar，1，self.on_5min_bar）将100 * 1 = 100分钟，这意味着我们需要等待100分钟才能进行交易
 -  BarGenerator（self.on_bar，5，self.on_5min_bar）必须等待100 * 5 = 500分钟然后可以交易

为什么我们可以使用Restapi加载historycal，它更快？

**Comment by vnpy** [comment]
目前所有的数字货币接口都提供了历史数据加载功能，初始化策略时会自动从服务器拉取最新的数据
