### ISSUE TITLE
海龟策略模板的的加仓逻辑是否是有问题？

### ISSUE THREAD

**Issue by ramoslin02** [vnpy/vnpy#1937]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.5 发行版或者（2019-7-16）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
    首先程序开始没有仓位的时候走以下方法：
```
        if not self.pos:
            self.atr_value = self.am.atr(self.atr_window)

            self.long_entry = 0
            self.short_entry = 0
            self.long_stop = 0
            self.short_stop = 0

            self.send_buy_orders(self.entry_up)
            self.send_short_orders(self.entry_down)
```
 但是成交之后

```
    def on_trade(self, trade: TradeData):
        """
        Callback of new trade data update.
        """
        if trade.direction == Direction.LONG:
            self.long_entry = trade.price
            self.long_stop = self.long_entry - 2 * self.atr_value
        else:
            self.short_entry = trade.price
            self.short_stop = self.short_entry + 2 * self.atr_value
```

self.long_entry 的价格为当前成交的价格.
然后如果向上突破当前价格+0.5ATR后开始加仓
```
        elif self.pos > 0:
            self.send_buy_orders(self.long_entry)

            sell_price = max(self.long_stop, self.exit_down)
            self.sell(sell_price, abs(self.pos), True)
```
此时的t = self.pos / self.fixed_size 已经是<2: 
 所以调用了
```
self.buy(price + self.atr_value * 0.5, self.fixed_size, True)

```
到这里没有问题，但是如果是第二次加仓后， 
self.long_entry = 第一次加的价格，也就是刚刚开仓的价格entry_up价格 + 0.5个atr了，

所以程序中的，第二加仓，加上一个ATR, 那么第二次加仓的价格是entry_up价格+1.5个ATR了。因为程序用没有记录entry_up的价格作为加仓的基准,而是以成交的价格作为加仓的基准，而成交的价格是最近一次的成交价格。
```
self.buy(price + self.atr_value, self.fixed_size, True)

```

麻烦指正下。谢谢。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by ramoslin02** [comment]
另外self.pos的仓位更新是哪里有更新了，发现程序中没有对该pos仓位进行更新记录。

**Comment by vnpy** [comment]
确实这里的逻辑有所错误，应该使用entry_up和entry_down作为后续加仓的基准价格，同时entry_up和entry_down只有在策略没有持仓时，才进行计算更新，一旦有持仓后则在平仓前保持该基准价格不变。
