### ISSUE TITLE
发单时开平方向没有判断

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1938]
在主界面发单时，如果开平没有选择，（默认有四个选项，但也可以不选）
如果没选方向的话，也可以发单，但一直显示提交中。
能否在接口加上判断？
而数量不选则会提示错误。希望开平方向不选也要提示一下嘛。

**Comment by vnpy** [comment]
好的，后续我们在接口层加上个相关字段的检查

**Comment by vnpy** [comment]
已处理
