### ISSUE TITLE
CTP接口编译细节求助

### ISSUE THREAD

**Issue by YugWu** [vnpy/vnpy#194]
ctp的接口已经使用build.sh编译好了，使用正常，但是今天删除了目录下的vn.ctp目录后，出现了这个错误：
```
  from vnctpmd import MdApi
ImportError: libthostmduserapi.so: cannot open shared object file: No such file or directory
```
查找后发现这个libthostmduserapi.so在之前的vn.ctp目录，所以我的问题是：

这个so文件的引用路径是在哪设置的，我能否将它放在vn.trader/ctpGateway目录下？

**Comment by YugWu** [comment]
好吧，我找到一个方法
编译前vn.ctp目录的绝对路径就是这个.so文件的引用路径，可以把这个目录转移到其他地方，就这样

**Comment by vnpy** [comment]
多谢提供这个经验了～

**Comment by hajaja** [comment]
+1
