### ISSUE TITLE
全局配置建议加上 数据源，如 rqdata还是本地数据库获取

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1941]
全局配置建议加上 数据源，如 rqdata还是本地数据库获取

**Comment by vnpy** [comment]
目前的模式，配置了rqdata.username, rqdata.password，实盘初始化就会优先从RQData获取，数字货币类/IB接口，会优先从接口获取。

获取不到的自动从本地数据库查询。

希望做什么修改呢？

**Comment by viponedream** [comment]
比如像这些。
result = rqdata_client.init()
    def init_rqdata(self):
        """
        Init RQData client.
        """
       先判断一下再载入和初始化
        from vnpy.trader.rqdata import rqdata_client
        result = rqdata_client.init()

可以统统判断一下有没有 rqdata.username, rqdata.password再来导入rqdata_client

**Comment by vnpy** [comment]
rqdata_client.init这个里面有判断了，如果没配置用户密码不会去发起连接，而import本身几乎没什么额外开销。
