### ISSUE TITLE
CTA策略加载的建议

### ISSUE THREAD

**Issue by sixuerain** [vnpy/vnpy#1942]
1.vnpy提供 vnpy_register_strategy(module_name)函数 ，该函数会在.vntrader创建strategy_external.json 
内容如下:
{
  "JQuant_strategy"
} 
2. 用户自己写的模块或者项目通过 from vnpy.app.ctastrategy. engine import vnpy_register_strategy
将自己注册到外部策略列表文件

3. 用户在模块__init__.py提供 
def vnpy_get_strategylist():
    strategy_list = [ JQuant_ma_strategy,JQuant_boll_strategy]
    return strategy_list

4. 在.\vnpy\app\cta_strategy\engine.py的 load_strategy_class函数添加如下 
self.load_strategy_class_from_external()函数

    def load_strategy_class_from_external(self,module_name: str = "" ):
        """
        load strategy class from external module
        """
        try:
            module = importlib.import_module(module_name)
            module_strategy_list = module.vnpy_get_strategylist()
            for value in module_strategy_list:
                if (isinstance(value, type) and issubclass(value, CtaTemplate) and value is not CtaTemplate):
                    self.classes[value.__name__] = value
        except: 
            msg = f"策略文件{module_name}外部加载失败，触发异常：\n{traceback.format_exc()}"
            self.write_log(msg)
---
通过这种 外部注册的方式，可以让用户不需要将策略文件拷贝到.vntrader目录，而是在自己的项目内就能够方便编写策略

**Comment by vnpy** [comment]
在任意目录创建.vntrader目录，并在此目录启动（运行run.py），就会将该目录直接作为VN Trader的运行时目录，并在当前目录寻找strategies目录加载CTA策略文件。
