### ISSUE TITLE
Windows Server 2012上安装报错

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#1943]
## 环境

* 操作系统: 如Windows Server 2012 R2
* Anaconda版本: Python 3.7 64位
* vn.py版本: v2.0.4

## Issue类型
三选一：Bug

## 预期程序行为
我在家里的windows 7 和 windows 10 安装2.0.4均成功
但准备将程序部署到阿里云上时（Windows Server 2012 R2），
install.bat运行到最后一个命令python -m pip install .  ，报出2个错误，图下所示

## 实际程序行为
在Windows Server 2012 R2上安装2.0.4报错，如下图

## 重现步骤
![image](https://user-images.githubusercontent.com/35967505/61591898-9452ad80-abfe-11e9-8248-2b03fc8ec693.png)

**Comment by vnpy** [comment]
请使用VNStudio安装：https://download.vnpy.com/vnstudio-2.0.5.exe
