### ISSUE TITLE
OKEXf 连接每30秒中断重连

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#1945]
## 环境

* 操作系统: Ubuntu 18.04 和mac
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 2.0.3和2.0.5-dev（0720）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

稳定连接

## 实际程序行为

每30秒提示连接中断并自动重连

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="376" alt="屏幕快照 2019-07-21 下午1 08 17" src="https://user-images.githubusercontent.com/10345996/61594337-cd682f00-abb8-11e9-8731-d61890fbf308.png">

本地服务器在美国，阿里服务器在香港，应该不是网络问题。

**Comment by UtorYeung** [comment]
好像是因为okexf的ping间隔是30秒，而vnpy的websocketClient默认是60秒。
py2的版本是要修改去websocketClient的_runPing，把间隔改为30秒ping一次。
py3版本不清楚，不过问题原因应该类似。

**Comment by vnpy** [comment]
> 好像是因为okexf的ping间隔是30秒，而vnpy的websocketClient默认是60秒。
> py2的版本是要修改去websocketClient的_runPing，把间隔改为30秒ping一次。
> py3版本不清楚，不过问题原因应该类似。

2.0版本的WebsocketClient可以直接调整ping_interval了，OKEX使用的都是20秒一次。

**Comment by vnpy** [comment]
https://www.okex.com/docs/zh/#spot_ws-general

> 连接上ws后30s未订阅或订阅后30s内服务器未向用户推送数据，系统会自动断开连接

OKEX官方文档中有提到，必须订阅数据且每30S有数据推送，否则就会被断开连接，所以连上后即时订阅行情就行。
