### ISSUE TITLE
HUOBI 接口掉线重连后，订阅的合约失效，无法使用

### ISSUE THREAD

**Issue by qzm** [vnpy/vnpy#1950]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Anaconda 2019.03 x64
* vn.py版本: 2.0.5
## Issue类型
三选一：Bug

## 预期程序行为
HUOBI 接口掉线重新连接的时候或者手动重新连接时，订阅的合约不失效

## 实际程序行为
HUOBI WebSocket掉线之后，自动发起了重新连接，但是连接之后，订阅的合约失效了，CTA策略里面无法获取实时的信息，界面上订阅的合约也无数据变化

## 重现步骤
可以左上角GATEWAY部分手动重新连接HUOBI接口

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="492" alt="屏幕快照 2019-07-22 下午4 31 44" src="https://user-images.githubusercontent.com/2801450/61617907-3f667400-ac9e-11e9-8002-65ee8da2b51a.png">

**Comment by xldistance** [comment]
就是行情api连接断了，你这也没贴掉线日志啊

**Comment by web2893** [comment]
我也碰到这样的情况

file:///C:/Users/Administrator/Desktop/VNPY开发文档/截图04.png

**Comment by web2893** [comment]
如果有合约持仓，或手动平仓后，退出重连都会报错卡死，本地订阅账户合约持仓错误，与交易所服务器不符合。这一重BUG不解决，很难实现数字货币实盘实战。

**Comment by web2893** [comment]
[
![E679CB05-30D3-4CB3-A587-6BB323DFC504](https://user-images.githubusercontent.com/4566707/62840411-ebfbaa80-bccc-11e9-8328-883c0f43e375.png)
![644F8410-D655-4D99-B8B7-C61FC3C37644](https://user-images.githubusercontent.com/4566707/62840412-ebfbaa80-bccc-11e9-9304-2d240ca23539.png)
![ECC7FF9A-0432-4799-AEAD-557D2D8CA1CC](https://user-images.githubusercontent.com/4566707/62840413-ec944100-bccc-11e9-8feb-1a7a3421ec71.png)


](url)

**Comment by vnpy** [comment]
这是用了我们目前不支持的委托类型，2.0.7升级下对HBDM全部支持

**Comment by web2893** [comment]
谢谢大神们的付出

**Comment by vnpy** [comment]
已修复
