### ISSUE TITLE
rpc gateway 发单send_order bug

### ISSUE THREAD

**Issue by gongnan** [vnpy/vnpy#1951]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 预期程序行为
rpc gateway的send_order函数应返回vt_orderid
## 实际程序行为
但该函数并未返回vt_orderid

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
