### ISSUE TITLE
sendOrder函数如何下单，函数中的订单对象应该如何构造？

### ISSUE THREAD

**Issue by xianba** [vnpy/vnpy#1952]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda2 Python 2.7 32位
* vn.py版本: 1.9.2-LTS

## Issue类型
Question

## 预期程序行为
可以通过通过sendOrder正常下单

## 实际程序行为
    def sendOrder(self, orderReq, gatewayName):
这个函数orderReq在Python中是如何构造的，有没有Demo，谢谢。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy/blob/master/vnpy/trader/object.py

在这里有定义。
