### ISSUE TITLE
[question] about buy and sell on CTA backtest

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1955]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
如下面的代码，这不处理任何“short”和“cover”关闭“short”状态，但我看到“Backtest交易记录”都是“short”任何人告诉我为什么？

```

        if self.pos == 0:

            if self.macd_signal.macd_long and self.rvi_signal.rvi_long:

                print("macd_long : {}" .format(self.macd_signal.macd_long))
                print("rvi_long : {}" .format(self.rvi_signal.rvi_long))



                self.buy(bar.close_price, self.fixed_size)



        if self.sar_signal.sar_value > bar.close_price:

            self.sell(bar.close_price, self.fixed_size)

            print("====> close long")
```
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![kl](https://user-images.githubusercontent.com/9572613/61704556-23ca9e80-ad6e-11e9-9d20-fc121c1d13fb.png)

**Comment by yunnant** [comment]
Direction has two types, long and short, and offset has two types, open and close. Buy means Direction.LONG, Offset.OPEN, sell means Direction.SHORT, Offset.CLOSE.
 
You can check app/cta_strategy/template from line 151 to line 175.

**Comment by vnpy** [comment]
楼上正解。
