### ISSUE TITLE
ubuntu 无法正常build oes

### ISSUE THREAD

**Issue by biggreyhairboy** [vnpy/vnpy#1957]
## 环境

* 操作系统: Ubuntu 18.04，华为云2核4g版本
* Anaconda版本: 通过官方库安装的python3.7.3版本，构建virtual env
* vn.py版本: v2.0.5

## Issue类型
三选一：Bug

## 预期程序行为
无法build 安装成功，build oes接口的时候出现会出现内存溢出的错误（卡住，消耗完服务器的内存和swap空间然后显示安装失败，在本地有8g内存的虚拟机上也出现了同样的结果）
去掉setup.py中关于vnoes的内容之后，可以build 安装成功

我不用oes模块，不过安装过程遇到了这个问题，所以提一下。

**Comment by yunnant** [comment]
可能需要更新requirement，试一下2.0.6，我之前也遇到这个问题，更新了完整版2.0.6没有再出现问题了。

**Comment by vnpy** [comment]
我们在2.0.5升级了autocxxpy编译脚本，导致需要50G内存完成编译，因为我们之前用服务器测试所以没发现，目前2.0.6暂时移除了OES自动编译，2.0.7我们会修复解决这个内存开销太大的问题

**Comment by vnpy** [comment]
已修复
