### ISSUE TITLE
按照vnpy上订单结构构造的订单为什么下不了单？

### ISSUE THREAD

**Issue by xianba** [vnpy/vnpy#1958]
版本：1.9.2-LTS，CTP
代码如下：
```
    orderReq = VtOrderReq()

    orderReq.symbol = 'RB1909'
    orderReq.exchange = 'SHFE'
    orderReq.volume = 1
    orderReq.direction = DIRECTION_LONG
    orderReq.priceType = PRICETYPE_MARKETPRICE

    print("sendOrder", me.sendOrder(orderReq, 'CTP'))
```
返回的结果：
('vtOrderID:', 'CTP.1')
sendOrder CTP.1
但是通过simnow去查询，并没有下单的信息，请问下是什么问题。

**Comment by vnpy** [comment]
上期所，symbol的英文部分是小写的，rb1909

**Comment by xianba** [comment]
symbol改成rb1909下单也一样，simnow也是没有反馈，软件上提示的信息也一样。
![image](https://user-images.githubusercontent.com/11084189/61766002-e6b7e800-ae11-11e9-803b-887801f6a508.png)

**Comment by vnpy** [comment]
你的交易服务器都没登录上去，检查账号密码、还有穿透式验证信息是否配置对了
