### ISSUE TITLE
vnpy通过CTP的方式不能在simnow上下单

### ISSUE THREAD

**Issue by xianba** [vnpy/vnpy#1959]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 2
* vn.py版本: 1.9.2-LTS

## Issue类型
三选一：Bug

## 预期程序行为
用simnow账号，通过CTP可以正常下单

## 实际程序行为
提示CTP接口和行情连接正常，通过simnow快期软件查看没有成功

## 重现步骤

![image](https://user-images.githubusercontent.com/11084189/61768545-5c27b680-ae1a-11e9-843c-577f4754be8c.png)

**Comment by vnpy** [comment]
另一个issue已经回答，请不要重复开。
