### ISSUE TITLE
希望K线图能增加信号线及指标显示

### ISSUE THREAD

**Issue by xcgoo** [vnpy/vnpy#1966]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6

## Issue类型
三选一：Enhancement

## 预期程序行为
希望2.0.6除了能显示回测交易信号外，还能够显示信号线，即开仓和平仓间的连线，同时根据盈利或亏损，信号线能有不同颜色。

**Comment by xcgoo** [comment]
效果可以借鉴Tb和文华里面的信号线

**Comment by hadrianl** [comment]
还有就是加个网格，没网格看起来别扭

**Comment by liuagng** [comment]
还有，鼠标点上去显示十字线， 像股票那样， 可以显示日期，当天的仓位，盈亏等。

**Comment by sdmovie** [comment]
可以用pyechart， 实现这些应该挺方便的

**Comment by vnpy** [comment]
已在社区线上分享中提供了实现方案：https://appszu5scwd6134.h5.xiaoeknow.com/v1/course/alive/l_5e417f0d405c7_1WgLyxPz?type=2&app_id=appSzu5scwd6134&is_redirect=1
