### ISSUE TITLE
下单为stop order时有一定概率会抛出异常

### ISSUE THREAD

**Issue by nov12** [vnpy/vnpy#1969]
## 环境

* 操作系统: 如Windows server 2008
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.5发行版者matser branch 20190726（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
正常下单

## 实际程序行为
有一定概率会出错，大概一两天就会蹦出来，

## 重现步骤
下单全部为stop order。但是暂时不清楚是什么情况下触发。

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![TIM截图20190726002547](https://user-images.githubusercontent.com/10071412/61891335-0ba87a00-af3c-11e9-8947-23bc5a7b3bee.png)

**Comment by vnpy** [comment]
请问你用的什么交易接口呢？

**Comment by nov12** [comment]
> 请问你用的什么交易接口呢？

用的是CTP接口。

**Comment by vnpy** [comment]
这里应该是风控模块或者其他功能，阻拦了该笔委托，导致委托号返回为空字符串，此时update_order_request就会报错，已经添加了额外判断的逻辑。
