### ISSUE TITLE
希望能加入多账号功能

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#1971]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

## 重现步骤

老大，真的很希望在2.0中能利用gateway实例化加入多账号管理交易功能，有这个需求的人感觉也不少，不知道能不能考虑加入到官方计划中，或者能不能提供一个指引或者模板。

**Comment by vnpy** [comment]
目前就能做到，自己改策略接口名字gateway_name就行
