### ISSUE TITLE
数字货币代理连接不对

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1972]
目前的代理连接是这样的：

api/rest/rest_client.py  def init 
        if proxy_host and proxy_port:
            proxy = f"{proxy_host}:{proxy_port}"
            self.proxies = {"http": proxy, "https": proxy}

实际的代理连接有
http
https
socks5
最少应该有这几种吧。在连接的时候加上一个协议判断。

**Comment by viponedream** [comment]
最好先判断一下代理能不能联通

**Comment by vnpy** [comment]
只推荐用shadowsocks代理，目前的代码直接用就行

**Comment by viponedream** [comment]
因为现在用的是 http代理的。
debug到 sebsocket  _http.py  -->  class proxy_info  
里面有一个 self.type ，发现默认就是 http
建议加上  proxy_type

**Comment by viponedream** [comment]
加上了proxy_type 就正常了。

**Comment by xldistance** [comment]
有完整的代码吗

**Comment by viponedream** [comment]
一， 在网关加了proxytype
class BitmexGateway(BaseGateway):
    default_setting = {
        "ID": "",
        "Secret": "",
        "会话数": 3,
        "服务器": ["REAL", "TESTNET"],
        "代理地址": "",
        "代理端口": "",
        "proxy_type": ["HTTP", "SOCKS5"],    # 协议类型
    }

二，connect 时传入
   各种连接时都带入

三，
发现就是 requests 和 websocket需要这个参数
1, class WebsocketClient:
    def _ensure_connection(self):
        """"""
        triggered = False
        with self._ws_lock:
            if self._ws is None:
                self._ws = self._create_connection(
                    self.host,
                    sslopt={"cert_reqs": ssl.CERT_NONE},
                    http_proxy_host=self.proxy_host,
                    http_proxy_port=self.proxy_port,
                    proxy_type=self.proxy_type,           # 加上这个就行。ws自动处理这个参数
                    header=self.header
                )
                triggered = True
        if triggered:
            self.on_connected()



2, api.rest.rest_client.py

class RestClient(object):
    def init(self, url_base: str, proxy_host: str = "", proxy_port: int = 0, proxy_type: str = ""):
        self.url_base = url_base
        if proxy_host and proxy_port:
            proxies = self.proxy_info(proxy_host, proxy_port, proxy_type )
            if proxies is not None:
                self.proxies = proxies



    def proxy_info(self, proxy_host: str, proxy_port: int,  proxy_type: str = "http"):
        """测试代理服务器是否正常运行
            或者干脆不要测试
        """
        allow_type = ['http', 'https', 'socks4', 'socks5', 'socks5h']
        des_type =   ['socks5', 'socks5h']    # 包含3DES协议的https网站

        headers = {
            "Content-Type": "text/html",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
                      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
        }

        if not(proxy_type in allow_type):
            raise ValueError(f"proxy_type must be {allow_type}")

        proxy = f"{proxy_type}://{proxy_host}:{proxy_port}"
        proxies = {"http": proxy, "https": proxy}           # 如果不需测试，这里就可以返回 proxies
        url = "https://www.baidu.com/"
        s = requests.Session()
        if proxy_type in des_type:
            s.mount(url, DESAdapter())

        try:
            r = s.get(
                url,
                headers=headers,
                proxies=proxies,
                timeout=5
            )
            if r.status_code == 200:
                print(f"代理正常 {proxy}")
                return proxies
        except:
            pass

        print(f"代理无法使用  {proxy}")
        return None



# This is the 2.11 Requests cipher string, containing 3DES.
CIPHERS = (
    'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:'
    'DH+HIGH:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+HIGH:RSA+3DES:!aNULL:'
    '!eNULL:!MD5'
)

class DESAdapter(HTTPAdapter):
    """
    A TransportAdapter that re-enables 3DES support in Requests.
    """
    def init_poolmanager(self, *args, **kwargs):
        context = create_urllib3_context(ciphers=CIPHERS)
        kwargs['ssl_context'] = context
        return super(DESAdapter, self).init_poolmanager(*args, **kwargs)

    def proxy_manager_for(self, *args, **kwargs):
        context = create_urllib3_context(ciphers=CIPHERS)
        kwargs['ssl_context'] = context
        return super(DESAdapter, self).proxy_manager_for(*args, **kwargs)

**Comment by viponedream** [comment]
在测试代理时写得不好。
以及代理失败后，要不要接下去运行？

**Comment by vnpy** [comment]
根据目前测试的结果还是SS最稳定，所以目前还是只支持SS了

**Comment by geeknr** [comment]
> 根据目前测试的结果还是SS最稳定，所以目前还是只支持SS了

请教下SS不使用密码连接怎么配置？
