### ISSUE TITLE
v2.0.6编译vnoes失败

### ISSUE THREAD

**Issue by zhanrongdp** [vnpy/vnpy#1974]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Anaconda 19.03 Python 3.7.3 64位
* vn.py版本: v2.0.6（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
机器内存很大，预计编译oes不是问题，于是在setup.py的ext_modules中添加了vnoes

## 实际程序行为
出现如下图错误导致编译失败

## 重现步骤
修改代码如下：
setup.py:121
ext_modules = [vnctptd, vnctpmd] ----> ext_modules = [vnctptd, vnctpmd, vnoes]

在终端中运行：
bash install.sh

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![Screenshot from 2019-07-29 19-21-28](https://user-images.githubusercontent.com/43390786/62045407-d3ed4b00-b237-11e9-821e-aeca38e5e032.png)

**Comment by vnpy** [comment]
目前需要50G内存或者交换区才能完成编译

**Comment by zhanrongdp** [comment]
我有64G内存，100G交换分区，出现了如上其它的问题，希望能帮忙看一下，谢谢。

**Comment by vnpy** [comment]
哦哦，请检查下你的系统版本，Ubuntu > 18.04，GCC > 7

**Comment by zhanrongdp** [comment]
我的系统是Ubuntu 18.04, GCC 8.3
