### ISSUE TITLE
Ubuntu安装完新版的vnpy无法运行

### ISSUE THREAD

**Issue by 15759101796** [vnpy/vnpy#1976]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Python 3.7 64位
* vn.py版本: 如v2.0 master branch 20190729（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
python run.py

## 实际程序行为

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from vnpy.event import EventEngine
  File "/home/yichen/Desktop/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
ImportError: dynamic module does not define module export function (PyInit_eventEngine)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请使用2.0.6版本
