### ISSUE TITLE
How to Get Tick data by ctp

### ISSUE THREAD

**Issue by chasingegg** [vnpy/vnpy#1977]
## 环境

* 操作系统: Ubuntu 18.04
* vn.py版本: v2.0.6

## Issue类型
三选一：Question

现在的文档非常少，如何通过ctp接口获取tick数据，是否能提供一个示例？

**Comment by vnpy** [comment]
请关注微信公众号vnpy-community获取傻瓜式入门教程，预计本周补完

**Comment by chasingegg** [comment]
公众号都是图形界面操作，想通过编程实现的方式来获取tick数据

**Comment by Gwill** [comment]
写个函数监听 EVENT_TICK 时间即可
