### ISSUE TITLE
futu gateway  -- "price" and "pnl" reverted

### ISSUE THREAD

**Issue by sdmovie** [vnpy/vnpy#1983]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

in  futu-gateway.py  --->  query_position

        for ix, row in data.iterrows():
            symbol, exchange = convert_symbol_futu2vt(row["code"])
            pos = PositionData(
                symbol=symbol,
                exchange=exchange,
                direction=Direction.LONG,
                volume=row["qty"],
                frozen=(float(row["qty"]) - float(row["can_sell_qty"])),
                _**### price=float(row["pl_val"]),
                pnl=float(row["cost_price"]),**_
                gateway_name=self.gateway_name,
            )  

price and pnl should be siwtched

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
