### ISSUE TITLE
[question] leverage bitmex

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1989]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
如何将杠杆（x1，x2，x3，..，x100）应用于bitmex保证金交易

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
需要调用额外的函数进行设置（目前没封装），考虑到用vn.py的用户都是为了策略交易，杠杆倍数直接选择了最高。
