### ISSUE TITLE
少了一个交易所 Exchange  CBOE

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1990]
class Exchange(Enum):

primaryExchange = 'CBOE'

======================================
ibgateway
        ib_size = contract.multiplier    #  这个数是str的，
        if not ib_size:
            ib_size = 1
        price = averageCost / ib_size   # ib_size是str的

================================
class Product(Enum):
OPTION = "期权"   #股票期权
还有几种 
 'FOP'      # Futures option 期货期权
 'CFD' = CFD           
'CMDTY'= Commodity

**Comment by viponedream** [comment]
加上K线模式，在回测以及历史数据会用到。
class BarMode(Enum):
    """
    K线模式
    """
    TICK = "TICK"
    BAR = "BAR"

**Comment by viponedream** [comment]
请求历史数据时加上两个：
class HistoricalDataRequest(BaseData):
     autosave: bool = False                  # 是否自动保存
     bar_mode: BarMode = None        # 请求的是BAR还是TICK

**Comment by vnpy** [comment]
已加上CBOE交易所支持，但其他几个更改内容暂时没有支持计划
