### ISSUE TITLE
连接网关

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#1992]
在engine的连接网关是 使用 str
connect(self, setting: dict, gateway_name: str)

但是在其它一些地方gateway用的是 class Exchange(Enum)

建议连接网关时兼容两种写法
gateway='BITMEX'
或者 gateway=Exchange.BITMEX
就是gateway_name可以接受两种类型吧。

应该是在get_gateway加上这个吧
    def get_gateway(self, gateway_name: str):        
        if isinstance(gateway_name, Exchange):
            gateway_name = gateway_name.value

也不对。一个是接口，一个是交易所。
BITMEX 的接口和交易所是一样的，
但如ib则不一样，不知道要怎么处理合理。
==========
应该要重新设计一个类。把交易所跟接口对应起来。
比如说传递 Exchange.BITMEX这个交易所，它就知道要走 BITMEX接口。
传递 SMART就知道要走 IB接口。

================
这样就好了。
Exchange作为一个类。里面只有两个字段。 
gateway : str
exchange

**Comment by vnpy** [comment]
gateway_name一定是字符串，只有exchange字段才会用Exchange类型的enum，两者不要混淆啊
