### ISSUE TITLE
[Question] 如何获得交换费（加密货币）

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1994]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行
当关闭多头或收盘时：我需要调整vol_real = vol  -  vol* exchange.fee
如何获得交换费（加密货币）?

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
交易系统不提供自动获取函数，自己查了作为参数写在策略里吧
