### ISSUE TITLE
最新 vnpy spread position keyError on get_allpositions in CTPgateway/ctptestgateway

### ISSUE THREAD

**Issue by wgd99** [vnpy/vnpy#1997]
vnpy2.06:

ctptest_gateway.py 不能处理spread positions: 有如下报错：

`ctptest_gateway.py(487): OnResQryInvestorPositions KeyError: ('SPC j1909&jm1909,)`

**Comment by vnpy** [comment]
2.0.6已经加上了对CTP价差合约的支持

**Comment by wgd99** [comment]
最新版本2.0.6依然有同样问题。 请看 line 488 in `vnpy\gateway\ctp\ctp_gateway.py(488): onRspQryInvestorPosition`
symbol_exchange_map[data["InstrumentID"]] 有spread pos ID keyerror:
`KeyError: ('SPC b1911&m2001',)`

**Comment by vnpy** [comment]
查了下确实这个SPC持仓，是没有收到合约信息的，加了额外的过滤逻辑来处理

**Comment by wgd99** [comment]
请问(#1997)是改了哪个文件？另外有个broker 给的服务器是SSL， 不是TCP， 但是 CTP_gateway.py里强行都改成TCP，导致连接失败。我传入完整服务器地址 SSL://xxxx, 是在哪里SSL：／／被删掉的？ 多谢。On Sep 19, 2019 11:39 PM, "vn.py" <notifications@github.com> wrote:Closed #1997.

**Comment by vnpy** [comment]
vnpy/gateway/ctp/ctp_gateway.py

改ssl这个有点神奇，现在的版本没支持ssl，是哪家期货呢？

**Comment by wgd99** [comment]
东海。这个哪里改？多谢。On Sep 26, 2019 9:37 PM, "vn.py" <notifications@github.com> wrote:vnpy/gateway/ctp/ctp_gateway.py

改ssl这个有点神奇，现在的版本没支持ssl，是哪家期货呢？

**Comment by vnpy** [comment]
我们在ctp_gateway中来做个修改，下个版本2.0.8会支持

**Comment by vnpy** [comment]
已修复

**Comment by wgd99** [comment]
你好, 能否再问您一个问题，也贴在论坛了，关于yd volume 和今仓还有volume的日内更新：positionData中的 yd_volume 会根据今天新仓位更新吗，还是固定的昨天收盘仓位？我看到说ydPositions是固定的昨天收盘仓位，今天如果有部分平昨，这个值不变，要自己算现在昨仓大小。 请问positionData中的 yd_volume传回来的是什么？如果yd_volume不变，在下面的positionData里，只有volume和yd_volume,没有一个today_volume, 还是没法算现在剩下多少昨仓啊？PositionData(gateway_name='CTP', symbol='cu1912', exchange=<Exchange.SHFE: 'SHFE'>, direction=<Direction.xxxx>, volume=xxxx, frozen=0, price=xxxx, pnl=xxx, yd_volume=xx),因为上期所区分offset.CLOSE 和offset。CLOSETODAY，以上计算看来是难免的了？vnpy封装了自动转换offset.CLOSE到平昨平今没有？多谢。On Sep 28, 2019 9:36 PM, "vn.py" <notifications@github.com> wrote:我们在ctp_gateway中来做个修改，下个版本2.0.8会支持
