### ISSUE TITLE
期货ctp的接入问题

### ISSUE THREAD

**Issue by shenglinqian** [vnpy/vnpy#2]
请问现在是仅仅接入了华宝lts么？是否接入了期货ctp？谢谢

**Comment by chenxy123** [comment]
准备开发CTP接口，不过计划里是先完成教程和策略引擎等的开发，CTP大概在2个月后吧，如果感兴趣的人多我会把它提前。这样把，在这个issue下提出需求的人超过10个我就提前好了，大概1周可以完成。

**Comment by shenglinqian** [comment]
好像目前已经pyctp的项目
https://github.com/lovelylain/pyctp
把他接入你的平台不知道方便不方便

**Comment by chenxy123** [comment]
pyctp是用的cython封装，我的是boost.python，另外设计思路上存在一些区别，另外pyctp的更新不太积极，vn.py这个项目已有的API将会维持跟最新API的同步快速更新（最多比官方的C++ API延迟2周）。

**Comment by shenglinqian** [comment]
了解了，恒生和金证柜台有支持的计划么？

**Comment by chenxy123** [comment]
你是期货公司的员工吗？一般用户不太会这么问哦。就像我前面说的，视乎需求了，如果在issue里提的人多我会进行开发的。如果是小众的API，又不得不用的话我可以提供付费开发的服务。

**Comment by shenglinqian** [comment]
不是。。。我说的恒生和金证是指证券柜台，因为这两个柜台在证券是最常见的两个柜台我才这么问的

**Comment by chenxy123** [comment]
金证有人问我了，恒生也有考虑、但是短期内不会做，他们的API设计很复杂，光搞清楚业务流程就要好长时间，如果有个会用恒生原生C++ API的人合作开发会快点。

**Comment by shenglinqian** [comment]
恩，交易和行情可以分开么？比如行情接宏汇，交易去对接各个经纪商

**Comment by chenxy123** [comment]
可以啊，第一这个东西是全开源的，用户想怎么改都行；第二整个架构设计是模块化的，中间通过事件驱动引擎来整合通信，所以换个组件很方便。宏汇据我所知没有python接口吧，wind到是有。

**Comment by shenglinqian** [comment]
宏汇有c++的接口，做成python的也不算麻烦，wind的数据太慢了

**Comment by chenxy123** [comment]
恩，反正封装方法懂了就都是类似的了。
