### ISSUE TITLE
发送订单的回合编号

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2002]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
我尝试过运行CTA策略:
```
.....
            

            buy_size = round(buy_size, self.precision_amount)
            buy_price = round(buy_price, self.precision_order_price)
           ......
                                       print("{} open long  {}  with price {} ".format(bar.datetime, buy_size,buy_price))
                            self.write_log("{} open long  {}  with price {} ".format(bar.datetime, buy_size,buy_price))
                            self.buy( buy_price, buy_size)


......


```

precision_amount value = 2or 4     
self.precision_order_price value = 8
![Annotation 2019-08-07 071420](https://user-images.githubusercontent.com/9572613/62585451-0c012780-b8e3-11e9-8cfd-6b5d6e29bc93.png)

但是当我看到佣金日志时

![Annotation 2019-08-07 064817](https://user-images.githubusercontent.com/9572613/62585079-51245a00-b8e1-11e9-95c0-bdf76da3f0c2.png)

打印输出：

```
-----08/07/2019, 03:17:00-----------------
 exchange is : Exchange.HUOBI
 symbol is : rsrusdt.HUOBI
last_price: 0.002981 
ask price: 0.002979
bid price : 0.002979 
pos: 0
xxxxxxxxx None
close : 0.002981
2019-08-07 03:16:00 open long  1677.29  with price 0.0029813 
self.order.type : OrderType.LIMIT , value : limmit 
self.order.direction : Direction.LONG , value : Direction.LONG 
self.order.status : Status.SUBMITTING 
self.order.type : OrderType.LIMIT , value : limmit 
self.order.direction : Direction.LONG , value : Direction.LONG 
self.order.status : Status.REJECTED 
-----08/07/2019, 03:18:00-----------------

```
有时订购REJECTED因为buy_size或price_buy的文件格式（如图片）。 怎么解决？

```
CommissionedRequest error, code:order-orderamount-precision-error，information：order amount precision error, scale: `2`
CommissionedRequest error, code:order-orderprice-precision-error，information：order price precision error, scale: `8`
```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这是因为部分数字货币接口json字符串转换精度的问题，我们会在2.0.7中修复

**Comment by cbogithub** [comment]
如何修复：del或注释engine.py中的2行（第778行，第779行）（路径：\ cta_strategy \ engine.py）：

        # price = round_to(price, contract.pricetick)
        # volume = round_to(volume, contract.min_volume)

**Comment by vnpy** [comment]
需要写一个新的round_to函数，采用字符串截取模式来做，而不是float运算

**Comment by vnpy** [comment]
调整了round_to的实现，改为使用Decimal来确保浮点数精度
