### ISSUE TITLE
vnpy的bar.datetime取值问题

### ISSUE THREAD

**Issue by LimingFang** [vnpy/vnpy#2008]
## 环境

* 操作系统: windows 2012 server
* Anaconda版本: python3.7
* vn.py版本: 2.0.6 (dev)

## Issue类型
三选一：Question

## 阐述

vnpy和rqdata交叉的有如下几部分：
1、CTA策略模拟交易盘前初始化:由于策略初始化使用load_bar(n)是使用n个完整的交易日的数据，因此datetime字段是区间起始还是区间末尾都无所谓。
2、策略回测时：
- 回测前的初始化：和模拟交易一样，无影响
- 真正开始交易时：
交易时段用的数据可能是外部csv导入到数据库的数据，也可能是rqdata直接下载到数据库中的数据
  - 前者：csv_loader模块在导入数据时，注释中没有明确规定9:00-9:05的bar的datetime应该是9：05还是9：00，假设vnpy内部统一使用区间前面端点，那么我9：00-9：05的bar.datetime=9:00，那么在策略层可能会有点问题（见后面的话）；；如果我csv文件9:00-9:05的bar.datetime=9:05，那么会与rqdata下载的数据冲突，因为rqdata会在分钟级数据存入数据库时减去一个adjustment，使得datetime为9:00，这两部分数据可能会产生冲突，不一致。
  - 后者：前面提到，如果统一使用时间区间的前面端点作为bar.datetime，由事件驱动框架保证了不可能出现未来的信息，我感觉有可能模糊的地方在于：（以15分钟bar举例）我需要每天在2：00收到最新的bar后（也就是包含了1：45-2：00的信息），利用bar.close去平今。按道理我应该使用2：00-2：15的bar进行撮合，但是实际上当我收到datetime是2：00的bar时，它是2：00-2：15的，因此我相当于在2：15发出我的信号，我对这个有一点点疑问。

**Comment by LimingFang** [comment]
补充提问，就是在BarGenerator里，比如15分钟的bar，10：45-11：00的bar数据的datetime字段会是10：45，也就是上面提到的取datetime区间的开头

**Comment by vnpy** [comment]
Bar的时间戳，本质只是个标识，本身不会影响策略收到数据的顺序，以及T时刻下单，T+1时刻才会撮合的逻辑，不可能导致未来函数。

导入数据时需要确保历史数据的时间戳规则和vn.py一致，否则的话需要做额外的平移调整。
