### ISSUE TITLE
在多账户体系下的考虑以及其他小问题

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2009]
https://github.com/vnpy/vnpy/blob/9608ec0f41102c0e0a64e99ddc08fb966e6de480/vnpy/gateway/ib/ib_gateway.py#L532

1.在多账户体系下面，这里对每个账户调用一次reqAccountUpdates是没有意义的，因为IB的 updatePortfolio和updateAccountValue只会返回最近一次调用reqAccountUpdates的账户的值。需要用reqAccountUpdatesMulti才会有其他账户的信息从accountUpdateMulti里返回。
2.另外，我觉得ibGateway需要有一个主账户的概念，连接时确认登录哪个账户交易，在多账户而且用gateway（TWS忘了是不是也要）作为网关的情况下，ib发出的普通订单都是需要填写具体账号，没有填写账号的订单是会被拒的。
3.还有就是关于类型的问题，合约里面的 multiplier还有tick数据里面返回的tickType等等，我觉得转换类型再判断会比较合适，这个可能是ibapi的问题，反正我用的版本一直tickType都是int，这里的tickType都是str。multiplier是str，这里默认是int？

**Comment by vnpy** [comment]
OK，目前IbGateway没考虑支持多账户的情况，我们后续加上

**Comment by hadrianl** [comment]
另外就是使用ibGateway发stoporder的问题，目前来说是做成local stop order，实际上ib是有server端的stoporder的。而且，现在的local stop order也是不可用的，因为目前ibGateway下的tick既没有limit up and down，也没有ask and bid price 5.这是个bug

**Comment by vnpy** [comment]
多账户功能已经支持，具体请参考：#2232

IB停止单已改为使用服务器停止单
