### ISSUE TITLE
RQData初始化错误

### ISSUE THREAD

**Issue by DavieJobs** [vnpy/vnpy#2012]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.3.1 Python 3.6 64位
* vn.py版本: vnstudio-2.0.6

## Issue类型
三选一：Question

## 预期程序行为
CTA回测中的“下载数据”功能能够正常使用

## 实际程序行为
系统提示“数据下载失败，无法获取IF88.CFFEX的历史数据”，在对照 回测模块文档 时发现是：RQData初始化未成功。
注：在测试源码时，发现是...vnpy\trader\rqdata.py中的rqdata_all_instruments问题，问题提示：RuntimeError: rqdatac is not initialized。
请问该问题怎么解决？？？

**Comment by LimingFang** [comment]
你的rqdata账号没有设置好

**Comment by DavieJobs** [comment]
这里用的rqdata账户是收费版的或者要申请试用的账户吗？

**Comment by LimingFang** [comment]
你没有rqdata使用权怎么可能通过rqdata获取数据，rqdata有一个月的试用期，结束后需要自行购买，数据质量还是很可以的。

**Comment by DavieJobs** [comment]
好的，明白了  感谢~~（不过文档里似乎没有提到rqdata功能要申请试用&收费，一直以为是程序哪安装错了...）

**Comment by vnpy** [comment]
具体使用和申请方法，请看公众号vnpy-community的快速入门教程
