### ISSUE TITLE
关于rpc获取成交信息不同

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#2013]
## 环境

* 操作系统: 如Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/10345996/62711647-696ea480-b9c7-11e9-8551-3f2ca2f6ed27.png)
![image](https://user-images.githubusercontent.com/10345996/62711656-6d022b80-b9c7-11e9-9fdd-b4876e1937a2.png)

上图为rpc接口，下图为普通接口，该问题导致cta策略中pos仓位数据不准确，少记录了部分成交仓位，而委托信息正常。
麻烦帮忙看一下，谢谢。
是同一台机器，rpc缺少了一个成交记录。是在服务器上出现问题之后，我在本地进行测试复现的，分别用原接口和rpc接口连接的结果。服务器确实有断线重启，但本地没有，本地是发现问题后分别点击接口连接后的结果。

**Comment by vnpy** [comment]
该问题无法重现，但估计和之前RPC模块没有做线程安全加锁有关，新版本已经修改
