### ISSUE TITLE
关于火币委托下单类型缺失导致报错

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#2014]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

火币期货有些独有的委托类型，包括 闪电下单，最优5单 等，在vnpy委托类型和接口文件中没有加入，导致获取委托信息时报错。

**Comment by vnpy** [comment]
已修复
