### ISSUE TITLE
关于rpc服务器断线重连

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#2015]
## 环境

* 操作系统: 如Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

rpc服务端断开重启之后，用户端似乎没有任何响应或者重连，cta策略没有运行。希望能加入断线重连机制。

**Comment by vnpy** [comment]
我们看看加上个心跳机制吧

**Comment by vnpy** [comment]
已完成
