### ISSUE TITLE
[Cryptocurrency] False order  

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2018]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
![Screenshot_20190812-111321_AnyDesk](https://user-images.githubusercontent.com/9572613/62845463-67bc1e00-bcf2-11e9-990a-ed1800052944.jpg)

订单成功但vnpy无法退货订单被交易，它仍然在顶峰。 你可以看到基金增加了

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
这是gateway的委托状态没有更新

**Comment by cbogithub** [comment]
![Annotation 2019-08-12 230208](https://user-images.githubusercontent.com/9572613/62879650-cf578500-bd55-11e9-9543-0db77f112b9a.png)
![Annotation 2019-08-12 230435](https://user-images.githubusercontent.com/9572613/62879652-cff01b80-bd55-11e9-98e6-c53ccfa08c17.png)

**Comment by vnpy** [comment]
请看下日志信息，里面是不是网络断了

**Comment by cbogithub** [comment]
没有错误，但订单状态仍在提交
![Annotation 2019-08-12 230435](https://user-images.githubusercontent.com/9572613/62958567-2fffc400-be21-11e9-849c-839b4224e404.png)
![Annotation 2019-08-13 232118](https://user-images.githubusercontent.com/9572613/62958568-30985a80-be21-11e9-8a52-c279a6b3e2bd.png)

**Comment by xldistance** [comment]
下单的委托价格和数量的精度出错，应该在cta_strategy/engine.py里面的send_order函数里面加上：
        #价格和成交量取整的到最小变动
        price = round_to(price,contract.price_tick)
        volume = round_to(volume,contract.min_volume)

**Comment by cbogithub** [comment]
如果我在主窗口上双击一次订单撤销（取消订单），订单无法获取状态。( cta策略不会成功)

**Comment by xldistance** [comment]
数字货币接口有时active_order里面的委托状态一直是提交中也无法撤单，这是订单发出去了，交易所没收到委托请求或者没有返回委托汇报，导致无效订单一直在active_order里面。目前想到的方法是ctaengine里面发单前处理active_order，把order.status是Status.SUBMITTING的委托单删除，但是这样连续发单可能会误伤。
