### ISSUE TITLE
CTP非交易时段无法登陆

### ISSUE THREAD

**Issue by jeffereylj** [vnpy/vnpy#202]
鉴于ctp无法在非交易时段正常登陆，希望能在程序中加入相应的时间管控。

1. 对非交易时段的登陆，系统能够提示。

2.  能支持在交易时段内，自动尝试登陆ctp系统。

**Comment by vnpy** [comment]
1. 这个可以在ctpGateway登录函数connect中加一个时间检查，如果非交易时段，就发送个日志通知“非交易时段”，但是这个可能不是通用需求所以就不做在项目里了
2. ctpGateway是实现了断线重连后自动登录的，但是建议不要太依赖这个功能，CTP的底层接口在多次断开状态下是有可能出现异常导致程序退出的

**Comment by jeffereylj** [comment]
非常感谢 交易员的回复 ！
