### ISSUE TITLE
连接CTP

### ISSUE THREAD

**Issue by zheyangshi** [vnpy/vnpy#2020]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本:  Python 3.7 64位
* vn.py版本: 如v2.06发行版

## Issue类型
Question

## 链接CTP之后
![image](https://user-images.githubusercontent.com/27290494/63002225-ff16a200-bea7-11e9-9b62-39bdc42ab26a.png)
python run.py打开的界面点连接后无显示，也没有反应，是我哪里操作问题吗？客户端启动的话，点击第二次连接就直接闪退，谢谢

**Comment by vnpy** [comment]
需要填写产品名称、授权编码
