### ISSUE TITLE
bitmex ontick和ondepth时间有穿插

### ISSUE THREAD

**Issue by xueshufeng** [vnpy/vnpy#2023]
下面是onDepth和ontick来时的时间。
onTick时间比onDepth慢，怎么处理呢？

onDepth: 07:18:03.063Z
onDepth: 07:18:03.063Z
onTick: 07:18:01.637Z
onTick: 07:18:01.673Z
onDepth: 07:18:03.197Z
onDepth: 07:18:03.202Z
onDepth: 07:18:03.204Z
onDepth: 07:18:03.207Z
onDepth: 07:18:03.210Z
onDepth: 07:18:03.232Z
onDepth: 07:18:03.242Z
onDepth: 07:18:03.244Z
onDepth: 07:18:03.250Z
onDepth: 07:18:03.252Z
onTick: 07:18:01.689Z
onTick: 07:18:01.738Z
onTick: 07:18:01.765Z
onTick: 07:18:01.853Z
onTick: 07:18:01.985Z
onTick: 07:18:02.014Z
onTick: 07:18:02.024Z

**Comment by xueshufeng** [comment]
是不是 把lastprice和深度数据分开上报， 新建一个 ondepth的消息

**Comment by vnpy** [comment]
可以采用分开上报的方案，或者采用不管这个时间戳直接合成的方案

**Comment by xueshufeng** [comment]
深度时间比成交时间 快2秒， 难道bitmex推送过来的成交数据会延迟2秒，那也太可怕了

**Comment by vnpy** [comment]
BitMEX的几条数据流本身是分开的，vn.py本地做了合成，如果网络有问题是可能出现前后到达时间的抖动，要解决还是优先在网络上想办法吧，比如用爱尔兰的AWS
