### ISSUE TITLE
ubuntu执行错误

### ISSUE THREAD

**Issue by WebyGit** [vnpy/vnpy#2027]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6

## Issue类型
三选一：Bug

## 重现步骤

执行python run.py
出现以下错误
<img width="970" alt="image" src="https://user-images.githubusercontent.com/25721961/63139170-e1fce300-c00f-11e9-80cf-c066c9586507.png">

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
MiniGateway并未支持Ubuntu，请在run.py里移除该加载

**Comment by WebyGit** [comment]
> MiniGateway并未支持Ubuntu，请在run.py里移除该加载

解决了，感谢
