### ISSUE TITLE
如何通过vnpy获取标的当前时刻实际成交的信息（交易所的全部成交信息）

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2029]
## Issue类型
三选一：Question

## 咨询

群主，您好，请教个问题
1、通过vnpy，是否可以获得内盘标的当前的时刻交易所的实际成交情况（交易所的全部成交情况），就是有实际成交量以及性质的数据信息，行情软件上是可以看到的，vnpy目前没有，是否能够实现？ctp接口是不是也不提供这个数据？

2、是否有其他方式获得这个当前时刻的实际成交量以及性质的（方向、量）数据？

3、行业内都是如何获取到这种实际成交的数据的？ 大概途径有哪些？ 

谢谢！

截图如下：

![test](https://user-images.githubusercontent.com/31505150/63153070-01136900-c040-11e9-895e-41cb0b8612fe.png)

**Comment by vnpy** [comment]
今开这类信息，是用tick的成交量和持仓量变化，本地计算的，知道算法很容易：
1. 持仓增：开，持仓减：平
2. 成交在上一个Tick卖价：多，反之：空

所以本质这些数据都是种抽象的猜测而已，和市场实际情况可能相去甚远，没多大参考价值。
