### ISSUE TITLE
zmq.error.ZMQError: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by vicjoe** [vnpy/vnpy#2031]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6

## Issue类型
三选一：Bug

## 预期程序行为
启动RPC 服务后，在启动一个RPC client 用于Data Record, 可以正常工作

## 实际程序行为
启动RPC client 后，

    def connect(self, setting: dict):
        """"""
        req_address = setting["主动请求地址"]
        pub_address = setting["推送订阅地址"]

        self.client.subscribe_topic("")
        self.client.start(req_address, pub_address)

        self.write_log("服务器连接成功，开始初始化查询")

        **self.query_all()   这一步出错**

## 重现步骤

![image](https://user-images.githubusercontent.com/31268451/63281616-adbf4600-c2df-11e9-82a7-fa1723b0439c.png)

**Comment by vicjoe** [comment]
有个相关的讨论
https://github.com/hanxiao/bert-as-service/issues/29

**Comment by vnpy** [comment]
DEV分支已修复，添加线程锁保证多线程调用安全
