### ISSUE TITLE
Cta策略在运行时停止工作

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2034]
![20190822_181238](https://user-images.githubusercontent.com/9572613/63510433-c3fc1a80-c508-11e9-8b47-c66f64660501.jpg)

当我运行cta策略时。 一段时间后它停了下来。 即使没有错误
# 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
看不懂你在说什么

**Comment by vnpy** [comment]
可以用英文留言。

It seems that your websocket connection to HUOBI server is broken. Please check if there is any network issue during the period from 19:48 to 20:11. And which version of vn.py are you using?

**Comment by cbogithub** [comment]
我在VPS上运行vnpy . 也许我发现为什么cta_strategy在运行一段时间后停止了：
 1.添加新的cta_strategy后（当另一个cta_strategy正在运行时）
 2.按stop_button然后按start_button restart
 3.按stop_all_button然后按start_all_button

**Comment by cbogithub** [comment]
![Untitled-1](https://user-images.githubusercontent.com/9572613/63644285-d1372600-c70f-11e9-9cae-29d3196ad908.png)
binance still works
while huobi stopped. perhaps we reset huobi websocket after a period of operation

**Comment by vnpy** [comment]
Adding new strategy, stopping and starting all strategies, all these 3 actions won't influence gateway connection. There should be some issue with your network to HUOBI server during that time.

**Comment by cbogithub** [comment]
I found why cta_strategy stop work 
after awhile run : system time was changed ..==> this reason .:)))

**Comment by vnpy** [comment]
OK, thanks for your feedback. I'm closing this issue now.
