### ISSUE TITLE
币安连接一段时间后，RestAPI 连接被关闭，报错ConnectionResetError

### ISSUE THREAD

**Issue by WeiLi1201** [vnpy/vnpy#2035]
## 环境
* Windows 10
* vn.py版本: 2.0.6

## Issue类型
三选一：Bug

## Bug描述
币安gateway连接一段时间后报错ConnectionResetError
错误中 /sapi/v1/userDataStream 是杠杆账户接口,   现货账户接口是/api/v1/userDataStream，接口都能正常使用，现货接口暂没保存到截图。
[币安现货RestAPI](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api_CN.md)
[币安杠杆接口RestAPI](https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md)
多次运行日志见附件log.txt 
[log.txt](https://github.com/vnpy/vnpy/files/3537329/log.txt)

[币安错误代码链接](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors_CN.md)

![error1](https://user-images.githubusercontent.com/16485482/63638967-0405fd80-c6c1-11e9-987c-7e92dd7dc4df.png)
![a](https://user-images.githubusercontent.com/16485482/63638985-3ca5d700-c6c1-11e9-9a45-95904adc5d34.png)

**Comment by vnpy** [comment]
无法重现，查询资料后感觉这里主要的原因是网络连接不稳定导致的（代理问题、网络抖动等），vn.py中没有什么处理办法，请试试用日本的AWS吧，和币安的服务器在一起。
