### ISSUE TITLE
，BITFINEX交易所卖一的五档行情有问题

### ISSUE THREAD

**Issue by wangdalei001** [vnpy/vnpy#2037]
## 环境

* 操作系统: 如Windows 10
*  Python 3.7 64位
* vn.py版本: 2.06

## Issue类型
Bug

bitfinex显示的结果是ask15-ask20的行情，不是ask1-ask5的行情

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![微信图片_20190826161138](https://user-images.githubusercontent.com/54528277/63675909-6f181700-c81c-11e9-8fb6-af10a0206fe1.png)

**Comment by vnpy** [comment]
已修复，非常感谢
