### ISSUE TITLE
策略交易记录入库

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2041]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

希望提供策略的交易记录入库和统计的功能，目前架构下，单账户多策略，对于策略的统计比较麻烦

**Comment by BillyZhangGuoping** [comment]
如果1.92版本可以参考我的方法，
http://blog.itpub.net/22259926/viewspace-2564798/

**Comment by hadrianl** [comment]
谢谢，问题倒是不大，我自己早改了，不过只是觉得官方层面应该有这个功能

**Comment by qmhedging** [comment]
这个收盘的时候自己写mysql即可

**Comment by vnpy** [comment]
和#1877重复，后续将会添加
