### ISSUE TITLE
代码兼容这种格式比较方便

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2043]
![2222](https://user-images.githubusercontent.com/16624529/63790569-1fc10c00-c92c-11e9-9799-e7315c32618b.png)

象这样就容易上手了。
纯数字的就以conId来看待。
否则就以symbol或localsymbol来处理。

代码分三部分，跟上交易所，共四部分，就可以组成一份合约了。
试过股票，期货，期权，指数都可以订阅行情数据。
港股是纯数字的就只能conId了。

**Comment by vnpy** [comment]
有道理，这个思路到也不错，确实纯数字太麻烦了，港股为啥不能采用这个模式呢？

**Comment by hadrianl** [comment]
在交易这里使用conId的思路我觉得完全没有问题的，能保证了交易合约的唯一性，而且对整接口的contract的统一是有帮助的。我觉得倒是这个合约查询这里有比较大的优化空间，通过一两个字段来查询出相关的合约的功能可以考虑下纳入需求

**Comment by viponedream** [comment]
我是这样处理的：
代码里面分三部分  
symbol.secType.currency
1,如果secType 属于["FUT", 'OPT', 'FOP']，则前面的symbol为localSymbol
2,如果第三部分没有，则默认为usd
3,如果第二部分没有，则以交易所来默认指定到底是哪个类型
    SMART -> STK
    CBOE  -> OPT
    GLOBEL -> FUT
    IDEALPRO -> CASH

例子：
-------------------------------------
股票
交易所：SMART 代码： QQQ ( 或QQQ.STK 或 QQQ.STK.USD )   
-------------
股票期权
交易所：SMART 代码：QQQ   190920P00185000.OPT.USD      中间三个空格
交易所：CBOE    代码：QQQ   190920P00185000  只有一位的通过交易所判断类型
                                       FB    190920P00200000.OPT       中间四个空格 
---------------------------------------
期货：
交易所：GLOBEX 代码： ESZ9.FUT.USD ( 或ESZ9.FUT 或 ESZ9 )   完整的代码为三部分
通过类型判断第一位为localSymbol, 不然需要太多参数
----------------------------------------
期货期权：
交易所：GLOBEX 代码： NQU9 P7600.FOP   localSymbol 中间一个空格
----------------------------------------------
外汇：
交易所： IDEALPRO  代码： EUR.USD (或EUR)
-----------------------------------------
指数： 
交易所CBOE   代码： SPX.IND.USD           标普500指数
----------------------------------------
指数期权：
交易所CBOE或SMART
SPX   190920P02900000.OPT  标普500指数的期权   中间三个空格（localSymbol中间多少个空格都有的）


======================================
港股的代码本来就是数字的，而我默认把数字都当作conId看待了。
所以港股的只能使用conId了。（或者再想一下其它办法避免冲突）

**Comment by vnpy** [comment]
这么看规则有点太复杂了，不如ConId来得简洁

**Comment by hadrianl** [comment]
其实现在主要的问题应该是用conId来交易是很懵逼的一个事情，因为目前界面上没有其他额外的信息，所以经常要自己单独查询合约的信息。如果加个简便的方法能获取到原始的标的信息（例如界面上的代码行加个hoverEvent显示原始标的信息）应该能解决这需求

**Comment by viponedream** [comment]
用 symbol 或 localSymbol吧。

**Comment by viponedream** [comment]
其实也不复杂。
localSymbol.secType.currency
或者纯数字 conId

**Comment by vnpy** [comment]
已完成修改，改用合约信息细节的方式来替代conId
