### ISSUE TITLE
Bitfinex行情断线

### ISSUE THREAD

**Issue by wangdalei001** [vnpy/vnpy#2045]
## 环境

* 操作系统: Windows 7
* Anaconda版本:  Python 3.7 64位
* vn.py版本: 如v2.06

## Issue类型
三选一：Enhancement

## 预期程序行为
行情正常连接

## 实际程序行为
连接交易所之后，3小时到24小时内，行情随机断，在本地代码框输入BTCUSD回车就又有行情了

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
在交易日志界面没有报错，在cmd报错如下：
![报错](https://user-images.githubusercontent.com/54528277/63823974-21202200-c988-11e9-9fb6-0eb1ba10f638.png)

**Comment by vnpy** [comment]
关于这个问题：
1. Bitfinex的WS API没有断开，因此不是网络连接问题
2. 搜了下Google有许多人遇到同样问题，但没有解决方案
3. 查看Bitfinex文档，也没有定时断开或者心跳断开的机制
4. 因此索性加了个每隔1分钟自动重新订阅所有已订阅行情的函数
