### ISSUE TITLE
在jupyter notebook连接CTP时候遇到的问题

### ISSUE THREAD

**Issue by zheyangshi** [vnpy/vnpy#2047]
## 环境

* 操作系统: Windows 10
* Anaconda版本:  Python 3.7 64位
* vn.py版本: 最新版

## Issue类型
Question

## 预期程序行为
jupyter notebook中连接CTP后应该提示行情连接成功，可是我这里没有提示
![image](https://user-images.githubusercontent.com/27290494/63827868-410b1200-c997-11e9-8c09-b182346c839e.png)
预期返回的结果应该如下：
![image](https://user-images.githubusercontent.com/27290494/63827884-4a947a00-c997-11e9-9d90-a8f9c0b6b03e.png)

## 实际程序行为
我自己运行时交易提示链接成功，但是没有提示合约连接成功
![image](https://user-images.githubusercontent.com/27290494/63827849-3486b980-c997-11e9-9137-255ac587c46f.png)
以及返回的结果也是不全的：
![image](https://user-images.githubusercontent.com/27290494/63828011-ae1ea780-c997-11e9-9ae4-e8396c975761.png)

**Comment by vnpy** [comment]
行情服务器没连上，应该是连接数满了，换一个试试

**Comment by zheyangshi** [comment]
![image](https://user-images.githubusercontent.com/27290494/64096711-ed346a80-cd94-11e9-93a3-a94c2b59b1e0.png)
你好~请问在连接成功情况下为什么get_tick（）返回的是None？

**Comment by vnpy** [comment]
先调用subscribe订阅行情，等几秒行情过来后，再get_tick

**Comment by zheyangshi** [comment]
好的，谢谢！
