### ISSUE TITLE
No module named "vnpy.api.mini.vnminimd"

### ISSUE THREAD

**Issue by ShawnWuzh** [vnpy/vnpy#2049]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6发行版

## Issue类型
三选一：Question

## 预期程序行为
python run.py 不能正常运行

## 实际程序行为
ModuleNotFoundError: No module named "vnpy.api.mini.vnminimd"

**Comment by ShawnWuzh** [comment]
我貌似发现原因了，是因为Ubuntu不支持mini api吗？我把run.py的api换成ctp之后就可以用了。不知道是不是因为这个原因

**Comment by vnpy** [comment]
是的，ubuntu不支持CTP mini
