### ISSUE TITLE
期权界面（为 白糖和豆粉期权做准备）

### ISSUE THREAD

**Issue by jeffereylj** [vnpy/vnpy#205]
希望交易员能够为期权界面立项， 为 17年就要推出的白糖和豆粉期权做准备啊 ！

**Comment by vnpy** [comment]
期权这个东西比较麻烦，我自己在公司里负责的就是期权交易，所以直接来写相关的功能会有潜在的合规问题......

**Comment by jeffereylj** [comment]
这个就比较麻烦了。是否可以提出一个框架，交给社区开发。你就做项目经理，复查可否？

**Comment by vnpy** [comment]
可能也不太方便，目前看只能社区做开发，弄完我合并进去
