### ISSUE TITLE
数字货币交易市场api接口有问题

### ISSUE THREAD

**Issue by LynnXtreme** [vnpy/vnpy#2050]
## 环境

操作系统: 如Windows 10

* vn.py版本: v2.0发行版
## Issue类型
Bug

## BUG行为
交易成功，testnet.bitmex.com，已经成单了，vnpy显示延迟，延迟了很久很久（起码十分钟）

**Comment by vnpy** [comment]
请检查网络环境，翻墙是否稳定，或者用海外服务器
