### ISSUE TITLE
能不能把注释写成中文啊

### ISSUE THREAD

**Issue by eyelivermore** [vnpy/vnpy#2051]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
能不能在后央的版本中把注释写成中文啊,英文不好 看改来比较累,谢谢

**Comment by vnpy** [comment]
2.0后的注释都会保持英文模式，为了后续进入海外市场
