### ISSUE TITLE
send_local_stop_order（BUG）

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2052]
https://github.com/vnpy/vnpy/blob/eedea7708bb82db1eee774a31414095e4067df5c/vnpy/app/cta_strategy/engine.py#L426

在contract.stop_supported为true或false的两种情况下，返回的orderid类型不一致，true调用的是send_server_stop_order返回是个list， false调用的是send_local_stop_order返回的是str单个orderid

**Comment by vnpy** [comment]
dev分支已经修复了
