### ISSUE TITLE
datetime 带上时区兼容各地

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2053]
1， 现在的datetime是没有时区的，建议带上时区，然后存库的时候转为utc
只要有时区各种转换就方便了。 postsql是可以支持时区的。
2，下载回测时使用的是日期 20190829 00:00:00  改为20190829 23:59:59 会不会更好？

**Comment by viponedream** [comment]
全球化就肯定要考虑时区问题，晚考虑不如早考虑。

**Comment by vnpy** [comment]
确实，这个还是挺重要的

**Comment by guo9310** [comment]
支持，现在保存时间到MongoDB的时候，没有时区默认就用UTC，就差了8个小时。

**Comment by lostleaf** [comment]
对的，OKEX 和 OKEXF 就有差了8个小时这个问题

**Comment by xldistance** [comment]
自己在gateway里面统一一下东八区就可以了

**Comment by vnpy** [comment]
已在dev-datetime分支中开发
