### ISSUE TITLE
把plot加进layout的处理放在add_item里面

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2055]
https://github.com/vnpy/vnpy/blob/eedea7708bb82db1eee774a31414095e4067df5c/vnpy/chart/widget.py#L125

这里没明白为什么把plot加进layout放在add_item里面？不应该是在add_plot里面吗？

**Comment by vnpy** [comment]
请看下pyqtgraph的官方文档吧

**Comment by hadrianl** [comment]
不是，我说的是这里其实应该是个bug。。。。。如果多个plot的情况下使用add_item，会导致新加item的plot直接给移动到最底下

**Comment by vnpy** [comment]
没太明白，能否提供个出错的代码？

**Comment by hadrianl** [comment]
https://github.com/hadrianl/vnpy/blob/455a2bea0a605239d4e2dc9b60aa31abe500e66f/vnpy/chart/widget.py#L129
我fork的版本已经改了一下了，把add_item最后两句放到add_plot最后面

**Comment by vnpy** [comment]
明白了，已经修改，非常感谢！！
