### ISSUE TITLE
CTA回测模块界面显示问题

### ISSUE THREAD

**Issue by wuzuhong** [vnpy/vnpy#2058]
## 环境

* 操作系统: Windows 10
* python版本: Python 3.7 64位
* vn.py版本: v2.0.6发行版

## 重现步骤
![image](https://user-images.githubusercontent.com/22707118/64059001-e9161a80-cbe5-11e9-84a2-d1f18aa9ff2f.png)

**Comment by vnpy** [comment]
请使用1920x1080的分辨率

**Comment by dehim** [comment]
程序右键，属性，兼容性，更改所有用户的设置，更改高的DP设置：
程序DPI：钩选“使用此设置修复此程序的缩放问题....”
执行以下操作时...：选择“打开此程序”
高级DPI缩放替代：勾选“替代高DPI绽放行为”
缩放执行：选择“系统”
