### ISSUE TITLE
第三方接口(飞鼠 等)在linux环境下的编译

### ISSUE THREAD

**Issue by tangyouze** [vnpy/vnpy#206]
像飞鼠这样的接口
我看了代码似乎只支持用visual studio编译

https://github.com/vnpy/vnpy/tree/master/vn.sgit

是否支持在linux编译呢? 如果不支持的话大概要如何修改. 我改完之后可以提交一个PR

**Comment by vnpy** [comment]
可以的，参考vn.ctp下面的Linux编译方法，然后写一个cmakelists
