### ISSUE TITLE
这里只有日期，没有时间

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2060]
比如说我今年下午才打开策略。要下载分钟K.

系统给的的时间是 20190902 00:00:00  。 那么上午的 10， 11点的分钟K就没有下载到了吧？
把默认的时间改为  20190902 23:23:59 会不会更好？

![QQ图片20190902041359](https://user-images.githubusercontent.com/16624529/64081778-1e328200-cd38-11e9-87d6-aa02a73eefbb.png)

**Comment by vnpy** [comment]
已修改，非常感谢
