### ISSUE TITLE
策略目录复制到另的地方就调不出来 vnpy.app.cta_strategy

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2063]
如果我把这个策略目录 cta_strategy 复制到新的地方，则调不出来。之前是可以的。
run.py这样的：
from vnpy.app.cta_strategy import CtaStrategyApp                      #这样就可以调用
from vnpy_other.app.cta_strategy import CtaStrategyApp           # 这样就调不到策略了
然后运行在ui界面下。策略就调不到。
============================
建议  策略文件存放位置：
1，cta_strategy目录下， 指import CtaStrategyApp 的这个目录。而不是默认的  vnpy.app.cta_strategy， 因为我们会把整个 cta_strategy 目录复制到别的地方修改，防止一更新全覆盖掉了。
2，设置文件 cta_strategy_setting.json 里面可以指定多个目录。
3，最后才是官方的，

如果重名则以上面的顺序为准。

**Comment by vnpy** [comment]
如果自行对App做了定制修改，请将整个App代码都放在你自己的目录下，然后在run.py中加载修改后的App即可
