### ISSUE TITLE
策略文件加载失败

### ISSUE THREAD

**Issue by caimmy** [vnpy/vnpy#2070]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
Question

## 预期程序行为
编写一个策略文件，能从策略下拉中看到这个策略
代码复制的vn.py教程中DemoStrategy

`from vnpy.app.cta_strategy import CtaTemplate

class DemoStrategy(CtaTemplate):
    """演示用的简单双均线"""
​
    # 策略作者
    author = "Smart Trader"
​
    # 定义参数
    fast_window = 10
    slow_window = 20
​
    # 定义变量
    fast_ma0 = 0.0
    fast_ma1 = 0.0
    slow_ma0 = 0.0
    slow_ma1 = 0.0
​
    # 添加参数和变量名到对应的列表
    parameters = ["fast_window", "slow_window"]
    variables = ["fast_ma0", "fast_ma1", "slow_ma0", "slow_ma1"]
​
    def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        """"""
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)
​
        # K线合成器：从Tick合成分钟K线用
        self.bg = BarGenerator(self.on_bar)
​
        # 时间序列容器：计算技术指标用
        #self.am = ArrayManager()
        pass
​
    def on_init(self):
        """
        当策略被初始化时调用该函数。
        """
        # 输出个日志信息，下同
        self.write_log("策略初始化")
​
        # 加载10天的历史数据用于初始化回放
        self.load_bar(10)
​
    def on_start(self):
        """
        当策略被启动时调用该函数。
        """
        self.write_log("策略启动")
​
        # 通知图形界面更新（策略最新状态）
        # 不调用该函数则界面不会变化
        self.put_event()
​
    def on_stop(self):
        """
        当策略被停止时调用该函数。
        """
        self.write_log("策略停止")
​
        self.put_event()
​
    def on_tick(self, tick: TickData):
        """
        通过该函数收到Tick推送。
        """
        self.bg.update_tick(tick)
​
    def on_bar(self, bar: BarData):
        """
        通过该函数收到新的1分钟K线推送。
        """
        am = self.am
​
        # 更新K线到时间序列容器中
        am.update_bar(bar)
​
        # 若缓存的K线数量尚不够计算技术指标，则直接返回
        if not am.inited:
            return
​
        # 计算快速均线
        fast_ma = am.sma(self.fast_window, array=True)
        self.fast_ma0 = fast_ma[-1]     # T时刻数值
        self.fast_ma1 = fast_ma[-2]     # T-1时刻数值
​
        # 计算慢速均线
        slow_ma = am.sma(self.slow_window, array=True)
        self.slow_ma0 = slow_ma[-1]
        self.slow_ma1 = slow_ma[-2]
​
        # 判断是否金叉
        cross_over = (self.fast_ma0 > self.slow_ma0 and
                      self.fast_ma1 < self.slow_ma1)
​
        # 判断是否死叉
        cross_below = (self.fast_ma0 < self.slow_ma0 and
                       self.fast_ma1 > self.slow_ma1)
​
        # 如果发生了金叉
        if cross_over:
            # 为了保证成交，在K线收盘价上加5发出限价单
            price = bar.close_price + 5
​
            # 当前无仓位，则直接开多
            if self.pos == 0:
                self.buy(price, 1)
            # 当前持有空头仓位，则先平空，再开多
            elif self.pos < 0:
                self.cover(price, 1)
                self.buy(price, 1)
​
        # 如果发生了死叉
        elif cross_below:
            price = bar.close_price - 5
​
            # 当前无仓位，则直接开空
            if self.pos == 0:
                self.short(price, 1)
            # 当前持有空头仓位，则先平多，再开空
            elif self.pos > 0:
                self.sell(price, 1)
                self.short(price, 1)
​
        self.put_event()
​
    def on_order(self, order: OrderData):
        """
        通过该函数收到委托状态更新推送。
        """
        pass
​
    def on_trade(self, trade: TradeData):
        """
        通过该函数收到成交推送。
        """
        # 成交后策略逻辑仓位发生变化，需要通知界面更新。
        self.put_event()
​
    def on_stop_order(self, stop_order: StopOrder):
        """
        通过该函数收到本地停止单推送。
        """
        pass`

## 实际程序行为
策略文件strategies.demo_strategy加载失败，触发异常：
Traceback (most recent call last):
  File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 760, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "D:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\vnpy_models\strategies\demo_strategy.py", line 11
    ​
    ^
SyntaxError: invalid character in identifier

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
不要直接复制微信文章里的代码，请手敲（否则起不到学习效果），否则会有Python代码的对齐问题，导致报错
