### ISSUE TITLE
openorders与orderstatus回报的BUG

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2073]
https://github.com/vnpy/vnpy/blob/32639a1ed732c884ae35f28a099a62a8989e6860/vnpy/gateway/ib/ib_gateway.py#L358

在极少数情况下，没有openorders回报但是存在orderstatus回报，这里的order没有对为None时做处理

**Comment by vnpy** [comment]
请问具体为何会出现这种情况呢？

openorders是全部活动状态委托的回报，应该包含了所有信息？

**Comment by hadrianl** [comment]
具体的目前没有办法复现了， 前几天香港交易所衍生品的交易出现异常的时候，发生过这样的情况

**Comment by vnpy** [comment]
这么看应该是比较少见的数据流混乱问题了，这种情况在软件层很难全部过滤
