### ISSUE TITLE
IB历史数据下载的问题

### ISSUE THREAD

**Issue by liujuncn** [vnpy/vnpy#2074]
## 环境

* 操作系统: Ubuntu 18.10
* Python 3.6.8 with virtual env 
* vn.py版本: 2.0.6

## Issue类型
Question

## 预期程序行为
运行cta_backtester，期望能按代码逻辑下载完整历史数据到sqlite数据库。
        # If history data provided in gateway, then query
        if contract and contract.history_data:
            data = self.main_engine.query_history(req, contract.gateway_name)

in ib_gateway:
        days = min(delta.days, 180)     # IB only provides 6-month data

## 实际程序行为
只下载了43条记录

![image](https://user-images.githubusercontent.com/902005/64482593-3ec27680-d227-11e9-997d-a41e2651fb63.png)

**Comment by liujuncn** [comment]
补充：
IB文档里写的限制是
Historical data requests that use a bar size below 30 seconds can only go back six months.
因此1分钟bar数据可能不止6个月。

**Comment by viponedream** [comment]
肯定不止6个月吧。
只是每次请求数据要隔好几秒。
数据可能好几年都有。
