### ISSUE TITLE
增强IB gateway连接的健壮性

### ISSUE THREAD

**Issue by liujuncn** [vnpy/vnpy#2076]
## 环境

操作系统: Ubuntu 18.10
Python 3.6.8 with virtual env
vn.py版本: 2.0.6

## Issue类型
Enhancement

## 预期程序行为
希望API客户端和TWS之间发生错误导致连接disconnect后，可以自动(无人值守情况)或手动重连。

## 重现步骤
 例如错误输入合约代码，回车发起订阅请求后，返回错误会disconnect和TWS的连接。但是此后重新使用“连接IB”并不能恢复连接。

![image](https://user-images.githubusercontent.com/902005/64508844-039c7200-d311-11e9-8ddc-1b910b8e7aee.png)

**Comment by liujuncn** [comment]
IbClient的run()断开连接，退出线程。

而mainwindow的main engine只初始化一次gateway，而IbClient的connect()只在gateway初始化时调用。

**Comment by liujuncn** [comment]
是否将IBClient线程 Thread(target=self.client.run)改为放到IbApi或IbGateway的connect、close中进行初始化和终止更好？

@vnpy

**Comment by vnpy** [comment]
`
class IbClient(EClient):
    """"""

    def run(self):
        """
        Reimplement the original run message loop of eclient.

        Remove all unnecessary try...catch... and allow exceptions to interrupt loop.
        """
        while not self.done and self.isConnected():
            try:
                text = self.msg_queue.get(block=True, timeout=0.2)

                if len(text) > MAX_MSG_LEN:
                    errorMsg = "%s:%d:%s" % (BAD_LENGTH.msg(), len(text), text)
                    self.wrapper.error(
                        NO_VALID_ID, BAD_LENGTH.code(), errorMsg
                    )
                    self.disconnect()
                    break

                fields = comm.read_fields(text)
                self.decoder.interpret(fields)
            except Empty:
                pass
`

ib_gateway.py文件中唯一做了异常捕捉的是上述代码，只是过滤了队列为空的情形正常返回，没有对ConnectionResetError的处理，如果确实在IB官方API内部进行了捕获，那么可能不适合在vn.py中进行处理（或者可以自己尝试修改IB API的代码）。
