### ISSUE TITLE
运行vn_trader可视化时，EnumCell的content报AttributeError

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#2079]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
使用simnow运行vn_trader可视化，运行时因EnumCell的content数据类型错误，报错。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1.报错截图如下：
![QQ图片20190910092250](https://user-images.githubusercontent.com/35967505/64576782-a6ee9500-d3ac-11e9-9c2a-87e17b0c3937.png)

2.在widget.py——set_content里添加try...except调试
![QQ图片20190910092759](https://user-images.githubusercontent.com/35967505/64576939-5c214d00-d3ad-11e9-9b23-e4262be42ec7.png)

3.打印结果如下：
![QQ图片20190910092420](https://user-images.githubusercontent.com/35967505/64576818-d30a1600-d3ac-11e9-9835-69b853640544.png)

**Comment by vnpy** [comment]
请问用的什么接口，这个应该是接口层传上来的数据类型不对

**Comment by unlimitnight0** [comment]
就是CTP， 连的SIMNOW

**Comment by vnpy** [comment]
你用的版本有点老了，升级到最新的VNStudio-2.0.6吧，这是个之前代码里的BUG

**Comment by unlimitnight0** [comment]
我用的2.0.2，改了挺多东西的，可否告知问题在哪个文件？

**Comment by vnpy** [comment]
在vnpy/gateway/ctp/ctp_gateway.py中
