### ISSUE TITLE
30分钟的分钟线，对有10：15到10：29休息的品种，在10：30的时候生成不了

### ISSUE THREAD

**Issue by maxsonic** [vnpy/vnpy#2084]
## 环境

LTS版本和2.0

## Issue类型
Bug

## 预期程序行为
可以生成10:30的30分钟线

## 实际程序行为
无法生成

## 重现步骤

LTS版本和2.0的判断逻辑都是

`if not (bar.datetime.minute + 1) % self.window:`

从15分到30分休息的时候，就没有29分了，那么在10：29的时候就不生成10:00-10:29的30分钟bar了。

**Comment by vnpy** [comment]
自己在on_tick函数中，判断tick时间戳，如果跨越了10:30分，就调用策略内BarGenerator对象的generate函数来强制合成
