### ISSUE TITLE
运行CTA策略，通过RQData获取历史数据时，报异常

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2089]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.6

## Issue类型
Bug

## 预期程序行为
rqdata_client.query_history应该正确获取数据。

## 实际程序行为
运行到rqdata_client.query_history这个函数的时候，报出异常：
Not permit to get minbar price
![image](https://user-images.githubusercontent.com/8924839/64955264-5e5a3e80-d8ba-11e9-8377-1118ab83aaa3.png)

## 重现步骤

开始以为是rqdata的问题，然后在调试过程中，发现不使用vnpy，直接调用rqdata的get_price函数可以正常获取数据。
![image](https://user-images.githubusercontent.com/8924839/64955639-5949bf00-d8bb-11e9-80c5-752b2167d768.png)
![image](https://user-images.githubusercontent.com/8924839/64955650-61096380-d8bb-11e9-8a22-3a4abe97d8dc.png)

单独调用rqdata的运行结果
![image](https://user-images.githubusercontent.com/8924839/64955291-703be180-d8ba-11e9-8d6c-22a3bc0ad86d.png)

于是查看rqdata的源代码，发现报异常，是因为rqdata在通过get_price函数调用get_minbar函数时，产生异常，用traceback_print_exc()查找异常原因，发现是超过最大连接数量rqdatac.share.errors.PermissionDenied: login session num reached MAX limit。
![image](https://user-images.githubusercontent.com/8924839/64955404-bbee8b00-d8ba-11e9-90be-41c618b30ef3.png)

不知道为什么，直接调用rqdata是不会超过最大连接量，但是通过vnpy的话就会出现这个异常。

**Comment by vnpy** [comment]
请问是否开了多个VN Trader？如果配置了RQData账号，那么每个VN Trader都会发起一个连接，默认情况下RQData的账号只能同一时间只能登录一个的

**Comment by tmaczjj** [comment]
同出现这样的问题。只开了一个VN Trader，在调取1M数据时不报连接量错误，但是使用天数据时就报最大连接量错误了。另外我也是单独使用RQData能查询，通过vnpy调用就报权限错误。

**Comment by linbozhong** [comment]
> 请问是否开了多个VN Trader？如果配置了RQData账号，那么每个VN Trader都会发起一个连接，默认情况下RQData的账号只能同一时间只能登录一个的

没有多开。开vntrader再运行测试脚本，脚本就会报错超过连接数量，这个我知道。
我用两台电脑测试都是这样。
我发现社区也有一些人报了这个问题。建议和rqdata的开发人员联系一下，看看他们中秋期间是否有做过什么变动。因为中秋节之前是运行正常的。

**Comment by vnpy** [comment]
联系了米筐，他们后端升级对账户的多线程调用做了限制，已经在着手解决。
