### ISSUE TITLE
做x-min或小时线级别的通道策略，新的交易日回放到最后一根历史bar的时候应该发出停止单

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2092]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.6

## Issue类型
三选一：Enhancement

## 预期程序行为
在做x-min或者小时线级别的通道策略的时候，在新的交易日开盘前启动策略就应该根据历史数据最后一根bar的信息，发出本地停止单，开盘后就可以立即进入等待撮合的状态。

现在策略模板的逻辑是在on_init函数用load_bar载入历史数据，在这个过程中用on_bar或on_x_bar回放数据，如果trading为false，cta_engine就不会发单，因为要先完成初始化才能启动策略，此时策略trading状态肯定是false，历史的数据全部回放完成也不会发出停止单，只有开盘后，等到bar_generator合成完第一根所需要的bar并推送到on_bar函数才能实现发单。
如果是1分钟的策略相对还好，最多就是等待一分钟。但是如果是5分钟以上的策略，这个等待就太久了，对于一些通道突破策略的入场或者是已有仓位的止损，都是需要在开盘就立即发出停止单，如果有需要，立即就进行交易。

虽然可以自己更改一下cta_engine的代码或者在策略中保存好最后一根bar的停止单数据然后启动策略后发单，不过还是有点麻烦，毕竟策略文件最好是仅写与策略相关的代码，而cta_engine用户最好是不用去改动，否则以后升级又要重新处理一下。
感觉这应该是一个比较常用的功能，最好是能在引擎层里面直接实现了。

**Comment by linbozhong** [comment]
这里提供一个临时解决方案，是通过保存最后一根bar的发单参数，在策略启动的时候发单出去。

1、在__init__新增一个变量用来保存最新的bar的stop_order参数列表
`self.last_stop_order_params_list = []`

2、在策略文件中重写template的send_order，主要是当trading为False的时候，保存最新bar的停止单参数。
`    def send_order(
        self,
        direction: Direction,
        offset: Offset,
        price: float,
        volume: float,
        stop: bool = False,
        lock: bool = False
    ):
        """
        Send a new order.
        """
        if self.trading:
            vt_orderids = self.cta_engine.send_order(
                self, direction, offset, price, volume, stop, lock
            )
            return vt_orderids
        else:
            params = (direction, offset, price, volume, stop, lock)
            self.last_stop_order_params_list.append(params)
            return []`

3、在on_x_min函数运行前，清空上一根bar保存的停止单参数
`    def on_hour_bar(self, bar: BarData):
        self.last_stop_order_params_list.clear()
`

4、新建一个策略启动后把最后一根bar的停止单发出去的函数，发单完成后清空停止单参数列表
`    def send_pre_trading_order(self):
        """
        Send a pre trading saved stop order after start strategy.
        """
        print(self.trading)
        l = self.last_stop_order_params_list
        if self.trading and l:
            for params in l:
                self.send_order(*params)
        l.clear()`

5、本来第四步的发单函数是可以放在on_start的，但是因为现在cta_engine在启动策略的时候是先调用了on_start函数再把trading状态改成True，所以如果我们把发单函数放在on_start的话，是无法触发发单行为的。这里有两个办法：
（1）修改cta_engine，把代码顺序改一下（没有充分测试，不确定有什么后果）
（2）把发单函数放在on_tick，这样第一根tick过来了就发单了。

特别声明：以上方案只经过简单测试，仅提供思路为主，如果出现什么bug也很正常。请大家自行调试。

**Comment by handsomehu** [comment]
也可以用小时线出信号，1分钟线发单。开盘价格波动剧烈，马上发单容易中招。

**Comment by vnpy** [comment]
楼上两种方案都能解决该问题。

我们提供另一种思路：
1. 策略每次on_bar/on_hour_bar产生信号后，记录信号到缓存变量中
2. 增加一个开盘发单的布尔值控制变量，每天重置
3. 在策略的on_tick函数中，检查当前的tick时间，超过9:30（开盘时间），且控制变量为True，则立即发出开盘委托（基于之前缓存的信号），并将控制变量设为False
