### ISSUE TITLE
cta_engine的start_strategy方法，应该先改变strategy的trading状态，再调用策略的on_start回调函数

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2095]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.6

## Issue类型
三选一：Question

## 重现步骤

我们知道回调函数一般是某件事情做完了，再来调用回调函数。
所以，我认为cta_engine的start_strategy应该是把策略的trading状态设置为True之后，再来调用策略的on_start函数。类似于我们连接ctp，连接上了才会调用on_connected。
而目前代码是先调用on_start之后才把trading设置为True，等于事情都还没做呢就调用策略的回调函数了。
用户期望在策略启动的时候做什么事情的时候，可能会把代码写入on_start函数里面，但是此时trading的状态仍然False，所以不是用户预期要触发的行为。

这是一个bug？还是我忽略考虑了什么东西？
![image](https://user-images.githubusercontent.com/8924839/65086981-76c77780-d9e6-11e9-8fd9-8ea511a29b01.png)

**Comment by vnpy** [comment]
on_start是启动过程的一部分，执行完后，才是正式启动完毕，此时on_start才应该变为True。
