### ISSUE TITLE
tickType类型BUG！

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2099]
https://github.com/vnpy/vnpy/blob/ad9676f242efbc2cf0eec770cfe18d4ee55b6c76/vnpy/gateway/ib/ib_gateway.py#L323

这里的tickType是int（反正最新的ibapi是int，老版本的ibapi不太确定）

**Comment by liujuncn** [comment]
use TickTypeEnum is better:

        if tickType != TickTypeEnum.LAST_TIMESTAMP:
            return

**Comment by vnpy** [comment]
已修复，非常感谢
