### ISSUE TITLE
请问：vn.trader\vtMain.py，要添加合约，是通过UI还是通过代码？

### ISSUE THREAD

**Issue by dotcream** [vnpy/vnpy#21]
vn.trader\vtMain.py，要添加合约，是通过UI还是通过代码？

**Comment by ideaplat** [comment]
通过代码`[
  {
    "name": "double ema",
    "className": "DoubleEmaDemo",
    "vtSymbol": "rb1606"
  },
  {
    "name": "DataRecorder",
    "className": "DataRecorder",
    "vtSymbol": "rb1606"
  }
]`
