### ISSUE TITLE
IB Gateway的openorder的订单价格考虑

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2100]
https://github.com/vnpy/vnpy/blob/ad9676f242efbc2cf0eec770cfe18d4ee55b6c76/vnpy/gateway/ib/ib_gateway.py#L395

ibGateway在支持server端的stoporder之后，这里的price是一个值得斟酌的点。ibapi下stop market order的时候，openorder回调的order的lmtPrice一般是下单时候的现价，触发价在auxPrice。
这里引申出来的一个点就是vnpy的OrderData是否需要新增一个触发价的概念，一旦涉及到停止单或触发单这种条件订单的话，没有触发价的话信息是有遗漏的

**Comment by vnpy** [comment]
已修改，非常感谢
