### ISSUE TITLE
EVENT_CONTRACT与subscribe存在循环调用

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2101]
https://github.com/vnpy/vnpy/blob/ad9676f242efbc2cf0eec770cfe18d4ee55b6c76/vnpy/app/spread_trading/engine.py#L202

例如ibGateway的subscribe同时会调用reqContractDetails，触发一次EVENT_CONTRACT。不知道其他Gateway是否存在这种情况。
而ib的reqContractDetails会同时把相关的tick再推送一次，这问题就导致1秒的tick数据可能有上万条，最终就是整个UI崩溃。

**Comment by vnpy** [comment]
非常感谢，我们来加个过滤

**Comment by vnpy** [comment]
已在dev分支修复
