### ISSUE TITLE
系统生成了不存在的套利合约

### ISSUE THREAD

**Issue by chdl21cn** [vnpy/vnpy#2110]
## 环境

* 操作系统: Windows 7
* Python版本: VNStudio-2.0.7
* vn.py版本: VNStudio-2.0.7

## Issue类型
三选一：Question

## 预期程序行为
策略运行中应无错误提示

## 实际程序行为
每隔3-5秒，在python控制台上就显示一次错误，提示找不到合约SP c1911&c2005：
![捕获1](https://user-images.githubusercontent.com/40117507/65563325-ce805880-df7b-11e9-8f93-91ec45220164.PNG)
对应vnpy的代码是：
![代码](https://user-images.githubusercontent.com/40117507/65563369-eeb01780-df7b-11e9-95bb-9277888650b2.PNG)
虽然提示错误，但是暂不影响策略运行。
## 重现步骤
我同时在做SP c1911&c2001 和SP c2001&c2005的两组套利。
当两组套利都有持仓时，vnpy自己会组合出一个SP c1911&c2005合约，并进行持仓查询。但这个合约在交易所是不存在的。因此查询返回时，本地的symbol_exchange_map字典里没有这个合约代码，提示错误。
我没找生成这个套利合约名称的代码在哪，现在觉得应该是在TdApi中。

同时持有SP c1911&c2001 和SP c2001&c2005这两组套利组合同方向的持仓，在下个交易日开始就会出现这个错误。

**Comment by vnpy** [comment]
已经在DEV分支修复，持仓是CTP自动生成的，vn.py定时查询持仓时获取到该合约就会出错，加个过滤就行了
