### ISSUE TITLE
TickData只能支持5档数据，无法支持L2 10档挂单数据

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#2113]
## 环境
* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6

## Issue类型
Enhancement

## 预期程序行为
利用oes接口查询L2行情数据，发现虽然传入的数据有10档挂单数据，但是TickData只能支持5档数据只能读取

## 实际程序行为
如下下代码，在vnpy/vnpy/gateway/oes/oes_md.py；发现如果档位大于5，都会取5。一开始以为写错，发现是因为TickData只有5档，不然会报错。
BTW，实盘这里的BidPriceLevel不是提供的行情档位数，而是此刻存在多少档价格挂挡，可能有60-70档挂单在后面，最好改为len(data.BidLevels). 

    def on_l2_tick(self, d: MdsMktRspMsgBodyT):
        """"""
        data: MdsL2StockSnapshotBodyT = d.mktDataSnapshot.l2Stock
        symbol = str(data.SecurityID)
        tick = self._get_last_tick(symbol)
        tick.open_price = data.OpenPx / 10000
        tick.pre_close = data.ClosePx / 10000
        tick.high_price = data.HighPx / 10000
        tick.low_price = data.LowPx / 10000

        for i in range(min(data.BidPriceLevel, 5)):
            tick.__dict__['bid_price_' + str(i + 1)] = data.BidLevels[i].Price / 10000
        for i in range(min(data.OfferPriceLevel, 5)):
            tick.__dict__['ask_price_' + str(i + 1)] = data.OfferLevels[i].Price / 10000
        self.gateway.on_tick(copy(tick))

## 重现步骤
修改建议，修改dataclass TickData为10档。

**Comment by vnpy** [comment]
因为绝大部分策略其实用不到10档数据，同时绝大部分接口也只提供5档数据，因此这里在框架中还是只支持5档，有需要的可以自行修改支持更多档位
