### ISSUE TITLE
成功更新到2.0.7版本，IB连接成功输入conid回车，没反应，无法订阅行情。

### ISSUE THREAD

**Issue by nwalesL** [vnpy/vnpy#2115]
升级之前，行情订阅正常。升级后就没反应了，求助。

**Comment by vnpy** [comment]
具体用的哪个CoinID？

**Comment by nwalesL** [comment]
SPY：756733 \ SMART

**Comment by vnpy** [comment]
用DEMO环境尝试订阅，提示没有该行情权限，需要付费订阅，这个是正常的情况，请检查下是不是行情到期后没有续费吧。
