### ISSUE TITLE
关于arraymanager的建议

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2116]
https://github.com/vnpy/vnpy/blob/222475fdf97f77f60cec4ecee231f1b85f44df21/vnpy/trader/utility.py#L285

具体实践中，觉得np.zeros(size)不太好，np.full(size, np.nan, dtype=np.float64)会更合理一点，talib本身能处理nan的问题，但是如果是0值的话，其实会导致前面指标数据失真。另外，datetime_array也应该是需要的

**Comment by vnpy** [comment]
ArrayManager的inited属性字段，就是用于控制只有将array全部填满时才进行后续的技术指标计算，所有策略Demo中也都加上了对该字段状态的检查
