### ISSUE TITLE
CTPJ接口在替换海通的api后无法显示行情，交易功能正常

### ISSUE THREAD

**Issue by liuyunjr** [vnpy/vnpy#2117]
## 环境

* 操作系统: Windows 10
* Python版本: 如VNStudio-2.0.7
* vn.py版本: 如v2.0.7

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重

现步骤以及报错截图

行情和交易显示连接成功，合约也可以查询，但是不能显示行情。
![Uploading [L@$2`X0}8T4GX78}ZLBU0U4.png…]()](url)

**Comment by vnpy** [comment]
看不到图片，请检查行情地址是否设置正确了
