### ISSUE TITLE
海通期货的仿真接口连接后不显示行情

### ISSUE THREAD

**Issue by liuyunjr** [vnpy/vnpy#2119]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.7
* vn.py版本: 2.0.7
## Issue类型

三选一：Question

## 重现步骤

下载了vnpy2.0.7的源码，用的是海通期货的CTP仿真接口。直接按照海通给的APPID和授权码登录CTPTEST接口报错4097。之后海通提供了CTP接口文件，直接用它替换掉源码中的api/ctp文件下的文件，提示行情和交易服务器以及合约信息查询均成功，但查询合约却不出现行情。

昨天由于图片没有上传成功，今天把海通提供的api接口文件和替换接口后的情况截图上传上来。

![微信图片_20190927142121](https://user-images.githubusercontent.com/55833428/65746740-2e206480-e132-11e9-9317-a7d7223a0269.png)

[v6.3.16_T1_20190508_api_win.zip](https://github.com/vnpy/vnpy/files/3661127/v6.3.16_T1_20190508_api_win.zip)

**Comment by vnpy** [comment]
6.3.16是实盘版本，请尝试直接用CTP接口连接看看，另外部分仿真环境可能有行情缺失的问题（期货公司为了节省流量只提供部分行情）
