### ISSUE TITLE
为什么CTP tick数据中的lastVolume都为0？

### ISSUE THREAD

**Issue by lipan0722** [vnpy/vnpy#2120]
## 环境

* 操作系统: 如Windows 10
* Python版本: 2.7
* vn.py版本: 1.9.2

## Issue类型
三选一：Question

## 预期程序行为
期望在CTP策略的onTick中获取到当前的成交量lastVolume

## 实际程序行为
tick 中的lastVolume都为0

## 重现步骤

在onTick中printtick数据

为什么CTP tick数据中的lastVolume都为0？simnow的问题还是需要自己计算？谢谢

**Comment by vnpy** [comment]
因为CTP没有这个字段，大部分交易系统都没有，而是只有volume字段，即全天成交量。

last_volume目前主要就是IB家有

**Comment by lipan0722** [comment]
非常感谢，那就只有使用两个tick之间的volume差异来用了。
