### ISSUE TITLE
1.9 與 2.x algo_trading 裡面的twap_algo的差異

### ISSUE THREAD

**Issue by ypochien** [vnpy/vnpy#2121]
## 环境

* 操作系统: Windows 10
* Python版本: conda 3.7.3
* vn.py版本: v2.0.7 master

## Issue类型
三选一：Enhancement

## 预期程序行为
根據wiki - [算法交易模块：CSV载入方法](https://github.com/vnpy/vnpy/wiki/算法交易模块：CSV载入方法) twap_algo的說明
有一個minVolume欄位，

但是2.0版本的twap_algo沒有實作這個部分，1.9.2才有，這部分會有同步的更新嗎?

因為不精準計算委託的(數量)與(總時間/間隔時間)會導致委託數量為小數的狀態...

**Comment by vnpy** [comment]
2.0版本的算法模块，下单时可以基于合约数据ContractData的min_volume来自动取整，无需用户再手动输入了
