### ISSUE TITLE
XTP的行情订阅接口不成功，返回-1错误

### ISSUE THREAD

**Issue by yum2016** [vnpy/vnpy#2125]
## 环境

* 操作系统: 如Windows 2016 Server
* Python版本: 如3.7.3
* vn.py版本: 如v2.0.7dev branch 20190921（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
XTP行情及交易服务器都正常登陆后订阅股票行情能够正常返回

## 实际程序行为
XTP行情及交易服务器都正常登陆后订阅股票行情不成功，返回-1错误

## 重现步骤

************************ register_event_trade only_hangqing_mode=False
2019-09-30 11:17:32,074  INFO: 8888888888888888888 开始连接接口：XTP
2019-09-30 11:17:32,241  INFO: 行情接口初始化成功
2019-09-30 11:17:32,309  INFO: 交易接口初始化成功
***subscribe_at_first_login****000*** gateway_name=XTP
self.settingFileName=D:\qlzn_data\DR_setting\XTP\DR_setting.json
req.symbol=000001 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SZ
XTP 000001 行情订阅失败。 ret=-1
req.symbol=000768 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SZ
XTP 000768 行情订阅失败。 ret=-1
req.symbol=600030 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SH
XTP 600030 行情订阅失败。 ret=-1
req.symbol=600357 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SH
XTP 600357 行情订阅失败。 ret=-1
2019-09-30 11:17:32,424  INFO: 行情服务器登录成功
2019-09-30 11:17:32,516  INFO: 交易服务器登录成功
2019-09-30 11:17:32,743  INFO: SSE合约信息查询成功
2019-09-30 11:17:32,864  INFO: SZSE合约信息查询成功

vnpy的XTP接口订阅调用如下：
self.api.SubscribeMarketData([req.symbol], xtp_exchange)

XTP的结口处是如下要求：
			///订阅行情，包括股票、指数和期权。
			///@return 订阅接口调用是否成功，“0”表示接口调用成功，非“0”表示接口调用出错
			///@param ticker 合约ID数组，注意合约代码必须以'\0'结尾，不包含空格 
			///@param count 要订阅/退订行情的合约个数
			///@param exchange_id 交易所代码
			///@remark 可以一次性订阅同一证券交易所的多个合约，无论用户因为何种问题需要重新登录行情服务器，都需要重新订阅行情
			virtual int SubscribeMarketData(char *ticker[], int count, XTP_EXCHANGE_TYPE exchange_id) = 0;

参数不一致。

请看看到底是哪里出了问题？

**Comment by yum2016** [comment]
seep(2)后再订阅，虽然报订阅成功，但还是有错：
2019-09-30 13:47:57,967  INFO: 订阅行情发生错误, 代码：11200003，信息：unknown security


日志如下：
req.symbol=000001 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SZ
XTP 000001 行情订阅成功。
req.symbol=000768 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SZ
XTP 000768 行情订阅成功。
req.symbol=600030 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SH
XTP 600030 行情订阅成功。
req.symbol=600357 xtp_exchange=XTP_EXCHANGE_TYPE.XTP_EXCHANGE_SH
XTP 600357 行情订阅成功。
2019-09-30 13:47:57,967  INFO: 订阅行情发生错误, 代码：11200003，信息：unknown security
发生内部错误：

**Comment by vnpy** [comment]
1. 你的订阅操作，在收到合约查询回报之前，所以系统找不到该合约信息，导致订阅失败
2. 11200003这个是什么股票的代码？unknown security就是填入错误代码的报错
