### ISSUE TITLE
algo_trading 運行中，新增 algo，容易出現 runtime error.

### ISSUE THREAD

**Issue by ypochien** [vnpy/vnpy#2126]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如Anaconda python 3.7.4
* vn.py版本: vnpy:latest(2019/10/03)

## Issue类型
三选一：Bug

## 预期程序行为
可持續新增alog進行交易

## 实际程序行为
當有algo進行運行，此時再新增algo容易發生
`RuntimeError: dictionary changed size during iteration`
## 重现步骤
密集新增algo就會發生

![image](https://user-images.githubusercontent.com/625016/66138035-91c5f880-e630-11e9-9f60-2add24859bca.png)

##預期修復

由於 list(dict) 為複製行為，故迴圈中就不會怕dict的異動

![image](https://user-images.githubusercontent.com/625016/66138103-abffd680-e630-11e9-986b-c0c4cb2604a3.png)

**Comment by vnpy** [comment]
已修复，非常感谢
