### ISSUE TITLE
sqlite表结构设计不合理

### ISSUE THREAD

**Issue by ujfjhz** [vnpy/vnpy#2127]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
按symbol分表。

## 实际程序行为
所有数据都在dbbardata和dbtickdata里面，在数据量增长后会存在读写的性能问题，而且不便于数据的维护。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by ujfjhz** [comment]
sqlite是非常强大的数据库，不能因为它简单就小看了它，库表结构设计好了比其他数据库都强。

**Comment by vnpy** [comment]
担心性能方面的请使用MySQL、MongoDB等数据库，SQLite只是为了方便使用的默认数据库。
