### ISSUE TITLE
更新spread trading模块后启动失败

### ISSUE THREAD

**Issue by nikitazhhy** [vnpy/vnpy#2129]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.6
* vn.py版本:  VNStudio-2.0.6自带版本

## Issue类型
三选一：Bug

## 预期程序行为
更新价差套利模板后启动报错

## 重现步骤
报错如图，请问如何修改？

<img width="271" alt="微信图片_20191007110432" src="https://user-images.githubusercontent.com/27732676/66282633-a46f5480-e8f2-11e9-96c7-5a8e2edc0392.png">
studio安装在c:\vnstudio,无中文字符的文件夹下

**Comment by vnpy** [comment]
请问是如何更新的？每个新版本更新分两步，第一步更新VN Station自身，第二步更新vn.py框架的代码，就是在VN Station界面上的【更新】按钮需要点两次

**Comment by nikitazhhy** [comment]
> 请问是如何更新的？每个新版本更新分两步，第一步更新VN Station自身，第二步更新vn.py框架的代码，就是在VN Station界面上的【更新】按钮需要点两次

我只点了一次更新按钮，点完两次可以运行了，多谢！
