### ISSUE TITLE
ubuntu搭建运行没有ctp等接口，且日志报错少库

### ISSUE THREAD

**Issue by Wilson-G** [vnpy/vnpy#213]
报错如下
![2017-01-24 12 05 40](https://cloud.githubusercontent.com/assets/12825462/22212263/f3ae5c76-e1ca-11e6-86bd-d624ac2e08f1.png)
能帮忙看下是怎么回事么，用的是releases里面的1.4版本

**Comment by vnpy** [comment]
1. 需要自己编译ctp/lts/ib的API，编译好后把.so文件复制到对应的gateway目录下
2. 其他的ksotp, xtp等接口在Linux下尚不支持

**Comment by Wilson-G** [comment]
多谢
