### ISSUE TITLE
vnpy v2 在 MacOS 的安装

### ISSUE THREAD

**Issue by xareelee** [vnpy/vnpy#2132]
## 环境

* 操作系统: mac
* Python版本: 3.7.3
* vn.py版本: v2.0.7 (commit 1257f9a6)

## Issue类型: Question

wiki 內的 MacOS 教学是 python 2.7 的，而 vnpy v2 是 python 3.7，想问一下能否更新该文档。以及能否简单口述哪些部分有需要调整。

https://github.com/vnpy/vnpy/wiki/MacOS安装

**Comment by vnpy** [comment]
请查看这篇教程：https://mp.weixin.qq.com/s?__biz=MzI1MTQ2Njc5OQ==&mid=2247483986&idx=1&sn=dde6ebf5d6499473d6954c53a3cde95a&chksm=e9f3c712de844e0460a771cbfeb227e130135341f4c0ba5783d3d66c967940348033f5201886&scene=21#wechat_redirect
