### ISSUE TITLE
Mac上如何安装vnpy

### ISSUE THREAD

**Issue by geeeeeeeek** [vnpy/vnpy#2133]
Mac上如何安装vnpy？ 未来会支持mac系统吗

**Comment by vnpy** [comment]
请参考这篇[文章](https://mp.weixin.qq.com/s?__biz=MzI1MTQ2Njc5OQ==&mid=2247483986&idx=1&sn=dde6ebf5d6499473d6954c53a3cde95a&chksm=e9f3c712de844e0460a771cbfeb227e130135341f4c0ba5783d3d66c967940348033f5201886&scene=0&xtrack=1&key=12bc6edc783b7cb0c1b0ff4ce7763aa3c8b2368ee2c7644e6f11d7aaef0ae705ca1a5639c70a710e09d5ea53ee2e69e88a0240071bc52e68e1758f4f1392bebc1b72ad5182648b5b73f7256c8459fa16&ascene=1&uin=ODY3MDY3NzQx&devicetype=Windows+10&version=62070141&lang=zh_CN&pass_ticket=k3pmgmDBLoPzKZOAjjTRM58DY6PrHhsLiGNKXe1lQwe7U3bUcxwpJocqV%2BBKIDcI)
