### ISSUE TITLE
binance和bitmex交易所没法获取到实时的orderbook数据

### ISSUE THREAD

**Issue by ramoslin02** [vnpy/vnpy#2138]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.7发行版

## Issue类型
三选一：Bug
binance和bitmex交易所没有获取到实时的orderbooK的数据，币安websocket订阅的数据depth5就不存在。所以没法获取，bitmex订阅的oderbook10推送的频率太低，价格跟实时的价格偏差很大。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
币安接口测试有正常的5档行情
