### ISSUE TITLE
vnpy 运行不了

### ISSUE THREAD

**Issue by cnjeff** [vnpy/vnpy#214]
File "D:\vnpy\vn.trader\eventEngine.py", line 10, in <module>
    from PyQt4.QtCore import QTimer
ImportError: No module named PyQt4.QtCore

因为无法找到 Anaconda2-4.0.0, 安装的Anaconda2-4.2.0，里边只有 PyQt5

**Comment by cnjeff** [comment]
found Anaconda2-4.0.0 in the end.

**Comment by cathero2001** [comment]
可以在这里找之前的版本。4.2.0（包括4.2.0）之后，都只有PyQt5.
https://repo.continuum.io/archive/.winzip/

32位 x86 Python 2.7 Anaconda-4.1.1
https://repo.continuum.io/archive/.winzip/Anaconda2-4.1.1-Windows-x86.zip


Thanks,
2017-02-02 

cathero2001 



发件人：Jeff <notifications@github.com>
发送时间：2017-01-28 16:31
主题：[vnpy/vnpy] vnpy 运行不了 (#214)
收件人："vnpy/vnpy"<vnpy@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

File "D:\vnpy\vn.trader\eventEngine.py", line 10, in 
from PyQt4.QtCore import QTimer
ImportError: No module named PyQt4.QtCore
因为无法找到 Anaconda2-4.0.0, 安装的Anaconda2-4.2.0，里边只有 PyQt5
