### ISSUE TITLE
spreadtrading模块有bug

### ISSUE THREAD

**Issue by dear-catchlove** [vnpy/vnpy#2140]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
![捕获](https://user-images.githubusercontent.com/56247897/66969346-c1a6de80-f0bb-11e9-8441-18f73036e8ef.PNG)

- [ ] 

## 预期程序行为
上面画圈的地方，只有在启动algo的时候，才推送algo给spreadstrategytemplate。

正确的做法应该是每当algoengine，active状态变化都要推送给策略。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by dear-catchlove** [comment]
@vnpy 麻烦看一下是否存在这个问题。只有启动策略，才把algo推送给策略，如果algoengine，状态发生变化，策略是收不到algo状态变化的

**Comment by dear-catchlove** [comment]
@vnpy 我认为应该在下图四个地方判断algo.is_active，如果False就应该把algo推送出去
![lx](https://user-images.githubusercontent.com/56247897/66969701-34fd2000-f0bd-11e9-9ffe-3aef5ca16c6f.PNG)

**Comment by vnpy** [comment]
在SpreadAlgoTemplatey以及开发的SpreadTakerAlgo中，有对应的调用put_event推送算法状态变化事件的函数，并不是只有创建算法时才会推送。
