### ISSUE TITLE
vnpy2交易下单程序不能下单成功

### ISSUE THREAD

**Issue by xianba** [vnpy/vnpy#2141]
## 环境
Windows 10、Python3.7、vnpy2.0.6

## Issue类型
Bug

## 预期程序行为
正常下单交易

## 实际程序行为
![image](https://user-images.githubusercontent.com/11084189/66985027-82de4c00-f0ee-11e9-9b6c-0a3d6bc9e5a8.png)

## 重现步骤
1.通过main_engine引擎调用下单程序
ordReq = OrderRequest(symbol="rb2001", exchange=Exchange.SHFE, direction=Direction.LONG, type=OrderType.MARKET,
volume=1, price=0, offset=Offset.NONE)
main_engine.send_order(ordReq, "CTP")

![image](https://user-images.githubusercontent.com/11084189/66985122-b4571780-f0ee-11e9-8dad-b98b33499f06.png)

**Comment by vnpy** [comment]
SIMNOW环境和上期所都不支持市价单，换限价单吧，另外offset是必填的

**Comment by xianba** [comment]
请问下如何才能下市价单？

**Comment by vnpy** [comment]
实盘环境除上期所以外都可以
