### ISSUE TITLE
vnpy-2.0.7 配置mongodb数据库，记录ticker数据的时候报错

### ISSUE THREAD

**Issue by kuskyfei** [vnpy/vnpy#2144]
## 环境

* 操作系统: macOS 10.14.6
* Python版本: 3.7.4
* vn.py版本:2.07

## Issue类型
bug
## 重现步骤
 配置mongodb数据库，记录ticker数据的时候报错

报错信息如下：
Exception in thread Thread-167:
Traceback (most recent call last):
File "/Users/kuskyfei/venv/vnpy37/lib/python3.7/site-packages/mongoengine/queryset/transform.py", line 236, in update
fields = _doc_cls._lookup_field(parts)
File "/Users/kuskyfei/venv/vnpy37/lib/python3.7/site-packages/mongoengine/base/document.py", line 1032, in _lookup_field
raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "date"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/kuskyfei/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/Users/kuskyfei/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, self._kwargs)
File "/Users/kuskyfei/Downloads/vnpy-2.0.7/vnpy/app/data_recorder/engine.py", line 69, in run
database_manager.save_tick_data([data])
File "/Users/kuskyfei/Downloads/vnpy-2.0.7/vnpy/trader/database/database_mongo.py", line 322, in save_tick_data
).update_one(upsert=True, updates)
File "/Users/kuskyfei/venv/vnpy37/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 593, in update_one
update)
File "/Users/kuskyfei/venv/vnpy37/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 517, in update
update = transform.update(queryset._document, update)
File "/Users/kuskyfei/venv/vnpy37/lib/python3.7/site-packages/mongoengine/queryset/transform.py", line 238, in update
raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "date"

一点点跟了断点进去，发现在 vnpy/app/data_recorder/engine.py中 65行（ task_type, data = task），如下：

def run(self):
""""""
while self.active:
try:
task = self.queue.get(timeout=1)
task_type, data = task

            if task_type == "tick":
                database_manager.save_tick_data([data])
            elif task_type == "bar":
                database_manager.save_bar_data([data])

        except Empty:
            continue

data的属性字段中有个date和time，在进行mongo存储的时候报错~~~

进一步打印信息，在文件中database_mongo.py断点跟进，并且打印了信息，代码如下在313行：
for d in datas:
updates = self.to_update_param(d)
updates.pop("setgateway_name")
updates.pop("setvt_symbol")
print(updates)
(
DbTickData.objects(
symbol=d.symbol, exchange=d.exchange.value, datetime=d.datetime
).update_one(upsert=True, **updates)
)

我打印了updates，信息如下：
{'setsymbol': 'LTCUSD', 'setexchange': 'BITFINEX', 'setdatetime': datetime.datetime(2019, 10, 17, 16, 55, 49, 206792), 'setname': 'LTCUSD', 'setvolume': 58245.03932339, 'setopen_interest': 0, 'setlast_price': 53.494, 'setlast_volume': 0, 'setlimit_up': 0, 'setlimit_down': 0, 'setopen_price': 54.99, 'sethigh_price': 55.152, 'setlow_price': 51.269, 'setpre_close': 0, 'setbid_price_1': 53.465, 'setbid_price_2': 53.462, 'setbid_price_3': 53.461, 'setbid_price_4': 53.449, 'setbid_price_5': 53.422, 'setask_price_1': 53.48, 'setask_price_2': 53.49, 'setask_price_3': 53.492, 'setask_price_4': 53.499, 'setask_price_5': 53.5, 'setbid_volume_1': 60.0, 'setbid_volume_2': 15.0, 'setbid_volume_3': 60.0, 'setbid_volume_4': 3.73893048, 'setbid_volume_5': 320.18926899, 'setask_volume_1': 10.0, 'setask_volume_2': 37.75928193, 'setask_volume_3': 60.0, 'setask_volume_4': 1.87971876, 'setask_volume_5': 0.00060068, 'setdate': '20191017', 'settime': '16:55:49.206792'}

报错是在
DbTickData.objects(
symbol=d.symbol, exchange=d.exchange.value, datetime=d.datetime
).update_one(upsert=True, **updates)

update_one的时候，进行字段查询的时候，无法转换date': '20191017'

**Comment by vnpy** [comment]
检查了database_mongo.py文件，其中的DbTickData对象，并无date和time字段，请检查是否自行做了什么修改导致的上述BUG。

**Comment by kuskyfei** [comment]
我尝试了2.0.7的版本，在mac和windows环境下，记录实时记录ticker模块，配置mongodb，确实都不正常，现在您这边换mongodb数据库是能正常记录ticker信息么。DataRecorderApp 模块，

**Comment by kuskyfei** [comment]
> 检查了database_mongo.py文件，其中的DbTickData对象，并无date和time字段，请检查是否自行做了什么修改导致的上述BUG。

2.0.7，行情记录，DataRecorderApp 模块，在用mongodb的时候，能正确记录k线数据么

**Comment by kuskyfei** [comment]
> 检查了database_mongo.py文件，其中的DbTickData对象，并无date和time字段，请检查是否自行做了什么修改导致的上述BUG。

没有做任何更改，本地mongodb版本4.0.13，行情记录，报错

**Comment by sam201904** [comment]
问题解决了吗？我也碰到类似问题，但我的是connot resovle field“open”

**Comment by vnpy** [comment]
我们官方做了测试，v2.0.9版本下的DataRecorder，IB和ByBit接口的行情录制均无问题，请升级到2.0.9后再试试吧
