### ISSUE TITLE
CTP多进程高频下单后，onTrade响应混乱问题

### ISSUE THREAD

**Issue by lipan0722** [vnpy/vnpy#2148]
环境
操作系统: Windows 2012
Python版本: 2.7
vn.py版本: 1.9.2
Issue类型
三选一：Question

预期程序行为
举例来说，c2001成交的onTrade应该由合约为c2001的CTP策略来响应，不应该出现在其他合约（如：m2005等）的CTP策略的onTrade事件中。

实际程序行为
c2001成交事件出现在了m2005的CTP策略的onTrade事件中

重现步骤
重现比较困难，我先描述下我是怎么做得吧。
我用多个命令行窗口分别开启了多个vnpy程序，每个窗口运行一个CTP策略：比如窗口1运行c2001的CTP策略，窗口2运行m2005的CTP策略，这些策略都是相对高频的按tick进行频繁交易。这时偶尔就会出现c2001的成交发到窗口2中的onTrade事件中进行响应，不知道大家有没有遇到这个问题？谢谢各位

**Comment by vnpy** [comment]
CTP的每个连接，本来就是会收到所有该账户的成交和委托推送，用户需要自行做过滤处理，请先翻阅官方文档后再做开发
