### ISSUE TITLE
IB登录后接口报错UnicodeDecodeError'utf8'code can't decode byte

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2151]
## 环境
* 操作系统: 如Windows 10
* vn.py版本: 如v2.0.6

三选一：Bug

## 预期程序行为
之前都是正确的，但是上周报错，后续登录都一直报错。

## 实际程序行为
（报错行数与IB接口行数对不上是因为在ibGateway.py中加了print导致行数不一致了）
接口中用了ib的标的前4档行情的。
除了cmd报这个错误，合约订阅等正常，标的交易正常。

## 重现步骤
![捕获](https://user-images.githubusercontent.com/31505150/67253029-3ad17780-f4a8-11e9-8a61-c4863e3e3454.PNG)

**Comment by hadrianl** [comment]
这个很可能是IB的问题，我昨天也遇到了这个情况，合约代码名称用utf8解析不了。你订阅的是那个合约？

**Comment by vnpy** [comment]
对于1.0版本的vn.py，必须在TWS的配置选项里，将API的语言设置为英文。

2.0后不存在这个问题了。
