### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by jianggs** [vnpy/vnpy#2158]
## 环境

* 操作系统: 如Windows 10
* Python版本: VNStudio-2.0.7
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Question

## 预期程序行为

点击连接ctp，没有处于出现连接成功，也没有报错。
在订阅界面输入期货合约也没出现数据
![vnpy-连接ctp](https://user-images.githubusercontent.com/55421784/67538043-6bb3e580-f710-11e9-85fe-cc5bd069be4c.png)

## 实际程序行为

没有任何反应
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![vnpy-订阅](https://user-images.githubusercontent.com/55421784/67538128-b5043500-f710-11e9-8d10-4fff6851ec13.png)

**Comment by vnpy** [comment]
请用你的机器，在cmd里telnet连接下CTP的服务器端口试试，看看网络是否能通

**Comment by jianggs** [comment]
在simsnow下载的快期客户端能正常使用，你们文档里提供的
180.168.146.187;10101
180.168.146.187;10111
218.202.237.33:10102
218.202.237.33:10112
地址均无法ping通。


jianggs@vip.qq.com
 
发件人： vn.py
发送时间： 2019-10-25 14:59
收件人： vnpy/vnpy
抄送： jianggs; Author
主题： Re: [vnpy/vnpy] 登录问题 (#2158)
请用你的机器，在cmd里telnet连接下CTP的服务器端口试试，看看网络是否能通

**Comment by jianggs** [comment]
在simnow下载的快期客户端能正常使用，你们文档里提供的
180.168.146.187;10101
180.168.146.187;10111
218.202.237.33:10102
218.202.237.33:10112
地址均无法ping通。

**Comment by vnpy** [comment]
如果无法ping通，那么可能是你的网络问题，请检查下吧，另外刚注册的SIMNOW账户，需要修改密码后才能通过vn.py登录
