### ISSUE TITLE
order_price_type 为7时超出了定义导致程序异常退出

### ISSUE THREAD

**Issue by stonejiang208** [vnpy/vnpy#2159]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.7发行版

## Issue类型
三选一：Bug

## 实际程序行为

异常

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

hbdb_gateway.py 第64~68行，只定义了 1~6 种类型，但在603行
type=ORDERTYPE_HBDM2VT[d["order_price_type"]],
存在返回的值为7

返回值数据片断为
{
    "status":"ok",
    "data":{
        "orders":[
            Object{...},
            Object{...},
            {
                "order_id":636414259111415808,
                "contract_code":"BTC191227",
                "symbol":"BTC",
                "lever_rate":20,
                "direction":"sell",
                "offset":"close",
                "volume":14,
                "price":8157.16,
                "create_date":1571774583380,
                "order_source":"trigger",
                "order_price_type":7,
                "order_type":1,
                "margin_frozen":0,
                "profit":-0.003051451235476,
                "contract_type":"quarter",
                "trade_volume":14,
                "trade_turnover":1400,
                "fee":-0.000034325672170216,
                "trade_avg_price":8157.16,
                "status":6,
                "order_id_str":"636414259111415808"
            },
---- 下略

**Comment by stonejiang208** [comment]
增加"fok":FOK订单(fok:全部成交或立即取消)，"ioc":IOC订单(ioc:立即成交并取消剩余)

**Comment by vnpy** [comment]
已在DEV分支修复，非常感谢
