### ISSUE TITLE
是否考虑神经网络算法等其他复杂算法在vnpy中实现

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2167]
群主，您好

请问是否考虑神经网络算法等其他复杂算法在vnpy中实现？ 感觉这个是将来非常有竞争力的并且是趋势的。

感谢！

**Comment by vnpy** [comment]
暂时没有计划了，vn.py中自带策略的作用是作为开发示例，而不是直接给大家提供赚钱的工具
