### ISSUE TITLE
spreadtrading 文档以及示例

### ISSUE THREAD

**Issue by xinhuih** [vnpy/vnpy#2169]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

## 重现步骤

如题，希望能增加文档和简单策略例子，现有的代码对于不是做套利的人来说有点难懂。我自己想在这部分基础上写一个通用的单策略多品种引擎。。。

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy/blob/dev/docs/spread_trading.md
目前已经完成价差文档，将会在下个版本更新到网站上
