### ISSUE TITLE
cta_strategy 下 backtesting.py  stop_order.vt_orderid = order.vt_orderid，是否有错

### ISSUE THREAD

**Issue by cfzvzv** [vnpy/vnpy#2171]
class StopOrder:
    vt_symbol: str
    direction: Direction
    offset: Offset
    price: float
    volume: float
    stop_orderid: str
    strategy_name: str
    lock: bool = False
    vt_orderids: list = field(default_factory=list)
    status: StopOrderStatus = StopOrderStatus.WAITING
中是 vt_orderids: list = field(default_factory=list)

cta 实盘引擎engine.py中 是vt_orderids=[order.vt_orderid],
        if order.type == OrderType.STOP:
            so = StopOrder(
                vt_symbol=order.vt_symbol,
                direction=order.direction,
                offset=order.offset,
                price=order.price,
                volume=order.volume,
                stop_orderid=order.vt_orderid,
                strategy_name=strategy.strategy_name,
                status=STOP_STATUS_MAP[order.status],
                vt_orderids=[order.vt_orderid],
            )
            self.call_strategy_func(strategy, strategy.on_stop_order, so)

请检查G:\Python\vnpy-2.0\vnpy-2.0.7\vnpy\app\cta_strategy\backtesting.py  下    def cross_stop_order(self):中
stop_order.vt_orderid = order.vt_orderid，是否有错

**Comment by vnpy** [comment]
已修复
