### ISSUE TITLE
Bitmex 手动web界面平仓报错

### ISSUE THREAD

**Issue by wwdd23** [vnpy/vnpy#2179]
## 环境

* 操作系统: mac
*Python版本:  3.7
* vn.py版本:  dev 

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
当手动提交平仓订单后 console bitmex_gateway 报错
![image](https://user-images.githubusercontent.com/5114088/68108937-2d929f00-ff24-11e9-9096-fb646ffb3972.png)

因为bitmex 接口中平仓操作 side: ""，
Direction 方向判断代码中没有包含 side 为空判断，造成出现keyerror 报错。

需要在 on_order 中添加bitmex side 信息判断。
当 side: "" 时，
on_order   OrderData.direction  需要修改为平仓。

![image](https://user-images.githubusercontent.com/5114088/68109221-ece75580-ff24-11e9-968d-43f1785cac29.png)

**Comment by xldistance** [comment]
这么奇葩，交易所连个字段都不留

**Comment by vnpy** [comment]
已处理，这个是WEB UI上的平仓下单指令会引发的一种特殊订单类型，因为缺失其他数据，vn.py无法进行对应处理，因此直接过滤掉了
