### ISSUE TITLE
spreadtrading模块LegData的update_trade方法是否有误？

### ISSUE THREAD

**Issue by Wei-Jianan** [vnpy/vnpy#2180]
class LegData:    
    def update_trade(self, trade: TradeData):
        """"""
        if trade.direction == Direction.LONG:
            if trade.offset == Offset.OPEN:
                self.long_pos += trade.volume
            else:
                self.short_pos -= trade.volume
        else:
            if trade.offset == Offset.OPEN:
                self.short_pos += trade.volume
            else:
                self.long_pos -= trade.volume
       # 这里的净仓位的逻辑是否应改为self.net_pos = self.long_pos - self.short_pos?
        self.net_pos = self.long_pos - self.net_pos

**Comment by vnpy** [comment]
已修复
