### ISSUE TITLE
Win10缩放不是100%的UI显示问题

### ISSUE THREAD

**Issue by zheng-di** [vnpy/vnpy#2183]
* 操作系统: Windows 10 64位
* Python版本:  VNStudio-2.0.7
* 分别率3840x2160，缩放大小300%

缩放只要不是100%都会有显示不全的问题

**Comment by vnpy** [comment]
目前尚未支持缩放，我们看看怎么实现

**Comment by vnpy** [comment]
已添加对高清屏的支持
