### ISSUE TITLE
价差demo策略statistical_arbitrage_strategy会一直重复开仓

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#2187]
![QQ截图20191111160816](https://user-images.githubusercontent.com/29418474/68571438-f846fd80-049d-11ea-8ee9-0d90b469f75d.png)

**Comment by xldistance** [comment]
示例的ipynb也出现了重复下单的情况
![QQ截图20191111162342](https://user-images.githubusercontent.com/29418474/68572178-bb7c0600-049f-11ea-9868-9e1978249967.png)

**Comment by vnpy** [comment]
有自己改过任何参数或者代码吗？这里看应该是之前启动了多个做空的算法，没有能成交，然后在10:43被集中触发了

**Comment by xldistance** [comment]
官方dev/examples里面的回测也是有这个问题的

**Comment by vnpy** [comment]
排查后无法重现该问题，操作步骤：
1. 准备IF1912.CFFEX和IF1911.CFFEX的数据，使用CtaBacktester从RQData获取
2. 使用dev分支最新版本的代码
3. 直接运行回测

输出结果如下：

![捕获](https://user-images.githubusercontent.com/11263900/68826298-421b2800-06d8-11ea-8646-0871b0e6e2ad.PNG)

符合策略正常的买卖逻辑。

**Comment by vnpy** [comment]
已修复，非常感谢
