### ISSUE TITLE
vnpy2.0.7 ubuntu 无法运行ctp接口

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2188]
## 环境

* 操作系统:  Ubuntu 18.04
* Python版本: miniconda 3
* vn.py版本: v2.0.7

## Issue类型
三选一：Enhancement

## 预期程序行为
python run.py

## 实际程序行为

> Traceback (most recent call last):
>   File "run.py", line 10, in <module>
>     from vnpy.gateway.ctp import CtpGateway
>   File "/root/quantopy/vnpy/gateway/ctp/__init__.py", line 1, in <module>
>     from .ctp_gateway import CtpGateway
>   File "/root/quantopy/vnpy/gateway/ctp/ctp_gateway.py", line 6, in <module>
>     from vnpy.api.ctp import (
>   File "/root/quantopy/vnpy/api/ctp/__init__.py", line 1, in <module>
>     from .vnctpmd import MdApi
> ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'

## 重现步骤
已经运行了 bash install.sh
python run.py

vnpy/api/ctp/ 没有找到build脚本，麻烦大神提供一个。

**Comment by vnpy** [comment]
2.0中改为使用项目的setup.py文件中的配置来build，无需脚本了，请查看：
https://github.com/vnpy/vnpy/blob/master/setup.py

**Comment by jieyujing** [comment]
粗心没看完整个目录，谢谢解答。

vn.py <notifications@github.com> 于2019年11月12日周二 下午2:26写道：
