### ISSUE TITLE
vn.Trader文件夹中的ctaAlgo文件夹中的ctaBacktesting.py中的crossStopOrder函数限价单和停止单混淆

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#219]
#----------------------------------------------------------------------
    def crossStopOrder(self):
        """基于最新数据撮合停止单"""
        # 先确定会撮合成交的价格，这里和限价单规则相反
        if self.mode == self.BAR_MODE:
            buyCrossPrice = self.bar.high    # 若买入方向停止单价格低于该价格，则会成交
            sellCrossPrice = self.bar.low    # 若卖出方向限价单价格高于该价格，则会成交
            bestCrossPrice = self.bar.open   # 最优成交价，买入停止单不能低于，卖出停止单不能高于
        else:
            buyCrossPrice = self.tick.lastPrice
            sellCrossPrice = self.tick.lastPrice
            bestCrossPrice = self.tick.lastPrice
        
        # 遍历停止单字典中的所有停止单
        for stopOrderID, so in self.workingStopOrderDict.items():
            # 判断是否会成交
            buyCross = so.direction==DIRECTION_LONG and so.price<=buyCrossPrice
            sellCross = so.direction==DIRECTION_SHORT and so.price>=sellCrossPrice
            
            # 如果发生了成交
            if buyCross or sellCross:
                # 推送成交数据
                self.tradeCount += 1            # 成交编号自增1
                tradeID = str(self.tradeCount)
                trade = VtTradeData()
                trade.vtSymbol = so.vtSymbol
                trade.tradeID = tradeID
                trade.vtTradeID = tradeID
                
                if buyCross:
                    self.strategy.pos += so.volume
                    trade.price = max(bestCrossPrice, so.price)
                else:
                    self.strategy.pos -= so.volume
                    trade.price = min(bestCrossPrice, so.price)                
                
                self.limitOrderCount += 1
                orderID = str(self.limitOrderCount)
                trade.orderID = orderID
                trade.vtOrderID = orderID
                
                trade.direction = so.direction
                trade.offset = so.offset
                trade.volume = so.volume
                trade.tradeTime = str(self.dt)
                trade.dt = self.dt
                self.strategy.onTrade(trade)
                
                self.tradeDict[tradeID] = trade
                
                # 推送委托数据
                so.status = STOPORDER_TRIGGERED
                
                order = VtOrderData()
                order.vtSymbol = so.vtSymbol
                order.symbol = so.vtSymbol
                order.orderID = orderID
                order.vtOrderID = orderID
                order.direction = so.direction
                order.offset = so.offset
                order.price = so.price
                order.totalVolume = so.volume
                order.tradedVolume = so.volume
                order.status = STATUS_ALLTRADED
                order.orderTime = trade.tradeTime
                self.strategy.onOrder(order)
                
                self.limitOrderDict[orderID] = order
                
                # 从字典中删除该限价单
                del self.workingStopOrderDict[stopOrderID]

以上是撮合停止单的函数，但是函数里面停止单成交后limitOrderCount 限价单计数器加1，又使用limitOrderDict限价单字典加入停止单的订单。这里的写法是不是错了？！如果没错，那么这样写很容易让人误解啊，本来限价单和停止单的概念就比较容易混淆，这里的变量命名让人看代码更容易混淆！

**Comment by vnpy** [comment]
1. 本地停止单在是盘中是一个运行在本地程序中的条件委托，当价格到达后会被立即触发并发出一个限价单，然后在市场上成交
2. 回测中为了模拟和实盘相同的效果，所以需要采用你之前提出的逻辑

**Comment by akeyong** [comment]
撮合限价单的函数主要是从workingLimitOrderDict里遍历，撮合成功后，就从workingLimitOrderDict里删除；
撮合停止单的函数主要是从workingStopOrderDict里遍历，撮合成功后，就从workingStopOrderDict里删除；函数里面停止单成交后limitOrderCount 限价单计数器加1，又使用limitOrderDict限价单字典加入停止单的订单，看起来目的只是保存触发停止单成交的委托报单。。。
LimitOrderDict和stopOrderDict目前看起来只是模拟和实盘相同的效果，起存档作用（相当于实盘里面的所有委托报单日志），并不会对回测结果有影响。。。

**Comment by vnpy** [comment]
楼上正解
