### ISSUE TITLE
windows10 安装报错

### ISSUE THREAD

**Issue by danerlt** [vnpy/vnpy#2195]
## 环境

* 操作系统: 如Windows 
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 最新版

## Issue类型
Question

## 预期程序行为
安装成功

## 实际程序行为
安装过程报错,提示信息:
![image](https://user-images.githubusercontent.com/14197717/68835902-173ecd00-06f4-11ea-9195-66c3404d1b90.png)
![image](https://user-images.githubusercontent.com/14197717/68836026-5a993b80-06f4-11ea-8d1e-d94db43f94fa.png)

**Comment by vnpy** [comment]
请尝试使用VPN或者全局代理的SS翻墙后，再执行安装程序
