### ISSUE TITLE
连接CTP时报错闪退

### ISSUE THREAD

**Issue by chiyt14** [vnpy/vnpy#2198]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.7, python 3.7.1
* vn.py版本: 下载日期 dev branch 20191105

## Issue类型
三选一：Bug

## 预期程序行为
利用powershell 管理员身份运行 python run.py，登陆vnstation，打开VN Trader Lite，连接CTP时，预计能顺利登陆

## 实际程序行为
实际上在powershell中提示RuntimeError:can not open CFlow file in line 331 of file ..\..\source\userapi_se\ThostFtdcUserApiImplBase.cpp
然后程序自动退出

## 重现步骤
先从github上下载源码，利用install.bat安装，然后利用powershell 管理员身份运行 python run.py，登陆vnstation，打开VN Trader Lite，连接CTP，输入用户名等信息，点击连接，powershell中提示RuntimeError:can not open CFlow file in line 331 of file ..\..\source\userapi_se\ThostFtdcUserApiImplBase.cpp，然后程序退出

**Comment by vnpy** [comment]
检查你的Windows用户名是否为中文，以及用户是否有管理员权限
