### ISSUE TITLE
不成交即撤单后再追单是否可以这样写？是否有改进的可能？求指导

### ISSUE THREAD

**Issue by ideaplat** [vnpy/vnpy#22]
`    def onOrder(self, order):
        """收到委托变化推送（必须由用户继承实现）"""
        # 对于无需做细粒度委托控制的策略，可以忽略onOrder

        # CTA委托类型映射
        if order.direction == u'多' and order.offset == u'开仓':
            orderType = u'买开'
        elif order.direction == u'多' and order.offset == u'平仓':
            orderType = u'买平'
        elif order.direction == u'空' and order.offset == u'开仓':
            orderType = u'卖开'
        elif order.direction == u'空' and order.offset == u'平仓':
            orderType = u'卖平'

        if order.status == u'未成交':
            self.cancelOrder(order.vtOrderID)

        elif order.status == u'已撤销':
            self.sendOrder(orderType, self.bar.close, 1)`

**Comment by vnpy** [comment]
这样写不妥，因为CTP在下单后，会立即推送一个委托回报，内容是当前委托已经提交（vn.trader中定义为未成交），如果是能立即成交的委托，会在随后立即推送第二个委托回报，通知当前委托已经成交。

因此如果要做撤单后立即追单的操作，最好在收到新的行情数据后在onTick里判断，而不要写在onOrder里，可能导致不必要的重复发单。

**Comment by ideaplat** [comment]
Thank you

**Comment by liuadong1984** [comment]
您好！项目需求需要重新编译高版本的ctp dll。但是对c++不是很熟悉！能否简单的描述一下应该注意的问题或者简单写个大概思路和教程。

**Comment by ideaplat** [comment]
请仔细查看vnpy.org教程，里面有详细说明
