### ISSUE TITLE
VNPY2.0.x 在mongoDB没有连接的情况下，记录数据没有任何报错，也不提示错误信息

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2204]
* 操作系统: 如Windows 10
* vn.py版本: 如v2.0.7发行版

## Issue类型
三选一：Bug

## 预期程序行为
mongo数据库没建好的情况下应该有提示或者报错的。

## 实际程序行为

群主，您好

数据库没有连接的情况下，应该报错或有提示信息，但是实际mongodb中没创建任何库，程序没任何提示的。
特意把把数据库drop了进行测试的。

![阿斯蒂芬](https://user-images.githubusercontent.com/31505150/69120349-5f833400-0ad4-11ea-91ac-5e883bad32f3.png)

**Comment by stone3536** [comment]
先是drop库后debug的时候发现这种情况的，然后又不再用debug模式进行测试，图是非debug模式测试结果。

**Comment by vnpy** [comment]
已修复，出现异常会正常提示
