### ISSUE TITLE
ctp二代行情

### ISSUE THREAD

**Issue by luffyasce** [vnpy/vnpy#2207]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: VNStudio-2.0.8
* vn.py版本: vnpy-2.0.8

## Issue类型
三选一：Enhancement

## 重现步骤

关于ctp二代行情的接口，在ctpgateway的代码里：
if data["BidPrice2"]:
tick.bid_price_2 = data["BidPrice2"]
tick.bid_price_3 = data["BidPrice3"]
tick.bid_price_4 = data["BidPrice4"]
tick.bid_price_5 = data["BidPrice5"]
tick.ask_price_2 = data["AskPrice2"]
tick.ask_price_3 = data["AskPrice3"]
tick.ask_price_4 = data["AskPrice4"]
tick.ask_price_5 = data["AskPrice5"]
tick.bid_volume_2 = data["BidVolume2"]
tick.bid_volume_3 = data["BidVolume3"]
tick.bid_volume_4 = data["BidVolume4"]
tick.bid_volume_5 = data["BidVolume5"]
tick.ask_volume_2 = data["AskVolume2"]
tick.ask_volume_3 = data["AskVolume3"]
tick.ask_volume_4 = data["AskVolume4"]
tick.ask_volume_5 = data["AskVolume5"]

我看代码里这段似乎是只有当bp2>0时才会赋值五档行情，但行情有时会出现跌停的情况，导致bp2==0，此时ap这边是有五档的，这样处理是否会导致跌停的时候只有一档行情呢？我感觉可以data["BidPrice2"]和data["AskPrice2"]分别判断，来赋值。
希望作者大神看下，谢谢。

**Comment by vnpy** [comment]
已经支持，基于BidVolume2和AskVolume2判断
