### ISSUE TITLE
建议这些回测参数保存起来，下次打开可以不用再重复再填

### ISSUE THREAD

**Issue by liuagng** [vnpy/vnpy#2210]
![TPR8YDDB`K_ )@C1@5JKWA5](https://user-images.githubusercontent.com/28752075/69291325-d425b200-0c3d-11ea-952c-cd3a43ef8ed9.png)
![JX7ESZ~CC(208F8{W7 C~4](https://user-images.githubusercontent.com/28752075/69291331-d851cf80-0c3d-11ea-8232-013edce4a23e.png)
建议这些回测参数保存起来，下次打开可以不用再重复再填

**Comment by vnpy** [comment]
已添加对于回测参数的保存功能
