### ISSUE TITLE
Tap trade没有 on_disconnect 报警. 断线了,不知道怎么处理

### ISSUE THREAD

**Issue by van420** [vnpy/vnpy#2213]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.7
* vn.py版本: VNStudio-2.0.7

## Issue类型
三选一：Bug

## 预期程序行为
Tap trade 断线报警,并重连

## 实际程序行为
Tap trade没有 on_disconnect. 断线了无法重连

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1.11/21 0:01分断线, 0:26才发现,并手工重连.
2. 行情已经重连了,但交易看起来,并没有重连.

![image](https://user-images.githubusercontent.com/5801273/69325008-7072a780-0c84-11ea-9fd3-9ab94467f27e.png)

**Comment by vnpy** [comment]
增加实现了TD接口的断线回调日志输出
