### ISSUE TITLE
RQData的连接限制有点恶心，每次关掉再开VNpy会显示连接达到上限

### ISSUE THREAD

**Issue by liuagng** [vnpy/vnpy#2214]
## 环境
VNStudio-2.0.8

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
能不能改成Http方式，这样就不会有连接上限的问题了,是RQData那边的问题？

## 实际程序行为
在实盘CTA策略的时候，打开CTA策略的时候。
RQData的连接限制有点恶心，每次关掉再开VNpy会显示连接达到上限

###截图

![image](https://user-images.githubusercontent.com/28752075/69399443-1ed02880-0d29-11ea-8fac-9b14e3738f27.png)

**Comment by vnpy** [comment]
购买付费账号，RQData会放开登录数限制
