### ISSUE TITLE
OKEXF 交易报错

### ISSUE THREAD

**Issue by WongLynn** [vnpy/vnpy#2215]
## 环境

* 操作系统: 如Windows  server2008
* Python版本: 环境安装适配，使用ananconda
* vn.py版本: 如v2.0.8发行版

## Issue类型
三选一：Bug

## 预期程序行为
使用示例的海龟交易策略，验证OKEXF 季度合约EOS 交易，验证交易程序稳定性

## 实际程序行为
1）发单成功之后 界面委托与活动之中的【状态】均没有进行更新
2）界面持仓信息也没有进行更新
3）程序报错，然后websocket 行情订阅停止，程序无效

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![001](https://user-images.githubusercontent.com/17221074/69471710-50350c80-0d9a-11ea-9116-ee077b880cc8.png)
![002](https://user-images.githubusercontent.com/17221074/69471712-532ffd00-0d9a-11ea-99a1-45f17906a0db.png)
![003](https://user-images.githubusercontent.com/17221074/69471713-54612a00-0d9a-11ea-8aed-e8a09c09e50b.png)
![004](https://user-images.githubusercontent.com/17221074/69471714-562aed80-0d9a-11ea-952d-78bf056409f8.png)

**Comment by vnpy** [comment]
已修复，非常感谢
