### ISSUE TITLE
okex永续合约支持加载本地历史数据

### ISSUE THREAD

**Issue by Cloud0421** [vnpy/vnpy#2216]
## 环境
* Win serve 2012 香港阿里云
*VNStudio-2.0.7

## Issue类型
Enhancement

## 加强的部分

希望okexs端口（okex永续合约）可以支持本地csv导入历史数据给策略
（怕自己描述的不清楚，摘一下群主大大的原话，感谢群主提供这么好的框架）
Quote：
OKEX接口支持历史数据下载的情况下，就直接通过服务器拉取最新的数据了，没有通过本地数据库来加载，如果需要的话请开个issue，我们看看怎么支持

**Comment by vnpy** [comment]
已处理。
