### ISSUE TITLE
Script_trader 模块是不是没有对上海持仓做平今、平昨处理？

### ISSUE THREAD

**Issue by solobear** [vnpy/vnpy#2217]
Script_trader 模块是不是没有对上海持仓做平今、平昨处理？

## 环境
* 操作系统: 如Windows 7
* Python版本:  3.7_64 
* vn.py版本:  dev

## Issue类型
三选一：Bug

## 预期程序行为
Script_trader 模块对上海持仓做平今、平昨处理

## 实际程序行为
Script_trader 模块没有对上海持仓做平今

## 重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by solobear** [comment]
交易委托失败，代码：51，信息：CTP:平昨仓位不足

**Comment by vnpy** [comment]
确实没有处理，我们后续版本加上

**Comment by solobear** [comment]
谢谢

**Comment by vnpy** [comment]
ScriptTrader模块和CtaStrategy、SpsreadTrading有个比较大的区别，就是策略内部是可以通过get_position函数来直接访问到底层账户的真实持仓数据，该数据包括总仓和昨仓字段（可以计算出今仓），可以很方便的自行判断是要发出平今还是平昨指令。

同时ScriptTrader模块主要的定位，是给用户提供一个尽可能接近各个交易接口最原始设计的交易功能，因此决定不加入OffsetConverter的自动转换功能。
