### ISSUE TITLE
SimNow 无法访问（翻墙后也无法访问）

### ISSUE THREAD

**Issue by CapsulE07** [vnpy/vnpy#2220]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为

无法访问此网站 网址为 http://www.simnow.com.cn/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_INVALID_RESPONSE
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
测试了下现在可以正常访问，不用翻墙的

**Comment by lenville** [comment]
@vnpy +1 同样法访问 simnow.com.cn，检查过 VPN 切换过 DNS 均无效，ping超时

**Comment by lenville** [comment]
Done. @CapsulE07 Simnow周五盘后及周末不开，盘中多访问下就可以
