### ISSUE TITLE
SimNow连接成功但是无法获取数据

### ISSUE THREAD

**Issue by CapsulE07** [vnpy/vnpy#2222]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
bug
## 预期程序行为
通过SimNow连接后，日志模块显示交易服务器授权验证成功，但是查询合约中是空的。
也无法在交易窗口中查询到相关代码的数据。
![image](https://user-images.githubusercontent.com/23300139/69726443-905e0b80-115b-11ea-8fa2-b064febcd7ab.png)
![image](https://user-images.githubusercontent.com/23300139/69726562-ca2f1200-115b-11ea-9b06-e71eb86a29e1.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
登录时间太早了，当时夜盘服务器还没完成初始化，迟点再登录就行。
