### ISSUE TITLE
LogEngine是不是用自己的queue比较好？

### ISSUE THREAD

**Issue by gang-yu** [vnpy/vnpy#2224]
## Issue类型
三选一：Question

## 重现步骤
 无

## 问题
你好~
LogEngine 与 EmailEngine，同样是职能比较单一的engine，前者使用系统的event_engine以及其中的queue，后者有自己的queue。这有什么特殊用意么？

### 我的理解
系统的event_engine，事件是异步加入的，但是handler处理是在（_run  _process）for循环中FIFO依次处理的。IO 比较费时，多少会影响到其后的event的处理。所以 log 不占用系统的queue比较好吧。
### 我的看法
系统的queue还是专注于核心的交易event比较好，log与email、data recorder有一点算外围。
我的想法：event直接加入到log自身的queue，然后LogEngine 给系统queue发一个log的event，供UI等模块使用。

没有做压测，高频经验也没有。只是自己的个人看法。【抱拳】请大神指正。

**Comment by vnpy** [comment]
这个猜测是对的，所以全局配置里直接加上了是否要开启Log的功能，一般推荐在系统或者策略测试阶段开着日志（尤其是文件日志），真到稳定实盘后可以关闭减少性能开销，因此在LogEngine的设计上就不多此一举了。
