### ISSUE TITLE
关闭界面卡住很久

### ISSUE THREAD

**Issue by oldoldjiang** [vnpy/vnpy#2225]
## 环境

* 操作系统: Mac OS
* Python版本: 3.7
* vn.py版本: dev branch 20191109

## Issue类型
三选一：Question

## 预期程序行为
立刻关闭界面

## 实际程序行为
等了好几分钟，才关闭界面

## 重现步骤
1. 打开vnpy的gui
2. 连接huobi
3. 订阅一个行情
4. 点击系统--》退出

经过调试，是关闭gateway的时候，在调用websocket的close的函数，卡住很久，请问这个是ws的正常行为么？有没有办法立刻关闭ws的连接？

**Comment by vnpy** [comment]
之前没测试过HuobiGateway在Mac上的效果，Windows上应该是可以正常关闭退出的，我们查下吧

**Comment by yhmickey** [comment]
windows上有时候也会卡很久，不太清楚原因

**Comment by vnpy** [comment]
WIN10测试下来无法重现，如果后续发现稳定重现的方法请告知
