### ISSUE TITLE
穿透测试现在需要CTP6.3.16T

### ISSUE THREAD

**Issue by RosyRomance** [vnpy/vnpy#2226]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6

## Issue类型
现在做穿透测是需要6.3.16T版本，之前的6.3.13用不了了。使用6.3.13版本登录会报交易服务器验证失败，错误代码63.

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
dev分支已升级到6.3.16
