### ISSUE TITLE
HBDM 在手动下单后，vntrader会出错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2227]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: v2.0.8

## Issue类型
Bug

## 实际程序行为

当vnpy连接hdbm后，如果此时在网页上手动下单，会导致本机vnpy出错崩溃

**Comment by vnpy** [comment]
请问具体下的什么委托？

**Comment by yhmickey** [comment]
![捕获](https://user-images.githubusercontent.com/34559558/70007835-d88e8b00-15ac-11ea-8151-e10610e15a5c.PNG)

手动平仓的时候


手动开仓没问题，但是当手动平仓时，会报错。
为复现此问题，又充了钱进去，试了一把。老大请再试试

**Comment by yhmickey** [comment]
![捕获](https://user-images.githubusercontent.com/34559558/70007952-1ee3ea00-15ad-11ea-8d0d-1cdb0965f734.PNG)

**Comment by vnpy** [comment]
已添加新的委托类型，非常感谢
