### ISSUE TITLE
委托回报触发的持仓推送卡住了

### ISSUE THREAD

**Issue by Cloud0421** [vnpy/vnpy#2228]
## 环境

* 操作系统: 如Winserve2012 香港阿里云
* Python版本: 如VNStudio-2.0.8 okexs接口 

## Issue类型
三选一：Bug

##quote 群主原话
委托回报触发的持仓推送卡住了

## 预期程序行为
平完一个仓位之后
1.过一段时间，vntrader右下角持仓界面应该显示这个仓位被平掉
2.脚本策略，使用持仓命令查询，应该显示这个持仓为0

## 实际程序行为
1.vntrader右下角显示被冻结，明明已经被平掉
2.脚本策略，使用持仓命令查询，还在给我推 这个仓位还在的信息

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![1](https://user-images.githubusercontent.com/40237194/69970929-0eeeea80-155a-11ea-81d8-1fd43ccfaeb3.png)
![2](https://user-images.githubusercontent.com/40237194/69970932-10b8ae00-155a-11ea-9955-d5d3c719f182.png)
![微信图片_20191202231921](https://user-images.githubusercontent.com/40237194/69970999-32199a00-155a-11ea-9c77-679140b9febd.jpg)

**Comment by vnpy** [comment]
该问题由于OKEX的Websocket连接闪断导致，建议更换到更加稳定网络条件，或者自行在WebsocketApi中on_login函数下添加委托查询逻辑
