### ISSUE TITLE
改为异步，协程模式会不会性能更好？

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2229]
起码有一个优点就是不会容易卡住。
系统复杂了，一个地方block就导致整个系统卡一下，可能很要命。
改为协程应该就没有这个隐患。它会把cpu让出来。

**Comment by vnpy** [comment]
不会的，协程只能解决IO密集型任务，而量化实盘交易是典型的计算密集型任务，协程完全没用，而且因为不能保证事件调度的顺序，还会出现难以排查的隐形BUG

**Comment by hadrianl** [comment]
做成异步能优化线程之间调度的损耗，不过，这项目已经到这步了，改异步很难了。而且从开发的角度上来说，这对策略开发人员来说不太友好的
