### ISSUE TITLE
k线图显示使用event事件刷新报错不是同一个thread

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2231]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.0.8

## Issue类型
三选一：Enhancement/Question

群主，您好

在群里咨询了这个问题，没得到高手们的指点，恳请您帮忙看下原因及是否有好的解决方式，谢谢！

用examples下的candle_chart下的run.py测试 ChartWidget() 没任何问题，使用里边的QtCore.QTimer() 方式调用 widget.update_bar(bar) 刷新新的K线也可以显示，但是新作的窗口（QtWidgets.QWidget参考合约窗口）中，注册了EVENT_TIMER事件，想使用该事件刷新 widget.update_bar(bar) 【目前测试使用300个K线，前3个显示，剩余的作为刷新测试】的，但是只要调用widget.update_bar(bar)就报错的，报错信息如下：
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0xa1b56a0), parent's thread is QThread(0x27fec60), current thread is QThread(0xa010a70)

不论是使用EVENT_TIMER 还是EVENT_TICK方式都报错的。之前是在 RecorderManager() 的窗口调用的也是同样的问题，在RecorderManager窗口中增加了按钮调出新作的窗口仍旧报同样的错误的。
其中widget.update_bar(bar)的widget改成窗口的self.widget的了。
确定检查过无其他错误的了，因为只要屏蔽掉widget.update_bar(bar)就都正确的。

只是想在bar变化（目前用tick和timer测试的）的时候刷新K线，
如果不是同一个线程，那么为什么RecorderManager()窗口中调用event不报错呢？

vnpy中是否有实现这个功能的范例？

请群主指导下这部分该如何用vnpy架构最优实现，感谢！

## 重现步骤
![阿道夫](https://user-images.githubusercontent.com/31505150/70103884-3c7d8600-1677-11ea-82b4-a4d997ee87a3.png)

**Comment by hadrianl** [comment]
https://github.com/hadrianl/vnpy/tree/master/vnpy/app/realtime_monitor/ui
可以参照一下我这里的实现，一般通过event触发qtsignal，signal绑定更新函数来实现刷新

**Comment by vnpy** [comment]
楼上正解，更新QT界面一定要通过Signal/Slot机制

**Comment by stone3536** [comment]
收到，感谢两位！
