### ISSUE TITLE
ib账户兼容问题

### ISSUE THREAD

**Issue by QueenConch** [vnpy/vnpy#2232]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版

## Issue类型
三选一：Bug

## 预期程序行为
盈透有账户和用户的概念，比如申请一个模拟账户，账户名大概是DUXXX，而用户名不一样，一个用户可以分配多个账户
## 实际程序行为
目前只支持模拟账号。真实的默认多账号登陆导致逻辑混乱的问题

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
使用一个（带2个账户的）用户名登陆

**Comment by vnpy** [comment]
已经支持
