### ISSUE TITLE
IB合约不能自动订阅问题，建议vnpy加上ib的标的自动订阅功能

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2233]
## 环境
* vn.py版本: 如v2.0.8发行版

## Issue类型
三选一：Enhancement

## 实际程序行为

群主，您好

vnpy的2.0.x中 ib合约不能自动订阅，不太清楚为啥这里没做，我试了下，在dr的窗口中，添加了这个合约的时候，判断出来是ib的合约了（我根据交易所判断的），那么就和内盘一样加到tick和bar的记录列表中并调用self.main_engine.subscribe(req, "IB") ，下次登录ib的时候，在ib接口文件的connect(...)登录成功获取时间完成后的位置，增加一个eIBcontractSubscribe的事件，在dr的engine的方法 process_contract_event(...) 中捕获到这个事件后调用 self.main_engine.subscribe(req, "IB") 来完成IB合约的自动订阅，否则这个位置真的是不够完美的，以上我测试过了没问题的。

当然也许还有更好的方式，期望vnpy从源头上能够优化下这里的。

另外 吐槽下 代码用纯数字的conId，实在是耗费精神熵的呀！当然，可能是为了更广泛的兼容。如果可以，是否可以在代码后边增加上localSymbol的呢？

2.0.x 的结构设计确实是漂亮的，赞！！！

感谢！

**Comment by vnpy** [comment]
已在DEV分支添加IbGateway的合约本地缓存和加载该功能
