### ISSUE TITLE
TargetPosTemplate的缺陷

### ISSUE THREAD

**Issue by leochan007** [vnpy/vnpy#2234]
在TargetPosTemplate里有这么一段 是有问题的， cancel后信息未确认，就开始计算poschange （这等于是假定了 挂单价格远离市场盘口，没有成交）
事实上，如果出现部分成交的问题，非常容易出现。
举例子说明 targetpos是5手 由于流动性不够只成交3手， 那么poschange是2 我又去买2张 如果再cancelall调用的时候 实际市场又成交了1手 那么就会出现多下单1手的情况；

def trade(self):
    """"""
    self.cancel_all()

    pos_change = self.target_pos - self.pos
    if not pos_change:
        return

正确的做法应该是cancel的order回调里去计算poschange

**Comment by vnpy** [comment]
已处理，非常感谢
