### ISSUE TITLE
建议以后改为异步协程模式

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#2238]
VNPY明显就是多任务的系统了。
最近发现使用asyncio这东西，一般就不会出现卡住的现象。
现在的vnpy是很容易出现堵塞现象的。建议以后改为asyncio模式。

**Comment by Alexdachen** [comment]
同样建议。目前这个多线程任务队列模式，在跑多个策略和多个合约的时候就明显不够用了。

**Comment by Gwill** [comment]
vnpy 是多进程，在整体架构上不会存在所谓的阻塞（事件流）。你遇到了什么具体的阻塞现象要具体拿出来具体分析具体解决。不要什么就是无脑上 asyncio ，这种风气在 python 界很不好。
