### ISSUE TITLE
回测模块  cross_limit_order 里面 trade.price计算有问题

### ISSUE THREAD

**Issue by ipqhjjybj** [vnpy/vnpy#2241]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

trade.price = order.price

## 实际程序行为

```
if long_cross:
        trade_price = min(order.price, long_best_price)   这里错的 trade.price=order.price
        pos_change = order.volume
else:
        trade_price = max(order.price, short_best_price) 这里错的 trade.price=order.price
        pos_change = -order.volume
```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这里的撮合原理，在公众号vnpy-community的进阶教程中有详细讲解
