### ISSUE TITLE
项目配置的问题

### ISSUE THREAD

**Issue by cxjpower** [vnpy/vnpy#2245]
## 环境

* 操作系统: Windows 10
* Python版本: miniconda python3.8
* vn.py版本: dev branch 20191119

1. 新换了电脑，按老习惯手动配置vnpy环境，一切安装好了后运行run.py出错，出错位置在ctptest.gateway.py的from .vnctpmd import MdApi行，出错信息为ImportError: DLL load failed while importing vnctpmd: 找不到指定的模块。
2. 这种情况以前遇到过，重新编译生成vnctpmd.pdb和vnctptd.pdb可以解决，于是用vs2019打开vnctp.sln项目文件，更新了与python安装位置相关的include目录和libs目录（原项目默认python是安装的C盘根目录下的)，但是在重新生成时出现以下错误：
1>vnctpmd.obj : error LNK2019: 无法解析的外部符号 "public: static class CThostFtdcMdApi * __cdecl CThostFtdcMdApi::CreateFtdcMdApi(char const *,bool,bool)" (?CreateFtdcMdApi@CThostFtdcMdApi@@SAPEAV1@PEBD_N1@Z)，该符号在函数 "public: void __cdecl MdApi::createFtdcMdApi(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?createFtdcMdApi@MdApi@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
1>S:\Trader\vnpy\vnpy\api\ctp\vnctp\..\vnctpmd.pyd : fatal error LNK1120: 1 个无法解析的外部命令
貌似是按照头文件信息链接库文件时出错，但是我看libs目录里thostmduserapi_se.lib和thosttraderapi_se.lib两个都在，不知道为什么会出错，请求帮助。

**Comment by cxjpower** [comment]
问题已解决，需要手动编辑vcxproj里的路径，图形界面里修改不完整。

**Comment by langway** [comment]
您好，遇到了同样的问题，已修改python的路径，但仍出现上述错误，请问还需修改哪里？
