### ISSUE TITLE
关于CTA策略功能界面中各个按钮状态与策略状态无关的问题

### ISSUE THREAD

**Issue by hxxjava** [vnpy/vnpy#2252]
## 环境
* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.x
* vn.py版本: 如v2.0.x发行版

## 预期程序行为
在CTA策略功能界面中可以加载已经回测好的策略，如图所示，其中的“初始化”、“启动”、"停止"、“编辑”、“移除”按钮用来加载和运行已经编写好的交易策略。如果操作者自觉地按照顺序按压执行“初始化”、“启动”、"停止"按钮的话，运行策略是没有问题的。

## 实际程序行为
1. 其中的“初始化”、“启动”、"停止"、“编辑”、“移除”按钮的使能与策略的运行状态无关，
可能导致策略被多次加载的问题，可能出重复买卖的情况。2. 已经初始化、启动一个策略之后，再次选择按压“初始化”、“启动”按钮，将会启动另外一个策略实例，导致启动多个策略运行实例存在。

# 修改建议
这些按钮的状态应该随策略的运行状态而改变，建议如下：
1.策略未初始化时，“初始化”按钮是有效的，“启动”、"停止"按钮应该是无效的
2.策略已经初始化未启动时，“启动”按钮是有效的，初始化”、"停止"按钮应该是无效的
3.策略已经启动时，初始化”、“启动”按钮是无效的，"停止"按钮应该是有效的
4.“移除”按钮的状态=not（策略已经启动）。

![image](https://user-images.githubusercontent.com/34177947/71301829-36113d00-23df-11ea-8586-a9b3194c9b8d.png)

**Comment by stone3536** [comment]
那每个策略都是要有自己的状态的，而且是有层次和递进的规则的，实际上这就是业务流了，后边的“全部”三个按钮都要考虑的。

**Comment by vnpy** [comment]
已修改，非常感谢这个建议！
