### ISSUE TITLE
使用126邮箱发邮件会报错

### ISSUE THREAD

**Issue by liuagng** [vnpy/vnpy#2253]
## 环境

* 操作系统: 如Windows 2012
* Python版本: VNStudio-2.0.8
* vn.py版本: v2.0.8发行版

## Issue类型
Bug/

## 预期程序行为
不会报错

## 实际程序行为
![image](https://user-images.githubusercontent.com/28752075/71394432-70334680-264c-11ea-92e4-b6aabb466f36.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

使用126邮箱发邮件会报错，100%重现

**Comment by vnpy** [comment]
请检查126邮箱是否支持并开启了SSL端口
