### ISSUE TITLE
加密价差模块下的engine文件报错

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2254]
## 环境
* 操作系统: 如Windows 10
* vn.py版本: 如v2.0.8

## Issue类型
三选一：Enhancement/Question
群主，您好
加密价差模块下的engine文件报错，对msg做encode仍旧报错。
未做任何处理的报错信息如下：

## 预期程序行为

E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.0.8\vnpy\app\spread_trading>zzz.bat

E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.0.8\vnpy\app\spread_trading>cythoniz
e -i engine.py
Compiling E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.0.8\vnpy\app\spread_tradin
g\engine.py because it changed.
[1/1] Cythonizing E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.0.8\vnpy\app\sprea
d_trading\engine.py
E:\00_VNPY_2.x\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:369: FutureWa
rning: Cython directive 'language_level' not set, using 2 for now (Py2). This wi
ll change in a later release! File: E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.
0.8\vnpy\app\spread_trading\engine.py
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
            self.symbol_algo_map[leg.vt_symbol].append(algo)

        # Put event to update GUI
        self.put_algo_event(algo)

        return algoid
              ^
------------------------------------------------------------

engine.py:477:15: Cannot convert Unicode string to 'str' implicitly. This is not
 portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
        event = Event(EVENT_SPREAD_ALGO, algo)
        self.event_engine.put(event)

    def write_algo_log(self, algo: SpreadAlgoTemplate, msg: str) -> None:
        """"""
        msg = f"{algo.algoid}：{msg}"
             ^
------------------------------------------------------------

engine.py:498:14: Cannot convert Unicode string to 'str' implicitly. This is not
 portable and requires explicit encoding.

Error compiling Cython file:
------------------------------------------------------------
...
        event = Event(EVENT_SPREAD_STRATEGY, data)
        self.event_engine.put(event)

    def write_strategy_log(self, strategy: SpreadStrategyTemplate, msg: str):
        """"""
        msg = f"{strategy.strategy_name}：{msg}"
             ^
------------------------------------------------------------

engine.py:1020:14: Cannot convert Unicode string to 'str' implicitly. This is no
t portable and requires explicit encoding.
Traceback (most recent call last):
  File "E:\00_VNPY_2.x\Anaconda3\Scripts\cythonize-script.py", line 10, in <modu
le>
    sys.exit(main())
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\Cython\Build\Cythonize.py", l
ine 223, in main
    cython_compile(path, options)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\Cython\Build\Cythonize.py", l
ine 106, in cython_compile
    **options.options)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py"
, line 1096, in cythonize
    cythonize_one(*args)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py"
, line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2
.0.8\vnpy\app\spread_trading\engine.py

E:\36_VNPY【2.0版本】下载\vnpy-2.0.8\vnpy-2.0.8\vnpy\app\spread_trading>

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
VNStation内置的cython加密工具，只是用来加密策略代码文件的，由于标准化了主动函数、回调函数，所以cython可以直接兼容。对于其他代码，尤其是引擎层涉及大量复杂控制逻辑的，如果要用cython加密需要自行调整代码细节，来实现兼容。
