### ISSUE TITLE
cta 策略模块增加对账户余额查询的支持

### ISSUE THREAD

**Issue by topscien** [vnpy/vnpy#2260]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.9
* vn.py版本: 如v2.0.9发行版

## Issue类型
三选一：Enhancement

## 预期程序行为
在cta策略模块中，想要某些策略能够实时查询账户余额，从而配合策略动态计算仓位，例如用到凯利公式的策略

## 实际程序行为
vn.py好像不支持在cta策略中查询账户余额信息

**Comment by dear-catchlove** [comment]
可以这样self.cta_engine.main_engine.get_accout(vt_accountid).available

**Comment by 0xhelloweb3** [comment]
> vt_accountid
vt_accountid 在策略中怎么获取啊
