### ISSUE TITLE
拼写错误 setting_filename = "spraed_trading_strategy.json"

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2268]
vnpy\app\spread_trading\engine.py
第586行 "spraed_trading_strategy.json"
应该是 "spread_trading_strategy.json"

**Comment by cbogithub** [comment]
https://github.com/vnpy/vnpy/commit/d8cca811fed1f75d5ba4c4298c2f3cc147b0218d

Fixed in dev version
