### ISSUE TITLE
converter.py中的锁仓逻辑有一点小瑕疵可以改进

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2271]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.8
* vn.py版本: 如v2.0.8

## Issue类型
三选一：Enhancement

## 预期程序行为

使用锁仓模式的时候，在平仓的时候应该是没有可用昨仓了，才会通过反向开仓来锁仓。

## 实际程序行为

现在的converter对于是否有昨仓的判断存在一点小问题，会导致仍然有可用昨仓的情况下，程序不平昨仓而是直接反向开仓。
```
# If there is td_volume, we can only lock position
 if td_volume:
      req_open = copy(req)
      req_open.offset = Offset.OPEN
      return [req_open]
```

## 重现步骤

假设我的策略是IF股指期货日内策略，昨日进行了5手日内，昨收盘进行了锁仓操作，收盘仓位是5手空和5手多，净仓为0。

今日策略先发出8手做多的信号，converter会先平掉5手空头，然后再开3手多头。这时候的仓位是0手空，8手多（5手昨仓，3手今仓）。
不久，策略发出了8手做空的平仓信号，预期应该是先平掉5手昨天的多仓，然后再开3手今日的空仓，最终预期仓位是3手多仓，3手空仓。
此时目前的converter逻辑里面，因为多头有3手今仓，就只会开今仓来锁仓，所以就会变成直接开了8手今天的空仓。这时候仓位是8手空仓，8手多仓，虽然净仓还是0，但是却多了5手的保证金占用。

enchance其实也很简单，就是判断条件改为存在今仓并且无可用昨仓的时候，才转为反向开仓。
```
# If there is td_volume, we can only lock position
 if td_volume  and not yd_available:
      req_open = copy(req)
      req_open.offset = Offset.OPEN
      return [req_open]
```

**Comment by 1122455801** [comment]
![image](https://user-images.githubusercontent.com/45591222/71870746-0dfd3a00-3152-11ea-8d76-d0d845c35a3c.png)

在issues的测试案例【test】，下午检测到全部锁仓为【no】，然后先平仓5手，再开3手空仓。
但是中金所没有平昨指令，在这5手中，会优先平今仓3手，在平昨仓2手，触发平今惩罚。

而原来版本的逻辑避开了平今惩罚，故无需修改

**Comment by linbozhong** [comment]
> ![image](https://user-images.githubusercontent.com/45591222/71870746-0dfd3a00-3152-11ea-8d76-d0d845c35a3c.png)
> 
> 在issues的测试案例【test】，下午检测到全部锁仓为【no】，然后先平仓5手，再开3手空仓。
> 但是中金所没有平昨指令，在这5手中，会优先平今仓3手，在平昨仓2手，触发平今惩罚。
> 
> 而原来版本的逻辑避开了平今惩罚，故无需修改

我仔细查阅了中金所关于平今手续费的规则，确实是一旦新开了今仓，即使你有昨仓也都是优先按平今仓计算手续费。官方通告：
http://www.cffex.com.cn/hs300wd/20180202/21454.html

之前我是因为看vntrader的持仓列表里面的昨仓数据，有平仓就先扣减昨仓，现在回头看了一下gateway代码，中金所昨仓的判断就是直接总仓位减去今仓，因此可以理解为这个昨仓和今仓的区分是本地维护的，与交易所怎么判断你平今仓还是平昨仓是无关的。
另外还有一点，是因为之前查资料的时候，有看到一些期货公司网站是写有今仓和昨仓，优先平历史仓，就被这些错误信息给误导了。
原逻辑确实是对的，主要还是我业务不够熟悉，见笑了。

**Comment by linbozhong** [comment]
但是如果是上期所的合约的话，确实是可以通过平昨单优先把昨仓先全平掉，实际上还是能起到节省单边保证金的作用。所以是否需要就加个判断，如果是中金所就维持原来的逻辑，如果是先平历史仓的交易所，就可以采用先全部平历史仓再开新仓的逻辑。
我从飞马的api文档查询到的各交易所平今平昨平仓逻辑表：
![image](https://user-images.githubusercontent.com/8924839/71878748-61c64e00-3167-11ea-82cd-84c3c9954f51.png)

**Comment by 1122455801** [comment]
上期所没有锁仓的需要，只需要平今平昨即可。
附上上期所平今平昨图。
![image](https://user-images.githubusercontent.com/45591222/71947360-938ef180-3207-11ea-83f3-8ca7289006a0.png)
