### ISSUE TITLE
ib标的的tick时间如何获取到精确的北京时间

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2272]
* vn.py版本: 如v2.0.8发行版
三选一：Enhancement/Question

## 实际程序行为

群主，您好

IB标的，对于IDESLPRO的外汇EURUSD等，tick用的是当前电脑时间的now()的，这个生成K线的时候因为本地电脑时 间不准就会有几秒甚至几十秒的差异的了，即使每周对时也会有这个差异，因为没办法实现软件启动前自动对一次 时间的，操作系统是按照周自动对时的。
那么对于SMART的黄金，在ib接口中打印datetime和now()的时间，看了下（本地电脑对时了）会差2~5分钟的时间 的呢，那么就是SMART的黄金的时间也没办法百分之百的作为北京时间来处理了？
那么其他标的的时间是不是也都不能作为北京时间呢？

是否有更好的办法实现ib的标tick的时间按照北京时间一点儿也不差（要排除掉本地电脑时间和北京时间的差） 实现K线保存呢？

恳请指点下如何处理该问题，谢谢！

**Comment by vnpy** [comment]
仔细查了下文档：
1. IB的期货、股票等交易所品种，是提供成交数据推送的，所以可以直接使用成交时间戳作为行情记录
2. IB的黄金、外汇，是在其自己IDEALPRO的ECN系统上交易，只提供盘口报单更新，而没有任何成交记录推送
3. 因此，其时间戳就只能在每次收到更新时，使用一个本地时间戳了
4. 如果确实担心延时的问题，推荐每天定时做一次Windows系统同步，也就30秒的事情
