### ISSUE TITLE
 error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by moxiaoying** [vnpy/vnpy#2276]
## 环境

* 操作系统: Ubuntu 16.04
* Python版本: 3.7.4
* vn.py版本: 如v2.0.9

## Issue类型
三选一：Question
 gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBRIGAND_NO_BOOST_SUPPORT=1 -Ivnpy/api/oes/vnoes/include -Ivnpy/api/oes/vnoes/include/oes -I/root/anaconda3/include/python3.7m -c vnpy/api/oes/vnoes/generated_files/module.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/module.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from vnpy/api/oes/vnoes/include/c2py/c2py.hpp:6:0,
                     from vnpy/api/oes/vnoes/generated_files/module.cpp:8:
    vnpy/api/oes/vnoes/include/c2py/property_helper.hpp:5:23: fatal error: string_view: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ovk5oll5/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ovk5oll5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-owo8kgji/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

安装到最后一步时报错，请问该怎样解决此类问题

**Comment by Gwill** [comment]
应该是 gcc 版本太低了

**Comment by vnpy** [comment]
楼上正解，请使用Ubuntu 18.04以上版本

**Comment by dyzhou666** [comment]
我也遇到了同样的问题，系统Ubuntu 16.04，gcc升级到6.5还是不可行
