### ISSUE TITLE
关于策略的一些建议

### ISSUE THREAD

**Issue by sunnycomes** [vnpy/vnpy#228]
当前尽管一个策略能跑多个标的，但是参数都是一样的，这跟现实中有出入，因为不同的品种，即使选择相同算法，合适的参数往往也不尽相同。
如果按照当前程序的做法，需要copy这个策略，并且重命名，然后调整参数，最后把策略添加到配置文件，我有10个交易品种，就得copy10份，这就带来一个问题，如果我对算法进行了升级，如何做到高效的同步？
其实如果把策略抽象出来，把参数放到配置文件中，同一个策略，不同的参数，也可认为不同的策略，不知道这样理解可不可行，如果我对程序理解有误，还望见谅。

**Comment by vnpy** [comment]
理解有点偏差，目前是通过CTA_setting.json来实现实盘策略的参数配置的。实盘中，不同交易标的可以使用同一个策略类，只需要给不同的策略名就行。

至于CTA_setting.json，你可以写个.py的脚本来自动生成以及做参数安全性检测等等。
