### ISSUE TITLE
cannot import name 'black_76_cython' from 'vnpy.app.option_master.pricing' 

### ISSUE THREAD

**Issue by moxiaoying** [vnpy/vnpy#2282]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 16.04
* Python版本: 如python 3.7.2
* vn.py版本: 如v2.0.9发行版
## Issue类型
三选一：Question
进入~/vnpy-2.0.9/examples/vn_trader页面启动vnpy时报以下错误
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    from vnpy.app.option_master import OptionMasterApp
  File "/root/anaconda3/lib/python3.7/site-packages/vnpy/app/option_master/__init__.py", line 3, in <module>
    from .engine import OptionEngine, APP_NAME
  File "/root/anaconda3/lib/python3.7/site-packages/vnpy/app/option_master/engine.py", line 25, in <module>
    from .pricing import (
ImportError: cannot import name 'black_76_cython' from 'vnpy.app.option_master.pricing' (/root/anaconda3/lib/python3.7/site-packages/vnpy/app/option_master/pricing/__init__.py)

请问如何解决该问题。。。

**Comment by moxiaoying** [comment]
/app/option_master/pricing# ls
binomial_tree_cython.pyd  black_76.py               __init__.py
binomial_tree.py          black_scholes_cython.pyd  __pycache__
black_76_cython.pyd       black_scholes.py

在这个目录下是存在该文件的

**Comment by vnpy** [comment]
pyd文件是windows上的，linux上无法使用

cython定价模型的自动编译还没弄完，所以2.0.9先移除掉了
