### ISSUE TITLE
关于测试的一些建议

### ISSUE THREAD

**Issue by sunnycomes** [vnpy/vnpy#230]
参与这提交的代码中不少存在bug，但还是合并到了dev分支，开发还需规范，能否写一些测试用例，跑通了再提交合并。

**Comment by vnpy** [comment]
指的是哪次提交呢？

**Comment by sunnycomes** [comment]
已经提交fix,详见https://github.com/vnpy/vnpy/pull/233

**Comment by vnpy** [comment]
在PR里回复了
