### ISSUE TITLE
有支持macbook的客户端吗？

### ISSUE THREAD

**Issue by QCCS** [vnpy/vnpy#2303]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前没有，请使用一键安装脚本install_osx.sh来安装即可
