### ISSUE TITLE
CTA实盘运行策略，如何进行不同分钟周期的交易？

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#231]
例如每个5分钟K线才验证一次交易信号。现在只能通过实现策略中的OnTick事件处理函数，集成多个tick为想要的分钟周期，然后再做分钟信号交易？

**Comment by vnpy** [comment]
基于tick先聚合成分钟线，然后在onBar（分钟线回调）中再聚合成5分钟线

**Comment by zhangshuiyong** [comment]
好的，thx
