### ISSUE TITLE
CTA策略参数优化结果希望能导出成文本格式供后续查阅及记录

### ISSUE THREAD

**Issue by xukaide77** [vnpy/vnpy#2311]
## 环境

* 操作系统: Windows 7
* Python版本: 3.7
* vn.py版本: 2.0.9发行版

## Issue类型
三选一：Enhancement

## 预期程序行为
CTA策略参数优化结果能导出成文本格式供后续查阅

## 实际程序行为
参数优化结果只能截图保存

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已添加该功能到DEV分支
