### ISSUE TITLE
开盘开仓错误

### ISSUE THREAD

**Issue by liuagng** [vnpy/vnpy#2313]
## 环境

* 操作系统: Windows 7
VNStudio-2.0.8

## Issue类型
三选一：Bug

## 预期程序行为
正常开仓预期1手

## 实际程序行为
如果一开盘达到买卖点就会不正常，重复开仓。实际上持仓2手
日志上传不了，日志已经发给你了

**Comment by vnpy** [comment]
不好意思，找不到你提供的日志信息了...

建议这么处理：
1. 升级到2.0.9
2. 在交易代码中，检查你的状态控制是否有问题，开盘时由集合竞价进入连续交易，短时间内可能触发多次on_bar回调，如果委托频率高但控制状态机又过于简单，就可能导致重复下单
3. 简单的解决办法就是加个时间判断，比如只有bar.datetime超过9:30后才允许发出委托
