### ISSUE TITLE
条件订单在未达到触发价格时撮合成交（bybit接口）

### ISSUE THREAD

**Issue by numa2048** [vnpy/vnpy#2316]
## 环境

* 操作系统: 如Windows 2008 R2 Server（阿里云香港）
* Python版本: 3.7
* vn.py版本: v2.0.8

## Issue类型
Bug

## 预期程序行为
CTA趋势跟踪策略，在 bybit 接口运行，预期在价格 entry_up_price 上开多单，entry_down_price 下 开空单

## 实际程序行为
在entry_down_price 和entry_up_price 之间的价格上开了空单，条件单的触发价格并未达到

## 重现步骤
暂无法重现，具体信息见截图

针对Bug类型Issue，请提供具体重现步骤以及报错截图

<img width="259" alt="1" src="https://user-images.githubusercontent.com/55630044/73442050-0c104a80-438f-11ea-90a2-2cf0292e14c8.png">
<img width="322" alt="2" src="https://user-images.githubusercontent.com/55630044/73442061-116d9500-438f-11ea-8174-f0b4887670a7.png">
<img width="588" alt="3" src="https://user-images.githubusercontent.com/55630044/73442069-15011c00-438f-11ea-9467-c7b78259545a.png">
<img width="372" alt="4" src="https://user-images.githubusercontent.com/55630044/73442072-17637600-438f-11ea-866a-7d56f01f34ab.png">
<img width="990" alt="5" src="https://user-images.githubusercontent.com/55630044/73442080-19c5d000-438f-11ea-896d-b9e20309c51d.png">

**Comment by vnpy** [comment]
已修复
