### ISSUE TITLE
希望增加海外嘉信的接口

### ISSUE THREAD

**Issue by ShiganChu** [vnpy/vnpy#2317]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.6
* vn.py版本: v2.0.9发行版

## Issue类型
Enhancement

## 预期程序行为
希望能增加 Charles Schwab 的接口， Charles Schwab目前也零佣金了  https://www.tradesmax.com/component/k2/item/5512-free-trade

**Comment by vnpy** [comment]
搜了下，似乎Charles Schwab并没有提供公开的API服务？要申请成为其技术提供商才行，这意味着即使我们对接了（我们的开发账户能用），用户也没法直接用

**Comment by ShiganChu** [comment]
我看到plaid似乎包括嘉信  https://plaid.com/docs/    所以这个普通用户也没法直接用吗？
