### ISSUE TITLE
dev版运行option master报错

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2322]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: dev

## Issue类型
三选一：Bug

## 预期程序行为
None

## 实际程序行为
无法打开“__init__.pxd”: 无法读取文件(Error: 找不到文件(c:\users\lcxly\vnpy\__init__.pxd))。

## 重现步骤
python run.py

**Comment by vnpy** [comment]
dev分支尚未正式发布，需要测试请使用Windows 2019 Server
