### ISSUE TITLE
进行实盘策略运行的时候，无法设定数据推送的周期

### ISSUE THREAD

**Issue by taoyonggang** [vnpy/vnpy#2324]
## 环境

Windows 10或者Ubuntu 18.04
VNStudio-2.0.9
last master

## Issue类型
三选一：Bug

## 预期程序行为
进行实盘策略运行的时候，无法设定运行的周期。
哪怕程序已经强制设定1小时周期，但还是按分钟推送数据Bar
‘’‘
  self.bg = BarGenerator(self.on_bar,window=1,on_window_bar=self.on_bar,interval=Interval.HOUR)
  self.am = ArrayManager(150)
’‘’

## 实际程序行为
正常应该推送过来按小时数据排布的数据
如果按分钟的话，要自己合成，需要1个小时后才能正常进入工作状态

希望能增加周期设定

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by taoyonggang** [comment]
def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        """"""
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)
        #定义2个周期的bg函数
        self.bg5min = BarGenerator(self.on_bar,
                    window=5, 
                    on_window_bar=self.on_5min_bar, 
                    interval=Interval.MINUTE)

        self.bg1H = BarGenerator(self.on_bar,
                    window=1,
                    on_window_bar=self.on_1H_bar,
                    interval=Interval.HOUR)

        #定义2个周期的am
        self.am5min = ArrayManager(150)
        self.am1H = ArrayManager(150)

def on_tick(self, tick: TickData):
        """
        Callback of new tick data update.
        """
        self.bg1H.update_tick(tick)
        self.bg5min.update_tick(tick)

  def on_bar(self,bar:BarData):
        """k线更新,切记先更新长周期，再更新短周期"""
        self.bg1H.update_bar(bar)#将1小时K线合成1小时K线
        self.bg5min.update_bar(bar)#将1分钟K线合成5分钟K线


  def on_1H_bar(self, bar: BarData):
        """
        Callback of new bar data update.
        """    
        #self.cancel_all()

        print("Run begin hour...")

        self.am1H.update_bar(bar)
        if not self.am1H.inited:
            return  

        am1H = self.am1H
        
        print("Run in hour...")

**Comment by taoyonggang** [comment]
接入的okex永续合约数据

**Comment by taoyonggang** [comment]
不管怎样，实盘和回测最好能一致，本来回测时候用小时周期，运行好好的，结果一到实盘，强制变成1分钟基础周期，刚开始还不知道。知道后，想强制用小时数据，也用不起来，实盘谁会用1分钟跑啊，说明很少有人用。可能考虑换个量化平台了

**Comment by taoyonggang** [comment]
Traceback (most recent call last):
  File "D:\vnstudio\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\vnstudio\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\vnstudio\lib\site-packages\vnpy\app\cta_backtester\engine.py", line 172, in run_backtesting
    engine.run_backtesting()
  File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 276, in run_backtesting
    if self.datetime and data.datetime.day != self.datetime.day:
AttributeError: 'str' object has no attribute 'day'

分钟数据复盘的时候会出现这个错误

**Comment by taoyonggang** [comment]
下面程序，用demo改的，实盘也不工作，回测用分钟会报错的

from vnpy.app.cta_strategy import (
    CtaTemplate,
    StopOrder,
    TickData,
    BarData,
    TradeData,
    OrderData,
    BarGenerator,
    ArrayManager,
)


class MultiTimeframeStrategy2(CtaTemplate):
    """"""
    author = "用Python的交易员"

    rsi_signal = 20
    rsi_window = 14
    fast_window = 5
    slow_window = 20
    fixed_size = 1

    rsi_value = 0
    rsi_long = 0
    rsi_short = 0
    fast_ma = 0
    slow_ma = 0
    ma_trend = 0

    parameters = ["rsi_signal", "rsi_window",
                  "fast_window", "slow_window",
                  "fixed_size"]

    variables = ["rsi_value", "rsi_long", "rsi_short",
                 "fast_ma", "slow_ma", "ma_trend"]

    def __init__(self, cta_engine, strategy_name, vt_symbol, setting):
        """"""
        super().__init__(cta_engine, strategy_name, vt_symbol, setting)

        self.rsi_long = 50 + self.rsi_signal
        self.rsi_short = 50 - self.rsi_signal

        self.bg5 = BarGenerator(self.on_bar, 5, self.on_5min_bar)
        self.am5 = ArrayManager()

        self.bg30 = BarGenerator(self.on_bar, 30, self.on_30min_bar)
        self.am30 = ArrayManager()

    def on_init(self):
        """
        Callback when strategy is inited.
        """
        self.write_log("策略初始化")
        self.load_bar(10)

    def on_start(self):
        """
        Callback when strategy is started.
        """
        self.write_log("策略启动")

    def on_stop(self):
        """
        Callback when strategy is stopped.
        """
        self.write_log("策略停止")

    def on_tick(self, tick: TickData):
        """
        Callback of new tick data update.
        """
        self.bg5.update_tick(tick)

    def on_bar(self, bar: BarData):
        """
        Callback of new bar data update.
        """
        self.bg5.update_bar(bar)
        self.bg30.update_bar(bar)

    def on_5min_bar(self, bar: BarData):
        """"""
        self.cancel_all()

        print("5 min begin")

        self.am5.update_bar(bar)
        if not self.am5.inited:
            return
        
        print("5 min ready")

        if not self.ma_trend:
            return

        self.rsi_value = self.am5.rsi(self.rsi_window)

        if self.pos == 0:
            if self.ma_trend > 0 and self.rsi_value >= self.rsi_long:
                self.buy(bar.close_price + 5, self.fixed_size)
            elif self.ma_trend < 0 and self.rsi_value <= self.rsi_short:
                self.short(bar.close_price - 5, self.fixed_size)

        elif self.pos > 0:
            if self.ma_trend < 0 or self.rsi_value < 50:
                self.sell(bar.close_price - 5, abs(self.pos))

        elif self.pos < 0:
            if self.ma_trend > 0 or self.rsi_value > 50:
                self.cover(bar.close_price + 5, abs(self.pos))

        self.put_event()

    def on_30min_bar(self, bar: BarData):
        """"""
        print("30 min begin")
        self.am30.update_bar(bar)
        if not self.am30.inited:
            return

        print("30 min ready")

        self.fast_ma = self.am30.sma(self.fast_window)
        self.slow_ma = self.am30.sma(self.slow_window)

        if self.fast_ma > self.slow_ma:
            self.ma_trend = 1
        else:
            self.ma_trend = -1

    def on_order(self, order: OrderData):
        """
        Callback of new order data update.
        """
        pass

    def on_trade(self, trade: TradeData):
        """
        Callback of new trade data update.
        """
        self.put_event()

    def on_stop_order(self, stop_order: StopOrder):
        """
        Callback of stop order update.
        """
        pass

**Comment by vnpy** [comment]
实盘交易初始化时调用on_init函数，此时可以调用load_bar加载最近N天的数据用于初始化，如果最近N天数据不存在则策略需要等待实盘收到的推送TICK满足条件后，才能触发交易。

这块基础的使用方法请在微信公众号vnpy-community的入门教程中学习。
