### ISSUE TITLE
为什么套利回测时，需要设置long_cross_price > 0或short_cross_price > 0的条件？

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#2327]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
long_cross_price、short_cross_price 的值是spread的价格，而spread的价格是会出现<0的情况的，为什么需要设置long_cross_price > 0或short_cross_price > 0的条件？

## 实际程序行为
![image](https://user-images.githubusercontent.com/44016591/73901414-aa3f6b80-48cd-11ea-8374-d73769c5b4ee.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
其实这里的过滤写错了，本来是要过滤没有挂单的情况，CTP接口没有挂单价格实际打印出来的价格是int32最大浮点数但是GUI里面显示的是0。我这里过滤改的是long_cross_price > 9999999 or short_cross_price > 9999999

**Comment by vnpy** [comment]
已修复，非常感谢
