### ISSUE TITLE
loadbar 在交易所数据有限的情况，只能装载部分数据，造成实盘交易迟迟不能启动

### ISSUE THREAD

**Issue by taoyonggang** [vnpy/vnpy#2328]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
1、尝试获取交易所数据，并判断是否满足预订数量
2、如果数量不满足，就尝试装载本地数据

## 实际程序行为
只要交易所有数据，不管满足不满足要求，就直接不再装载本地数据。
这样造成大周期策略迟迟不能运行。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

我已经修复了，你们对应修改下就可以。

**Comment by taoyonggang** [comment]
最新版已经修复

**Comment by sdmovie** [comment]
这里有个潜在风险， 就是本地数据和交易所数据之间是否能无缝接续。比如你在盘中启动策略，需要的loadbar是当日已发生部分和昨日及以前的历史数据合并起来。尽量能在单一源获取最好

**Comment by vnpy** [comment]
请参考：#2362
