### ISSUE TITLE
english version

### ISSUE THREAD

**Issue by authenticfake** [vnpy/vnpy#2330]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Is it possibile to have a english version on what you have done so far?
thanks a lot
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
We do had a plan to provide English version at the start of 2020. So far there are too many other works need to be done for Chinese financial markets. Therefore we have to delay this plan for the moment.

**Comment by jcsena** [comment]
It would be nice to have 👍🏼 . @vnpy

**Comment by Otnicka1** [comment]
Hello, 
Any update @vnpy  ?
