### ISSUE TITLE
希望移植Vnpy LTS版的VN Trader界面双击填充功能

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#2336]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
希望移植Vnpy LTS版的VN Trader界面双击填充功能，例如：
双击品种或者双击持仓，在下单界面自动填充对应字段

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
#2336
