### ISSUE TITLE
ctaBackBesting.py，CTA运行回测，用下一个Bar来撮合上一个Bar的订单，判断是否成交是否有点问题？

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#234]
在Bar模式中，CTA运行回测过程中，每一个Bar调用newBar函数一次，先撮合订单，再运行Bar。如果在上一根Bar的开盘价或者收盘价下了订单，CTA回测框架是用下一个Bar的OHLC价格来撮合订单。
例如，如果用上一个Bar的开盘价100开多，上一个Bar的最高价是110，就应该成交阿。上一个Bar的收盘价是95.但是回测中用下一个Bar的OHLC价来撮合，下一个Bar的最高价99，这样上个Bar用开盘价下的订单的价格100比下一个Bar的最高价99低，回测框架判断为不成交！！！这样会导致回测结果有问题

def runBacktesting(self):
        """运行回测"""
        # 载入历史数据
        self.loadHistoryData()
        
        # 首先根据回测模式，确认要使用的数据类
        if self.mode == self.BAR_MODE:
            dataClass = CtaBarData
            func = self.newBar
        else:
            dataClass = CtaTickData
            func = self.newTick

        self.output(u'开始回测')
        
        self.strategy.inited = True
        self.strategy.onInit()
        self.output(u'策略初始化完成')
        
        self.strategy.trading = True
        self.strategy.onStart()
        self.output(u'策略启动完成')
        
        self.output(u'开始回放数据')

        for d in self.dbCursor:
            data = dataClass()
            data.__dict__ = d
            func(data)     
            
        self.output(u'数据回放结束')
        
    #----------------------------------------------------------------------
    def newBar(self, bar):
        """新的K线"""
        self.bar = bar
        self.dt = bar.datetime
        self.crossLimitOrder()      # 先撮合限价单
        self.crossStopOrder()       # 再撮合停止单
        self.strategy.onBar(bar)    # 推送K线到策略中

 #----------------------------------------------------------------------
    def crossLimitOrder(self):
        """基于最新数据撮合限价单"""
        # 先确定会撮合成交的价格
        if self.mode == self.BAR_MODE:
            buyCrossPrice = self.bar.low        # 若买入方向限价单价格高于该价格，则会成交
            sellCrossPrice = self.bar.high      # 若卖出方向限价单价格低于该价格，则会成交
            buyBestCrossPrice = self.bar.open   # 在当前时间点前发出的买入委托可能的最优成交价
            sellBestCrossPrice = self.bar.open  # 在当前时间点前发出的卖出委托可能的最优成交价
        else:
            buyCrossPrice = self.tick.askPrice1
            sellCrossPrice = self.tick.bidPrice1
            buyBestCrossPrice = self.tick.askPrice1
            sellBestCrossPrice = self.tick.bidPrice1
        
        # 遍历限价单字典中的所有限价单
        for orderID, order in self.workingLimitOrderDict.items():
            # 判断是否会成交
            buyCross = order.direction==DIRECTION_LONG and order.price>=buyCrossPrice
            sellCross = order.direction==DIRECTION_SHORT and order.price<=sellCrossPrice
            
            # 如果发生了成交
            if buyCross or sellCross:
                # 推送成交数据
                self.tradeCount += 1            # 成交编号自增1
                tradeID = str(self.tradeCount)
                trade = VtTradeData()
                trade.vtSymbol = order.vtSymbol
                trade.tradeID = tradeID
                trade.vtTradeID = tradeID
                trade.orderID = order.orderID
                trade.vtOrderID = order.orderID
                trade.direction = order.direction
                trade.offset = order.offset
                
                # 以买入为例：
                # 1. 假设当根K线的OHLC分别为：100, 125, 90, 110
                # 2. 假设在上一根K线结束(也是当前K线开始)的时刻，策略发出的委托为限价105
                # 3. 则在实际中的成交价会是100而不是105，因为委托发出时市场的最优价格是100
                if buyCross:
                    trade.price = min(order.price, buyBestCrossPrice)
                    self.strategy.pos += order.totalVolume
                else:
                    trade.price = max(order.price, sellBestCrossPrice)
                    self.strategy.pos -= order.totalVolume
                
                trade.volume = order.totalVolume
                trade.tradeTime = str(self.dt)
                trade.dt = self.dt
                self.strategy.onTrade(trade)
                
                self.tradeDict[tradeID] = trade
                
                # 推送委托数据
                order.tradedVolume = order.totalVolume
                order.status = STATUS_ALLTRADED
                self.strategy.onOrder(order)
                
                # 从字典中删除该限价单
                del self.workingLimitOrderDict[orderID]
                
    #----------------------------------------------------------------------
    def crossStopOrder(self):
        """基于最新数据撮合停止单"""
        # 先确定会撮合成交的价格，这里和限价单规则相反
        if self.mode == self.BAR_MODE:
            buyCrossPrice = self.bar.high    # 若买入方向停止单价格低于该价格，则会成交
            sellCrossPrice = self.bar.low    # 若卖出方向限价单价格高于该价格，则会成交
            bestCrossPrice = self.bar.open   # 最优成交价，买入停止单不能低于，卖出停止单不能高于
        else:
            buyCrossPrice = self.tick.lastPrice
            sellCrossPrice = self.tick.lastPrice
            bestCrossPrice = self.tick.lastPrice
        
        # 遍历停止单字典中的所有停止单
        for stopOrderID, so in self.workingStopOrderDict.items():
            # 判断是否会成交
            buyCross = so.direction==DIRECTION_LONG and so.price<=buyCrossPrice
            sellCross = so.direction==DIRECTION_SHORT and so.price>=sellCrossPrice
            
            # 如果发生了成交
            if buyCross or sellCross:
                # 推送成交数据
                self.tradeCount += 1            # 成交编号自增1
                tradeID = str(self.tradeCount)
                trade = VtTradeData()
                trade.vtSymbol = so.vtSymbol
                trade.tradeID = tradeID
                trade.vtTradeID = tradeID
                
                if buyCross:
                    self.strategy.pos += so.volume
                    trade.price = max(bestCrossPrice, so.price)
                else:
                    self.strategy.pos -= so.volume
                    trade.price = min(bestCrossPrice, so.price)                
                
                self.limitOrderCount += 1
                orderID = str(self.limitOrderCount)
                trade.orderID = orderID
                trade.vtOrderID = orderID
                
                trade.direction = so.direction
                trade.offset = so.offset
                trade.volume = so.volume
                trade.tradeTime = str(self.dt)
                trade.dt = self.dt
                self.strategy.onTrade(trade)
                
                self.tradeDict[tradeID] = trade
                
                # 推送委托数据
                so.status = STOPORDER_TRIGGERED
                
                order = VtOrderData()
                order.vtSymbol = so.vtSymbol
                order.symbol = so.vtSymbol
                order.orderID = orderID
                order.vtOrderID = orderID
                order.direction = so.direction
                order.offset = so.offset
                order.price = so.price
                order.totalVolume = so.volume
                order.tradedVolume = so.volume
                order.status = STATUS_ALLTRADED
                order.orderTime = trade.tradeTime
                self.strategy.onOrder(order)
                
                self.limitOrderDict[orderID] = order
                
                # 从字典中删除该限价单
                del self.workingStopOrderDict[stopOrderID]

**Comment by vnpy** [comment]
不好意思你的描述没能看懂，不过现在vn.py的K线回测模式的原理简单解释下：
1. 每根K线走完后，会触发策略的onBar
2. 策略发单时，是在上一根K线走完的时候发
3. 这样发出的委托，最快只能在下一根K线运行的过程中成交
4. 所以做模拟撮合的时候，必须用后续的K线来判断

如果用当根K线来撮合，那么直接就是逻辑上的错误了。

**Comment by zhangshuiyong** [comment]
就是说，现在的回测框架是用收盘价下单才是逻辑完善。如果我用当前的Bar的开盘价下单，用下一个bar的价格去撮合。但是开盘价到下一个bar的价格可能撮合不了。就是说一直不会达成成交。那么回测中，如果下单的前提，对仓位有判断，仓位没有成交，以后的信号出来，也不会再下单。就会导致不准确。

**Comment by akeyong** [comment]
@vnpy， 针对发出的开多委托（委托价格为当根k线的收盘价），如果下一根k线的最低价都比这个委托价高度话（即出现一个向上缺口），这个委托单会最终被cancel掉无法成交，这样理解对吗？

另外，在下面的策略程序文件里面，为了保证成交，选择超价5个整指数点下单，这在实盘中，当卖一价格低于委托价，会以当时的卖一价格来撮合成交的；但是在回测中，因为是用下一个K线的OHLC来撮合成交的，因此只要下一根k线的开盘价是高于这个委托价的话，并且最低价低于这个委托价的话，撮合价格就是超价5个整指数点来撮合成交的，因此可以把这个5个整指数点理解为回测滑点？

# 当前无仓位
        if self.pos == 0:
            self.intraTradeHigh = bar.high
            self.intraTradeLow = bar.low

            # ATR数值上穿其移动平均线，说明行情短期内波动加大
            # 即处于趋势的概率较大，适合CTA开仓
            if self.atrValue > self.atrMa:
                # 使用RSI指标的趋势行情时，会在超买超卖区钝化特征，作为开仓信号
                if self.rsiValue > self.rsiBuy:
                    # 这里为了保证成交，选择超价5个整指数点下单
                    self.buy(bar.close+5, self.fixedSize)

                elif self.rsiValue < self.rsiSell:
                    self.short(bar.close-5, self.fixedSize)

**Comment by vnpy** [comment]
@zhangshuiyong 

理解有点错误，回测中，当你收到某个bar的推送时，这个bar已经走完了，所以你永远不能在某个bar的开始时发单，只能在上一个bar走完时发单（尽管实盘时这两个时间点是重合的），回测中必须通过这种区分才能完全杜绝未来函数的存在（你永远看不到还没发生的数据）。

另外ctaAlgo模块的回测功能，是用来验证你的策略代码的实盘运行效果和回测是否一致。如果需要做初期的策略雏形开发，建议自己写脚本去做，可以有最大的自由度。

**Comment by vnpy** [comment]
@akeyong 

1. 针对发出的开多委托（委托价格为当根k线的收盘价），如果下一根k线的最低价都比这个委托价高度话（即出现一个向上缺口），这个委托单会最终被cancel掉无法成交，这样理解对吗？

没错

2. 另外，在下面的策略程序文件里面，为了保证成交，选择超价5个整指数点下单，这在实盘中，当卖一价格低于委托价，会以当时的卖一价格来撮合成交的；但是在回测中，因为是用下一个K线的OHLC来撮合成交的，因此只要下一根k线的开盘价是高于这个委托价的话，并且最低价低于这个委托价的话，撮合价格就是超价5个整指数点来撮合成交的，因此可以把这个5个整指数点理解为回测滑点？

“下一根k线的开盘价是高于这个委托价的话，并且最低价低于这个委托价的话”，这个情况出现的概率非常非常低，所以造成的误差基本可以忽略。

滑点有单独的setSlippage可以设置，这里如果真出现了你说的情况，会有5个整指数点的额外成本。

strategyAtrRsi更多也只是用来展示的一个策略，可以跑着试试，但其中的很多交易时状态管理还远没有达到实盘的安全性，需要用户自己去完善。我受限制于公司合规的关系，无法分享更详细的策略代码出来。

**Comment by zhangshuiyong** [comment]
@vnpy 规避未来函数，可以用bar的开盘价和收盘价下单，如果用收盘价下单，是应该到下一个bar去成交。但是有些策略是要用开盘价下单的。

**Comment by akeyong** [comment]
@vnpy tnx!

**Comment by vnpy** [comment]
@zhangshuiyong 能举个例子描述下是怎样的情况吗？

**Comment by zhangshuiyong** [comment]
举个例子：一个策略需要开盘价open买入，用的是真实的通达信数据日线数据。现在回测框架是下一日才撮合成交。但是实际上当天就要成交。这就是现在CTA回测的问题，不能反映那些以开盘价下单的策略的真实交易情况

**Comment by wzy2009520** [comment]
个人感觉vnpy的回测更偏向于交易向，更偏重于实际交易遇到的情况，日线级别的回测或许更改回测框架更合适一些？而不是将日线的数据导入数据库然后使用CTA的回测框架？

**Comment by vnpy** [comment]
@zhangshuiyong ctaAlgo模块整体上还是为了比较中高频的策略设计的，日线级别策略的回测建议还是直接写脚本。如果你一定要用，可以基于分钟线级别的数据来做回测（指标等方面自己通过分钟线聚合为日线来算），这样开盘第一分钟获取到当日开盘价后，可以在第二分钟就买入。

**Comment by vnpy** [comment]
@wzy2009520 没错，vn.trader整个设计都是为了交易，不是为了策略研究（模型开发、回测、优化）。ctaAlgo里的回测和优化功能是为了用来验证你的策略代码是否在事件驱动框架下能和之前用脚本回测做的结果一致。

**Comment by zhangshuiyong** [comment]
@vnpy 好的，了解了。
