### ISSUE TITLE
安装完毕后，运行脚本run.py报错

### ISSUE THREAD

**Issue by scolo111** [vnpy/vnpy#2349]
## 环境

* 操作系统: manjaro
* Python版本: python3 3.8.1
* vn.py版本: v2.1 2020/2/17

## Issue类型
三选一：Bug

## 预期程序行为
安装完成后，执行 `python run.py` . 期待启动VS station

## 实际程序行为
> Traceback (most recent call last):
  File "run_git.py", line 3, in <module>
    from vnpy.trader.ui import MainWindow, create_qapp
  File "/home/scolo/.local/lib/python3.8/site-packages/vnpy/trader/ui/__init__.py", line 11, in <module>
    from .mainwindow import MainWindow
  File "/home/scolo/.local/lib/python3.8/site-packages/vnpy/trader/ui/mainwindow.py", line 28, in <module>
    from .editor import CodeEditor
  File "/home/scolo/.local/lib/python3.8/site-packages/vnpy/trader/ui/editor.py", line 4, in <module>
    from PyQt5 import QtWidgets, Qsci, QtGui
ImportError: /usr/lib/python3.8/site-packages/PyQt5/Qsci.abi3.so: undefined symbol: __cxa_throw_bad_array_new_length, version Qt_5

**Comment by cbogithub** [comment]
Try python 3.7

**Comment by scolo111** [comment]
用conda 把pyhton 降为 3.7 后，执行 install.sh . 出现了其他错误

>......  
build/temp.linux-x86_64-3.7/talib/_ta_lib.o: file not recognized: file format not recognized
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
   ERROR: Failed building wheel for ta-lib

>...... 
ERROR: Command errored out with exit status 1: /home/scolo/Software/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/tmp/pip-install-wcqmqz02/ta-lib/setup.py'"'"'; __file__='"'"'/var/tmp/pip-install-wcqmqz02/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /var/tmp/pip-record-mykpam6u/install-record.txt --single-version-externally-managed --compile --install-headers /home/scolo/Software/miniconda3/include/python3.7m/ta-lib Check the logs for full command output.

>......   
 build/temp.linux-x86_64-3.7/psycopg/psycopgmodule.o: file not recognized: file format not recognized
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ERROR: Failed building wheel for psycopg2

**Comment by vnpy** [comment]
1. 请使用Python 3.7
2. Linux需要先安装gcc
3. install.sh是为Ubuntu系统编写的，其他系统请自行编写相关脚本，主要是安装命令
4. 目前官方只支持Ubuntu了
