### ISSUE TITLE
建议目录结构调整

### ISSUE THREAD

**Issue by firememory** [vnpy/vnpy#235]
建议根目录下新建一个新目录专门存放接口封装的代码（vn.ctp, vn.femas）取名 如 warpper之类的。。。

**Comment by mangox** [comment]
赞同，可以取名vn.api， 可以简化目录结构，部分用户只需要trader下的内容
FAQ
vn.api
vn.trader
...

**Comment by firememory** [comment]
嗯嗯，这样会清晰一些
同样， vn.trader 目录下面的 一些 *Gateway 也放到一个Gateway目录下去。

**Comment by vnpy** [comment]
确实也有这个计划，目前接口越来越多了。

**Comment by akeyong** [comment]
@firememory , 好建议！

**Comment by vnpy** [comment]
已完成
