### ISSUE TITLE
实时K线图表模块

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2350]
## 环境
* vn.py版本: 如v2.1.0
三选一：Enhancement

## 实际程序行为
群主，您好

实时K线图表，是否可以把图表上的标的“IF2002.CFFEX”显示在图表的右上角（在K线图图表内），这样可以节省下屏幕空间，谢谢！

期待“实时K线图表模块”能够实现动态添加指标、多指标在同一个图表中叠加......等功能的【超级“实时K线图表模块”】，碾压市面上所有的行情软件的K线图表功能，期待中......。
感谢！
酒香不怕巷子深！静待花开！

也请其他有这方面需求的交易者、伙伴们尽快提出更多优秀的点子，谢谢！

**Comment by sdmovie** [comment]
https://blog.csdn.net/MAILLIBIN/article/details/99654762?utm_source=distribute.pc_relevant.none-task 用pyechart就能做出蛮好的带指标，可缩放的K线图； 另外有个HQchart的也不错。

**Comment by stone3536** [comment]
群主，您好
k线图这个，是否可以考虑除了加上可以灵活的更换标的、切换时间周期以及添加指标外，是否可以像ib的一样在最右边可以根据tick时时显示当前的价格变动情况？

谢谢！
截图如下：
![微信图片_20200225173447](https://user-images.githubusercontent.com/31505150/75234338-63220780-57f5-11ea-96f1-8a9d4f59976a.png)

**Comment by vnpy** [comment]
右侧显示Tick实时价格的功能，已在社区线上分享中提供了实现方案：https://appszu5scwd6134.h5.xiaoeknow.com/v1/course/alive/l_5e417f0d405c7_1WgLyxPz?type=2&app_id=appSzu5scwd6134&is_redirect=1

其他扩展暂无计划。
