### ISSUE TITLE
断线重连后，已有订阅的数据不会刷新，好像没有重新订阅。造成行情记录和实盘不工作

### ISSUE THREAD

**Issue by taoyonggang** [vnpy/vnpy#2355]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.1.0
* vn.py版本: 所有现有版本

## Issue类型
三选一：Bug

## 预期程序行为
断线重连后，重新订阅已有数据，让实盘和数据记录能继续工作

## 实际程序行为
断线重连后，主界面实时行情不再刷新，数据记录也停止工作

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by taoyonggang** [comment]
这个会造成CTA实盘停止

**Comment by vnpy** [comment]
请具体说明用的什么接口？

**Comment by taoyonggang** [comment]
okex永续合约。今天又断了，不能恢复

**Comment by vnpy** [comment]
DEV分支已经修复了，手动更新下okex的三个gateway或者等下个版本即可

**Comment by taoyonggang** [comment]
谢谢
