### ISSUE TITLE
UI界面[交易模块]，期望恢复1.x的功能

### ISSUE THREAD

**Issue by msincenselee** [vnpy/vnpy#2356]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Enhancement

## 预期程序行为
1、价格可设置跟随tick变动
2、双击行情的任意合约，自动更新交易界面的合约/交易所/价格等
3、输入symbol合约，如果和交易所不一致，最好能自动更正交易所

**Comment by vnpy** [comment]
已修改，将币安现货接口改为使用小写代码

**Comment by vnpy** [comment]
已修改完成
