### ISSUE TITLE
Mac选择交易所的输入框展示异常

### ISSUE THREAD

**Issue by Ged0** [vnpy/vnpy#2359]
## 环境

* 操作系统: macOS 10.15.3
* Python版本: 3.7.5
* vn.py版本: master分支

## Issue类型
Bug

## 预期程序行为
选择交易所等界面有异常, 选中的选项特别大

## 重现步骤

Mac下打开examples/vn_trader这个例子, 直接就有这个问题了.
![mac_vnpy_error](https://user-images.githubusercontent.com/4569451/74997858-1c997980-5492-11ea-8233-af0a7308a704.png)

**Comment by vnpy** [comment]
查了下这个是PyQt底层库的问题，暂时没办法了

**Comment by dev-kang** [comment]
> ## 环境
> * 操作系统: macOS 10.15.3
> * Python版本: 3.7.5
> * vn.py版本: master分支
> 
> ## Issue类型
> Bug
> 
> ## 预期程序行为
> 选择交易所等界面有异常, 选中的选项特别大
> 
> ## 实际程序行为
> ## 重现步骤
> Mac下打开examples/vn_trader这个例子, 直接就有这个问题了. ![mac_vnpy_error](https://user-images.githubusercontent.com/4569451/74997858-1c997980-5492-11ea-8233-af0a7308a704.png)

这个问题有解决吗？ 目前也遇到这样的问题比较苦恼，而且有的地方显示不全，或者不显示
