### ISSUE TITLE
EmailEngine中send_mail里的receiver没写对

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#2360]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.1.0
## Issue类型
三选一：Bug

msg["to"] = SETTINGS["email.receiver"]
应该改为：
msg["to"] = receiver

**Comment by vnpy** [comment]
已修复，非常感谢
