### ISSUE TITLE
OKEX交易所loadbar 在交易所数据有限的情况，只能装载部分数据，造成实盘交易迟迟不能启动

### ISSUE THREAD

**Issue by wangdalei001** [vnpy/vnpy#2362]
## 环境

* 操作系统: 如Windows 10

* vn.py版本: v2.10

## Issue类型
三选一：Enhancement

## 预期程序行为
初始化之后，下载的数据足够多，可以马上交易

## 实际程序行为
初始化之后，下载的数据不足，不能马上交易

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
在OKEX交易的时候，修改query_history函数，改为从onetoken下载历史数据

**Comment by vnpy** [comment]
已有解决方案：
1. 请使用DataRecorder录制数据后
2. 在策略中调用load_bar函数时，传入可选参数use_database=True，强制使用本地数据库的数据

**Comment by wangdalei001** [comment]
收到，谢谢陈总！
