### ISSUE TITLE
fix "order amount precision error, scale: `0`"

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2363]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

when send order with (volume=11063) , vnpy will convert it to float (volume=11063.0)  ==> got erorr : 
Commission Request error, code：order-orderamount-precision-error，information：order amount precision error, scale: `0`

how to fix : 
add to line  129 in  utility.py :  
```
	r_split = str(rounded)

	if r_split.split(".")[1] == '0' :
		rounded = int(rounded)
```

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这个问题应该在接口层修改，即在下单时将数量转换为整数，而不应该在utility中提供的函数中修改
