### ISSUE TITLE
关于套利模块的两个建议

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#2364]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

1.algo定时撤单里，只检查check_order_finished，会出现主动腿已成交，而被动腿还在等待成交的情况，这时候直接撤单会导致单腿风险，两腿仓量不对称的情况。
最好在检查时，如果判断active_leg已成交，则重发passive_leg的单子 或者 平掉active_leg的仓 或者 返回单腿成交的状态，让用户在策略里自行处理。

    def on_interval(self):
        """"""
        if not self.check_order_finished():
            self.cancel_all_order()

    def check_order_finished(self):
        """"""
        finished = True

        for leg in self.spread.legs.values():
            vt_orderids = self.leg_orders[leg.vt_symbol]

            if vt_orderids:
                finished = False
                break

        return finished

2.建议优化load_data（load_bar_data, load_tick_data的部分，直接读取leg_data，然后推送给策略，在策略里进行合成spread_bar。

相比在load_bar_data里直接合成spread_bar再返回，这样有两个好处，
第一个是更好的计算成本。
成本估算是套利策略设计和仿真回测策略里很重要的一环，需要对各leg进行分别设置成本参数和计算成交情况。
而目前直接用spread_bar来模拟成交，其中成交额是粗略估算，cross_algo里的成交也是直接用spread_bar来模拟成交的，与真实的各腿各自成交还是有差距。

第二个是利于实现协整策略等需要动态调整的price_multiplier的策略。
可以在策略里自行合成动态spread，而不是直接推一个固定price_multiplier的spread.

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
因为涉及的内容有点复杂拖了比较久：
1. 每一轮到时间限制撤单后，在下一个价差tick到来时触发的逻辑里，会检查当前主动腿和被动腿的状态，如果不平衡会立即再次对冲，所以只要正常运行算法，不会存在长时间的瘸腿风险（瞬时几秒内对冲失败是有可能的）
2. 同样这块的逻辑已经在SpreadTrading的回测中实现了，如果确实需要加载各条腿的原始数据进行回测，可以使用PortfolioStrategy模块来实现
