### ISSUE TITLE
 BarGenerator 合成小时线BUG

### ISSUE THREAD

**Issue by qmzhn** [vnpy/vnpy#2365]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 2.0.9
* 文件路径: vnpy/vnpy/trader/utility.py
## Issue类型
三选一：Bug

## 预期程序行为
1分钟线合成1小时线，class BarGenerator合成正确的BAR

## 实际程序行为
在interval=Interval.HOUR，执行update_bar，当遇到bar.datetime=datetime.datetime(2020, 1, 13, 22, 59,0)切换到bar.datetime=datetime.datetime(2020, 1, 14, 9, 0,0)这样的情况时，由于self.last_bar没有清空，导致
self.last_bar and bar.datetime.hour != self.last_bar.datetime.hour为True，这样会生成一条bar.datetime=datetime.datetime(2020, 1, 14, 9, 0)的错误小时线，此条bar的实际数据为bar.datetime=datetime.datetime(2020, 1, 14, 9, 0,0)的分钟线数据

## 目前我的解决方法
把280行-286行改成这样

`        self.last_bar = bar`
       `if finished:`
            `    　self.on_window_bar(self.window_bar)`
             ` 　self.window_bar = None`
           ` 　self.last_bar = None`

**Comment by xldistance** [comment]
我改了试下没区别的
