### ISSUE TITLE
[ enhancement ]add Scroll for long CTA setting (GUI)

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2370]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

find : class SettingEditor(QtWidgets.QDialog): (line 393) in app\cta_strategy\ui\widget.py

in  def init_ui(self):  add below line (form = QtWidgets.QFormLayout())

```
screen = QtGui.QDesktopWidget().screenGeometry()
        scroll = QtWidgets.QScrollArea()
        scroll.setMinimumHeight(screen.height())
        # scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        groupBox = QtWidgets.QGroupBox("CTA Strategy Setting")
        scroll.setWidgetResizable(True)
```

replace : self.setLayout(form) with 

```
        groupBox.setLayout(form)
        scroll.setWidget(groupBox)
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(scroll)

```

![image](https://user-images.githubusercontent.com/9572613/75641055-93402f00-5c69-11ea-8d01-eaac55ccba96.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修改
