### ISSUE TITLE
No module named 'vnpy.api.ctp.vnctpmd'

### ISSUE THREAD

**Issue by yuud** [vnpy/vnpy#2377]
## 环境

* 操作系统: mac
* Python版本: python3
* vn.py版本:  v2.1.0     20200301（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
无报错

## 实际程序行为
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'

## 重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
MAC上不支持CTP接口，下周我们会在vnpy-community微信公众号上一篇关于交易接口的介绍，欢迎关注
