### ISSUE TITLE
IB 官方现在提供了Python3支持，是否考虑在这个基础上做？

### ISSUE THREAD

**Issue by 4ever911** [vnpy/vnpy#238]
IbPython3 provides a native Python 3 implementation of the Interactive Brokers API software (version 9.70), allowing traders and investors to use Python's command line console to interact with Interactive Brokers via the IB Gateway or IB Trader Workstation platforms.

**Comment by vnpy** [comment]
考虑到一些其他的原因，vn.py暂时还不会升级到Python 3，所以目前会继续用vn.ib。如果IB官方接口有了2的版本，或者出了个Python 3的JIT，那么肯定会换过去。
