### ISSUE TITLE
建议linux操作系统使用fork进行多进程optimize

### ISSUE THREAD

**Issue by cainiaocome** [vnpy/vnpy#2381]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.6
* vn.py版本: 2.1.0.1

## Issue类型
三选一：Enhancement

## 预期程序行为
在cta_strategy app下面的backtesting.py中，多进程optimize的时候，根据操作系统选择使用spawn或者fork，linux的fork比spawn更快并且问题更少
直接取消指定启动方式即可，[python可以自动根据操作系统采用不同的启动方式](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context)

## 实际程序行为
linux下面也是用的spawn，会慢一些，并且如果对vnpy进行了monkey patch，采用spawn启动进程会导致patch失效

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
之前采用的fork模式，会导致MySQL等数据库的连接，因为无法扩进程共享出现问题，所以改为了spawn模式
