### ISSUE TITLE
小时线的行为和分钟线的行为不统一，小时线结尾并非59分钟，而是60分钟

### ISSUE THREAD

**Issue by maxsonic** [vnpy/vnpy#2383]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
合成5分钟数据的时候，假设是9：00开始，实际上用的数据是9:00到9:04的数据。
那么合成小时线数据的时候，假设是9：00开始，实际上也应该用9:00到9:59的数据

## 实际程序行为
合成5分钟数据，的确用的9:00到9:04的数据
而小时线则是用的9:01到10:00的数据

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
从代码可以看出，minute实际上有一个提前量，比如5分钟，实际上第4分钟的时候就结束了，直接合成。
但是小时线则是过了那个小时之后，才合成小时线。
![image](https://user-images.githubusercontent.com/1520489/76306924-c0907b00-6302-11ea-847c-6b3428119667.png)

**Comment by vnpy** [comment]
5分钟线，举个例子是从9:00:00到9:04:59，这个5分钟内的数据合成的，所以是9:00到9:04。

**Comment by maxsonic** [comment]
5分钟是对的，但是1小时是错的，一小时用的是9：01-10：00

**Comment by hadrianl** [comment]
09:00-09:59 ---> 09:00:00-09:59:59

**Comment by maxsonic** [comment]
@hadrianl ， @vnpy 
从代码可以看出来，是10：00的时候去合成的，而不是9:59。分钟合成的时候，用minute + 1 % window，提前了1分钟去判断。而hour的时候，是hour不同的时候判断，实际上已经过线了。
我看vnpy的设计，9：00代表9：00：00-9：00：59，所以如果是统一的话，5分钟就是9:00:00到9:04:59，一小时就是9：00到9：59：59。
但是实际上判断hour不同的时候，已经在10：00：00时刻了，最后变成了9:01:10:00。
9:59的时候，hour不是10，所以小时线没有生成，到了10：00，hour不同，所以小时线生成。

**Comment by hadrianl** [comment]
你把update tick的逻辑结合一起看吧，注意看last_bar和bar的变化

**Comment by qmzhn** [comment]
这个是有过线的BUG，需要你自己重写一下BarGenerator的update_bar方法！
