### ISSUE TITLE
富途gateway已连接，可查询代码，但不可以订阅对应代码的行情。

### ISSUE THREAD

**Issue by MaoChen1980** [vnpy/vnpy#2389]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.1
* vn.py版本: 如v2.1.1

## Issue类型
三选一：Bug

## 预期程序行为

gateway 是富途，登录正常，可以看到持仓，资金，委托，成交。等等记录

在交易 TAB ,选择交易所，输入代码。回车，显示代码对应的名字， 并在在行情tab 显示对应代码实时行情

## 实际程序行为
在交易 TAB ,选择交易所，输入代码。回车，显示代码对应的名字， 但是在行情tab 并没有显示对应代码实时行情

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请附上你操作的截图

**Comment by MaoChen1980** [comment]
![fb](https://user-images.githubusercontent.com/5670446/77061563-66379e80-6a15-11ea-8390-072b403361d6.png)

**Comment by vnpy** [comment]
富途去年就把美股的API交易功能关掉了......
