### ISSUE TITLE
希望支持python 3.X

### ISSUE THREAD

**Issue by jandykwan** [vnpy/vnpy#239]
希望可以增加支持python 3.X。 非常感谢。

**Comment by vnpy** [comment]
短期内不会支持3，原因如下：
1. Python 3.6的虚拟机比起之前3.5有了很大的提升，但是比起2.7没有质的飞跃
2. 依旧有不少量化工作中使用到的库，对于Python 3尚未全面支持

现在也比较担心社区的分裂，眼下最为重要的是Python的JIT实现，预测推出JIT的版本会更好的引领Python未来的发展，如果3上推出了JIT的话我会立即开始移植的工作。
