### ISSUE TITLE
可以作为服务在后台运行吗

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#240]
突然想到，能不能作为服务在后台运行？这样我就可以安装在 ubuntu server或win机器（本机或远程）上。
各种设置(如运行策略，记录数据，监控行情，交易情况等等操作) 则通过命令行，或web，或ui从本机或远端来操作？

**Comment by fanchuan8848** [comment]
里面的vtServer.py就是为这种方式准备的，而且已经有人实现了

**Comment by vnpy** [comment]
可以，vtServer.py的设计更多是用来展示vn.rpc模块的用法，你可以参考他来设计自己需要的后台服务器

**Comment by silent494529371** [comment]
哪里能看到参考实现的代码@fanchuan8848
