### ISSUE TITLE
XTP连接成功，过一段时间报错并断开（交易服务器连接断开, 原因10210006）

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#2400]
## 环境

* 操作系统: Windows 10
* Python版本: ANACONDA 3.7
* vn.py版本: v2.0.9

## Issue类型
三选一：Bug

## 预期程序行为
测试账号正常连接服务器

## 实际程序行为
使用XTP提供的测试账号和环境，显示连接交易服务器和测试服务器成功，但过一段时间后系统报错如下：
**报错：**
TypeError: login(): incompatible function arguments. The following argument types are supported:
    1. (self: vnpy.api.xtp.vnxtpmd.MdApi, arg0: str, arg1: int, arg2: str, arg3: str, arg4: int) -> int

Invoked with: <vnpy.gateway.xtp.xtp_gateway.XtpMdApi object at 0x0000019597B26830>

At:
  C:\TraderWu\vnpywj\vnpy\gateway\xtp\xtp_gateway.py(234): onDisconnected

**并打印日志**
2020-03-31 10:13:06,142  INFO: 交易服务器连接断开, 原因10210006

**Comment by vnpy** [comment]
2.1.2将会发布重构的XTP API，最近有些新的升级了
