### ISSUE TITLE
建议支持mac版本

### ISSUE THREAD

**Issue by firefeifei** [vnpy/vnpy#2402]
## 环境

* 操作系统: mac
* Python版本: python3.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前vn.py支持在Mac上运行，也提供了安装脚本install_osx.sh
