### ISSUE TITLE
打开vnstation，或者是命令行输入python run.py，都会出现如下信息：This Windows version (6.3.9600) does not support the required bluetooth API.

### ISSUE THREAD

**Issue by moyuweiqing** [vnpy/vnpy#2409]
## 环境

* 操作系统: 如Windows 8版本（6.3.9600）
* Python版本: 3.7
* vn.py版本: 2.1.1

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by moyuweiqing** [comment]
目前已经解决，可能是win8系统下不支持吧，使用win10系统可以正常运行

**Comment by vnpy** [comment]
到文件夹中 vnstudio中\Lib\site-packages\PyQt5\Qt\bin\

将Qt5Bluetooth.dll 重命名为 Qt5Bluetooth.dll1
