### ISSUE TITLE
有没有计划支持PyQt5

### ISSUE THREAD

**Issue by bitcof** [vnpy/vnpy#241]
现在最新版的Anaconda（4.3.0）默认安装的是PyQt5了，不知道有没有计划升级到PyQt5，不然需要Downgrade，比较麻烦。谢谢。

**Comment by vnpy** [comment]
建议使用的Anaconda版本是4.0.0，PyQt5的很多API都发生了变化，预计年底可能做升级。

**Comment by vnpy** [comment]
通过qtpy实现兼容
