### ISSUE TITLE
能否获取上期所的五档行情

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2411]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
vn.py已经支持了CTP的5档行情，只要对接的期货公司CTP行情服务器支持就能直接显示和使用
