### ISSUE TITLE
交易开、平仓记录查询；交易盈亏统计分析

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2413]
## 环境

* vn.py版本: 如v2.1.x发行版

## Issue类型
三选一：Enhancement

## 预期程序行为
群主，您好

关于 CTA、algo、价差、期权等全部的策略开仓、平仓：
1、查询（开仓、平仓记录最好能够显示在打开对应标的的1分钟K线图上，复盘方便）；
2、持仓（当前市价）、平仓后盈利的计算统计分析；

这里两个功能，从实际实际交易的角度确实是需要的，并且相对成熟的软件也都是有对应的这两个查询、分析功能的，是否可以把这部分功能纳入到2.xx版本的开发进程中，恳请您考虑下，谢谢！

（我提这个需求是基于实际情况提出的，其实这是很多用了 vnpy 用户的两个痛点的，真的！   我目前用的在 vnpy1.9.2 版本上已经都实现上边功能的了，但是觉得 vnpy 2.x.x 应该有这2个功能才更合适、完美的，并且这个功能是成熟的交易软件都应该具备的，也是目前使用 vnpy2.x.x 大量爱好者们的痛点的。）
另外我认为对于交易成功后的记录保存到数据库可能会影响性能这个应该是非常非常小的，因为毕竟不是频繁交易，再就是用eventType方式应该没啥影响的吧，另外是否可以做成开关功能，相当于可以保存开平仓记录也可以不保存，那么这样实际使用起来也方便的。对于python3.9后续版本升级也肯定会比较方便。

有这方面需要的朋友们帮忙顶下吧，谢谢！

**Comment by vnpy** [comment]
以上两点更多属于定制化的需求，截止目前没有其他用户留言，所以不考虑在vn.py里提供了。

**Comment by waytrylee** [comment]
确实需要

**Comment by rjl02468** [comment]
平时逛vnpy论坛的时候，发现很多vnpy的粉丝提过这个需求的，github 中也多次有人提及，望老大重视一下，希望vnpy越来越强壮，开创中国量化交易一个辉煌的未来，加油！

**Comment by ouryoustone** [comment]
这部分功能确实是需要的，对于使用一个量化交易系统来说如果不能有基于策略的交易记录查询、盈利统计分析，那么就是半盲的了，策略多了单子多了光一个个的数岂不是得掐人中了！
期望vnpy越来越好能够成为量化交易中的完美软件。

**Comment by ouryoustone** [comment]
这部分功能确实是需要的，对于使用一个量化交易系统来说如果不能有基于策略的交易记录查询、盈利统计分析，那么就是半盲的了，策略多了单子多了光一个个的数岂不是得掐人中了！
期望vnpy越来越好能够成为量化交易中的完美软件。

**Comment by stone3536** [comment]
群主，您好
因为这个需求对于一个交易软件或者系统来说确实是最基本的硬需求，另外其实很多用vnpy的铁粉们都需要的（或者您可以再咨询确认下），我就再把这个问题打开了，请您再次考虑下是否可以添加上这个功能。感谢！

找了下，真的是没找到怎么reopen这个问题的，以前记得还有这个功能的呢。
