### ISSUE TITLE
vnpy是否考虑增加跟单模块

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2414]
## 环境

* vn.py版本: 如v2.1.x发行版

## Issue类型
三选一：Enhancement

## 预期程序行为

群主，您好

vnpy2.x.x 是否考虑增加跟单模块？

相当于登录当前交易账号（子账号，跟单账号）后，再登录一个跟单的主账号（被跟单账号，主账号在该系统中不能进行交易，可能需要一个账户属性的字段用来做限制。这里比较麻烦的地儿就是知道了主账号密码的了，而不是主账号的“只读密码”），主账号的成交等交易信息显示在一个单独的窗口中，主账号开平仓对应的接口的标的交易了，那么登录账号（子账号）就对应的开平仓，开仓手数等根据资金比例或者设定的固定比例进行处理？

个人觉得这个需求还是很多交易者需要的，或者说不是特别懂交易或者做不好交易的人反倒是更需要的，因为会跟着交易做的好的人做。

感谢！

**Comment by stone3536** [comment]
印象中好像以前论坛中有人提过这个需求的。

**Comment by stone3536** [comment]
密码这个问题应该可以绕过去解决的，就是做个密码的加密文件，放到对应的文件夹下边即可，那么跟单客户端只需要输入被跟单的账号（主账号）即可，该账号自动找对应的密码文件验证并登录并且这个模式登录的账号是不能做交易的。

有个输入主账号、密码的特定窗口，生成这个特定的密码文件即可。

**Comment by vnpy** [comment]
评估了下这块功能不属于大多数用户需要的功能，开源版本就不打算开发了，如果需要的话可以找我们定制
