### ISSUE TITLE
郑商所tick覆盖问题

### ISSUE THREAD

**Issue by zly111** [vnpy/vnpy#2415]
## Issue类型
Question

## 实际程序行为
由于郑商所的tick没有毫秒时间戳，导致录制行情的时候会相互覆盖，每秒只有一个tick会被保存，
后期可否针对郑商所做额外的判断加上一个随机毫秒时间以便于入数据库时不会出问题

**Comment by xldistance** [comment]
官方交易所都没给毫秒，就不要自己加了吧......

**Comment by zly111** [comment]
> 官方交易所都没给毫秒，就不要自己加了吧......

是的，可能会导致数据污染，但是入库的时候该怎么办呢，就变成一秒一跳了

**Comment by vnpy** [comment]
技术上可以通过缓存时间戳到字典中，然后每次有重复时间戳就加500毫秒后缀的方式来实现。

考虑到交易所自身就没提供的情况，因此vn.py也不在底层接口中做修改了。
