### ISSUE TITLE
找不到自定义的策略

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2416]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
在vn trader中选择CTA策略没有显示在用户目录下/strategies/中我自定义的策略

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by TIANRENK** [comment]
。

**Comment by fudingyu** [comment]
> ## 环境
> * 操作系统: 如Windows 10或者Ubuntu 18.04
> * Python版本: 如VNStudio-2.0.6
> * vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）
> 
> ## Issue类型
> 三选一：Bug/Enhancement/Question
> 
> ## 预期程序行为
> ## 实际程序行为
> 在vn trader中选择CTA策略没有显示在用户目录下/strategies/中我自定义的策略
> 
> ## 重现步骤
> 针对Bug类型Issue，请提供具体重现步骤以及报错截图

我用这个方法成功的 #1942
