### ISSUE TITLE
华鑫 Tora 无法订阅行情

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#2418]
## 环境

* 操作系统: Win7
* Python版本: VNStudio-2.1.1
* vn.py版本: 2.1.1

## Issue类型
Bug

## 实际程序行为
无法订阅行情，输入代码回车后没有行情信息

## 重现步骤

![image](https://user-images.githubusercontent.com/692980/78850126-faab8480-7a48-11ea-96aa-8e4918ea1c22.png)

**Comment by vnpy** [comment]
请看下cmd中是否有报错输出？

**Comment by Gwill** [comment]
我使用 vnstation gui 启动的

**Comment by Gwill** [comment]
我用命令行启动重新操作了一下：

订阅：

![image](https://user-images.githubusercontent.com/692980/78862269-89c89480-7a69-11ea-8d79-b6c0e9fbd7ff.png)

GUI日志：

![image](https://user-images.githubusercontent.com/692980/78862259-8208f000-7a69-11ea-931d-24e86012451a.png)

cmd 输出：

![image](https://user-images.githubusercontent.com/692980/78862288-96e58380-7a69-11ea-95e8-5dccc4b4dd9b.png)

都没有什么报错信息

**Comment by vnpy** [comment]
这里看，行情服务器没有登录上去（没有登录成功的日志）。检查下是否是地址写错了？
