### ISSUE TITLE
Sleep中call回调函数， PyGILState_Ensure使得程序崩溃

### ISSUE THREAD

**Issue by geraybos** [vnpy/vnpy#242]
研究dll接口封装中，

发现：如果在C++代码中使用sleep，或者在python中使用time.sleep，有需要回调函数的时候，PyLock中`gil_state = PyGILState_Ensure(); `会使得程序崩溃。

我猜是在sleep中不能call  PyGILState_Ensure？

请问有什么方法避免或者解决？

**Comment by vnpy** [comment]
sleep应该是会让当前你调用sleep的线程进入休眠状态，等待一段时间。

不明白你是如何在sleep中call PyGILState_Ensure？贴段代码吧

**Comment by geraybos** [comment]
问题解决了

其实我在写易盛的接口。易盛给的cpp demo里面有一个sleep(1000)。如果我使用带PyLock的Wrapper Class的话，会报错。我猜测是由于sleep过程中，程序尝试调用callback函数，其中的PyGILState_Ensure()就会报错。

不好意思，编程方面是半路出家，只能表述个大概。其实是个很简单的问题。后来仔细看了vnpy的实现，还是在python中使用threading解决了。

多谢回复。

**Comment by oldoldjiang** [comment]
@geraybos 您好，请问，您是否已经完成易盛api的vnpy封装呢，不知能否开源呢

**Comment by LishanZhong** [comment]
@geraybos @oldoldjiang 您好，请问，您是否已经完成易盛api的vnpy封装呢？能否分享呢？可有偿。
