### ISSUE TITLE
self.pos延时更新、止盈止损时发生竞速

### ISSUE THREAD

**Issue by noname2024-tech** [vnpy/vnpy#2424]
## 环境

* 操作系统: Windows 10
* Python版本: anaconda python3.7 
* vn.py版本: 版本2.1.1
* simnow交易

## Issue类型
三选一：Bug

## 预期程序行为
`self.pos`能根据当前仓位变化更新，根据self.pos值的变化可实现止盈止损策略的实施

## 实际程序行为
在onBar中设置根据`self.pos`决定的发单逻辑，在`self.pos`还未来得及更新的情况下，下一个Bar出现了，会再走一次发单逻辑，重复发单

根据我的测试，这在simnow交易中不会出现，尤其是平仓委托。如当前持有pos1的仓位，那么同一时间内只能挂出pos-1的一份委托，如需要更改委托内容，必须先撤回，再进行委托，不会出现针对同一仓位同时有两个平仓单的情况。

按照已有问题的回答尝试解决，偶然的竞速情况依然出现，并体现在撤单时的延时上。

## 重现步骤

- 我对此分别进行了回测和simnow交易，发现问题来源于两部分：1/重复发单；2/如“发单”指令为“止盈/止损”，还会同时出现：对同一个pos1的仓发了两个pos-1的平仓单，并且都成交了，self.pos直接更新为-1。

- 有高度类似的问题：https://www.vnpy.com/forum/topic/1562-qiu-zhu-zhi-ying-zhi-sun-deng-wen-ti      作者给出的解决方案是“把止盈止损的设置，写在on_trade回调函数里”

- 在这个基础上，尝试了作者的建议，使用`on_trade`可基本实现检查开仓交易是否已经完成，如完成再发下一单，同时场上对应平仓单只维持已有仓位数量的功能，但：

1/ 效率低下；

2/ 考虑到撤单失败的情形。出现撤销指令时，撤销在回测系统中往往执行得非常快，和“撤销委托X的指令发送完毕“几乎同时发生，即：“order1已经撤销完毕，委托状态更新”甚至比“撤销order1的指令已发送，等交易所处理”的结果反回得更快一些（我估计和具体策略也有关系），导致检查委托状态变得困难。

用log来解释（在`cta_strategy/template.py`中自行添加）：

  ```
  2020-04-06 18:22:23,344  CRITICAL: [Signal][2019-12-13 10:41:00]close order sent['BACKTESTING.22']
  2020-04-06 18:22:23,344  CRITICAL: [Signal][2019-12-13 10:41:00]22_Status.NOTTRADED
  2020-04-06 18:22:23,345  CRITICAL: [Signal][2019-12-13 10:42:00]22_Status.CANCELLED
  2020-04-06 18:22:23,345  CRITICAL: [Signal][2019-12-13 10:42:00]cancel order sent
  ```

- 诸如此类在simnow中会被拒绝，但在回测系统中会通过并竞速的相似问题还有一些，这个比较有代表性。不知道有没有更好的方法解决。

作为一个刚入门量化交易，对编程也没有很多了解的新人，对代码的误解和考虑的不周到在所难免。感谢各路大神的耐心指点。

**Comment by xldistance** [comment]
发单前进行仓位检查了吗

**Comment by noname2024-tech** [comment]
> 发单前进行仓位检查了吗

进行了。而且按照作者早前给他人的建议，self.pos不准确，是在on_trade中通过判断当前活跃订单的状态进行的。

**Comment by vnpy** [comment]
1. 回测引擎的撤单，是瞬间完成的，实盘中撤单是需要时间的
2. 在K线回测模式下，最高执行频率为每分钟一次，如果只用本地停止单，那么直接撤单重下即可
3. 如果用到限价单（存在对持仓的冻结），那么每轮on_bar中需要判断之前的委托是否均已结束，没有要执行全撤，同时本轮不再做任何其他操作，只有全都结束时才允许下新的委托
4. 细粒度的委托状态管理，需要对于期货实盘交易中委托的生命周期，资金持仓的冻结规则有明确的了解，不建议刚入门交易的新手去尝试
