### ISSUE TITLE
关于今昨仓位更新相关计算逻辑的不一致的疑问

### ISSUE THREAD

**Issue by noname2024-tech** [vnpy/vnpy#2425]
## 环境

* 操作系统: Windows 10
* Python版本: anaconda python3.7 
* vn.py版本: 版本2.1.1
* simnow交易

trader指位于`C:\vnstudio\Lib\site-packages\vnpy\trader`中的一系列文件，包括事件驱动引擎，converter等

所涉及代码地址：`trader/converter.py`里的`class PositionHolding`中的`update_trade`，`calculate_frozen`和`convert_order_request_shfe`方法

## Issue类型
三选一：Question

## 预期程序行为
区分上交所和其他交易所的平今平昨指令，并保持一致的逻辑。我理解中交易所逻辑都应该是先开先平，任何情况下都先平历史仓，然后对上交所的情况，根据委托指令不同，进行特别处理。

## 实际程序行为

不知道会对交易结果的预期造成怎样的影响，但看上去有些奇怪。

- update_trade(self, trade: TradeData)。根据代码：

  ```
                  if trade.exchange in [Exchange.SHFE, Exchange.INE]:
                      self.short_yd -= trade.volume
                  else:
                      self.short_td -= trade.volume
  
                      if self.short_td < 0:
                          self.short_yd += self.short_td
                          self.short_td = 0
  ```

  我的理解是，如果交易所是SHFE/INE, then change yesterday position, if not, change today position first(until today's position runs out)。感觉逻辑和交易所规定不同。（请看参考部分）

- `calculate_frozen`: 针对平仓操作计算（交易未完成部分）冻结量

  问题：没有区分不同交易所close指令的不同效果，和update_trade()的计算逻辑不一致

- convert_order_request_shfe：对发往上期所的下单申请的预先处理

  我理解中这段代码的逻辑是：开仓任意下单，对平仓部分，先计算当前的可操作仓位数（持有仓数-冻结仓数），包括总可操作仓数和今日可操作仓数。超出总可操作仓数，订单无效；在今日可操作仓数内，先平今仓；超出今日可操作仓数但在总操作仓数内，先平今后平昨。

  问题：逻辑和update_trade不太一致

## 参考

我理解中交易所的逻辑：

1、上海期货交易所平今指令
① 同时持有历史持仓和当日新仓，投资者既可以先平新仓(也即平今仓)，也可以先平历史仓(也即老仓)。
② 同为今仓或老仓时，遵从先开先平原则。

2、大商所、郑商所、中金所、上海能源交易中心，此4家交易所均无平今指令
① 同时持有历史持仓和当日新仓，平仓时只能默认优先平历史持仓;
② 同为今仓或老仓时，遵从先开先平原则。

没有做过期货实盘交易，有一点迷惑。
感谢大家的耐心解释。

**Comment by vnpy** [comment]
除了上期所外，其他三家优先平今，算是期货交易的基础知识了。
