### ISSUE TITLE
如何连接到富途牛牛

### ISSUE THREAD

**Issue by zjplab** [vnpy/vnpy#2426]
什么软件都装好了
FutuOpenD打开后 
连接窗口：
![image](https://user-images.githubusercontent.com/16349466/78994402-fdbc7880-7b0d-11ea-94d7-446d9c3cf123.png)

之后给我各种报错，说我没解锁交易：
![image](https://user-images.githubusercontent.com/16349466/78994545-5be95b80-7b0e-11ea-857e-76a1092d9f80.png)
然而我在软件里已经解锁了

还有实盘行情也看不到

![image](https://user-images.githubusercontent.com/16349466/78994574-6e639500-7b0e-11ea-9298-068fc097c950.png)

是不是我的默认配置不对?
![image](https://user-images.githubusercontent.com/16349466/78994594-78859380-7b0e-11ea-934f-42bb570f25b7.png)

**Comment by vnpy** [comment]
1. 富途暂停了API的实盘行情推送
2. 解锁方面请检查你交易的是否为港股市场，只有港股需要解锁
