### ISSUE TITLE
图形界面连接CTP后订阅失败

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#2435]
## 环境

* 操作系统: Windows 10
* Python版本: anaconda3.7 64位
* vn.py版本: v2.1.1 release 

## Issue类型
三选一：Bug/Enhancement/Question
我启动了图形界面vnpy后，输入了
以SinNow仿真交易账号登陆CTP接口为例：点击菜单栏的“系统”->“连接CTP”后，弹出如上图所示CTP接口的配置对话框，输入以下内容后即可登录：
- 用户名username：111111 （6位纯数字账号）
- 密码password：1111111  （需要修改一次密码用于盘后测试）
- 经纪商编号brokerid：9999 （SimNow默认经纪商编号）
- 交易服务器地址td_address：218.202.237.33 :10102 （盘中测试）
- 行情服务器地址md_address：218.202.237.33 :10112 （盘中测试）
- 授权码auth_code：0000000000000000（16个0）
- 名称app_id：simnow_client_test
显示连接成功，
![image](https://user-images.githubusercontent.com/40389023/79415901-06ff8680-7fe1-11ea-8838-82a41b4842db.png)
但是 我选择 SHFE后 输入rb2010， 界面完全没有反应，没有显示订阅的行情

**Comment by vnpy** [comment]
没有交易服务器登录成功的日志，请检查账号密码问题以及SIMNOW的交易服务器是不是挂了
