### ISSUE TITLE
simnow无法平仓

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2440]
## 环境

* 操作系统: win10
* Python版本: VNStudio-2.0.6
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Bug

## 预期程序行为
用simnow模拟账户，rb合约平仓

## 实际程序行为
无法平仓，错误代码51,50，平今仓位不足，平昨仓位不足。

## 重现步骤
vn station 无法进行平仓

**Comment by vnpy** [comment]
检查下是否已有其他委托导致了仓位被冻结

**Comment by cjj208** [comment]
这个问题好像还没解决
