### ISSUE TITLE
行情单边市-5档行情，前端界面展示行情-只展示了一档，预期展示单边的五档

### ISSUE THREAD

**Issue by yzcpleo** [vnpy/vnpy#2442]
## 环境

* 操作系统: 如Windows 10
* Python版本: python 3.7
* vn.py版本: V2.12

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
单边市，5档行情只有买方或者卖方五档，预期展示单边5档，

## 实际程序行为

实际程序只展示了一档

## 重现步骤

![image](https://user-images.githubusercontent.com/5761049/79814410-bf964300-83b0-11ea-9907-d1fe02c58cad.png)

![image](https://user-images.githubusercontent.com/5761049/79814423-c58c2400-83b0-11ea-94d4-3efdcd13ef06.png)

排除gateway层，从日志上去分析tickdata准确。event.data准确。猜测是前端处理问题

**Comment by vnpy** [comment]
这是什么接口的？如果是自己开发的请检查底层是否对2-5档数据赋值了
