### ISSUE TITLE
请问银河期货如何作看穿测试！测试时报错！

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#2444]
## 环境

* 操作系统: 如Windows 10
* Python版本: conda 3.7 64
* vn.py版本: v2.1.1

## Issue类型
三选一：Bug/Enhancement/Question
我是银河期货的账户，客户经理说 需要先作一个看穿测试，然后发了一个文档，
![image](https://user-images.githubusercontent.com/40389023/79820722-80bbb980-83bf-11ea-8dc6-579f4f9e766b.png)
我就按文档里面的信息修改了cpt_setteing ，但是运行报错: 交易服务器连接断开，原因4097

**Comment by jxhuliqun138** [comment]
ctp_setting = {
        "用户名": "10000014",
        "密码": "abc@123456",
        "经纪商代码": "1010",
        "交易服务器": "tcp://106.39.36.105:32213",
        "行情服务器": "tcp://106.39.36.105:32205",
        "产品名称": "",
        "授权编码": "YHQHYHQHYHQHYHQH",
        "产品信息": ""
    }
这是测试的 ctp_setting

**Comment by Gwill** [comment]
4097 貌似是服务器版本和客户端版本不对应造成的

**Comment by jxhuliqun138** [comment]
对， 银河期货那边 测试用的是v6.3.16_T， 生产用的是 v6.3.15，我的vnpy是v2.1.1 release,我把银河期货的6.3.16解压的几个dll和库文件都替换了D:\Anaconda\Lib\site-packages\vnpy-2.1.1-py3.7.egg\vnpy\api\ctp目录， 但依然不行。
 那我应该如何修改呢，

**Comment by vnpy** [comment]
穿透式测试请用CtptestGateway连接

**Comment by jxhuliqun138** [comment]
我用的就是 CtptestGateway

**Comment by ben46** [comment]
兄弟我也遇到同样问题,你后来怎么解决的

**Comment by vingin007** [comment]
同样遇到这个问题，并且也替换了银河提供的库文件和dll文件，也是报4097
