### ISSUE TITLE
请教log信息窗口的QtWidgets.QTextEdit字体大小调整问题

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2445]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v1.9.2发行版

## Issue类型
三选一：Question

群主，您好

请教个问题，
对于vnpy的log信息，用到的是QtWidgets.QTextEdit的，为什么我修改字体大小改不了呢？想修改成10号字体，但是使用
，# 定义字体
BASIC_FONT10 = None
try:
    family = globalSetting['fontFamily']
    size = globalSetting['fontSize']
    BASIC_FONT10 = QtGui.QFont(family, size)
except:
    BASIC_FONT10 = QtGui.QFont(u'微软雅黑', 10)

，# 修改字体
self.setFont(BASIC_FONT10)

是改不了的，然后使用QtGui.QFont(u'微软雅黑', 10)的方式直接改，仍旧修改不了的，但是在运行中的窗口中按住ctrl控件用鼠标滚轮滚就可以变小字体的。
我担心10是视觉看不出来的，把数字调整成 5 ，仍旧不行的呢。

不想通过VT_setting.json来修改的，因为VT_setting.json中改成10号太小的了，用QtWidgets.QTextEdit做的看板，希望看板的字体单独小一点儿的，不跟随VT_setting.json设置来，但是怎么改都改不了的呢。

恳请指导下，谢谢！

**Comment by vnpy** [comment]
请检查下修改的是否是site-packages安装目录里的文件

**Comment by stone3536** [comment]
群主，您好

VT_setting.json  修改，没有问题的。
我说的是代码单独改QtWidgets.QTextEdit的（class StLogMonitor(QtWidgets.QTextEdit):）字体的，为啥不行（StLogMonitor 和新作的QtWidgets.QTextEdit都不能单独修改的字体大小的）？是因为整个vnpy都设置了基于VT_setting.json的设置字体的了吗？ 是有特殊的设置位置吗？

**Comment by vnpy** [comment]
不会，肯定都是可以单独修改的，我猜测你改错代码位置了，你不妨直接改个显示的文字，看看能不能生效

**Comment by stone3536** [comment]
是的，您说的没错，
我搜索了关键字，找到了在另外的位置有
setFont(BASIC_FONT)，而且是在测试修改的位置后边的，
导致前边的修改不起作用的了。
感谢！
