### ISSUE TITLE
binance与binancef的vt_symbol相同，导致相互覆盖

### ISSUE THREAD

**Issue by UtorYeung** [vnpy/vnpy#2451]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.1.1
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 预期程序行为
现货和期货的vt_symbol格式不同，例如：
BTCUSDT.BINANCE表示现货
BTCUSDT.BINANCEF或BTC-USDT.BINANCE表示期货

## 实际程序行为
![搜狗截图20200425221222](https://user-images.githubusercontent.com/44016591/80282132-4f861500-8742-11ea-9fb5-d59ced61e57e.png)
![搜狗截图20200425221243](https://user-images.githubusercontent.com/44016591/80282136-50b74200-8742-11ea-957f-93cad1c04efe.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by UtorYeung** [comment]
另一个问题是，连现货没有问题，但是连期货就会出现会出现Invalid API-key的问题。Binance官方貌似是不区分现货和期货的api的。

status: ready
headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json', 'X-MBX-APIKEY': '.................'}
params: {}
data: {}
response: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: ................."}

**Comment by xldistance** [comment]
我改成Exchange.BINANCEF了
