### ISSUE TITLE
BarGenerator.update_bar

### ISSUE THREAD

**Issue by walkingsnail** [vnpy/vnpy#2459]
BarGenerator.update_bar的下述代码，只会在分钟为x的时候生成x minutes bar，每小时生成一个，而不是每x分钟生成一个x minutes bar：
        if self.interval == Interval.MINUTE:
            if not (bar.datetime.minute + 1) % self.window:
                finished = True

修改为：
        if self.interval == Interval.MINUTE:
            if not (bar.datetime.minute - self.window_bar.datetime + 1) % self.window:
                finished = True

还不严谨，假设了x分钟bar的x小于60，常规来说应该OK

**Comment by vnpy** [comment]
5分钟K线正常就应该是5分钟才生成一次，而不是每分钟都在生成。
