### ISSUE TITLE
增加 sopttest api 

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#2461]
上期的股票期权 CTP 也有看穿式监管评测版本：

http://www.sfit.com.cn/5_2_DocumentDown_3.htm

http://www.sfit.com.cn/DocumentDown/api_3/5_2_3/v3.5.5_20190604.zip

对应期货 CTP API 也需要一个 sopttest api 

能否官方编译一个方便使用？  @vnpy

**Comment by vnpy** [comment]
已在dev分支添加
