### ISSUE TITLE
价差交易收不到ontrade推送

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2464]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.1.1

## Issue类型
三选一：Bug

## 预期程序行为
获得TradeData

## 实际程序行为
None

## 重现步骤
运行BasicSpreadStrategy， 成交后onTrade没有收到推送，交易正常。

**Comment by vnpy** [comment]
价差策略启动算法来做交易的话，策略不会收到on_trade推送，只会收到on_algo的状态推送
