### ISSUE TITLE
撮合回测貌似有问题

### ISSUE THREAD

**Issue by jason887** [vnpy/vnpy#247]
在持多仓后，有浮赢的情况下，orderID = self.sell(longStop, 1, stop=True)  longStop=3194.05,后面的k线，最高价都远远超过3195，可一直没有被撮合成交，这是什么原因呢，求教

**Comment by jason887** [comment]
补充下，这是回测

**Comment by hardywu** [comment]
@jason887 碰到同样问题了。请问你是怎么解决的？
