### ISSUE TITLE
官方是否有完善文档的计划？

### ISSUE THREAD

**Issue by scqsu** [vnpy/vnpy#2480]
## 当前问题
目前官网更偏向引导使用打包好的图形化 vnstation，但是相关文档不太全。
像官方文档中有提到一个「CSV载入模块」这部分文档看上去是非图形化版本的，这样混着读，阅读上去实在是不太方便。

## 建议
增加按照使用场景的文档（step1、step2 这种），目前大部分都是按照模块编写文档。按照使用场景编写，首先能够降低入门门槛，其次能够让用户更好的理解各个模块怎么串联。

如果官方没有时间编写，是否考虑招募志愿者共创？

**Comment by vnpy** [comment]
目前的文档落后3-4个版本了，我们后续会更新上来。
