### ISSUE TITLE
Cta回测模块 输入错误vtsymbol 程序卡住

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#2485]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
连接HUOBI 接口后，下载合约数据，如BTC-USD.HUOBi， 由于交易所【HUOBi】填写错误，程序卡住。

在枚举值Exchange中，Exchange("HUOBi")识别不了导致的bug。

![微信图片_20200506155154](https://user-images.githubusercontent.com/45591222/81149906-ae088a00-8fb1-11ea-8b93-7a21ce71494e.png)
![微信图片_20200506155215](https://user-images.githubusercontent.com/45591222/81149925-b365d480-8fb1-11ea-89ed-781432eb7e68.png)

![微信图片_20200506155219](https://user-images.githubusercontent.com/45591222/81149964-bd87d300-8fb1-11ea-86f0-dab00f6a6dea.png)

**Comment by vnpy** [comment]
已修改
