### ISSUE TITLE
scripty_trader 发送委托全是已撤销

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2488]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

正常发送委托
## 实际程序行为
上期，simnow账号模拟交易，发送委托全部都是已撤销

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
上期所只支持平今、平昨，不支持标准的平仓指令，请用send_order下单，然后指定offset即可
