### ISSUE TITLE
IB接口SI合约订阅失败

### ISSUE THREAD

**Issue by dawnbrave** [vnpy/vnpy#2489]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.2
* vn.py版本: v2.1.2发行版

## Issue类型
Enhancement

## 预期程序行为
IB接口， 在VNStudio主界面订阅白银期货(SI)合约

## 实际程序行为
由于白银5000和1000乘数的符号都是SI，订阅失败，提示符号不唯一。

![捕获](https://user-images.githubusercontent.com/19900384/81466088-5b251180-9201-11ea-984f-daa2e61bccaf.PNG)

**Comment by vnpy** [comment]
已修复
