### ISSUE TITLE
关于riskmanger的2个问题

### ISSUE THREAD

**Issue by hoio8** [vnpy/vnpy#2494]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.4.9
* vn.py版本: 如v2.1.2.1发行版

## Issue类型
三选一：Bug/Enhancement/Question
bug
## 预期程序行为
使用南华期货的ETF仿真接口(http://nanhua.net/download/20190604_tradeapi64_windows_se.rar）。
问题1、利用FOK指令交易ETF期权，重启traderPro后，读取的历史委托数据的订单类型应该也还是之前的FOK类型。
问题2、利用FAK和FOK指令不应被统计在撤单次数内，该类订单应该被正常发送。
## 实际程序行为
问题1、FOK指令全部被Limit订单类型覆盖，与实际订单类型不符。
问题2、交易所对FOK和FAK指令不计算在撤单统计中，但实际操作中，未区分订单类型，只是看该合约撤单次数是否超标进行拦截。

## 重现步骤
1、修改撤单笔数为5，输入10002439.SSE合约，买开，FOK，价格设定为低于买1的价格，保证FOK指令不会成交。
2、重复下单5次
3、从第6次开始，riskmanger都开始过滤合规的订单。
4、重启traderPro，查看委托，里面的订单类型全部为“限价”。
针对Bug类型Issue，请提供具体重现步骤以及报错截图
![QQ截图20200514155040](https://user-images.githubusercontent.com/22140606/81907896-0d424c00-95fb-11ea-98e9-f7118585fad7.png)
无限易软件重启后读取的委托订单类型。
![QQ截图20200514155222](https://user-images.githubusercontent.com/22140606/81907906-0f0c0f80-95fb-11ea-8e90-76c23bc9b6e5.png)
traderPro重启后读取的委托订单类型
![QQ截图20200514155558](https://user-images.githubusercontent.com/22140606/81908160-6f9b4c80-95fb-11ea-8e2b-c7752b44f723.png)
traderPro利用FOK发单，但是被riskmanger屏蔽的日志

**Comment by vnpy** [comment]
国内的ETF期权目前不支持FOK和FAK指令，所以接口层就没有做这两个委托类型的映射
