### ISSUE TITLE
cannot import name 'MdsApiClientEnvT' from 'vnpy.api.oes.vnoes' (unknown location)

### ISSUE THREAD

**Issue by welcomeyou2019** [vnpy/vnpy#2495]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Question

## 预期程序行为
能正常连接oes接口

## 实际程序行为
from vnpy.api.oes.vnoes import MdsApiClientEnvT, MdsApi_DestoryAll

## 重现步骤
无法连接

**Comment by vnpy** [comment]
请检查使用的系统，OES接口只支持Windows
