### ISSUE TITLE
AttributeError: type object 'MainEngine' has no attribute 'get_contract'

### ISSUE THREAD

**Issue by guorgithub** [vnpy/vnpy#2498]
## 环境

* 操作系统: Windows 10
* Python版本: python3.7.3
* vn.py版本: v2.1.2发行版

## Issue类型
三选一：Bug, Question

## 预期程序行为
AttributeError: type object 'MainEngine' has no attribute 'get_contract'

## 实际程序行为
AttributeError: type object 'MainEngine' has no attribute 'get_contract'

## 重现步骤
![image](https://user-images.githubusercontent.com/52487729/82217932-b7004080-994d-11ea-907f-a0c34dba8793.png)

Absolute path: 'vnpy/vnpy/app/data_manager/engine.py/'
![image](https://user-images.githubusercontent.com/52487729/82217773-7ef8fd80-994d-11ea-9821-0578a2cd1646.png)

vnpy.trader.engine.MainEngine has no attribute 'get_contract'. 

What does the second picture's code mean? 
And what role?

**Comment by guorgithub** [comment]
The same problem!?!
Absolute path: 'vnpy/vnpy/app/cta_backtester/engine.py(line 369)'
![image](https://user-images.githubusercontent.com/52487729/82223224-f67e5b00-9954-11ea-99fd-679b82758b18.png)

**Comment by vnpy** [comment]
The get_contract method is added to MainEngine dynamically by OmsEngine object when its created.

Please check whether you have changed related code.

**Comment by guorgithub** [comment]
> The get_contract method is added to MainEngine dynamically by OmsEngine object when its created.
> 
> Please check whether you have changed related code.
Does 'its' mean 'MainEngine is' or 'OmsEngine is'?

**Comment by vnpy** [comment]
Here means OmsEngine
