### ISSUE TITLE
回测时ontrade函数重复返回平仓的数据

### ISSUE THREAD

**Issue by jason887** [vnpy/vnpy#250]
发了1手卖平的指令后，ontrade 函数返回了两次，造成pos变成-1，然后再也没有开仓
检查了数据库的1分钟数据，正常的（用别的策略回测同样的数据，很顺利的跑完所有数据），如何解决这个问题呢？求教

**Comment by vnpy** [comment]
检查你的历史数据，onTrade返回两次必然是因为有两个委托被触发了，是否有之前遗留的委托未取消。
