### ISSUE TITLE
二叉树美式期货期权定价模型BUG:  calculate_greeks 现金希腊值的意义与Black-76 欧式期货期权, 与标的物现金Delta,不一致

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2501]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.0
* vn.py版本:  vnpy-2.1.2

## Issue类型
三选一：Bug

## 实际程序行为
会影响到二叉树美式期货期权现金希腊值, 持仓希腊值计算是否正确, 影响后继是否能正确对冲
详细情况说明:
https://www.vnpy.com/forum/topic/3341-wo-qing-jiao-yi-ge-wen-ti-:xian-jin-xi-la-zhi-chi-cang-xi-la-zhi-de-yi-yi-zai-black-76-ou-shi-qi-huo-qi-quan-he-er-cha-shu-mei-shi-qi-huo-qi-quan-liang-chong-ding-jie-mo-xing-shang-bu-yi-zhi?page=1#pid12010

## 重现步骤
详细情况说明:
https://www.vnpy.com/forum/topic/3341-wo-qing-jiao-yi-ge-wen-ti-:xian-jin-xi-la-zhi-chi-cang-xi-la-zhi-de-yi-yi-zai-black-76-ou-shi-qi-huo-qi-quan-he-er-cha-shu-mei-shi-qi-huo-qi-quan-liang-chong-ding-jie-mo-xing-shang-bu-yi-zhi?page=1#pid12010

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢
