### ISSUE TITLE
价差交易单腿问题

### ISSUE THREAD

**Issue by pywang2018** [vnpy/vnpy#2504]
## 环境

* 操作系统: Windows 10
* vn.py版本: 2.11

## Issue类型
三选一：Enhancement

## 预期程序行为
价差交易模块预期不应该出现单腿

## 实际程序行为
在停止算法之前经常出现未成交的下单（没有追单一直未成交），或者主动腿下单被动腿没有下单的情况。
在关闭算法之前是否需要检查单腿情况？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![多平](https://user-images.githubusercontent.com/51951327/82415461-2770a400-9aab-11ea-83b3-1783a1e486d3.png)
这张是平仓时没有追单

![开仓](https://user-images.githubusercontent.com/51951327/82415497-2d668500-9aab-11ea-898f-af5eff40572c.png)
![算法记录](https://user-images.githubusercontent.com/51951327/82415503-2fc8df00-9aab-11ea-9293-ecaa9ab04002.png)
这张是开仓时主动腿多开单，被动腿没有跟

**Comment by pywang2018** [comment]
建议在template的stop函数的if判断语句里加入check order finished 和check hedged finished，在kill algo之前也要检查是否对冲完成

**Comment by vnpy** [comment]
1. 被动腿的对冲委托撤单再追，这里的撤单间隔是通过【间隔】参数（interval）来控制的，请检查下是否设置的太长
2. 图中日志里，有委托发出的记录，但是没有成交记录，因此被动腿没有执行对冲，这个完全符合算法逻辑的设计，建议检查是否底层接口是否出现断开等异常
