### ISSUE TITLE
期权电子眼process_trade_event/update_net_pos有Bug,.KeyError: 

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2505]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.3
* vn.py版本: v2.1.3 

## Issue类型
三选一：Bug

## 重现步骤
以豆粕期权为例进行测试:
1,  开启期权电子眼自动盯盘
2,  开启对冲引擎自动跟进对冲, 
当电子眼有抓到订单, 且对冲引擎自动跟进对冲,
随后,Bug就出现了: 详见报错截图
 Bug定位及原因分析:
     期权电子眼界面在处理process_trade_event事件并更新净持仓显示时, 抓到了来自标的物合约的成交事件,  没有进行过滤, 试图直接送到期权电子眼的UI界面进行显示,  但期权电子眼的UI上却无法找到相应的地方来显示标的物合约的净持仓
  建议修改方案:
option_master\ui\manager.py", line 462, in process_trade_event
option_master\ui\manager.py", line 467, in update_net_pos
像update_tick那样, 在update_net_pos函数的开头增加合约符号过滤:
cells = self.cells.get(vt_symbol, None)
if not cells:
    return

针对Bug类型Issue，请提供具体重现步骤以及报错截图
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.3-py3.7.egg\vnpy\app\option_master\ui\manager.py", line 462, in process_trade_event
    self.update_net_pos(trade.vt_symbol)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.3-py3.7.egg\vnpy\app\option_master\ui\manager.py", line 467, in update_net_pos
    cells = self.cells[vt_symbol]
KeyError: 'm2009.DCE'

**Comment by vnpy** [comment]
已修复，非常感谢
