### ISSUE TITLE
CTPtick数据没有成交字段

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2508]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.2
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
simnow五档tick数据，包含五档的行情，和成交金额字段。

## 实际程序行为
 只有一价和一量，也没有成交额字段。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
CTP有5档行情的柜台可以直接看见，另外成交额特意不加的，因为量化中没什么用。
