### ISSUE TITLE
回测优化参数的结果和单独跑不一致

### ISSUE THREAD

**Issue by jason887** [vnpy/vnpy#251]
用多线程跑了参数优化，选最好的参数
单独跑，结果居然不一样，哪位碰到类似情况吗

**Comment by vnpy** [comment]
检查你的参数配置

**Comment by freeitaly** [comment]
测试发现这个问题确实存在：
多进程优化在创建进程池时，没有传递self.priceTick参数，所以optimize函数在创建回测引擎时，使用了默认的priceTick=0. 导致在撮合时有时会偷一个tick
`            l.append(pool.apply_async(optimize, (strategyClass, setting,
                                                 targetName, self.mode, 
                                                 self.startDate, self.initDays, self.endDate,
                                                 self.slippage, self.rate, self.size,
                                                 self.dbName, self.symbol)))`

测试vnpy的模板atrrsi策略：
多进程优化：{'rsiLength': 5, 'atrMa': 20, 'atrLength': 18}: -83175.4999776
单进程：{'rsiLength': 5, 'atrMa': 20, 'atrLength': 18}: -79055.1456

**Comment by vnpy** [comment]
已经修复，将会在这几天上传到dev。

**Comment by vnpy** [comment]
已修复
