### ISSUE TITLE
datamanger模块的bug

### ISSUE THREAD

**Issue by hoio8** [vnpy/vnpy#2510]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VN trader-2.1.3
* vn.py版本: 如v2.5.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
datamanger模块，点击“刷新‘，应该看到数据。

## 实际程序行为
异常错误
Traceback (most recent call last):
  File "C:\Users\zhb\PycharmProjects\vnpy\vnpy\app\data_manager\ui\widget.py", line 192, in refresh_tree
    item.setText(6, d["end"].strftime("%Y-%m-%d %H:%M:%S"))
AttributeError: 'str' object has no attribute 'strftime'
debug显示的d["end"] = '2020-05-22 15:00:00+08:06'
看数据格式与代码要求不同，多了+08:06，不知道是不是时区问题引起。
## 重现步骤
登陆ctp系统，打开datamanger，点刷新数据。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
用vnstation的话请升级到2.1.3.1版本，或者直接下载新的master分支。

另外需要将数据库中15:00:00+08:06这种带有时区后缀的数据删除下即可，或者直接删掉数据库重新下载更加方便了。
