### ISSUE TITLE
建议加强算法交易模块的功能

### ISSUE THREAD

**Issue by mm-lucky** [vnpy/vnpy#2515]
## 环境

* 操作系统: Windows 10
* vn.py版本: v2.1.3发行版

## Issue类型
三选一：Enhancement

## 预期程序行为
算法交易模块
1，能不能不预先指定价格，而是可以选择去挂当时的bid1或者ask1？
2，除了价格触发，能不能加上时间触发的功能？

**Comment by vnpy** [comment]
1. 需求可以通过BestLimit算法实现
2. 不是通用需求，有需要可以自行通过Python的脚本调度来实现，很方便
