### ISSUE TITLE
get_all_active_orders 报错：RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by ieachen** [vnpy/vnpy#2518]
## 环境

* 操作系统: Windows 10
* Python版本: Anaconda Python3
* vn.py版本: 2020-05-28 master & dev

## Issue类型
Bug

## 实际程序行为

`\vnpy\trader\engine.py 497行 get_all_active_orders()`，如果有多个挂单，并且连续不间断调用 get_all_active_orders，那么过几分钟或十几分钟会报错：

> RuntimeError: dictionary changed size during iteration

原代码：

```Python
active_orders = [
    order
    for order in self.active_orders.values()
    if order.vt_symbol == vt_symbol
]
```

建议修改：
```Python
active_orders = [
    order
    for order in list(self.active_orders.values())
    if order.vt_symbol == vt_symbol
]
```

以往 issue 提到过类似（但并非此函数）问题：
- https://github.com/vnpy/vnpy/issues/2126
- https://github.com/vnpy/vnpy/issues/1066

## 重现步骤

```Python
# 例子：有挂单情况下，连续不断调用 get_all_active_orders
while True: 
    active_orders = main_engine.get_all_active_orders()

    if active_orders:
      for order in active_orders:
        pass # do something...
```

**Comment by vnpy** [comment]
请问是用ScriptTrader模块触发的吗？

还是自己在新开的线程里启动了while循环？

**Comment by ieachen** [comment]
没有使用ScriptTrader，也没新开线程，就在单一主进程脚本里写simple code，类似这样：

```Python
event_engine = EventEngine()
main_engine = MainEngine(event_engine)
main_engine.add_gateway(CtpGateway)
main_engine.connect(setting=ctp_connect_setting, gateway_name='CTP')
# 假设手动下了几个挂单
while True:
    active_orders = main_engine.get_active_orders()
```

可能写 on_tick, on_order 比较符合事件驱动的风格，不过合约、订单多了的话写 while True简单粗暴 😅

**Comment by vnpy** [comment]
因为GIL的存在导致Python线程越多性能越差的问题，vn.py的设计是单线程架构，由事件驱动引擎完成异步驱动，所以和策略交易相关的逻辑，都应该通过事件驱动引擎的回调来调用，也就是你这里提到策略里的on_tick/on_order等函数。

所以不建议在主循环中启动while循环的模式来运行程序了。

**Comment by vnpy** [comment]
可以试试ScriptTrader，但是在while循环里，要加上sleep逻辑每隔若干秒运行一次，而不能直接循环下去，否则就可能触发上述问题（本质是多线程数据冲突了）。

**Comment by ieachen** [comment]
了解，多谢！
