### ISSUE TITLE
position持仓查询比orders订单查询更慢

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2519]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 如v2.1.2发行

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
CTP中，当限价单成交后，get_all_active_orders返回结果中的未成交订单消失，get_positions返回结果过了很久都没有更新成交后的持仓

## 实际程序行为
当挂单成交后，get_all_active_orders中的order消失，get_positions中增加成交后的持仓信息。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
委托信息是基于推送立即跟新的，持仓信息是基于轮询每隔几秒才更新的。

要知道准确的最新持仓情况，要通过持仓和成交两个数据流来维护。

**Comment by TIANRENK** [comment]
> 委托信息是基于推送立即跟新的，持仓信息是基于轮询每隔几秒才更新的。
> 
> 要知道准确的最新持仓情况，要通过持仓和成交两个数据流来维护。

那么通过哪个函数可以查询当前最新的成交情况，和最新的持仓呢

**Comment by vnpy** [comment]
成交要通过监听EVENT_TRADE事件来获取，没有查询全部成交的函数
