### ISSUE TITLE
CTP,cancel_all()无效

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2520]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
self.cancel_all() 取消所有报单

## 实际程序行为
self.cancel_all()之后，get_all_active_orders()中还是有挂单

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
cancel_all函数的功能，是立即发出撤单委托，要等到撤单确认信息返回后，才会从缓存的活动委托列表中移除该委托，此时get_all_active_orders才会为空

**Comment by TIANRENK** [comment]
> cancel_all函数的功能，是立即发出撤单委托，要等到撤单确认信息返回后，才会从缓存的活动委托列表中移除该委托，此时get_all_active_orders才会为空

在当前on_tick中，我发出撤单委托之后，无论过多久get_all_active_orders都没有更新，必须等到下个on_tick才会更新， 这个问题有办法解决吗
