### ISSUE TITLE
查询实时持仓情况

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2521]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Question

## 预期程序行为
查询最新持仓函数

## 实际程序行为
get_all_positions函数结果是几秒更新，那么通过哪个函数可以查询当前实时的成交情况，和最新的持仓呢

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
可以自行基于EVENT_POSITION和EVENT_TRADE推送的数据来合成计算，引擎层没有提供现成的查询函数
