### ISSUE TITLE
融航接口无法返回账户信息

### ISSUE THREAD

**Issue by longmumin** [vnpy/vnpy#2522]
## 环境

* 操作系统: 如Windows 10
* Python版本: py 3.7
* vn.py版本: dev branch 20200526（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
登陆融航CTP后自动获取账户信息

## 实际程序行为
登录后无法获取账户信息，第一次发单结束后，账户信息才能获取到
reqQryTradingAccount这个函数是能够执行到的，但是就是收不到回调函数，ctp的日志能收到回报，所以问题应该是接口函数没有把回报传递给python造成的

## 重现步骤
首次登陆融航模拟柜台，无法显示账户信息

**Comment by vnpy** [comment]
发单结束后能正常收到账户信息，说明封装代码逻辑部分没有错误，这段代码里没有判断逻辑，建议联系下期货公司的运维团队检查是否服务端配置有问题。
