### ISSUE TITLE
canel_all函数调用更新延迟

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2525]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Question

## 预期程序行为
调用cancel_all函数后，一定时间get_all_active_orders更新。

## 实际程序行为
在当前on_tick中，我发出撤单委托之后，无论过多久get_all_active_orders都没有更新，必须等到下个on_tick才会更新， 这个问题有办法解决吗

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by TIANRENK** [comment]
不仅仅调用cancel_all函数，包括send_order等发送委托，过了一定时间后，即使该委托已经成功了，但是在当前on_tick内，查询get_all_active_orders或者查询当前仓位都没有更新，是否是因为线程阻塞和调度的问题

**Comment by xldistance** [comment]
cancel_all不适合放到on_tick里面，on_tick里面需要更精细的控制

**Comment by vnpy** [comment]
cancel_all只是给on_bar这种比较低频交易模式下的一个便捷功能，请不要在on_tick下使用
