### ISSUE TITLE
数据管理模块，显示数据，如果start 和end为同一天，不能显示数据

### ISSUE THREAD

**Issue by WANGYE-2012** [vnpy/vnpy#2529]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

数据模块里的展示数据时，如果start 和end为同一天，就不能展示吗，这个写死了吗，不可以改吗
想查看，当天录得数据，想展示一下
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
