### ISSUE TITLE
HUOBI testnet 

### ISSUE THREAD

**Issue by AronWater** [vnpy/vnpy#2530]
请问vnpy的huobi gateway是不是还没有推出testnet功能

**Comment by vnpy** [comment]
目前没有，我们来查下加上吧

**Comment by vnpy** [comment]
火币的TESTNET目前只提供现货，没有期货和永续。

且其Websocket接口使用的还是老的V1版本，而vn.py中已经升级到了新的V2版本，两者无法兼容。

因此无法对接其testnet环境了。
