### ISSUE TITLE
回测时，backtesting的 run_backtesting 函数中，准备数据时，计数错误。

### ISSUE THREAD

**Issue by chenchenwenfeng** [vnpy/vnpy#2539]
## 环境

* vn.py版本: 如v2.3.1

## Issue类型
三选一：Bug

## 重现步骤

1.在backtesting.py的 run_backtesting 中，第一条记录由于self.datetime 是none，而没有为day_count加1.

       ```
 for ix, data in enumerate(self.history_data):
            if self.datetime and data.datetime.day != self.datetime.day:
                    day_count += 1
                    if day_count >= self.days:
                        break
```
2. 在utility.py中，ArrayManager的update_bar中，计数是每条记录都加1。
这种差异，导致策略还没有开始，am.inited就满足条件了。

**Comment by vnpy** [comment]
非常感谢，已经修复第1点。

第2点里，am.inited状态只表示这个容器本身是否完成了初始化，和策略是否完成初始化是独立的。
