### ISSUE TITLE
过滤非交易时段成交量为0的tick数据

### ISSUE THREAD

**Issue by akeyong** [vnpy/vnpy#254]
试用dataRecorder模块，发现了不少非交易时段成交量为0的tick数据，建议过滤掉，代码如下：

def processTickEvent(self, event):
        """处理行情推送"""
        tick = event.dict_['data']
        
        # 过滤成交量为0的tick
        if not tick.volume:
            return
        
        vtSymbol = tick.vtSymbol

        # 转化Tick格式
        drTick = DrTickData()
        d = drTick.__dict__
        for key in d.keys():
            if key != 'datetime':
                d[key] = tick.__getattribute__(key)

![tickimg](https://cloud.githubusercontent.com/assets/25548173/23732629/1b1b5da2-04af-11e7-9164-6c4a5ef1cde0.png)

**Comment by vnpy** [comment]
相当好的建议，我会在v1.5添加进去

**Comment by vnpy** [comment]
已经在ctpGateway的onRtnDepthMarketData中添加了过滤
