### ISSUE TITLE
K线图表显示有一个Bug,open、high、low、close四个数值相同时K线显示不正常

### ISSUE THREAD

**Issue by heshibs** [vnpy/vnpy#2541]
## 环境

* 操作系统: 如Windows 10

* vn.py版本: 如v2.1.3
Bug

![QQ截图20200617113814](https://user-images.githubusercontent.com/37288834/84853479-d2b44f00-b091-11ea-94b9-16e5f94e022f.png)
K线图表显示有一个Bug,就是当K线的open、high、low、close四个数值相同的时候，就会显示一根上下边界很长的红色K线，并不是显示一个价格没有变化的横线。
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢
