### ISSUE TITLE
实盘上期平单变开单

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2542]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如3.7
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Bug

## 预期程序行为
平仓就是平仓，不是自动开仓

## 实际程序行为
发送平今，变成了开仓

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by TIANRENK** [comment]
我用cta_engine.offset_converter.holdings来查询当前仓位，显示已经持了多仓，我发送的SHORT，平今指令，但是发现实际是在开空单。

**Comment by vnpy** [comment]
1. CTA策略模块对策略只提供了平仓指令，没有提供平今、平昨的选项
2. 对于上期所合约，开平自动转换只会转换平仓到对应的平今、平昨
2. buy/sell/short/cover四个函数的最后一个可选参数lock，控制是否要用锁仓模式，在有反向持仓时会将平转开，请检查是否这里调用错了
