### ISSUE TITLE
无法执行signal.connect连接的函数

### ISSUE THREAD

**Issue by sunshinelover** [vnpy/vnpy#255]
>  def registerEvent(self):
        """注册事件监听"""
        self.signal.connect(self.updateMarketData)
        self.__eventEngine.register(EVENT_MARKETDATA, self.signal.emit)

代码中的updateMarketData始终无法执行

**Comment by vnpy** [comment]
这是什么地方的代码，请把上下文一起贴出来。

另外可以先检查下你调用registerEvent函数了没
