### ISSUE TITLE
关于咨询vnpy中盈透连续合约代码的合成规则是？

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2553]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.6
* vn.py版本: v2.0.5发行版

## Issue类型
vnpy中盈透连续合约代码的合成规则是？查了盈透api的官方文档资料，TWS v971及更高版本的API可以提供连续期货，连续期货不能用于实时数据或下订单，而只能用于历史数据，那么在vnpy中如何输入这些连续期货合约的代码呢？   例如XINA50,尝试了一下这些组合都不能下载连续合约：XINA50-20200629-USD-FUT+CONTFUT.SGX均提示错误
![Pic00009](https://user-images.githubusercontent.com/60735134/85290526-b9653580-b4cb-11ea-9715-3faef629bc7e.jpg)
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前没支持这种类型，我们看看后续如何加上吧

**Comment by vnpy** [comment]
查了下资料目前应该就能支持，请试试：ES-USD-CONTFUT.GLOBEX
