### ISSUE TITLE
关于MT5_Gateway加载历史数据的Bug

### ISSUE THREAD

**Issue by Billy-Meng** [vnpy/vnpy#2557]
## 环境

* 操作系统: Windows 10
* Python版本: 3.7.6
* vn.py版本: v2.1.4

## Issue类型
Bug

## 预期程序行为
策略初始化时，从mt5_gateway获取的历史数据应该截止当时的最新行情。

## 实际程序行为
实际在加载历史数据进行策略初始化时，mt5_gateway只获取到截止当天0点的历史数据，0点之后的数据是缺失的。
按照mt5_gateway中query_history的写法，传入的结束时间是本地时间，比MT5平台的时间戳还多8小时，req理应是可以获取的最新行情的，不知道是否vnpy_server.mq5中存在Bug？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![微信图片_20200629163955](https://user-images.githubusercontent.com/56326576/85993348-caacc580-ba28-11ea-93f5-69515e6471ed.png)

![微信图片_20200629164002](https://user-images.githubusercontent.com/56326576/85993397-e021ef80-ba28-11ea-810b-37a9f37039ae.png)

**Comment by vnpy** [comment]
已修复，#2618
