### ISSUE TITLE
如何连接币安接口

### ISSUE THREAD

**Issue by Angel0726** [vnpy/vnpy#2558]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.1.4

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

如何连接币安接口

**Comment by vnpy** [comment]
请查看【vnpy-community】微信公众号的入门教程。
