### ISSUE TITLE
libthostmduserapi_se.so 不支持arm linux环境

### ISSUE THREAD

**Issue by obrua** [vnpy/vnpy#2559]
## 环境

* 操作系统: Linux ubuntu 5.3.0-1017-raspi2 #19~18.04.1-Ubuntu SMP Fri Jan 17 11:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
* Python版本: Python 3.7.8
* vn.py版本: master

## Issue类型
Bug

## 预期程序行为
在树莓派上运行， ubuntu arm 18.04

## 实际程序行为
/usr/bin/ld: skipping incompatible libthostmduserapi_se.so when searching for -lthostmduserapi_se
/usr/bin/ld: cannot find -lthostmduserapi_se
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

## 重现步骤
sh install.sh

## 分析
查看libthostmduserapi_se.so：libthostmduserapi_se.so: ELF 64-bit LSB shared object, **x86-64**, version 1 (SYSV), dynamically linked, not stripped

libthostmduserapi_se.so是x86-64，不支持arm
需要编译对应的arm版本libthostmduserapi_se.so

**Comment by Gwill** [comment]
上期技术官方不开源，不提供，不支持

**Comment by obrua** [comment]
确实，无解
