### ISSUE TITLE
关于vntrader界面版中添加自动重启软件、自动登录API、自动初始化与实盘功能的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2562]
环境

操作系统: Windows 10
Python版本: VNStudio-2.0.6
vn.py版本: v2.0.5发行版

Issue类型
三选一：Enhancement

1：vntrader界面版中是否可以添加自动重启软件，重启软件自动登录需要的API接口，登录API后，自动初始化，然后自动实盘运行的功能

2：no_ui模式对新人不是非常的友好

预期程序行为

vntrader界面版中是否可以添加自动重启软件，重启软件自动登录需要的API接口，登录API后，自动初始化，然后实盘运行的功能

实际程序行为

需要手工一步一步去操作

**Comment by vnpy** [comment]
使用类似no_ui的脚本操作即可，修改点：
1. 需要启动图形界面
2. 需要有另一个线程，来执行各项初始化调用
