### ISSUE TITLE
修复ctp中，simnow测试环境下，推送数据缺少时间戳导致无法运行问题

### ISSUE THREAD

**Issue by cqychen** [vnpy/vnpy#2564]
## 环境

* 操作系统: windows7    ，centos7.5
*Python版本: python3.6
* vn.py版本: 2.14
## Issue类型
三选一：Bug

## 预期程序行为
预期在simnow 测试环境中，订阅了品种后，应该推送相关数据，但是实际未推送时间相关信息。

## 实际程序行为 
下载vnpy后，直接运行run程序，连接ctp simnow缓慢后，订阅行情
![image](https://user-images.githubusercontent.com/3394913/86508104-f5739100-be0f-11ea-8943-ba36dd56c7b6.png)
timestamp = f"{self.current_date} {data['UpdateTime']}.{int(data['UpdateMillisec']/100)}"
dt = datetime.strptime(timestamp, "%Y%m%d %H:%M:%S.%f")
dt = dt.replace(tzinfo=CHINA_TZ)
得到data如下：
{'ActionDay': '',
 'AskPrice1': 3572.0,
 'AskPrice2': 1.7976931348623157e+308,
 'AskPrice3': 1.7976931348623157e+308,
 'AskPrice4': 1.7976931348623157e+308,
 'AskPrice5': 1.7976931348623157e+308,
 'AskVolume1': 770,
 'AskVolume2': 0,
 'AskVolume3': 0,
 'AskVolume4': 0,
 'AskVolume5': 0,
 'AveragePrice': 35694.45795017636,
 'BidPrice1': 3571.0,
 'BidPrice2': 1.7976931348623157e+308,
 'BidPrice3': 1.7976931348623157e+308,
 'BidPrice4': 1.7976931348623157e+308,
 'BidPrice5': 1.7976931348623157e+308,
 'BidVolume1': 139,
 'BidVolume2': 0,
 'BidVolume3': 0,
 'BidVolume4': 0,
 'BidVolume5': 0,
 'ClosePrice': 1.7976931348623157e+308,
 'CurrDelta': 1.7976931348623157e+308,
 'ExchangeID': '',
 'ExchangeInstID': '',
 'HighestPrice': 3582.0,
 'InstrumentID': 'rb2010',
 'LastPrice': 3571.0,
 'LowerLimitPrice': 3311.0,
 'LowestPrice': 3560.0,
 'OpenInterest': 1404619.0,
 'OpenPrice': 3565.0,
 'PreClosePrice': 3566.0,
 'PreDelta': 0.0,
 'PreOpenInterest': 1361885.0,
 'PreSettlementPrice': 3561.0,
 'SettlementPrice': 1.7976931348623157e+308,
 'TradingDay': '20200702',
 'Turnover': 22253317170.0,
 'UpdateMillisec': 0,
 'UpdateTime': '',
 'UpperLimitPrice': 3810.0,
 'Volume': 623439}
## 重现步骤
登陆vnpy后，订阅行情即可。 注意是 simnow 测试环境。
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复。
