### ISSUE TITLE
可以假如v2ray代理方式吗

### ISSUE THREAD

**Issue by Angel0726** [vnpy/vnpy#2565]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
查看v2ray的文档后，只需打开https代理，即可通过和SS类似的方式来翻墙，无需vn.py中做额外修改
