### ISSUE TITLE
用Bybit接口初始化策略获取1分钟K线每天缺失8小时K线数据

### ISSUE THREAD

**Issue by 515119049** [vnpy/vnpy#2567]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.3
* vn.py版本: 2.1.3发行版

## Issue类型
三选一：Bug

用Bybit接口初始化策略获取1分钟K线 每天 缺失8小时K线数据
导致初始化的开平仓指标错误
初始化获取数据日志截图
![image](https://user-images.githubusercontent.com/59277883/86866867-5a770180-c104-11ea-9715-33452d7dbf0d.png)

**Comment by vnpy** [comment]
已修复
