### ISSUE TITLE
自动更新数据库里的持仓数据更新

### ISSUE THREAD

**Issue by akeyong** [vnpy/vnpy#257]
尝试了一下模拟盘交易，目前委托报单成交后，持仓数据并不会自动更新同步到数据库里的持仓表，需要手动点击按钮”保存持仓“才会更新同步到数据库里的持仓表；
     假如vnpy系统中途意外退出或者操作系统意外重启，就会导致数据库里的持仓数据不是最新的，下一次重启vnpy系统后，只会导入旧的持仓数据，因为策略里的买卖行为依赖于self.pos，这样可能会造成重复买卖或者错过平仓机会，不知道这样的理解是否正确？

      如果可以的话，建议在processTradeEvent里面，除了更新持仓缓存数据后，也同时去更新数据库里的持仓数据，代码如下：

    def processTradeEvent(self, event):
        """处理成交推送"""
        trade = event.dict_['data']
        
        if trade.vtOrderID in self.orderStrategyDict:
            strategy = self.orderStrategyDict[trade.vtOrderID]
            
            # 计算策略持仓
            if trade.direction == DIRECTION_LONG:
                strategy.pos += trade.volume
            else:
                strategy.pos -= trade.volume
            
            self.callStrategyFunc(strategy, strategy.onTrade, trade)
            
            # 更新数据库里的持仓数据
            flt = {'name': strategy.name,
                   'vtSymbol': strategy.vtSymbol}
            
            d = {'name': strategy.name,
                 'vtSymbol': strategy.vtSymbol,
                 'pos': strategy.pos}
            
            self.mainEngine.dbUpdate(POSITION_DB_NAME, strategy.className,
                                     d, flt, True)
            
            content = '自动同步更新策略%s的持仓' %strategy.name
            self.writeCtaLog(content)

**Comment by vnpy** [comment]
这个可能设计为一个CTA模块的配置会更好？有些情景并不希望实时保存数据到数据库中，因为某个时间点后可能手动去处理，我再考虑下

**Comment by vnpy** [comment]
已完成，增加了关闭窗口时的询问
