### ISSUE TITLE
运行examples/vn_trader/run.py报错No module named 'vnpy.trader.engine'

### ISSUE THREAD

**Issue by ctycode** [vnpy/vnpy#2572]
## 环境

* 操作系统: MacOS 10.15.3
* Python版本: Python 3.7.4
* vn.py版本: 最新发行版

## Issue类型
三选一：Question

## 报错
(base) DearMacBook-Pro:vn_trader quoba$ python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.trader.engine import MainEngine
ModuleNotFoundError: No module named 'vnpy.trader.engine'

**Comment by vnpy** [comment]
请检查是否正确安装了vn.py到你的Python环境中
