### ISSUE TITLE
队列是否使用“优先级队列”功能更好？

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2575]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6

## Issue类型
三选一：Question

群主，您好

对线程、队列这部分不太了解的，想咨询下，vnpy2.x的新版本中，队列是否实现了“优先级队列”功能？相当于是行情、交易使用高优先级队列，对于日志、数据保存等使用低优先级的方式？这样是不是可以提高交易的性能？

比如同时50个标的要保存k线数据和交易的情况下，这样是否可以提升整体的性能？

谢谢！

**Comment by vnpy** [comment]
PriorityQueue性能比较差，可以自己测试看下。
