### ISSUE TITLE
关于盈透持仓空单双击平仓后，报错“提交中"的咨询

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2577]
环境

操作系统: Windows 10
Python版本: VNStudio-2.1.4
vn.py版本: v2.1.4发行版

Issue类型
三选一：bug

1：盈透持有**空单**双击平仓报错：”提交中“，是否与下图中的-1有关系呢？
2：盈透持仓多单双击平仓显示：”成交“
![微信图片_20200714203139](https://user-images.githubusercontent.com/60735134/87426034-3a1dda00-c611-11ea-8fde-258025ac11f7.jpg)

预期程序行为

vntrader中，双击持仓订单后，可以直接点击“委托”平仓

实际程序行为

**需要把双击后的空单 ”-1“修改为”1“** 才能正常显示

**Comment by vnpy** [comment]
已修复，非常感谢
