### ISSUE TITLE
用vnpy对BITMEX上的XBTUSD进行Tick逐笔回测，逐笔数据的格式应是什么？

### ISSUE THREAD

**Issue by ctycode** [vnpy/vnpy#2578]
## 环境

* 操作系统: Mac
* Python版本: Python3.7.5
* vn.py版本: 最新版

## Issue类型
Question

## 问题
用vnpy对BITMEX上的XBTUSD进行Tick逐笔回测，逐笔数据的格式应是什么？也就是表头都应该有什么？

**Comment by vnpy** [comment]
请参考这个文件：https://github.com/vnpy/vnpy/blob/master/vnpy/trader/database/database_sql.py

其中的：class DbTickData(ModelBase)
