### ISSUE TITLE
能解释一下，为什么放弃了docker的vnpy吗？因为效率太低吗？

### ISSUE THREAD

**Issue by Angel0726** [vnpy/vnpy#2583]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. docker性能比不上系统级运行，对量化交易来说很关键
2. docker带来的部署便捷特性，对交易来说意义不大
