### ISSUE TITLE
Okex option合约查询数据类型错误

### ISSUE THREAD

**Issue by TrinityWater1991** [vnpy/vnpy#2585]
## 环境

* 操作系统: 如Windows 10
* Python版本: VNStudio-2.5.1
* vn.py版本: v2.5.1
## Issue类型
Bug

## 实际程序行为

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/59277883/87847759-10183080-c90d-11ea-9418-ac191c6f7b68.png)

**Comment by TrinityWater1991** [comment]
解决方法: 数据类型改为float
![image](https://user-images.githubusercontent.com/59277883/87847958-a3059a80-c90e-11ea-89e0-86973a5eb75d.png)

**Comment by vnpy** [comment]
已修复，非常感谢
