### ISSUE TITLE
CTA回测线程不能“优雅”结束

### ISSUE THREAD

**Issue by agelongwin** [vnpy/vnpy#2586]
## 环境

* 操作系统: 如Windows 10
* Python版本: Anaconda 2020.02 Python版本是3.7.6
* vn.py版本: 如v2.1.4

## Issue类型
Bug

## 预期程序行为
即使在CTA回测线程执行过程中出现异常，线程也能优雅地结束。

## 实际程序行为
如果线程执行过程中出现异常，线程就会异常中止，BacktesterEngine类的thread属性无法重新置为None，以后就无法创建新的回测线程，只有重新启动程序。

## 重现步骤
在CTA回测界面上输入一个错误的本地代码，开始回测。
提示窗中显示了横线----------------------------------------后就结束了。
即使在界面上修改为正确的本地代码，系统也会提示“已有任务在运行中，请等待完成”，其实并没有。
如果有其它错误，也会有此现象。

针对Bug类型Issue，请提供具体重现步骤以及报错截图
可以将BacktesterEngine.run_backtesting()方法改为如下形式：
        try:
            engine = self.backtesting_engine
            ……
            self.result_statistics = engine.calculate_statistics(output=False)
        except:
            self.write_log("回测过程中发生错误，回测线程已中止。")
        finally:
            # Clear thread object handler.
            self.thread = None
就可以解决上述问题。
另外，搜索程序代码没有发现finally保留字，这不是好现象。

**Comment by vnpy** [comment]
已处理，非常感谢！
