### ISSUE TITLE
CTA回测结束事件的处理机制不合理

### ISSUE THREAD

**Issue by agelongwin** [vnpy/vnpy#2587]
## 环境

* 操作系统: 如Windows 10
* Python版本: Anaconda 2020.02 Python版本是3.7.6
* vn.py版本: v2.1.4

## Issue类型
Enhancement

针对Bug类型Issue，请提供具体重现步骤以及报错截图

现在的实现方法如下：
BacktesterManager是回测窗体类，在vnpy\app\cta_backtester\ui目录下的widget.py中定义。在窗体类中首先定义一个PyQt5信号：
    signal_backtesting_finished = QtCore.pyqtSignal(Event)
在窗体类的register_event方法中：
        self.signal_backtesting_finished.connect(
            self.process_backtesting_finished_event)
指明process_backtesting_finished_event为该信号的槽函数。后续代码：
        self.event_engine.register(
            EVENT_BACKTESTER_BACKTESTING_FINISHED, 
            self.signal_backtesting_finished.emit)
将发出signal_backtesting_finished信号的函数注册为EVENT_BACKTESTER_BACKTESTING_FINISHED事件的处理函数。
感觉上述代码有些绕。
可以只用一句代码完成上述功能：
        self.event_engine.register(
            EVENT_BACKTESTER_BACKTESTING_FINISHED, 
            self.process_backtesting_finished_event)
经过简单测试，这样改代码没有问题。如果我理解的是对的，这样的代码又少又直观。但我不敢确定，也许vn.py的开发者另有深意吧。

**Comment by vnpy** [comment]
Qt编程中的一个重要知识点：不能在Qt事件循环以外的线程中，直接调用对Qt图形组件进行修改操作，否则可能因为冲突导致程序崩溃。

如果要这么做，必须通过Signal/Slot机制来实现这种跨线程的通知调用。
