### ISSUE TITLE
MT5委托状态“提交中”，交易触发异常已停止

### ISSUE THREAD

**Issue by linst95** [vnpy/vnpy#2590]
## 环境

* 操作系统: Windows 10
* vn.py版本: VNStudio-2.1.4

## Issue类型
Bug

## 预期程序行为
委托已撤销/成功提交

## 实际程序行为
VN Trader主界面显示委托“提交中”，CTA策略界面显示“触发异常已停止”

## 截图
<img width="858" alt="1" src="https://user-images.githubusercontent.com/25526144/87931323-f6bde280-cacc-11ea-9457-69607d141bb6.PNG">
<img width="1241" alt="2" src="https://user-images.githubusercontent.com/25526144/87931451-2e2c8f00-cacd-11ea-94a7-a742203146ab.PNG">

**Comment by vnpy** [comment]
已修复
