### ISSUE TITLE
bybit交易所正向合约，使用一个没有交易过的账号登入时报错

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2594]
C:\Users\Administrator>python -m vnstation
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
[2020-07-22T14:07:06.373781]: Unhandled RestClient Error:<class 'KeyError'>
request:request : GET /private/linear/order/list error because 200:
headers: {'Referer': 'vn.py'}
params: {'symbol': 'BTCUSDT', 'limit': 50, 'page': 1, 'api_key': 'u2EhilD0Pr1Zauikm5', 'recv_window': 30000, 'timestamp': 1595398021311, 'sign': 'f93a76ea051f53e086eb7df5e5ffb0849964b4f8c26a29953ce10f3f34322624'}
data: None
response:{"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"current_page":1,"data":[{"order_id":"8b2359be-7aac-4d9e-b524-a9ac2ca5e1e8","user_id":804109,"symbol":"BTCUSDT","side":"Buy","order_type":"Limit","price":9342,"qty":0.001,"time_in_force":"GoodTillCancel","order_status":"Cancelled","last_exec_price":0,"cum_exec_qty":0,"cum_exec_value":0,"cum_exec_fee":0,"reduce_only":false,"order_link_id":"","created_time":"2020-07-22T05:56:19Z","updated_time":"2020-07-22T05:56:28Z"}]},"time_now":"1595398026.355384","rate_limit_status":599,"rate_limit_reset_ms":1595398026350,"rate_limit":600}

Exception trace:
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\api\rest\rest_client.py", line 272, in _process_request
    request.callback(json_body, request)
  File "C:\vnstudio\lib\site-packages\vnpy\gateway\bybit\bybit_gateway.py", line 503, in on_query_order
    if result["current_page"] != result["last_page"]:
KeyError: 'last_page'

**Comment by vnpy** [comment]
已修复
