### ISSUE TITLE
IB的tick数据一秒钟可能有十几个甚至几十个，运行策略的时候造成堵车，造成时间延迟或者数据缺失

### ISSUE THREAD

**Issue by heshibs** [vnpy/vnpy#2597]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.4
* vn.py版本: VNStudio-2.1.4

## Issue类型
三选一：Question

## 预期程序行为
国内期货CTP的tick数据都是一秒2个，策略运行起来合成K线计算指标比较准确

## 实际程序行为
国内期货CTP的tick数据都是一秒2个，策略运行起来合成K线计算指标比较准确，但是IB的tick数据一秒钟可能有十几个甚至几十个，运行策略的时候造成堵车，造成时间延迟或者数据缺失，合成K线、计算指标误差会很大，请问这个有什么好的解决办法吗？
使用的CL-20200820-USD-FUT.NYMEX合约，tick数据输出如下图
![123](https://user-images.githubusercontent.com/37288834/88268060-636ef200-cd04-11ea-8b22-e45c6e05ea58.jpg)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by rjl02468** [comment]
IB一般是250ms推送一次tick

**Comment by vnpy** [comment]
1. IB的tickPrice/tickSize等函数，是每当有250ms有变化时就会立即推送（分开调用的），而不是像国内的TICK一样是500ms一次的切片，所以确实会有更多的tick事件
2. 对于CTA策略来说，一秒十几个TICK完全没有影响，即使来个50-100个TICK应该影响也不明显，如果出现明显卡顿建议检查策略on_tick函数下的相关逻辑，是否耗时过长
