### ISSUE TITLE
gateway调用close之后未关闭注册事件的bug

### ISSUE THREAD

**Issue by chuwt** [vnpy/vnpy#2599]
存在部分gateway中注册了事件（EVENT_TIMER）后，在关闭gateway(close方法)时未取消事件，导致事件在gateway关闭后仍运行。特别是1s一次的rest请求，在关闭了gateway之后会积攒在queue中，等重新连接gateway时，会迸发大量请求，导致api请求上限触发，封ip

**Comment by vnpy** [comment]
close函数，是由MainEngine在程序退出时调用，用来断开接口连接的，正常情景随后就会立即关闭进程，所以不会出现上述问题
