### ISSUE TITLE
如何在vntrader界面的委托和成交后面添加一栏策略名称呢？ 实盘测试不确定某个委托号对应的是那个策略

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2600]
## 环境

* 操作系统: 如Windows 10
* Python版本: python3.7
* vn.py版本: v2.1.4发行版

## Issue类型
三选一：Enhancement

预期程序行为

在vntrader界面的委托和成交后面添加一栏策略名称，确定某个委托号对应的是那个策略

实际程序行为

vntrader界面的委托和成交只有委托号， 实盘测试时发现策略一个bug，因为启动了10个策略，所以不确定某个委托号对应的是那个策略，排查半天，找不出来，十分着急

## 重现步骤

![Pic00001](https://user-images.githubusercontent.com/60735134/88399284-3d774980-cdf9-11ea-9bea-b5989ac4599c.jpg)

**Comment by vnpy** [comment]
这里可以自行通过以下数据关系实现：
1. 下单时的OrderRequest对象，带有可选的reference字段（委托参考信息）
2. 下单后立即获取该委托的委托号vt_orderid，缓存vt_orderid和reference的映射关系
3. 后续收到事件推送的OrderData和TradeData后，通过vt_orderid的映射关系，即可知道是来自某个策略
4. 主界面显示的内容，只包括原始底层接口推送的数据信息，而该映射需要上层模块支持才能实现
5. 因此不适合在主界面添加，有需要可以自行定制相关的图形组件
