### ISSUE TITLE
直达期货下单出错

### ISSUE THREAD

**Issue by zoulux** [vnpy/vnpy#2601]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.5.1
* vn.py版本: 2.1.4

## Issue类型
三选一：Bug

## 预期程序行为
可以下单

## 实际程序行为
一直显示提交中，并且没有打印错误日志

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

<img width="1680" alt="WechatIMG14" src="https://user-images.githubusercontent.com/9365514/88478727-36794400-cf7d-11ea-822c-b0f9d3a853ff.png">
<img width="1680" alt="WechatIMG25" src="https://user-images.githubusercontent.com/9365514/88478735-442ec980-cf7d-11ea-9f11-9eeaa544e8d5.png">

**Comment by vnpy** [comment]
这里没有报错信息，应该不是客户端的vn.py问题，可能是直达测试服务器不支持该合约。

推荐用日元合约JY试试。

**Comment by zoulux** [comment]
我用直达自己的客户端是可以的，可以看到我的持仓是有 CL 合约的

**Comment by zoulux** [comment]
@vnpy 客户端不报错，我猜测是客户端的log有问题

**Comment by vnpy** [comment]
我这边测试了下没问题，最近直达接口做了些升级，可以先试试手动更新DEV分支的代码

**Comment by zoulux** [comment]
vn Station 如何切换分支

**Comment by vnpy** [comment]
VNStation是安装版本的程序，没有分支切换功能，请在Github上找到DEV分支的代码下载吧

**Comment by zoulux** [comment]
👌 我测试一下 后面给你反馈

**Comment by zoulux** [comment]
我这边 install 之后，然后使用 ` python -m vnstation` 启动对吗？
现在控制台报两个错误，
```qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
```
```
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
```
然后依然提交不成功。
![image](https://user-images.githubusercontent.com/9365514/89369418-a1aadf00-d710-11ea-98c2-6df0f6e3a254.png)
