### ISSUE TITLE
gateway ws重连之后没有重新订阅tick和bar的问题

### ISSUE THREAD

**Issue by chuwt** [vnpy/vnpy#2602]
gateway的websocket重连之后并不会重新订阅之前的subscribe，导致tick和bar数据在重连之后没有反馈，程序名存实亡，所以建议在订阅的时候将订阅保存，之后重连重新发送订阅

**Comment by vnpy** [comment]
请说明具体的接口？

**Comment by chuwt** [comment]
@vnpy 比如我启动了一个策略，然后策略通过(main_engine.subscribe)方法订阅了某个gateway的交易对的tick和bar数据，然后接受回报。
当该Gateway的websocket因为异常原因终止重连后，只会执行重连的on_connected方法，没有把之前subscribe的交易对重发，导致策略的tick和bar数据的回报就没有了，此时策略虽然正常运行，但是tick和bar数据已经收不到了

**Comment by vnpy** [comment]
具体是哪个gateway没有实现这块逻辑？因为大部分官方开发的接口，我们应该是实现了的

**Comment by chuwt** [comment]
HUOBI
