### ISSUE TITLE
捷仕MT5中有后缀‘.’的交易品种，加载策略后报错

### ISSUE THREAD

**Issue by houyingxu** [vnpy/vnpy#2603]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.4

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
正常加载与下单

## 实际程序行为
报错提示并停止

## 重现步骤
正常的策略加载操作

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![微信截图_20200727130950](https://user-images.githubusercontent.com/58158372/88505742-e5b02c80-d00a-11ea-8d76-500f9adaf6fa.png)

**Comment by houyingxu** [comment]
版本号写错了，VN Trader是  2.1.4 ， VN Station 是 2.5.1

**Comment by vnpy** [comment]
已在DEV分支修改
