### ISSUE TITLE
vnpy1.9.2版本，安装在windows Server的哪个版本上比较稳定

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2605]
## 环境

* 操作系统: windows Server xxx
* vn.py版本: 如v1.9.2

## Issue类型
三选一：Question

## 预期程序行为

群主，您好

请问定制的服务器或者说云服务器，对于V1.9.2版本的，windows Server用哪个版本的最稳定？
比较推荐那几个操作系统的版本？

因为是windows Server 2012~20xx 的版本，硬件系统配置有要求吗？比较合适的配置是哪类的？

可能的机器配置：2cpu，16g内存，固态硬盘128g，主板？、网卡？
这样的配置，是否在  window server   的服务器上跑起来不卡？ 大概交易20个标的的。

谢谢！

**Comment by vnpy** [comment]
1.9.2之前一直用Server 2012开发的，这个配置正常运行应该没啥问题了，注意不要买【突发性能实例】即可
