### ISSUE TITLE
PortfolioStrategy无on_trade和on_order

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2606]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 2.1.2

## Issue类型
三选一：Question

## 预期程序行为
PortfolioStrategy有on_trade和on_order。如果有on_trade，可以在开仓成功后第一时间进行平仓挂单，如果没有该如何进行？

## 实际程序行为
没有on_trade,on_orders
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
PortfolioStrategy针对的多标的组合策略，最低也就是分钟线级别运行的，所以不需要on_trade/on_order回调函数，同时在回测中也无法保证时间前后的一致性，所以不会提供。
