### ISSUE TITLE
vnpy1.9.2版本可以连接 IB Gateway 而不是tws吗

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2607]
## 环境

* 操作系统: 如windows server 2012
* vn.py版本: vnpy1.9.2

## Issue类型
三选一：Question

## 实际程序行为
群主，您好

咨询下，vnpy1.9.2版本，可以连接 IB Gateway 而不通过tws连接吗？

如果可以连接，对 IB Gateway 的版本有要求吗？具体那几个版本可以，哪个版本是最推荐的版本？
是否可以用带有FIX CTCI（ib的一种专线连接模式，相当于国内专线连接到ib香港或者ib美国的服务器端） 的IB Gateway 连接？

如果可以连接，是否有这方面的简要说明？在vnpy.com上搜索了ibGateway，没找到任何对应的资料的。
如果可以连接，在windows server 2012上是可以的，对吗？

是否还有其他的特殊要求或者注意事项，恳请您指点下，谢谢！

谢谢！

**Comment by vnpy** [comment]
1. 可以对接，具体版本要求不确定了，因为1.9.2太老了
2. 不支持FIX协议，而是走的IB API
3. 老版本已经停止维护，2012应该可以运行，但不推荐使用了
