### ISSUE TITLE
精简深度行情结构体

### ISSUE THREAD

**Issue by tel13908519494** [vnpy/vnpy#262]
作为vnpy的爱好者兼一个文科生，希望用文科生的思维方式为vnpy做一点贡献。今天的建议是简化深度行情结构体。深度行情结构体显然是考虑到了股票交易的需要，对于大多期货交易者来说，现在的结构体数据冗余，简化确有必要。另外，现结构体的行情数据中前收、前结、前仓等数据是静态的，每一个TICK都处理这些数据比较浪费计算和存储资源，因此可将TICK的深度行情结构体一分为二，即动态部分和静态部分。具体见代码吧：
void MdApi::processRtnDepthMarketData(Task task)
{
	PyLock lock;
	CThostFtdcDepthMarketDataField task_data = any_cast<CThostFtdcDepthMarketDataField>(task.task_data);
	dict data;
	dict data0;
//data字典用于传递静态行情，DATA0字典用于传递动态行情
//注释掉的结构体字段要么没有数据，要么无用，推送给PYTHON后再处理是相当为难PYTHON的
	data0["ExchangeInstID"] = task_data.ExchangeInstID;
	data0["ExchangeID"] = task_data.ExchangeID;
	data0["PreSettlementPrice"] = task_data.PreSettlementPrice;
	data0["PreClosePrice"] = task_data.PreClosePrice;
	data0["PreOpenInterest"] = task_data.PreOpenInterest;
	data0["UpperLimitPrice"] = task_data.UpperLimitPrice;
	data0["LowerLimitPrice"] = task_data.LowerLimitPrice;
	data0["TradingDay"] = task_data.TradingDay;
	data["InstrumentID"] = task_data.InstrumentID;
	data["TradingDay"] = task_data.TradingDay;
	data["UpdateTime"] = task_data.UpdateTime;
	data["OpenPrice"] = task_data.OpenPrice;
	data["LastPrice"] = task_data.LastPrice;
	data["OpenInterest"] = task_data.OpenInterest;
	data["Volume"] = task_data.Volume;
	//data["ClosePrice"] = task_data.ClosePrice;
	data["LowestPrice"] = task_data.LowestPrice;
	data["HighestPrice"] = task_data.HighestPrice;
	data["AveragePrice"] = task_data.AveragePrice;
	//data["SettlementPrice"] = task_data.SettlementPrice;
	data["AskPrice1"] = task_data.AskPrice1;
	data["AskVolume1"] = task_data.AskVolume1;
	data["BidPrice1"] = task_data.BidPrice1;
	data["BidVolume1"] = task_data.BidVolume1;	
	//data["BidPrice5"] = task_data.BidPrice5;
	//data["BidPrice4"] = task_data.BidPrice4;
	//data["BidPrice3"] = task_data.BidPrice3;
	//data["BidPrice2"] = task_data.BidPrice2;
	//data["AskPrice5"] = task_data.AskPrice5;
	//data["AskPrice4"] = task_data.AskPrice4;
	//data["AskPrice3"] = task_data.AskPrice3;
	//data["BidVolume5"] = task_data.BidVolume5;
	//data["BidVolume4"] = task_data.BidVolume4;
	//data["BidVolume3"] = task_data.BidVolume3;
	//data["BidVolume2"] = task_data.BidVolume2;
	//data["AskPrice2"] = task_data.AskPrice2;
	//data["AskVolume3"] = task_data.AskVolume3;
	//data["AskVolume2"] = task_data.AskVolume2;
	//data["AskVolume5"] = task_data.AskVolume5;
	//data["AskVolume4"] = task_data.AskVolume4;
	//data["UpdateMillisec"] = task_data.UpdateMillisec;
	//data["PreDelta"] = task_data.PreDelta;
	//data["CurrDelta"] = task_data.CurrDelta;
	//data["Turnover"] = task_data.Turnover;
	//data["ActionDay"] = task_data.ActionDay;

	this->onRtnDepthMarketData(data,data0);
};
有基础的朋友记得修改onRtnDepthMarketData的参数，PYTHON行情回调部分参数是两个。

**Comment by vnpy** [comment]
CTP的期权是有5档行情的，如果你只用CTP做期货可以这么改下，另外这种经验分享请发到vnpy.org上

**Comment by we1559** [comment]
@vnpy 大商所的期货有level2的行情，现在好像是10档来着

**Comment by vnpy** [comment]
@we1559 那个需要用大商所L2 API，另外售价是30W一年
