### ISSUE TITLE
币安期货request返回错误

### ISSUE THREAD

**Issue by yunnant** [vnpy/vnpy#2620]
## 环境

* 操作系统: mac
* Python版本: 3.76
* vn.py版本: 2.14
## Issue类型
三选一：Bug
## 实际程序行为
放置一段时间出现截图的错误

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/10345996/89474764-8366d280-d754-11ea-9a8f-a2dbd65fdf4b.png)

**Comment by vnpy** [comment]
无法重现，猜测可能是临时性的服务器错误，如果持续出现请提供更多细节
