### ISSUE TITLE
关于IB无法使用RPC直接拉取历史数据初始化的咨询 

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2622]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.4
* vn.py版本: v2.1.4

## Issue类型
Enhancement

## 实际程序行为
**1:老师您好，咨询一下，如果直接使用vntrader连接ib gateway的话，可以正常从ib gateway拉取历史数据初始化，一般5个策略初始化时间为3分钟左右，但是如果使用RPC服务器进行CTA策略的初始化，5个策略就会在1秒内直接初始化完成，这种差距太大了，是否是RPC无法从API拉取历史数据进行初始化呢？ 只能是实时行情的数据推送？望Enhancement这个功能，万分感激！**

**Comment by vnpy** [comment]
RPC接口，没有支持历史数据查询功能，因为大部分接口是不支持历史数据查询的，所以无法通过RPC来支持
