### ISSUE TITLE
安装时WMI模块报错

### ISSUE THREAD

**Issue by CACppuccino** [vnpy/vnpy#2624]
## 环境

* 操作系统: Ubuntu 16.04
* Python版本: Python3.7，基于Anaconda
* vn.py版本: 2.1.4

## Issue类型
Question

## 预期程序行为
运行 `bash install.sh` 安装成功

## 实际程序行为
在安装wmi模块时，报错，显示找不到 pywin32 模块。

## 注释
我尝试了Anaconda和Virtuualenv来安装python package，都遇到了相同的问题，请问如何在linux系统中解决这个问题

**Comment by vnpy** [comment]
请删除requirements.txt里的wmi，再执行安装即可。

目前vn.py支持的接口数量太多，不同接口存在许多不同的依赖，后续3.0会做拆分了
