### ISSUE TITLE
有考虑使用IB官方的PYTHON接口吗？

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#263]
使用官方的接口不用考虑以后的维护问题。反正它官方会更新维护。整合起来应该比较省事。

现在越来越多人使用了python3了，
要不我们也弄两个版本？一个py2, 一个 py3?
py2就是目前这个全功能版的。
py3就是精简版的，只有ctp,ib等几个接口。
同时考虑py3是大势所趋，早晚要换过去，不如逐步一边换过去。

**Comment by vnpy** [comment]
可以考虑做一个py3的分支或者单独的文件夹

**Comment by hackerwei** [comment]
支持切换python3版本

**Comment by nehCkirE** [comment]
python3 64位 qt5

**Comment by akeyong** [comment]
赞同，py3是大势所趋，早晚要换过去

**Comment by shaoupipi** [comment]
talib wrapper都支持py3了，的确没理由继续用py2了

**Comment by vnpy** [comment]
我个人目前暂时没有精力来维护一个py3的分支，同时vnpy的项目也还在快速迭代的阶段，所以这块暂时就不做了。

未来如果移植到py3，会将ibGateway采用的接口改为ib提供的python封装
