### ISSUE TITLE
火币现货接口ws 问题，请官方帮助修复

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2631]
https://www.vnpy.com/forum/topic/4248-huo-bi-xian-huo-wsjie-kou-wen-ti-qing-jiao-zen-yao-xiu-gai-huo-bi-xian-huo-wsjie-kou-xiu-fu-yi-xia-wen-ti
火币现货接口ws 出现假死问题，只要开启现货接口不作任何操作（只获取行情数据）运行一天左右肯定出现链接上的问题，cmd上有时有报错代码，有时没有。关闭重启后又正常。运行一些时间又出现。

**Comment by 1122455801** [comment]
发现是火币服务器推送行情问题，如EHTUSD，bids只有3档，而ask有十来档。
![微信图片_20200818154131](https://user-images.githubusercontent.com/45591222/90484836-53aec600-e169-11ea-9633-d05938ec1c00.png)

解决方法是在gateway上，通过len来获取深度行情档数，与5对比，取最小值
修改前：
![微信图片_20200818154333](https://user-images.githubusercontent.com/45591222/90485072-9f616f80-e169-11ea-8b16-ae34082be469.png)
修改后
![微信图片_20200818154339](https://user-images.githubusercontent.com/45591222/90485097-a6887d80-e169-11ea-9276-e367901e54dc.png)

**Comment by vnpy** [comment]
> 发现是火币服务器推送行情问题，如EHTUSD，bids只有3档，而ask有十来档。
> ![微信图片_20200818154131](https://user-images.githubusercontent.com/45591222/90484836-53aec600-e169-11ea-9633-d05938ec1c00.png)
> 
> 解决方法是在gateway上，通过len来获取深度行情档数，与5对比，取最小值
> 修改前：
> ![微信图片_20200818154333](https://user-images.githubusercontent.com/45591222/90485072-9f616f80-e169-11ea-8b16-ae34082be469.png)
> 修改后
> ![微信图片_20200818154339](https://user-images.githubusercontent.com/45591222/90485097-a6887d80-e169-11ea-9276-e367901e54dc.png)

我们检查了代码，上面这个情形并不会导致WS断开，火币官网的API文档里也没有提到明确的多长时间会断开数据推送的信息。

vn.py的WebsocketClient中都有内置了ping-pong的心跳回复机制，而且即使断开也会收到正式断开的信息。

**Comment by vnpy** [comment]
之前缺失了断线后自动重新订阅的逻辑，已修复
