### ISSUE TITLE
仿真看穿测试要求6.3.13版本，而CTPTEST对应6.3.16，请问应如何完成看穿测试？

### ISSUE THREAD

**Issue by forhonourlx** [vnpy/vnpy#2632]
Hi @vnpy 

国金期货仿真看穿测试要求6.3.13版本，而现在使用的VNPY 2.1.4 CTPTEST对应6.3.16，请问有何办法完成仿真看穿测试？
恳请赐教，衷心感谢。

## 环境
* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.4

**Comment by Gwill** [comment]
直接把对应的 dll 文件替换试试

**Comment by vnpy** [comment]
可以让国金期货联系我们这边来做下对接测试。

**Comment by forhonourlx** [comment]
@vnpy @Gwill 
请问下：除了`gateway\ctptest\`下`thostmduserapi_se.dll`和`thostmduserapi_se.dll`替换成6.3.13版本，32位？
`vnctpmd.pyd`和`vnctptd.pyd`是否需要调整？

最后vnpy团队，请问应该如何联系你们？联系方式可否私信？感谢。

**Comment by Gwill** [comment]
pyd 不需要动，直接换 dll ，试一下，有的版本可以

**Comment by forhonourlx** [comment]
使用VNSTUDIO 2.0.8的CTPTEST 6.3.13依然连接仿真失败。
然后直接使用VNSTUDIO 2.1.5的CTP(非CTP TEST)可以连接仿真。
