### ISSUE TITLE
CTA回测报错

### ISSUE THREAD

**Issue by TIANRENK** [vnpy/vnpy#2633]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本:2.1.2

## Issue类型
三选一：Bug

## 预期程序行为
正常回测

## 实际程序行为
回测报错，在调用back_testing()函数的时候，backtesting.py文件中 self.callback(data),  self.callback是None，我检索了backtesting.py 发现只有调用self.load_tick 或者self.load_bar 才会的self.callback赋值， 但是回测的demo中没有发现有调用这两个函数，那么self.callback是怎么被赋值的

## 重现步骤
backtesting.py中run_backtesting()函数中 self.callback(data)报错，TypeError: 'NoneType' object is not callable
            try:
                self.callback(data)
            except Exception:
                self.output("触发异常，回测终止")
                self.output(traceback.format_exc())
                return

**Comment by vnpy** [comment]
所有自带策略中，在on_init函数下都有调用load_bar函数来做初始化。

没有调用的TestStrategy是用来执行功能测试的，不支持回测。
