### ISSUE TITLE
组合投资策略回测的问题

### ISSUE THREAD

**Issue by breadbread1984** [vnpy/vnpy#2635]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.5.1
* vn.py版本: v2.1.4

## Issue类型
三选一：Question

## 预期程序行为

组合投资策略可以在每天开盘时间不同的合约上进行。

## 实际程序行为

在开盘时间不同的合约上回测会报错误“数据缺失”。

## 重现步骤

比如在'IF99.CFFEX', 'I99.DCE', 'CU99.SHFE', 'TA99.CZCE'四种合约上回测。IF99每天9:15开盘，其他是9:00。回测时候就会发生这样的问题。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

[错误截图](https://static.vnpy.com/upload/temp/db418db7-510e-4738-985e-99f67e4717b4.png)

**Comment by vnpy** [comment]
2.1.5已经修改了
