### ISSUE TITLE
okex现货接口，挂个止损单时，再启动vnpy时报错。

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2642]
okes 现货接口，我手动挂了个eos卖出单（限价止损），然后再启动vnpy时联接接口时报错如下：

C:\Users\Administrator>python -m vnstation
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
[2020-08-23T10:00:10.396711]: Unhandled RestClient Error:<class 'TypeError'>
request:request : GET /api/spot/v3/orders_pending error because 200:
headers: {'OK-ACCESS-KEY': '1baec52c-08fa-45ee-84ee-d009f5853c92', 'OK-ACCESS-SIGN': b'IYLZ3eGFWzFOFHinpThu7uygsu1l4xiqRttfOMInWnE=', 'OK-ACCESS-TIMESTAMP': '2020-08-23T10:00:10.349Z', 'OK-ACCESS-PASSPHRASE': '376166910Yc01', 'Content-Type': 'application/json'}
params: None
data: null
response:[{"client_oid":"","created_at":"2020-08-23T09:57:10.241Z","fee":"","fee_currency":"","filled_notional":"0","filled_size":"0","funds":"","instrument_id":"EOS-USDT","notional":"","order_id":"5468365143421952","order_type":"0","price":"3.303","price_avg":"0","product_id":"EOS-USDT","rebate":"","rebate_currency":"","side":"sell","size":"1.4985","state":"0","status":"open","timestamp":"2020-08-23T09:57:10.241Z","type":"limit"}]

Exception trace:
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\api\rest\rest_client.py", line 272, in _process_request
    request.callback(json_body, request)
  File "C:\vnstudio\lib\site-packages\vnpy\gateway\okex\okex_gateway.py", line 381, in on_query_order
    datetime=generate_datetime["timestamp"],
TypeError: 'function' object is not subscriptable

**Comment by vnpy** [comment]
已修复，非常感谢
