### ISSUE TITLE
OKex交割合约下单参数设置错误

### ISSUE THREAD

**Issue by catplay** [vnpy/vnpy#2645]
## Issue类型
Bug

## vnpy中okexf_gateway.py
![image](https://user-images.githubusercontent.com/26114198/91146537-9a606b00-e6e9-11ea-8500-fca3830ecc5a.png)

## OKex文档
https://www.okex.com/docs/zh/#futures-orders
![image](https://user-images.githubusercontent.com/26114198/91146653-c11ea180-e6e9-11ea-81dc-64b8f9455259.png)

**Comment by vnpy** [comment]
类型映射问题，已在DEV分支修复
