### ISSUE TITLE
投资组合没有同步更新时区字段

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2646]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: dev

## Issue类型
三选一：Bug

## 预期程序行为
None

## 实际程序行为
time字段报错

## 重现步骤
开启投资组合下单。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/12085501/91443373-d3ddd580-e8a5-11ea-8f01-7ac4f689c59f.png)

**Comment by vnpy** [comment]
已修复
