### ISSUE TITLE
价格跳动和交易滑点

### ISSUE THREAD

**Issue by huluBrother** [vnpy/vnpy#2647]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.5.1
* vn.py版本: 

## Question
这个价格跳动和交易滑点是什么意思？

## 重现步骤

![image](https://user-images.githubusercontent.com/18010792/91545564-ca12ab80-e953-11ea-9694-4de1c55ec1d8.png)

**Comment by vnpy** [comment]
价格跳动，是合约价格的最小变动单位。

交易滑点，是平均每次交易成交价和发单预期成交价的差别。
