### ISSUE TITLE
你好，请问下，目前linux版本的还未支持okcoin的业务对接吗？

### ISSUE THREAD

**Issue by xiyanxiyan10** [vnpy/vnpy#265]
1. 刚初步接触该项目。看了下说明ubuntu版本未提到对okCoin的支持。

2. 但看该平台接口是python的, 应该可以跨平台，确认下ubuntu对OKCoin是否支持.

3.不支持的话后续会支持吗？

**Comment by vnpy** [comment]
ubuntu版本可以使用okcoin接口，自己安装websocket客户端模块

`pip install websocket-client`

**Comment by xiyanxiyan10** [comment]
哇，谢谢大侠
