### ISSUE TITLE
请教vnpy中对对象 做copy.deepcopy(spread) 报错TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2655]
## 环境

* vn.py版本: v2.0.5

## Issue类型
三选一：Question

## 实际程序行为

群主，您好

请教个问题，

做数据分析，就是把 spread 的数据 tick 层一直保存下来做分析，用了创建类 StSpread 的新对象，然后用__dict__的方式把 spread.__dict__ 赋值给了new_spread.__dict__, 此时 new_spread 的id是新的id的了，但是 new_spread 里边的腿的 id 确一直都是一样的呢，如何才能让 new_spread 中的leg的也是新的id呢，不受到spread更新价格时候的影响？
是不能用 copy.deepcopy(spread) 的方式生成新的 new_spread 的，因为 spread是被注册了event的了。

试过对 new_spread 再次做深度拷贝赋值给一个新的对象，仍旧不行的，报错：TypeError: can't pickle thread.lock objects，
恳请百忙中指导下在vnpy中如何处理这类spread（将多个spread的数据记录到list中，然后需要倒序循环，此时spread中的legs上的数据都是同一个了）和leg的tick层数据深度拷贝并保存问题，谢谢！

**Comment by vnpy** [comment]
1. SpreadData和LegData存在内存中的映射关系，所以应该不适合直接做deepcopy操作
2. 建议自己创建一个字典，然后将SpreadData和LegData中对应字段的数据逐个写进去，保存这个字典即可
