### ISSUE TITLE
回测引擎不能多次set_parameters

### ISSUE THREAD

**Issue by breadbread1984** [vnpy/vnpy#2657]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: 3.8.2
* vn.py版本: v2.1.5

## Issue类型
三选一：Bug

## 预期程序行为

回测引擎对象每次set_parameters，应该清空上次回测的数据。

## 实际程序行为

回测引擎对象每次set_parameters，没有清空上次回测的数据。所有新创建挂单数据都是和之前回测的挂单数据叠加的。

## 重现步骤

保持一个回测引擎对象不销毁，重复set_parameters，load_data，run_backtesting。就会从第二次回测开始，之前的数据都保持。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 调用clear_data函数清空下之前回测的缓存数据即可
2. 一般不建议重复使用，直接重新创建个对象更方便
