### ISSUE TITLE
沪深300 期权 计算的隐含波动率很大，是什么原因呢？

### ISSUE THREAD

**Issue by xueshufeng** [vnpy/vnpy#2663]
## 环境

* 操作系统: 如Windows 10 

沪深300的期权隐含波动率计算很大，不知道什么原因 

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
       在程序中加了个打印：
        try:
            self.askImpv = self.calculateImpv(self.askPrice1, underlyingPrice, self.k,
                                          self.r, self.t, self.cp)
            self.bidImpv = self.calculateImpv(self.bidPrice1, underlyingPrice, self.k,
                                              self.r, self.t, self.cp)
            self.midImpv = (self.askImpv + self.bidImpv) / 2

            if self.midImpv > 20:
                print("midImpv :"+str(self.midImpv) +" askPrice1:"+str(self.askPrice1) +" s"+str(self.bidPrice1) +" underlyingPrice  ："+ str(underlyingPrice))

        except ZeroDivisionError:

     下面是打印的值：
       这里k是4900
       midImpv  : 575062173.5229
      askPrice1:   292.2
      bidPrice1： 290.0
      underlyingPrice ： 4628.5131

**Comment by vnpy** [comment]
请问用的是什么版本的vn.py？

**Comment by xueshufeng** [comment]
我搞错了，把沪深300 IO搞成美式期权了。
