### ISSUE TITLE
ArrayManager的ad()报错

### ISSUE THREAD

**Issue by breadbread1984** [vnpy/vnpy#2666]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: 3.8.2
* vn.py版本: v2.1.5发行版

## Issue类型
三选一：Bug

## 预期程序行为

ArrayManager可以正常计算ad()

## 实际程序行为

报错，talib.AD()函数需要4个参数，给了5个参数。最后一个n不需要。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
