### ISSUE TITLE
建议vnpy团队在回测报告中加入胜率和盈亏比，看见vnpy论坛有很多忠实粉丝都在说有这个需求

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#2667]
## 环境

* 操作系统: 如Windows 10
* Python版本:3.7.1
* vn.py版本: v2.1.5

Enhancement
1：建议vnpy团队在回测报告中加入胜率和盈亏比，逛了一下论坛，看见论坛中有很多忠实粉丝都在说有这个需求！

**Comment by yhmickey** [comment]
这个在vnpy\examples\cta_backtesting\trade_by_trade.ipynb里

**Comment by vnpy** [comment]
楼上正解
