### ISSUE TITLE
使用paper_account问题

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2673]
连接实盘之后，在CTA策略初始化时，日志显示： 找不到底层接口：PAPER

请问，这个是正常的吗？

**Comment by vnpy** [comment]
我们来查下，这个应该和历史数据查询有关系...请问用的什么交易接口呢？

**Comment by yhmickey** [comment]
BITMEX

**Comment by yhmickey** [comment]
试了下BINANCE初始化时，参数也未能初始化，可能和历史数据有关

**Comment by yhmickey** [comment]
用了Paper后，ChartWizard也报 找不到底层接口：PAPER ， 无法绘图，BINANCE

**Comment by vnpy** [comment]
已在DEV分支修复，2.1.7发布后更新下就行
