### ISSUE TITLE
bybiy 交易所运行反向合约时报错  <class 'KeyError'>，信息：'create_time' 

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2674]
## 环境 window 10

* Python版本: 如VNStudio-2.1.6

bybiy 交易所运行反向合约时报错  <class 'KeyError'>，信息：'create_time' ，查询交易接口文档时发现正向合约与反向合约字段不一样。

![image](https://user-images.githubusercontent.com/57986593/93730593-df4dc380-fbfb-11ea-936e-e908573ed9d0.png)

**Comment by vnpy** [comment]
已修复
