### ISSUE TITLE
使用多进程或遗传算法寻优时的问题

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2675]
测试了好几次，多参数寻优后的结果与相同参数的单独回测的结果（sharp等）不同
可能是寻优函数有问题，但也没找出来原因
目前只是看到backtesting文件最下面一行缺少inverse变量。
如方便，也请做下测试

**Comment by vnpy** [comment]
请尝试下用自带策略AtrRsiStrategy进行优化，是否也会出现这样的情况？

**Comment by yhmickey** [comment]
又换了几个策略，重新测试了一遍，没有问题。
之前出现的问题不知道是怎么出来的。。。
