### ISSUE TITLE
二叉树期权定价模型有bug

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2676]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.7.1
* vn.py版本: v2.1.6
![QQ图片20200922145710](https://user-images.githubusercontent.com/12085501/93852059-e51ed400-fce3-11ea-93f6-ee79b4fee79c.png)

## Issue类型
三选一：Bug
## 预期程序行为
None
![QQ图片20200922145650](https://user-images.githubusercontent.com/12085501/93852043-dafcd580-fce3-11ea-8696-ccfb7370a0df.png)

![QQ图片20200922145614](https://user-images.githubusercontent.com/12085501/93852002-c91b3280-fce3-11ea-871e-26c2319921cb.png)

## 重现步骤
正常启动一个商品期权使用二叉树定价模型

**Comment by vnpy** [comment]
已修复，之前的定价模型中缺失了二叉树每步回溯的折现

**Comment by jieyujing** [comment]
赞

vn.py <notifications@github.com> 于2020年10月25日周日 下午9:28写道：
