### ISSUE TITLE
cta_strategy remove_strategy 没有 remove_strategy_data

### ISSUE THREAD

**Issue by TangPere** [vnpy/vnpy#2677]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: python3.7
* vn.py版本: 2.1.6

## Issue类型
Bug

## 预期程序行为
remove_strategy 时 remove_strategy_data

## 实际程序行为
remove_strategy 时 没有 remove_strategy_data

是有什么考量吗?

**Comment by vnpy** [comment]
如果修改策略代码后，想要不重启程序立即生效，可以重载策略，移除老的策略后重建一个同名新的，会自动加载之前的缓存状态
