### ISSUE TITLE
请问如何实现简单的CTP期货登陆下单、平仓、查询功能

### ISSUE THREAD

**Issue by liuminglm** [vnpy/vnpy#268]
我想用这个项目实现非常简单的功能，就是CTP期货登录、下单、平仓、查询功能，不想使用UI功能和其他的功能，只想使用命令行来操作，请问有没有相关的接口，可以直接使用，就像wind python接口一样，就是有登录、下单、平仓、查询的函数，可以直接调用

**Comment by akeyong** [comment]
请参考 https://github.com/vnpy/vnpy/issues/240
