### ISSUE TITLE
portfolio组合策略模块盘中停止推送tick

### ISSUE THREAD

**Issue by DLHNET** [vnpy/vnpy#2681]
## 环境

* 操作系统: 如Windows 10
* Python版本: vnpy-2.1.6
* vn.py版本: master

## Issue类型
三选一：Bug
## 预期程序行为
tick

## 实际程序行为
盘中随机不定时停止推送tick，实盘+simnow出现同样情况，portfolio的on_tick接收不到数据

## 重现步骤
实盘 OR simnow测试，加载PairTradingStrategy策略，在on_tick函数下面print(tick.__dict__)，一段时间后会收不到tick，无任何报错。
针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/32806757/95089723-0907fe00-0757-11eb-95ba-09cb7d626c98.png)

**Comment by xldistance** [comment]
策略里面哪里阻塞了吧

**Comment by DLHNET** [comment]
> 策略里面哪里阻塞了吧
应该是bars合成问题，调试了一下，一段时间后会出现on_bars收到的bars是None值，然后停止了推送

**Comment by xldistance** [comment]
组合策略一定要交易时间相同的标的放一个策略

**Comment by DLHNET** [comment]
> 组合策略一定要交易时间相同的标的放一个策略

同合约，跨月份，和标的交易时间应该无关

**Comment by vnpy** [comment]
测试无法重现，建议在on_tick函数顶部第一行加上print(tick)，看看是否TICK推送真正暂停。若无异常抛出，是不应该暂停的。
