### ISSUE TITLE
请问如何将bybit的反向合约的本地停止单改为交易所停止单，有没有朋友改过？

### ISSUE THREAD

**Issue by TrinityWater1991** [vnpy/vnpy#2684]

**Comment by vnpy** [comment]
我们回头来看下，理论上在接口层增加对停止单类型的支持就行

**Comment by TrinityWater1991** [comment]
> 我们回头来看下，理论上在接口层增加对停止单类型的支持就行

陈老师，我试着改了一下，发现bybit反向合约不支持同时下多头和空头支票的停止单，只能下一个方向的停止单，后下的会被拒单。询问了bybit官方API支持确认，确实如此。通道类策略同时下多头空头停止单是刚需。。。准备放弃bybit。。。

**Comment by vnpy** [comment]
啊。。。看来是他们底层净仓位撮合机制的问题了，这个确实没办法在vn.py客户端的层面来修改
