### ISSUE TITLE
为vn.py系统增加策略账户

### ISSUE THREAD

**Issue by hxxjava** [vnpy/vnpy#2685]
## 环境

* 操作系统: Windows 10或者Ubuntu 18.04
* Python版本: VNStudio-2.1.4以后

## Issue类型
三选一：Enhancement

### 为CTA策略引入策略账户
策略账户是一个虚拟的资金账户，与CTA策略模块中的策略实例对应。很好地解决用户算法对资金、保证金和手续费等参数的需求。
策略账户的功能：
1）策略账户为策略分配交易的初始资金，还可以做出金入金等虚拟操作，从而控制策略的交易规模。
2）管理交易合约实际使用的保证金（率）和手续费（率）
3）记录策略产出的委托单，并且可以查询策略历史委托单
4）记录策略初始的成交单，并且可以查询策略历史成交单
5）按笔计算策略的历史交易盈亏和当前交易的浮动盈亏
6）提供策略账户的本金、权益、保证金、手续费和可用资金查询功能
7）为策略动态仓位提供接口支持，可以进行策略账户风控设置，向策略输出风控报警信号。
8）策略账户提供的初始持仓、出金、入金、委托单和成交单查询功能，是策略交易活动可视化的必要保证。

## 实际程序行为
1）在用户策略的on_init()中创建策略账户，大致过程如下：
```
    def on_init(self):
        self.write_log("策略初始化")

        if self.engine_type == "LIVE":
            contract:ContractData = self.cta_engine.main_engine.get_contract(self.vt_symbol)
            self.contractsize = contract.size 
            self.pricetick = contract.pricetick
            if self.sam_engine.create_strategy_account(self.strategy_name,[self.vt_symbol],self.money_total,pickup_position=True):
                print(f"创建{self.strategy_name}策略账户成功,交易合约:{[self.vt_symbol]},初始资金:{self.money_total}")
            else:
                print(f"{self.strategy_name}策略账户已经存在！")
            self.sam_engine.notify_strategy_ui(self.strategy_name)
            cur_pos = self.sam_engine.get_strategy_account_cur_pos(strategy_name=self.strategy_name)
            print(f"{self.strategy_name}策略账户当前仓位：{cur_pos}")
        else:
            self.contractsize = self.cta_engine.size
            self.pricetick = self.cta_engine.pricetick

        # self.load_bar(days=20,callback=self.on_bar,use_database=True) 
        self.load_bar(days=23)      
```
2）启动策略后的系统就会显示如下图的界面
如果策略发生了成交单，那么在策略账户的显示区域就会显示对应策略账户的本金、权益、保证金、手续费和可用资金等信息。

### 先分享一下策略账户设计的最新成果
用户策略只需要调用策略账户引擎提供的接口，启动之初创建本策略实例的策略账户，策略账户引擎就可以在后台监视策略的交易活动了。它可以监视策略的每笔交易盈亏，分配资金的使用情况，保证金的占用情况，累计手续费，目前的可用资金（按分配资金计算）等信息，这些信息对用户策略是非常有用的。
#### 主界面面中多了个策略账户区域
![description](https://static.vnpy.com/upload/temp/44785bd6-2091-4a13-902f-e3f61df8de95.png)
#### 双点策略账户区域，进入策略账户管理界面
![description](https://static.vnpy.com/upload/temp/a69933d8-22cc-4415-9818-1c268186269a.png)
#### 这是策略的出入金管理界面
可以查询策略自创建以来的所有的出让金记录。当你策略中资金不足，你可以在此往策略账户中入金，当然如果策略很赚钱，你也可以通过出金减小策略的交易规模，做到落袋为安！
![description](https://static.vnpy.com/upload/temp/7dc7023c-2f73-4dbc-b583-58ffd9d809ab.png)
#### 这是策略账户中保存的属于本策略的历史委托单记录：
![strategyOrderDialog](https://user-images.githubusercontent.com/34177947/95754073-1849f700-0cd5-11eb-843c-228600b58094.png)
#### 这是策略账户中保存的属于本策略的历史成交单记录：
![description](https://static.vnpy.com/upload/temp/c976af83-c6d0-44e5-94a6-1624f7eea307.png)

**Comment by zfsamzfsam** [comment]
策略账户,应该能够支持多策略,尤其是支持多品种

**Comment by hxxjava** [comment]
# 对策略账户的更进一步的说明：
1）这里所说的策略账户其实与文华软件中的模组账户相似；
2）每个策略都可以选择是否创建策略账户；
3）策略账户的名称与创建它的策略实例同名；
4）不同策略实例使用它自己创建的策略账户，不需要支持多个策略；
5）策略账户支持多个品种（合约），它会在后台拦截所有的属于自己策略的委托单、成交单；
6）策略账户分品种按笔的方式管理策略的交易，并且实时计算当前交易的浮动盈亏；
7）所谓笔是指：一个合约从持仓为0到非0，再次回到持仓为0的成交单列表。持仓为0的交易为历史交易，持仓不为0的交易为当前交易；
8）策略账户的权益=累计出入金+累计（历史交易盈亏-历史交易手续费）+累计（当前交易浮动盈亏-当前交易手续费）；
9）策略账户保证金=累计当前交易保证金；
10）策略账户可用资金=策略账户的权益-累计当前交易保证金；
12）策略账户具有交易活动记录功能，其中交易活动包括：出人金操作、初始持仓、委托单、成交单记录；
13）策略账户的初始持仓和成交单记录中包含当时的客户使用的保证金比率和手续费率，也就是说保证金比率和手续费率的后续变化不影响历史交易手续费的计算；
14）策略账户根据CTP接口收到的合约信息、保证金率和手续费率产生并且维护属于客户自己的完整合约参数；
15）策略账户可用输出自创建之日其的所有历史委托单和成交单列表，使你的策略交易历史有据可查，也可为策略的交易活动的可视化提供后台支持。

**Comment by vnpy** [comment]
挺好的设计，PortfolioMananger模块最初定位就是这个，之前只做了个雏形没进一步深入下去，大家有什么其他建议欢迎在这里分享，我们最迟12月的版本会把相应功能都加进去

**Comment by zfsamzfsam** [comment]
> 1）这里所说的策略账户其实与文华软件中的模组账户相似；
> 2）每个策略都可以选择是否创建策略账户；
> 3）策略账户的名称与创建它的策略实例同名；
> 4）不同策略实例使用它自己创建的策略账户，不需要支持多个策略；
> 5）策略账户支持多个品种（合约），它会在后台拦截所有的属于自己策略的委托单、成交单；


我的理解:
	策略账户,应该是策略的容器,容纳一组策略,这组策略可以涵盖不止一个品种,比如黑色系(rb,i,j),能够合并计算该策略账户的信息,基于这一组策略来分配资金等
	这样,是否更加有意义???

**Comment by hxxjava** [comment]
> > 1）这里所说的策略账户其实与文华软件中的模组账户相似；
> > 2）每个策略都可以选择是否创建策略账户；
> > 3）策略账户的名称与创建它的策略实例同名；
> > 4）不同策略实例使用它自己创建的策略账户，不需要支持多个策略；
> > 5）策略账户支持多个品种（合约），它会在后台拦截所有的属于自己策略的委托单、成交单；
> 
> 我的理解:
> 策略账户,应该是策略的容器,容纳一组策略,这组策略可以涵盖不止一个品种,比如黑色系(rb,i,j),能够合并计算该策略账户的信息,基于这一组策略来分配资金等
> 这样,是否更加有意义???
> 
> ```
>     而且,这种方式也是兼容"只包含一个策略的策略账户"的!灵活性更强!
> ```

我这里所说的策略账户主要是为每个策略提供一个独立的后台资金管理，策略的交易活动跟踪和计算功能。以便于解决目前系统中所有策略使用同一个资金账户的问题的，因为这样你不知道当前的盈亏是哪个策略贡献的，也没有办法知道各个策略的交易业绩，也无法查询各个策略的历史委托单记录，历史交易记录（通过其他软件可以查询不在讨论范围内）。
另外：能够详细说明下您理解的策略账户吗，容纳一组策略的好处是什么？

**Comment by vnpy** [comment]
已通过PortfolioManager模块实现，将于2.1.8中发布
