### ISSUE TITLE
针对价差交易，每次algo算法交易完成后，返回当次algo算法交易的平均成交价格

### ISSUE THREAD

**Issue by kolamanlee** [vnpy/vnpy#2688]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## 预期程序行为

当一次Algo交易完成，返回当次成交的平均价格

**Comment by vnpy** [comment]
已添加价差成交均价计算
