### ISSUE TITLE
安装时出现pip警告

### ISSUE THREAD

**Issue by suimong** [vnpy/vnpy#2689]
## 环境

* 操作系统: Windows 10
* Python版本: Python 3.7.9 + VNStudio-2.1.6
* vn.py版本: v2.1.6

## Issue类型
Bug

## 实际程序行为
使用`install.bat`出现如下图的红色错误信息。pip提示由于包依赖解析算法的变化，将会安装不兼容的包。但最终是顺利完成安装的。

![image](https://user-images.githubusercontent.com/812576/96099035-60e7f700-0f05-11eb-998d-84c065ab01f8.png)

**Comment by vnpy** [comment]
测试过目前没有影响，只是提示信息
