### ISSUE TITLE
【K线图】光标划到K线图最后一个数据（bar)的时候，这个K线会消失。

### ISSUE THREAD

**Issue by felixice** [vnpy/vnpy#2693]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.8 64bit
* vn.py版本: 如v2.1.16

## Issue类型
三选一：Bug

## 预期程序行为
光标划到K线图最后一个数据（bar)的时候，不影响已有数据的显示。

## 实际程序行为
【K线图】光标划到K线图最后一个数据（bar)的时候，这个K线会消失。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
![f989fa7b02c3d60c51d68797a21557b](https://user-images.githubusercontent.com/11263900/97022616-eb27ff00-1586-11eb-926f-212b6530962a.png)

测试无法重现类似情况，请检查是否为特定机器问题。
