### ISSUE TITLE
交易开、平仓记录查询；交易盈亏统计分析 （旧编号#2413）

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2700]
环境
* vn.py版本: 如v2.x

## Issue类型
三选一：Enhancement

## 实际程序行为

旧问题编号：#2413
#2413 

找了下，不知道怎么打开旧的问题，重新贴下，请群主考虑下是否在未来计划中，不会考虑请关闭即可，谢谢！

原贴截图如下：
![1](https://user-images.githubusercontent.com/31505150/96839362-a6fc0800-147b-11eb-8a7b-5142a1dd1893.png)

![2](https://user-images.githubusercontent.com/31505150/96839375-acf1e900-147b-11eb-9e7f-373ea719d7e2.png)

**Comment by vnpy** [comment]
1. 图表显示这块的功能没计划，一方面会大幅拖慢程序响应速度，另一方面这类需求更推荐去用TB/MC这些商业平台
2. 分策略统计盈亏的功能，2.1.8会推出
