### ISSUE TITLE
okex_gateway循环遍历20万条的大集合

### ISSUE THREAD

**Issue by jwtdmkty** [vnpy/vnpy#2704]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/53430781/96970289-07f01280-1546-11eb-82fc-0d9c4f452605.png)

我调整后的代码
![image](https://user-images.githubusercontent.com/53430781/96970136-d0816600-1545-11eb-80e7-3b38ddb944d5.png)

**Comment by vnpy** [comment]
已修复
