### ISSUE TITLE
火币永续合约无法获取历史记录

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2707]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.6发行版
获取火币永续历史记录时为空，如下图
![图1](https://user-images.githubusercontent.com/57986593/97101941-6cdd7100-16dc-11eb-9844-d6c303d6905b.png)

我打印symbol 和 params 用打印的symbol 和params 拼接后在浏览器上可以正常获取到历史数据。
![图2](https://user-images.githubusercontent.com/57986593/97101995-b29a3980-16dc-11eb-9400-198f175e14c9.png)
![图3](https://user-images.githubusercontent.com/57986593/97101996-b332d000-16dc-11eb-87d8-5bec9f50f559.png)

请官方帮助协助修复！！

**Comment by vnpy** [comment]
已修复
