### ISSUE TITLE
alpaca国内可以注册吗

### ISSUE THREAD

**Issue by weiguang-zz** [vnpy/vnpy#2711]
之前对alpaca这个券商有过一些调研，这是一家零佣金的美国券商， 而且对于自动化的交易支持得非常到位，但是很可惜国内用户没有办法注册。
想问一下社区的朋友有没有使用这家券商的，是否有私有的注册途径，非常非常感谢

**Comment by vnpy** [comment]
似乎没有，需要有美国护照或者社保账号吧，这个经纪商并不适合美国以外的客户

**Comment by weiguang-zz** [comment]
使用程序化交易美股和港股的券商，大家有什么可以推荐的吗？

**Comment by vnpy** [comment]
IB、富途用户比较多吧
