### ISSUE TITLE
数字获取okexs，size有float的数据，源码中int转化异常bug

### ISSUE THREAD

**Issue by jwtdmkty** [vnpy/vnpy#2712]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![111](https://user-images.githubusercontent.com/53430781/97412997-3fdbc900-193d-11eb-9f9d-3e7767987f51.png)

![2222](https://user-images.githubusercontent.com/53430781/97413060-4e29e500-193d-11eb-8750-09e9a1233749.png)

**Comment by jwtdmkty** [comment]
修改建议：from typing import Any

**Comment by vnpy** [comment]
已修复，#2757
