### ISSUE TITLE
带有"."的symbol 识别错误

### ISSUE THREAD

**Issue by mxazz123** [vnpy/vnpy#2713]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版

## Issue类型
Bug

## 预期程序行为
symbol正常识别

## 实际程序行为
symbol和exchange_str识别错误

## 重现步骤
调用BacktestingEngine.set_parameters时，vt_symbol设置为"sh.600008.LOCAL"，app\cta_strategy\backtesting.py :196行报错

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/51085754/97462342-8f3fea80-1979-11eb-8992-da0826d1b023.png)

**Comment by mxazz123** [comment]
建议修改：

        temp_split = self.vt_symbol.split(".")
        exchange_str = temp_split[-1]
        self.symbol = "".join(temp_split[1:-1])

**Comment by vnpy** [comment]
vn.py的vt_symbol编码规则是：[代码].[交易所]

所以其中的英文 . 无法用于代码部分，请以下划线之类的其他标点代替即可。
