### ISSUE TITLE
okexf okexs中遍历集合数量10万+，导致内存泄露

### ISSUE THREAD

**Issue by jwtdmkty** [vnpy/vnpy#2714]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![a1](https://user-images.githubusercontent.com/53430781/97510672-36e00b80-19c0-11eb-9df5-0c6a757b0dfa.jpg)
![a2](https://user-images.githubusercontent.com/53430781/97510681-3a739280-19c0-11eb-9d9f-0bb9cfea1b6f.jpg)
![a3](https://user-images.githubusercontent.com/53430781/97510689-3e071980-19c0-11eb-9694-cf0d30fbb1d4.jpg)
![a4](https://user-images.githubusercontent.com/53430781/97510873-a5bd6480-19c0-11eb-91e3-55a16f4f0842.jpg)
![a5](https://user-images.githubusercontent.com/53430781/97510882-a9e98200-19c0-11eb-9cbf-0267949d19b6.jpg)

**Comment by vnpy** [comment]
已修复，#2755
