### ISSUE TITLE
windGateway中提供对万得（模拟）交易的支持

### ISSUE THREAD

**Issue by geraybos** [vnpy/vnpy#272]

**Comment by vnpy** [comment]
这块功能目前没有开发的计划，2个原因:
1. WIND接口现在只能用于模拟，无法实盘，意义不大（树大招风，估计也不敢提供实盘了）
2. WIND接口不提供任何成交、委托方面的推送机制，所有的数据都必须通过主动查询实现，和vn.py针对的低延时交易需求偏差较大
