### ISSUE TITLE
K线图是否可以增加多个标的叠加等功能需求

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2730]
## 环境

* vn.py版本: 如v2x

## Issue类型
三选一：Enhancement

## 预期程序行为

群主，您好

请问是否可对K线功能部分进行增强功能增加，具体如下：
1、在K线图上左边显示百分比，右边显示价格功能；
2、在K线图上可以选择多个标的的K线图进行叠加，进行趋势的分析和关联性的分析；
3、对于组合策略或者多标的交易或者价差模块，可以将组合的标的、价差及价差的标的同时显示在图上，并能够时时显示当前行情；
4、对于历史回测部分，组合策略或者多标的同时测试或者价差模块的历史回测（多个标的价格同时加载），可以实现1分钟K线图的时时显示功能并在图上显示出开仓、平仓的时间、记录、手数信息及当前持仓信息和对应盈亏；（类似MT4/MT5的测试功能）

5、其他，欢迎有这类需求的朋友们补充；

请问是否有这方面的考虑？ 这类需求是通用类行情软件和交易类软件基本上都提供的，期望vnpy新版本中也能够有这类完美的功能而不是使用者不停的切来切去的换系统等。

如果没有增加这部分功能的考虑，请问是否可以提供下这类全部功能实现的大概例子？谢谢！

请其他了解的高手们提供下这类实现的范例，非常感谢！

如果这个需求不被考虑，是否可以暂留此问题几个月，看是否其他高手们可否提供类似K线叠加的例子？ 看社区上其他用户是否也有这类需求？
即使官方不增加这类需求，也恳请多留些时日再关闭，谢谢！

请有这类需求的交易者们也补充下你们更好的需求，谢谢！

**Comment by vnpy** [comment]
vn.py定位不是图表交易软件，同时一个月过去也没有其他用户反馈，官方没有这块的计划了。
