### ISSUE TITLE
希望VN做出的改进

### ISSUE THREAD

**Issue by couldn** [vnpy/vnpy#2733]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Enhancement
## 预期程序行为
1.数据库存储数据能将不同类别数据存储于不同表中，并以合约名为表名
2.模拟盘和实盘加入回测，如计算持仓盈利率曲线，最大回撤曲线，以及当日盈亏

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by lookis** [comment]
为何要用表来区分合约呢？直接在查询的时候可以加个symbol条件就过滤出来数据了

**Comment by vnpy** [comment]
楼上正解，数据库本来正确用法就不是每个合约存一张表，而是每种类型的数据存一张表。

实盘交易不会加入图表功能，因为会显著拖慢程序响应速度，这类需求更推荐用TB/MC等平台。
