### ISSUE TITLE
由于是金融软件 有没有考虑把float全部换成Decimal

### ISSUE THREAD

**Issue by TangPere** [vnpy/vnpy#2734]
## 环境

* 操作系统: Linux and Windows
* Python版本: Python 3.7
* vn.py版本: v2.1.7

## Issue类型
三选一：Enhancement and Question

## 预期程序行为
太多地方出现精度丢失

## 实际程序行为
不应该出现精度丢失 

不过想看看为什么不用Decimal是因为 速度还是内存还是什么考量?

**Comment by vnpy** [comment]
主要是速度，Decimal的计算比float慢很多，对量化平台来说不合适

**Comment by vnpy** [comment]
收到，我们来研究下新版的ibapi
