### ISSUE TITLE
官方图形化回测引擎可能存在漏加载数据的bug？

### ISSUE THREAD

**Issue by reeingal** [vnpy/vnpy#2738]
## 环境

* 操作系统: Windows 10
* Python版本: Python 3.7.6
* vn.py版本: v2.1.7

## Issue类型
三选一：Bug

## 预期程序行为

图形化回测引擎加载所有交易日日K数据

## 实际程序行为

今天偶然发现的，自己写的脚本回测和官方图形化引擎的回测结果有出入，加载的是从2015年1月5日至今的数据。细查发现官方回测引擎加载的数据少了不少天数，例如2015年2月4日的日K线数据就没有加载。最后定位到下方的源码：

```python
# vnpy/app/cta_backtester/ui/widget.py BacktesterManager start_backtesting()
start = self.start_date_edit.date().toPyDate()
end = self.end_date_edit.date().toPyDate()
```

官方回测引擎的load_data()方法是按30天为周期加载数据的，而2015年2月4日刚好是2015年1月5日开始的第30天，在边界值上。这里是将图形化界面了日期编辑栏转换为Python的`datetime.date`类型。不知道为什么导致了漏数据。我将其修改为：

```python
# vnpy/app/cta_backtester/ui/widget.py BacktesterManager start_backtesting()
start = self.start_date_edit.dateTime().toPyDateTime()
end = self.end_date_edit.dateTime().toPyDateTime()
```

转换为`datetime.datetime`类型，官方图形化回测引擎加载的数据量就和自己的脚本一致了，2015年2月4日的K线也能看到了。不清楚其它数据周期会不会存在这个问题。

## 重现步骤

运行图形化界面，以平安银行股票为例，在本地代码填入`000001.SZSE`，开始日期选择`2015/1/5`，结束日期`2020/11/22`，策略随便选，开始回测。

![bug1](https://user-images.githubusercontent.com/13419726/99892912-439d0a00-2cb5-11eb-8580-9d304e4352a9.jpg)

回测结束，可以看到加载的数据量是`1386`，但实际交易日应该有1400以上。

![bug2](https://user-images.githubusercontent.com/13419726/99892931-70e9b800-2cb5-11eb-8ca4-735a002c4547.jpg)

打开`K线图表`可以发现2015年2月4日的K线是缺失的：

![bug3](https://user-images.githubusercontent.com/13419726/99892956-d8076c80-2cb5-11eb-8a6d-dfc964ae3129.jpg)
![bug4](https://user-images.githubusercontent.com/13419726/99892958-d9d13000-2cb5-11eb-8512-890fe795f72e.jpg)

而2015年2月4日正好是回测开始时间2015年1月5日后的30天。

数据库数据展示：

![bug5](https://user-images.githubusercontent.com/13419726/99892984-1bfa7180-2cb6-11eb-904d-1a36a09c66ac.jpg)

可以看到是有2015年2月4日的数据。

如果按照前面说的把日期转换为`datetime.datetime`类型，再次进行回测，会发现加载的数据量正常了，2015年2月4日的K线也出现了。

![bug6](https://user-images.githubusercontent.com/13419726/99893060-acd14d00-2cb6-11eb-8be7-6635a2e5a2f4.jpg)
![bug7](https://user-images.githubusercontent.com/13419726/99893062-b0fd6a80-2cb6-11eb-837e-f28bcc7805b9.jpg)

**Comment by reeingal** [comment]
数据库用的是sqlite，感觉可能是加载数据的接口有问题，但没有细查

**Comment by vnpy** [comment]
已修改，非常感谢！
