### ISSUE TITLE
filter的兼容性问题

### ISSUE THREAD

**Issue by hadrianl** [vnpy/vnpy#2741]
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/trader/utility.py#L209

volume会导致IB Gateway不能正确update_tick：
1.当交易所结算后， last_tick维持了当日收盘时的volume
2.隔日交易新tick推进来volume一直是小于last_tick的volume的

**Comment by lookis** [comment]
我没记错的话在vnpy里每个策略在收盘后官方都是建议关闭策略，第二天开盘的时候再重开策略的。这一行代码上面的注释也是说在过滤 intraday trading。

对ib不是很熟悉，所以感觉上应该是需要重启策略

**Comment by vnpy** [comment]
检查了下，确实对于连续交易的市场（外盘、数字货币）会存在这个问题，改回之前的基于tick.datetime的过滤方法
