### ISSUE TITLE
不理解为何PortfolioStrategy没有 on_trade 和 on_order

### ISSUE THREAD

**Issue by lookis** [vnpy/vnpy#2743]
## 环境
* Windows 10
* VNStation 2.5.4

## Issue类型
Question

## 预期程序行为
PortfolioStrategy 支持 on_trade 和 on_order

文档里原文是说：

> 在于组合策略中需要对多合约同时下单交易，在回测时无法判断某一段K线内部每个合约委托成交的先后时间顺序，因此无法提供on_order和on_trade获取委托成交推送，而只能在每次on_bars回调时通过get_pos和get_order来进行相关的状态查询。

可是我们为什么要判断某一段K线内部每个合约委托成交的先后时间顺序呢？首先我觉得回测是基于模拟实盘考虑的，那么在实盘中，合约成交的先后时间顺序就是不一定的，也就是说有可能A先成交 B再成交，也有可能 B先成交，A再成交，这些都是合理的实盘情况，所以回测引擎完全可以忽略成交顺序问题。

希望 PortfolioStrategy 支持 on_trade 和 on_order 的最主要原因是希望保持策略代码的一致性，在 CtaStrategy 里所有数据基本上都是基于回调来处理的，如果在 PortfolioStrategy 里需要轮询操作的话就感觉很不和谐。

希望开发组考虑一下这个问题，因为对于成熟的交易者来说，肯定大概率会通过分散品种来降低风险，所以 PortfolioStrategy 的应用情景应该不比 CtaStrategy 差

**Comment by vnpy** [comment]
举个例子吧，假设提供了on_trade和on_order函数：
1. 策略同时交易A、B两个合约
2. 在A、B上都挂出了限价委托，任何一个合约成交后撤销另一个合约的委托
3. 回测时因为只有K线数据（非连续的切片），对齐时间戳后在同一轮中进行撮合，假设A、B的委托对于这一刻的K线都能立即成交
4. 如果先推送A的on_trade则会撤销B的委托，反之则撤销A的委托，撤销顺序取决于【回测中的撮合顺序】
5. 但在实盘交易中，因为交易时TICK BY TICK连续的，所以A、B的成交是可以确定的，撤销顺序取决于【实际世界哪个合约的价格先满足成交条件】
6. 所以这里提供on_trade/on_order则会导致回测和实盘的不一致性，因此不能提供，这也是Zipline这类框架扩展到实盘交易中的一个痛点
7. 如果想满足一致性要求，就要有带有【本地时间戳】的TICK数据，目前只有宏汇、国泰安等几家提供，也可以自行录制，这块不属于PortfolioStrategy模块的应用场景，另外有对应的DeltaOne做市模块（可能因为大量挂撤单导致被交易所封账户，因此只放在了【vn.py机构用户群】里）

**Comment by lookis** [comment]
> 举个例子吧，假设提供了on_trade和on_order函数：
> 
> 1. 策略同时交易A、B两个合约
> 2. 在A、B上都挂出了限价委托，任何一个合约成交后撤销另一个合约的委托
> 3. 回测时因为只有K线数据（非连续的切片），对齐时间戳后在同一轮中进行撮合，假设A、B的委托对于这一刻的K线都能立即成交
> 4. 如果先推送A的on_trade则会撤销B的委托，反之则撤销A的委托，撤销顺序取决于【回测中的撮合顺序】
> 5. 但在实盘交易中，因为交易时TICK BY TICK连续的，所以A、B的成交是可以确定的，撤销顺序取决于【实际世界哪个合约的价格先满足成交条件】
> 6. 所以这里提供on_trade/on_order则会导致回测和实盘的不一致性，因此不能提供，这也是Zipline这类框架扩展到实盘交易中的一个痛点
> 7. 如果想满足一致性要求，就要有带有【本地时间戳】的TICK数据，目前只有宏汇、国泰安等几家提供，也可以自行录制，这块不属于PortfolioStrategy模块的应用场景，另外有对应的DeltaOne做市模块（可能因为大量挂撤单导致被交易所封账户，因此只放在了【vn.py机构用户群】里）

我觉得考虑到回测尽可能地模拟出实际世界的场景确实是个很好的出发点，我的观点主要在于实际世界场景的不确定性也应该是一种情况，因为我们需要承认的一点就是我们确实没有办法在这个场景里去完全逼近实际世界

在您举的例子中的第5点也不是完全确定的，比方说我的合约是基于不同交易所，比方说一个在 DCE 一个在 SHFE，就确实有可能在同一个 tick 里两个合约都成交了，然后撤消失败，所以至少在一个 tick 的时间内，我们可以把两个合约看作是“对齐时间戳后的同一轮”

我并不是说在抬杠，而是说既然用户是在回测，就应该去考虑的更周全以应对这种不确定性的情况。

当然我也看过vnpy的源码，能理解这样处理的困难。现在的 vnpy 每根bar推进都是一个原子过程，如果要在推进的过程中再调用策略代码，就会把原来的一次撮合弄成复杂的递归逻辑，无论是 on_trade 或者 on_order 都会让整个框架进入特别麻烦的情况。

**Comment by vnpy** [comment]
可以自己扩展下看看，原理和CTA策略类似，也很简单了

**Comment by lookis** [comment]
> 可以自己扩展下看看，原理和CTA策略类似，也很简单了

嗯嗯，现在是这样做的，开源就是这点好处，可以自己折腾，在这里主要是想交流一下 XD
