### ISSUE TITLE
火币期货接口获取历史数据问题

### ISSUE THREAD

**Issue by zyujiawei** [vnpy/vnpy#2744]
## 环境

* 操作系统: Windows Server 2012 R2
* Python版本: 3.7
* vn.py版本: 2.5.4

## Issue类型
三选一：Bug
程序行为
CTA引擎初始化中未能获取数据

11月后出现，可能是火币接口更新

![捕获](https://user-images.githubusercontent.com/9926515/100544664-463dc780-3292-11eb-90fa-7178c1b9cd8e.PNG)

**Comment by db005** [comment]
火币其他接口也有问题。

**Comment by noranhe** [comment]
> ## 环境
> * 操作系统: Windows Server 2012 R2
> * Python版本: 3.7
> * vn.py版本: 2.5.4
> 
> ## Issue类型
> 三选一：Bug
> 程序行为
> CTA引擎初始化中未能获取数据
> 
> 11月后出现，可能是火币接口更新
> 
> ![捕获](https://user-images.githubusercontent.com/9926515/100544664-463dc780-3292-11eb-90fa-7178c1b9cd8e.PNG)
我看火币API“交割合约”下，10月10号的更新日志里有一个关于通过合约code调用暂时只支持查询当前上市中的合约的更新。里面有包括/market/history/kline这个接口URL（vnpy查询历史函数用的这个），并没有说可查询K线数据限制修改的更新。请问你查询的合约是否退市了呢？

**Comment by noranhe** [comment]
> 火币其他接口也有问题。

请问你发现还有火币的哪几个有这个问题呢？

**Comment by db005** [comment]
> > 火币其他接口也有问题。
> 
> 请问你发现还有火币的哪几个接口有这个问题呢？

不好意思，看错了。

**Comment by xldistance** [comment]
没有连接成功吧，resp.json()收到的是空列表，我的是正常的

**Comment by vnpy** [comment]
我们测试也没问题，请检查是否正确配置了翻墙工具
