### ISSUE TITLE
binance_gateway窗口显示问题

### ISSUE THREAD

**Issue by CendyBY** [vnpy/vnpy#2745]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio
* vn.py版本: 如v2.1.7发行版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

连接binance_gateway的接口
![image](https://user-images.githubusercontent.com/26918333/100584123-a1b99500-3326-11eb-8adb-06ea480a5dc8.png)
资金界面会显示实时的余额，冻结和可用
![image](https://user-images.githubusercontent.com/26918333/100584207-beee6380-3326-11eb-8323-d6ebc08b388b.png)
火币的余额和冻结跟网站的是对应的。binance的数额不对。我修改代码字段之后，bianance账号的数额能对上
![image](https://user-images.githubusercontent.com/26918333/100584485-2a383580-3327-11eb-9290-f5694e8ab98b.png)

但是不会自动更新实时的账户余额变动。火币和bitmex的余额，冻结资金显示是能够正常实时变动

**Comment by vnpy** [comment]
币安的钱包资金推送，依赖于Websocket而不是REST，Gateway只会在初始化的时候进行一次查询，后续都通过WS推送获取，如果没有变化请检查是否WS连接有问题。
