### ISSUE TITLE
解决一个很少人能够遇到的融航接口的bug。

### ISSUE THREAD

**Issue by kingmo888** [vnpy/vnpy#2746]
## 环境

* 操作系统: 任意win7及以上的win系统（含win server2012及以上版本）
* Python版本: python3.7.4
* vn.py版本: v2.1.7

## Issue类型
Bug

## 预期程序行为
登录融航接口，正常登录及交易

## 实际程序行为
登录时无提示直接崩溃。

## 重现步骤
说实话，要不是我瞎折腾，还真遇不上这个bug，为了解决这个bug，在3天时间里虚拟机重装了不下30遍，最终找到问题所在。
这个问题的复现需要同时满足3个条件：
1、基于脚本启动
2、所有配置保存在脚本所在目录（即通过mkdir 创建过.vnxxxx）
3、脚本所在目录有中文。
如果是基于VN Station启动的话，是不会复现中文字符问题的。

## 修改方法
修改融航网关文件的2处，
1、
self.createFtdcTraderApi(str(path) + "\\\Td")修改为：
self.createFtdcTraderApi((str(path) + "\\\Td").encode("GBK"))
2、
self.createFtdcMdApi(str(path) + "\\\Md")修改为：
self.createFtdcMdApi((str(path) + "\\\Md").encode("GBK"))

#2747

**Comment by vnpy** [comment]
已合并，非常感谢
