### ISSUE TITLE
strategy name 为中文时，策略监控的pos有异常

### ISSUE THREAD

**Issue by msincenselee** [vnpy/vnpy#275]
在策略实例配置cta_setting.jason中配置name时，若为中文名，self.putevent()时，反馈在策略监控中的pos变量，跟实际的pos不一致。改成英文就没事了。

**Comment by fanchuan8848** [comment]
用的是哪个版本？

**Comment by vnpy** [comment]
这个应该和json文件在保存时的编码方式有关，默认使用的是纯英文的模式而非UTF-8，所以不能在json文件中输入中文数据，如果需要的话，可以修改loadSetting时对json的解码方式为UTF-8，应该就不会出问题。
