### ISSUE TITLE
[Bug]VN Studio无法进入行情记录模块窗口（点击'功能'按钮，不显示下拉框）

### ISSUE THREAD

**Issue by forhonourlx** [vnpy/vnpy#2758]
## 环境

* 操作系统: 如Windows 10/ Windows Server 2019
* Python版本: 如VNStudio-2.1.7

## Issue类型
三选一：Bug

## 预期程序行为
根据文档，“进入VN Trader后，首先登陆接口，如连接CTP；然后在菜单栏中点击“功能”->"行情记录“后，会弹出行情记录窗口，“

## 实际程序行为
VN Trader 图形界面连接CTP后，点击'功能'按钮，不显示下拉框，故无法启动行情记录模块。
另外，'系统'和'帮助'可以正常显示下拉框。

@vnpy 恳请大佬看看，衷心感谢。

**Comment by noranhe** [comment]
请问在配置VN Trader上层应用的时是否勾选了DataRecorder呢？
![image](https://user-images.githubusercontent.com/63988546/101453084-bcfd5380-3969-11eb-971e-27a974698cae.png)

**Comment by vnpy** [comment]
楼上正解

**Comment by forhonourlx** [comment]
对不起，我上层应用里没勾上。感谢！
