### ISSUE TITLE
数据库里的时区在回测和实盘时的逻辑不一致问题

### ISSUE THREAD

**Issue by lookis** [vnpy/vnpy#2759]
## 环境
* 操作系统: Mac/CentOS
* Python版本: 3.8.6
* vn.py版本: 2.1.7

## Issue类型
Bug

Bug 产生过程：

1. 在行情记录模块中，从CTP接口拿到的 TickData 是带着时区信息的，且固定为 UTC+8 
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/gateway/ctp/ctp_gateway.py#L316

2. 然后到了数据库接口的时候，会先转换为数据库时区对应时间，然后把时区信息丢掉：
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/trader/database/database_mongo.py#L226-L257

3. 但要注意的是，如果我们用的是 mongodb(pymongo，mongoengine是基于pymongo的封装) 的话，mongodb会把“无时区”时间带上默认的时区，也就是 UTC，而且在 mongodb 里是无法存入其它时区的（如果存入的时间带着时区信息，pymongo 就会转换成 UTC 来存储）

4. 在实盘中，我们用 load_bar 来预加载数据的时候，传入的时间是带着时区信息的:
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/app/portfolio_strategy/engine.py#L287
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/app/cta_strategy/engine.py#L535

在这个情况下， load_bar 能够正确取到对应时间的数据。

5. 在回测中，load_data 的数据是不带时区信息的：
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/app/cta_strategy/backtesting.py#L216
https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/app/portfolio_strategy/backtesting.py#L122

在这个情况下，mongodb 会把这个“无时区”时间直接认做 UTC 时间。从而导致数据加载错误

**参考解决方案：**

把回测的逻辑调整成和实盘一致，都带上时区，同时在 mongodb 里不支持用户传入 database.timezone，统一采用 UTC
，根据 mongodb 文档，所有时区转换逻辑都应该在应用层： 
https://docs.mongodb.com/manual/tutorial/model-time-data/#overview

> MongoDB stores times in UTC by default, and will convert any local time representations into this form. Applications that must operate or report on some unmodified local time value may store the time zone alongside the UTC timestamp, and compute the original local time in their application logic.

**Comment by vnpy** [comment]
收到，我们来改下

**Comment by noranhe** [comment]
我用的mongodb，对照了我的数据库，并没有转成UTC。所以导出的数据还是同样的时间，只不过是在to_bar的时候localize加上了数据库时区信息
![image](https://user-images.githubusercontent.com/63988546/102741887-7eff2700-438e-11eb-818a-3b666d98d2b0.png)
这是数据库和csv的对比
![image](https://user-images.githubusercontent.com/63988546/102741933-9ccc8c00-438e-11eb-9055-a060e3ded1e6.png)
![image](https://user-images.githubusercontent.com/63988546/102741938-a0f8a980-438e-11eb-81a6-044d0c244eb2.png)
图上可以看出我load_bar的end是10号0点，品种是rb，加载数据加到了9号22：59。如果转成UTC了的话，应该是不能load到这么晚的时间的。我感觉是不用修改的

**Comment by lookis** [comment]
我们来看你第一张图里的数据，在excel表里的数据我相信你应该是在做国内的市场，也就是北京时间，而在第一张图里右边是 mongodb 里的数据，最后一个 ‘Z’ 就代表了这表达的是一个 UTC 时间。
（可参考wiki: https://zh.wikipedia.org/wiki/%E6%97%B6%E5%8C%BA 中的 协调世界时）
换句话说。excel和mongodb里的这两个时间已经表达的不是同一个时间了。

然后在 to_bar 的时候，会用 localize 方法强行再把数据库里的UTC时间转回 北京时间，在这个流程里是没问题的，我们的确可以直接忽略数据库的时区强行转。但重点在于我们的逻辑需要一致。

那么在什么情况下我们的逻辑会不一致呢？问题就在于时间判断的逻辑如果不在代码里，而是在数据库里的话，这里就会出问题了。看这段代码：

https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/trader/database/database_mongo.py#L196-L212

我们是把查询请求里的时间对比直接交给了数据库，而mongodb在比对时间的时候是不会忽略时区的。

**Comment by lookis** [comment]
也就是说，现在有两种逻辑在共同跑着：
1. 代码里忽略数据库存储的时区，都按配置文件里设置的走，直接把数据库里的时区信息 truncate 掉
2. 提交数据库查询的时候，比对时间在数据库层面，而数据库里比对时区的时候不会忽略。

所以首先：现在你第一张图里的数据库里的时间其实是错的，不应该是 2005-01-04 00:00:00.000Z，而应该是 2005-01-03 16:00:00.000Z

**Comment by lookis** [comment]
> 图上可以看出我load_bar的end是10号0点，品种是rb，加载数据加到了9号22：59。如果转成UTC了的话，应该是不能load到这么晚的时间的。我感觉是不用修改的

回复一下这一句，在这里对mongodb处理时间的理解有点问题，因为这个是回测，而回测传入的时间不带时区，所以mongodb不会再去转UTC，而是直接把这个时间 “认作” UTC时间，不再进行转换

换句话就是说，在回测逻辑中，mongodb直接认为你传入的就是 UTC时间（而不是我们以为的 +8 的时间）

**Comment by lookis** [comment]
我们可以来看看这段代码，是不是和你想象中的逻辑一致：

```python
from vnpy.trader.database import database_manager
from vnpy.trader.constant import Exchange, Interval
import pytz
from datetime import datetime, timedelta
CHINA_TZ = pytz.timezone('Asia/Shanghai')
start = datetime(2020, 12,1,0,0,0)
end = datetime(2020,12,10,12,0,0)

start_with_tz = CHINA_TZ.localize(start)
end_with_tz = CHINA_TZ.localize(end)


print(end)
print(end_with_tz)
```
```
2020-12-10 12:00:00
2020-12-10 12:00:00+08:00
```

```python
#回测场景的加载数据
backtest_load_datas = database_manager.load_bar_data('rb2105', exchange=Exchange('SHFE'), interval=Interval.MINUTE, start=start, end=end)
#实盘场景的加载数据
prod_load_datas = database_manager.load_bar_data('rb2105', exchange=Exchange('SHFE'), interval=Interval.MINUTE, start=start_with_tz, end=end_with_tz)

print(backtest_load_datas[-1])
print(prod_load_datas[-1])
```
```
BarData(gateway_name='DB', symbol='rb2105', exchange=<Exchange.SHFE: 'SHFE'>, datetime=datetime.datetime(2020, 12, 10, 6, 59, tzinfo=<DstTzInfo 'Asia/Shanghai' LMT+8:06:00 STD>), interval=<Interval.MINUTE: '1m'>, volume=8530.0, open_interest=1005780.0, open_price=4037.0, high_price=4042.0, low_price=4037.0, close_price=4040.0)
BarData(gateway_name='DB', symbol='rb2105', exchange=<Exchange.SHFE: 'SHFE'>, datetime=datetime.datetime(2020, 12, 10, 3, 29, tzinfo=<DstTzInfo 'Asia/Shanghai' LMT+8:06:00 STD>), interval=<Interval.MINUTE: '1m'>, volume=3636.0, open_interest=1022270.0, open_price=4046.0, high_price=4051.0, low_price=4045.0, close_price=4051.0)
```

**Comment by vnpy** [comment]
已修复，将所有不带时区的start/end时间戳，加上本机所在的本地时间戳后，再转化为配置中的数据库时间戳，然后进行查询即可，和之前插入数据的逻辑保持一致（全部使用database.timezone)。
