### ISSUE TITLE
建议实盘策略逻辑和GUI在架构上做分离

### ISSUE THREAD

**Issue by lookis** [vnpy/vnpy#2762]
## Issue类型
Enhancement

现在 vnpy 运行的模式有两种
一个是使用 vnstudio 启动 vntrader 来运行带 GUI 的逻辑，可以看到 put_event 的数据变化等
第二个是直接用类似 no_ui 的脚本，让策略在后台运行。无法看到 put_event 的数据变化

第一种运行的优势在于对全局状况很清晰，GUI像是个 dashboard 一样能够快速了解所有策略的情况，但它的缺点在于 GUI 程序的不稳定性，特别是在 windows 下如果内存占用或者别的资源紧张（比方说数据录制的品种过多等一些正常使用场景）就容易导致窗口无响应然后不得不强制关闭，而且采用的 Qt 也是一个比较重型的多平台适配框架，会因此带来更多的不稳定性。

第二种的运行方式的优缺点就和第一种方式刚好相反。

所以期望可以把策略运行和GUI在架构上做分离，让真实逻辑部分（数据记录、策略运行等 Engine 的逻辑）在后台跑着，而 GUI 部分可以独立出来，有需要看数据的时候再打开，崩溃的时候可以独立关闭和重启。

如果前后端分离的彻底一些、接口设计的更加健全的话，甚至我们可以实现在策略逻辑跑在不同 linux server 上（追求稳定），然后在 windows 下统一看大盘（追求易用），监控全集群不同 engine 的运行情况

**Comment by yanxiu0614** [comment]
所以我建议这里更彻底一点可以抛弃qt这种，通过启用webserver实现网页操作，这样天然可以实现跨平台，而且服务端可以部署在服务器上。

**Comment by lookis** [comment]
> 所以我建议这里更彻底一点可以抛弃qt这种，通过启用webserver实现网页操作，这样天然可以实现跨平台，而且服务端可以部署在服务器上。

这也是我提这个issue最初的想法，如果能在后端把这些控制命令都暴露成接口的话，就可以用webserver来实现了，就哪怕不是http接口，一个rpc调用都是好的。

如果太彻底一步到位的话我担忧是工作量太大，容易出现bug，如果能先做分离再做ui重构会走的更稳一些。另外也不知道vnpy团队里在web前端的投入有多少，如果没有足够的前端支持也是比较难受的一点。但至少我认为如果把架构分离出来之后就有可能以开源大家参与的形式慢慢把web部分配齐了。

供vnpy参考

**Comment by vnpy** [comment]
我们计划2月搞一次线下活动，分享下我们基于FastAPI开发的Web服务端程序，大家有兴趣的话可以帮忙把前端（网页部分）实现出来。

在1.0时代我们倾向于使用vue做开发，找了外部团队帮忙实现，遗憾的是我们自己并没有前端开发能力，所以后续逐渐就没有更新了，2.0希望把前端部分交给社区来做试试看。

**Comment by zhangyaobo** [comment]
> 我们计划2月搞一次线下活动，分享下我们基于FastAPI开发的Web服务端程序，大家有兴趣的话可以帮忙把前端（网页部分）实现出来。
> 
> 在1.0时代我们倾向于使用vue做开发，找了外部团队帮忙实现，遗憾的是我们自己并没有前端开发能力，所以后续逐渐就没有更新了，2.0希望把前端部分交给社区来做试试看。

赞，期待前端的大神

**Comment by sobriver** [comment]
现在这方面进展的怎么样了

**Comment by vnpy** [comment]
2.5.0版本的WebTrader模块将会发布。
