### ISSUE TITLE
demo_notebook.ipynb 运作错误

### ISSUE THREAD

**Issue by chloe-wang** [vnpy/vnpy#2768]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7
* vn.py版本: master

## Issue类型
三选一：Question

## 预期程序行为
直接clone vnpy的master分支，运行examples/notebook_trading/demo_notebook.ipynb, 发现以下错误：

![image](https://user-images.githubusercontent.com/22490931/102568013-9f747a80-411d-11eb-8f89-5add9263bd5b.png)

## 重现步骤

直接clone vnpy的master分支，运行examples/notebook_trading/demo_notebook.ipynb

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
