### ISSUE TITLE
由分钟 bar 合成小时 bar 问题

### ISSUE THREAD

**Issue by lookis** [vnpy/vnpy#2775]
## 环境

* 操作系统: MacOS/CentOS
* Python版本: 3.8.6
* vn.py版本: 2.1.7

## Issue类型
Bug

BarGenerator 在实盘中用分钟K合成小时K的时候，多计算了一根分钟Bar，具体Bug发生过程如下：

https://github.com/vnpy/vnpy/blob/024343d4111ec5bb8eb37085e1df2f48e26cdeea/vnpy/trader/utility.py#L284-L299

在合成 x-minute bar 的时候，用的判断是
```
 minute + 1 % self.window
```
这里的判断是正确的，也就是说 “如果下一分钟刚好满足一个时间窗口” 那么就在这一分钟的bar作为最后一根。换句话说，如果我们要生成 15min 的K线，用的数据是左闭右开 [0,15) 的数据

而到了 HOUR 的分支逻辑里面，判断的是
```
if self.last_bar and bar.datetime.hour != self.last_bar.datetime.hour:
```
用的是当前分钟bar的hour 来判断是否满足一个时间窗口，这就导致多计算了一根分钟bar，因为按照这个逻辑，1Hour 的K线就是左开右闭 (0, 60] 的数据

### 修改建议：
~~在小时逻辑里面采用~~
```python
        elif self.interval == Interval.HOUR:
            if self.last_bar and (
                    bar.datetime + timedelta(minutes=1)).hour == (self.last_bar.datetime + timedelta(minutes=1)).hour + 1:
                # 1-hour bar
                if self.window == 1:
                    finished = True
                # x-hour bar
                else:
                    self.interval_count += 1

                    if not self.interval_count % self.window:
                        finished = True
                        self.interval_count = 0
```
~~来判断，保持K线逻辑的一致，虽然在遇到中午11:30休到13:30的时候还是会算错一根分钟bar（把 13:30 分钟算作 [11,12) 小时bar的最后一根）但其它的小时数据都正确了~~

~~这样至少避免了一个问题，使得K线能正确反映出来日盘、夜盘开盘时候的跳空~~

#### 上面的解决方案还是不完整，会有问题，仅供参考

**Comment by vnpy** [comment]
已修复

**Comment by lookis** [comment]
@vnpy 需要 reopen 这个 issue, 今天试了一下新版本的代码，发现这个 fix 导致了一个更严重的bug。

https://github.com/vnpy/vnpy/blob/8502cd7335e3f19e5a1bb2355708aa8523d8cdf7/vnpy/trader/utility.py#L299-L302

这个判断会导致一个周期生成两根 bar，比方说 13:59 的时候 last_minute 判断成功，生成新bar，然后在 14:00 的时候 new_hour 又一次判断成功，生成新bar，也就是说一个小时周期生成了两根 小时 k线

**Comment by vnpy** [comment]
增加了一个过滤条件，已经修复了
