### ISSUE TITLE
CTP订阅交易所标准套利合约数据显示错误

### ISSUE THREAD

**Issue by Billy-Meng** [vnpy/vnpy#2779]
## 环境

* 操作系统: Windows 10
* Python版本: 3.7
* vn.py版本: V2.1.8

## Issue类型
Bug

## 预期程序行为
正确订阅并显示交易所标准套利合约Tick数据

## 实际程序行为
实际订阅交易所标准套利合约时，套利合约的最新价、成交量、开盘价、最高价、最低价行情显示有问题，和真实行情有出入。望官方能及时排查，修复BUG。

## 重现步骤
![image](https://user-images.githubusercontent.com/56326576/103127334-5055b900-46cc-11eb-9df2-12db58211996.png)

**Comment by vnpy** [comment]
已修复#2785
