### ISSUE TITLE
咨询在同一台电脑上跑多个账户实现方式

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2780]
## 环境
* 操作系统: 如Windows 10
## Issue类型
三选一：Question

## 实际程序行为

群主，您好

这个咨询，发到群里未得到高手们的准确答复，特地向您请教下，

因为多核的机器并且内存配置也都非常高，那么想利用好这台机器，在这个机器上想开多个vnpy的，怕有冲突，想到的一个方法是：

1、再我机器的安装vnpy的位置，拷贝一个新的文件夹出来 ssTrdr,在ssTrdr中把所有源代码中的 vnpy.  都替换成 ssTrdr. 
2、在我运行的 run 的文件位置，新建一个文件夹，把文件夹中的所有文件中的vnpy. 都替换成ssTrdr
3、同时运行run，是不是就是两个完整的了，其中的所有开平仓以及策略等都不会冲突了，因为是完全的2个实例进程了？

写了代码把安装好的路径下的vnpy中的所有文件中的vnpy. 都替换成了 ssTrdr. ，也把run文件单独拷贝了一个文件出来，也都把vnpy.替换成了ssTrdr. 了，但是报错，错误信息
E:\01_ssTrdr>python run.py
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from ssTrdr.trader.uiMainWindow import MainWindow
  File "E:\00_VNPY_192\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\ssTrdr\t
rader\uiMainWindow.py", line 9, in <module>

...

    from ssTrdr.trader.gateway.ibGateway.ibGateway import account_Deposit
  File "E:\00_VNPY_192\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\ssTrdr\t
rader\gateway\ibGateway\__init__.py", line 5, in <module>
    from .ibGateway import IbGateway
  File "E:\00_VNPY_192\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\ssTrdr\t
rader\gateway\ibGateway\ibGateway.py", line 22, in <module>
    from ssTrdr.api.ib import *
  File "E:\00_VNPY_192\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\ssTrdr\a
pi\ib\__init__.py", line 4, in <module>
    from .vnib import *
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

恳请群主指导下，谢谢！

是想到的这种方式就不行呢，还是限制死了必须是vnpy的目录呢？

非常感谢！

**Comment by lookis** [comment]
不知道你是否一定需要图形界面？如果不一定需要图形界面的话可以直接用类似example/no_ui 的脚本直接运行，然后不同的账号可以写在脚本里面

**Comment by stone3536** [comment]
交易的机器，需要图形界面的，因为要操作设置对应的开平仓的点位的。（但是这个图形界面只是gui的操作界面的，不是K线图的，K线图的图形界面是行情功能，在单独的行情的机器上的。）

**Comment by lookis** [comment]
如果需要图形界面的话有一个比较保准的方案是使用虚拟机软件，可选方案有 vmware，virtualbox，还有windows自带的hyper-v。

**Comment by vnpy** [comment]
今天（2020年12月29日）下午的宏源期货分享活动会有讲解这块的内容，活动报名请加：2476475172
