### ISSUE TITLE
支持 Huobi 的 USDT 正向永续合约交易

### ISSUE THREAD

**Issue by xgao1023** [vnpy/vnpy#2786]
目前Huobi已经提供USDT正向永续合约的RESTful API，但是vnpy的HuobisGateway似乎还只支持币本位合约接入。
目前想知道有多少人感兴趣，我本人可以提供实现，希望能合并到主分支。

**Comment by bigcat213** [comment]
大佬求提供

**Comment by AITrading2020** [comment]
很不错的提议

**Comment by xgao1023** [comment]
已经提供 PR 
https://github.com/vnpy/vnpy/pull/2793

**Comment by xgao1023** [comment]
PR: https://github.com/vnpy/vnpy/pull/2794

**Comment by gub176** [comment]
支持！越快完成越好！

**Comment by aijy** [comment]
支持，希望尽快，谢谢！

**Comment by vnpy** [comment]
已在HuobisGateway中添加对于U本位合约的支持，注意vn.py只支持全仓模式的交易。
