### ISSUE TITLE
希望vnpy可以接入掘金量化平台

### ISSUE THREAD

**Issue by xgao1023** [vnpy/vnpy#2787]
希望vnpy可以接入掘金量化平台，使其成为vnpy的一个gateway。

https://www.myquant.cn/

从我个人来说主要为了使用历史数据进行回测。

目前想知道有多少人感兴趣，我本人可以提供实现，希望能合并到主分支。

**Comment by vnpy** [comment]
掘金本身就是个量化平台了，不需要用vn.py再次去接入吧，想用他们的数据就直接用掘金好了

**Comment by xgao1023** [comment]
掘金并非像vnpy一样的功能完整的平台，因此并非“想用他们的数据用他们的平台就好了”。

我认为他仅仅相当于  对ctp和券商接口的封装+数据。

 - 只支持A股和内盘期货(非定制版不支持期权)
 - 不支持期权模型，价差交易等高级功能
 - 必须随时联网，离线状态下无法回测

**Comment by vnpy** [comment]
咨询了下券商朋友，掘金作为一个券商采购平台本身是合规的，在外面加挂vn.py就未必了（类似通达信破解），这个方案存在合规风险，我们官方没法支持了。
