### ISSUE TITLE
币安USDT永续合约实盘交易发现合成Bar的时间与本地时间差距很大，甚至早已停止合成数据

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#2788]
## 环境

* 操作系统: 如Windows 10
* Python版本: python3.7
* vn.py版本: 2.1.7, 2.1.8

## Issue类型
三选一：Bug

## 重现步骤
重现步骤以及报错截图详情请见这个帖子的具体内容：
https://www.vnpy.com/forum/topic/5314-bi-an-usdtyong-xu-he-yue-shi-pan-jiao-yi-fa-xian-he-cheng-barde-shi-jian-yu-ben-di-shi-jian-chai-ju-hen-da

**Comment by AITrading2020** [comment]
发现无论币安现货行情还是是反向期货的或者正向USDT永续合约，都存在合成Bar的时间与本地时间差距很大的情况，而且这个如果不是把合成的Bar时间打印出来很难发现这个问题

**Comment by AITrading2020** [comment]
问题已找到，是2.1.7版本里面，数字货币行情底层的tick过滤有问题：https://github.com/vnpy/vnpy/issues/2741。
目前2.1.8 master版本里面，虽然把这个问题修正了，但是当选择interval.Hour时，合成Hour Bar的逻辑依然有问题，不知道当前的2.1.8 dev分支下的utility的最终的版本吗？

**Comment by vnpy** [comment]
之前的Hour合成确实可能还有些问题，2.1.9发布会修复
