### ISSUE TITLE
2.18导出历史数据出错

### ISSUE THREAD

**Issue by zhoujie2104231** [vnpy/vnpy#2790]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.8

## Issue类型

![image](https://user-images.githubusercontent.com/64771779/103331762-61267600-4aa2-11eb-935b-fc1bf113e02b.png)

**Comment by xgao1023** [comment]
在 vnpy\app\data_manager\ui\widget.py 第 438 行，DateRangeDialog.get_date_range 函数
`
    def get_date_range(self) -> Tuple[datetime, datetime]:
        """"""
        start = self.start_edit.**_date()_**.toPyDate()
        end = self.end_edit**_.date()_**.toPyDate() + timedelta(days=1)
        return start, end
`
这个函数应该返回 Tuple[datetime, datetime]，而实际上返回的是 Tuple[date, date]。

这个是否在最新开发版本中已经修复了？如果没有，我可以提供。 @vnpy

**Comment by lookis** [comment]
@xgao1023 看了一些你的commit，我的想法是不要用time(), 对于 start 可以用 00:00:00，end 可以用 23:59:59

**Comment by xgao1023** [comment]
> @xgao1023 看了一些你的commit，我的想法是不要用time(), 对于 start 可以用 00:00:00，end 可以用 23:59:59

time()默认的hour/min/sec都是0，当然可能显示指定更好。

至于end，因为date已经加了1，所以time也应该是00:00:00？

**Comment by vnpy** [comment]
已修复，#2781
