### ISSUE TITLE
希望可以使用 TimescaleDB 存储历史数据

### ISSUE THREAD

**Issue by xgao1023** [vnpy/vnpy#2791]
希望可以使用 TimescaleDB ( https://www.timescale.com/ )存储历史数据，原因：

 1. 完整的 标准 SQL 支持，这对于习惯关系数据库的用户很重要
 2. 成熟的数据库引擎
 3. 多个性能测试表明，在多并发以及略微复杂的查询情况下，性能优于 MongoDB 和 InfluxDB

TimescaleDB 原本是 PostgresSQL 的扩展，本应该可以使用SqlManager。
目前的 SqlManager 并不能使用 TimescaleDB，原因： TimescaleDB 的 hypertable 要求 partition key 必须是主键的一部分，而目前的 SqlManager 表结构使用了 id 作为主键，不满足要求。
原则上，纵向partition key 应该是 datetime， 横向 partition key 应该是 exchange或者 (symbol, exchange)。
修改现有的SqlManager不可行，因为会造成不兼容。

我本人可以提供实现，想知道有多大可能会合并到主分支。

**Comment by vnpy** [comment]
欢迎发起PR，数据库这块我们也在考虑剥离成类似接口的插件模式

**Comment by xgao1023** [comment]
> 欢迎发起PR，数据库这块我们也在考虑剥离成类似接口的插件模式

PR很快杀到😏

**Comment by xgao1023** [comment]
> 欢迎发起PR，数据库这块我们也在考虑剥离成类似接口的插件模式

PR: #2802

**Comment by vnpy** [comment]
检查了PR的代码，存在下述问题：

1. 对vnpy.trader.object的修改，底层涉及面较广因此无法接受
2. 存在较多裸写SQL的逻辑后续难以维护，基于PostgreSQL是否可以用Peewee或者SQLAlchemy的ORM

故而无法合并，已关闭PR。

目前已在dev分支完成vnpy.database模块的拆分，后续每个数据库支持将会采用类似Gateway的方式独立维护，所以推荐参考新的结构，看下是否能够解决上述问题后再发起PR，谢谢！

**Comment by xgao1023** [comment]
> 检查了PR的代码，存在下述问题：
> 
> 1. 对vnpy.trader.object的修改，底层涉及面较广因此无法接受
> 2. 存在较多裸写SQL的逻辑后续难以维护，基于PostgreSQL是否可以用Peewee或者SQLAlchemy的ORM
> 
> 故而无法合并，已关闭PR。
> 
> 目前已在dev分支完成vnpy.database模块的拆分，后续每个数据库支持将会采用类似Gateway的方式独立维护，所以推荐参考新的结构，看下是否能够解决上述问题后再发起PR，谢谢！

1可以某种程度上解决

2其实是有意为之，裸sql能达到最大的性能和最小的开销，经过测试在大量订阅的情况下是值得的。orm的开销不适合大批量数据操作。不知有没有两全其美的办法？


新的数据结构会参考，有空会提供实现。

**Comment by vnpy** [comment]
如果确定ORM不适合大批量开销的话，那就用裸SQL好了，然后比较长的SQL语句请尽可能用""""""的长字符串来实现吧，看着清楚一些。
