### ISSUE TITLE
行情记录模块性能提升

### ISSUE THREAD

**Issue by xgao1023** [vnpy/vnpy#2795]
在行情记录模块中，每一条数据都需要进行一次数据库访问（一个DB transaction)。数据库每秒进行的transaction数目非常有限，当记录标的太多（比如全市场行情记录）时，必然会造成队列拥塞

>     def run(self):
>         """"""
>         while self.active:
>             try:
>                 task = self.queue.get(timeout=1)
>                 task_type, data = task
> 
>                 if task_type == "tick":
>                     database_manager.save_tick_data([data])
>                 elif task_type == "bar":
>                     database_manager.save_bar_data([data])
> 
>             except Empty:
>                 continue
> 
>             except Exception:
>                 self.active = False
> 
>                 info = sys.exc_info()
>                 event = Event(EVENT_RECORDER_EXCEPTION, info)
>                 self.event_engine.put(event)
> 

可以每次从队列中先取出所有待记录数据，一次性把队列中已有数据写入数据库。这样可以大大降低数据库压力和记录延迟。

**Comment by xgao1023** [comment]
如果有人感兴趣，我可以提供实现

**Comment by xgao1023** [comment]
PR: #2803

**Comment by vnpy** [comment]
已修改，非常感谢
