### ISSUE TITLE
本地洗价功能之框架化

### ISSUE THREAD

**Issue by zfsamzfsam** [vnpy/vnpy#2796]
参考hxxjava的帖子:
	https://www.vnpy.com/forum/topic/4481

如果能够把本地停止单的维护上提到main_engine的话，
	不光是CTA策略模块可以下本地停止单，
	使得手动也可以下本地停止单!!!
	还有其他app模块，可能都会有下本地停止单的需要

	但是,AlgoTrading模块,一般不会下本地停止单!!!

可能不止是本地停止单,还有其他的复杂下单方式,也可以本地化!!!

**Comment by raycool** [comment]
这个功能确实很好，如果可以使用，就可以手动设置止盈止损了。

**Comment by vnpy** [comment]
停止单本质上都是条件算法的一种，如果服务端（交易所、柜台）没有提供，在客户端实现就必须依赖算法引擎。

因此vn.py在AlgoTrading模块中提供了StopAlgo算法，加载后模块后直接使用即可。
