### ISSUE TITLE
macOS启动vnpy失败，QtPrintSupport版本问题。

### ISSUE THREAD

**Issue by xSinGle** [vnpy/vnpy#2797]
## 环境

* 操作系统: macOS Big Sur Version 11.1
* Python版本: Python 3.7.9
* vn.py版本: vnpy-2.1.8 

## Issue类型
Question

## 预期程序行为
cd ./vnpy/examples/vn_trader
python3 run.py 
正常应该像Windows一样弹出应用交互界面

## 实际程序行为
![image](https://user-images.githubusercontent.com/32978243/103550120-62610400-4ee3-11eb-9885-6d61cb0792b4.png)

## 重现步骤
* git clone https://github.com/vnpy/vnpy.git  
* tar -zxvf vnpy-2.1.8.tar.gz
* sh install_osx.sh python3   这个脚本很多问题(必出现install_osx.sh: line 23: `install-ta-lib': not a valid identifier，我手动改了脚本跑过了，另外就是最后一行install vnpy文件结尾乱码，我手动执行安装的vnpy，反正各种问题。)
* cd vnpy-2.1.8/examples/vn_trader
* python3 run.py
针对Bug类型Issue，请提供具体重现步骤以及报错截图
如上所述，还没打开交互界面，一直卡在这里，每次执行run.py企图启动交互界面就会报截图的错
Reason: Incompatible library version: Qsci.abi3.so requires version 5.15.0 or later, but QtPrintSupport provides version 5.14.0
很希望可以在mac上顺畅的使用vnpy，希望大神帮忙看看，感谢。

**Comment by raycool** [comment]
pip install --upgrade PyQt5 就解决了吧

**Comment by lookis** [comment]
建议使用 3.6 的 python，不然遇到各种问题……
就算跑起来之后 Mac 下的 界面也是很多问题，比方说下拉菜单项里哪怕只有一个选项也会给一个很高的控件。
反正我是放弃了最后用虚拟机跑windows版本的……

**Comment by xSinGle** [comment]
的确，看来vnpy支持Mac还有很长的路要走(或者干脆不支持。。。)，我还是搞个VM跑Windows好了，感谢各位。

**Comment by MrKoooooo** [comment]
更新一下pyqt5就好了
