### ISSUE TITLE
币安合约不能下单开空

### ISSUE THREAD

**Issue by sxxzwzf** [vnpy/vnpy#2798]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）
币安合约不能下单开空，一直提示-2022 REDUCE_ONLY_REJECT
ReduceOnly Order is rejected.
ReduceOnly订单被拒绝

**Comment by vnpy** [comment]
请问是否开平指令中，选择了【平仓】？应该选择【开仓】

**Comment by dongwenxiao** [comment]
@vnpy 我也遇到了同样的问题，请问你说的是“开仓”、“平仓”是指 BUY | SELL ？
