### ISSUE TITLE
能不能推出TERMUX下的可编译的源码

### ISSUE THREAD

**Issue by tel13908519494** [vnpy/vnpy#280]
termux是安卓端的Linux，手机和电脑比，其实其优势还是蛮多，比如随身携带，单终端成本低，随便扔哪里只要有WIFI有点就可以跑代码等有点。我在CLONE现有代码到TERMUX下运行BUILD.SH的时候，出了一大堆错误，不知道什么时候更新一下可以在TERMUX下编译成功的代码。

**Comment by vnpy** [comment]
看了下，termux只是个android上的终端模拟器，而不是完整的系统。

另外vn.py支持的绝大部分API都是没有Android版本的，所以即使想支持也是无能为力。

最后用手机跑量化交易是一件比较不严谨的事情，作为机构投资者通常不会这么做。vn.py计划在v1.8开发Web终端，可以实现在服务器运行你的交易系统，然后通过手机实现监控。

**Comment by tel13908519494** [comment]
如果手机只是用来接收行情，多个手机向一个远程服务器推送行情数据，由远程服务器来排重加工数据，这种模式不是很经济吗？？另外，个人用户，办公室的网络总比家庭的问题，比如我的，我希望丢几个手机在办公室悄悄的干活，这也是我的一个小需求，总之我觉得是一个有意义的尝试。

**Comment by vnpy** [comment]
为什么不用远程服务器直接来收集行情呢？
