### ISSUE TITLE
portfolio_manager engine最后get_time_interval返回值错误

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#2800]
def get_timer_interval(self) -> None:
        """"""
        return self.timer_interval

要将返回的None类型修改为int

**Comment by vnpy** [comment]
已修复，#2820，非常感谢

**Comment by seabreeze912** [comment]
> ```
> def get_timer_interval(self) -> None:
>     """"""
>     return self.timer_interval
> ```
> 
> 要将返回的None类型修改为int

您好，最近在看vnpy的代码，想问一下app中，这个 portfolio_manager 和 portfolio_strategy 主要是做什么的么？代码看的有点晕。

**Comment by seabreeze912** [comment]
@smartgang 您好，想请教下app中的 portfolio_strategy 和 portfolio_manager 分别主要用来实现什么功能呢？代码看的有点晕。
