### ISSUE TITLE
在 jupyter 内 run_ga_optimization 会缓存优化目标 target_name 以致于调整后无法正确计算

### ISSUE THREAD

**Issue by lookis** [vnpy/vnpy#2801]
https://github.com/vnpy/vnpy/blob/f53749deffe5a516e790a9911ace1711f6a29649/vnpy/app/cta_strategy/backtesting.py#L1257-L1283

在 jupyter 做参数优化时，这里会做 lru cache ，优化目标 ga_target_name 不在 cache 的 key 列表内，如果修改了优化目标的话重新跑优化还会走缓存以至于输出错，可以在_ga_optimize函数里把 target 作为参数传入就好，而不是走全局变量

**Comment by vnpy** [comment]
已在dev分支修复：

https://github.com/vnpy/vnpy/blob/eb9db232fd53ada88314c4e627ce461a7f5caf3b/vnpy/app/cta_strategy/backtesting.py#L644
