### ISSUE TITLE
内盘ctp的连接，是否可以修改成不获取之前成交、委托的方式

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2805]
## 环境

* 操作系统: 如Windows 10

## Issue类型
三选一：Enhancement

## 预期程序行为

群主，您好

内盘ctp的连接，是否可以修改成不获取之前成交、委托的方式，这样在登录的时候比较节省性能，另外也让机器负荷变小，虽然下午收盘就又是第二个交易日不会再有之前的交易记录了，，，但是每天早上9点前开盘的登录，因为成交记录、委托的撤单太多，导致大概得5分钟才能登录好，，，如果是盘中出了问题必须重启，那就更是悲催的了。

希望vnpy能够从官方版本上进行修改。

如果vnpy确定不修改了，请您指导下该如何修改，谢谢！

**Comment by raycool** [comment]
应该是修改这个地方吧。
	///订阅私有流。
	///@param nResumeType 私有流重传方式  
	///        THOST_TERT_RESTART:从本交易日开始重传
	///        THOST_TERT_RESUME:从上次收到的续传
	///        THOST_TERT_QUICK:只传送登录后私有流的内容

**Comment by vnpy** [comment]
可以，修改这里两个订阅函数中的订阅模式（整数）即可：

https://github.com/vnpy/vnpy/blob/f8f76e6b71ff16a5066187b253371e0b956f12ef/vnpy/gateway/ctp/ctp_gateway.py#L757-L760
