### ISSUE TITLE
cta strategy 模块报错

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2812]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 2.8.1
## Issue类型
Bug

## 预期程序行为
None

## 实际程序行为
attributeError:'ctamanager' does not have a signal with the signature signal_strategy

## 重现步骤
启动ctaManager运行策略

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="687" alt="截屏2021-01-15 下午9 54 07" src="https://user-images.githubusercontent.com/12085501/104738777-eab39480-5780-11eb-8df4-5afb6e031962.png">

**Comment by noranhe** [comment]
不知道你启动脚本怎么修改的了，看日志应该是用的no_ui的脚本，但是CtaManager是图形界面的类了

**Comment by jieyujing** [comment]
> 不知道你启动脚本怎么修改的了，看日志应该是用的no_ui的脚本，但是CtaManager是图形界面的类了

def run_child():
    """
    Running in the child process.
    """
    qapp = create_qapp()
    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    main_engine.add_gateway(CtpGateway)
    main_engine.add_app(CtaStrategyApp)
    main_engine.connect(ctp_setting, "CTP")

    ctaUI = CtaManager(main_engine, event_engine)

    sleep(20)
    ctaUI.cta_engine.init_all_strategies()

    sleep(60)
    ctaUI.cta_engine.start_all_strategies()

    ctaUI.show()
    sys.exit(qapp.exec())

为了方便看变量，直接启动了cta 的ui，没有加载mainWindows。

**Comment by vnpy** [comment]
CtaManager没有正确初始化，请查看其中在初始化时需要调用的函数并进行对应操作。
