### ISSUE TITLE
coinbase的连接一直报Invalid API Key！的错误，可能是passphrase的API接口修改了，需要升级一下。

### ISSUE THREAD

**Issue by pnfgxw** [vnpy/vnpy#2816]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
应该是需要升级了，我们后续来安排下

**Comment by vnpy** [comment]
查了下文档，目前签名规则没有变化，建议检查是否填错了API Key

**Comment by vnpy** [comment]
测试后确认目前可以正常使用，关闭issue
