### ISSUE TITLE
mac 能支持ctp接口吗？

### ISSUE THREAD

**Issue by universewill** [vnpy/vnpy#2821]
mac 能支持ctp接口吗？

```
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'
```

**Comment by noranhe** [comment]
国内市场用到的绝大部分量化交易接口（如CTP、飞马、飞创、恒生等），其开发商只提供了Windows和Linux的API开发包。没有Mac版本（无法直接使用）的同时，也没有提供API源代码（无法自行编译），因此这类接口在Mac系统上无法使用（强行加载会报错找不到C++的DLL文件）。但纯Python接口和REST/WebSocket接口，由于不存在对于C++链接库的依赖，所以在Mac上均可以直接运行。

**Comment by universewill** [comment]
> 国内市场用到的绝大部分量化交易接口（如CTP、飞马、飞创、恒生等），其开发商只提供了Windows和Linux的API开发包。没有Mac版本（无法直接使用）的同时，也没有提供API源代码（无法自行编译），因此这类接口在Mac系统上无法使用（强行加载会报错找不到C++的DLL文件）。但纯Python接口和REST/WebSocket接口，由于不存在对于C++链接库的依赖，所以在Mac上均可以直接运行。

纯python接口或者REST/WebSocket接口，是指CTP、飞马、飞创、恒生等提供的接口吗？

**Comment by vnpy** [comment]
> > 国内市场用到的绝大部分量化交易接口（如CTP、飞马、飞创、恒生等），其开发商只提供了Windows和Linux的API开发包。没有Mac版本（无法直接使用）的同时，也没有提供API源代码（无法自行编译），因此这类接口在Mac系统上无法使用（强行加载会报错找不到C++的DLL文件）。但纯Python接口和REST/WebSocket接口，由于不存在对于C++链接库的依赖，所以在Mac上均可以直接运行。
> 
> 纯python接口或者REST/WebSocket接口，是指CTP、飞马、飞创、恒生等提供的接口吗？

国内市场的几乎没有纯Python版本。有的包括：数字火币、IB、富途、老虎等等

**Comment by xJayLee** [comment]
MAC上面，可以只把VNPY当做一个量化客户端，自动订单的可以通过Web
