### ISSUE TITLE
推荐使用 scikit-build 构建二进制模块

### ISSUE THREAD

**Issue by tinkernels** [vnpy/vnpy#2823]
## 环境

* 操作系统: windows 10、ubuntu 20.04
* Python版本: python 3.7.9
* vn.py版本: v2.1.8

## Issue类型
Enhancement

## 预期程序行为
源码目录 pip install . 时构建所有 C/C++ 模块

## 实际程序行为
windows 下不启动构建，linux 下只构建一部分

## 重现步骤

vnpy 源码目录 pip install .

**Comment by vnpy** [comment]
评估了下，发现：

1. scikit-build需要额外掌握CMake，于2014年针对C++和Fortran的复杂编译任务开发
2. 项目的Star和Fork数量均较低，且除了SciPy外没有找到知名的用户项目

综上对于vn.py来说，用scikit-build作为构建工具的意义不大，依旧保持使用现有方案。
