### ISSUE TITLE
币安的永续合约，平仓后，策略仓位没有变0，导致一直发数量为0的空单

### ISSUE THREAD

**Issue by gaozhong301** [vnpy/vnpy#2827]
## 环境

* 操作系统: 如Windows server 2019
* vn.py版本: 如v2.1.8
* 
## Issue类型
三选一：Bug/

## 重现步骤
错误截图
服务器在东京无网络问题。
![1](https://user-images.githubusercontent.com/46582179/106541383-ee933500-653c-11eb-914c-62336d737bca.jpg)
交易标的：EOSUSDT.BINANCES
bar：15分钟
策略：肯特钠通道上下轨进场，CCi低于正负44出场。固定手数5手。
使用停止单入场和出场。
错误描述
入场单没有问题，出场单完成后，策略的仓位没有清零，导致一直想服务器发送交易数量为0的平仓单，最后被服务器kill。

**Comment by vnpy** [comment]
已修复
