### ISSUE TITLE
查询活动委托请求出错，代码：1032，信息：The number of access exceeded the limit.    ##接口：HUOBIS

### ISSUE THREAD

**Issue by imjing0921** [vnpy/vnpy#2830]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
查询活动委托单超限了，可以定时几秒查一次

**Comment by vnpy** [comment]
已修复
