### ISSUE TITLE
价差交易模块，平仓时被动腿一直显示拒单；币安季度合约

### ISSUE THREAD

**Issue by Yaolinwang** [vnpy/vnpy#2832]
## 环境

* 操作系统: 如Windows 2012 数据中心R2
* vn.py版本: 如v2.1.8

## Issue类型
三选一：Bug

## 重现步骤
1. 服务器在香港无网络问题。
2. 交易标的：BTCUSD_210326.BINANCE （主动腿可以成交，每次都是被动腿未能成交）
3. 日志信息显示：14:02:05.545,"委托失败，状态码：400，信息：{""code"":-1102,""msg"":""Mandatory parameter '-1.0' was not sent, was empty/null, or malformed.""}",BINANCES
![image](https://user-images.githubusercontent.com/26902034/107110722-312e7780-6885-11eb-8d42-bdb74eee7b01.png)
![image](https://user-images.githubusercontent.com/26902034/107110797-c3cf1680-6885-11eb-9f22-267dafc2bf1c.png)

**Comment by noranhe** [comment]
是因为你下单的volume是负数吧

**Comment by Yaolinwang** [comment]
> 是因为你下单的volume是负数吧

我在开了一个价差策略后 - 策略开仓；然后我开了个平仓的策略，策略触发，但是只能平掉主动腿；这过程中我没有进行下单操作
这是价差交易界面的日志：
![image](https://user-images.githubusercontent.com/26902034/107113593-e28bd800-689a-11eb-9abd-1833b4342a36.png)

**Comment by vnpy** [comment]
已修复，非常感谢

**Comment by Yaolinwang** [comment]
> 已修复，非常感谢

那我现在需要更新VNPY吗？在登录的时候

**Comment by vnpy** [comment]
请等本周发布新版本后更新即可。
