### ISSUE TITLE
ubuntu下ctp连接失败，闪退。

### ISSUE THREAD

**Issue by tendrillion** [vnpy/vnpy#2833]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.9（64bit）
* vn.py版本: 2.1.8

## Issue类型
三选一：Bug

## 预期程序行为
登陆完ctp应该正常运行

## 实际程序行为
ctp连接失败，闪退。

## 重现步骤

参照说明执行连接CTP：https://www.vnpy.com/docs/cn/quickstart.html#id3

以SinNow仿真交易账号登陆CTP接口：
    用户名username：111111 （6位纯数字账号）
    密码password：1111111 （需要修改一次密码用于盘后测试）
    经纪商编号brokerid：9999 （SimNow默认经纪商编号）
    交易服务器地址td_address：218.202.237.33 :10102 （盘中测试）
    行情服务器地址md_address：218.202.237.33 :10112 （盘中测试）
    授权码auth_code：0000000000000000（16个0）
    名称app_id：simnow_client_test

执行结果：闪退。
错误信息：
(python:24635): dbind-WARNING **: 10:42:57.353: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
已放弃 (核心已转储)

**Comment by vnpy** [comment]
请使用该命令安装中文编码格式：

`
locale-gen zh_CN.GB18030
`

如果报错没有locale-gen就apt安装即可

**Comment by tendrillion** [comment]
按照给出的操作执行，没有再出现闪退的现象，但是交易服务器登录失败，提示为CTP:不合法的登录。操作日志为：
time,msg,gateway_name
15:44:03.8,交易服务器登录失败，代码：3，信息：CTP:不合法的登录,CTP
15:44:02.968,交易服务器授权验证成功,CTP
15:44:02.943,行情服务器登录成功,CTP
15:44:02.916,行情服务器连接成功,CTP
15:44:02.912,交易服务器连接成功,CTP

**Comment by tendrillion** [comment]
> 请使用该命令安装中文编码格式：
> 
> `locale-gen zh_CN.GB18030`
> 
> 如果报错没有locale-gen就apt安装即可

---------------------------------------------   回复  ------------------------------------------------------------
按照给出的操作执行，没有再出现闪退的现象，但是交易服务器登录失败，提示为CTP:不合法的登录。操作日志为：
time,msg,gateway_name
15:44:03.8,交易服务器登录失败，代码：3，信息：CTP:不合法的登录,CTP
15:44:02.968,交易服务器授权验证成功,CTP
15:44:02.943,行情服务器登录成功,CTP
15:44:02.916,行情服务器连接成功,CTP
15:44:02.912,交易服务器连接成功,CTP

**Comment by vnpy** [comment]
【不合法的登录】是指账户密码错误，请联系期货公司检查吧
