### ISSUE TITLE
目前是否真的支持max osx ?

### ISSUE THREAD

**Issue by lu-liu-perion** [vnpy/vnpy#2837]
如题 尝试安装几次 总是报错
但安装目录下发现 install mac osx setup 所以尝试安装
是否有人在 mac 上安装成功过 ？

**Comment by vnpy** [comment]
请查看社区论坛中的相关文章：www.vnpy.com/forum。

Mac OS并不是我们优先支持的系统，所以安装脚本的更新会有落后。
