### ISSUE TITLE
穿透式测试系统无法采集到硬件信息

### ISSUE THREAD

**Issue by kumapy** [vnpy/vnpy#2838]
## 环境

* 操作系统: 如Windows 7
* Python版本: 如Anaconda2，python 2.7
* vn.py版本: 如1.9.2. LTS

## Issue类型
三选一：Question

## 预期程序行为
客户端登陆测试系统，服务端顺利采集信息

## 实际程序行为
客户端顺利登陆测试系统（交易、行情均顺利连接、登录、验证通过），服务端有部分硬件信息采集不到（硬盘序列号、CPU序列号、bios序列号）

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
事前从期货公司传来CTP 6.5.1测试包，安装到gateway\ctptestGateway，修改了相应examples\Vntrader\CTPTEST_connect.json信息，在run.py中手动修改ctpGateway为ctptestGateway。
顺利登录测试系统。
但服务端有部分硬件信息采集不到（硬盘序列号、CPU序列号、bios序列号）
按照https://www.vnpy.com/forum/topic/603-kan-wan-zhe-pian-che-di-gao-ding-qi-huo-chuan-tou-shi-ctp-apijie-ru?page=1
的办法将wmic.exe路径添加到系统path，仍然采集不到
但手动cmd下命令可以查询到相关信息。

最终：期货公司建议咨询vnpy

**Comment by vnpy** [comment]
1. 穿透式测试请使用实体机，不要使用云服务器（可能没有：硬盘序列号、CPU序列号、bios序列号）
2. 老版本1.9.2已经停止维护，请升级到2.0新版本
