### ISSUE TITLE
运行vtMain.py,vntrader启动后，菜单里没有没有连接CTP的选项；

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#284]
Ubuntu 16.04 LTS
Python 2.7.12
terminal里的log:
twsapi.so: caannot open shared object file: No such file or directory
No module named vnshzd

**Comment by vnpy** [comment]
需要自己编译vn.ib接口后，把编译好的.pyd替换到ibGateway下面

**Comment by FallacyWalker** [comment]
怎么编译啊，给个文档的地址吧

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#2-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
参考这个CTP的来做
