### ISSUE TITLE
IB 在VNPY界面上的名称显示有问题

### ISSUE THREAD

**Issue by heshibs** [vnpy/vnpy#2848]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.1.8
* vn.py版本: 如v2.1.8发行版或者dev branch 20210201（下载日期）

## Issue类型
三选一：Bug

IB接口，TWS系统选择使用的英语，大部分期货股票的名称显示栏有问题，不能显示出正确的名称
![QQ图片20210220143047](https://user-images.githubusercontent.com/37288834/108586325-98215580-7388-11eb-903a-bb3a93ae9212.jpg)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
![微信截图_20210322210527](https://user-images.githubusercontent.com/11263900/111994128-5c79d700-8b52-11eb-89ce-749a380a5cdb.png)

测试可以正常显示，请升级到最新版本再试试，以及确保系统是Win10或者Server 2019，中文版。
