### ISSUE TITLE
币安永续接口无法正常下单

### ISSUE THREAD

**Issue by aijy** [vnpy/vnpy#2849]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.9
* vn.py版本: 如v2.1.9

## Issue类型
三选一：Bug

## 预期程序行为
币安永续接口连接后无法下单

## 实际程序行为
下单后遇到两种报错：编号 -4061和 -4164，如图编号所示。

## 重现步骤
连接币安永续接口后，下单就报错。
针对Bug类型Issue，请提供具体重现步骤以及报错截图
![币安异常](https://user-images.githubusercontent.com/31498816/108615954-f3644e00-7443-11eb-80eb-aab0c5eea774.PNG)

**Comment by vnpy** [comment]
请检查账户是否有做空权限，以及持仓是否设置为了全仓模式。
