### ISSUE TITLE
关于 oms 中持仓数据的更新问题

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#2851]
有些期货公司柜台的持仓查询返回会有较大的延时，导致获取当前持仓会有不同步的问题，可否考虑使用 on_trade 来更新 oms 中的持仓数据保证 oms 持仓数据不滞后？

**Comment by vnpy** [comment]
技术上可以，请参考vnpy.trader.converter中的逻辑实现：

1. 基于委托请求、委托回报、成交回报来实时计算仓位情况
2. 基于持仓查询数据来进行全量同步
