### ISSUE TITLE
币安永续-4061错误

### ISSUE THREAD

**Issue by chenglong-zhao** [vnpy/vnpy#2854]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.8

## Issue类型
三选一：Bug

## 实际程序行为
币安的永续合约接口，在双边持仓模式下，下单会出如下错误：
   **Code -4061 msg:  Order’s position side does not match user’s setting。**

在设置为单边持仓模式下，可以正常下单。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
币安目前支持两个模式：

1. One-way Mode的全仓模式，或者叫做单边持仓模式，这个是vn.py能支持的（和传统交易所规则一致）
2. Hedge Mode的逐仓模式，或者叫做对冲模式，这个是来自于零售外汇的持仓模式，vn.py无法支持这种

所以请选择One-way Mode后再使用vn.py即可。
