### ISSUE TITLE
rqdata历史数据查询转换时的浮点数精度问题

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#2855]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.9.1
* vn.py版本: VNStudio-2.1.9.1发行版
## Issue类型
三选一：Enhancement
## 实际程序行为
价格显示浮点精度问题

## 重现步骤

vnpy.trader.rqdata.py的query_history函数收到rqdata传来的数据后，把dataframe里的数据通过df.iterrows()处理。导致部分价格显示出现浮点精度问题
![q1](https://user-images.githubusercontent.com/63988546/109127632-9a6d2080-7789-11eb-8979-a5753f5ebf26.png)
这是收到时的数据
![q2](https://user-images.githubusercontent.com/63988546/109127679-a78a0f80-7789-11eb-8ad6-502dab349490.png)
这是处理后的数据

**Comment by vnpy** [comment]
已修复，非常感谢
