### ISSUE TITLE
火币永续-订单提交中

### ISSUE THREAD

**Issue by chenglong-zhao** [vnpy/vnpy#2856]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/

## 实际程序行为
在正向合约交易中，无论限价/市价单发送，都显示提交中。实际持仓已经变化。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请检查代理配置是否正确，如果错误则会由于Websocket无法连接导致收不到委托的状态变化推送
