### ISSUE TITLE
data_manager模块增加clear_overview功能

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#2857]
2.1.9.1 vnpy.database.sqlite.sqlite_database：
init_bar_overview函数下的overview.start和end写反了，而save_bar_data函数下的没写反，导致data_manager显示如下图：
![image](https://user-images.githubusercontent.com/63988546/109266308-d7491e00-7842-11eb-8eff-a9530f5bad62.png)

**Comment by vnpy** [comment]
已修复
