### ISSUE TITLE
关于仓位资金管理

### ISSUE THREAD

**Issue by akeyong** [vnpy/vnpy#286]
未来是否有计划在风险管理模块里面增加仓位资金管理功能或者单独增加一个仓位资金管理模块？比如当目前持仓超过账户资金多少比例就不再开新仓，或者如果加上新开的仓位后会导致总持仓超过账户资金多少比例从而拒绝执行，或者单个品种的持仓不能超过多少比例，诸如此类等等仓位和资金管理方面的功能，避免在某些特殊行情下，多周期多策略一下子发出太多的新开仓位，从而导致在宽幅震荡行情里让账户处于非常危险的状态。。。。因此感觉对于一个成熟的自动化交易系统而言，仓位资金管理模块是非常必要的！

**Comment by vnpy** [comment]
有考虑把风控模块里面的风控规则开发为一种动态的组件，这样方便用户自定义规则

**Comment by vnpy** [comment]
计算在v1.8实现风控组件灵活添加风控规则

**Comment by vnpy** [comment]
已添加保证金占比上限风控逻辑
