### ISSUE TITLE
币安永续-双向持仓

### ISSUE THREAD

**Issue by chenglong-zhao** [vnpy/vnpy#2864]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
目前币安永续接口默认并且只支持，单项持仓模式交易。这对于多策略-单品种的交易方式极不友好，策略直接会出现干扰。希望可以支持双向持仓模式。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by matthew77** [comment]
我一直收到“拒单”

**Comment by vnpy** [comment]
请参考#2854
