### ISSUE TITLE
使用 QTextEdit 显示日志

### ISSUE THREAD

**Issue by tinkernels** [vnpy/vnpy#2865]
## 环境

* 操作系统: windows 10
* Python版本: python 3.7.9
* vn.py版本: v2.1.9.1

## Issue类型
三选一：Enhancement

## 预期程序行为
UI 日志显示单条内容 wrap

## 实际程序行为
UI 日志显示有时会横向滚动

## 重现步骤
CTA策略 UI 中日志消息内容单条稍长时, 横向滚动 scroll bar 行为异常

**Comment by vnpy** [comment]
已合并到dev-logmonitor分支
