### ISSUE TITLE
跨市场交易的价差的交易时间不同如何保证价差数据准确

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2868]
## 环境
* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6

## Issue类型
三选一：Question

## 预期程序行为

群主，您好
请教群主个问题，

对于跨市场的spread，因为有时间差（比如内盘的时间不交易，那么ctp和ib的价差数据就会在内盘不交易时间不准确了），那么这个时候分钟的bar有不需要录入和不需要在K线图上显示的，最优的处理方式该如何处理？
恳请群主指导下，谢谢！

我想到的方式，在价差的engine位置，增加timer事件，判断这个价差对应的交易时间，如果不在交易时间了（具体到时分秒，在开始和结束时间，提前几秒结束和延迟几秒开始），设置个“交易标识flag”，不在交易时间设置为false，那么在类class SpreadDataEngine的 def process_tick_event 位置，如果“交易标识flag”是false了，不再调用 self.put_data_event(spread)，到了交易时间，继续调用 self.put_data_event(spread) 的，

不知道这样的处理方式是不是从架构上最优的？

另外这样是否可以保证K线图上的bar是准确的（会不会有跨分钟的数据更新错误？）？是否可以保证小时的k线数据保存是正确的？

恳请百忙中指导下，谢谢！

**Comment by stone3536** [comment]
2.1.9版本

**Comment by vnpy** [comment]
技术上这么做没问题，通过定时事件来检查肯定比每个Tick都进行检查效率要来的高。

我个人更推荐非交易时段由交易员自行停止算法，毕竟价差交易中交易员还是很重要的。
