### ISSUE TITLE
CTP Api 请求间隔控制

### ISSUE THREAD

**Issue by tinkernels** [vnpy/vnpy#2869]
## 环境

* 操作系统: windows 10
* Python版本: 3.7.9
* vn.py版本: v2.1.9.1

## Issue类型
Enhancement

## 预期程序行为
连续 CTP Api 请求正常响应

## 实际程序行为
当没有控制请求间隔的时候, CTP Api 请求连续发出(两个或以上), 只有第一个请求响应

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
- 连接 CTP
- 顺序调用 CTP TdApi 查询合约手续费和保证金比例

**Comment by vnpy** [comment]
CTP有查询流控，每秒所有类型请求都只能发起一个，具体请查看上期技术的CTP技术文档
