### ISSUE TITLE
无法导入DB_TZ问题

### ISSUE THREAD

**Issue by googlefan** [vnpy/vnpy#2872]
## 环境

* 操作系统: Mac os Big Sur
* Python版本: 如Anaconda 3.8
* vn.py版本: 如v2.1.9.1

## Issue类型
三选一：Bug

## 预期程序行为
执行启动时候可以正常使用cat策略

## 实际程序行为
执行启动时候报错：
ImportError: cannot import name 'DB_TZ' from 'vnpy.trader.database' 
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/3354782/109742969-e77a4800-7c0a-11eb-9fa4-d50d117a8124.png)

**Comment by vnpy** [comment]
最新dev分支已经包含DB_TZ常量，请等待2.2.0发布后更新试下
