### ISSUE TITLE
回测后绘制图表默认1m问题

### ISSUE THREAD

**Issue by amangqq** [vnpy/vnpy#2875]
## 环境

* 操作系统: Windows 10
* Python版本: 3
* vn.py版本: 2.19

## Issue类型
三选一：Question

## 预期程序行为
希望在回测后绘制图表，可以自定义K线图周期，而不是默认1m。
或者在源码哪里可以修改？

**Comment by vnpy** [comment]
可以通过BarGenerator来将1分钟K线合成更高级别的K线，然后显示在图表中即可，目前我们官方团队暂无进一步增强K线图表的计划
