### ISSUE TITLE
火币永续接口合约乘数有问题

### ISSUE THREAD

**Issue by aijy** [vnpy/vnpy#2880]
## 环境
* Python版本: 如VNStudio-2.1.9

## Issue类型
三选一：Bug
火币永续接口合约乘数为小数的数字货币无法使用价差交易。

## 预期程序行为
火币永续接口很多数字货币合约乘数是小数，比如BTCUSDT是0.001，在huobis接口中将乘数转为整形就变为0，影响后续对乘数的调用。

## 实际程序行为
火币永续正向接口，价差交易中有些数字货币下单量一直为0。

## 重现步骤
![image](https://user-images.githubusercontent.com/31498816/110098456-2fe86000-7ddb-11eb-8acc-5d687b68cce5.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，非常感谢
