### ISSUE TITLE
install.bat on windows error

### ISSUE THREAD

**Issue by arisliang** [vnpy/vnpy#2882]
## 环境

* 操作系统: Windows 10
* Python版本: 3.7.9, conda 4.9.2
* vn.py版本: vnpy-2.1.9

## Issue类型
三选一：Bug

## 预期程序行为
install.bat成功无错误

## 实际程序行为
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.1.5 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
spyder 4.1.5 requires pyqt5<5.13; python_version >= "3", but you have pyqt5 5.14.1 which is incompatible.

![image](https://user-images.githubusercontent.com/1115503/110232037-29322800-7f56-11eb-9b3b-faf0e696414b.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1. create anaconda environment with:
 dependencies:
  - python = 3.7
  - anaconda
  - pip

2. `install.bat`

**Comment by arisliang** [comment]
`install.bat` 还有必要运行吗？是不是只要安装vn studio就行了？

**Comment by vnpy** [comment]
新手推荐用VN Studio（卸载其他Python环境），install.bat是给Python官方社区的发行版用的，Anaconda因为有很多版本依赖的问题需要用户会手动处理，不推荐用
