### ISSUE TITLE
新版中两个文件代码位置错误

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2884]
## 环境

* vn.py版本: 如v2.1.x，最新版

## Issue类型
三选一：Bug

## 预期程序行为
群主，您好，
新版的文件中发现以下两个错误：

一、
文件：postgresql_database.py 中的
def save_tick_data(self, ticks: List[TickData]) -> bool:
中，d["interval"] = d["interval"].value
是垃圾代码，导致直接卡死了，需要删除掉，tick是没有interval的。

二、文件：data_recorder 下的engine.py
def add_bar_recording(self, vt_symbol: str):
中的 self.tick_recordings[vt_symbol] = {}
应该是 bar_recordings

以上两个错误都导致dr模块无法录制数据。

**Comment by vnpy** [comment]
已修复，非常感谢
