### ISSUE TITLE
ib标的，tick和bar都无法保存到数据库中

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2886]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.最新

## Issue类型
三选一：Bug

## 实际程序行为

群主，您好
ib的标的tick和bar都无法保存到数据库中，对于内盘标的以及价差数据的tick、bar，都可以正常保存的，debug了几次，都无法在保存位置确认出具体问题，请帮忙确认下，谢谢！

debug截图
![ib的标的tick无法保存到数据库中](https://user-images.githubusercontent.com/31505150/110415529-00806e80-80cd-11eb-9729-26011dda94b6.png)

**Comment by stone3536** [comment]
debug到这个位置已经是执行过for循环里边 的  DbTickData.insert(d).on_conflict( 行了，再单步就退出for的了。

**Comment by stone3536** [comment]
使用K线图表来看ib的标的的K线的时候，无法显示，然后一步步找到这里的。

**Comment by stone3536** [comment]
目前确定是it的gateway中的
if exchange is Exchange.IDEALPRO:
限制导致
        tick.last_price = (tick.bid_price_1 + tick.ask_price_1) / 2
        tick.datetime = datetime.now(self.local_tz)
价格是时间没有更新到XAUUSD标的上导致的，修改了这个位置就可以了。

不知道为啥没加SMART这个交易所的。
另外想请群主确认下，这里是不是直接都更新价格和时间不就可以了吗？ 为啥非得区分IDEALPRO 的呢？
谢谢，盼复！

**Comment by vnpy** [comment]
已修复，非常感谢。

**Comment by vnpy** [comment]
> 目前确定是 ib 的gateway中的
> if exchange is Exchange.IDEALPRO:
> 限制导致
> tick.last_price = (tick.bid_price_1 + tick.ask_price_1) / 2
> tick.datetime = datetime.now(self.local_tz)
> 价格、时间没有更新到XAUUSD标的上导致的，修改了这个位置就可以了。
> 
> 不知道为啥没加SMART这个交易所的。
> 另外向群主请教下，这里是不是直接都更新价格和时间不就可以了吗？ 为啥非得区分IDEALPRO 的呢？
> 谢谢，盼复！

IB中只有外汇（IDEALPRO交易所）和现货贵金属（CMDTY产品），因为是IB的OTC交易，所以没有提供最新成交数据（即没有last_price和datetime），因此必须采用本地计算的方式来模拟。

之前的写法中，漏掉了现货贵金属的判断逻辑（因为曾经现货贵金属也是属于IDEALPRO交易所，后来改了）。
