### ISSUE TITLE
K线图显示数据对应的下边时间有问题

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2887]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.最新

## Issue类型
三选一：Bug/Question

## 实际程序行为
群主，您好

K线图，显示第一根K线时对应下边的时间有冗余的，即使等到第二根K线显示，也仍旧有问题。

第一根K线图：
![1](https://user-images.githubusercontent.com/31505150/110415863-a92ece00-80cd-11eb-8ad2-12a6cc672c51.png)

第二根K线图：
![2](https://user-images.githubusercontent.com/31505150/110415873-acc25500-80cd-11eb-86e1-3b2f1282a56c.png)

**Comment by stone3536** [comment]
群主，请问这里K线图，是否可以优化成假如K线图“根据每根K线图的最小宽度”不够铺满整个屏幕的数量，直接就根据每根K线图最小宽度显示，最右边空白出来，再次新出来的K线再继续往右更新，满了再根据规则移动。
另外，K线图上十字光标线，是否可以增加使用ESC键取消掉的功能？

**Comment by vnpy** [comment]
已修复，非常感谢。

十字光标目前无法取消
