### ISSUE TITLE
是否可以增加 spread_name.LOCAL 价差的K线图显示呢？

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2889]
## 环境
* vn.py版本: 如v2.1.x

## Issue类型
三选一：Enhancement

群主，您好

是否可以考虑增加 spread_name.LOCAL 价差的K线图显示呢？

我通过增加 EVENT_SPREAD_DATA 的功能，实现了价差的分钟线显示在K线图上了，但是希望vnpy从原始功能上就增加上的。

vnpy的架构设计确实是漂亮，感恩，谢谢！

**Comment by vnpy** [comment]
已添加
