### ISSUE TITLE
建议在文件中增加 最近修改日期

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#289]
经常更新，有的文件我们也改动过。不时不知道到底要不要换。
建议在文件头部中，增加 最后修改日期
# lastupdated: 20170414  这样的

**Comment by vnpy** [comment]
有道理，我来逐渐加上吧，不过这个是否有能够自动实现的方案呢？

**Comment by kingmo888** [comment]
@vnpy 写个脚本判断修改日期？

**Comment by vnpy** [comment]
最近参考了一些其他的项目，计划如下：
1. 未来vnpy添加setup.py后，会在项目信息中添加最近更新的日期
2. 每个文件中添加修改日期的方式在实践中比较繁琐，我比较粗心也容易忘记，所以暂时不考虑了
3. vnpy未来会采用安装到python库中的方式，保留较好的向下兼容性，慢慢变成真的一个框架（类似flask），降低对用户代码的入侵性，简化升级时的难度
