### ISSUE TITLE
在编译测试和生产版本的CTP库的项目时候，出现的问题

### ISSUE THREAD

**Issue by huluBrother** [vnpy/vnpy#2894]
## 环境

* 操作系统: 如Windows 10 
* Python版本: Python3.7
* vn.py版本: master 分支 下载日期 2020110（下载日期）

## Issue类型
Question

## 预期程序行为
我打算了解一下VNPY对CTP库的封装，对`./vnpy/vnpy/api/ctp`目录下的visual studio 项目进行重新编译，生成一个测试版本的CTP库和正式版本的CTP库。

## 实际程序行为
我整理出来了`./vnpy/vnpy/api/ctp`目录下的visual studio项目   
依据 `项目--》重定解决方案 ` ，将项目的Windows SDK版本制定到 10.0.17763.0   
配置了 `项目--> 属性--->  配置属性---> c/c++--->常规 ---> 附加包含目录` ,
![image](https://user-images.githubusercontent.com/18010792/111099169-e1c42100-857f-11eb-8553-51b72bee068a.png)

旨在为`vnpyc\include\pybind11\detail\common.h`添加<Python.h>文件，

![image](https://user-images.githubusercontent.com/18010792/111099199-f6081e00-857f-11eb-8c6b-2940db987277.png)

但是实际的编译结果确实这样的
![image](https://user-images.githubusercontent.com/18010792/111099236-08825780-8580-11eb-9cfb-4d6541d4cdc4.png)

![image](https://user-images.githubusercontent.com/18010792/111099245-0f10cf00-8580-11eb-83d4-37ea6a4a12d4.png)

我哪里出现错误，我应该如何解决这些问题？

**Comment by vnpy** [comment]
在项目的配置中，请添加你的Python环境目录，包含Include Path和Reference Path等
