### ISSUE TITLE
XtpGateway，行情服务器连接错误-1

### ISSUE THREAD

**Issue by yangco** [vnpy/vnpy#2896]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
BUG

多网卡情况下，连接XTP 行情服务报错（-1），vnpy 当前版本XTP Login接口不能设置本地IP。最新版本XTP Login接口可以设置local_ip,  请升级下XTP版本。 
int Login(const char ip, int port, const char user, const char password, XTP_PROTOCOL_TYPE sock_type, const char local_ip = NULL)

**Comment by vnpy** [comment]
查了下vn.py目前对接的XTP API版本尚未支持该local_ip字段，我们在后续版本来升级下吧

**Comment by vnpy** [comment]
已更新，将在2.4.0发布
