### ISSUE TITLE
一个市场内，两个合约的模型如何处理

### ISSUE THREAD

**Issue by ideaplat** [vnpy/vnpy#29]
比如CTP中，两个合约的单模型如何处理？
是分成两个模型分别处理，互不影响还是一个模型中引入两个合约，来处理？

**Comment by vnpy** [comment]
如果是一个策略里面用到两个或者以上的合约行情来判断信号并且交易，那么目前CTA模块是用不上的，这种需求建议自己改写CTA引擎和策略模板。

这种策略往往涉及套利或者价差交易，都要配合一些特殊的下单算法，每一个策略间的区别非常大，所以也很难抽象成为一个策略模板。

我自己的话更宁愿基于事件引擎和主引擎，来直接开发一个策略算法的Class，而不使用引擎和模板。
