### ISSUE TITLE
数据管理，是否可以增加对于具体行的错误数据删除功能；更新数据，报错

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2906]
## 环境

* vn.py版本: 如v2.1.9.x(2021.02.24下载的)

## Issue类型
三选一：Bug/Enhancement

群主，您好

对于查看数据位置右侧具体数据行，是否可以增驾对于具体行的错误数据删除功能，这样方便操作，因为确实可能会存在某一行数据不准确的情况，而此时再使用下载、修改数据、再次导入覆盖的方式及其不方便。
恳请考虑增加该方便操作功能，谢谢！

另外，在查看模式下，点击“更新数据”，直接报错，错误信息

Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\app\data_manager\ui\widget.py", line 355, in update_data
    data = self.engine.get_bar_data_available()
AttributeError: 'ManagerEngine' object has no attribute 'get_bar_data_available'

**Comment by vnpy** [comment]
bug已修复，具体数据的修改，可以通过DBeaver之类的数据库工具来实现
