### ISSUE TITLE
Rpc在使用非对称加密后，无法正常退出的Bug

### ISSUE THREAD

**Issue by zhouwuji** [vnpy/vnpy#2907]
## 环境

- 操作系统: Ubuntu 18.04 和 20.04
- Python版本: python3.7、python3.8
- vn.py版本: v2.1.7 、v2.1.9

## Issue类型
Bug

## 预期程序行为
使用非对称加密的Rpc服务器时，在调用main_engine.close()之后，程序正常退出

## 实际程序行为
在调用main_engine.close()之后程序没有正常退出，出现进程futex挂起的情况，直到Ctrl + C退出。用nohup+crontab每天定时运行的话就会受到影响，除非手动kill掉futex阻塞的Python进程。推测应该是authenticator没有正常退出导致的。

## 重现步骤
复现的代码如下

1，创建服务器的私钥
![image](https://user-images.githubusercontent.com/31885084/112126424-66a5df00-8bff-11eb-923a-31e4f26c0d75.png)

2，给RpcServiceApp的start方法增加server_secretkey_path选项传入self.server
![image](https://user-images.githubusercontent.com/31885084/112126327-4d9d2e00-8bff-11eb-99e4-154b7887b42e.png)

3，执行以下代码

```
# rpc_demo.py

from vnpy.event import EventEngine, Event
from vnpy.trader.engine import MainEngine
from vnpy.trader.event import EVENT_LOG
from vnpy.app.rpc_service import RpcServiceApp, RpcEngine
from vnpy.app.rpc_service.engine import EVENT_RPC_LOG


def process_log_event(event: Event):
    """"""
    log = event.data
    msg = f"{log.time}\t{log.msg}"
    print(msg)


if __name__ == '__main__':
    print("程序开始运行" + "*" * 100)

    event_engine = EventEngine()
    event_engine.register(EVENT_LOG, process_log_event)
    event_engine.register(EVENT_RPC_LOG, process_log_event)

    main_engine = MainEngine(event_engine)
    rpc_engine: RpcEngine = main_engine.add_app(RpcServiceApp)

    rpc_engine.start(
        "tcp://*:2014",
        "tcp://*:4102",
        "./certificates/server.key_secret"
    )

    main_engine.close()

    print(f"程序运行结束\n")

```
![image](https://user-images.githubusercontent.com/31885084/112124175-07df6600-8bfd-11eb-97be-8cc87d350b50.png)
![image](https://user-images.githubusercontent.com/31885084/112124256-1e85bd00-8bfd-11eb-93c7-e1389bed8408.png)
![image](https://user-images.githubusercontent.com/31885084/112124403-42490300-8bfd-11eb-8c2e-e44cb66424c8.png)
![image](https://user-images.githubusercontent.com/31885084/112125346-49244580-8bfe-11eb-8b69-fcd7c6175720.png)

解决方案是在vnpy/rpc/\_\_init\_\_.py的RpcServer.run方法结束时调用__authenticator的stop方法

![image](https://user-images.githubusercontent.com/31885084/112125576-8c7eb400-8bfe-11eb-8913-afbd31dd0f12.png)

**Comment by vnpy** [comment]
已修复，非常感谢！

**Comment by vnpy** [comment]
方便的话欢迎加个我的微信

![单人二维码](https://user-images.githubusercontent.com/11263900/112262010-e12a3980-8ca7-11eb-802d-e45b598bf793.png)

**Comment by zhouwuji** [comment]
> 已修复，非常感谢！

大佬客气了，从您开源的vnpy项目学到了很多，已添加您微信，谢谢！
