### ISSUE TITLE
OKEx报错

### ISSUE THREAD

**Issue by KAMIENDER** [vnpy/vnpy#2917]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.7
* vn.py版本: 最新版

## Issue类型
Question

## 预期程序行为
可以正常连接okex的服务器

## 实际程序行为
一直报400，接口返回的是
请求失败，状态码：400，信息：{"error_message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey.","code":30016,"error_code":"30016","message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey."}
问官网客服，说是已经不支持v3的api了，现在已经是v5的，有什么办法可以解决这个问题

**Comment by vnpy** [comment]
我们会在下个版本增加对V5的支持，另外你这里的报错是因为在用V1的API KEY，请用重新申请一个V3的KEY再用即可
