### ISSUE TITLE
BINANCES gateway 无法启动strategy

### ISSUE THREAD

**Issue by matthew77** [vnpy/vnpy#2918]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 2.2.0

## Issue类型
Bug

## 预期程序行为
策略加载历史数据成功

## 实际程序行为
策略加载历史数据失败

## 重现步骤

启动策略：

12:22:28.529,行情Websocket API连接刷新,BINANCES
12:22:28.478,"获取历史数据失败，状态码：400，信息：{""code"":-1023,""msg"":""Start time is greater than end time.""}",BINANCES
12:22:28.442,获取历史数据成功，BTCUSDT - 1m，2021-01-09 12:23:00+08:00 - 2021-01-10 13:22:00+08:00,BINANCES
12:22:22.624,交易Websocket API连接成功,BINANCES
12:22:22.573,合约信息查询成功,BINANCES
12:22:22.529,委托信息查询成功,BINANCES
12:22:22.475,持仓信息查询成功,BINANCES
12:22:22.419,账户资金查询成功,BINANCES
12:22:22.319,REST API启动成功,BINANCES

**Comment by zhengow** [comment]
binances_gateway.py的750行-751行逻辑有错误

**Comment by zhengow** [comment]
binances_gateway.py的query_history（676行）函数有逻辑错误

**Comment by noranhe** [comment]
![6b74f437818816029db3ec1b1e617f8](https://user-images.githubusercontent.com/63988546/112817623-39e94000-90b5-11eb-9131-16b8f9bf0327.png)
![88c91b12219b84d0b13a53b7d267f50](https://user-images.githubusercontent.com/63988546/112817750-5dac8600-90b5-11eb-9e05-157080986102.png)
请升级至2.2.0版本再试试看
