### ISSUE TITLE
daily_return统计指标计算有BUG

### ISSUE THREAD

**Issue by zhengow** [vnpy/vnpy#2924]
## 环境

* 操作系统: Windows 10
* Python版本: 3.7
* vn.py版本: v2.2.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
在比日线频率更快的策略回测中（如分钟，小时回测），应考虑balance到第一天结束（**即回测开始到第一天末**）的daily_return，以及基于daily_return计算的如夏普比率等指标。

## 实际程序行为
然而在文件例如vnpy.app.cta_strategy.backtesting的BacktestingEngine中，未考虑上述情况，导致统计指标计算不符合预期

## 重现步骤
如某策略在第一天**内**就出现盈利或亏损，则会出现统计指标与预期不符合。例如以下截图，**负的**收益率计算出**正的**夏普
![image](https://user-images.githubusercontent.com/38389586/113085438-5ea6fa00-9212-11eb-9235-dc08cbd4de2d.png)

主要逻辑错误在下述这一行代码：
![image](https://user-images.githubusercontent.com/38389586/113085496-839b6d00-9212-11eb-91ed-c2afe14a7a57.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by zhengow** [comment]
原：df["return"] = np.log(x).fillna(0)
修改为：
df["return"] = np.log(x).fillna(np.log(df["balance"][0]/self.capital))
即可

**Comment by vnpy** [comment]
已在vnpy_ctastrategy项目中修复
