### ISSUE TITLE
标的fut类型的成交后报错can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2928]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.9.x

## Issue类型
三选一：Bug

## 实际程序行为
群主，您好

做合约 fut类型的时候，可能有错误，使用标的 HG-202105-25000-USD-FUT.NYMEX
的时候，确定有bug，会在portfolio_manager 的base的 函数 中报错，错误信息是size 不是int类型，debug进去发现是'25000'的，用其他标的进行了测试，没这类问题的。

使用的是vnpy的主界面委托单，市价，立刻成交后，就报错了。后续就跑不下去了。

请确认是否此处有bug。
详细错误信息（最后部分）：
File "D:\00_VNPY_2.x\Anaconda3\Lib\site-packages\vnpy\app\portfolio_manager\engine.py", line 116, in process_timer_event
  contract_result.calculate_pnl()
￼ File "D:\00_VNPY_2.x\Anaconda3\Lib\site-packages\vnpy\app\portfolio_manager\base.py", line 71, in calculate_pnl
  trade_cost = trade.price * trade_volume * size
builtins.TypeError: can't multiply sequence by non-int of type 'float'

截图如下：
![错误-1](https://user-images.githubusercontent.com/31505150/113238214-de000080-92da-11eb-8d68-c84fe7bba0d1.png)

**Comment by stone3536** [comment]
print的信息如下：
contract.size: type: <class 'str'>
确定是str类型导致的。
对size进行了int后就没错误了。

**Comment by vnpy** [comment]
已修复
