### ISSUE TITLE
标的fut类型的无法自动订阅及获取合约行情信息

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2929]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.9.x

## Issue类型
三选一：Bug

## 实际程序行为

群主，您好

做合约 fut类型的时候，使用标的 HG-202105-25000-USD-FUT.NYMEX
目前确认，

一、
在行情记录中，输入该标的合约，无法进行K线和bar的添加，报错信息：
11:20:39	找不到合约：HG-202105-25000-USD-FUT.NYMEX
（在行情记录以及spread中，都有此问题的）其他标的xag、eur等都可以的。

二、
在vnpy主界面中，选择交易所NYMEX ，输入标的HG-202105-25000-USD-FUT，选择接口ib，回车，无法获得行情数据，试过多次，都不可以的，其他标的xag、以及eur都是可以的。
然后在不做任何操作的情况下，选择类型市价，输入数量1，点击委托，立刻成交，此时行情就自动订阅过来了。

确定以上一、二处有bug的，请在vnpy原始版本中修改吧，谢谢！

**Comment by stone3536** [comment]
补充下，这次测试，获得过来的不是 HG-202105-25000-USD-FUT 的，而是HG-20210526-USD-FUT 也就是NYMEX Copper Index的，HG-202105-25000-USD-FUT在行情清淡中反倒是没有的呢，确认过3次，也仔细查找了。

再次重新登录，测试，获得过来的标的就又有
HG-202105-25000-USD-FUT 了，
当然同时 HG-20210526-USD-FUT 也被带了过来的，这个index是否获取行情的时候可以不带过来？

**Comment by stone3536** [comment]
群主，您好，对于合约有进行了详细测试，目前结果如下，

"HG-20210728-USD-FUT.NYMEX"，获取过来的是指数吧？

而对于具体标的 "HG-202107-25000-USD-FUT.NYMEX"，在界面上是有时候可以获取到行情、可以交易的，但是在
 self.contracts 中就没有合约的，那么在dr模块添加K线的时候就没有办法找到"HG-202107-25000-USD-FUT.NYMEX"的，就报错
“找不到合约：HG-202107-25000-USD-FUT.NYMEX”

感觉这里确实是有问题的，因为在vnpy1.9.2中是不存在这种问题，使用的是“Symbol：HGN1”的。
在tws界面输入HGN1或者选择对应的月份合约，会把对应的index也自动带过来的。但是在 self.contracts 中就没有 "HG-202107-25000-USD-FUT.NYMEX"的。

目前用 “HG-202107-25000-USD-FUT.NYMEX”和 "HG-202107-25000-USD-FUT.NYMEX" 在主界面都可以手工交易的，交易出来的也是同一个标的HGN1的，但是描述信息获取过来的是index的；
另外就是在dr模块，不能使用"HG-202107-25000-USD-FUT.NYMEX"进行操作的。

疑惑的是，在主界面为啥2个标的都可以？但是在dr模块只能用一个的，具体原因是啥？

恳请百忙中帮忙解答下，谢谢！

**Comment by stone3536** [comment]
使用 "HG-20210728-USD-FUT.NYMEX" 应该可以的。但是还是想不通原因的。

**Comment by stone3536** [comment]
补充2个截图如下，刚才漏掉上传截图了：
![HG--1](https://user-images.githubusercontent.com/31505150/114962705-c8273980-9e9d-11eb-9722-5c0042dfac24.png)


![HG--2](https://user-images.githubusercontent.com/31505150/114962738-d8d7af80-9e9d-11eb-8f51-c35bfad721df.png)

**Comment by noranhe** [comment]
可参考此贴的21楼和25楼
https://www.vnpy.com/forum/topic/3751-qing-jiao-xia-zen-yang-ibying-tou-li-esde-li-shi-shu-ju?page=2

**Comment by stone3536** [comment]
收到，感谢！
