### ISSUE TITLE
是否可以在Gatway增加重建orderbook的 抽象方法，增加OrderBook类型。

### ISSUE THREAD

**Issue by Wei-Jianan** [vnpy/vnpy#2932]
## Issue类型
三选一：Enhancement

就是个讨论。在考虑做基于orderbook的策略。

**Comment by Wei-Jianan** [comment]
ordrebook太过庞大，不比五档行情，不适合作为dataclass，反复构建，并放入event进入队列中通讯。可能得单独做一个app。我在考虑，是做一个orderbook_trading还是做一个其他的可以让order复用的方案。
前者的话，OrderBook类型的设计更新比较自然，但毕竟还是需要gateway的支持。后者，这个Orderbook的设计就比较复杂了，得考虑各种app的兼容，不能随意构造，只能是全局唯一。

**Comment by vnpy** [comment]
OrderBook这块不同接口的数据流区别太大无法标准化，所以在vn.py中不适合作为标准模块，请根据自己的需求开发吧
