### ISSUE TITLE
ubuntu 18.04 安装完成后无法启动

### ISSUE THREAD

**Issue by huangyingjie** [vnpy/vnpy#2933]
## 环境

* 操作系统:  Ubuntu 18.04
* Python版本: 3.7.6
* vn.py版本: 2.2.0

## Issue类型
三选一：Bug
## 报错信息
安装成功后，执行python run.py，报以下错误，试过N种方式仍失败
```bash

qt.qpa.xcb: could not connect to display :1.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

**Comment by sharp** [comment]
难用到家

**Comment by vnpy** [comment]
这是Qt的报错，请开启Qt的DEBUG环境变量后，再运行启动，即可看到具体的报错输出，应该是少了某个图形驱动库so导致的。

设置环境变量的方法，请在terminal中运行，再在当前terminal启动VN Trader：

`set QT_DEBUG_PLUGINS=1`

**Comment by xfzen** [comment]
Need to install libxcb for Fresh Ubuntu installation,
sudo apt install --reinstall libxcb-xinerama0
