### ISSUE TITLE
for循环中使用遗传算法优化参数的问题

### ISSUE THREAD

**Issue by wyx-tree** [vnpy/vnpy#2936]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Question

## 实际程序行为
![image](https://user-images.githubusercontent.com/56290638/113654628-d4a3d900-96ca-11eb-9c91-f14f0268f9a9.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/56290638/113654711-fc933c80-96ca-11eb-825d-2e5418fdf65b.png)

## 问题
使用for循环进行多个标的的遗传算法优化，发现以上问题。第一个标的正常运行，之后的标的都不会启动遗传算法，打印出的结果直接是第一个标的的优化结果。
请问这个问题如何处理？

**Comment by wyx-tree** [comment]
看来我只能用多进程来试试了

**Comment by vnpy** [comment]
该问题由于遗传算法的lru_cache缓存没有清空导致，2.2.0版本已经修复了，请升级到最新版试试
