### ISSUE TITLE
官网微信登录页面刷不出来

### ISSUE THREAD

**Issue by learnpythontheew** [vnpy/vnpy#2938]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

如题，一直刷不出来微信登录页面。
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/29298489/113885902-cea91780-97f2-11eb-9f06-084b526d7830.png">

**Comment by vnpy** [comment]
这里是直接跳转微信官网的二维码接口进行认证，所以请试试在你的机器上直接登录微信客户端，是否能打开二维码扫描页面吧
