### ISSUE TITLE
QTtable太慢了，下1000单后，订单状态会长时间持续在“提交中”

### ISSUE THREAD

**Issue by jnydfc** [vnpy/vnpy#2939]
![image](https://user-images.githubusercontent.com/14302726/113887770-5b080a00-97f4-11eb-91bb-1658459202fd.png)

ctp也是一样的，QTtable相关的问题，现在做法：只显示几十条数据或者在vnpy\trader\object.py里ACTIVE_STATUSES = set([Status.NOTTRADED, Status.PARTTRADED])

不知怎么才能彻底解决

**Comment by vnpy** [comment]
1. 提交中状态，是接口层返回的，和图形界面无关
2. 现在PyQt5版本的QTable，撑个几万条显示无卡顿还是很简单的

请检查下是否因为短时间发单过多，被TWS流控了吧。
