### ISSUE TITLE
请问实盘中错误日志该如何打印？

### ISSUE THREAD

**Issue by wyx-tree** [vnpy/vnpy#2945]
问题：
请问实盘中错误日志该如何打印？
![image](https://user-images.githubusercontent.com/56290638/114406055-cf1e2580-9bd9-11eb-89cf-9db284dfd939.png)
有能设置日志等级的地方吗？
或者可以告诉我vnpy用的哪个日志的组件  我去研究下

**Comment by vnpy** [comment]
主界面顶部菜单栏的【配置】对话框中有log相关的配置，可以选择是否要开启日志，以及是否要记录的日志级别信息

**Comment by wyx-tree** [comment]
> 主界面顶部菜单栏的【配置】对话框中有log相关的配置，可以选择是否要开启日志，以及是否要记录的日志级别信息

请问代码层面上时怎么弄    我不用UI界面的。

**Comment by vnpy** [comment]
用图形界面修改后保存即可，或者也可以手动修改该文件里的配置：

`C:\users\administrator\.vntrader\vt_setting.json`
