### ISSUE TITLE
huobif_gateway查询历史数据报错

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#2951]
huobif_gateway查询分钟及小时级别的历史数据报错（查询日线不报错），底层报错如下：
![914befaf0ede4b2e7a22acf46e71a63](https://user-images.githubusercontent.com/63988546/114962352-1b4cbc80-9e9d-11eb-8aa2-abebde9282c3.png)

**Comment by vnpy** [comment]
已修复
