### ISSUE TITLE
对于trader下的engine中的 get_contract 为何一直被调用？是否有办法瘦身字典数据

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2952]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.2.0

三选一：Enhancement/Question

群主，您好

请教个问题，

对于 def get_contract(self, vt_symbol: str) -> Optional[ContractData]:
为何一直被持续不断的调用？
我把字典 self.contracts  的 key 和 data 打印了出来，发现基本上都是CTP的，我看了下数据，里边是不存在价格的，但是有size，是因为有size才一直更新吗？
那么对于我用不到那么多标的，可能都用不到10个ctp的标的，对于这个self.contracts如此大并且还一直被调用，是不是非常影响性能？
请教：
1、为何一直在被调用？是因为tick变动了就被调用吗？
2、是否有办法对self.contracts 进行瘦身？  就是只要我订阅的合约的，不要这些全市场的？

谢谢！

**Comment by raycool** [comment]
self.contracts 是个字典，对他调用取值是哈希的，时间复杂度O(1)
对性能没影响。

**Comment by vnpy** [comment]
楼上正解
