### ISSUE TITLE
spread_trading 策略逻辑错误

### ISSUE THREAD

**Issue by realChenHui** [vnpy/vnpy#2954]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.9
* vn.py版本: 如v2.1.8

## Issue类型
[三选一：Bug]

basic_spread_strategy.py文件on_spread_data函数，位置如下：(https://github.com/vnpy/vnpy/blob/6dcaf9249e9cee4f4049c8f0f97e91bf9e2eb112/vnpy/app/spread_trading/strategies/basic_spread_strategy.py#L92)

self.spread_pos = self.get_spread_pos()

// No position
if not self.spread_pos:
    self.stop_close_algos()

## 预期程序行为
spread自动开仓后，待交易信号出现，自动平仓成功。

## 实际程序行为
spread自动开仓后，待交易信号出现，先平主动腿后，此时进入该函数，self.spread_pos为0，即spread头寸为0，触发stop_close_algos，将会关闭整个平仓算法algo，导致被动腿无法平仓。

是否可将self.stop_close_algos这行去掉？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
可以，这个只是一个策略开发的模板DEMO，请具体根据自己的交易场景进行修改。
