### ISSUE TITLE
bitfinex 历史行情 OHLC 对应错误

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2955]
## 环境

* 操作系统: 如Windows 10
* Python版本: VNStudio-2.0.6
* vn.py版本: 最新版本

## Issue类型
三选一：Bug

## 实际程序行为

四价在数据库中存错了

![bitfinex 错误](https://user-images.githubusercontent.com/34559558/115000662-8914da80-9ed5-11eb-83fc-14d05941c6ea.jpg)

![屏幕截图 2021-04-16 170535](https://user-images.githubusercontent.com/34559558/115001207-0dfff400-9ed6-11eb-8eea-ecbd3dc554df.jpg)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
