### ISSUE TITLE
portfolio回测搞了个多进程加载数据   可否采纳

### ISSUE THREAD

**Issue by wyx-tree** [vnpy/vnpy#2956]
`

    def load_data(self) -> None:
        self.output("开始加载历史数据")

        if not self.end:
            self.end = datetime.now()

        if self.start >= self.end:
            self.output("起始日期必须小于结束日期")
            return

        # Clear previously loaded history data
        self.history_data.clear()
        self.dts.clear()

        param = [vt_symbol for vt_symbol in self.vt_symbols]

        p = multiprocessing.Pool(multiprocessing.cpu_count())

        result = p.map(self.generate_bar, param)  # result是一个由所有进程生成的字典的列表
        p.close()
        p.join()
        self.history_data = self.list_dict(result)  # 调用将列表中字典转成字典的函数
        self.dts = result[0][1]  # self.dts要有
        self.output("所有历史数据加载完成")

    @staticmethod
    def list_dict(list_data):
        dict_data = {}
        for i in list_data:
            dict_data.update(i[0])
        return dict_data

    def generate_bar(self, vt_symbol):
        dts: Set[datetime] = set()
        history_data = {}
        progress_delta = timedelta(days=30)
        total_delta = self.end - self.start
        interval_delta = INTERVAL_DELTA_MAP[self.interval]

        start = self.start
        end = self.start + progress_delta
        progress = 0

        data_count = 0
        while start < self.end:
            end = min(end, self.end)  # Make sure end time stays within set range
            if self.is_parted_mongo:
                data = load_bar_data(
                    vt_symbol,
                    self.interval,
                    start,
                    end,
                    collection_name=vt_symbol.split('.')[0].upper(),
                )
            else:
                data = load_bar_data(
                    vt_symbol,
                    self.interval,
                    start,
                    end,
                )
            for bar in data:
                dts.add(bar.datetime)
                history_data[(bar.datetime, vt_symbol)] = bar
                data_count += 1
            progress += progress_delta / total_delta
            progress = min(progress, 1)
            progress_bar = "#" * int(progress * 10)
            self.output(f"{vt_symbol}加载进度：{progress_bar} [{progress:.0%}]")

            start = end + interval_delta
            end += (progress_delta + interval_delta)
        self.output(f"{vt_symbol}历史数据加载完成，数据量：{data_count}")
        return history_data, dts
`
思路是用多进程map函数多进程执行  generate_bar 函数，generate_bar是源码中提取出来的

**Comment by vnpy** [comment]
感谢分享，大多数情况下加载数据的性能瓶颈在于数据库的IO，而非Python层的处理。

采用多进程在部分情况下（MySQL之类的数据库）能提高一定程度的速度，但是会造成系统的普适性降低，因此不考虑合并到主分支了。

推荐有需要的用户在自己的扩展代码里进行修改吧。
