### ISSUE TITLE
K线图实现多个标的折线叠加显示

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2959]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.2.0

## Issue类型
三选一：Question

## 实际程序行为

群主，您好

请教下，对于K线，要实现折线图并且几个标的的数据在一个图上显示其相关性，
1、在现有的chart模块上是否可以实现？
debug了chart 2遍，还是比较蒙圈的。 是否可以指导下大概修改的技术点在哪里？ 

2、《30天掌握Python数据分析》中“绘图可视化”是否有这部分技术的讲解并实现的范例？

3、目前您了解的是否有可实现这部分的例子可供参考？恳请推荐下能够完整这部分功能的范例，恳请推荐下能够完成这部分功能的视频学习资料，谢谢！

想要实现效果图如下：

![111](https://user-images.githubusercontent.com/31505150/115649627-42523500-a35a-11eb-8b64-9d6bf0f373ad.png)

恳请百忙中指导下，非常感谢！

**Comment by stone3536** [comment]
这个，是自己犯了愚蠢的错误的，早在2020年2月份“K线图表和Excel RTD”的社区课程中，就已经讲解到的line的实现方式了，当时路上听的这部分内容，1年多过去了，竟然没印象当时群主已经做过范例的了，现在弄这块，最开始竟然是想着要看下当时这个课程的K线图的实现方式，却一直拖着没看，竟然直接硬啃代码，犯了错误的了。

问题找出来了竟然才回头看视频的，唉！

磨刀不误砍柴工的，工欲善其事必先利其器，竟然犯了这么低级的错误，唉！

**Comment by vnpy** [comment]
所以确实我们还是推荐多看看已有的分享内容了，直接用pyqtgraph的line绘制就行。
