### ISSUE TITLE
行情录制模块设置每天自动重启运行会由于无效数据无法记录日盘数据

### ISSUE THREAD

**Issue by jdsfia123** [vnpy/vnpy#2961]
## 环境

* 操作系统: win7
* Python版本: python3.7
* vn.py版本: vnpy2.2.0

## Issue类型
三选一：Bug

## 预期程序行为
每天8：45vnpy重启，等待开盘后记录行情

## 实际程序行为
开盘后，行情没有记录

## 重现步骤
![image](https://user-images.githubusercontent.com/83171519/115996319-60958a80-a611-11eb-94fd-72aa1d7a6af1.png)
rutu如图中记录所示，在开盘前交易所会推送一些乱数据，其时间戳为19点，导致trader/utility.py中第211行代码return，无法记录。等到夜盘开始，重启程序，交易所不推送无效数据，记录恢复。
![image](https://user-images.githubusercontent.com/83171519/115996419-c97d0280-a611-11eb-9efb-563bb7f776ff.png)

**Comment by noranhe** [comment]
因为每个市场的交易时段不同，不好做标准化处理。建议在对应app的engine.py里的process_tick_event函数下收到tick之后，自己写一个判断，看tick的时间是否处于交易时间段，不是的话直接return，就不用走到下一步了
