### ISSUE TITLE
mongo数据库报错in _raise_connection_failure_raise_connection_failure(self.address, error)

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2962]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

## 实际程序行为

群主，您好
mongodb数据库报错，错误信息如下：

\site-packages\pymongo\collection.py", line 947, in replace_one collation=collation, hint=hint, session=session),

\site-packages\pymongo\collection.py", line 870, in _update_retryable _update, session)

\site-packages\pymongo\mongo_client.py", line 1498, in _retryable_write return self._retry_with_session(retryable, func, s, None)

\site-packages\pymongo\mongo_client.py", line 1384, in _retry_with_session return self._retry_internal(retryable, func, session, bulk)

\site-packages\pymongo\mongo_client.py", line 1416, in _retry_internal return func(session, sock_info, retryable)

\site-packages\pymongo\collection.py", line 866, in _update retryable_write=retryable_write)

\site-packages\pymongo\collection.py", line 836, in _update retryable_write=retryable_write).copy()

\site-packages\pymongo\pool.py", line 699, in command self._raise_connection_failure(error)

\site-packages\pymongo\pool.py", line 891, in _raise_connection_failure_raise_connection_failure(self.address, error)

\site-packages\pymongo\pool.py", line 271, in _raise_connection_failure msg = '%s:%d: %s' % (host, port, error)

\encodings\utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 12: invalid continuation byte

----------------------

是正常使用过程中，一直在正常处理的时候（正常开平仓、1分钟前还正常，突然报错的。）出错的，请问这种错误的原因大概是啥原因导致的？恳请百忙中指导下，谢谢！

版本是 3.4.9，查了下网上的报错信息都是低版本才会报这种功能错误的。

**Comment by noranhe** [comment]
实盘的时候一般只会在load_bar、下载数据和录制行情的时候才用到数据库。请问报错时正在用数据库做什么操作呢？
看报错像是编码错误，应该是处理的数据编码格式不是utf8导致的，请问是否是用数据库保存了中文信息？

**Comment by stone3536** [comment]
是保存订单的唯一id，防止id重复的。
没有保存中文信息的，只是英文字符和数字，就2个字段的。
orderUUID 和对应的数字

一直都用的好好的，只是突然报错的了。并且是都正在开平仓的，然后某一个订单成交后保存这个orderUUID的时候就报错了。
重启程序，立刻又交易，都正常的。


报错信息上显示的是数据库连接丢失的：
\site-packages\pymongo\pool.py", line 699, in command self._raise_connection_failure(error)

\site-packages\pymongo\pool.py", line 891, in _raise_connection_failure_raise_connection_failure(self.address, error)

**Comment by vnpy** [comment]
这个不是vn.py的问题，请自行排查pymongo调用的代码吧
