### ISSUE TITLE
建议：加载/重载交易策略时，排除掉 “.ipynb_checkpoints” 文件夹

### ISSUE THREAD

**Issue by dehim** [vnpy/vnpy#2967]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.9
* vn.py版本: 如v2.2.0

## Issue类型
三选一：Enhancement

## 预期程序行为
用jupypterLab打开策略文件后，不管是否编辑，都会在当前目录产生隐藏文件夹“.ipynb_checkpoints”，并在里面产生相同文件名的文件，导到vnpy回测界面加载/重载策略时报错。

## 实际程序行为
报错信息：ModuleNotFoundError:No module named '...-checkpoint'

## 临时解决办法
rm -Rf .ipynb_checkpoints

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/9805228/116495830-4e983e00-a8d6-11eb-9b01-2d69339ee2c6.png)

**Comment by vnpy** [comment]
已改为使用glob模块扫描策略文件夹，只会加载当前文件夹层级的策略文件。
