### ISSUE TITLE
candle_picture的id、地址 和 painter的id、地址重复问题咨询

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2968]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.2.0

## Issue类型
三选一：Question

## 重现步骤

群主，您好

请教个问题，

        candle_picture = QtGui.QPicture()
        painter = QtGui.QPainter(candle_picture)

一、
创建后，因为bar是很多个，但是后续发现竟然有candle_picture的id、地址和前边的对象的painter的id、地址一模一样的呢，我数据导出来在excel进行了分析的，在excel中用了排序和排重发现并且用vlookup公式查找确定有这种情况的，

二、
另外就是后边创建的candle_picture、painter与前边创建过的有重复的，数据都是第一次创建的。我是创建完了查询list是否存在，最后才把这个数据写入list的，确定不会重复。

请教下，在创建多个bar的时候，两个对象地址创建完，什么情况会导致id和地址一样？（确定没有重用对象情况的，而且是2个不同的对象的，仔细检查过多遍了）最奇怪的是两个不同的对象的呢。

恳请百忙中指导下，非常感谢！

二的数据截图如下：（只截图前2页的）
![1](https://user-images.githubusercontent.com/31505150/116508621-523abd80-a8f4-11eb-8061-41ec9e9d510f.png)

![2](https://user-images.githubusercontent.com/31505150/116508631-57980800-a8f4-11eb-91cb-b2cdd35ecf39.png)

代码位置抛出信息如下：
![555](https://user-images.githubusercontent.com/31505150/116509273-98dce780-a8f5-11eb-88b6-f3c85209f7d7.png)

**Comment by vnpy** [comment]
1. id获取的只是Python对象内存身份编号
2. 上述代码中，candle_picture和candle都是每次在_draw_bar_picture函数下创建的对象，函数执行后即销毁，没有任何缓存
3. 因此在多次_draw_bar_picture函数的调用过程中，出现id重复是很正常的现象
