### ISSUE TITLE
请教：chart画折线时有时无法正确显示是否跟标的的bar属性有关

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2973]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.2.0

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

**群主，您好**

将chart修改为画折线图时，在CandleItem中的_draw_bar_picture中画完K线后继续画折线，此时出现ag2112.SHFE、cu2107.SHFE完全可以正确画出，但是价差类的就无法正确画出，外盘标的无法画出，XAUUSD-USD-CMDTY.SMART又有的不正确，将bar的open_price、close_price都print出来，数据都完全正确的，奇怪的是为啥会跟标的有关，另外有的标的有时正确有时又不正确，

请问这种是跟标的的bar的属性有关吗？是受到了bar的属性影响吗？（感觉又不可能跟bar的属性有关的，但是实际结果又想不通、解释不通。）

我将不正确的图形的价格，画折线 前强制修改成指定价格，图形又都可以画出的。

恳请您百忙中指导下此种情况可能得原因，万分感谢！

**具体截图如下：**

## 一、	
Item下CandleItem的_draw_bar_picture代码逻辑逻辑截图（保留bar的画图，这样方便知道是否错误了）：

![图片](https://user-images.githubusercontent.com/31505150/116639902-25da7c00-a99c-11eb-8c0e-045eb5bde521.png)

## 二、
1、白银 ag2112.SHFE 折线图显示（正确）

![图片](https://user-images.githubusercontent.com/31505150/116639926-31c63e00-a99c-11eb-9e5b-79e572e15fdd.png)

2、铜，也是正确的

![图片](https://user-images.githubusercontent.com/31505150/116639940-3a1e7900-a99c-11eb-92b7-4a3f061b273b.png)

## 三、
1、价差数据无法正确画出折线图

![图片](https://user-images.githubusercontent.com/31505150/116639952-430f4a80-a99c-11eb-970b-b449ea2edc76.png)

2、将上图 ob_XAU/XAG_100/d.LOCAL 的价格，直接修改下，就画出了对应的数据
（使用代码图中的 “ pre_price, cur_price = 67, 68 # 测试，指定价格确定是否可以画出 ”的部分强制改下值）

![图片](https://user-images.githubusercontent.com/31505150/116639959-4a365880-a99c-11eb-92f3-d8ab201062a5.png)

3、再次将上图中的价格黄色线价格分别 + 2、 – 2进行处理，结果如图

![图片](https://user-images.githubusercontent.com/31505150/116639996-5b7f6500-a99c-11eb-9a44-96c5967e10ea.png)

4、实际上bar上的open_price、close_price 数据赋值都正确的，打印出来的数据如下：

![图片](https://user-images.githubusercontent.com/31505150/116640007-63d7a000-a99c-11eb-93e7-ba43cbfdbf15.png)

## 四、
1、外盘标的XAUUSD-USD-CMDTY.SMART 有的正确、有的不正确

![图片](https://user-images.githubusercontent.com/31505150/116640020-6cc87180-a99c-11eb-8bce-c8eeab7ad94f.png)

**Comment by stone3536** [comment]
发现贴的图不够清晰，特意把word文档链接也发出来：
链接：https://pan.baidu.com/s/1FJ4VQoSlrSz_n1Sz2bANyQ 
提取码：4qxq

**Comment by stone3536** [comment]
目前确定不是我文件中写的原因的了。
我通过 BarData 把数据库查询出来的转换后，仍旧显示不出来折线，那么就不是属性等导致的。

我又把所有代码都过了一遍，发现差异是我用的是
painter.drawLine(pre_ix, pre_price, ix, cur_price)
虽然是符合条件的，刚换成
        painter.drawLine(
            QtCore.QPointF(pre_ix, pre_price),
            QtCore.QPointF(ix, cur_price)
        )      
就完全没有任何错误的了，目前还不知道为啥导致这样的问题，但是问题点定位到了。


请问 群主 及 了解这块的高手们是否知道这两个的差别？ 怎么会导致折线画出来错乱成这个样子？

（前边被折磨的死的心都有的了，叨扰群主和各位了！）

感恩，谢谢！

**Comment by vnpy** [comment]
尽管根据官方文档：https://www.riverbankcomputing.com/static/Docs/PyQt4/qpainter.html

drawLine支持多种不同的函数重载，但实际上PyQt类库中许多存在重载的函数，最安全的还是传入PyQt对象（比如这里的QPointF）作为参数的那个，其他的可能出现各种问题，算是个经验吧。
