### ISSUE TITLE
编译Bug - 2.3.0 release version 在 Linux 下编译错误

### ISSUE THREAD

**Issue by fxt0706** [vnpy/vnpy#2978]
## 环境

* 操作系统: Debian 10.8、Ubuntu 18.04
* Python版本: 3.7.0
* vn.py版本: 2.3.0 release 版
## Issue类型
Bug
## 预期程序行为
安装过程中，按教程执行 install.sh 后正常通过编译。

## 实际程序行为
编译过程中报错（已精简）：
```
gcc: error: vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp: No such file or directory
gcc: error: vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.cpp: No such file or directory
```

## 重现步骤
bash ./install.sh

## 临时解决方案
删除或注释掉 setup.py 中 vnctptd vnctpmd 相关的代码，即可正常通过编译。

**Comment by fudingyu** [comment]
给个详细一点的吧

  building 'vnpy.api.ctp.vnctptd' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/vnpy
  creating build/temp.linux-x86_64-3.7/vnpy/api
  creating build/temp.linux-x86_64-3.7/vnpy/api/ctp
  creating build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp
  creating build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd
  gcc -pthread -B /root/anaconda3/envs/python3.7.1_evn/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ivnpy/api/ctp/include -Ivnpy/api/ctp/vnctp -I/root/anaconda3/envs/python3.7.1_evn/include/python3.7m -c vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/ctp/vnctp/vnctptd/vnctptd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
  gcc: error: vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp: No such file or directory
  error: command 'gcc' failed with exit status 1

**Comment by dehim** [comment]
看到楼上说报错，然后 git clone master分支最新代码，手动安装一次，能顺利安装。
![image](https://user-images.githubusercontent.com/9805228/116994500-5f4c1800-ad0b-11eb-8f52-c91a81de36cd.png)

**Comment by vnpy** [comment]
请使用2.3.0的最新Release代码安装即可

**Comment by huabuxiang** [comment]
在全新的系统上，下载最新的2.3.0 在Ubuntu 1804上编译会出现楼主这样的问题

下载的安装包应该有问题

gcc: error: vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp: No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by ruoshui1314** [comment]
确实是这样，2.2.0是正确的。 2.3.0编译有问题。
