### ISSUE TITLE
关于目录名

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#298]
最新版的精简了目录，感觉不错。
就是还有点重复。
主目录已经是vnpy了，下面就没必要 vn.api, vn.trader了吧。直接 api,  trader 就行了啊。

**Comment by vnpy** [comment]
这一步准备在vn.py全面打包支持pip安装的时候来做，后续是计划把整个vn.py提供安装到Python的库中的，暂时还有很多用户只是直接使用某个文件夹，所以得留着前缀。

**Comment by vnpy** [comment]
已经在dev中开始精简
