### ISSUE TITLE
OKEX v5 永续合约无法下单了

### ISSUE THREAD

**Issue by grantchen** [vnpy/vnpy#2981]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.0
* vn.py版本: 2.3.0

## Issue类型
Bug

## 预期程序行为
下单成功

## 实际程序行为

升级到最新的 2.3.0，委托下单购买永续合约的时候，报下面的错，你们代码里面是不是没有写入这个参数

`委托失败，状态码：51000，信息：Parameter posSide  error`

## 重现步骤

合约正常下多/空单，即可发现。

**Comment by vnpy** [comment]
由于统一账户的规则变动，OKEX的V5接口只能支持以下模式：

1. 只支持单币种保证金模式
2. 只支持全仓模式
3. 只支持单向持仓模式

**Comment by luhongkai** [comment]
我也遇到这个问题，所以代码里要怎么写才能成功下单？正常写self.buy 也不行呢

**Comment by junyanwu** [comment]
1. 在`vnpy.trader.constant`中，修改常量：
```python
class Direction(Enum):
    """
    Direction of order/trade/position.
    """
    LONG = "long"
    SHORT = "short"
    NET = "净"
```

2. 在`okex_gateway.py`的`send_order`中，`arg`改为如下：
```python
args: dict = {
            "instId": req.symbol,
            "clOrdId": orderid,
            "side": DIRECTION_VT2OKEX[req.direction],
            "posSide": req.direction.value,
            "ordType": ORDERTYPE_VT2OKEX[req.type],
            "px": str(req.price),
            "sz": str(req.volume)
        }
```

即可合约双向下单

**Comment by zhuanqizhirou** [comment]
> 1. 在`vnpy.trader.constant`中，修改常量：
> 
> ```python
> class Direction(Enum):
>     """
>     Direction of order/trade/position.
>     """
>     LONG = "long"
>     SHORT = "short"
>     NET = "net"
> ```
> 
> 2. 在`okex_gateway.py`的`send_order`中，`arg`改为如下：
> 
> ```python
> args: dict = {
>             "instId": req.symbol,
>             "clOrdId": orderid,
>             "side": DIRECTION_VT2OKEX[req.direction],
>             "posSide": req.direction.value,
>             "ordType": ORDERTYPE_VT2OKEX[req.type],
>             "px": str(req.price),
>             "sz": str(req.volume)
>         }
> ```
> 
> 即可合约双向下单

但无法正常平仓

**Comment by junyanwu** [comment]
你的邮件已收到，我会尽快回复~
