### ISSUE TITLE
CTA 回测tick数据， 参数优化目标结果都为0

### ISSUE THREAD

**Issue by gh-wtw-p3470528** [vnpy/vnpy#2985]
## 环境

* VN Station2.2版本
* win10系统

## Issue类型
Bug

## 预期程序行为
VN Station中CTA回测Tick数据，点击参数优化获取目标结果

## 实际程序行为
VN Station中CTA回测Tick数据，点击参数优化获取的目标结果都为0

## 重现步骤
1. 启动VN Station程序，导入以太坊历史Tick数据
2. 在CTA回测界面中选择k线周期为tick，如下图：
![`M5 VM08{)0G6{DKBOBE$1R](https://user-images.githubusercontent.com/19661602/117570269-f47c5180-b0fb-11eb-8309-93e590abaa0c.png)

3. 点击参数优化，随意指定参数，获取的目标结果都为0

## 原因
路径：vnpy/app/cta_backtester/engine.py文件中run_optimization函数中代码块：
`
        if interval == Interval.TICK:
            mode = BacktestingMode.TICK
`
应该改为：
`        if interval == Interval.TICK.value:
            mode = BacktestingMode.TICK`

**Comment by vnpy** [comment]
数据库中的已有数据量太短，不足以完成策略的初始化，导致整个回测没有发生过交易，因此所有统计指标也都是0了。

**Comment by gh-wtw-p3470528** [comment]
不是数据量太短的原因吧，况且载入的时间可以缩短到一天。
`CTA`回测界面上，点击开始回测是能获取到统计指标结果的，而参数优化获取的指标都为0，后面我按照上线的方法改了这块代码:
` if interval == Interval.TICK.value: mode = BacktestingMode.TICK`
然后，参数优化就能获取到统计指标了。
`tick` 数据：在本地` mongodb `数据库中载入了10天的以太坊 `tick `数据，没有载入任何k线数据。

**Comment by gh-wtw-p3470528** [comment]
> 数据库中的现有数据量太短，不足以完成策略的初始化，导致整个回测没有发生过交易，因此所有统计指标也都是0了。

不是数据量太短的原因吧，况且载入的时间可以缩短到一天。
CTA回测界面上，点击开始回测是能获取到统计指标结果的，而参数优化获取的指标都为0，后面我按照上线的方法改了这块代码：
if interval == Interval.TICK.value: mode = BacktestingMode.TICK
然后，参数优化即可获取到统计指标了。
tick数据：在本地mongodb数据库中加载了10天的以太坊tick 数据，没有加载任何k线数据。

**Comment by vnpy** [comment]
好的，我们这边来排查下

**Comment by vnpy** [comment]
已在vnpy_ctabacktester项目中修复，2.4.0会发布替换目前的模块，非常感谢
