### ISSUE TITLE
网络问题，币安交易所每间隔一小时断开长链接导致

### ISSUE THREAD

**Issue by EvenZheng129** [vnpy/vnpy#2989]
## 环境

* 操作系统: Windows Server 2019 Datacenter
* Python版本: 如VNStudio-2.0.6
* vn.py版本: v2.3.0发行版（下载日期）20210510

## Issue类型
三选一：Bug

## 预期程序行为
正常运行没有报错误

## 实际程序行为
不断报错误，有界面的程序卡崩了

## 重现步骤

可能是币安交易所每间隔一小时断开长链接导致的
![微信图片_1](https://user-images.githubusercontent.com/84166720/118219697-990be400-b4ac-11eb-982c-ccfa88c517cb.png)
![微信图片_2](https://user-images.githubusercontent.com/84166720/118219702-9b6e3e00-b4ac-11eb-9014-9d95f727ce4d.png)

**Comment by vnpy** [comment]
已修复
