### ISSUE TITLE
基于1.6版本后的开发思路

### ISSUE THREAD

**Issue by desont** [vnpy/vnpy#299]
当前的版本从gateway到策略，灵活度较低，对于多账户、多市场、多策略暂时没有提供直接的支持。对此个人对后继版本的一些想法如下。

1、设置基类，把主要的类如vtgateway，vtengine，server，client等类转移到专门的vn.lib目录，为上次应用提供支持

2、解耦，对基类的功能进行解耦，把参数读取，数据处理，风险控制等通过参数形式传送，尽量不要在基类中直接创建。例如，vtengine中，写入mongodb的操作，应该可以剥离出去。如各种gateway里面，直接写死了读取配置文件，也可以独立出来。实现界面与服务不共用进程，服务可以自启动，通过界面可以进行干预及启停等操作。

3、标准化，把某些未标准化的内容做标准化，现在发现的主要是数据库相关的内容，例如insert，query时候，怎么兼容mysql和mongodb的操作。这个需要整体再理一次。

4、用户账户的配置，考虑写入到py文件中，编译后使用，在云端使用时候，或者在一些保密性不强的服务器上，可以稍微放心一些。

5、统一参数配置目录，如server、gateway、策略参数统一目录。

6、在完成解耦和标准化基础上，增加配置管理功能。通过一些预先定义的模板，快速进行配置。

6、增加日志目录和记录日志功能，可以考虑增加日志引擎，并且对普通日志以及错误日志进行区分。

7、基于rpc与日志功能，增加监控模块。对gateway、数据流、关键策略指标进行监控。这里不确定是否适用rpc功能。

’

**Comment by vnpy** [comment]
这些建议都挺有价值，短时间内没法快速做完，但是会作为长期方向。

先记录一下，后续有具体计划了来更新。

**Comment by akeyong** [comment]
非常棒的建议！

**Comment by vnpy** [comment]
参考以上建议，已经初步完成v1.6.2的重构
