### ISSUE TITLE
链接 okex 时，输入了key和  secretkey后链接出现 check hostname requires server hostname 错误

### ISSUE THREAD

**Issue by Sober-Chen** [vnpy/vnpy#2990]
## 环境

* 操作系统: 如Windows 10（使用了 vpn 的国内个人电脑）
* Python版本: 如VNStudio-2.3

## Issue类型
Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by TristanXi** [comment]
代理问题.
huobipro = ccxt.huobipro({
    'proxies': {
        'http': 'http://127.0.0.1:port',  # no auth
        'https': 'https://127.0.0.1:port',  # with auth
    },
})

试试这样写

**Comment by Sober-Chen** [comment]
> 代理问题.
> huobipro = ccxt.huobipro({
> 'proxies': {
> 'http': 'http://127.0.0.1:port', # no auth
> 'https': 'https://127.0.0.1:port', # with auth
> },
> })
> 
> 试试这样写

这个不是火币的么，okex 的该改哪个文件
![image](https://user-images.githubusercontent.com/47527606/118224052-f60b9800-b4b4-11eb-8dff-d05f25dfa7cb.png)

**Comment by Sober-Chen** [comment]
在海外服务器就可以正常运行了，但国内的运行方法暂时不太清楚
