### ISSUE TITLE
华鑫TORASTOCK GATEWAY 的send_order(..) 没有返回orderid

### ISSUE THREAD

**Issue by kolamanlee** [vnpy/vnpy#2991]
## 环境

* 操作系统: 无关
* Python版本: 无关
* vn.py版本: 无关

## Issue类型
Bug

## 预期程序行为
应该返回orderid,否则在vt_orderid = self.main_engine.send_order(
                req, contract.gateway_name)以及后续CTA/SPREAD中均无法正常工作

## 实际程序行为
vt_orderid为空None

## 重现步骤

通过algo产生一个algo 订单，即可重现

**Comment by vnpy** [comment]
已修复

**Comment by kolamanlee** [comment]
没有看到有对应的代码呀。但是我已经更改好，如果需要，我可以发给你们。
