### ISSUE TITLE
单合约回测与多合约回测结果不一致

### ISSUE THREAD

**Issue by dionysos137** [vnpy/vnpy#2992]
## 环境

* 操作系统: 如Windows 7
* Python版本: 如VNStudio-2.5.6
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 预期程序行为
一样的策略（比如简单的双均线），一个用cta strategy写一个用portforlio strategy。让两者都跑同样的一个合约，起始时间也相同。所得的回测统计结果应该都一致

## 实际程序行为
1. daily_df相比错位一天
2. 多合约回测的total trade days比单合约的多出了load_bars(n)要用的前n天。这样虽然绝对收益等结果不变，但是所有用到总交易天数的指标都不同。

## 重现步骤
单合约回测没有问题：
![单合约](https://user-images.githubusercontent.com/49093201/118452951-412de100-b729-11eb-9549-52e4f7fc070a.PNG)

多合约：
![多合约](https://user-images.githubusercontent.com/49093201/118452967-44c16800-b729-11eb-98fa-5c39ef61aeb8.PNG)

##可能的解决办法
1. 多合约的run_backtesting() 里面 day_count = 0； 单合约里面day_count = 1. 比如前者该为1可解决前面提到的错位问题。
2. 排查发现是因为多合约里面在处理前n天的时候call self.new_bars(), 里面会更新daily results. 但是单合约里面call 的是策略的on_bar()所以没有这个问题。最简单的方法是在update_daily_close()前面加上对self.strategy.inited的判断条件。

两个修改之后目前所有统计结果指标都一致。

**Comment by dionysos137** [comment]
还发现了一个不一致。return_drawdown_ratio的定义方式不同。

**Comment by vnpy** [comment]
已修复
