### ISSUE TITLE
东航期货仿真测试环境获取不到合约信息数据

### ISSUE THREAD

**Issue by nhfmaster** [vnpy/vnpy#2997]
## 环境

* 操作系统: windows7
* Python版本: 代码中的run_ui.py
* vn.py版本: v2.2.0
* ctp api版本为6.5.1

## Issue类型
三选一：Question

## 预期程序行为
可以获取到合约信息并且订阅

## 实际程序行为
可以查询到合约信息，可是无法订阅到合约tick数据

## 重现步骤
![image](https://user-images.githubusercontent.com/12438251/118910503-23de5a00-b957-11eb-8e5e-57c8b04aa5b3.png)

**Comment by noranhe** [comment]
是否有on_tick行情推送取决于测试环境了，【已撤销】状态可能是因为下单价格不匹配测试环境盘口价格导致的。穿透式测试具体做到什么程度，建议还是与期货公司沟通一下。

**Comment by nhfmaster** [comment]
好的，多谢
