### ISSUE TITLE
币安交易所市价交易时出错

### ISSUE THREAD

**Issue by ppt331** [vnpy/vnpy#3003]
## 环境

* 操作系统: Windows server 2019
* Python版本: VNStudio-2.5.6
* vn.py版本: 2.5.6

## Issue类型
Bug

## 预期程序行为
连接币安交易所用市价成交，能返回成功消息

## 实际程序行为
服务器返回   委托失败，状态码：400，信息：{"code":-1106,"msg":"Parameter 'timeInForce' sent when not required."}

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
连接币安交易所，调用市价成交可以重现。限价成交正常。
![image](https://user-images.githubusercontent.com/29396464/119341582-8a040d80-bcc6-11eb-89a6-95bfb07b79df.png)

**Comment by Albert19981008** [comment]
我遇到了一样的问题

**Comment by ricardo88t4** [comment]
binance_gateway的下单请求功能需要修改下，针对市价单，不需要传递timeInForce参数，需要传递quoteOrderQty和quantity参数，具体可以看binance官方api文档修改

**Comment by vnpy** [comment]
已修复，非常感谢
