### ISSUE TITLE
Bug: IB_gateway重连之后不会自动订阅数据

### ISSUE THREAD

**Issue by rian-dev** [vnpy/vnpy#3006]
## 环境

* 操作系统: Windows Server 2019
* vn.py版本: VNStudio-2.1.8 - ib gateway升级版

## Issue类型
Bug

## 预期程序行为
* 每天自动重连ib_gateway 且会自动订阅数据, 策略继续正常运行

## 实际程序行为
* 每天自动重连ib_gateway 但不会会自动订阅数据, 策略的数据卡在重连之前,

## 重现步骤
1. 在ib_gateway每日例行自动重启后, 新版本ib_gateway会自动重连.
2. 此时ib_gateway会显示API Client是正常连接的. 同时Market Data Farm是断开的.

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="970" alt="WechatIMG39251" src="https://user-images.githubusercontent.com/66057562/119611975-ecc3e900-be2d-11eb-8f4e-e3cf0086e5dc.png">

**Comment by noranhe** [comment]
请升级至最新版本

**Comment by vnpy** [comment]
根据TWS API的[官方文档](https://interactivebrokers.github.io/tws-api/message_codes.html)

> 2103 A market data farm is disconnected.
> Indicates a connectivity problem to an IB server. Outside of the nightly IB server reset, this typically indicates an underlying ISP connectivity issue.

这个红色状态disconnected的Market Data Farm应该是你的交易机器到IB服务器之间的网络连接问题，或者就是在晚间（美国）IB服务器重置期间发生的，无法在vn.py层解决了。

**Comment by vnpy** [comment]
https://www.interactivebrokers.com/en/index.php?f=en/software/systemStatus.php

这个网页可以看到关于IB服务器重置的时间段信息

**Comment by rjl02468** [comment]
老师你好，我也在使用ib_gateway跟vnpy，方便加个好友吗？用盈透的人少，难得
