### ISSUE TITLE
脚步策略，增加成交回调事件插槽，方便处理逻辑

### ISSUE THREAD

**Issue by wangzhilongh** [vnpy/vnpy#3007]
## 环境

操作系统: Windows 10，ubuntu 18
Python版本:  3.7
vn.py版本: 2.3.0

## Issue类型
Enhancement

## 预期程序行为
希望在脚本策略中，增加类似on_order，on_trade等成交有关的回调，方便逻辑处理，谢谢。

## 实际程序行为
脚步策略中，暂时没有相关api。

**Comment by wangzhilongh** [comment]
如果轮询的话，频繁调用（例如1秒1次）get_orders、get_trades，会有接口调用频率的限制吗（比如，交易所会有调用限制吗）？

**Comment by vnpy** [comment]
1. 脚本策略定位于同步轮询的程序设计，因此不会提供回调函数接口（事件驱动用）
2. get_orders/get_trades函数都只是在访问vn.py本地内存中的数据，背后的数据来源于交易接口推送，因此没有查询频率的问题
