### ISSUE TITLE
使用CTA策略AtrRsiStrategy策略导致卡死问题

### ISSUE THREAD

**Issue by warriorBrian** [vnpy/vnpy#3009]
## 环境

* 操作系统: windows 10
* Python版本: VN Station 2.5.6
* Trader版本：VN Trader 2.3.0

## Issue类型
Bug

## 预期程序行为
连接OKEX，使用AtrRsiStrategy策略，启动策略，在脚本自动计算后进行大量买入后程序卡死。

## 实际程序行为
VN Trader 程序卡死，策略模块卡死

## 重现步骤

使用策略，进行买入卖出程序过大概一个小时程序会卡死，无法进行任何操作。

**Comment by vnpy** [comment]
请提供卡死的状态截图？

**Comment by warriorBrian** [comment]
@vnpy 

![image](https://user-images.githubusercontent.com/28696399/119918496-2d8d4080-bf9b-11eb-9439-2d6daec62483.png)


程序无响应，卡死。

**Comment by warriorBrian** [comment]
@vnpy 左下角日志信息，他将不断的买入，但是余额是不够的，然后进行报错。

过一段时间，则程序卡死。无响应。

**Comment by vnpy** [comment]
这是因为频繁出错后，交易所断开网络连接导致的问题，请在策略中增加对最小交易数量的限制即可。
