### ISSUE TITLE
关于vnpy无法下载盈透连续合约的咨询

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3014]
@陈晓优 ，已升级到2. 3版本。但是在vnpy数据管理或者CTA回测里面下载连续合约还是报错：请检查交易所后缀，XINA50-USD-CONTFUT. SGX这么写无法下载
![image](https://user-images.githubusercontent.com/60735134/120157290-735d3980-c225-11eb-87a3-69b59746c349.jpeg)
![image](https://user-images.githubusercontent.com/60735134/120157306-79531a80-c225-11eb-9996-c90458930bad.jpeg)
![image](https://user-images.githubusercontent.com/60735134/120157318-7e17ce80-c225-11eb-8cef-556091f64655.jpeg)

**Comment by vnpy** [comment]
已修复，之前缺失了SGX交易所

**Comment by rjl02468** [comment]
@陈晓优 ，已升级到2. 4版本。但是在vnpy数据管理或者CTA回测里面下载连续合约还是报错：数据下载失败，无法获取XINA50-USD-CONTFUT. SGX的历史数据，我已开通SGX交易所的XINA50权限，实盘是可以正常运行的，就是无法下载历史数据，您方便帮忙看看是怎么回事儿吗？
![image](https://user-images.githubusercontent.com/60735134/123018637-8072e000-d401-11eb-983c-f4932caa9536.jpeg)
![image](https://user-images.githubusercontent.com/60735134/123018669-8d8fcf00-d401-11eb-8bc8-4eedf81a4b4e.jpeg)
![image](https://user-images.githubusercontent.com/60735134/123018701-997b9100-d401-11eb-9504-55e879194d10.jpeg)

**Comment by noranhe** [comment]
请问你的日志界面有输出对应的日志信息吗？
