### ISSUE TITLE
AlgoTrading 模块下单时为何不用 convert_order_request ？

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#3019]
这部分：

https://github.com/vnpy/vnpy/blob/81ab73dc57d12a3ff7c74c73665513b46fc0f668/vnpy/app/algo_trading/engine.py#L215-L225

为何不用 convert_order_request 把 order_request 进行转换处理？

**Comment by Gwill** [comment]
@vnpy

**Comment by vnpy** [comment]
这里因为AlgoTrading面向的市场和场景比起CTA策略更加广泛，因此许多情景下是不需要做开平自动转换的。对于有这方面需求的情景（主要是国内期货）可以自行扩展下
