### ISSUE TITLE
Okex接口断开重连出现错误

### ISSUE THREAD

**Issue by sunmichace** [vnpy/vnpy#3022]
## 环境

* 操作系统: Windows 10
* Python版本: python3.7
* vn.py版本: v2.3.0

## Issue类型
三选一：Question

## 预期程序行为
针对Okex接口，设计了断开重连的代码，调用self.gateway.close()，之后调用self.gateway.connect()。预期gateway能继续连接上交易所数据。

## 实际程序行为
调用过程中，报错出现在self.gateway.connect()中，在调用OkexRestApi.connect中的self.start(session_number)报错。在启用start_event_loop()中报错。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图，流程：

self.gateway.close()（完成不报错）-->self.gateway.connect(报错)-->OkexRestApi.connect-->错误出现在start_event_loop

![image](https://user-images.githubusercontent.com/30697733/120964887-998b5800-c796-11eb-93a4-8c83348740c3.png)
报错信息：There is no current event loop in thread 'Thread-6'

**Comment by sunmichace** [comment]
再次声明使用库：
vnpy：2.3.0版本
okex：vnpy_okex（最新，来自作者github库）
rest：vnpy_rest（最新，来自作者github库）
websocket：vnpy_websocket（最新，来自作者github库）

**Comment by vnpy** [comment]
收到，我们来排查下

**Comment by vnpy** [comment]
已在vnpy_rest/vnpy_websocket项目中修改，将会在2.4.0发布中修复。

**Comment by sunmichace** [comment]
谢谢，爱你呦
