### ISSUE TITLE
gateio的api接口无法使用

### ISSUE THREAD

**Issue by wwwlyw** [vnpy/vnpy#3023]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
gateio的api接口因为官方api的修改导致程序接口不能使用，需要修改

## 实际程序行为
gateio的api接口因为官方api的修改导致程序接口不能使用，需要修改
官方在2019-11-07修改了api接口，原有的
修改内容如下：
以 /futures 为前缀的所有接口前缀统一调整为 /futures/{settle} ，以支持基于多种结算货币的合约操作。
/futures/{settle}/accounts 返回的账户信息里 currency 增加 USDT 的返回
/futures/{setttle}/tickers 返回的交易量信息新增 volume_24h_base, volume_24h_quote 和 volume_24h_settle 字段，取代原有 volume_24h_btc 和 volume_24h_usd 的使用。 后两个字段为了兼容依然保留，但是新的操作不推荐继续使用。
将 /futures 替换成 /futures/usdt 就可以使用 USDT 结算的合约操作, 例如 GET /futures/usdt/accounts 能够获取 USDT 的合约账户，而 GET /futures/btc/accounts 则是用来获取 BTC 的合约账户。

为了保持兼容, 原有的 GET /futures/xxx 的 API 都会默认为 BTC GET /futures/btc/xxx 。如 GET /futures/accounts 会被服务默认按 GET /futures/btc/accounts 请求来处理

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
暂时没有更新计划了，gateio接口的用户太少，后面3.0应该会移除掉它。
