### ISSUE TITLE
vnpy不能连接bybit

### ISSUE THREAD

**Issue by xkyykx** [vnpy/vnpy#3024]
## 环境

* 操作系统: Windows 7
* Python版本: VNStudio-2.5.6

## Issue类型
三选一：Question

在使用vnpy连接bybit时，触发异常，状态码：<class 'ValueError'>，信息：check_hostname requires server_hostname.
请问这个怎么解决？谢谢大家。

![1](https://user-images.githubusercontent.com/61793499/121457466-4d305a00-c9da-11eb-8666-ff8543cb2e09.png)
![2](https://user-images.githubusercontent.com/61793499/121457476-502b4a80-c9da-11eb-828f-fec611db15b5.png)

**Comment by xkyykx** [comment]
`Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>python -m vnstation
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_sess
ion_callback
qt.network.monitor: Could not get the INetworkConnection instance for the adapte
r GUID.
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_sess
ion_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_sess
ion_callback
qt.network.monitor: Could not get the INetworkConnection instance for the adapte
r GUID.
qt.network.monitor: Could not get the INetworkConnection instance for the adapte
r GUID.
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_sess
ion_callback
qt.network.monitor: Could not get the INetworkConnection instance for the adapte
r GUID.
[2021-06-10T14:14:54.381656]: Unhandled RestClient Error:<class 'ValueError'>
request:request : GET /v2/public/symbols error because terminated:
headers: {'Referer': 'vn.py'}
params: {'api_key': 'WkPwFs8Q0JfGtavf4k', 'recv_window': 30000, 'timestamp': 162
3305689290, 'sign': '3cf21f609015231da300cfaabe642d61a341796651ee8a37f568a84cf2c
b4871'}
data: None
response:

Exception trace:
Traceback (most recent call last):
  File "D:\vnstudio\lib\site-packages\vnpy\api\rest\rest_client.py", line 262, i
n _process_request
    proxies=self.proxies,
  File "D:\vnstudio\lib\site-packages\requests\sessions.py", line 542, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "D:\vnstudio\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\vnstudio\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\vnstudio\lib\site-packages\urllib3\connectionpool.py", line 696, in u
rlopen
    self._prepare_proxy(conn)
  File "D:\vnstudio\lib\site-packages\urllib3\connectionpool.py", line 964, in _
prepare_proxy
    conn.connect()
  File "D:\vnstudio\lib\site-packages\urllib3\connection.py", line 359, in conne
ct
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\vnstudio\lib\site-packages\urllib3\connection.py", line 506, in _conn
ect_tls_proxy
    ssl_context=ssl_context,
  File "D:\vnstudio\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wr
ap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\vnstudio\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_w
rap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\vnstudio\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "D:\vnstudio\lib\ssl.py", line 810, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`

**Comment by xkyykx** [comment]
![1](https://user-images.githubusercontent.com/61793499/121474806-31877c80-c9f7-11eb-9a1b-04c64a71f7a0.png)

**Comment by MonkeyOliver** [comment]
根据[这个issue](https://github.com/urllib3/urllib3/issues/2075)来看应该是新urllib3换了个schema，看是把vnstudio里的urllib3版本降掉还是改[这块代码](https://github.com/vnpy/vnpy/blob/81ab73dc57d12a3ff7c74c73665513b46fc0f668/vnpy/api/rest/rest_client.py#L118)吧
```Python
if proxy_host and proxy_port:
    proxy = f"http://{proxy_host}:{proxy_port}"
    self.proxies = {"http": proxy, "https": proxy}
```

**Comment by MonkeyOliver** [comment]
贴一下D:\vnstudio\lib\site-packages\vnpy\api\rest\rest_client.py这个文件的这几行

    def init(
        self,
        url_base: str,
        proxy_host: str = "",
        proxy_port: int = 0
    ) -> None:
        """
        Init rest client with url_base which is the API root address.
        e.g. "https://www.bitmex.com/api/v1/"
        """
        self.url_base = url_base


        if proxy_host and proxy_port:
            proxy = f"http://{proxy_host}:{proxy_port}"
            self.proxies = {"http": proxy, "https": proxy}

**Comment by xkyykx** [comment]
`    def init(
        self,
        url_base: str,
        proxy_host: str = "",
        proxy_port: int = 0
    ) -> None:
        """
        Init rest client with url_base which is the API root address.
        e.g. "https://www.bitmex.com/api/v1/"
        """
        self.url_base = url_base

        if proxy_host and proxy_port:
            proxy = f"http://{proxy_host}:{proxy_port}"
            self.proxies = {"http": proxy, "https": proxy}
`

**Comment by xkyykx** [comment]
`
    def init(
        self,
        url_base: str,
        proxy_host: str = "",
        proxy_port: int = 0
    ) -> None:
        """
        Init rest client with url_base which is the API root address.
        e.g. "https://www.bitmex.com/api/v1/"
        """
        self.url_base = url_base

        if proxy_host and proxy_port:
            proxy = f"http://{proxy_host}:{proxy_port}"
            self.proxies = {"http": proxy, "https": proxy}

`

**Comment by xkyykx** [comment]
def init(
    self,
    url_base: str,
    proxy_host: str = "",
    proxy_port: int = 0
) -> None:
    """
    Init rest client with url_base which is the API root address.
    e.g. "https://www.bitmex.com/api/v1/"
    """
    self.url_base = url_base


    if proxy_host and proxy_port:
        proxy = f"http://{proxy_host}:{proxy_port}"
        self.proxies = {"http": proxy, "https": proxy}

**Comment by MonkeyOliver** [comment]
> ```
>     def init(
>     self,
>     url_base: str,
>     proxy_host: str = "",
>     proxy_port: int = 0
> ) -> None:
>     """
>     Init rest client with url_base which is the API root address.
>     e.g. "https://www.bitmex.com/api/v1/"
>     """
>     self.url_base = url_base
> 
>     if proxy_host and proxy_port:
>         proxy = f"http://{proxy_host}:{proxy_port}"
>         self.proxies = {"http": proxy, "https": proxy}
> ```
> 
> 一样的呀

这块儿没问题的话看一下requests和urllib3这俩库的版本，都升到最新试试（尤其是requests的版本）

**Comment by xkyykx** [comment]
我使用的是&nbsp;VN Station这个我就不会升级&nbsp;requests和urllib3 能指导下吗？老师，发个连接也行。
&nbsp;

请订阅（更多资源）：http://www.zjclw.net/get &nbsp; &nbsp; &nbsp;


&nbsp;

**Comment by MonkeyOliver** [comment]
> 我使用的是&nbsp;VN Station这个我就不会升级&nbsp;requests和urllib3 能指导下吗？老师，发个连接也行。 &nbsp; 请订阅（更多资源）：http://www.zjclw.net/get &nbsp; &nbsp; &nbsp; &nbsp;

我只是路过看到你这个issue感觉像是和[这个issue](https://github.com/urllib3/urllib3/issues/2075)有关，这个报错一般就是requests库和urllib3库版本不匹配造成的，但问题是我也不太清楚VN Station是怎么装的这俩库，实在不行等其他大佬来解答吧

**Comment by MonkeyOliver** [comment]
你看一下能不能在`D:\vnstudio\lib\site-packages\urllib3`和`D:\vnstudio\lib\site-packages\requests`这两个地方找到version有关信息，requests那个文件夹里应该直接就有一个`__version__.py`，urllib3的`__init__.py`里应该有个`__version__`字段

**Comment by vnpy** [comment]
这个报错通常因为使用了全局代理，vn.py底层使用的requests库只能用指定地址和端口的代理模式。
