### ISSUE TITLE
火币合约接口，无法订阅 O3-USDT 永续合约

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3026]
## 环境

* 操作系统: 如Windows 10 
* Python版本: python 3.7
* vn.py版本: 2.1.9版本以上

## Issue类型
三选一：Bug

## 预期程序行为
火币合约接口，无法订阅 O3-USDT 永续合约。

## 实际程序行为
永续不能订阅是因为subscribe函数处理过的合约名变O-USDT了

## 重现步骤
具体详情见： 
https://www.vnpy.com/forum/topic/6971-huo-bi-apixin-shang-shi-de-bi-wu-fa-ding-yue-xing-qing-yi-ji-yong-xu-he-yue-jin-zhi-chi-zhu-cang-de-pin-chong-wu-fa-ding-yue?page=1#pid25315

**Comment by vnpy** [comment]
已修复

**Comment by AITrading2020** [comment]
> 已修复

依旧报错，报错如下：

![O3-USDT HUOBI 下单依旧报错](https://user-images.githubusercontent.com/53517184/123823375-b64b2380-d92f-11eb-8ec1-052b4d14a404.png)

**Comment by AITrading2020** [comment]
> 已修复

下单是正常流程的，并且没有调整过杠杆，下单别的合约都没问题的，怀疑还是O3-USDT下单有bug

**Comment by AITrading2020** [comment]
@vnpy 应该是没问题了，上面报错是因为代码里面设置的代码倍数被调整的了原因，之前默认的是 "lever_rate": 5。
现在改为了 "lever_rate": 20， 如果已有持仓的话再下单会报错。  我建议还是改为之前默认的 "lever_rate": 5，以免不熟悉火币接口的朋友不知道怎么调整这个默认的杠杆倍数
