### ISSUE TITLE
BarData结构缺少成交金额，部分策略开发需要用到

### ISSUE THREAD

**Issue by rpyproject** [vnpy/vnpy#3029]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.6发行版

## Issue类型
三选一：Enhancement
建议在BarData结构中增加成交金额，可以做细致的策略开发，例如计算K线周期内的平均成交价，日内分时图中黄线的构造等；由于是基础结构，个人修改后担心影响之后版本升级，还望在的基础数据结构中可以增加。

**Comment by vnpy** [comment]
2.5.0已添加turnover字段
