### ISSUE TITLE
BUG：vnpy_xtp已分离到requirements.txt，但setup.py没有同步分离。

### ISSUE THREAD

**Issue by dehim** [vnpy/vnpy#3030]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.9
* vn.py版本: v2.4.0

## Issue类型
三选一：Bug

## 预期程序行为
安装时报错

## 实际程序行为
![image](https://user-images.githubusercontent.com/9805228/122835821-a924a800-d323-11eb-92e7-699a0326c0db.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

看到vnpy_xtp已分离到requirements.txt，但setup.py没有同步分离。
![image](https://user-images.githubusercontent.com/9805228/122835985-f143ca80-d323-11eb-8ba4-51d7acd194e0.png)

**Comment by vnpy** [comment]
收到，我们来处理下

**Comment by dehim** [comment]
@vnpy 麻烦尽快修复，合并代码吧，便于自动化编排docker

**Comment by vnpy** [comment]
已经DEV分支完成处理
