### ISSUE TITLE
异常处理的一些情况

### ISSUE THREAD

**Issue by KimChow** [vnpy/vnpy#3037]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

INFO  [2021-06-25 04:28:22,855][gateway.py:193] 触发异常，状态码：<class 'concurrent.futures._base.TimeoutError'>，信息 ：
在使用aiohttp的时候，有出现了这样的报错，从这些信息上面无法定位得到是在哪里报错的。导致想加一些机制让他更稳健的时候，不知道从哪里下手好。可以提供一下解决这类问题的思路吗？我也不确定是基于rest报错，还是基于websocket出错的。

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请问具体是使用哪个gateway触发的异常？
