### ISSUE TITLE
2.4.0版本在ubuntu系统编译失败（不支持vnxtptd、vnxtpmd编译）

### ISSUE THREAD

**Issue by buque** [vnpy/vnpy#3040]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: python 3.8.5
* vn.py版本: 2.4.0

## Issue类型
三选一：Bug

## 实际程序行为
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ivnpy/api/xtp/include -Ivnpy/api/xtp/vnxtp -I/usr/include/python3.8 -c vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp -o build/temp.linux-x86_64-3.8/vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
x86_64-linux-gnu-gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 

## 重现步骤
1、执行vnpy安装
python3 setup.py build

2、程序报错
x86_64-linux-gnu-gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 

3、注释vnxtptd, vnxtpmd库
303         ext_modules = [
304             #vnxtptd, vnxtpmd,          <-----此处注释
305             vnsgittd, vnsgitmd,
306             vnksgoldmd, vnksgoldtd,
307             vnnhmd, vnnhfutures, vnnhstock,
308             vnrohontd, vnrohonmd,
309         ]

4、编译成功

针对Bug类型Issue，请提供具体重现步骤以及报错截图
303         ext_modules = [
304             #vnxtptd, vnxtpmd,          <-----此处注释
305             vnsgittd, vnsgitmd,
306             vnksgoldmd, vnksgoldtd,
307             vnnhmd, vnnhfutures, vnnhstock,
308             vnrohontd, vnrohonmd,
309         ]

**Comment by vnpy** [comment]
已在DEV分支修复
