### ISSUE TITLE
v2.4.0 centos系统下，初始化策略失败：创建策略失败，找不到策略类XXX

### ISSUE THREAD

**Issue by glysoft** [vnpy/vnpy#3041]
## 环境

* 操作系统: centos 7.6
* Python版本: python3.7.10
* vn.py版本: release v2.4.0 20210627

## Issue类型
Bug

## 预期程序行为
策略文件放在/root/strategies（或项目的策略目录）下可以正常加载

## 实际程序行为
创建策略失败，找不到策略类

## 重现步骤
![image](https://user-images.githubusercontent.com/81026711/123536559-919f5200-d75d-11eb-8722-082d5c721a75.png)
修改vnpy_ctastrategy/engine.py中load_strategy_class_from_folder()方法内的文件路径符为/后正常，应该是没有兼容操作系统所致
![image](https://user-images.githubusercontent.com/81026711/123536603-e773fa00-d75d-11eb-8541-e53fe29dd9a6.png)
![image](https://user-images.githubusercontent.com/81026711/123536631-23a75a80-d75e-11eb-875a-a578a46b4427.png)

**Comment by mixbe** [comment]
👍🏻  mac系统下，也是需要修改的

**Comment by xuxin3101** [comment]
这个问题是因为mac和windows的路径分隔符不一致
下面这样修改可以
`https://github.com/vnpy/vnpy_ctabacktester/pull/2/commits/a0c1a1b92bb937d51592b449f7b70a949522d0e7`

**Comment by noranhe** [comment]
vnpy/cta_strategy PR 1 已修复
https://github.com/vnpy/vnpy_ctastrategy/pull/1
