### ISSUE TITLE
BarGenerator中的last_bar字段没有用到

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3042]
## 环境

* 操作系统: Windows 10
* vn.py版本: v2.4.0发行版

## Issue类型
Enhancement

## 实际程序行为
![1](https://user-images.githubusercontent.com/63988546/123575433-4f7d1b80-d804-11eb-9640-f7a7db9fdc3f.png)

![2](https://user-images.githubusercontent.com/63988546/123582924-43e42180-d811-11eb-91ff-8f7ec90bc088.png)

**Comment by vnpy** [comment]
已处理
