### ISSUE TITLE
2.4.0的cta_strategy希望能增加一些灵活配置

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#3043]
2.4.0的cta_strategy抽离之后，strategies这个文件夹由原来的vnpy文件夹换到了python内部文件夹。
现在stategy的策略代码来源只有两个路径：
1.  python的安装目录下
2. 当前运行的启动文件的strategies下（尚有bug无法正常加载）
1文件夹是以前代码管理能覆盖的文件夹，而现在已经不能覆盖到了。
2文件夹一般是测试或者运营时的文件，不纳入代码管理范畴。
这个改动导致了代码管理的困难，所以能不能增加一个策略集中存放，方便代码管理的文件夹，或者直接在配置文件中指定一个存放策略的文件夹？

**Comment by noranhe** [comment]
vnpy_ctastrategy加载示例策略的问题已经修复。
https://github.com/vnpy/vnpy_ctastrategy/pull/1
cta_strategy模块一共会去两个文件夹下加载策略，分别是vnpy_ctastrategy.strategies和启动目录下的strategies文件夹。如下图所示：
![af649886731d515db9604de950d282f](https://user-images.githubusercontent.com/63988546/128821466-45db25a4-f764-4ca9-ae3f-2078f94f0ce9.png)
1： vnpy_strategy.strategis文件夹是存放示例策略的文件夹，有被更新覆盖的风险；
2： 官方推荐使用用户启动目录下的自建的strategies文件夹来存放所有自建策略。
