### ISSUE TITLE
binances_gateway 中tick 时间戳未添加时区

### ISSUE THREAD

**Issue by milkpuff** [vnpy/vnpy#3045]
## 环境

* 操作系统: Windows 10
* Python版本: 如VNStudio
* vn.py版本: 如v2.4

## Issue类型
Bug

binances_gateway.py 中tick 时间戳未进行时区转换

`def on_packet()` 中 

`tick.datetime = datetime.fromtimestamp(float(data['E']) / 1000)`

应改为

`tick.datetime = generate_datetime(float(data['E']))`

**Comment by noranhe** [comment]
vnpy_binance已修复
