### ISSUE TITLE
币安gateway下单科学计数法问题，币安不支持科学计数法字符串

### ISSUE THREAD

**Issue by milkpuff** [vnpy/vnpy#3050]
## 环境

* 操作系统: Windows 10
* Python版本: 如VNStudio
* vn.py版本: v2.4.0

## Issue类型
三选一：Bug

## 预期程序行为

如：下单数量0.00003时，会被转换为字符串“3e-05”，币安不支持科学计数法的字符串，报错

"委托失败，状态码：400，信息：{""code"":-1100,""msg"":""Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'.""}",BINANCE

问题位置：
binance_gateway 中， `def send_order()` 内，
`           "price": str(req.price),
            "quantity": str(req.volume),`

python 中，str(0.00003) 会返回字符串 ’3e-05’，此处可用 Decimal 转换。

**Comment by noranhe** [comment]
vnpy_bianance PR 4 已修复
