### ISSUE TITLE
严重Bug：币安永续合约 best limit order 下单时，存在大量无法撤单的情况，导致实际成交量远远超过用户指定的下单量

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3052]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如python 3.7
* vn.py版本: 如v2.4.0

## Issue类型
三选一：Bug

## 重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图

使用算法交易下单时，无法正常撤单，并且非常快速的持续挂单，UI界面显示是提交中，其实已经源源不断的把订单持续发到交易所了。
![Uploading 大量提交中的订单.png…]()
十几秒之内就发出去了几十个订单，并且都陆续成交了，导致下单量比用户指定的大很多。

![Uploading 算法交易报错.png…]()

**Comment by AITrading2020** [comment]
![微信图片_20210706092501](https://user-images.githubusercontent.com/53517184/124528959-1401d300-de3c-11eb-8ff8-16e98dcae7e5.png)

**Comment by AITrading2020** [comment]
算法交易下单完成后，不自动停止:
![算法交易下单完成后，不自动停止](https://user-images.githubusercontent.com/53517184/124575542-11c06880-de7e-11eb-9636-2a513db1872b.png)
发出了很多特别小的委托单，但是活跃订单里面并没有显示，也没有拒单:
![发出了很多特别小的委托单，但是活跃订单里面并没有显示，也没有拒单](https://user-images.githubusercontent.com/53517184/124575571-18e77680-de7e-11eb-8588-480a472041bf.png)

**Comment by AITrading2020** [comment]
大量提交中的订单:
![大量提交中的订单](https://user-images.githubusercontent.com/53517184/124602242-3d058080-de9b-11eb-9074-38d8676e4705.png)

上一个订单未完成时，便连续发单：
![连续发单](https://user-images.githubusercontent.com/53517184/124602309-4b539c80-de9b-11eb-8287-ef30bba2ea73.png)

上一个订单未完成时，便连续发单2：
![连续发单2](https://user-images.githubusercontent.com/53517184/124602328-50185080-de9b-11eb-979c-f2e3f364f58f.png)

**Comment by vnpy** [comment]
收到，我们来排查下

**Comment by vnpy** [comment]
2.5.0升级了币安底层接口，目前使用：

1. 香港阿里云服务器
2. 币安仿真测试账号

无法重现上述问题，请在2.5.0发布后升级下试试。
