### ISSUE TITLE
币安现货接口未能及时更新USDT等资金余额

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3053]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如python3.7
* vn.py版本:2.4.0

## Issue类型
三选一：Bug

## 重现步骤
先登录币安现货接口，然后将现货的USDT划转入永续合约，结果UI界面上，币安现货的USDT依旧不变（这个显示是不对的），永续合约的USDT确实显示增加了。

**Comment by noranhe** [comment]
建议可以去币安接口的on_packet函数下打印，看是否收到了outboundAccountPosition事件推送。如果收到了，接口是有处理的，代码如下图所示：
![a496d7e2c4cbb02667ffb7c14c90321](https://user-images.githubusercontent.com/63988546/128798643-f38ee2ad-37da-4eb0-bffa-23e3f227da8a.png)
