### ISSUE TITLE
策略引擎的持仓不能只用一个pos来存，期货存在双向交易，没办法同时记录多头仓位和空头仓位

### ISSUE THREAD

**Issue by glysoft** [vnpy/vnpy#3055]
策略引擎的持仓不能只用一个pos来存，期货存在双向交易，没办法同时记录多头仓位和空头仓位，是否可以优化？

**Comment by vnpy** [comment]
对于CTA策略来说，只需要关注自己的逻辑仓位，而无需去跟踪账户底层的持仓（因为还可能有其他策略、以及手动交易持仓），因此单一的pos字段在大部分情况下已经足以。

如果确实有需求，可以自行在策略中增加long_pos、short_pos这样的变量，然后基于on_trade回报计算更新即可，无需在vn.py系统层做修改。
