### ISSUE TITLE
K线图更新时出错：Cannot destroy paint device that is being painted

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3056]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug/Question

## 重现步骤

群主，您好

k线图更新时出错，错误信息如下：

QPaintDevice: Cannot destroy paint device that is being painted
QPaintDevice: Cannot destroy paint device that is being painted
PS D:\00_VNPY_2.x\trader2.x>

恳请百忙中帮看看下这类错误是何原因，谢谢！

**Comment by vnpy** [comment]
这个问题是否在关闭程序时才出现？

**Comment by stone3536** [comment]
群主，您好
这个不是在关闭程序时出现，是正在运行的时候，直接所有程序被强退的了，然后cmd窗口出现这个提示的，其他没有提示信息的了。

**Comment by stone3536** [comment]
尝试在价差窗口打开多个ChartWizardWidget窗口后，在窗口关闭位置最早加了destroy()，应该是这个原因导致窗口destroy时和event事件又还有的时候paint冲突了。

关闭窗口时出现这个错误是上边的原因导致的，但是很多时候没关闭的时候竟然会因为这个错误直接导致程序全部退出的了，这个就想不通是哪里导致的了。因为原始的ChartWizardWidget是close()的方式而不是destroy()的。

先将问题关闭了。

不知道后续 vnpy的 2.5.0版本 是否会做行情记录模块、价差模块、CTA模块、......、K线图时时画图并且同时时时画价差、多个标的内外盘的这种组合测试，感觉为了要这个整个大的系统稳定还是要做下比较复杂的模块组合挂盘测试的，并且隔夜等的挂着。
