### ISSUE TITLE
vnpy新版订阅SI行情报错：you must specify the multiplier or trading class.

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3058]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Question

## 重现步骤

群主，您好

登录tws后，对于si标的订阅的，报错信息如下：
......
ERROR 16 200 The contract description specified for SI is ambiguous;
you must specify the multiplier or trading class.
......
2021-07-07 15:49:04,574  INFO: 信息通知，代码：200，内容: The contract descripti
on specified for SI is ambiguous;
you must specify the multiplier or trading class.
2021-07-07 15:49:08,221  INFO: 合约信息查询成功

TWS 是英文的登录环境，使用新版本的，SI 的合约 "SI-20210928-USD-FUT.NYMEX" 报错，但是使用vnpy1.9.2版本的获取合约 SIU1 都是可以订阅到的，同一个IB的实盘账号的，请问这类是跟 vnpy 或者 ib 的接口有关吗？
恳请百忙中帮忙确认下，谢谢！

论坛及网上搜索了，没有这类的解决方法的。

**Comment by noranhe** [comment]
应该是因为没有传multiplier和trading class导致的。可以根据自己需求自行去接口的generate_ib_contract函数进行修改了

**Comment by stone3536** [comment]
@noranhe 
您好，这个是标的订阅的时候就报的错误的，是否可以考虑在vnpy标准中就增加上？
谢谢！

**Comment by stone3536** [comment]
另外请教下，在data_recorder_setting.json 或者 spread_trading_setting.json 中有标的了，启动程序，并不会自动订阅，即使再次打开，也不会订阅上。在主界面输入代码位置并选择对应的交易所、接口后，敲击回车，第一次都要等待大概30秒到2分钟左右的情况的，就是这个标的第一次用，如果不这样操作，就订阅不过来的，试过大概10几次了。这次过后，就正常了，启动程序，就自动订阅了。
不知道这种情况是何原因。
ib实盘账号，该标的的交易所数据付费并订阅的了。比如 铜。

**Comment by vnpy** [comment]
IB的合约信息不提供全量查询功能，必须用户输入完整的合约代码后主动查询才能获取，因此上述问题目前必须手动先订阅后才能录制行情。
