### ISSUE TITLE
CTP接口夜盘不能连续交易

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#306]
行情接收正常。命令重新connetCTP也不行，需要重启vnpy才能继续交易。难道每天夜盘要手动开启量化交易的大门。。。

**Comment by vnpy** [comment]
可以通过父子进程的方式来实现自动化管理，但是我依旧建议所有的交易启动前都请手动检查。

**Comment by jieyujing** [comment]
Thanks

2017-04-21 9:20 GMT+08:00 vn.py <notifications@github.com>:
