### ISSUE TITLE
关于vnpy2. 4. 0行情实时数据不更新的咨询

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3063]
![image](https://user-images.githubusercontent.com/60735134/124856399-046dc000-dfdd-11eb-841a-08e5aabe86a2.jpeg)
如图所示，17041这个行情是多天前的数据，没有随着行情更新，买一和卖一可以正常刷新更新，之前的版本一直正常刷新，2.4才出现这个错误，应该是个bug

**Comment by noranhe** [comment]
请问之前的版本指的是哪个版本？SGX是2.4.0才支持的。
