### ISSUE TITLE
币安算法交易一直显示订单在提交中，每次卡在提交状态很久才有回报

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3064]
## 环境

* 操作系统: 如Windows 10
* Python版本: python3.7
* vn.py版本: 2.3.0 以上版本

## Issue类型
三选一：Bug

## 实际程序行为
目前最新一版的Binances gateway，我已经上报了问题，并且我退回了前一个版本的币安接口，也发现了一些报单的问题。
币安算法交易一直显示订单在提交中，每次卡在提交状态很久才有回报。
服务器位于新加坡，平时几乎没用遇到报单延迟很高的情况，现在明显每次报单提交中的状态非常久。

## 重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图

币安算法交易保单，一直显示在提交中：
![币安算法交易保单，一直显示在提交中](https://user-images.githubusercontent.com/53517184/124914908-7a951580-e023-11eb-8924-aaf788fad60a.png)

币安算法交易保单，一直显示在提交中 (2)
![币安算法交易保单，一直显示在提交中 (2)](https://user-images.githubusercontent.com/53517184/124914924-7ff26000-e023-11eb-8461-f2e3761dc026.png)

**Comment by AITrading2020** [comment]
应该不是网络的问题，1. tick正常跳动，时间戳完全同步，没用阻塞。
2. 每次发现订单卡在提交中的状态之后，重启算法交易之后，又可以正常进行一段时间的算法交易下单，但等会马上就又会卡住在订单提交中的状态了

**Comment by AITrading2020** [comment]
O3-USDT.HUOBI 在执行best limit order算法交易的时候，也遇到了同样的问题。目前在火币和币安永续合约交易上，算法交易报单都遇到了长时间卡在提交中的问题

**Comment by vnpy** [comment]
1. 行情和交易是两套Websocket连接，因此TICK跳动时，可能交易连接已经断开
2. Websocket连接由于自身机制无法保证数据不丢包，新版本2.5.0已经将币安接口升级为使用基于aiottp的底层客户端，请试试能否解决上述问题
