### ISSUE TITLE
tick 合成 1分钟 k 线未取得实际最低价及最高价

### ISSUE THREAD

**Issue by Vincent-CDeng** [vnpy/vnpy#3066]
## 环境

* 操作系统: MacOx
* vn.py版本: 2.3.0

## Issue类型
三选一：Bug

## 预期程序行为
正常合成

## 实际程序行为
当新的一分钟的第一个 tick的 last_price < high_price ,并且该high_price是一分钟内最大值时,
合成的分钟 bar 的 high_price 将会小于 该一分钟内实际的最大值

当新的一分钟的第一个 tick 的 last_price < low_price ,并且该low_price是一分钟内的最小值时,
合成的分钟 bar 的 low_price 将会大于该一分钟内实际的最小值

 即是:新的一分钟的第一个 tick 的最高价/最低价是该分钟最大/最小值时出现这个 bug
## 重现步骤
       if new_minute:
            self.bar = BarData(
                symbol=tick.symbol,
                exchange=tick.exchange,
                interval=Interval.MINUTE,
                datetime=tick.datetime,
                gateway_name=tick.gateway_name,
                open_price=tick.last_price,
                high_price=tick.last_price,
                low_price=tick.last_price,
                close_price=tick.last_price,
                open_interest=tick.open_interest
            )
        else:
            self.bar.high_price = max(self.bar.high_price, tick.last_price)
            if tick.high_price > self.last_tick.high_price:
                self.bar.high_price = max(self.bar.high_price, tick.high_price)

            self.bar.low_price = min(self.bar.low_price, tick.last_price)
            if tick.low_price < self.last_tick.low_price:
                self.bar.low_price = min(self.bar.low_price, tick.low_price)

            self.bar.close_price = tick.last_price
            self.bar.open_interest = tick.open_interest
            self.bar.datetime = tick.datetime

**Comment by AITrading2020** [comment]
@Vincent-CDeng 你这个是不是tick的时间戳给过滤掉了？ 
https://github.com/vnpy/vnpy/issues/2741
看看这个对你有帮助吗？

**Comment by vnpy** [comment]
以上修改内容对于国内期货的K线合成，从理论上来说没问题。

但实际上存在其他问题：
1. 在Tick之间形成的最高价、最低价，对于CTA常用的本地停止单来说无法成交（因为出现时已经超过了触发价）
2. 对于数字货币等市场，最高价、最低价不是开盘至今的统计值，而是过去24小时滚动窗口的统计值

因此vn.py从通用框架的角度考虑，不对BarGenerator进行相应修改，用户可以根据自己的需求自行继承开发比如FuturesBarGenerator来实现上述功能。
