### ISSUE TITLE
策略variables加载机制导致的信号覆盖问题

### ISSUE THREAD

**Issue by dz8235462** [vnpy/vnpy#3067]
## 环境

* 操作系统: Windows 10
* Python版本: 如VNStudio-2.3
* vn.py版本: master branch 20210615（下载日期）

## Issue类型
Bug

## 预期程序行为
使用vnpy自带DualThrust策略，cta_strategy_data.json文件中存在day_open,long_entry,short_entry等参数。当策略在交易时段内启动时，预期day_open,long_entry,short_entry应为当日开盘价计算的结果

## 实际程序行为
day_open,long_entry,short_entry为文件内储存的旧参数

## 重现步骤
原因：交易时段内启动策略，会导致当日的day_open,long_entry,short_entry是在on_init内load（10）计算的，但json文件会在on_init后覆盖策略参数

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by noranhe** [comment]
程序是这么设计的，预计的是如果没有缓存，就用load_bar10天计算的指标初始化。如果有缓存，默认的是正常连续交易，所以第二天盘前打开读取昨天收盘交易结束时计算的指标数值。如果有盘中内启动策略的需求，可以根据自己需求进行个性化修改了。
