### ISSUE TITLE
多进程优化时内存一直累加的bug

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3069]
原帖链接：
https://www.vnpy.com/forum/topic/7140-ti-jiao-yi-ge-yuan-ke-cheng-dai-ma-zhong-duo-jin-cheng-you-hua-shi-nei-cun-yi-zhi-lei-jia-de-bug?page=1#pid26149

**Comment by noranhe** [comment]
目前发现再次实例化BacktestingEngine类时，仍有history_data内存没有释放

**Comment by vnpy** [comment]
测试后无法重现，在Jupyter运行过程中由于Plotly等相关库的内存对象释放需要时间，因此内存占用会存在上下的范围抖动，但是没有明显增长的情况
