### ISSUE TITLE
BitstampGateway报错

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3072]
版本：2.3.0

用户反映如下：

![24d9f9db884aec232775217d3d78dfa](https://user-images.githubusercontent.com/63988546/126268789-6fedebab-a70c-4741-9026-6438d965f030.png)

建议：

_process_request函数是根据BitstampGateway接口特性修改的，应在接口内修改对应的_run函数以与_process_request达到一致而不是把session加回来。

**Comment by vnpy** [comment]
已修复
