### ISSUE TITLE
TargetPosTemplate 锁仓功能

### ISSUE THREAD

**Issue by AStupidBear** [vnpy/vnpy#3073]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: Python 3.7.7
* vn.py版本: v2.0.5

## Issue类型
Enhancement

## 预期程序行为

希望 `set_target_pos`可以支持锁仓功能， 并且假如日内保证金占用过高，切换到不锁仓模式后，`offset`的判断不应该只看`self.pos`，还要像`convert_order_request_lock`一样看`td_volume`。

**Comment by noranhe** [comment]
请根据自己需求进行个性化修改了
