### ISSUE TITLE
vnstudio 为啥要登录？回测不是离线的吗？除了下载历史数据还有什么需要联网的？

### ISSUE THREAD

**Issue by GF-Huang** [vnpy/vnpy#3077]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 用于获取最新的版本信息，获取自动更新
2. 登录社区论坛，查看最新的论坛帖子

vn.py本身可以直接用脚本启动，并不一定要通过VN Station。
