### ISSUE TITLE
gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory

### ISSUE THREAD

**Issue by finology** [vnpy/vnpy#3079]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: Python3.7
* vn.py版本: 2.4.0

## Issue类型
三选一：Bug

## 预期程序行为

正常安装

## 实际程序行为

gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory
  error: command 'gcc' failed with exit status 1

**Comment by vnpy** [comment]
已在dev分支修复

**Comment by lingchingteng** [comment]
請問有實際的 commit 嗎？
