### ISSUE TITLE
希望增加TCP期权组合策略交易指令的支持，以享受组合策略保证金，非常感谢！

### ISSUE THREAD

**Issue by wangzhilongh** [vnpy/vnpy#3080]
## Issue类型
三选一：Enhancement

## 预期程序行为
希望增加TCP期权组合策略交易指令的支持，以享受组合策略保证金，非常感谢！

**Comment by vnpy** [comment]
组合保证金功能目前很少有策略中自动调用的，更多通过：
1. 图形界面实现，这种情况推荐用快期等软件
2. 资深用户可以直接通过CtpGateway去调用TdApi的底层函数来实现

因此现阶段不考虑增加这块的功能了。
