### ISSUE TITLE
回测时漏掉刚好达到阈值的数据

### ISSUE THREAD

**Issue by Vincent-CDeng** [vnpy/vnpy#3081]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

    def on_init(self):
        """
        Callback when strategy is inited.
        """
        self.write_log("策略初始化")

        self.load_bar(10)

会少回放数据刚好达到10时数据



## 重现步骤

原贴链接
https://www.vnpy.com/forum/topic/7303

**Comment by noranhe** [comment]
vnpy_ctastrategy PR 1 已修复
