### ISSUE TITLE
pip安装的一些列模块都无法使用

### ISSUE THREAD

**Issue by FreAirLy** [vnpy/vnpy#3082]
ImportError: cannot import name 'CtpGateway' from 'vnpy_ctp' (/usr/local/lib/python3.8/site-packages/vnpy_ctp/init.py)
mac系统

**Comment by vnpy** [comment]
1. vnpy_ctp只支持Python 3.7 64位的Windows/Linux
2. CTP官方就不支持Mac

**Comment by FreAirLy** [comment]
from vnpy.gateway.ctp import CtpGateway 
这个模块怎么替换呢

**Comment by FreAirLy** [comment]
> * vnpy_ctp只支持Python 3.7 64位的Windows/Linux
> * CTP官方就不支持Mac

from vnpy.gateway.ctp import CtpGateway
这个模块怎么替换呢

**Comment by vnpy** [comment]
直接在run.py中移除掉这个模块的加载就行
