### ISSUE TITLE
gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory

### ISSUE THREAD

**Issue by gysheng** [vnpy/vnpy#3088]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: python3.7.6
* vn.py版本: 2.4.0

## Issue类型
三选一：Enhancement

## 预期程序行为
在ubuntu18.04上安装vnpy

## 实际程序行为
安装时报错：
gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory

## 重现步骤
conda create -n vnpy python=3.7.6
conda active vnpy
git clone https://gitee.com/vnpy/vnpy.git -b 2.4.0
cd vnpy/
python setup.py install
报错：
gcc -pthread -B /home/gys/soft/anaconda3/envs/vnpy/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ivnpy/api/xtp/include -Ivnpy/api/xtp/vnxtp -I/home/gys/soft/anaconda3/envs/vnpy/include/python3.7m -c vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.o -std=c++17 -O3 -Wno-delete-incomplete -Wno-sign-compare
gcc: error: vnpy/api/xtp/vnxtp/vnxtptd/vnxtptd.cpp: No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by vnpy** [comment]
DEV分支已修复，下个版本将会发布
