### ISSUE TITLE
OES_API连接闪退的问题

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3090]
## 实际程序行为
mdsapi客户端版本和服务端版本不匹配，服务端使用的是0.15.12版本，不支持查询期权行情静态信息，如果发起查询，会被断开连接。0.17.1.3的版本没有问题

原帖链接：
https://www.vnpy.com/forum/topic/7333-oes-apilian-jie-shan-tui-de-wen-ti?page=1#pid26894

**Comment by vnpy** [comment]
需要更新宽睿API到0.17.1.3版本
