### ISSUE TITLE
使用RqdataClient的方法query_history获取历史数据报错

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#3091]
## 环境

* 操作系统: 如Windows 10
* Python版本: Anancoda 3.7
* vn.py版本: 如2.3.0

## Issue类型
三选一：Bug

## 预期程序行为
使用RqdataClient的方法query_history获取历史数据时候

## 实际程序行为
            for ix, row in df.iterrows():
                dt = row.name.to_pydatetime() - adjustment
报错
row.name 是tuple, 是(symbol, 时间）组合，而不是直接时间，没有pydatetime()
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by noranhe** [comment]
请问你是下载什么数据的什么时间段的什么频率的数据导致的报错？我们来复现一下。

**Comment by vnpy** [comment]
请使用2.9.33版本的rqdatac，我们会在后续升级到最新版本
