### ISSUE TITLE
Macbook如何按照vnstudio

### ISSUE THREAD

**Issue by hiyoung123** [vnpy/vnpy#3092]
## 环境

* 操作系统: mac 
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Question

请问 macbook 如何安装vnstudio？

**Comment by vnpy** [comment]
VNStudio目前只有Windows版本，Mac上可以直接命令行安装即可
