### ISSUE TITLE
Mac 可以使用ctp吗？

### ISSUE THREAD

**Issue by hiyoung123** [vnpy/vnpy#3093]
## 环境

macbook

## Issue类型
Question

请问mac 可以使用ctp吗？　我使用命令行安装后，运行 examples/vn_trader/run.py 出现找不到　ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'

**Comment by vnpy** [comment]
无法使用，请从run.py中移除CTP相关加载（以及其他一些国内柜台API的加载）
