### ISSUE TITLE
gate.io api连接只显示REST API连接成功，合约信息，资金，持仓都没有

### ISSUE THREAD

**Issue by ma853529615** [vnpy/vnpy#3094]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7
* vn.py版本: VNStudio-2.2.0

## Issue类型
Question

使用的是gate.io的api v4。币安可以正常连接。

**Comment by vnpy** [comment]
gateio的用户太少，后面准备移除这个接口了

**Comment by ma853529615** [comment]
> gateio的用户太少，后面准备移除这个接口了

所以说是一直不能用的吗，还是用法不一样。。。

**Comment by vnpy** [comment]
之前可以，后来gateio官方升级了API，我们没有更新了
