### ISSUE TITLE
k线图刷新异常停止和dr模块记录bar不再记录数据问题

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3098]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug/Question

## 重现步骤

群主，您好

对于组合的K线图刷新和dr模块、价差模块同时开着时，有如下问题，恳请您根据场景确认下问题所在。（此种情况未做任何交易，仅仅是3台机器都只做数据记录、时时画图，价差模块也只是开着未做交易的任何操作。）详细如下：

K线图时时挂着刷图（价差 [内外盘价差、纯外盘金银比价差，内盘开着的时候都开着，如果有外盘交易时间那么就只开纯外盘金银比价差] 、内盘、外盘标的同时开着）、
dr模块时时录制bar数据（对应开着图的价差及标的）、价差模块，以上模块是同时一直在运行，并且挂盘时间是 北京时间 8:30 到第二天交易时间段，其中ib重新登录时间是下午 3:05 前。

内盘交易时间K线图都开着，内盘不开的时间只开外盘的价差和对应标的K线图刷新；

此种场景，导致如下情况：
1、ib断开（或ctp断开，这个是凌晨2:30后期货公司服务器重新的ctp断开），cmd直接卡死，导致图不再继续画了，此时cmd敲击回车才会出来对应的提示信息；
2、此种情况不再画图，多数情况下导致内盘标的的bar不再记录了，不知道为啥dr模块的记录会和cmd卡死或者说画图卡住有冲突，此种情况碰到大概10几次了，每周大概3~4次（3台机器同时挂着，2台window10、1台云server2016）
99%的实际情况如下：每次大概 23:30 左右ib的farm断开，ib会自动重连farm，此时bar就不再记录数据了（事后查询的），图不再画了的，cmd卡死。

请问对于以上场景，vnpy标准版本 2.3.0 是否进行过类似的开着一直运行的组合测试过？ 特别是刷图的必须开着。我用的是2.3.0版本的。

恳请百忙中对于此种场景进行下这种组合测试确认下卡死的问题所在，是否会在接下来发布的2.5.0版本中进行这种组合测试？ 

谢谢！

**Comment by noranhe** [comment]
如果你是用cmd运行启动图形节目的run.py的话，请直接点击图标启动或者用vscode跑run.py然后复现你的操作看看。
cmd卡死的问题已经在你提出的issue3087中提过了，可能是在cmd执行脚本的时候，如果鼠标点击了cmd任意区域，进入了编辑模式，阻塞了脚本的运行。当之后回车时，则会退出编辑模式，打印出提示信息。

**Comment by stone3536** [comment]
使用shift + 鼠标右键，在run.py的目录下启动Powershell的，然后python run.py执行的，没做过其他操作的。发现卡死是因为感觉出错了，在cmd窗口敲击回车才会打印出来信息的。此时就是ib接口的farm断了或者ctp的连接（收盘）断了的情况。

**Comment by stone3536** [comment]
请教个技术问题，在主窗口关闭的时候，怎么能检查到是否所有的该关闭的都关闭了（就是在主窗口中再次打开了个新的窗口，这个新的窗口也关闭了，比如打开了价差窗口，虽然看到有widget.close() 的，但是想知道是否有其他方法可以检查该关闭的都关闭了呢？ 没关闭的，都会显示看到的？内存中不会有影响的，对吗？）呢？ 虽然__dict__可以列出所有的信息，但是并不知道是否所有该关闭的窗口都关闭了，用什么方法检查并关掉是好的？ 恳请指导下，谢谢！
（不知道我的表述是否清晰了...，因为里边写的有点儿嵌套解释的了。）

**Comment by noranhe** [comment]
> 使用shift + 鼠标右键，在run.py的目录下启动Powershell的，然后python run.py执行的，没做过其他操作的。发现卡死是因为感觉出错了，在cmd窗口敲击回车才会打印出来信息的。此时就是ib接口的farm断了或者ctp的连接（收盘）断了的情况。

请参考上一条建议，用点击图标启动或者用vscode跑run.py然后复现你的操作看看是否断开后会卡死。我们做了测试，只要不在cmd乱点导致进入编辑模式，接口断开是不会阻塞进程的。

**Comment by stone3536** [comment]
@noranhe 
收到，感谢您的指导，谢谢！

我把cmd窗口的编辑模式的勾勾都取消掉了。
后续再看是否会卡死吧。

前边我又请教的 “技术问题”，是对widget理解不够清晰，感觉有没关掉的导致了cmd卡死的，技术上太薄弱了。
