### ISSUE TITLE
RuntimeError:can not open CFlow file in line 256 of file ../../source/userapi/ThostFtdcUserApiImplBase.cpp

### ISSUE THREAD

**Issue by lhzw** [vnpy/vnpy#31]
RuntimeError:can not open CFlow file in line 256 of file ../../source/userapi/ThostFtdcUserApiImplBase.cpp

Linux下运行vn.trader/vtMain.py，点击“连接ctp”，发生如上段错误，感觉很奇怪，后来偶然发现是connect()方法中的路径分隔符造成的，修改成这样即可正常完成连接：
path = os.getcwd() + '/temp/' + self.gatewayName + '/'

库中目前是这样：
path = os.getcwd() + '\\\\temp\\\\' + self.gatewayName + '\\\\'

json配置文件处的容易发现，惭愧的是没有再搜索下其他地方，汗。

经测试，使用'/'在wins下也可正常工作。将来会把代码中的 \\\\ 替换成 / ，以达到更好的跨平台性。

**Comment by OldTogether** [comment]
你好，你的问题解决了没有 ，具体怎么解决？麻烦能帮忙一下么，我qq1325412043

**Comment by vnpy** [comment]
请使用最新的版本吧，这个问题很早就处理掉了

**Comment by OldTogether** [comment]
麻烦问一下，你指的是什么的最新版本

**Comment by TLDay** [comment]
避免后来的人浪费时间：
这个错误是因为调用`CThostFtdcTraderApi.CreateFtdcTraderApi(folder)`时，传入的这个folder不存在导致的，需要先手动创建这个目录。
