### ISSUE TITLE
如何使用策略文件进行模拟盘交易呢？

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#310]
"也可以通过ctaSetting.py进行配置后，在vn.trader中进行模拟交易。", 如何配置呢？文档里说到这就没了, ctaSetting.py是指vn.how/tick2trade/vn.trader_t2t/ctaAlgo/ctaSetting.py吗？我只找到这一个ctaSetting.py ;

**Comment by vnpy** [comment]
啊，不好意思，这个解释的文档比较老了，目前已经无需通过ctaSetting.py来加载策略。

问下你是在哪里看到这个文档的？

**Comment by FallacyWalker** [comment]
在这里看到的：
http://www.vnpy.org/talib-tutorial.html
最新的文档在哪里啊？

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy/wiki
