### ISSUE TITLE
Binance USDT永续合约，下载数据时open_interest没有能正常下载

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3101]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 所有VNPY版本

## Issue类型
三选一：Bug

## 实际程序行为
Binance USDT永续合约，下载数据时 open_interest 没有能正常下载，导致数据库的open_interest都是默认的0值。

**Comment by noranhe** [comment]
![6b4f89df5c4efdbf16eb40cf16afa53](https://user-images.githubusercontent.com/63988546/129292022-aefdd365-ad24-4ad4-8b96-3b378fb689ef.png)
交易所没有提供，无法支持了
