### ISSUE TITLE
K线图画图是否可以对一些刷新、更新做分钟级别的修改

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3106]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3

## Issue类型
三选一：Enhancement

## 重现步骤

群主，您好

对于 class ChartWizardWidget 的结构设计等真的是没得说的，非常棒的，是否会考虑对于这部分做如下修改：

1、对于图形上下限，做10%（可分别上下限设置，可能需要增加参数修改的页签会更方便的）的溢出，这样就会看起来比较舒服些；
2、对于纵轴，是否可以考虑修改成分钟级别或者说bar数量变更级别的更新，因为1溢出了，不需要一直更新y轴的了；

图形画图，感觉有些更新、刷新修改成分钟级别或者说bar数量变更级别会好些的，尤其是开了多个图形一直时时刷的情况下。
（以上是我已经变相实现后感觉这样修改会更好的切实感受。）

谢谢！

**Comment by stone3536** [comment]
对了，感觉左边是百分比，右边是价格比较好些，画图按照百分比画（这个就需要有个初始值了，默认第一个bar），实际显示的时候该显示价格的位置显示价格，该显示百分比的显示百分比比较合适的。

**Comment by vnpy** [comment]
经过考虑，VeighNa项目核心定位保持在量化交易平台开发框架，K线图表等相应图表功能建议使用其他项目实现（如TradingView等）
