### ISSUE TITLE
macOs bigSur install vnpy Something's wrong

### ISSUE THREAD

**Issue by FengFei01** [vnpy/vnpy#3107]
## 环境

* 操作系统: macOs bigSur 11.5.1 (20G80)
* Python版本: python3.6.5
* vn.py版本:  git clone master in 2021.08.13 

## Issue类型
三选一：ModuleNotFoundError: No module named 'vnpy_ctp.api.vnctpmd'

## 重现步骤
I Write run. py  and execute it as described in MD

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
Mac系统不支持CTP接口

**Comment by FengFei01** [comment]
> Mac系统不支持CTP接口
那就是不支持mac 系统安装吗？

**Comment by vnpy** [comment]
可以用其他的数字货币、IB等接口，期货类的接口MAC都无法使用

**Comment by FengFei01** [comment]
感谢

**Comment by FengFei01** [comment]
## 环境

* 操作系统:  MacOs big Sur 11.5.1 (20G80)
* Python版本: 3.10
* vn.py版本: 2.4.0
## Issue类型
三选一：
question
## 预期程序行为
应该要打开程序才对。

## 实际程序行为
%    python3 run.py
qt.qpa.fonts: Populating font family aliases took 1080 ms. Replace uses of missing font family "微软雅黑" with one that exists to avoid this cost. 
启动时，提示上面所述的描述，任务栏已经出现黑马图标，但是没有任何窗口打开，这是什么问题呢？


## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/43366988/129432396-82fc6261-f155-4c34-97b3-b0672bdbc1d9.png)

**Comment by FengFei01** [comment]
可以了，我把PPyQt5==5.14.1 改成了 PyQt5==5.15.4  就好了
