### ISSUE TITLE
ImportError: cannot import name constant

### ISSUE THREAD

**Issue by akeyong** [vnpy/vnpy#311]
D:\vnpy-master\vn.trader\ctaStrategy>python ctaHistoryData.py
Traceback (most recent call last):
  File "ctaHistoryData.py", line 15, in <module>
    from ctaBase import *
  File "D:\workspace\vnpy-master\vn.trader\ctaStrategy\ctaBase.py", line 43, in <module>
    from vtConstant import EMPTY_UNICODE, EMPTY_STRING, EMPTY_FLOAT, EMPTY_INT
  File "..\vtConstant.py", line 3, in <module>
    from language import constant
ImportError: cannot import name constant

**Comment by vnpy** [comment]
这个bug目前比较纠结，因为目录结构修改的关系，根目录下的language目录和CTA模块目录下的language存在冲突，可能要等将vn.trader的完整目录添加到python环境中后才能实现

**Comment by vnpy** [comment]
已修复

**Comment by HunterChan** [comment]
code还没有update?

**Comment by vnpy** [comment]
dev分支已经更新了，使用的时候注意将vnpy文件夹添加到系统环境变量PYTHONPATH下面（没有就新建一个）
