### ISSUE TITLE
v2.5.0 安装后，运行notebook trading 报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#3110]
## 环境

* 操作系统: Windows 10
* Python版本: 如python 3.7 64
* vn.py版本: v2.5.0
* 
## Issue类型
三选一：Bug

## 实际程序行为
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fb5bf9a2a128> in <module>
----> 1 from vnpy.app.script_trader import init_cli_trading
      2 from vnpy.gateway.ctp import CtpGateway
      3 from vnpy.trader.utility import load_json

C:\ProgramData\Miniconda3\envs\vnpy2\lib\site-packages\vnpy\app\script_trader\__init__.py in <module>
      1 from pathlib import Path
      2 from vnpy.trader.app import BaseApp
----> 3 from .engine import ScriptEngine, APP_NAME
      4 from .cli import init_cli_trading
      5 

C:\ProgramData\Miniconda3\envs\vnpy2\lib\site-packages\vnpy\app\script_trader\engine.py in <module>
     12 
     13 from vnpy.event import Event, EventEngine
---> 14 from vnpy.trader.engine import BaseEngine, MainEngine
     15 from vnpy.trader.constant import Direction, Offset, OrderType, Interval
     16 from vnpy.trader.object import (

C:\ProgramData\Miniconda3\envs\vnpy2\lib\site-packages\vnpy\trader\engine.py in <module>
     40     Exchange
     41 )
---> 42 from .setting import SETTINGS
     43 from .utility import get_folder_path, TRADER_DIR
     44 

C:\ProgramData\Miniconda3\envs\vnpy2\lib\site-packages\vnpy\trader\setting.py in <module>
     28     "rqdata.password": "",
     29 
---> 30     "database.timezone": get_localzone().zone,
     31     "database.driver": "sqlite",                # see database.Driver
     32     "database.database": "database.db",         # for sqlite, use this as filepath

AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'zone'

**Comment by vnpy** [comment]
请问是如何安装的？

**Comment by vnpy** [comment]
如果不是用VNStudio，请指定tzlocal版本：

`pip install tzlocal==2.0`

**Comment by yhmickey** [comment]
pip requirements.txt 安装的，安装了tzlocal 3.0版本。
