### ISSUE TITLE
mysql 数据库存无法区分现货和u合约品种交易队（唯一差异就是品种名称大小写）

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#3113]
问题：
    举例  先从币安接口下载现货数 btcusdt 存入到数据库后，在从u 合约下载 BTCUSDT交易队存入数据库，显示保存成功。但实际是把 BTCUSDT 数据替换了 btcusdt 数据（同时间周期内的）先下载合约再下载现货结果是一样，那个先保存就显示那个。正常应该是有两个品种的交易队存入数据库。两个唯一的差异就是品种名称大小写的差异。

2.3 2.4 2.5版都是这样的结果 

## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
区分品种要看symbol和exchange啊，symbol一样就对比exchange

**Comment by yxl560** [comment]
你好：
&nbsp; &nbsp; symbol一样就对比exchange&nbsp; 都是币安交易所，所以这两个字段都是一样的。。唯一的区别就是&nbsp;大小写，现货是小写，u本位合约是大写。目前mysql数据库无法处理这个问题。influxdb-1.8.4_windows_amd64&nbsp;这个数据库是正常的。其他的我没测试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vnpy/vnpy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月19日(星期四) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vnpy/vnpy] mysql 数据库存无法区分现货和u合约品种交易队（唯一差异就是品种名称大小写） (#3113)





 
区分品种要看symbol和exchange啊，symbol一样就对比exchange
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxl560** [comment]
你好：
&nbsp; &nbsp; symbol一样就对比exchange&nbsp; 都是币安交易所，所以这两个字段都是一样的。。唯一的区别就是 大小写，现货是小写，u本位合约是大写。目前mysql数据库无法处理这个问题。influxdb-1.8.4_windows_amd64 这个数据库是正常的。其他的我没测试。


你测试下，先下载现货btcusdt&nbsp;存入数据库，&nbsp;在下载u&nbsp;合约&nbsp;BTCUSDT&nbsp;在存入数据库，你就会发现&nbsp;只有&nbsp;现货的btcusdt，没有BTCUSDT&nbsp;合约的数据，并且 现货的btcusdt&nbsp;被 BTCUSDT&nbsp;合约的数据覆盖了


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "vnpy/vnpy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月19日(星期四) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vnpy/vnpy] mysql 数据库存无法区分现货和u合约品种交易队（唯一差异就是品种名称大小写） (#3113)





 
区分品种要看symbol和exchange啊，symbol一样就对比exchange
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by noranhe** [comment]
MySQL在Windows下都不区分大小写的，如果需要在查询时区分字段值的大小写，则需要将查询字段值需要设置BINARY属性，设置的方法有如下几种方法:
1. 创建时设置：
CREATE TABLE  `tablename` (A VARCHAR(10) BINARY);
2. 使用alter修改：
ALTER TABLE `tablename` MODIFY COLUMN `cloname` VARCHAR(45) BINARY;
