### ISSUE TITLE
可不可以更新一下examples里面的样例？2.5的变动挺大的，里面一些路径已经找不到了

### ISSUE THREAD

**Issue by ad50810344** [vnpy/vnpy#3115]
## 环境

* 操作系统:  Windows 10 
* Python版本: 如VNStudio-2.5
* vn.py版本: 如v2.5

## Issue类型
三选一：Enhancement

可不可以更新一下examples里面的样例？2.5的变动挺大的，里面一些路径已经找不到了

**Comment by vnpy** [comment]
收到，我们下个版本来处理

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy/pull/3144
