### ISSUE TITLE
macOS多线程参数优化报错

### ISSUE THREAD

**Issue by xuxin3101** [vnpy/vnpy#3118]
## 环境

* 操作系统: macOS 11.1
* Python版本: 3.7
* vn.py版本: 2.5

## Issue类型
三选一：Bug

## 预期程序行为
正常参数优化不报错

## 实际程序行为
报错

## 重现步骤

macOS启动多线程参数优化会报错
![image](https://user-images.githubusercontent.com/29241434/130711470-bb260323-e3f0-4b09-b556-826cea990399.png)

**Comment by vnpy** [comment]
已修复
