### ISSUE TITLE
关于自动连接CTP的功能

### ISSUE THREAD

**Issue by akeyong** [vnpy/vnpy#312]
新版本自动连接数据库的功能不错，不过每次重启系统都要再连接一次CTP也不是太方便，建议也加上自动连接CTP的功能。我自己的实现方案如下。 另外，明文保存账户密码感觉不是太安全，未来建议也改进一下。。。（比如CTP_connect.json里面先保持密码空置，第一次连接CTP的时候，系统发现密码为空，就会弹出一个窗口提示输入密码，连接成功后，就会以密文的方式保存到CTP_connect.json里面，以后就不再需要再次手工输入了；如果连接失败，弹出窗口提示重新输入。。。）

in　vtEngine.py:
#----------------------------------------------------------------------
    def initGateway(self):
        """初始化接口对象"""
        # 用来保存接口对象的字典
        self.gatewayDict = OrderedDict()
        
        # 遍历接口字典并自动创建所有的接口对象
        for gatewayModule in GATEWAY_DICT.values():
            try:
                self.addGateway(gatewayModule.gateway, gatewayModule.gatewayName)
                if gatewayModule.gatewayQryEnabled:
                    self.gatewayDict[gatewayModule.gatewayName].setQryEnabled(True)
                if gatewayModule.gatewayAutoConnect:
                    self.connect(gatewayModule.gatewayName)
            except Exception, e:
                print e

in gateway/ctpGateway/__init__.py:
# encoding: UTF-8

import vtConstant
from ctpGateway import CtpGateway as gateway

gatewayName = 'CTP'
gatewayDisplayName = gatewayName
gatewayType = vtConstant.GATEWAYTYPE_FUTURES
gatewayQryEnabled = True
gatewayAutoConnect = True

**Comment by vnpy** [comment]
密码的保存形式确实值得再改进下，很多券商朋友也和我提过明文保存不太合规

**Comment by vnpy** [comment]
考虑到vn.py框架主要应用情景是用户对电脑机器拥有完全控制权的情况下，因此密码的加密保存并非特别必要，自动连接方面的功能会添加到后续的行情自动收集脚本中。
