### ISSUE TITLE
重新安装后的vnpy2.5.0版本，option_master 初始化导入 trading_calendars 报错，原因可能是quantopian不再维护该库，可以替换为exchange_calendars

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3126]
## 环境

* vn.py版本: 如v2.5.0

## Issue类型
三选一：Bug

## 实际程序行为

trading_calendars  导入会报错如下：
TypeError: int() argument must be a string, a bytes-like object or a number, not ‘NaTType‘

## 重现步骤
重新安装 trading_calendars  包即会发现问题，已经安装过的包暂时不会报错。

建议采用 exchange_calendars 库替换，详情请见：

https://github.com/alpacahq/alpaca-backtrader-api/pull/178
https://github.com/gerrymanoim/exchange_calendars

**Comment by vnpy** [comment]
已替换，非常感谢
