### ISSUE TITLE
vnpy2.5.0版本 utility.py 中 update_bar_hour_window 函数遗漏了 新的一根bar的bar.close_price,open_interest 的数据初始赋值

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3127]
## 环境
* vn.py版本: 如v2.5.0

## Issue类型
三选一：Bug

## 重现步骤
vnpy2.5.0版本 utility.py 中 update_bar_hour_window 函数遗漏了 新的一根bar的bar.close_price,open_interest的数据初始赋值，涉及到还在中的两个地方：

1. 刚刚开始的赋值bar：
      # If not inited, create window bar object
        if not self.hour_bar:
            dt = bar.datetime.replace(minute=0, second=0, microsecond=0)
            self.hour_bar = BarData(
                symbol=bar.symbol,
                exchange=bar.exchange,
                datetime=dt,
                gateway_name=bar.gateway_name,
                open_price=bar.open_price,
                high_price=bar.high_price,
                low_price=bar.low_price,
                close_price=bar.close_price,
                volume=bar.volume,
                turnover=bar.turnover,
                open_interest=bar.open_interest
            )
            return

2.      # If minute bar of new hour, then push existing window bar
        elif bar.datetime.hour != self.hour_bar.datetime.hour:
            finished_bar = self.hour_bar

            dt = bar.datetime.replace(minute=0, second=0, microsecond=0)
            self.hour_bar = BarData(
                symbol=bar.symbol,
                exchange=bar.exchange,
                datetime=dt,
                gateway_name=bar.gateway_name,
                open_price=bar.open_price,
                high_price=bar.high_price,
                low_price=bar.low_price,
                close_price=bar.close_price,
                volume=bar.volume,
                turnover=bar.turnover,
                open_interest=bar.open_interest
            )

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy/pull/3140
