### ISSUE TITLE
convert_order_request_shfe需要修改

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3129]
## Issue类型：Enhancement

现在vnpy自带的convert_order_request_shfe，对上期所是平今优先，但是最新螺纹钢、铜这些品种平今都是加倍收取手续费，建议改成平昨优先。

![a02db28e-0401-44bc-8361-2c594c4c539c](https://user-images.githubusercontent.com/63988546/131787458-1e0d1fa6-2681-4e0b-baef-d3ed47c579b0.png)

![2fa896d6f6b9b4934456f4e39830f61](https://user-images.githubusercontent.com/63988546/131787609-5f4ed830-474c-4562-8c62-40cc0b4d0ba6.png)

**Comment by vnpy** [comment]
对于这类品种，请使用锁仓交易模式。
