### ISSUE TITLE
MT5 vnpy_server.mq5编译错误

### ISSUE THREAD

**Issue by linst95** [vnpy/vnpy#3136]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.5
* vn.py版本: VNStudio-2.5

## Issue类型
Bug

## 预期程序行为
MT5编译vnpy_server.mq5，0 error

## 实际程序行为
2 errors, 9 warnings，两条error报错如下：
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	vnpy_server.mq5	256	29
cannot convert 0 to enum 'ENUM_TRADE_REQUEST_ACTIONS'	vnpy_server.mq5	289	31

## 重现步骤
MT5编译vnpy_server.mq5

![image](https://user-images.githubusercontent.com/25526144/132972118-0f039446-507a-4de2-b484-5a70818b1729.png)
![image](https://user-images.githubusercontent.com/25526144/132972135-3110b271-3254-42e3-8f3a-ae14fbd16039.png)

**Comment by noranhe** [comment]
谢谢你的反馈，这个问题会在下次剥离mt5接口的时候修复的

**Comment by linst95** [comment]
> 谢谢你的反馈，这个问题会在下次剥离mt5接口的时候修复的

已经找到了解决方法：因为MT5采用了更严格的语法检查，所以只需要将{0} 改成 {}来初始化就好。

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_mt5/pull/1
