### ISSUE TITLE
M1 silicon support

### ISSUE THREAD

**Issue by axot** [vnpy/vnpy#3137]
## 环境

* 操作系统: macOS Big Sur 11.5.2 arm64
* Python版本: 3.7.11 arm64
* vn.py版本: master branch

## Issue类型
Enhancement

## 预期程序行为
install_osx.sh可以在arm64环境中正常运行

## 实际程序行为
部分dependencies安装的时候发生如下错误
```
ModuleNotFoundError: No module named '_ctypes'
```

## 重现步骤
```
git clone https://github.com/vnpy/vnpy.git
cd vnpy
pyenv install 3.7.11
pyenv virtualenv 3.7.11 vnpy
pyenv local vnpy
./install_osx.sh
```

**Comment by vnpy** [comment]
这个报错是Python本身的问题了，目前没有太好的解决方法，请尝试使用新版本的Python吧。

**Comment by axot** [comment]
There are the instructions as a workaround to run python in x86 mode to avoid this issue.
https://github.com/pyenv/pyenv/issues/1768#issuecomment-871602950

Then compile source code,

```
arch -x86_64 /usr/local/bin/brew install postgresql
./install_osx.sh ~/.pyenv/versions/3.7.12/bin/python /usr/local
```
