### ISSUE TITLE
from vnpy.gateway.xtp import XtpGateway 失败

### ISSUE THREAD

**Issue by zechzhao** [vnpy/vnpy#3141]
## 环境

* 操作系统: Windows 10  & ubuntu 20.04
* Python版本: 3.7 & 3.8
* vn.py版本:  v2.5.0

## Issue类型
三选一：Question

## 预期程序行为
import 成功

## 实际程序行为
import 失败

## 重现步骤
from vnpy.gateway.xtp import XtpGateway

![企业微信截图_16319436947621](https://user-images.githubusercontent.com/11520462/133877420-981539fe-3bdf-461f-8e22-5fd0241cfd83.png)

**Comment by vnpy** [comment]
请使用Python 3.7 64位，或者VNStudio最新版
