### ISSUE TITLE
docker 分支中，Dockerfile 执行出错，缺locale-gen 文件

### ISSUE THREAD

**Issue by tianhm** [vnpy/vnpy#315]
Sending build context to Docker daemon 11.78 kB
Step 1/11 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
c62795f78da9: Pull complete 
d4fceeeb758e: Pull complete 
5c9125a401ae: Pull complete 
0062f774e994: Pull complete 
6b33fd031fac: Pull complete 
Digest: sha256:c2bbf50d276508d73dd865cda7b4ee9b5243f2648647d21e3a471dd3cc4209a0
Status: Downloaded newer image for ubuntu:16.04
 ---> 6a2f32de169d
Step 2/11 : ENV TZ Asia/Shanghai
 ---> Running in 04c07d75c39e
 ---> 3916f24354fc
Removing intermediate container 04c07d75c39e
Step 3/11 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Running in 9e597e49ad06
 ---> 39a44eaba1f8
Removing intermediate container 9e597e49ad06
Step 4/11 : RUN locale-gen zh_CN.UTF-8     && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
 ---> Running in 90d1c3c5cab3
/bin/sh: 1: locale-gen: not found
Removing intermediate container 90d1c3c5cab3
The command '/bin/sh -c locale-gen zh_CN.UTF-8     && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales' returned a non-zero code: 127

通过修改Dockerfile, 增加 RUN apt-get install locales  即可正常运行。

**Comment by tianhm** [comment]
改动后的Dockerfile，ubuntu的docker image换成了网易的。这样速度快了很多。
FROM hub.c.163.com/public/ubuntu:16.04-tools

# 时区设置
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install locales

# 中文支持
RUN locale-gen zh_CN.UTF-8 \
    && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
RUN locale-gen zh_CN.UTF-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8


## 替换 apt 源为阿里云，在本地构建镜像时，取消注释，使用阿里云的 apt 源
RUN echo "" > /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ xenial main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-backports main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-proposed main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-backports main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-proposed main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main multiverse restricted universe" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main multiverse restricted universe" >> /etc/apt/sources.list

# 更新源列表
RUN apt-get clean \
    && apt-get update

# 安装编译环境
RUN apt-get install -y build-essential libboost-all-dev python-dev cmake

# 安装 conda
RUN echo "从 apt 获取软件" \
    && apt-get install -y bzip2 wget \
    && apt-get clean \
    && echo "安装 miniconda" \
    && mkdir /tmp/conda/ \
    && cd /tmp/conda/ \
    && wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh \
    && bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm Miniconda2-latest-Linux-x86_64.sh \
    && echo "设置 conda 和 python 的环境" \
    && ln -s /opt/conda/bin/python /usr/local/bin/python \
    && ln -s /opt/conda/bin/conda /usr/local/bin/conda \
    && ln -s /opt/conda/bin/pip /usr/local/bin/pip \
    && echo "从 conda 安装 python 库" \
    && conda install -y pymongo bsddb \
    && conda clean -ay \
    && echo "安装结束"

**Comment by tianhm** [comment]
网易的docker镜像已经安装了locales，特此说明。

**Comment by nehCkirE** [comment]
miniconda还可以换成清华的源
`RUN echo "从 apt 获取软件" \
    && apt-get install -y bzip2 wget \
    && apt-get clean \
    && echo "安装 miniconda" \
    && mkdir /tmp/conda/ \
    && cd /tmp/conda/ \
    **&& wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda2-latest-Linux-x86_64.sh \**
    && bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm Miniconda2-latest-Linux-x86_64.sh \
    && echo "设置 conda 和 python 的环境" \
    && ln -s /opt/conda/bin/python /usr/local/bin/python \
    && ln -s /opt/conda/bin/conda /usr/local/bin/conda \
    && ln -s /opt/conda/bin/pip /usr/local/bin/pip \
    && echo "从 conda 安装 python 库" \
    **&& conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
    && conda config --set show_channel_urls yes**
    && conda install -y pymongo bsddb \
    && conda clean -ay \
    && echo "安装结束"`

**Comment by lamter** [comment]
现在Dockerfile 已经采用了 163的Docker镜像和源
