### ISSUE TITLE
币安永续USDT接口一直在不断刷新API连接

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3154]
## 环境

* Python版本: python3.7
* vn.py版本: 如v2.5.0

## Issue类型
三选一：Bug

## 实际程序行为
币安永续USDT接口一直在不断刷新API连接

## 重现步骤
![币安接口一直在不断刷新API连接](https://user-images.githubusercontent.com/53517184/136206724-7a7524cd-b5c6-4cee-89c3-97bca2f466ff.png)

**Comment by AITrading2020** [comment]
> 请使用海外云服务器

@vnpy 这个就是在海外云服务器上部署的，几个月都没有出现过这个情况，前天是头一次出现

**Comment by arul67800** [comment]
Qqw qqaqqqqu
