### ISSUE TITLE
海外云端服务器，运行币安永续合约接口一段时间后，出现以下报错

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3155]
## 环境

* 操作系统: 如Windows 
* Python版本: 3.7
* vn.py版本: vnpy2.5.0

## Issue类型
三选一：Bug

## 实际程序行为
运行了半年多的币安合约接口了一直没遇到过这个情况，今天突然出现了，跑了四个进程，其中一个进程报了这个错误

![运行报错](https://user-images.githubusercontent.com/53517184/136548942-35c073ff-91c1-4605-bf91-19dfb719d546.png)

**Comment by vnpy** [comment]
交易所流量太大，导致币安用的这个CloudFront云供应商的前置访问后端服务器时没有收到响应，在客户端这边没有太好的处理办法了。。。
