### ISSUE TITLE
是否可以对数据管理中的导入数据位置增加选择文件后加上标的和交易所的自动对应

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3160]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.6.0

## Issue类型
三选一：Enhancement

## 重现步骤

群主，您好

是否可以增加选择导入的数据文件后自动增加上symbo、exchange，因为文件中已经有这两个数据的了，这样用起来才更方便的。我已经弄好了，期望后续版本能够增加上这个位置的方便使用。
谢谢！

**Comment by vnpy** [comment]
暂无计划，很多数据文件是没有symbo/exchange列的
