### ISSUE TITLE
关于启动web服务时的报错。

### ISSUE THREAD

**Issue by wozhishilaonanhai** [vnpy/vnpy#3168]
## 环境

* 操作系统: Windows 10
* Python版本: 3.7
* vn.py版本:  2.6.0

## Issue类型
三选一：Question

## 预期程序行为
程序通过代码启动，在添加了WebTraderApp模块后。启动web服务，能顺利看到web页面。

## 实际程序行为
启动web服务时报错，提示“FileNotFoundError: [WinError 3] 系统找不到指定的路径。....”，我不确定问题出在哪里。问题所指的路径我能找到。似乎跟vue有关。

## 重现步骤

![image](https://user-images.githubusercontent.com/43127110/138594729-c3035e96-6da0-4b55-964e-4b5d5e927f19.png)

**Comment by vnpy** [comment]
请使用VNStudio试试，不推荐新手自己安装还使用虚拟环境。
