### ISSUE TITLE
vnpy2.7版本新增的dydx接口对用户的服务器预埋stop order不兼容

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3177]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如3.7
* vn.py版本: 如v2.7

## Issue类型
三选一：Bug

## 实际程序行为
当用户已经有预埋的止损单时，或者用户新添加止损单时，运行中的dydx接口均会报如下错误：
![dydx stop order报错](https://user-images.githubusercontent.com/53517184/139013983-cfd6917b-5b92-4480-a135-adb191ff80ac.png)

另外该接口是否可以下载足够的历史数据长度呢？ 策略初始化的时候发现很快初始化完成了，疑似接口没有提供策略足够的数据来进行初始化：
![接口中历史数据提供的频率](https://user-images.githubusercontent.com/53517184/139014216-898e2224-55a6-414a-bc21-6745be9c5c00.png)

**Comment by noranhe** [comment]
> ## 环境
> * 操作系统: 如Windows 10
> * Python版本: 如3.7
> * vn.py版本: 如v2.7
> 
> ## Issue类型
> 三选一：Bug
> 
> ## 实际程序行为
> 当用户已经有预埋的止损单时，或者用户新添加止损单时，运行中的dydx接口均会报如下错误： ![dydx stop order报错](https://user-images.githubusercontent.com/53517184/139013983-cfd6917b-5b92-4480-a135-adb191ff80ac.png)
> 
> 另外该接口是否可以下载足够的历史数据长度呢？ 策略初始化的时候发现很快初始化完成了，疑似接口没有提供策略足够的数据来进行初始化： ![接口中历史数据提供的频率](https://user-images.githubusercontent.com/53517184/139014216-898e2224-55a6-414a-bc21-6745be9c5c00.png)

这是接口不支持的订单类型了，请自己进行个性化修改了。
dydx只提供100根历史数据了。

**Comment by noranhe** [comment]
> ![image](https://user-images.githubusercontent.com/53517184/139446130-41e2e1af-054d-4861-b355-a19d53db2c23.png)
> 
> dydx在进行下单时，报上述错误。
> 
> 我发现设置limitfee 设置为 0.0004时，依旧是上述错误，只有设置为limitfee为0.0009的时候，才可以正常运行算法交易。 但我选择的算法交易里面的best limit order的执行方式，结果实际执行的发到交易所的单子，还都是吃单成交的，这个明显没有起到best limit order算法交易的作用了啊

可参考https://docs.dydx.exchange/#order-limitfee
