### ISSUE TITLE
FTX接口，best limit order报错

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#3180]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如3.7
* vn.py版本: 如v2.7

## Issue类型
三选一：Bug

## 实际程序行为
![image](https://user-images.githubusercontent.com/53517184/139455542-1876bdfa-5271-4a04-a577-fa3491f117b7.png)

**Comment by vnpy** [comment]
这个提示是FTX接口的流控较为严格导致的，不适合运行BestLimit算法了
