### ISSUE TITLE
遗传算法优化报错

### ISSUE THREAD

**Issue by linst95** [vnpy/vnpy#3187]
## 环境

* 操作系统: Windows 10
* vn.py版本: VN Station 2.7.1

## Issue类型
Bug

## 预期程序行为
遗传算法优化完成，显示结果

## 实际程序行为
log记录显示卡住，且点击开始新回测显示：已有任务在运行中，请等待完成

## 重现步骤
启动遗传算法优化

## 后台报错截图
![遗传算法优化bug截图](https://user-images.githubusercontent.com/25526144/141301945-ae8c3c68-5309-46e4-98b6-a0286750afcb.PNG)

**Comment by vnpy** [comment]
目前找到的参考资料：https://stackoverflow.com/questions/52265120/python-multiprocessing-pool-attributeerror

我们这里尝试下来有一定概率出现，不是每次必定出现，需要继续排查。

**Comment by kimibao** [comment]
出现同样问题

RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\vnstudio\lib\multiprocessing\managers.py", line 234, in serve_client
    request = recv()
  File "c:\vnstudio\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'scalar' on <module 'numpy.core.multiarray' from 'c:\\vnstudio\\lib\\site-packages\\numpy\\core\\multiarray.py'>

**Comment by Edanflame** [comment]
应该是与目前的vnstation有关，暂时可以通过使用run.py脚本启动的方式来解决
