### ISSUE TITLE
portfolio_strategy.backtesting 夜盘交易记录对应的daily_results 错误

### ISSUE THREAD

**Issue by sixkingdoms** [vnpy/vnpy#3188]
## 环境

* 操作系统: Win10 
* Python版本: Py3.7
* vn.py版本: 2.7

## Issue类型
三选一：Bug

vnpy/vnpy/app/portfolio_strategy/backtesting.py 函数 calculate_result , 获取对应的daily_results
for trade in self.trades.values():
            d = trade.datetime.date()
            daily_result = self.daily_results[d]
            daily_result.add_trade(trade)

## 预期程序行为
对于夜盘时段交易， 应返回交易日 
如： 2019-05-07 21：30：00，应返回 2019-05-08
## 实际程序行为
返回日历日。 
如： 2019-05-07 21：30：00， 返回 2019-05-07

## 重现步骤

正常运行程序。

**Comment by vnpy** [comment]
vn.py的逐日盯市结算，是基于自然日来实现的，这点需要兼容除了国内期货以外的其他市场，因此无法改为交易日了。
