### ISSUE TITLE
rqdata接口下载rb数据时报错

### ISSUE THREAD

**Issue by wangyitao** [vnpy/vnpy#3198]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: python3.7
* vn.py版本: 如vnpy 2.7发行版

## Issue类型
三选一：Bug

## 预期程序行为
下载数据不报错，且能正常下载

## 实际程序行为
当下载rb888.SHFE 2010/1/1-2013/11/12的数据时，程序报错
![image](https://user-images.githubusercontent.com/12211038/142886925-79a9838d-f2fe-460c-bd88-ef8ac007dd57.png)

## 重现步骤
rqdata接口下载rb888.SHFE 2010/1/1-2013/11/12的数据

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请升级到2.7.0版本的vn.py，然后运行：

`pip install vnpy_rqdata --upgrade`

升级下接口即可
