### ISSUE TITLE
CTPgateway 交易所组合价差，最新价和成交量无法正常获取，显示为最大浮点数或0；

### ISSUE THREAD

**Issue by mailtostanley** [vnpy/vnpy#3199]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
![## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
%J(Q@K$ X93XL2UZZIABW](https://user-images.githubusercontent.com/15809878/142959724-e9db5566-0c26-465d-8d5d-4bc1cbd602a0.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
收到，我们来排查下

**Comment by smartgang** [comment]
价差合约本来就不带最新价和成交量吧

**Comment by noranhe** [comment]
请问你的vnstation版本是？这个问题应该早就解决了，last_price通过adjust_price函数处理之后应该显示的是0
