### ISSUE TITLE
oanda Api 配置文件

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#32]
vnoanda.py中的以下几行，有点小错误
API_SETTING['practice'] = {'rest': 'https://api-fxpractice.oanda.com',
                           'stream': 'https://stream-fxpractice.oanda.com'}
API_SETTING['trade'] = {'rest': 'https://api-fxpractice.oanda.com',
                        'stream': 'https://stream-fxtrade.oanda.com/'}

应为
API_SETTING['practice'] = {'rest': 'https://api-fxpractice.oanda.com',
                           'stream': 'https://stream-fxpractice.oanda.com/'}
API_SETTING['trade'] = {'rest': 'https://api-fxtrade.oanda.com',
                        'stream': 'https://stream-fxtrade.oanda.com/'}

**Comment by vnpy** [comment]
多谢，今天修复！
