### ISSUE TITLE
vn.py官网论坛点击“微信登陆”没有反应

### ISSUE THREAD

**Issue by xiedidan** [vnpy/vnpy#3203]
## 环境

* 操作系统: Win10
* Python版本: 无关
* vn.py版本: 无关

## Issue类型
三选一：Question

## 预期程序行为
点击官网论坛“微信登录”应该弹出微信扫码界面

## 实际程序行为
页面似乎刷新了一下，但没有其他反应
在2台电脑，2个不同的网络环境（电信有线和手机热点），Edge和Chrome浏览器都是同样反应

## 重现步骤
访问https://www.vnpy.com/forum/点击“微信登录”

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
之前遭受来自境外的网络攻击，目前正在升级论坛程序，预计下周恢复。

**Comment by xiedidan** [comment]
> 

辛苦了，了解，谢谢
