### ISSUE TITLE
CTP合约信息查询成功前,PAPER_ACCOUNT就尝试订阅已有持仓的合约导致合约订阅失败

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3205]
![image](https://user-images.githubusercontent.com/55074597/144805762-0d4e22ef-be99-4a3a-bb23-33a96d1921ea.png)

**Comment by EzMoney-Sniper** [comment]
这样会导致 portfolio_manager 无法获取到当前持仓，问题较为严重

**Comment by noranhe** [comment]
这个问题应该是你同时勾选了paper_account模块和portfolio_manager模块导致的，目前可以先用run.py启动，在add_app加载模块的时候把加载paper_account放在加载portfolio_manager前面试试

**Comment by EzMoney-Sniper** [comment]
这个问题已经解决，谢谢楠姐啊
