### ISSUE TITLE
PAPER_ACCOUNT+portfolio_manager组合使用问题

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3207]
盘中关闭vn_trader,last_pos保存，再马上打开vn_trader，界面上今日买卖数量都归0，进行交易后再次将vn_trader关闭后，last_pos为第二次打开vn_trader后进行交易的仓位，而不是两次交易仓位的总和，这个问题除了盘中不关闭vn_trader，还有别的解决方案吗

**Comment by EzMoney-Sniper** [comment]
我觉得last_pos不应该是覆盖第一次关闭vn_trader前的last_pos，而应该增量更新啊

**Comment by noranhe** [comment]
这个文档（https://www.vnpy.com/docs/cn/portfolio_manager.html#id8）里介绍过了，目前只支持隔日加载的
