### ISSUE TITLE
get_position持仓查询的使用方法与文档不符

### ISSUE THREAD

**Issue by lanchengjiu** [vnpy/vnpy#3209]
## 环境
* 操作系统: 如Windows 10
* Python版本: 如Python 3.7.11
* vn.py版本: v2.7.0-git源码安装

## Issue类型
Bug

## 预期程序行为
engine.main_engine.get_position('IF2112.CFFEX.Direction.LONG')

## 实际程序行为
engine.main_engine.get_position('IF2112.CFFEX.多')

{'IF2112.CFFEX.多': PositionData(gateway_name='CTP', symbol='IF2112', exchange=<Exchange.CFFEX: 'CFFEX'>, direction=<Direction.LONG: '多'>, volume=4, frozen=1, price=4917.0, pnl=68400.0, yd_volume=4), 'IF2112.CFFEX.空': PositionData(gateway_name='CTP', symbol='IF2112', exchange=<Exchange.CFFEX: 'CFFEX'>, direction=<Direction.SHORT: '空'>, volume=0, frozen=0, price=0, pnl=0.0, yd_volume=0)}

现在这个“IF2112.CFFEX.多”也没什么不好，不过建议修改文档统一，谷歌查了下，没有人指出这个问题。

## 回测中开始日期无法正确读取
另外还有个小问题，cta_backtester_setting.json中start的格式是isoformat()，造成Qt界面无法成功读取
建议如下修改，顺便加上了end时间读取，理由如下
1、为了回测速度，有些指标是提前算好保存在文件中的，因此无法实时计算与更新
2、相同的时间段才能保证回测结果可对比，所以保存读取end时间可能比使用最新时间的情况更常见

\site-packages\vnpy_ctabacktester\ui\widget.py

start_str = setting.get("start", "")
if start_str:
    start_dt = QtCore.QDate.fromString(start_str, "yyyy-MM-dd")
    self.start_date_edit.setDate(start_dt)

end_str = setting.get("end", "")
if end_str:
    end_dt = QtCore.QDate.fromString(end_str, "yyyy-MM-dd")
    self.end_date_edit.setDate(end_dt)

backtesting_setting = {
    "class_name": class_name,
    "vt_symbol": vt_symbol,
    "interval": interval,
    "start": start.strftime('%Y-%m-%d'),
    "end": end.strftime('%Y-%m-%d'),
    "rate": rate,
    "slippage": slippage,
    "size": size,
    "pricetick": pricetick,
    "capital": capital,
    "inverse": inverse,
}
save_json(self.setting_filename, backtesting_setting)

**Comment by Edanflame** [comment]
已在https://github.com/vnpy/vnpy/pull/3216 中修复文档问题。回测开始时间读取问题已在https://github.com/vnpy/vnpy_ctabacktester/pull/5 中修复。结束日期可能不同的使用者的使用习惯不同，暂未修改。
