### ISSUE TITLE
Mac安装脚本不支持M1芯片

### ISSUE THREAD

**Issue by sunaigo** [vnpy/vnpy#3210]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 如v2.0.5发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cymqqqq** [comment]
在此询问vnpy团队什么时候能修复m1 mac安装失败的问题

**Comment by Edanflame** [comment]
尝试使用2.9.0最新的安装脚本安装试试。m1 mac的问题有些是依赖库和python本身不支持导致的，我们也在等待python以及依赖对m1芯片的完美适配。由于我们目前没有m1芯片的机器来开发，所以有些问题可能需要自行调试修改一下，在过程中可以把遇到的具体问题贴在issues上或者论坛上，可以大家一起讨论，我们也会尽力解决。
