### ISSUE TITLE
Binance接口

### ISSUE THREAD

**Issue by kaiqiangh** [vnpy/vnpy#3217]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.8.1

## Issue类型
Question

更新VN Station至2.8.1版本之后，没有找到Binance接口，所有的数字货币交易所接口都没了，请问如何添加？

**Comment by vnpy** [comment]
我们团队已经不再维护，仓库转移给了新的维护者：https://github.com/vn-crypto/vnpy_binance/
