### ISSUE TITLE
vnpy在python 3.10版本下安装问题

### ISSUE THREAD

**Issue by Edanflame** [vnpy/vnpy#3219]
## 环境

* 操作系统: 如Windows 10
* Python版本: python 3.10
* vn.py版本: v2.8.1

## Issue类型
Enhancement

## 安装问题
python 3.10无法安装rqdatac的2.9.38版本
python 3.10中移除parser库
python 3.10无法安装最新的deap库

**Comment by vnpy** [comment]
已有对应解决方案
