### ISSUE TITLE
升级Python依赖库

### ISSUE THREAD

**Issue by xJayLee** [vnpy/vnpy#3222]
## 环境

* 操作系统: Mac M1
* Python版本: Anaconda-Navigator 最新
* vn.py版本: 如v2.9.0发行版

## Issue类型
升级Python依赖库

## 预期程序行为
升级Python依赖库

## 实际程序行为

[已经升级成功](url)
[requirements.txt](https://github.com/vnpy/vnpy/files/7797746/requirements.txt)

**Comment by Edanflame** [comment]
你好，由于vn.py是多平台支持的，目前使用一些依赖库在不同版本下可能会产生冲突，目前已知的一些是pyqt5最新版可能会导致windows或mac用户无法打开图像界面，pandas最新版可能无法使用某些数据库等问题。所以目前暂时锁住了版本，避免带来用户无法使用的问题。目前我们开发机没有M1芯片机器，欢迎尝试升级后给我们反馈建议。
