### ISSUE TITLE
vnpy 在macOS Monterey下的安装问题

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#3223]
## 环境

* 操作系统: MacOS Monterey
* Python版本: 如python 3.7.11
* vn.py版本: v2.9.0

## Issue类型
Question

## 预期程序行为
example中的run.py打开图形主界面

## 实际程序行为
无法打开图形界面

解决方案：
pip install PyQt5==5.15.4 后，才可以打开图形界面

**Comment by yhmickey** [comment]
找不到字体解决： mac下需要将vt_setting.json中 微软雅黑 换成 简宋

**Comment by vnpy** [comment]
3.0中将改为使用PySide6，解决该问题
