### ISSUE TITLE
一些实用的功能优化建议，请作者看下哪些可以提PR

### ISSUE THREAD

**Issue by lanchengjiu** [vnpy/vnpy#3225]
## Issue类型
三选一：Enhancement

## 建议优化
**OptimizationSetting参数配置生成器相关优化**
1. 使用Decimal计算步进参数值，避免出现N位小数问题，并且可以使得截止值end也在生成的参数列表内
2. 添加固定参数的条件加上“or start == end”，避免start == end造成不能成功添加参数的bug
3. 允许将列表作为参数直接传入，“self.params[name] = start”，方便代码回测情况的二次开发

**各实盘引擎添加策略时使用self.symbol_strategy_map[strategy.vt_symbol]代替vt_symbol**
目的是引擎初始化添加策略时，策略自身可以对合约进行分析和修改扩充，进而方便二次开发实现自动移仓换月等功能

**保存参数优化回测结果时将参数与结果字段全部展开保存（Excal打开后的效果如下）**
当前参数字段是字典格式，结果只有一个目标指标，但是其实回测结果是完整全量的，新人不知道甚至重复多次相同的回测

![最终效果展示](https://user-images.githubusercontent.com/43301062/149638712-5a03cc88-8b53-473b-a337-3ec9a4e1653c.jpg)

## 可选优化
1. 通过分析依赖树，numpy可以使用的最高版本为1.19.3，当前依赖版本1.18.2，dolphindb[numpy<=1.19.3]，scipy[numpy<1.23.0]
2. vnpy_ctabacktester的UI界面，StatisticsMonitor显示回测结果指标时遗漏了“最大回撤天数”这个指标，应该是个小bug

**Comment by vnpy** [comment]
您好，感谢建议！

这样我们来分步来操作，方便的话请先提起这个的PR看下：

> 使用Decimal计算步进参数值，避免出现N位小数问题，并且可以使得截止值end也在生成的参数列表内

**Comment by vnpy** [comment]
您好，感谢建议！

这样我们来分步来操作，方便的话请先提起这个的PR看下：

> 使用Decimal计算步进参数值，避免出现N位小数问题，并且可以使得截止值end也在生成的参数列表内
