### ISSUE TITLE
自成交一多一空的2条成交记录只显示其中1条

### ISSUE THREAD

**Issue by ieachen** [vnpy/vnpy#3229]
## 环境

* vn.py版本: v2.9.0发行版

## Issue类型
三选一：Bug

## 重现步骤

自成交一多一空两笔的成交编号相同，但实际是两笔不同的成交记录，vnpy只显示其中一笔成交记录，少了另一笔。

代码涉及到两处：

object.py 里 TradeData：

```Python
self.vt_tradeid = f"{self.gateway_name}.{self.tradeid}" 
```

engine.py 里 OmsEngine：
```Python

    self.trades: Dict[str, TradeData] = {}
    ......
    def process_trade_event(self, event: Event) -> None:
        trade: TradeData = event.data
        self.trades[trade.vt_tradeid] =  trade
```

`process_trade_event` 用 vt_tradeid 作为唯一 key，vt_tradeid 用 gateway_name + tradeid，而部分交易所（比如上期所、大商所）对于自成交一多一空的 tradeid 相同，这就导致了 `process_trade_event`  会只保留自成交的2条记录中的1条。

修改建议是 TradeData 的 vt_tradeid 添加另一个识别符，这个标识符有2个候选：direction 或 orderid，比如 `vt_tradeid = gateway_name.tradeid.direction的int版`。

ps：请勿自成交

**Comment by vnpy** [comment]
请问具体怎么触发的自成交？

**Comment by ieachen** [comment]
您好。比如卖一有自己的挂单，然后砸对手价下买单、下单量超过卖一的量，就触发自成交。成交记录少了一条，因为tradeid相同被过滤了。

不过不建议在实盘复现，因为自成交是违规的。SimNow不确定能不能复现。

从网上找了篇文章，说了各大期货交易所的tradeid 自成交规则： https://zhuanlan.zhihu.com/p/133433958
截图如下：

![aaa](https://user-images.githubusercontent.com/24794105/150973466-f38eda18-6ebe-4098-be09-3fcc59fcee78.jpg)

**Comment by vnpy** [comment]
这块基于以下几点原因不做处理：
1. 实盘交易中，不应出现自成交的委托（策略控制）
2. 即使发出了相应委托，极大概率也是和他人订单成交
3. 主界面的TradeMonitor采用自增行数显示，即使两条vt_tradeid相同的记录也会分两条显示
