### ISSUE TITLE
我自己在做的重构思路

### ISSUE THREAD

**Issue by desont** [vnpy/vnpy#324]
1、目录调整，像语言、类、配置参数、应用目录作为并列的子目录。应用目录类似vnapp可以根据需求存在多个。
├─.idea
├─FAQ
├─language
│  ├─Chinese
│  └─English
├─lib
│  └─gateway
│      ├─ctpGateway
│      │  └─language
│      │      ├─Chinese
│      │      └─English
│      ├─femasGateway
│      ├─huobiGateway
│      ├─ibGateway
│      │  └─language
│      │      ├─Chinese
│      │      └─English
│      ├─ksgoldGateway
│      │  └─SLEdll
│      │      └─KSCA
│      │          └─ksca
│      ├─ksotpGateway
│      ├─lhangGateway
│      ├─ltsGateway
│      ├─oandaGateway
│      ├─okcoinGateway
│      ├─qdpGateway
│      ├─sgitGateway
│      ├─shzdGateway
│      ├─windGateway
│      └─xspeedGateway
├─util
│  └─model
└─vnapp
    ├─conf
    ├─ctaStrategy
    │  ├─language
    │  │  ├─Chinese
    │  │  └─English
    │  ├─strategy
    │  └─tools
    │      └─multiTimeFrame
    ├─strategy
    │  ├─param
    │  └─vars
    │      ├─ctpgw_nh
    │      └─ctpgw_simnow1
    └─temp
        └─ctpgw_simnow1

2、lib里面的类互相直接不会直接嵌套，通过vnapp里面的mainServer或者mainClient统一调度插入，下面是无界面的简单调用例子，如果配合界面使用需要做改造。
`# encoding: UTF-8

################################################################
# 服务端程序
# 按照顺序创建组件
# 可以配合界面程序进行监控管理
# by huangwei
# 2017.4.24
################################################################
import sys
from env import appPath,rootPath,modelPath,confPath,debugset
sys.path.append(rootPath)
from lib.vtServer import *
from lib.dbEngine import *
from lib.eventEngine import *
from lib.eventType import *
from lib.rmEngine import *
from lib.vtEngine import *
from lib.vtGateway import *
from lib.vtLog import *
from lib.dbEngine_mysql import *
from lib.gateway.ctpGateway.ctpGateway import *
from lib.showLog import *

#----------------------------------------------------------------------
def log(data):
    print data

#----------------------------------------------------------------------
def readSetting(fname):
    #返回setting信息
    sfile = confPath + fname
    with open(sfile) as sf :
        d = json.load(sf)
        return d
#----------------------------------------------------------------------
def readSource():
    #返回source信息
    sourcefile = confPath + 'sourceServer.json'
    #print sourcefile
    with open(sourcefile) as sf :
        d = json.load(sf)
        return d

#----------------------------------------------------------------------
def getPassword(userid):
    d={}
    d['72300079'] = '082411'
    d['030208'] = '3854251'
    return d[userid]

#----------------------------------------------------------------------
def main():
    source = readSource()               # 读取资源
    setDict = {}

    for d in source :
        name = d['name']
        fname = d['fname']
        if d['type'] != 'strategy':
            setDict[name] = readSetting(fname)

    # eventEngine 模块
    eventEngine = EventEngine2()
    eventEngine.start()

    # log模块 初始化设置
    vtlog = VtLog()
    vtlog.setEventEngine(eventEngine)   # 设置eventEngine
    vtlog.setPrintable(True)            # 设置可打印输出
    vtlog.setDebug(debugset)            # 设置可输出debug信息
    #vtlog.setEventable(True)           # 设置日志进入event序列,debug信息除外

    showLog = ShowLog(eventEngine)

    for k,v in setDict.items():        # 检查是否正常
        vtlog.writeDebug(v)

    # db模块
    dbEngine = DbEngineMysql()
    dbEngine.setLog(vtlog)              # 配置log
    set = setDict['mysql_1']            # 获取需要使用的配置信息
    dbEngine.dbConnect(set)

    # 主引擎
    vtEngine = MainEngine()
    vtEngine.setEventEngine(eventEngine)
    vtEngine.setLogEngine(vtlog)                            # 插入日志引擎

    # 新建gateway
    '''
    gw = CtpGateway(eventEngine,'ctpgw_nh')
    set = setDict['ctpgw_nh']
    set['password'] = getPassword(set['userID'])
    gw.setSetting(set)
    vtEngine.addGateway(gw)
    vtEngine.setRmSetting('ctpgw_nh',setDict['rm_1'])
    vtEngine.connect('ctpgw_nh')
    '''

    # 新建另一个gateway
    gw = CtpGateway(eventEngine,'ctpgw_simnow1')
    set = setDict['ctpgw_simnow1']
    set['password'] = getPassword(set['userID'])
    gw.setSetting(set)
    vtEngine.addGateway(gw)
    vtEngine.setRmSetting('ctpgw_simnow1',setDict['rm_1'])          # 内置风险引擎设置
    vtEngine.connect('ctpgw_simnow1')

    repAddress = 'tcp://127.0.0.1:2014'
    pubAddress = 'tcp://127.0.0.1:0602'

    # 创建并启动RPC服务器
    server = VtServer(repAddress, pubAddress)
    server.setMainEngine(vtEngine)
    server.registerAll()
    server.start()

    printLog('-'*50)
    printLog(u'vn.trader服务器已启动')

if __name__ == '__main__':
    main()`

3、基础目录设置在应用目录下的evn.py定义
`import os

rootPath = os.path.abspath(os.path.join(os.path.dirname(__file__),".."))
#print 'rootPath',rootPath
modelPath = rootPath + '/util/model/'
#print 'modelPath',modelPath
appPath = os.path.dirname(os.path.abspath(__file__))+'/'
#print 'appPath',appPath
confPath = appPath+'/conf/'

debugset = True`

4、多语言的设置，我的设想是wirtelog时候直接使用特定id值，通过event发送出去，id值对应的描述统一放在语言目录中，使用单独的类显示描述内容，这样语言目录不用分散到各个子目录，统一在根目录中就可以了。

**Comment by vnpy** [comment]
参考以上建议，已经初步完成v1.6.2的重构
