### ISSUE TITLE
白天行情记录问题

### ISSUE THREAD

**Issue by ibmxiang** [vnpy/vnpy#3251]
版本：vnpy2.3.0
运行方式 no_ui 格式运行，环境为：腾讯云ubuntu20.04
no_ui，中仅仅添加行情记录模块代码 main_engine.add_app(DataRecorderApp)

在8.45启动程序的时候能够正确记录上期所SHFE数据
8.55启动，能够正确记录上期所SHFE数据,能够部分记录郑商所CZCE数据，不能够记录大商所DCE数据
8.58启动，能够正确记录上期所SHFE数据,能够部分记录郑商所CZCE数据，不能够记录大商所CZE数据

但是早上9点之后重启程序，则可以记录所有交易所数据

夜盘下午20.45启动程序。能够记录所有交易所数据

在这些情况下。策略中能够收到所有交易所的数据，这说明行情订阅成功吧？
如我的datarecoder_setting：
早上只记录上期所的。其他两个都不记录
{
    "tick": {},
    "bar": {
        "AP205.CZCE": {
            "symbol": "AP205",
            "exchange": "CZCE",
            "gateway_name": "CTP"
        },
        "TA205.CZCE": {
            "symbol": "TA205",
            "exchange": "CZCE",
            "gateway_name": "CTP"
        },
        "fu2205.SHFE": {
            "symbol": "fu2205",
            "exchange": "SHFE",
            "gateway_name": "CTP"
        },
        "sp2205.SHFE": {
            "symbol": "sp2205",
            "exchange": "SHFE",
            "gateway_name": "CTP"
        },
        "i2209.DCE": {
            "symbol": "i2209",
            "exchange": "DCE",
            "gateway_name": "CTP"
        },
        "p2205.DCE": {
            "symbol": "p2205",
            "exchange": "DCE",
            "gateway_name": "CTP"
        }
    }
}

**Comment by siaosing** [comment]
https://www.vnpy.com/forum/topic/6160-guan-yu-sheng-ji-vnpy2-1-9hou-ce-lue-on-barbu-hong-fa-he-datarecoderwu-fa-zheng-chang-ji-lu-de-wen-ti-ctp
早上开盘前连接ctp的时候会重播一遍夜盘的tick，最后一个tick的时间戳会打错成当天的，导致bg.update_tick直接return了，自己在on_tick里面加个过滤，把非交易时间收到的tick过滤掉就行了.

**Comment by vnpy** [comment]
请升级到3.0.0版本即可，优化了CTP的tick数据推送时间戳日期部分的判断逻辑。
