### ISSUE TITLE
请移除开拓者历史数据导入函数

### ISSUE THREAD

**Issue by cooooo** [vnpy/vnpy#326]
请移除ctaHistoryData.py中loadTBCsv函数。
原因如下：
1、开拓者导出历史数据中持仓量与实盘CTP记录数据不同
2、函数本身逻辑有错误

**Comment by vnpy** [comment]
请给出具体的问题细节，否则单纯两句话就要删除代码的请求不可能接受

**Comment by vnpy** [comment]
跟函数作者沟通后发现问题所在，会尽快移除

**Comment by vnpy** [comment]
已完成
