### ISSUE TITLE
希望多合约组合策略与cta策略模块保持一致，支持停止单

### ISSUE THREAD

**Issue by daysdaysup** [vnpy/vnpy#3260]
## 环境

* 操作系统: macos 
* Python版本:3.10
* VeighNa版本: 3.0

## Issue类型
Enhancement

## 预期程序行为
多合约组合策略模块支持停止单

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
暂无计划，由于投组策略的多合约数据回放特性，无法保证回测时的停止单撮合顺序和实盘一致。
