### ISSUE TITLE
父进程守护子进程时lo: Resource temporarily unavailable eth1: Resource temporarily unavailable

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3268]
## 环境
ubuntu18.4
python3.10
vnpy3.0
## Issue类型
question

linux python3.10下在全市场录制行情时警告如下
lo: Resource temporarily unavailable
eth1: Resource temporarily unavailable
/dev/mem: No such file or directory
/dev/mem: No such file or directory
lo: No such file or directory
eth1: No such file or directory

**Comment by vnpy** [comment]
请问使用的数据库是？

**Comment by EzMoney-Sniper** [comment]
使用的数据库是mongodb，下图是报错出现的位置
![image](https://user-images.githubusercontent.com/55074597/159820169-8b3b194b-44c4-41f0-b661-9fd3e9d2728a.png)

**Comment by EzMoney-Sniper** [comment]
也不是报错只是警告，没影响正常使用

**Comment by vnpy** [comment]
找到两个对应资料：

https://blog.csdn.net/badqiu/article/details/84002280

https://forums.docker.com/t/dev-mem-no-such-file-or-directory-in-ubuntu-linux-14-04-container/28403/6

猜测应该是Ubuntu系统的设置问题。
