### ISSUE TITLE
tzlocal版本升级后需要更换函数

### ISSUE THREAD

**Issue by Edanflame** [vnpy/vnpy#3269]
## 环境

* 操作系统: 全平台
* Python版本: VeighNa Studio-3.0.0
* VeighNa版本: 3.0.0发行版
 
## Issue类型
Enhancement

## 问题
tzlocal在最新的4.1版中get_localzone().zone会有警告，推荐更换get_localzone_name()

**Comment by noranhe** [comment]
已修复
https://github.com/vnpy/vnpy/pull/3275

**Comment by dehim** [comment]
@noranhe 这个文件漏改了 [vnpy]/setup.cfg
`install_requires =
    tzlocal==2.0.0
    PySide6
    pyqtgraph
    qdarkstyle
    numpy
    pandas
    matplotlib
    seaborn
    ta-lib
    deap
    pyzmq
    plotly`
