### ISSUE TITLE
解决BarGenerator在产生n分钟bar的错误

### ISSUE THREAD

**Issue by hxxjava** [vnpy/vnpy#3270]
## 环境

* 操作系统: 所有
* Python版本: 所有
* VeighNa版本: 所有版本

## Issue类型
三选一：Bug

## 预期程序行为

vnpy的BarGenerator在产生国内商品期货的n分钟bar的时候，
1）应该把每日集合竞价的那一个tick归入到之后的连续竞价的1分钟bar中。
2）在n分钟bar的时间占位上应该有日对齐、白盘对齐和夜盘对齐等多种方式。

## 实际程序行为

vnpy的目前的BarGenerator，在产生国内商品期货的n分钟bar的时候，有两个问题：
以30分钟bar为例
1）如果你是集合竞价之前启动的，会多出来一个只包含集合竞价tick的30分钟bar，因为它不考虑集合竞价，错误；
2）10:00~11:00只生成以一个30分钟bar，可是却包含45分钟的数据，而且之后的bar的时间占位、开盘、收盘、最高和最多也可能是错了，这和市面上绝大部分软件产生的K线都不一致，也不符合大多数用户的理解。

就是说每天可能会多出1个bar，还会有多个bar的时间占位是错误的，这个问题咱们需要结合交易时间段来彻底地解决一下，

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by noranhe** [comment]
原帖已复现回复，但是修改后的组件对vnpy_rqdata有强依赖、日线所有频率都是以分钟计且最后一个n分钟可能会不等长，不是特别适合合并进主仓库了。
