### ISSUE TITLE
start vn_trader get warning: Faile to import cython option pricing model, please rebuild with cython in cmd.

### ISSUE THREAD

**Issue by cetsupport** [vnpy/vnpy#3271]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: 3.9
* VeighNa版本: V3.0

## Issue类型
Question
## 预期程序行为
No warning.

## 实际程序行为
When start up the vn_trader, get below warning.

## 重现步骤
Fresh installation by python3 -m pip install vnpy

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cooooo** [comment]
更换 Python 版本之后需要重新 build 定价模型

**Comment by hwangjr** [comment]
如何重新 build 定价模型呢？ 使用最新 3.0.0 版本。

**Comment by vnpy** [comment]
进入vnpy_optionmaster\pricing\cython_model下的每个模型目录，运行命令：

`python setup.py build_ext --inplace`

然后将生成的pyd文件，复制到pricing目录即可

**Comment by hwangjr** [comment]
3.0.0 好像没有这个目录？

**Comment by vnpy** [comment]
> 3.0.0 好像没有这个目录？ 是其他关联库吗？

需要自行安装vnpy_optionmaster

**Comment by hwangjr** [comment]
> 

好的，感谢哈。

**Comment by Clairewangxiaotong** [comment]
您好，我也出现了同样的问题，在按您的方法xiug 后，出现了还是没有好，请问编译方法是有什么问题吗？
![image](https://user-images.githubusercontent.com/103891038/199906526-d32df31e-ffaa-4c94-8740-bb55ac0b43d0.png)




> 进入vnpy_optionmaster\pricing\cython_model下的每个模型目录，运行命令：
> 
> `python setup.py build_ext --inplace`
> 
> 然后将生成的pyd文件，复制到pricing目录即可

**Comment by dongyeo** [comment]
@vnpy 3.5.0 遇到同样的问题，pricing 目录也没有 cython_model 目录可以重新build的

**Comment by UnicornUnderMoon** [comment]
@dongyeo 
到 [vnpy_optionmaster](https://github.com/vnpy/vnpy_optionmaster/tree/main/vnpy_optionmaster/pricing)项目或者[gitee](https://gitee.com/vnpy/vnpy_optionmaster/tree/main/vnpy_optionmaster/pricing)上，下载 cython_model 目录。
进入该目录下的 binomial_tree_cython，  black_76_cython，  black_scholes_cython 三个目录中。分别运行：
`python setup.py build_ext --inplace`
复制新生成同目录名一样的`.pyx .so`文件到`/anaconda3/envs/trade/lib/python3.10/site-packages/vnpy_optionmaster/pricing/`(ananconda，ubuntu环境)。其他环境应该是把文件放到对应 pricing 文件夹下。
查网上信息知，windows环境下`python setup.py build_ext --inplace`命令生成的是`pyd`文件，安装vnpy后自带。本人ubuntu环境，该环境下，cython生成的是`.pyx .so`文件，都需要。
