### ISSUE TITLE
运行回测时需要给datetime添加时区信息

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3276]
## 环境

* 操作系统: ALL
* Python版本: ALL
* VeighNa版本: ALL

## Issue类型
三选一：Bug

运行回测时需要给datetime添加时区信息，否者输入的时间和实际想要回测的时间会不一致哦，建议官方在图形界面和example里边修改一下
'''
from pytz import timezone
DB_TZ = timezone("Asia/Shanghai")
start=datetime(2021, 11, 1,6,5).astimezone(DB_TZ),
 end=datetime(2022, 3, 11,12,23).astimezone(DB_TZ),
'''

**Comment by noranhe** [comment]
请问你用的数据库是mongodb吗？

**Comment by EzMoney-Sniper** [comment]
对

**Comment by vnpy** [comment]
已经在vnpy_mongodb修复
