### ISSUE TITLE
数据服务的适配器接口是否计划 CSMAR ？

### ISSUE THREAD

**Issue by luneice** [vnpy/vnpy#3279]
## Issue类型
Enhancement
[CSMAR](https://cn.gtadata.com/)也提供了很多高质量的数据，是否考虑支持该接口数据？
或者vnpy留接口让用户自己适配？

**Comment by vnpy** [comment]
简单看了下文档，技术上应该没什么问题，主要看CSMAR是否：

1. 提供股票、期货这类的行情数据了（日线和分钟级）
2. 是否提供日内数据更新，还是到了收盘后更新当天数据

另外CSMAR这家服务商我们团队没有接触过，如果有认识的可以介绍交流下上面两个问题

**Comment by luneice** [comment]
> 简单看了下文档，技术上应该没什么问题，主要看CSMAR是否：
> 
> 1. 提供股票、期货这类的行情数据了（日线和分钟级）
> 2. 是否提供日内数据更新，还是到了收盘后更新当天数据
> 
> 另外CSMAR这家服务商我们团队没有接触过，如果有认识的可以介绍交流下上面两个问题

仔细看了看，数据频率是日度的。
CSMAR是个比较有名的，但是它的目标好像从学术研究需求出发，提供的数据很全，但目前不支持分钟级数据。
