### ISSUE TITLE
vnpy-dev版本 No model named vnpy.trader.vtGlobal 报错处理建议

### ISSUE THREAD

**Issue by nikitazhhy** [vnpy/vnpy#329]
1.下载vnpy-dev版本的，windows系统添加pythonpath：系统--高级系统设置--环境变量--用户变量--新建--PYTHONPATH--vnpy-dev（主意是vnpy-dev，不是vnpy）。（我试着用pycharm添加路径，但是没成功，不知道为啥）

2.如果还是报No model named vnpy.trader.vtGlobal 错误，试着删除vnpy\trader\gateway 中的cshshlpGateway文件夹（中信证券接口）。

3.再次双击vtmain.py,看能否运行起来，我自己的是这么处理的 目前没什么问题。

另外，用pycharm的同学，有时候debug时候会莫名其妙报缺少各种库，我也不知道咋回事儿，之前明明装了pyqt之类的 可是就是读取不出来，这个还是让专业人士解答下吧，毕竟我是个半路出家的文科僧~

**Comment by vnpy** [comment]
1. 问下你添加的PYTHONPATH的路径，是完整的vnpy-dev文件夹所在的路径吗？
2. 确实pycharm会有些奇怪的问题，也是为啥我自己一直用WingIDE

**Comment by kantmp** [comment]
在vtMain 里面
import sys
sys.path.append('vnpy path')
这个方法也是可行

**Comment by nikitazhhy** [comment]
回答群主：
1.是的，要将完整vnpy-dev加进去，否则还是会报错。
2.pycharm经常读取不到已经安装的库，很奇怪，准备转投其他IDE。

**Comment by vnpy** [comment]
试试别的IDE吧
