### ISSUE TITLE
策略下拉列表里的策略的排序规则

### ISSUE THREAD

**Issue by adriancobb** [vnpy/vnpy#3292]
CTA策略模块里，策略下拉列表里的策略的排序规则不清楚是怎样的，策略多了以后，每次新添加一个策略，都要在列表里找半天。如果能默认按照字母顺序，或者策略添加的时间序来排序，那找策略的时候会方便很多。

**Comment by vnpy** [comment]
已经添加：

https://github.com/vnpy/vnpy_ctastrategy/commit/4ad7b4de35499bda20db897fb9b82b256245ab08
