### ISSUE TITLE
ubuntu 20.04报错ModuleNotFoundError: No module named 'vnpy_ctastrategy'

### ISSUE THREAD

**Issue by Anastasia-Sablina** [vnpy/vnpy#3293]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: python3.9.7
* VeighNa版本: 如v3.0.0

## Issue类型
三选一：Question

## 预期程序行为
运行python run.py后出现GUI

## 实际程序行为
    from vnpy_ctastrategy import CtaStrategyApp
ModuleNotFoundError: No module named 'vnpy_ctastrategy'

## 重现步骤
$sudo bash install.sh
$cd examples/veighna_trader
$python run.py
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
`pip install vnpy_ctastrategy`

安装下对应的模块即可
