### ISSUE TITLE
多策略执行时由于并发导致cta_strategy_data.json数据被覆写

### ISSUE THREAD

**Issue by xuxin3101** [vnpy/vnpy#3295]
## 环境

* 操作系统: linux
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 2.3

## Issue类型
三选一：Bug

## 预期程序行为
cta_strategy_data.json中的数据应该是所有正在运行的data

## 实际程序行为
cta_strategy_data.json中的数据由于并发导致只会写入一个策略的data

## 重现步骤
![image](https://user-images.githubusercontent.com/29241434/167375457-217e450d-595b-4761-905b-3110bd822c72.png)
![image](https://user-images.githubusercontent.com/29241434/167375971-508e56fc-f59f-4b74-a6b5-0ca8e6b32b83.png)
同时并发执行这里的时候会导致，建议加锁，目前采取的方式是sync_data的时候给不同的策略不同的延迟，不过还是希望能在框架方处理下，而不是策略方

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xuxin3101** [comment]
> 这个不主动调用就没事吧

是的，不主动调用没关系，一般策略会在on_trade方法去调用这个方法，一般来说，多个策略的成交时间不会出现这么巧的时候，但是如果有人把sync_data用在on_bar或者on_tick等方法的话，那这个bug就必现了

**Comment by noranhe** [comment]
参照示例策略使用应该不会出现这个问题的。process_trade_event函数里调用策略实例on_trade函数之后会sync_strategy_data的。如果需要主动调用建议还是进行个性化修改了。

**Comment by xuxin3101** [comment]
> 参照示例策略使用应该不会出现这个问题的。process_trade_event函数里调用策略实例on_trade函数之后会sync_strategy_data的。如果需要主动调用建议还是进行个性化修改了。

https://github.com/vnpy/vnpy_ctastrategy/issues/9
看到有人按照示例来也可能会有这种问题，如果行情波动大，多策略同时成交多也是可能出现这种问题的
