### ISSUE TITLE
Incorrect backtest statistics

### ISSUE THREAD

**Issue by Myusico** [vnpy/vnpy#3299]
## 环境

* 操作系统: Windows 10
* Python版本: VeighNa Studio-2.9.0
* VeighNa版本: v2.9.0发行版

## Issue类型
Bug

### Correct Method
- If (balance/pre_balance) is non-positive, leave daily log return as NaN, drop NaN before calculating standard deviation.
```
pre_balance = df["balance"].shift(1)
pre_balance.iloc[0] = self.capital
x = df["balance"] / pre_balance
df["return"] = np.log(x)
return_std = df["return"].dropna().std() * 100
```
### Current Method
- If (balance/pre_balance) is non-positive, treat daily log return as 0.
- The standard deviation calculated this way is biased and tend to be smaller than actual.
```
df["return"] = np.log(x).fillna(0)
return_std = df["return"].std() * 100
```

### Correct Method
![Max Drawdown Duration](https://pbs.twimg.com/media/EazQNclUMAI2wFm?format=png&name=900x900)
- Let the start day be 1, the drawdown duration of any given day i

$$
Drawdown\ Duration_i=i-k
$$

- where $k\in [1,2,...,i]$ is the day with the highest balance.
```
drawdown_durations = [np.asarray(df["balance"])[i::-1].argmax() for i in range(total_days)]
```
### Current Method
- Calculates the difference in days between the bottom and the peak of the max drawdown.
```
max_drawdown = df["drawdown"].min()
max_ddpercent = df["ddpercent"].min()
max_drawdown_end = df["drawdown"].idxmin()

if isinstance(max_drawdown_end, date):
    max_drawdown_start = df["balance"][:max_drawdown_end].idxmax()
    max_drawdown_duration = (max_drawdown_end - max_drawdown_start).days
else:
    max_drawdown_duration = 0
```
### See Also
https://en.wikipedia.org/wiki/Drawdown_(economics)

### Correct Method
- Use the simple total return to calculate the annual compound return

$$
R_{annual}=((\frac {B_{end}}{B_{start}})^{{Annual\ Days}/{Total\ Days}}-1)\cdot100
$$

- where B is the balance.
```
if end_balance >= 0:
    annual_return = ((end_balance / self.capital) ** (self.annual_days / total_days) - 1) * 100
else:
    annual_return = np.nan
```
### Current Method
- Does not account for compound interest
```
annual_return = total_return / total_days * self.annual_days
```

### Correct Method
$$
R_{daily}=((\frac {B_{end}}{B_{start}})^{1/{Total\ Days}}-1)\cdot 100
$$
```
if end_balance >= 0:
    daily_return = ((end_balance / self.capital) ** (1 / total_days) - 1) * 100
else:
    daily_return = np.nan
```
### Current Method
- In case balance goes to negative and back to positive, the daily return will be incorrect since the daily log return will be treated as 0.
```
daily_return = df["return"].mean() * 100
```

### Correct Method
$$
Sharpe\ Ratio=\frac {R_{annual}-R_{risk\ free, annual}}{\sigma_{daily\ return}\cdot \sqrt{Annual\ Days}}
$$
```
sharpe_ratio = np.divide((annual_return - self.risk_free), (return_std * np.sqrt(self.annual_days)))
```
### Current Method
- Incorrect daily risk-free rate formula
```
daily_risk_free = self.risk_free / np.sqrt(self.annual_days)
sharpe_ratio = (daily_return - daily_risk_free) / return_std * np.sqrt(self.annual_days)
```
### See Also
https://en.wikipedia.org/wiki/Sharpe_ratio

**Comment by qiyuexuezainanfang** [comment]
For the "Correct Method" you mentioned in the Daily return question, a check should be made when the balance is calculated. If there is a negative value, it means that there is a stock break, and the backtesting is meaningless. At this time, the log should be output and the backtesting should be terminated. If there is no negative, it means that there is no stock break, then "return" will not become a NaN. "return_std=df [" return "]. dropna(). std() * 100" should be replaced by "return_std=df [" return "]. std() * 100". In the source code of vnpy, "df [" return "]=np.log (x). fillna (0)" is incorrect, because the first "pre_balance" is NaN, the "return" on the first day will become 0.

**Comment by Myusico** [comment]
> For the "Correct Method" you mentioned in the Daily return question, a check should be made when the balance is calculated. If there is a negative value, it means that there is a stock break, and the backtesting is meaningless. At this time, the log should be output and the backtesting should be terminated. If there is no negative, it means that there is no stock break, then "return" will not become a NaN. "return_std=df [" return "]. dropna(). std() * 100" should be replaced by "return_std=df [" return "]. std() * 100". In the source code of vnpy, "df [" return "]=np.log (x). fillna (0)" is incorrect, because the first "pre_balance" is NaN, the "return" on the first day will become 0.

**Comment by Myusico** [comment]
> For the "Correct Method" you mentioned in the Daily return question, a check should be made when the balance is calculated. If there is a negative value, it means that there is a stock break, and the backtesting is meaningless. At this time, the log should be output and the backtesting should be terminated. If there is no negative, it means that there is no stock break, then "return" will not become a NaN.

Currently, termination at a negative balance is not implemented in VNPY. The suggestion I provided is a temporary workaround.

**Comment by vnpy** [comment]
已经添加vnpy_ctastrategy对于回测过程中资金爆仓（小于等于0）情况的检查
