### ISSUE TITLE
修复了直达端口，并略作修改使LME行情获取可用

### ISSUE THREAD

**Issue by xyddly** [vnpy/vnpy#330]
改了一下1.6.1里面直达的接口，现在可以用了。同时改了部分代码，使LME行情获取可用了。

**Comment by xyddly** [comment]
怎么上传zip格式的附件啊……

**Comment by xyddly** [comment]
in shzdGateway.py:
# 交易所类型映射
exchangeMap = {}
#exchangeMap[EXCHANGE_CFFEX] = 'CFFEX'
#exchangeMap[EXCHANGE_SHFE] = 'SHFE'
#exchangeMap[EXCHANGE_CZCE] = 'CZCE'
#exchangeMap[EXCHANGE_DCE] = 'DCE'
exchangeMap[EXCHANGE_HKEX] = 'HKEX'
exchangeMap[EXCHANGE_CME] = 'CME'
exchangeMap[EXCHANGE_ICE] = 'ICE'
**exchangeMap[EXCHANGE_LME] = 'LME'**
exchangeMapReverse = {v:k for k,v in exchangeMap.items()}

def onMarketData(self, data):

        tick.volume = int(data['513'])
        print data
        **if data['306'] == 'LME':
            tick.openInterest = 0
        else:
            tick.openInterest = int(data['514'])**


in uiBasicWidget.py:
    exchangeList = [EXCHANGE_NONE,
                    EXCHANGE_CFFEX,
                    EXCHANGE_SHFE,
                    EXCHANGE_DCE,
                    EXCHANGE_CZCE,
                    EXCHANGE_SSE,
                    EXCHANGE_SZSE,
                    EXCHANGE_SGE,
                    EXCHANGE_HKEX,
                    EXCHANGE_HKFE,
                    EXCHANGE_SMART,
                    EXCHANGE_ICE,
                    **EXCHANGE_LME,**
                    EXCHANGE_CME,
                    EXCHANGE_NYMEX,
                    EXCHANGE_GLOBEX,
                    EXCHANGE_IDEALPRO]


in \language\chinese\constant.py:
# 交易所类型
EXCHANGE_CME = 'CME'           # CME交易所
**EXCHANGE_LME = 'LME'           # LME交易所**
EXCHANGE_ICE = 'ICE'           # ICE交易所


in \language\english\constant.py:
# 交易所类型
EXCHANGE_CME = 'CME'           # CME交易所
**EXCHANGE_LME = 'LME'           # LME交易所**
EXCHANGE_ICE = 'ICE'           # ICE交易所

**Comment by vnpy** [comment]
可以开一个PR来请求合并的，或者回头我来手动修改

**Comment by xyddly** [comment]
我下周有时间，我来弄吧。

**Comment by vnpy** [comment]
已处理
