### ISSUE TITLE
是否考虑适配 AKShare 数据？

### ISSUE THREAD

**Issue by luneice** [vnpy/vnpy#3300]
[AKShare项目地址](https://github.com/akfamily/akshare) 里面有很多数据，[具体数据在这里可以看到](https://www.akshare.xyz/tutorial.html#id1)。

**Comment by vnpy** [comment]
之前有考虑，但是VeighNa最主要需求的期货日内分钟线级别数据，AkShare上还没有提供的，因此暂时无法支持了
