### ISSUE TITLE
unresolved issues

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3302]
|              | 仓库                  | Issue | Add                                                          | Mod                                        | Fix                                                          |
| ------------ | --------------------- | ----- | ------------------------------------------------------------ | ------------------------------------------ | ------------------------------------------------------------ |
| WANGYE-2012  | vnpy                  | 3186  | 增加gateway状态机                                            |                                            |                                                              |
| adriancobb   | vnpy_ctastrategy      | 15    | 增加【查找策略】按钮                                         |                                            |                                                              |
| yhmickey     | vnpy_arctic           | 16    | 增加get_tick_overview支持                                    |                                            |                                                              |
| yhmickey     | vnpy_datamanager      | 3     | 可视化界面增加按交易所分类的可折叠功能，且可以按交易所删除数据 |                                            |                                                              |                                                          |
| vnpy         | vnpy_spreadtrading    | 1     | 图形界面增加修改价差策略变量的对话框                         |                                            |                                                              |
| vnpy         | vnpy_spreadtrding     | 2     | 增加主动腿和被动腿因为比例差，无法完全对冲时，被动腿的特殊追平逻辑 |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
| stone3536    | vnpy                  | 3060  |                                                              | K线图分钟级别更新                          |                                                              |
| stone3536    | vnpy                  | 3099  |                                                              | K线图窗口提示修改成弹窗方式                |                                                              |
| stone3536    | vnpy                  | 3106  |                                                              | K线图十字光标、价格更新修改                |                                                              |
| vnpy         | vnpy                  | 3281  |                                                              | 使用zoneinfo替换pytz库                     |                                                              |
| vnpy         | vnpy_portfoliomanager | 6     |                                                              | 优化结算机制，适配中国期货市场的交易日规则 |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
| andyxk3      | vnpy_tora             | PR9   |                                                              |                                            | 修改获取字段VolumeMultiple为UnderlyingMultiple前50etf合约乘数为1，修改后为10000 |
| SimpleRealDT | vnpy_ifind            | 3     |                                                              |                                            | 生成iFinD合约名称没有大写，交易所映射缺少INE                 |
| synote       | vnpy                  | 3299  |                                                              |                                            | 修改daily_return/max_drawndown_duration/annual_return/daily_return/sharp_ration的计算方法 |
| hxxjava      | vnpy                  | 3270  |                                                              |                                            | BarGenerator生成n分钟bar的错误                               |
| cawind2      | vnpy_femas            | 4     |                                                              |                                            | 订阅合约不报错，收不到行情                                   |
| cawind2      | vnpy_femas            | 5     |                                                              |                                            | 无界面查不到持仓信息                                         |
| cawind2      | vnpy_femas            | 6     |                                                              |                                            | 底层报错导致界面看不见委托与持仓信息                         |
| Edanflame    | vnpy_webtrader        | 19    |                                                              |                                            | 进程未能及时销毁（多次启动并关闭webtrader后，后台进程无法及时杀死，导致当前端口被占用，更换接口才能运行） |
| Edanflame    | vnpy_portfoliostrategy | 7     |                                                              |                                            | BarGenrator重复推送问题（在实盘中可能会因为迟到的tick数据，导致在错误的时间额外推送一次k线数据） |
|              |                       |       |                                                              |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |
|              |                       |       |                                                              |                                            |                                                              |

**Comment by vnpy** [comment]
已经基本完成合并
