### ISSUE TITLE
vnpy_ctastrategy  TargetPosTemplate 小BUG 建议修改一下

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3312]
vnpy_ctastrategy   template  TargetPosTemplate   on_tick 里，
‘’‘’
if self.trading:
    self.trade() 
‘’‘’
这个语句没必要的哈，因为on tick里会self.calculate_target_pos()，所以这个ontick里继承的self.trade() 只会在策略刚开始启动时调用一次，且和self.calculate_target_pos()里边的 self.trade重复了，导致策略开启时会【撤单失败，找不到委托CTP.1_-1839978639_7】看起来比较别扭，建议官方修改一下

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_ctastrategy/pull/23
