### ISSUE TITLE
请教个计算期权希腊字母的问题

### ISSUE THREAD

**Issue by nankaimy** [vnpy/vnpy#3313]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

针对期权定价模块，原来的pricing 模块是数值解，最新的是解析解，但是计算以下参数的gamma 差别有点大，不知道是什么原因，感谢大家。

s=50
k=50
r=0.12
q=0.0
t=0.25
v=0.3
cp=1

matlab计算gamma结果为：0.05121，

最新pricing的是解析解
#-------------------------------------------------------------------------------
from scipy import stats
from math import log, pow, sqrt, exp
from typing import Tuple
cdf = stats.norm.cdf
pdf = stats.norm.pdf
def calculate_d1(
    s: float,
    k: float,
    r: float,
    t: float,
    v: float
) -> float:
    """Calculate option D1 value"""
    d1: float = (log(s / k) + (r + 0.5 * pow(v, 2)) * t) / (v * sqrt(t))
    return d1

def calculate_gamma(
    s: float,
    k: float,
    r: float,
    t: float,
    v: float,
    d1: float = 0.0
) -> float:
    """Calculate option gamma"""
    if v <= 0:
        return 0

    if not d1:
        d1: float = calculate_d1(s, k, r, t, v)

    _gamma: float = pdf(d1) / (s * v * sqrt(t))
    gamma: float = _gamma * pow(s, 2) * 0.0001

    return gamma
#------------------------------------------------------------------------------

calculate_gamma(s,k,r,t,v,)
Out[44]: 0.01280463051019016

原来pricing的是数值解
#------------------------------------------------------------------------------
from scipy import stats
from math import (log, pow, sqrt, exp)

cdf = stats.norm.cdf
# 计算希腊值和隐含波动率时用的参数
STEP_CHANGE = 0.001
STEP_UP = 1 + STEP_CHANGE
STEP_DOWN = 1 - STEP_CHANGE
STEP_DIFF = STEP_CHANGE * 2

DX_TARGET = 0.00001

def calculatePrice(s, k, r, t, v, cp):
    """计算期权价格"""
    # 如果波动率为0，则直接返回期权空间价值
    if v <= 0:
        return max(0, cp * (s - k))

    d1 = (log(s / k) + (r + 0.5 * pow(v, 2)) * t) / (v * sqrt(t))
    d2 = d1 - v * sqrt(t)
    price = cp * (s * cdf(cp * d1) - k * cdf(cp * d2) * exp(-r * t))
    return price

def calculateMPrice(s, k, r, t, v, q, cp):
    """计算期权价格,带股息率"""
    # 如果波动率为0，则直接返回期权空间价值
    if v <= 0:
        return max(0, cp * (s - k))

    d1 = (log(s / k) + (r -q + 0.5 * pow(v, 2)) * t) / (v * sqrt(t))
    d2 = d1 - v * sqrt(t)
    price = cp * (s * cdf(cp * d1)*exp(-q*t) - k * cdf(cp * d2) * exp(-r * t))
    return price

def calculateDelta(s, k, r, t, v, cp):
    """计算Delta值"""
    price1 = calculatePrice(s*STEP_UP, k, r, t, v, cp)
    price2 = calculatePrice(s*STEP_DOWN, k, r, t, v, cp)
    delta = (price1 - price2) / (s * STEP_DIFF) * (s * 0.01)
    return delta

def calculateGamma(s, k, r, t, v, cp):
    """计算Gamma值"""
    delta1 = calculateDelta(s*STEP_UP, k, r, t, v, cp)
    delta2 = calculateDelta(s*STEP_DOWN, k, r, t, v, cp)
    gamma = (delta1 - delta2) / (s * STEP_DIFF) * pow(s, 2) * 0.0001
    return gamma

calculateGamma(s, k, r, t, v, cp)
Out[46]: 0.007923080148275335

calculate_gamma(s,k,r,t,v,)
Out[44]: 0.01280463051019016

上面这两个结果差别有点大

**Comment by Edanflame** [comment]
因为vnpy中采用的现金希腊值，考虑了合约价值的因素，在calculateDelta中delta = (price1 - price2) / (s * STEP_DIFF)，获得的结果就和vnpy中一致了

**Comment by qiyuexuezainanfang** [comment]
matlab计算的是普通的gamma希腊值，在python中用数值方法得到了跟它一样的结果。vnpy提供的是现金希腊值，如果你也想计算这个，就在calculateDelta中delta = (price1 - price2) / (s * STEP_DIFF)，gamma函数不用改；如果你想计算普通的ganma希腊值，那两个函数都要改。
