### ISSUE TITLE
如何在策略中获得当日平仓盈亏率？

### ISSUE THREAD

**Issue by zengbotang** [vnpy/vnpy#332]

**Comment by zengbotang** [comment]
@vnpy 能拿到吗？

**Comment by jieyujing** [comment]
从维护的positionbuffer写函数拿不就得了

**Comment by zengbotang** [comment]
请问是在这文件vnpy\vn.trader\ctaStrategy\ctaEngine.py 里面的 class PositionBuffer(object): 添加方法吗？

**Comment by vnpy** [comment]
目前不支持这个功能，另外也不建议在实盘中使用类似的操作，今天的盈亏情况对于未来行情的判断是没有多少指导价值的。
