### ISSUE TITLE
可否通过环境变量指定strategies和.vntrader路径？

### ISSUE THREAD

**Issue by DennisXie** [vnpy/vnpy#3321]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
支持通过环境变量指定strategies和.vntrader路径，实现strategies和.vntrader文件夹不会被强制限制在一个目录下。

## 实际程序行为
目前仅能支持用户home目录和判断当前目录下是否有.vntrader文件夹来作为TRADER_DIR。strategies和.vntrader是强绑定在TRADER_DIR下的。在实际调试策略代码的时候，需要策略文件夹下面有个.vntrader目录，一手滑说不定就会把某些敏感数据提交到github上面。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 可以通过.gitignore文件限制git仓库跟踪的文件，杜绝错误提交的情况
2. 目前.vntrader和strategies文件夹强绑定的设计，是为了基于目录实现一个个独立的VeighNa Trader运行环境，保证多个VeighNa Trader进程运行时数据的安全隔离

综上暂时不会在开源版本中修改，如果有需求可以fork一份vnpy_ctastrategy目录进行针对性调整。
