### ISSUE TITLE
取消vnpy与talib的关联

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#3323]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: python3.7
* VeighNa版本: v3.2.0发行版

## Issue类型
Enhancement

## 建议：
pip install vnpy只包含main_engine、event_engine、各类gateway等基本功能，取消与talib的关联。
在linux下安装vnpy很麻烦，基于vnpy的event_engine和gateway写的一些行情运算，报警监控小程序之类的，其实用不到talib，为了pip install vnpy成功，还得先下载talib包编译之类的，很麻烦。
talib可以跟vnpy_ctastrategy之类的关联，或者单独搞个vnpy_core之类的安装包

**Comment by vnpy** [comment]
使用仓库中提供的install.sh脚本应该可以实现一键安装，请问具体遇到的问题是什么呢？

**Comment by eachout** [comment]
> 使用仓库中提供的install.sh脚本应该可以实现一键安装，请问具体遇到的问题是什么呢？

不行啊，还得先下载编译talib，要不然报错

**Comment by dehim** [comment]
我也遇过类似问题，在upgrade pip前，需要将ta-lib编译好，不然会报错，另外，VNPY提供的 https://pip.vnpy.com/colletion/ta-lib-0.4.0-src.tar.gz 编译时报mv: cannot stat '.deps/gen_code-gen_code.Tpo': No such file or directory，改用https://nchc.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 就顺利编译成功。

**Comment by thuzhf** [comment]
用conda直接安装试试呢：`conda install -c conda-forge ta-lib`

**Comment by vnpy** [comment]
目前已经在我们公司的PyPI源中提供wheel，可以直接通过下述命令安装：

`pip install ta-lib --index=https://pypi.vnpy.com`
