### ISSUE TITLE
datafeed数据下载时，无法快速定位错误位置

### ISSUE THREAD

**Issue by Edanflame** [vnpy/vnpy#3332]
## 环境

* 操作系统: Windows 11
* Python版本: VeighNa Studio-3.3.0
* VeighNa版本: v3.3.0发行版

## Issue类型
Enhancement

## 预期程序行为
当使用datafeed数据源下载数据时，可能会因为用户名密码错误、合约代码错误、不支持的数据周期等原因造成返回的数据量为1。

预期是程序应该能够通过打印或者日志等方式给出错误的原因。

## 实际程序行为

目前程序只会返回数量为0，无法通过返回的信息判断错误原因

**Comment by vnpy** [comment]
已经增加datafeed中的日志输出功能
