### ISSUE TITLE
最新版本无法微信扫码登录，注册时没有维护邮箱与密码；找回密码必须邮箱，无解了

### ISSUE THREAD

**Issue by CharlesSong** [vnpy/vnpy#3335]
最新版本无法微信扫码登录，注册时没有维护邮箱与密码；找回密码必须邮箱，无解了

**Comment by vnpy** [comment]
请在公众号[VeighNa开源量化]后台，提供您的注册时昵称和邮箱信息，以及新的要使用的邮箱，我们在后台看看能否找回匹配的记录

**Comment by CharlesSong** [comment]
您好，APP端的扫码登录能否恢复？

**Comment by CharlesSong** [comment]
> 请在公众号[VeighNa开源量化]后台，提供您的注册时昵称和邮箱信息，以及新的要使用的邮箱，我们在后台看看能否找回匹配的记录


您好，APP端的扫码登录能否恢复？
