### ISSUE TITLE
usedf=True报错 AttributeError: 'NoneType' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by zhouqi8892** [vnpy/vnpy#3336]
## 环境

* 操作系统: Windows 11
* Python版本: VeighNa Studio-3.3.0
* VeighNa版本: 3.3.0

## Issue类型
Bug

## 预期程序行为
usedf=True->
return pd.Dataframe

## 实际程序行为
return pd.Dataframe
由tickData类的datetime属性带有tzinfo造成
同时报错 AttributeError: 'NoneType' object has no attribute 'total_seconds'
## 重现步骤
![image](https://user-images.githubusercontent.com/58021599/186846109-f9d1a4c1-8d6d-4268-a963-b62388a16a3a.png)

https://github.com/pandas-dev/pandas/issues/43516
pandas库有人提交过类似bug，问题主要处在datetime.datetime 的tzinfo属性，带有该属性后转 pandas datetime会报错

**Comment by qiyuexuezainanfang** [comment]
升级一下pandas版本就好了，pip install --upgrade pandas==1.5.0
