### ISSUE TITLE
调试vtMain.py->ctpGateway->CTPTdApi类中sendOrder后，onRtnOrder与onRtnTrader没有回应！

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#334]
已经连接CTP,如下图：
http://pan.baidu.com/s/1kVcDmhp

CTPTdApi->sendOrder的调试，设置断点，如下图：
http://pan.baidu.com/s/1sloCnE1

在CTPTdApi->onRtnOrder()中设置断点，如下图：

http://pan.baidu.com/s/1qYnYs8W

在CTPTdApi->onRtnTrader()中设置断点，如下图：
http://pan.baidu.com/s/1i4Iy5LV

sendOrder已经成交
http://pan.baidu.com/s/1i4ZZxRn

但是onRtnOrder与onRtnTrader没有任何回应！！！

**Comment by vnpy** [comment]
vn.ctp等底层接口的回调函数，因为本质是由C++线程发起，因此在其中设置的断点无法为IDE捕捉，你可以试试print会有输出
