### ISSUE TITLE
用cython改写eventengine

### ISSUE THREAD

**Issue by jandykwan** [vnpy/vnpy#3340]
eventengine是整个框架的核心，大量的Event对象被创建，如果能用cython改写evnetengine， 框架的性能应该会有比较大的提升。

**Comment by vnpy** [comment]
EventEngine内部的性能瓶颈，主要在于跨线程通讯用队列Queue和多线程Thread来回切换的处理延时，在目前全局锁GIL存在的情况下，用Cython改进的空间不大，反而根据特定的场景进行事件分发的算法优化可能更有价值（去除不用的事件，调整派发处理逻辑等）。
