### ISSUE TITLE
mac 上测试过能装吗，各种问题。真是。。

### ISSUE THREAD

**Issue by heyonghan** [vnpy/vnpy#3341]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前M1/M2芯片的MAC上只能使用VeighNa的投研相关功能，交易接口可以运行纯Python的IB
