### ISSUE TITLE
数据库选型

### ISSUE THREAD

**Issue by Angel0726** [vnpy/vnpy#3343]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
Question
问一下postgreSQL也可以使用NoSQL（支持json、jsonb）格式，此外还有丰富的插件例如时间序列插件等。为什么使用MongDB不使用postgerSQL呢

**Comment by vnpy** [comment]
目前已经提供了对PostgreSQL的支持，如果追求性能可以使用其TimeScaleDB插件的方案

**Comment by Angel0726** [comment]
我知道提供了postgreSQL。我只是想问一下数据库选型问题
