### ISSUE TITLE
增加期货资管接口：杰伊斯接口

### ISSUE THREAD

**Issue by daidanbin** [vnpy/vnpy#3346]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请提供下该接口的相关资料和网址？

**Comment by daidanbin** [comment]
公司网址：https://www.jeesit.com/contact.html
注意事项：
1. 杰宜斯接口暂不强制认证，投顾认证流程可以保留，AppID和授权码可以暂时填空或保持原来设置
2. 杰宜斯接口只提供交易接口（对应ctp版本6.3.15），行情接口请自行连接期货公司ctp行情柜台前置
3. 模拟测试账户需要单独提交测试申请，如果需要连接实盘，请跟对应的系统管理方联系
4. linux接口的编译环境为gcc4.8.4
5. windows接口的编译环境为vc10.0
6. python目前只提供windows版本，编译环境为python3.7，C++转换python工具使用的是swigwin4.0
7. 接口报单时，OrderRef字段必须赋值，且要求每笔报单递增
8. 接口撤单时，推荐以FrontID+SeessionID+OrderRef 来报送撤单指令

**Comment by vnpy** [comment]
查了网站，似乎不像simnow直接有提供测试环境的申请，这块是否有合适的人（杰宜斯或者期货公司）可以对接下？

**Comment by vnpy** [comment]
好的，请添加vn_trader
