### ISSUE TITLE
TypeError: Can't instantiate abstract class SqliteDatabase with abstract methods get_tick_overview

### ISSUE THREAD

**Issue by cloudseasail** [vnpy/vnpy#3347]
## 环境

* 操作系统: Linux Deepin
* Python版本: Python 3.8.5
* VeighNa版本: VNPY 3.3.0

## Issue类型   Bug

```
Faile to import cython option pricing model, please rebuild with cython in cmd.
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    main()
  File "run.py", line 76, in main
    main_engine.add_app(CtaStrategyApp)
  File "/home/william/miniconda3/lib/python3.8/site-packages/vnpy/trader/engine.py", line 101, in add_app
    engine: BaseEngine = self.add_engine(app.engine_class)
  File "/home/william/miniconda3/lib/python3.8/site-packages/vnpy/trader/engine.py", line 72, in add_engine
    engine: BaseEngine = engine_class(self, self.event_engine)
  File "/home/william/miniconda3/lib/python3.8/site-packages/vnpy_ctastrategy/engine.py", line 110, in __init__
    self.database: BaseDatabase = get_database()
  File "/home/william/miniconda3/lib/python3.8/site-packages/vnpy/trader/database.py", line 158, in get_database
    database = module.Database()
TypeError: Can't instantiate abstract class SqliteDatabase with abstract methods get_tick_overview
```

## 重现步骤

`vnpy/examples/veighna_trader$ python run.py 
`

**Comment by vnpy** [comment]
请升级核心库到3.3.0版本接口

`pip install vnpy --upgrade`

**Comment by cloudseasail** [comment]
> 
Already upgraded to 3.3.0

`Requirement already satisfied: vnpy in /home/william/miniconda3/lib/python3.8/site-packages (3.3.0)
Requirement already satisfied: pyqtgraph in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (0.12.3)
Requirement already satisfied: ta-lib in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (0.4.24)
Requirement already satisfied: plotly in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (5.5.0)
Requirement already satisfied: qdarkstyle in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (3.0.3)
Requirement already satisfied: numpy in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (1.21.5)
Requirement already satisfied: pyzmq in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (22.3.0)
Requirement already satisfied: matplotlib in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (3.5.1)
Requirement already satisfied: pandas in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (1.3.5)
Requirement already satisfied: seaborn in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (0.11.2)
Requirement already satisfied: PySide6 in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (6.2.3)
Requirement already satisfied: tzlocal in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (4.2)
Requirement already satisfied: deap in /home/william/miniconda3/lib/python3.8/site-packages (from vnpy) (1.3.3)
Requirement already satisfied: pyparsing>=2.2.1 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (8.0.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (4.33.3)
Requirement already satisfied: packaging>=20.0 in /home/william/miniconda3/lib/python3.8/site-packages (from matplotlib->vnpy) (20.8)
Requirement already satisfied: pytz>=2017.3 in /home/william/miniconda3/lib/python3.8/site-packages (from pandas->vnpy) (2020.5)
Requirement already satisfied: tenacity>=6.2.0 in /home/william/miniconda3/lib/python3.8/site-packages (from plotly->vnpy) (8.0.1)
Requirement already satisfied: six in /home/william/miniconda3/lib/python3.8/site-packages (from plotly->vnpy) (1.15.0)
Requirement already satisfied: shiboken6==6.2.3 in /home/william/miniconda3/lib/python3.8/site-packages (from PySide6->vnpy) (6.2.3)
Requirement already satisfied: qtpy>=1.9 in /home/william/miniconda3/lib/python3.8/site-packages (from qdarkstyle->vnpy) (2.1.0)
Requirement already satisfied: scipy>=1.0 in /home/william/miniconda3/lib/python3.8/site-packages (from seaborn->vnpy) (1.5.4)
Requirement already satisfied: pytz-deprecation-shim in /home/william/miniconda3/lib/python3.8/site-packages (from tzlocal->vnpy) (0.1.0.post0)
Requirement already satisfied: backports.zoneinfo in /home/william/miniconda3/lib/python3.8/site-packages (from tzlocal->vnpy) (0.2.1)
Requirement already satisfied: tzdata in /home/william/miniconda3/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal->vnpy) (2022.1)
`

**Comment by cloudseasail** [comment]
更新vnpy_sqlite 之后解决了。
有没有脚本可以把这些vnpy插件一起更新？  因为实在太多了

**Comment by vnpy** [comment]
> 更新vnpy_sqlite 之后解决了。 有没有脚本可以把这些vnpy插件一起更新？ 因为实在太多了

VeighNa Studio中的Station提供了环境管理维护的功能，包括【一键更新】等
