### ISSUE TITLE
连接simnow账号失败

### ISSUE THREAD

**Issue by kennyoysj** [vnpy/vnpy#3350]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如vnpy 3.3.0 vn_ctp 6.5.1

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
从veighna station 启动ctp实盘连接simnow账号成功
从代码启动连接ctp成功

## 实际程序行为
从veighna station 启动ctp实盘连接simnow账号成功
从代码启动连接ctp实盘行情服务报错4040 CTP:API Front shake hand err: decode err
交易服务报错 4097
连接期货账号无问题(这里我用的是华泰)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/19526439/192959811-f2ef4638-e4cf-4d19-92b2-d12c0dbd09f7.png)

![image](https://user-images.githubusercontent.com/19526439/192959749-d58fab43-7a8f-4afa-bdca-a88d24f82cb8.png)

**Comment by vnpy** [comment]
现在最新CTP版本是6.6.7了，升级下吧：

`pip install vnpy_ctp --upgrade`

**Comment by kennyoysj** [comment]
升级到了6.6.7仍然不行仍然提示
2022-09-30 13:46:17,982  INFO: 行情接口报错，代码：4040，信息：CTP:API Front shake hand err: decode err
2022-09-30 13:46:19,884  INFO: 交易服务器连接断开，原因4097

**Comment by kennyoysj** [comment]
问题解决了CTPTEST_GATEWAY的提前引入会导致连接时使用的是ctptest而不是ctp
