### ISSUE TITLE
使用rq_data数据，cta_strategy的backtest漏掉一根K线

### ISSUE THREAD

**Issue by eachout** [vnpy/vnpy#3353]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 3.7
* VeighNa版本: v3.2.0

## Issue类型
三选一：Bug

## 程序行为
vnpy_ctastrategy/backtesting.py中的load_data在加载小时图k线时有时会漏掉一根：

298行：
            start = end + interval_delta
            end += progress_delta

INTERVAL_DELTA_MAP = {
    Interval.TICK: timedelta(milliseconds=1),
    Interval.MINUTE: timedelta(minutes=1),
    Interval.HOUR: timedelta(hours=1),
    Interval.DAILY: timedelta(days=1),
}

rq_data数据，期货夜盘数据有一根小时线是2：00-2：30的，回测时如果分段的结束点卡在2：00，下一个数据会从3：00开始加载，会漏掉2：30这根小时线。

**Comment by noranhe** [comment]
软件默认的加载时间点是0:00，目前国内期货应该还没有0:30的小时线，所以基于软件默认设置来加载是不会漏数据的。因为小时线也有15分、45分结尾的情况，对小时的timedelta也不方便进行统一修改。如果有选择特定加载时间点的需求，建议还是自己进行个性话修改了。
