### ISSUE TITLE
安装ctp接口报错

### ISSUE THREAD

**Issue by fishstoryyy** [vnpy/vnpy#3354]
## 环境

* 操作系统: 如Windows 10
* Python版本: 3.8
* VeighNa版本: 3.3.0

## Issue类型
Bug

## 预期程序行为
ctp接口顺利安装

## 实际程序行为
报错

## 重现步骤
1. 创建新环境
2. install.bat (成功)
3. pip install vnpy_ctp (报错)

![image](https://user-images.githubusercontent.com/44186562/194774570-f27f263c-6ea4-4bb9-9e02-5bff0d80ffb8.png)

**Comment by vnpy** [comment]
根据StackOverflow上这个帖子的内容：https://stackoverflow.com/questions/71295840/python-pip-error-legacy-install-failure

可能是Visual Studio编译环境的问题，建议重装试试看，注意安装时要勾选安装C++开发环境的选项，否则会缺失各种链接库。
