### ISSUE TITLE
MainEngine执行close的过程中无法输出日志

### ISSUE THREAD

**Issue by xinyundao** [vnpy/vnpy#3356]
## 环境

* 操作系统: 所有操作系统
* Python版本: 如VeighNa Studio-3.3.0
* VeighNa版本: 如v3.3.0发行版

## Issue类型
Enhancement

## 预期程序行为
在vnpy程序退出处理期间，期望能正常输出日志信息

## 实际程序行为
vnpy程序退出过程中无法输出日志

该问题由MainEngine.close()函数的退出流程引起，
因为日志的输出依赖Event Engine, 一旦close()函数停掉event engine之后，就无法再输出日志。  

  
```python
class MainEngine:
    """
    Acts as the core of the trading platform.
    """
...

    def write_log(self, msg: str, source: str = "") -> None:
        """
        Put log event with specific message.
        """
        log: LogData = LogData(msg=msg, gateway_name=source)
        event: Event = Event(EVENT_LOG, log)
        self.event_engine.put(event)

...
    def close(self) -> None:
        """
        Make sure every gateway and app is closed properly before
        programme exit.
        """
        # Stop event engine first to prevent new timer event.
        self.event_engine.stop()

        for engine in self.engines.values():
            engine.close()

        for gateway in self.gateways.values():
            gateway.close()
```

## 重现步骤
1. 无界模式下启动vnpy，
2. 关市后执行 main_engine.close()操作，
3. CTA策略无法打印退出期间的的日志

**Comment by siaosing** [comment]
可以在main_engine.close() 前打印下日志啊，
main_engine.write_log("bye bye")
time.sleep(10)
main_engine.close()

**Comment by xinyundao** [comment]
问题描述以及原理：
vnpy关闭流程如下图所示，关闭退出流程中的日志无法打印和输出。

```
总之在退出流程会调用到CTA策略的回调函数，回调函数中的日志信息无法打印输出。
CtaEngine数据保存过程的异常情况也无法记录日志。
```

![UML 图](https://user-images.githubusercontent.com/97147578/196084618-f2014e33-ade5-4475-9cfb-d16e5d3ac90c.jpg)

**Comment by xinyundao** [comment]
退出流程是否可以针对日志系统做特殊处理，在退出的最后一刻关闭日志，确保所有日志数据能够落盘存储。

**Comment by noranhe** [comment]
1.  可以考虑把退出时间稍微往后调几分钟，收盘后也没有新的回调回报了，这样应该能保证所有日志存储。
2.  如果怕收盘后不马上停止策略，策略实例会收到交易时段外的数据。也可以考虑在close之前先自行调用stop_all_strategy停止所有策略实例然后sleep一下再关闭。
