### ISSUE TITLE
又发现一个TargetPosTemplate的新问题

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3358]
一个tick收到后，单子发出了，如果下个tick收到的时候这笔单子还没到交易所，cancel_old_order时会撤单失败，因为交易所还没有返回“提交中”的委托汇报，但此时由于self.cancel_orderids有这笔单子了，所以再收到tick时无法继续撤单了，这笔单子会一直挂着，我的解决方案如下
![image](https://user-images.githubusercontent.com/55074597/196334292-5d77eaa7-a004-4df3-a232-8cf7ecb0bd82.png)
实盘验证过了没有问题

**Comment by vnpy** [comment]
1. TargetPosTemplate主要针对国内期货和证券极速柜台API设计
2. 此类柜台支持基于本地委托号（如CTP的OrderRef）机制进行撤单，无需等待交易所下行回报
3. 非此类规则的市场，可以根据自己需求参考TargetPosTemplate设计实现类似的策略模板
4. 目前VeighNa中的交易接口发送委托后，均会在本地推送一条状态为【提交中】的委托更新

**Comment by EzMoney-Sniper** [comment]
你们再好好想想我提的问题吧，这个就是CTP会遇到的问题，你本地虽然形成委托号了，但是这笔订单交易所还没来得及处理你就撤单了，交易所就会返回撤单失败，这笔单子也就会挂着无法再进行任何操作了

**Comment by EzMoney-Sniper** [comment]
你信我 我的这个版本绝对是对的，不然你就写个demo，on tick里每一个TICK都改变一次仓位，这次是1，下次是-1不断循环，你用simnow都能复现出我的问题

**Comment by EzMoney-Sniper** [comment]
这个问题和本地的那个提交中没有关系，主要是由于单子没到交易所的缘故

**Comment by vnpy** [comment]
请提供一个具体的报错截图或者日志信息？

**Comment by EzMoney-Sniper** [comment]
你撤的单子CTP还没收到，自然会显示撤单失败，然后这个单子就在cancel_orderids里边留存着，程序也就相当于暂停了啊

**Comment by EzMoney-Sniper** [comment]
也就是说你这个撤单失败的单子其实还没提交到交易所，达到交易所后如果成交了还好说，不成交的话就会一直挂在那儿

**Comment by EzMoney-Sniper** [comment]
因为它已经在cancel_orderids里了，程序不会对这个单子撤单了

**Comment by vnpy** [comment]
CTP柜台提供了撤单请求异步缓存逻辑：

1. 用户报单
2. 用户撤单
3. 柜台收到撤单请求时，尚未收到交易所报单回报，此时CTP柜台会缓存该请求
4. 柜台收到交易所报单回报，会触发立即发出撤单请求
5. 完成撤单功能

以上逻辑在CTP官方资料中有说明，如果确实发现问题欢迎提供截图信息来帮助定位具体问题。

**Comment by EzMoney-Sniper** [comment]
我实测下来这个撤单请求异步缓存逻辑是不存在的，我修改后这个问题是再也没遇见过的

**Comment by EzMoney-Sniper** [comment]
这个问题在sn fu等品种都遇到过
