### ISSUE TITLE
vnpy_spreadtrading 回测模块BUG

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3359]
逐日盯市结算价格应该是bar.value而不是bar.close_price
![image](https://user-images.githubusercontent.com/55074597/196609634-3003965c-f8b0-4dba-a9e1-09478c7b7e5f.png)
![image](https://user-images.githubusercontent.com/55074597/196609666-d619cdef-9b87-4368-89e3-f66a244f412e.png)

**Comment by EzMoney-Sniper** [comment]
两张图片，改这两个地方

**Comment by noranhe** [comment]
这个地方没有写错的

**Comment by EzMoney-Sniper** [comment]
> 

交易的怎么可能是价差，肯定是自定义合约的价值啊，比如说你根据IF-IC的价差做交易，但是实际上只交易IF这一个合约，肯定得用我这个版本做回测才准确
