### ISSUE TITLE
ubuntu 编译lts失败

### ISSUE THREAD

**Issue by zsluedem** [vnpy/vnpy#336]
进入 vnpy/vn.api/vn.lts
运行一下指令：
mkdir build
cd build
cmake ..
make VERBOSE=1 -j 1
报下面错误
/usr/bin/cmake -H/work/finance/vn/vnpy/vn.api/vn.lts -B/work/finance/vn/vnpy/vn.api/vn.lts/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles /work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
make -f CMakeFiles/vnltsmd.dir/build.make CMakeFiles/vnltsmd.dir/depend
make[2]: Entering directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
cd /work/finance/vn/vnpy/vn.api/vn.lts/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /work/finance/vn/vnpy/vn.api/vn.lts /work/finance/vn/vnpy/vn.api/vn.lts /work/finance/vn/vnpy/vn.api/vn.lts/build /work/finance/vn/vnpy/vn.api/vn.lts/build /work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/vnltsmd.dir/DependInfo.cmake --color=
Dependee "/work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/vnltsmd.dir/DependInfo.cmake" is newer than depender "/work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/vnltsmd.dir/depend.internal".
Dependee "/work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/work/finance/vn/vnpy/vn.api/vn.lts/build/CMakeFiles/vnltsmd.dir/depend.internal".
Scanning dependencies of target vnltsmd
make[2]: Leaving directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
make -f CMakeFiles/vnltsmd.dir/build.make CMakeFiles/vnltsmd.dir/build
make[2]: Entering directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
make[2]: Warning: File 'CMakeFiles/vnltsmd.dir/depend.make' has modification time 0.69 s in the future
[ 16%] Building CXX object CMakeFiles/vnltsmd.dir/vnltsmd/vnltsmd/vnltsmd.cpp.o
/usr/bin/c++   -DBUILD_LTS_MD -DBUILD_LTS_QRY -DBUILD_LTS_TD -DUSE_64BITS -Dvnltsmd_EXPORTS -I/work/finance/vn/vnpy/vn.api/vn.lts/ltsapi -I/work/finance/vn/vnpy/vn.api/vn.lts/LTS_MD_PATH -I/work/finance/vn/vnpy/vn.api/vn.lts/LTS_TD_PATH -I/work/finance/vn/vnpy/vn.api/vn.lts/LTS_QRY_PATH -I/usr/include/python2.7  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/vnltsmd.dir/vnltsmd/vnltsmd/vnltsmd.cpp.o -c /work/finance/vn/vnpy/vn.api/vn.lts/vnltsmd/vnltsmd/vnltsmd.cpp
[ 33%] Linking CXX shared library lib/vnltsmd.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/vnltsmd.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC  -fPIC -std=c++11 -O3 -DNDEBUG  -shared -Wl,-soname,vnltsmd.so -o lib/vnltsmd.so CMakeFiles/vnltsmd.dir/vnltsmd/vnltsmd/vnltsmd.cpp.o  -L/work/finance/vn/vnpy/vn.api/vn.lts/ltsapi -lboost_python -lboost_thread -lboost_date_time -lboost_system -lboost_chrono -lboost_atomic -lpthread -lpython2.7 -lsecuritymduserapi -Wl,-rpath,/work/finance/vn/vnpy/vn.api/vn.lts/ltsapi
/usr/bin/ld:/work/finance/vn/vnpy/vn.api/vn.lts/ltsapi/libsecuritymduserapi.so: file format not recognized; treating as linker script
/usr/bin/ld:/work/finance/vn/vnpy/vn.api/vn.lts/ltsapi/libsecuritymduserapi.so:1: syntax error
collect2: error: ld returned 1 exit status
CMakeFiles/vnltsmd.dir/build.make:103: recipe for target 'lib/vnltsmd.so' failed
make[2]: *** [lib/vnltsmd.so] Error 1
make[2]: Leaving directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vnltsmd.dir/all' failed
make[1]: *** [CMakeFiles/vnltsmd.dir/all] Error 2
make[1]: Leaving directory '/work/finance/vn/vnpy/vn.api/vn.lts/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

看起来是编译链接的错误,怎么解决

**Comment by vnpy** [comment]
试试直接用bash build.sh能否编译？

**Comment by zsluedem** [comment]
不可以啊～！报同样的错～！

**Comment by vnpy** [comment]
我这边测试了下，发现了同样的问题，应该是上次更新有东西出错了，会尽快修复

**Comment by vnpy** [comment]
找到问题所在了：v1.6.1的ltsapi目录下的三个lib开头的.so文件，可能因为之前同步的原因弄坏了，目前都是错误的。

删除三个lib开头的.so文件，然后将三个security开头的.so文件加上lib前缀（这三个文件是正常的），再执行编译即可。

**Comment by vnpy** [comment]
也将更新推送到了dev中

**Comment by zsluedem** [comment]
好的～！明白～！
