### ISSUE TITLE
算法交易AlgoTrading模块，触发弹窗提醒时有时程序会未响应

### ISSUE THREAD

**Issue by billzhaox** [vnpy/vnpy#3367]
## 环境

* 操作系统: 如Windows 10
* Python版本: Python 3.10
* VeighNa版本: v3.2.0

## Issue类型
三选一：Question

程序是基于vnpy3.2.0二次开发，算法交易模块运行过程中，有时触发弹窗提醒时GUI会立即变为未响应（不是所有时候都会未响应，复现条件还在排查中），如下图：

![微信图片_20221124021513](https://user-images.githubusercontent.com/39547378/203705114-a133dfaf-cb09-467a-bade-11b0b42f5588.png)

下面是algotrading/engine.py中send_order()函数中触发弹窗的相关代码，WarningDialog和源码中的AboutDialog基本类似，继承于QtWidgets.QDialog：

![微信图片_20221124174343](https://user-images.githubusercontent.com/39547378/203751894-839d8489-4b60-4a8b-86db-017853045e27.png)

单步调试了一下，未响应时的函数调用情况如下图：

![微信图片_20221124020800](https://user-images.githubusercontent.com/39547378/203705217-e21b641c-2b46-4208-9f5d-168d6916816a.png)

怀疑是调用模态对话框没有交还控制权，导致其他Event被阻塞，造成GUI卡死？求一个排查/解决思路

**Comment by vnpy** [comment]
1. 不能在事件引擎工作的后台线程中，直接对UI相关组件进行操作，否则会卡住或者崩溃
2. UI相关的代码，统一应该放在ui/widget.py之类的专用文件中，然后通过事件或者信号的方式来触发对应逻辑
