### ISSUE TITLE
ERROR 19 10268 不支持“EtradeOnly”委托单属性。

### ISSUE THREAD

**Issue by GJHLCX** [vnpy/vnpy#3368]
## 环境

* 操作系统: 如Mac
* Python版本: python 3.9
* VeighNa版本: 如v3.1.0发行版

## Issue类型
三选一：Bug

## 预期程序行为
使用盈透接口下单美股。之前能成功提交订单至盈透TWS

## 实际程序行为
11月20左右之后，在工作台提交委托订单后，未能盈透TWS没有委托订单。报错信息：ERROR 19 10268 不支持“EtradeOnly”委托单属性。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

ERROR 19 10268 不支持“EtradeOnly”委托单属性。

**Comment by vnpy** [comment]
已经在vnpy_ib仓库中修复：https://github.com/vnpy/vnpy_ib/issues/17

将在VeighNa的3.5.0版本中发布。
