### ISSUE TITLE
仿真环境下能否用rqdata实现行情推送代替接不同的交易接口？

### ISSUE THREAD

**Issue by MrGuann** [vnpy/vnpy#3371]
## 环境

* 操作系统: Windows 11
* Python版本: VeighNa Studio
* VeighNa版本: v3.4.0

## Issue类型
三选一：Enhancement

## 描述
如果交易品种较多，涉及期货、ETF期权、ETF时，需要接入不同的交易接口。如果只是模拟仿真阶段，暂未申请实盘接口，这时能否用rqdata的实时行情推送功能，以本地撮合形式进行模拟？如果是实盘阶段，能否用rqdata作为统一的实时数据源？

**Comment by vnpy** [comment]
已在vnpy_rqdata模块下添加，将在3.5.0中发布
