### ISSUE TITLE
请问策略编写时，回调函数 on_bar 传入的 BarData 对象如何增加新的一列或多列数据？

### ISSUE THREAD

**Issue by pfeak** [vnpy/vnpy#3372]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: Python-3.9.0 及以上
* VeighNa版本: v3.4.0 发行版

## Issue类型
Question

## 预期程序行为
请问策略编写时，回调函数 on_bar 传入的 BarData 对象如何增加新的一列或多列数据（这些数据可能是当天换手率，量比，资金流向等三方已提供的数据，每条数据 label 都有对应的时间与数值）？

如果无法通过已有功能实现，是否只需要修改 BarData 与数据库加载时对应迭代对象，为他们增加一列或几列字段？

## 实际程序行为
仅能获取当日 BarData 已定义基础信息（open_price、close_price、volume等）

**Comment by vnpy** [comment]
1. PortfolioStrategy模块的on_bars函数，就是多列传入的
2. 扩展字段可以通过BarData.extra字段来实现加载
3. 数据库中该extra字段可用json格式存储，载入后转换为字典，需要自行对数据库驱动进行扩展开发
