### ISSUE TITLE
DolphinDB 官方说下个月初会发布新版本API，支持Python 3.10

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3375]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Enhancement

## 重现步骤

DolphinDB 官方说下个月初会发布新版本API，支持Python 3.10

**Comment by vnpy** [comment]
可喜可贺，终于等来了

**Comment by vnpy** [comment]
这样我们争取在VeighNa的3.6版本中做下测试更新

**Comment by vnpy** [comment]
截止2023-2-12依旧没有发布，3.6版本来不及了，后续等DolphinDB团队发布了我们再跟进
