### ISSUE TITLE
融航实盘无法市价下单，市价指令融航无法识别

### ISSUE THREAD

**Issue by zhujun8000520** [vnpy/vnpy#3379]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VeighNa Studio-3.5
* VeighNa版本: v3.5.0发行版

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
使用vntrader程序市价下单，应当会立即成交

## 实际程序行为
使用vntrader发出市价指令会被拒单，价格为0.00，提示报单价格类型参数错误，
我用融航的客户端发出市价指令，价格为0.00，可以发送到柜台并成交，
![20230105132124](https://user-images.githubusercontent.com/106017978/210707408-58e59ab0-129c-4ed6-9f90-93b7dd001b53.png)

## 重现步骤
![}G_@ S_NU W{R8)}H~QAF76](https://user-images.githubusercontent.com/106017978/210705624-39d671f6-0f55-4746-bcff-fecf52d5a3d8.png)

**Comment by zhujun8000520** [comment]
第一张图中融航客户端下单的没有成交是还没到1点半开盘，正常会成交的。但使用vntrader市价无论如何都会被判定为参数错误拒单

**Comment by noranhe** [comment]
那就传大于0的价格试试就好，市价单不会按照传入的价格委托成交的
