### ISSUE TITLE
将MongoDB替换为其他时序数据库？

### ISSUE THREAD

**Issue by geraybos** [vnpy/vnpy#338]
有没有将MongoDB替换成为其他性能更好的时序数据库的考虑？例如OpenTSDB, InfluxDB等等？MongoDB结构松散，似乎在时序数据上支持得不太好。

**Comment by vnpy** [comment]
不好意思，暂时没有，原因如下：
1. MongoDB现阶段足以满足开发需求
2. MongoDB在用户数、资料、三方支持获取等方面优于以上数据库

没必要在尚未遇到瓶颈的时候去做提前优化。
