### ISSUE TITLE
3.5.0版本 IB接口 回测模块下载历史数据报错

### ISSUE THREAD

**Issue by liuyindyx** [vnpy/vnpy#3384]
Windows 11
VeighNa版本: v3.5.0发行版

## Issue类型
Bug
利用IB TW 接口，及CtaBacktester 模块，下载历史数据时
下载失败，程序报错。

Traceback (most recent call last):
  File "C:\Users\12\VeighNaStudio\lib\threading.py", line 1319, in invoke_excepthook
    hook(args)
TypeError: create_qapp.<locals>.threading_excepthook() missing 1 required positional argument: 'extra'

![Snipaste_2023-02-02_23-32-14](https://user-images.githubusercontent.com/16070387/216368504-e341b1f5-278a-4179-aa75-0cae2edd92a7.png)

**Comment by noranhe** [comment]
可参考https://github.com/vnpy/vnpy_ib/pull/19/files
