### ISSUE TITLE
Mac OS使用自动安装脚本安装失败

### ISSUE THREAD

**Issue by EasonPeachOolong** [vnpy/vnpy#3387]
## 环境

* 操作系统: Mac OS Ventura 13.1（基于Apple M1 Pro）
* Python版本: Python=3.9.16
* VeighNa版本: 暂无（The Unarchiver无法解压veighna_studio-3.5.0.exe)

## Issue类型
Bug

## 预期程序行为
成功运行自动安装脚本 成功安装依赖库

## 实际程序行为
安装numpy1.21.5 pyqtgraph0.12.4 PySide6_Essentials-6.4.2时失败 报错如下

## 重现步骤
通过代码安装 均在terminal中操作
1、成功为其创建虚拟环境并激活
conda create -n py39_vnpy python=3.9
conda activate py39_vnpy
2、成功从此处下载最新版release的zip文件 解压 放在合适的路径
https://github.com/vnpy/vnpy/archive/refs/tags/3.5.0.zip
3、成功进入文件目录
cd /Users/easonyang/vnpy-3.5.0
4、运行自动安装脚本
bash install_osx.sh
此步骤出现报错 全过程如下
<img width="1512" alt="截屏2023-02-11 10 45 08" src="https://user-images.githubusercontent.com/113883803/218235468-b8133518-3680-4594-84a5-bf1495c2ab9c.png">
<img width="1512" alt="截屏2023-02-11 10 45 28" src="https://user-images.githubusercontent.com/113883803/218235473-96970384-341b-4676-968b-6ea412b9f5c4.png">
<img width="1512" alt="截屏2023-02-11 10 45 46" src="https://user-images.githubusercontent.com/113883803/218235480-f8e3aa9b-3f89-4d3a-a2e3-27f356722cf8.png">
<img width="1512" alt="截屏2023-02-11 10 46 05" src="https://user-images.githubusercontent.com/113883803/218235488-d2036a48-088e-4ba2-9e1e-4ca4a36a829b.png">
<img width="1512" alt="截屏2023-02-11 10 46 17" src="https://user-images.githubusercontent.com/113883803/218235492-1d431bb5-0352-417b-9101-a75b41791407.png">
<img width="1512" alt="截屏2023-02-11 10 46 31" src="https://user-images.githubusercontent.com/113883803/218235498-7b87eff3-5727-4ee0-a810-88f085e0ba02.png">
<img width="1512" alt="截屏2023-02-11 10 46 42" src="https://user-images.githubusercontent.com/113883803/218235504-911c7498-40a7-4dcd-9c6f-006abb33dea8.png">
<img width="1512" alt="截屏2023-02-11 10 46 55" src="https://user-images.githubusercontent.com/113883803/218235508-320cc54d-c32d-4895-90a9-9d5480f25f32.png">
<img width="1512" alt="截屏2023-02-11 10 47 10" src="https://user-images.githubusercontent.com/113883803/218235509-41f7b155-e715-407f-b979-60f589ff1c51.png">
<img width="1512" alt="截屏2023-02-11 10 47 51" src="https://user-images.githubusercontent.com/113883803/218235522-79613a65-b313-48f2-9ae0-5a136054e9a2.png">
<img width="1512" alt="截屏2023-02-11 10 48 02" src="https://user-images.githubusercontent.com/113883803/218235525-e43f6c26-e324-4811-9e1a-4562c645e9d3.png">
<img width="1512" alt="截屏2023-02-11 10 48 31" src="https://user-images.githubusercontent.com/113883803/218235536-e0136b50-4967-4ece-a312-e97b925d062c.png">
<img width="1512" alt="截屏2023-02-11 10 49 18" src="https://user-images.githubusercontent.com/113883803/218235542-72bd48a4-20cf-4858-af2a-c2189667f7ab.png">
<img width="1208" alt="截屏2023-02-11 10 54 36" src="https://user-images.githubusercontent.com/113883803/218235546-ee80efd7-4128-4895-bd03-9a94f6c03355.png">

顺便礼貌求问为什么The Unarchiver无法解压 下载地址已附
https://download.vnpy.com/veighna_studio-3.5.0.exe
The Unarchiver已开启解压exe文件的选项

**Comment by vnpy** [comment]
截图中报错的主要原因，是由于国内到PyPI官方源的网络不稳定，不是安装脚本本身的问题了。

解决方法可以配置使用豆瓣源等国内PyPI镜像，在pip命令后加参数：

`--index=https://pypi.douban.com/simple`

veighna_studio-3.5.0.exe是基于安装打包工具打包的Windows系统安装程序，不是自解压文件。
