### ISSUE TITLE
关于把所有OMS业务数据（非行情）例如成交、委托订单转入到数据库database的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3388]
### 如下链接，张国平老师发表于论坛的《利用保存的成交订单，生成实盘交易分析报表》已经实现，这个功能很实用很实在，望陈老师与VeighNa采纳
https://www.vnpy.com/forum/topic/31103-li-yong-bao-cun-de-cheng-jiao-ding-dan-sheng-cheng-shi-pan-jiao-yi-fen-xi-bao-biao
https://www.vnpy.com/forum/topic/31133-shi-yong-metabasezuo-fen-xi-bao-biao-gong-ju-fen-xi-zheng-ti-ce-lue-ji-xiao?page=1#pid57630

**Comment by vnpy** [comment]
VeighNa核心定位于交易平台，历史绩效分析这块更多属于资管系统或者后端系统的功能。

因此不考虑在VeighNa中支持，如果确实有需求可以自行将Order/Trade等数据导出到数据库中实现。
