### ISSUE TITLE
添加基金数据支持

### ISSUE THREAD

**Issue by cygnusyang** [vnpy/vnpy#3389]
## 环境

* 操作系统: Windows 11、 Ubuntu 20.04、 MACOS
* Python版本: v3.9
* VeighNa版本: 如VeighNa Studio-3.5.0

## Issue类型
Enhancement

## 预期程序行为
一期：框架能下载、更新、删除基金数据，并有UI展示。
二期：可以根据下载的数据做分析

## 实际程序行为
可以通过run.py中启动一个新的APP，添加一个类似datamanager的类。需要考虑是否可以在datamanager类上扩展，但是基金数据结构与bar数据都不一样。同时需要适配database，及数据通道的各个类（如tushare).

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
如果是交易所场内的基金（LOF、ETF等）的量价数据，那么直接可以通过RQData等数据服务下载（需要购买对应数据权限），无需另外做扩展。
