### ISSUE TITLE
出现KeyError，但不知道问题在哪

### ISSUE THREAD

**Issue by damaicheng** [vnpy/vnpy#3390]
## 环境

* 操作系统: 如Windows Server 2012 R2 Datacenter
* Python版本:   python 3.10.9
* VeighNa版本: v3.5.0
![image](https://user-images.githubusercontent.com/53368605/218363823-be16d761-a79b-43ad-90df-f68f0937216f.png)

## Issue类型
三选一：Question

## 实际程序行为
终端在我找问题时重启了，保存的记录如下
![image](https://user-images.githubusercontent.com/53368605/218364164-064d5e03-6c0e-43c6-b4ec-364988790d5e.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已经修复：https://github.com/vnpy/vnpy_portfoliostrategy/commit/bc5dbbf3eab247d0adf97dd99ba88bd96d181636

**Comment by damaicheng** [comment]
你好，使用修复后的vnpy_portfoliostrategy,
加载组合策略出现异常1，
![image](https://user-images.githubusercontent.com/53368605/218627276-f1676708-294c-4ed7-bd1b-3205ffb13967.png)

我直接把self.write_log删除了，删除后能加载，但是组合策略始终无法初始化完成
