### ISSUE TITLE
你好，修复后的vnpy_portfoliostrategy冲突

### ISSUE THREAD

**Issue by damaicheng** [vnpy/vnpy#3392]
你好，使用修复后的vnpy_portfoliostrategy,
加载组合策略出现异常1，
![image](https://user-images.githubusercontent.com/53368605/218627276-f1676708-294c-4ed7-bd1b-3205ffb13967.png)

我直接把self.write_log删除了，
**删除后能加载，但是组合策略始终无法初始化完成**

_Originally posted by @damaicheng in https://github.com/vnpy/vnpy/issues/3390#issuecomment-1429036563_

**Comment by vnpy** [comment]
已经重新在master分支提供了一个临时的3.5.0兼容版本。
