### ISSUE TITLE
请教连接binance的问题，vnpy程序定期跑一段时间就会卡死 

### ISSUE THREAD

**Issue by speedfengjun** [vnpy/vnpy#3399]
目前用cta_strategy在跑150个策略，出错卡死的情况下，无法stop策略，但是主界面pyqt可以点出“退出确认”框，无错误日志输出（其他正常错误日志可正常输出），所有订阅的品种TICK无跳动，由于没有错误日志输出无法定位是本地问题还是与binance连接的问题

请教别人，说主要是binance断开问题，需要自己优化代码，加上ws断开后重连机制，请教应该如何实现？
还有这类线程死掉的情况下，如何排障呢？不知道怎么troubeshooting，请支撑，谢谢。

目前迁移到最新版的，还是有这个问题

**Comment by vnpy** [comment]
相关项目已交接给：https://github.com/vn-crypto

请去这里求助吧：https://github.com/vn-crypto/vnpy_crypto
