### ISSUE TITLE
debian 8 LANG为zh_CN.UTF-8，safeUnicode报错：UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by lhzw** [vnpy/vnpy#34]
当我使用zh_CN.UTF-8作为默认语言时。那个safeUnicode方法会报错：
n: 0, header: logTime
Traceback (most recent call last):
  File "/home/szc/github/vnpy/vn.trader/uiBasicWidget.py", line 243, in updateEvent
    self.updateData(data)
  File "/home/szc/github/vnpy/vn.trader/uiBasicWidget.py", line 288, in updateData
    content = safeUnicode(data.__getattribute__(header))
  File "/home/szc/github/vnpy/vn.trader/vtFunction.py", line 26, in safeUnicode
    return unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 2: ordinal not in range(128)

我就把它注释掉了，然后qt界面日志处时间就是乱码了。使用英语作为默认语言，就可以正确显示数字日期，形如：23:12:20。请指点一二，谢谢！

**Comment by lhzw** [comment]
因为zh_CN.UTF-8作为默认语言时，获取到的时间串是这样的，"23时15分30秒"，就是utf8编码的了，我还没有找这个时间是在什么地方生成的。然后python的默认编码又是ascii码，解码不了，就报上面的错了：
n [16]: sys.getdefaultencoding()
Out[16]: 'ascii'

暂时解决办法，把这些字符串使用utf8进行decode()即可。
返回时间处，直接返回形如23:12:20就可以避免这样的问题了。但是safeUnicode()实际上也并不是很安全啊。

**Comment by vnpy** [comment]
主要因为vn.trader目前还只是在windows上开发，linux的移植工作2016年下半年会展开。

**Comment by ideaplat** [comment]
linux我这里是没有问题的。不过要改一些地方。

比如vtfunction里面加
`reload(sys)
sys.setdefaultencoding('utf8')`
