### ISSUE TITLE
量化回测

### ISSUE THREAD

**Issue by Tonykeng** [vnpy/vnpy#340]
搭建了vnpy，看到策略只支持CTA策略，请教下不知道做股票的回测支持不支持，改动大不大？

**Comment by vnpy** [comment]
vn.py的主要定位是量化交易这个环节，如果以Alpha类策略举例，vn.py解决的是每天策略生成的交易列表实盘中的算法执行任务，而不是每天收盘后的策略运行计算目标持仓的任务。
