### ISSUE TITLE
【windows install bug】

### ISSUE THREAD

**Issue by SnJForever** [vnpy/vnpy#3403]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如3.8.5
* VeighNa版本: 如v3.6.0

## Issue类型
三选一：Bug

## 预期程序行为
./install.bat

## 实际程序行为
 E:\workspace\vnpy-3.6.0> .\install.bat

E:\workspace\vnpy-3.6.0>python -m pip install --upgrade pip wheel 
Requirement already satisfied: pip in d:\program\python3\lib\site-packages (23.0.1)
Requirement already satisfied: wheel in d:\program\python3\lib\site-packages (0.38.4)

E:\workspace\vnpy-3.6.0>python -m pip install --extra-index-url http://139.196.190.180 --trusted-host 139.196.190.180 TA_Lib 
Looking in indexes: https://pypi.org/simple, http://139.196.190.180
Collecting TA_Lib
  Downloading TA-Lib-0.4.25.tar.gz (271 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.0/272.0 kB 9.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Downloading https://139.196.190.180/packages/numpy-1.24.2-cp38-cp38-win_amd64.whl (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 365.3 kB/s eta 0:00:00
Building wheels for collected packages: TA_Lib
  Building wheel for TA_Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for TA_Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\talib
      copying talib\abstract.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\deprecated.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\stream.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_abstract.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_data.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_func.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_pandas.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_polars.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\test_stream.py -> build\lib.win-amd64-cpython-38\talib
      copying talib\__init__.py -> build\lib.win-amd64-cpython-38\talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\talib
      "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -IC:\Users\Administrator\AppData\Local\Temp\pip-build-env-2ez2ev96\normal\Lib\site-packages\numpy\core\include -ID:\program\python3\include -ID:\program\python3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program 
Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-cpython-38\Release\talib/_ta_lib.obj        
      _ta_lib.c
      talib/_ta_lib.c(745): fatal error C1083: 无法打开包括文件: “ta_libc.h”: No such file or directory
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2       
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA_Lib
Failed to build TA_Lib
ERROR: Could not build wheels for TA_Lib, which is required to install pyproject.toml-based projects

## 重现步骤
![image](https://user-images.githubusercontent.com/31909226/222106471-37f44ddd-f49d-4629-abbd-cf7d52e42d93.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by SnJForever** [comment]
远程资源没有0.4.25版本
![image](https://user-images.githubusercontent.com/31909226/222106818-1fdd7ef6-8594-4a71-ad24-600b54c9bf1e.png)

![image](https://user-images.githubusercontent.com/31909226/222106611-16a1998b-2b09-42e4-9b0e-139748763423.png)

**Comment by vnpy** [comment]
感谢反馈，我们来更新下install.bat脚本

**Comment by eachout** [comment]
建议再精简一个核心版本，去除BarGenerator以及talib、还有各种ui如pySide，只保留event, rpc, trader（去掉BarGenerator），这样可以很方便的使用vnpy和它丰富的gateway资源写出很多不需要K线和界面的程序，比如订单监控，指数合成，rqdata、ctp、股票数据监控，实时数据校对入库之类的轻型后台服务程序

**Comment by PinkPanther-ny** [comment]
D:\Deepblue\vnpy-3.6.0>python -m pip install --extra-index-url http://139.196.190.180/packages --trusted-host 139.196.190.180 TA_Lib==0.4.24
Looking in indexes: https://pypi.org/simple, http://139.196.190.180/packages
Collecting TA_Lib==0.4.24
  Downloading TA-Lib-0.4.24.tar.gz (269 kB)
     ---------------------------------------- 269.4/269.4 kB 345.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy (from TA_Lib==0.4.24)
  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)
Building wheels for collected packages: TA_Lib
  Building wheel for TA_Lib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      C:\Users\alvin\AppData\Local\Temp\pip-install-h9xqw7gg\ta-lib_9d6650fd3e9b4a1783f70a4c3adbd17d\setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
        warnings.warn('Cannot find ta-lib library, installation may fail.')
      C:\Python311\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\talib
      copying talib\abstract.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\deprecated.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\stream.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_abstract.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_data.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_func.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_pandas.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_polars.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_stream.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\__init__.py -> build\lib.win-amd64-cpython-311\talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\talib
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -Ic:\users\alvin\appdata\local\temp\pip-install-h9xqw7gg\ta-lib_9d6650fd3e9b4a1783f70a4c3adbd17d\.eggs\numpy-1.24.2-py3.11-win-amd64.egg\numpy\core\include -IC:\Python311\include -IC:\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-cpython-311\Release\talib/_ta_lib.obj
      _ta_lib.c
      talib/_ta_lib.c(680): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA_Lib
  Running setup.py clean for TA_Lib
Failed to build TA_Lib
ERROR: Could not build wheels for TA_Lib, which is required to install pyproject.toml-based projects

> 远程资源没有0.4.25版本，指定0.4.24安装成功 ![image](https://user-images.githubusercontent.com/31909226/222106818-1fdd7ef6-8594-4a71-ad24-600b54c9bf1e.png)
> 
> ![image](https://user-images.githubusercontent.com/31909226/222107086-b4da7d86-a5e4-4f3a-9859-29de4ece0eac.png)

**Comment by Big-Mizu** [comment]
现在依然存在这个严重的问题。talib导致整个vnpy安装不成功。安装talib的时候总是出问题。

**Comment by happyTonakai** [comment]
> 现在依然存在这个严重的问题。talib导致整个vnpy安装不成功。安装talib的时候总是出问题。

使用最新的`install.bat`成功安装
