### ISSUE TITLE
多合约组合策略在成交后，pos或pos_data的持仓数据没有改变

### ISSUE THREAD

**Issue by holmhe** [vnpy/vnpy#3406]
## 环境

* 操作系统: Windows 10
* Python版本: vn studio自带的python
* VeighNa版本: VeighNa Studio-2.9.0 和最新的3.6

## Issue类型
三选一：Bug or Question

## 重现步骤
在vn trader的界面程序里，使用多合约组合策略的模块，使用buy,sell等函数下单，下单能实际成交，但pos或pos_data没自动更新

## 预期程序行为
pos应该和cta策略模块一样，会自动根据成交来更新持仓，查阅一些文档也没发现有什么需要注意。在最新的3.6版本，pos在多合约策略中变成了pos_data,按照例子使用set target，target是能改变，但也影响不了pos_data(也就是pos)的变化

## 实际程序行为
使用下单或平仓函数可以，但持仓pos数据没有根据成交来改变，这是在2.9和3.6版本中的多合约策略都出现，与之对应，cta策略就会自动改变pos

**Comment by noranhe** [comment]
请问你的vnpy_portfoliostrategy版本是？方便的话能否提供成交后pos_data不变的截图？正常情况下，engine收到process_trade_event函数的推送时会找到成交信息上委托号对应的策略实例调用update_trade函数更新策略实例的pos_data的
