### ISSUE TITLE
自成交导致trade信息不更新仓位紊乱问题

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3407]
vnpy_ctastrategy-engine-process_trade_event 函数里的语句if trade.vt_tradeid in self.vt_tradeids:
    return在自成交时会导致第二个成交信息收不到仓位紊乱，建议修改

**Comment by EzMoney-Sniper** [comment]
国内期货会遇到这个问题

**Comment by vnpy** [comment]
自成交在实盘中是交易所禁止的违规行为，建议加载RiskManager事前风控模块进行相关拦截，这里不考虑在VeighNa中修改了。
