### ISSUE TITLE
连接rpc的接口，获取的positionid中的接口还是源接口，这样导致如果同时连接rpc（源接口也是ctp）和ctp的话，仓位无法区分

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#3408]
看图就知道了。
自己在本地改倒是容易，官方衡量一下，看看rpc服务在推送positionData的时候，是否有必要更改positionid的gateway_name

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/8924839/225841772-4487ea7e-2317-4304-9277-4fc4854abcba.png)

**Comment by vnpy** [comment]
感谢反馈，下个版本修复

**Comment by vnpy** [comment]
已修复
