### ISSUE TITLE
RPC模式Mac上能运行vtClient客户端么？

### ISSUE THREAD

**Issue by summerxiaomi** [vnpy/vnpy#341]
如题，提示没有找到 .so文件

**Comment by vnpy** [comment]
可以，但是你的vtServer必须跑在Linux或者Windows的机器上（虚拟机也行）。

最近更新v1.6.2项目结构有所调整，vtClient和vtServer回头会在v1.8里重新实现，将所有的appEngine都移动到服务端，客户端仅负责GUI控制。

**Comment by summerxiaomi** [comment]
thx
