### ISSUE TITLE
[Enhancement] 建议策略里增加统一的事件回调

### ISSUE THREAD

**Issue by kkqy** [vnpy/vnpy#3411]
## 环境

* 操作系统: Windows 10
* Python版本: 3.10.10
* VeighNa版本: v3.6.0

## Issue类型
Enhancement

## 预期程序行为
希望在[PortfolioStrategy](https://www.vnpy.com/docs/cn/portfolio_strategy.html)、[CtaStrategy](https://www.vnpy.com/docs/cn/cta_strategy.html)等策略模板里增加网关事件回报的回调。

例如，
1. 接口断开通知（我看已经在In Plan状态 https://github.com/vnpy/vnpy/issues/3234 )，目前策略无法处理这种通信故障的问题，即便策略无法发起重连，至少我可以发送邮件或者短信提醒，但现在是啥也不知道。所以策略跑起来还提心吊胆的，就失去托管的意义了。

2. CTP的交易接口会接收到合约的交易状态更新通知，比如竞价、连续交易、停盘等，这些信息对于自定义的K线合成非常重要。
比如我要合成固定交易间隔的K线，论坛上的办法都是通过增加一个minute计数器来实现，但这种实现方法是很不稳定的，因为tick不是连续的，交易接口也没有保证一分钟内一定有一个tick，对于CTP接口而言，只会在”固定间隔“和”发生变动“同时满足的时候才会发送新的tick，如果一个品种长期没交易，那它的tick推送就会很慢。
再比如有的交易所停盘的最后一个tick不会发送，导致最后一根k线无法生成。如果能接收到停盘消息，我就可以强行生成最后一根线了。
再比如，竞价阶段的报价我可能并不关心，但是现在我区分不了哪些tick是什么阶段的tick，对于k线合成也有干扰，会合成8:59、20:59这种时间，还有就是交易所在开盘之前会推送昨日的Tick快照，也会干扰k线合成。
论坛大佬的办法是对vnpy进行大改，增加了合约状态回报，其实也就相当于实现了这个issue的请求了，但鉴于没有纳入到vnpy的源码管理里面，不方便更新（相当于要自己维护一个分支）。

当然t还有其它可能的用处，我只是就我遇到的一些需求举的例子，除了CTP以外，其它的交易网关也有其它交易网关自己的事件。

目前的策略模板就只有on_tick，on_order，on_trade这几个回调，可能vnpy一开始的构想是，只要有行情就能驱动策略，进而完成交易。但如果策略依赖一些通知，仅靠tick信息就很难办了。

综上，鉴于各个Gateway接口不同，通知可能多种多样，如果增加太多的回调势必会导致策略模板变复杂，
所以我建议，把所有的事件通知统一到策略模板的以下回调里
```
on_event(self,event)
```
这个event的类型可以区分为通用事件和不同Gateway的专属事件，具体看怎么定义。
这样on_tick接受行情报价，on_event接受事件通知，两者相辅相成，才能覆盖完整的需求。

## 实际程序行为
没有类似的回调接口

**Comment by vnpy** [comment]
考虑梳理出来如下问题：

1. on_event事件回测中无法支持
2. 对于各个策略模块引擎来说，无法区分各个事件具体推送给哪个策略的on_event函数（要推就得全推）
3. 目前对于高级用户，这块功能已经可以通过向event_engine注册事件监听函数来实现

综上不考虑添加该on_event函数了
