### ISSUE TITLE
建议将 vnpy/chart/widget.py中update_info中info.setText改成info.setHtml实现彩色文字

### ISSUE THREAD

**Issue by laowalter** [vnpy/vnpy#3412]
1. 建议将vnpy/chart/widget.py 487行 改为info.setHtml
2. 对应的将482行的\n\n替换为`<br/><br/>`
这样在画图是可以用html实现彩色文字对应指标线。

**Comment by vnpy** [comment]
尝试后发现<br/> <br /> <br>这三种，都会被解析为空格而非换行，导致显示效果和目前不一致，暂时无法修改了。

请测试完成后提供个运行截图？R
