### ISSUE TITLE
CTA 策略和 组合合约策略对市价下单的直接支持

### ISSUE THREAD

**Issue by Y-L-LIU** [vnpy/vnpy#3417]
## 环境

* 操作系统: 如Windows 10
* Python版本: Python3.7
* VeighNa版本: v3.1

## Issue类型
三选一：Enhancement
`
调用下单函数希望市价下单是必须从引擎里重新包装,非常不方便，如果可以，想改进后提pr

            contract: Optional[ContractData] = self.cta_engine.main_engine.get_contract(self.vt_symbol)
            if not contract:
                self.write_log(f"委托失败，找不到合约：{self.vt_symbol}")
                return ""
            # Round order price and volume to  incremental value
            price: float = round_to(price, contract.pricetick)
            volume: float = round_to(volume, contract.min_volume)
            if direction==-1:
                return self.cta_engine.send_server_order(
                    self,
                    contract,
                    direction,
                    Offset.OPEN,
                    price,
                    volume,
                    OrderType.MARKET,
                    False,
                    False
                )
            else:
                return self.cta_engine.send_server_order(
                    self,
                    contract,
                    direction,
                    Offset.CLOSE,
                    price,
                    volume,
                    OrderType.MARKET,
                    False,
                    False
                )

`

**Comment by vnpy** [comment]
量化策略的委托执行上，一贯建议使用超价限价单的方式来提高成交率，而不是使用市价单了。
