### ISSUE TITLE
Support ArcticDB

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#3418]
ArcticDB supports Python 3.6 - 3.10

ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem. Launched in March 2023, it is the successor to [Arctic](https://github.com/man-group/arctic).

**Comment by vnpy** [comment]
感谢反馈，我们来研究下

**Comment by vnpy** [comment]
https://pypi.org/project/arcticdb/#files

For moment, there is only linux support of ArcticDB.

We will wait till there is windows version before developing the vnpy_arcticdb module.

**Comment by vnpy** [comment]
不错的消息，我们后续来尝试下

**Comment by vnpy** [comment]
1. ArcticDB的后端主要针对AWS/Azure的云端存储
2. 目前对Windows支持仅处于Beta状态

综上目前不考虑支持了。
