### ISSUE TITLE
bug：没有启动程序的文件并且ModuleNotFoundError: 

### ISSUE THREAD

**Issue by ForgetThatNight** [vnpy/vnpy#3419]
## 环境

* 操作系统: Mac
* Python版本: 3.10
* VeighNa版本: github3.6仓库

## Issue类型
三选一：Bug

## 预期程序行为
一：可以有studio的启动文件
二：没有import报错问题

## 实际程序行为
一：没有启动文件
二：ModuleNotFoundError: 

>>> from vnpy.event import EventEngine
>>> from vnpy.trader.engine import MainEngine
>>> from vnpy.trader.ui import MainWindow, create_qapp
>>> 
>>> from vnpy_ctp import CtpGateway
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vnpy_ctp'
>>> from vnpy_ctastrategy import CtaStrategyApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vnpy_ctastrategy'
>>> from vnpy_ctabacktester import CtaBacktesterApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vnpy_ctabacktester'

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

新建一个虚拟环境conda create -n vnpy python=3.10.9,按照readme进行安装，无法启动

**Comment by vnpy** [comment]
功能模块需要独立安装：

`pip install vnpy_ctabacktester`

**Comment by ForgetThatNight** [comment]
全安装了还是一堆问题，bug太多了，先将就用聚宽吧，要不就是pyqt 要不就是少其他的，等过段时间看看还有大佬贡献代码没
Faile to import cython option pricing model, please rebuild with cython in cmd.
qt.core.plugin.loader: In /Users/luocheng/anaconda3/plugins/platforms/libqcocoa.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/luocheng/anaconda3/plugins/platforms/libqminimal.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/luocheng/anaconda3/plugins/platforms/libqoffscreen.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /Users/luocheng/anaconda3/plugins/platforms/libqwebgl.dylib:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      python /Users/luocheng/Documents/vnpy-master/examples/veighna_trader/run.py

**Comment by vnpy** [comment]
不要用Anaconda，可以试试用Python官方的3.10发行版来装，基本奇怪的问题就不会出现了。
