### ISSUE TITLE
新手友好问题

### ISSUE THREAD

**Issue by Big-Mizu** [vnpy/vnpy#3422]
## 环境

* 操作系统: 如Windows 11
* Python版本: 3.10
* VeighNa版本: 2.60

## Issue类型
三选一：bug

## bug内容
当前版本的代码与新手教程和示例代码 有很大冲突，已经到了文不对题的地步，跟着新手教程学习敲代码寸步难行。希望开发者能更新一下新手教程和示例代码的相关内容。
例如：
①在examples目录下好多.ipynb文件的 import 处报红。查找整个项目均未找到import的文件。
![1682417403734](https://user-images.githubusercontent.com/65221778/234245658-c197c879-d752-4ae2-a3f7-9ea8e7dd4959.jpg)
②在官方微信公众号中《vn.py快速入门6 - 开发第一个量化策略》一文中，“定义策略类”处，
from vnpy.app.cta_strategy import (
    CtaTemplate,
    StopOrder,
    TickData,
    BarData,
    TradeData,
    OrderData,
    BarGenerator,
    ArrayManager,
)
然而在整个项目中vnpy只有chart, event, rpc, trader四个目录，app目录已被移除。类似的在问题在微信公众号的视频课程中也存在多数。

**Comment by HogwartsRico** [comment]
同问，教程里的app目录去哪儿了？
