### ISSUE TITLE
DataManager数据管理预览结束时间不准确

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3423]
## 环境

* 操作系统: 操作系统: Windows 11
* Python版本: VeighNa Studio-3.7.0
* VeighNa版本: v3.7.0

### Issue类型

Enhancement

### 预期程序行为

数据管理预览结束时间应该为数据库里面rb2310的最后结束时间20230512

## 实际程序行为

如下图所示，数据管理预览结束时间为20230511，实际查看数据库里面rb2310实际最后结束时间是20230512

![捕获1](https://github.com/vnpy/vnpy/assets/60735134/46487335-1d05-4da6-884f-660b964b3672)
![捕获](https://github.com/vnpy/vnpy/assets/60735134/8e3747bb-75f6-4b0b-973a-cf31856f1b0d)

**Comment by vnpy** [comment]
选择数据区间对话框的问题已经修复。

数据预览中范围和实际数据范围的偏差问题，建议检查下数据插入时是否基于vnpy.trader.database组件，否则会出现不一致问题。
