### ISSUE TITLE
DataManager数据管理-更新数据报错

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3424]
## 环境

* 操作系统: 操作系统: Windows 11
* Python版本: VeighNa Studio-3.7.0
* VeighNa版本: v3.7.0

### Issue类型

Enhancement

### 预期程序行为

数据服务使用天勤，数据库里面有米筐rb888.SHFE这类天勤不支持的数据，   使用数据管理-更新数据直接跳过不支持的数据品种，更新其他剩余还支持的数据品种到数据库中。

## 实际程序行为

数据服务使用天勤，数据库里面有米筐rb888.SHFE这类天勤不支持的数据，   使用数据管理-更新数据就会报错，然后卡住，而不是跳过不支持的数据品种，更新其他剩余还支持的数据品种到数据库中。

**Comment by vnpy** [comment]
DataManager在设计上是针对单DataFeed场景的，如果需要同时使用多个DataFeed建议将其数据拆分到各自专用的数据库中存储。
