### ISSUE TITLE
vnpy模块的ui运行报错

### ISSUE THREAD

**Issue by Intgrp** [vnpy/vnpy#3425]
## 环境

* 操作系统: Windows 11
* Python版本: 3.10
* VeighNa版本: VeighNa Studio-3.6.0

## Issue类型
Bug

## 预期程序行为
执行创建app窗口的程序，正常创建、界面

## 实际程序行为
出现异常一
![image](https://github.com/vnpy/vnpy/assets/16705924/5ef39af6-c44b-49a7-ad12-b9f2564b865b)
解决方式是：
将标红的文件232行下述内容
![image](https://github.com/vnpy/vnpy/assets/16705924/cf005c73-7a65-4f57-bd85-f28f105f9403)
改成
> dock.setFeatures(dock.DockWidgetFeature.DockWidgetFloatable | dock.DockWidgetFeature.DockWidgetMovable)

再次运行时出现下述问题
![image](https://github.com/vnpy/vnpy/assets/16705924/0d56d6bb-2390-43f0-8633-e5c403f0f988)
解决方式是：
将下述
![image](https://github.com/vnpy/vnpy/assets/16705924/09d63660-61f1-4bcd-bddd-74cfac999a51)
改成
> self.setEditTriggers(self.EditTrigger.NoEditTriggers)

最后运行正常

## 处理方式建议
不知道是不是只有我的环境出现这个问题，官方看一下是否需要优化进程序

此问题其他用户在 https://toscode.gitee.com/vnpy/vnpy_spreadtrading/issues/I6KS5A 的vnpy_spreadtrading也有出现

**Comment by Intgrp** [comment]
貌似更新成最新版本后每个模块都多多少少会报上面问题。如果本地clone代码的时候，pycharm又能正常索引到对应变量，只有安装完包后运行那些app模块才会报错。感觉像运行安装包时，引包统一识别少了一层的样子。

**Comment by vnpy** [comment]
请尝试下使用6.3.0版本的PySide6，看看问题是否还存在
