### ISSUE TITLE
vnpy3. 7使用dolphinDB数据库报错

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3427]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为

实际程序行为

### **在Win11中使用MongoDB，只要线程数设置在61以下，CTA回测优化就不会报错，但是换成dolphinDB数据库后，设置进程上限超过30，就会如下图所示报错。 如果设置进程上限30以下，就没有任何问题。物理机是双路工作站，36核心72线程，256GB内存，，查询了一下dolphinDB的日志文件，报错代码如下，，咨询了一下dolphinDB工作人员，他们提示用连接池的方式，事先建立固定数量的链接，确保连接数可控。**

`2023-05-19 11:26:03.540419 <INFO> :Created a new socket connection. Number of connections: 64
2023-05-19 11:26:03.540419 <ERROR> :WSAWaitForMultipleEvents() failed with error 87`

![1](https://github.com/vnpy/vnpy/assets/60735134/92d9068d-5ae1-4f77-80f2-57281ba76938)
![微信图片_20230520164715](https://github.com/vnpy/vnpy/assets/60735134/c4b7a2f5-ef28-43a8-99c9-2ff5b201b312)
![3](https://github.com/vnpy/vnpy/assets/60735134/0052d38d-cb37-4506-9eac-84d20a588e19)

**Comment by vnpy** [comment]
这个属于DolphinDB的问题，猜测和免费版的连接数限制有关，无法在VeighNa中处理了
