### ISSUE TITLE
关于回测K线图表新增自定义周期与回测每日盈亏新增盈利为红色的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3428]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为

实际程序行为
**1. “回测K线图表“ 默认使用1分钟，进行策略开发时，一旦周期长了就会变的非常卡顿，如果策略是长周期跨主力合约，需要缩放很久，如果能新增自定义周期，多个选择的话，就更加直观一些。**

**2. “回测每日盈亏” 新增盈利为红色，亏损为绿色，直观一点。**
![捕获](https://github.com/vnpy/vnpy/assets/60735134/10d3f702-fa8f-4455-be60-a6a21a66f210)
![捕获](https://github.com/vnpy/vnpy/assets/60735134/78c9f849-bcb7-4323-853d-766de98c9369)

**Comment by vnpy** [comment]
对于专业量化用户，还是更推荐在Jupyter中执行投研回测任务，因此暂不考虑上述功能支持。
