### ISSUE TITLE
期货价格计算有误

### ISSUE THREAD

**Issue by qmhedging** [vnpy/vnpy#343]
期货价格不应当乘以合约乘数

**Comment by vnpy** [comment]
请说一下具体出错的代码或者功能部分？

**Comment by qmhedging** [comment]
![vnpyerror1](https://cloud.githubusercontent.com/assets/1763575/26830555/cbc832f0-4afb-11e7-93ea-5b10313f8827.jpg)

**Comment by keith-ch** [comment]
可能价格有歧义？改成市值？

**Comment by qmhedging** [comment]
那价格字段还是需要的，而且持仓价格不对影响显著，这个应该能尽快改正

**Comment by vnpy** [comment]
CTP接口返回的数据是持仓总成本（持仓合约*合约大小*均价），因此计算持仓均价时需要反向计算，而有时系统中尚未收到合约大小的数据时，就会默认取1，出现上面的情况。

最新的1.6.2版本已经修复，若无法获得合约大小数据，则直接不进行计算。
