### ISSUE TITLE
关于增加停止单执行价格为设定价的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3430]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为
**增加停止单执行价格为设定价、市场价，这至少对开仓是很有利的，可以有效的控制开仓时的滑点。**
实际程序行为
**实盘测试发现一般停止单均存在2个点的滑点，极端行情甚至在涨停板成交，当然散户资金肯定无法做到这点。论坛也有很多人提出过这个疑问，包括[hxxjava]老师，https://www.vnpy.com/forum/topic/30437-bi-ting-zhi-dan-geng-hao-yong-de-tiao-jian-dan-conditionorder?page=1**

**例如实际使用中停止单也是有缺点的：
当以比市场价更低的价格买，它会立即被执行
当以比市场价更高的价格卖，它会立即被执行
实际运行中有多个停止单通知满足条件，接口在极短时间内接受多个停止单发出的委托，发生委托覆盖。表现为明明策略发出过多个停止单，但是只有最后一个停止单有结果，其他的委托莫名其妙的人间蒸发了，不见了，接口不回应、不通知，策略也不知道，用户无法查。停止单一经发出，触发价也是执行价，无法根据当时的市场价格做出价格调整。只有CTA策略才可以使用停止单，其他类型的策略无法使用，因为它的执行逻辑和具体合约耦合度太高。**

**Comment by vnpy** [comment]
停止单更多为了保证成交效率，如果确实因为资金较大担心冲击市场，可以自行修改CTA策略模块引擎中的停止单触发后委托价格了
