### ISSUE TITLE
关于提升K线生成器BarGenerator效率的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3432]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为

一个策略大部分时候，甚至90%时间主要的事情就是接收tick，然后合成1分钟bar，然后合成15分钟或者其他自定义长度bar。批量的功能重复的事情，可以通过集中k线生成器来实现。集中合成bar，使用方法回调传给策略对应的方法on_bar或者on_minute_bar。

实际程序行为

在使用vntrader cta策略交易模块时候，其每个策略都有各自实例化的K线生成器BarGenerator，来根据传入的tick或者历史回放的bar，来合成需要的k线bar，在on_minute_bar方法中进行条件发单或者平仓。对于中低频的分钟级策略，一个策略大部分时候，甚至90%时间主要的事情就是接收tick，然后合成1分钟bar，然后合成15分钟或者其他自定义长度bar。

**对于一个品种只有一两个策略倒是没有什么问题，如果一个品种对应的策略比较多，比如针对螺纹钢的策略有5-6个，做10个品种，一共50-60个实例，那么每个策略自己来花时间做同样的K线合成实在有浪费算力，尤其是python本身效率不高情况。从项目角度来看，批量的功能重复的事情，可以通过集中k线生成器来实现。集中合成bar，使用方法回调传给策略对应的方法on_bar或者on_minute_bar。**

**Comment by vnpy** [comment]
vnpy.trader.utility模块下的BarGenerator，更多作为尽可能通用的标准K线合成器实现。

在各种细分场景下，很可能会有更好的实现逻辑，但存在普适性不足的问题。

上述场景建议根据自己的需求定制BarGenerator组件（或者整体的行情数据缓存组件），可以使用全局单例模式等方式来提高整体效率。
