### ISSUE TITLE
[install] Python3.7 not match numpy version 1.23.1

### ISSUE THREAD

**Issue by orangle** [vnpy/vnpy#3438]
## 环境

* 操作系统: macos 12.5
* Python版本: 3.7.12
* VeighNa版本:  main branch 

## Issue类型
三选一：Question

## 预期程序行为
```
python -m pip install numpy==1.23.1 
```
正常安装

## 实际程序行为
<img width="1469" alt="image" src="https://github.com/vnpy/vnpy/assets/2696746/73d8322a-311a-4425-9735-377d90ef0ce5">

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by orangle** [comment]
readme 是不是可以更新一波了？

**Comment by noranhe** [comment]
可以pip install numpy==1.21.6试试看
