### ISSUE TITLE
回测页面显示界面错乱

### ISSUE THREAD

**Issue by nicy010** [vnpy/vnpy#3440]
## 环境

* 操作系统: 如Windows service 2019
* Python版本: 3.7.9
* VeighNa版本: 3.7.0

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
打开回测页面，界面能正常显示

## 实际程序行为
打开回测页面，界面显示错乱

## 重现步骤
通过python命令执行run.py文件，启动vn，打开回测页面，界面显示错乱

针对Bug类型Issue，请提供具体重现步骤以及报错截图

<img width="1422" alt="image" src="https://github.com/vnpy/vnpy/assets/124545599/d547aaa4-cea6-4422-b9fd-c745838d4ac5">

**Comment by vnpy** [comment]
需要最低1920x1080分辨率
