### ISSUE TITLE
仿真交易模块一键清仓后，行情订阅未清空

### ISSUE THREAD

**Issue by yanxiu0614** [vnpy/vnpy#3445]
仿真交易在下单成交后，再一键清仓后，持仓已经显示为0，但是重启vnpy之后，会自动订阅先前已清空的股票。
关闭vnpy，再把把本地本地配置文件（portfolio_manager_data.json）修改为{}之后，问题消失。看起来像是读写配置文件的问题？

**Comment by vnpy** [comment]
PaperAccount、PortfolioManager这些每个是独立的模块，互相之间的缓存数据独立。

自动订阅之前的股票，是源于PortfolioManager对于已有持仓合约的盈亏计算需求。

**Comment by yanxiu0614** [comment]
> PaperAccount、PortfolioManager这些每个是独立的模块，互相之间的缓存数据独立。
> 
> 
> 
> 自动订阅之前的股票，是源于PortfolioManager对于已有持仓合约的盈亏计算需求。

但是持仓已经全部清空了，持仓量为零了。
