### ISSUE TITLE
关于DataManager界面增加搜索与排序的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3447]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为

**建议DataManager界面增加搜索与排序，点击排序就支持按照交易所，时间等排序，增加搜索框，方便数据库全市场数据时一键搜索，提升效率**

实际程序行为

**Comment by vnpy** [comment]
vnpy_datamanager新版本中已经增加交易所节点的显示，同时对于每个交易所内的合约也基于合约代码进行了排序处理。
