### ISSUE TITLE
关于DataManager “查看” 界面结束时间不准确的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3452]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行
![捕获](https://github.com/vnpy/vnpy/assets/60735134/457e7f6b-4aa8-4648-8565-3ed528b26408)
为
![捕获](https://github.com/vnpy/vnpy/assets/60735134/2438b9e6-b749-4a72-85f9-a8474bed515f)

### **如图所示，DataManager查看界面结束时间不准确，为前一日日期，准确来说应该是数据库结束时间最新的日期，end.day+1即可。**

实际程序行为

**Comment by vnpy** [comment]
已经修复
