### ISSUE TITLE
关于CTA策略重启后自动加载停止单的建议

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3453]
环境
操作系统: 操作系统: Windows 11
Python版本: VeighNa Studio-3.7.0
VeighNa版本: v3.7.0
Issue类型

Enhancement

预期程序行为
### **如果使用长周期与停止单，重启软件后本地停止单就会丢失，在下一个K线周期推送进来之前，如果发生极端行情，策略面临非常大的风险，建议CTA策略重启后自动加载停止单，望采纳。**

**Comment by vnpy** [comment]
这里可以在策略中自行维护要挂出的停止单状态，并在on_start策略启动时检查，有必要的话立即发出委托。
