### ISSUE TITLE
运行install_osx.sh报错

### ISSUE THREAD

**Issue by gaspire** [vnpy/vnpy#3456]
## 环境

* 操作系统: macos
* Python版本: python3
* VeighNa版本: 20230802

## Issue类型
Bug
运行install_osx.sh报错:
install_osx.sh: line 17: `install-ta-lib': not a valid identifier
install_osx.sh: line 21: `ta-lib-exists': not a valid identifier

## 预期程序行为
install-ta-lib \ta-lib-exists 两个函数名需要改成下划线
https://blog.csdn.net/kokiafans/article/details/122320630

**Comment by xzmeng** [comment]
I recommend you to use bash (according to README):
```
$ bash install_osx.sh
```

**/bin/sh** shipped with macOS is a posix-compliant shell which is not the same as bash.
