### ISSUE TITLE
海通期货的uft尝试在Linux系统下连接股票期权行情 显示无法连接到行情 

### ISSUE THREAD

**Issue by kmeiMagma** [vnpy/vnpy#3457]
## 环境

* 操作系统:Ubuntu 22.04.2 LTS
* Python版本: Python 3.10.12

## Issue类型
Bug

## 预期程序行为
正确连接到行情

## 实际程序行为
无法正确连接到行情

## 重现步骤
from vnpy_uft.gateway import UftGateway
from vnpy.event import EventEngine
from vnpy.trader.engine import MainEngine
from vnpy_scripttrader import ScriptEngine, ScriptTraderApp
from vnpy_scripttrader import init_cli_trading
from script_trade_test import run
stage_setting = {
    "用户名": "********", #此处隐去账号密码
    "密码": "********",
    "交易服务器": "116.236.247.243:21491",  # 模拟交易
    "行情服务器": "116.236.247.243:21492",  # 模拟行情
    "服务器类型": "ETF期权",
    "产品名称": "",
    "授权编码": "",
    "委托类型": "7"
}
def main():
    engine = init_cli_trading([UftGateway])
    engine.connect_gateway(stage_setting,"UFT")
    vt_symbols = ["10005860.SSE", "10005107.SSE"]
    engine.subscribe(vt_symbols)
    contract_info = engine.get_all_contracts()
    print(contract_info)

if __name__ == "__main__":
    main()
针对Bug类型Issue，请提供具体重现步骤以及报错截图

找不到数据服务驱动vnpy_，使用默认的RQData数据服务
[]
2023-08-09 16:22:59.052041	行情服务器连接断开，原因：-1009，连接超时，重试中...
2023-08-09 16:22:59.095026	交易服务器连接断开，原因：-1009，连接超时，重试中...
2023-08-09 16:23:02.055486	行情服务器连接断开，原因：-1009，连接超时，重试中...
2023-08-09 16:23:02.099250	交易服务器连接断开，原因：-1009，连接超时，重试中...
2023-08-09 16:23:05.002897	交易服务器连接断开，原因：-1009，连接超时，重试中...
2023-08-09 16:23:05.059165	行情服务器连接断开，原因：-1009，连接超时，重试中...

没有任何别的报错，对于windows版本是一直可用但是linux版本就无法连接 
券商为海通期货

**Comment by vnpy** [comment]
可能是Linux上的API版本老了，目前UFT的ETF期权版用户比较少，所以柜台新版本发布后的反馈会慢很多
