### ISSUE TITLE
建议用sqlite替换mongodb

### ISSUE THREAD

**Issue by ujfjhz** [vnpy/vnpy#346]
原因如下：
1) sqlite是一个文件数据库，非常轻量，降低vnpy的外部依赖，便于项目的推广。
2) 对普通用户来说，运维一个mongodb增加了学习成本，而sqlite几乎无运维成本，备份直接通过文件拷贝完成。
3) 相比nosql的mongodb，普通用户更熟悉sqlite这样的关系型数据库。
4) 在交易相关的场景下，sqlite有更好的性能。mongodb更适合大量用户大量并发的场景，而vnpy一般一个实例只有若干个并发，只要设计好sqlite的库表结构，sqlite有更好的性能。
5) mongodb的运行需要额外开销。

**Comment by jeffereylj** [comment]
支持这个建议，sqlite 在Ubuntu下已经是自带的软件，成本更低。

**Comment by vnpy** [comment]
看了下存在几个问题，sqlite可能无法解决：
1. 多进程访问：盘中一个进程负责执行策略交易，一个进程负责收集数据
2. 分布式访问：某些用vn.py构建多台机器集群系统的私募，需要能在局域网内跨机器访问

要解决以上两个问题，一个方案是用vnrpc来写一个数据代理进程，比起用MongoDB这种数据库的方案又没什么优势了。

**Comment by shaoupipi** [comment]
其实influxdb更适合tick数据存取，性能更好、使用更简单

**Comment by vnpy** [comment]
vn.py里的储存需求并不是只有Tick行情数据，对于私募用户而言还有很多其他的数据类型

**Comment by ssh352** [comment]
> 看了下存在几个问题，sqlite可能无法解决：
> 
> 1. 多进程访问：盘中一个进程负责执行策略交易，一个进程负责收集数据
> 2. 分布式访问：某些用vn.py构建多台机器集群系统的私募，需要能在局域网内跨机器访问
> 
> 要解决以上两个问题，一个方案是用vnrpc来写一个数据代理进程，比起用MongoDB这种数据库的方案又没什么优势了。

这几个理由很有道理， 那后来为什么还是用sqlite了呢？

**Comment by vnpy** [comment]
因为通过独立的database模块实现了四个数据库支持：MongoDB/Sqlite/MySQL/PostgreSQL
