### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x91 in position 130: illegal multibyte sequence

### ISSUE THREAD

**Issue by namenotexist** [vnpy/vnpy#3469]
import tushare as ts
print(ts.get_rrr())

<img width="843" alt="image" src="https://github.com/vnpy/vnpy/assets/40298904/29609596-be18-4dc8-9a4b-8380fa39b913">

**Comment by vnpy** [comment]
这是TuShare相关的问题，请去https://github.com/waditu/tushare开issue吧
