### ISSUE TITLE
交易所有误

### ISSUE THREAD

**Issue by lance52587** [vnpy/vnpy#3471]
## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
https://github.com/vnpy/vnpy/blob/6dcaf9249e9cee4f4049c8f0f97e91bf9e2eb112/vnpy/trader/constant.py#L112
IB接口用CBT无法正确订阅合约，改为CBOT可以。
ZS-20231114-USD-FUT.CBOT

**Comment by noranhe** [comment]
这个枚举值除了IB接口之外，直达和易盛也在用的。这个value这是图形界面显示，接口订阅传出的exchange值依赖于EXCHANGE_VT2IB的映射值，而不是枚举值的value
