### ISSUE TITLE
CTA模块、价差交易模块、组合回测模块一些函数的参数问题建议

### ISSUE THREAD

**Issue by Mjzs12138** [vnpy/vnpy#3473]
1.价差交易模块和组合回测模块的BacktestingEngine不支持自定义annual_days和risk_free参数。建议在初始化方法中增加该参数，并调整对应的calcaulate_statistics方法。
2.cta交易模块的run_ga_optimization方法不支持用户从外部修改ngen_size参数。价差交易模块和组合回测模块的run_ga_optimization/run_bf_optimization不支持ngen_size参数和max_workers参数的外部修改。
3.组合回测模块的evaluate函数中返回值setting仍然是字符串格式。建议修改和价差交易模块和cta模块保持一致。
4.cta交易模块的TargetPosTemplate不支持外部修改tick_add

**Comment by noranhe** [comment]
1-3 已修复，4已在issue3465中回复过了
