### ISSUE TITLE
优化模块在Linux上运行报错

### ISSUE THREAD

**Issue by CancerQ** [vnpy/vnpy#3476]
## 环境

* 操作系统: debian 12
## Issue类型
三选一：Bug

## 预期程序行为
正常运行

## 实际程序行为
运行报错

## 重现步骤
使用回测优化

提交记录
https://github.com/vnpy/vnpy/commit/ceae1e72f1785c3098058bd87ed0fba795346565

**Comment by vnpy** [comment]
具体报错信息请提供下截图

**Comment by CancerQ** [comment]
linux请使用fork来创建，spawn使用在windows，另外请确认windows在使用spawn时是否能共享父进程的资源，确认组合策略回测是否能正常读取数据库的数据，是否需要重连数据库，请确认是否有必要这样做，目前linux使用spawn是无法共享父线程资源的，需要重连数据库，只有fork创建时可以共享父进程资源才能读取到数据库资源，请确认一下，请注重linux的开发和体验

**Comment by noranhe** [comment]
我们这边测过了了，没有问题。可以检查一下你的回测脚本是否有把优化代码写在if __name__ == "__main__":下，以防优化代码被子进程读取
