### ISSUE TITLE
veigh trader 无法查询合约以及查看行情

### ISSUE THREAD

**Issue by xiefengnian** [vnpy/vnpy#3485]
## 环境

* 操作系统: MacOS 13.5.2
* Python版本: 3.9
* VeighNa版本: 3.8.0

## Issue类型
三选一：Question

## 预期程序行为

从examples/veighna_trader中启动项目并填写了udata账号密码以及安装 vnpy-udata 后，可以正常查询合约查看行情

## 实际程序行为

无法查询任何合约，且无报错

## 重现步骤

![image](https://github.com/vnpy/vnpy/assets/20136563/82103ba2-f067-46f4-9d4c-6ad1e80fe297)

已配置udata

![image](https://github.com/vnpy/vnpy/assets/20136563/91220005-3ba0-4dfd-8a80-406f2fa45a57)

**Comment by vnpy** [comment]
合约信息来自于交易接口，udata是datafeed数据服务，没有合约信息提供了
