### ISSUE TITLE
有些gateway, 我想脱离vnpy使用，可以吗，如何做？

### ISSUE THREAD

**Issue by happybeta** [vnpy/vnpy#3489]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
大部分Gateway模块中（如vnpy_ctp）都包含了两层：

1. C++类接口的Python封装
2. 将1对接到VeighNa标准交易接口的实现

其中1部分可以脱离VeighNa框架直接使用，例如：

```
from vnpy_ctp.api import CtpMdpi, CtpTdApi

class MyMdApi(CtpMdApi):
....

```
