### ISSUE TITLE
VeighNa Station选择安装目录与卸载优化

### ISSUE THREAD

**Issue by shinyruo177** [vnpy/vnpy#3491]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如3.10.11
* VeighNa Station版本: 如v3.7.0

## Issue类型
Enhancement
## 问题
在安装VeighNa Station时，安装位置选择了一个非空的文件夹A，该文件夹A中包括其它软件的安装目录，
此时由于安装过程中出错，想要卸载程序安装，但是卸载程序把A下所有文件夹都清空了，导致其它软件的异常卸载。
## 预期程序行为
![image](https://github.com/vnpy/vnpy/assets/40891772/0c4e22cf-b6d8-4705-971d-b819b6d02b38)
预期是VeighNa Station在选择安装位置的时候，能够在选中的目录下面再附加一级用于安装软件的目录，
例如选中 D:\professional_install_space后，自动附加一级vnpy-studio，这样程序安装的位置就是：
D:\professional_install_space\vnpy-studio。
据观察目前常用的开发软件大多会在选中的目录后面，再自动附加一级子目录去存放程序，个人认为比较科学一些（比如说避免卸载时清空多余的用户文件夹）。

## 实际程序行为
卸载时清空了安装目录下所有文件，缺乏检查。

**Comment by vnpy** [comment]
3.9.0的VeighNa Studio安装包，已经增加了对安装目录的非空检查，建议可以测试下：

https://download.vnpy.com/veighna_studio-3.9.0.exe

**Comment by shinyruo177** [comment]
> 3.9.0的VeighNa Studio安装包，已经增加了对安装目录的非空检查，建议可以测试下：
> 
> https://download.vnpy.com/veighna_studio-3.9.0.exe

验证已解决😘
