### ISSUE TITLE
vnpy.rpc.server.check_heartbeat()推送的时间数据类型与vnpy.rpc.client._last_received_ping初始化的类型不一致

### ISSUE THREAD

**Issue by mtwhitecamel** [vnpy/vnpy#3492]
## 环境

* 操作系统: centos7
* Python版本: 3.8.8
* VeighNa版本: latest

## Issue类型
三选一：Enhancement

vnpy.rpc.server.check_heartbeat()将time.time(): float写入zmq，在rpc_client中赋值给_last_received_ping，但_last_received_ping定义是datetime类型

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy/pull/3520/files
