### ISSUE TITLE
cta柜台下订阅持仓推送，PositionData的持仓成本是错误的，price并非持仓成本，而是昨日的结算价格，导致pnl也是错误的。

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#3494]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
Bug

## 预期程序行为
持仓推送返回持仓信息

## 实际程序行为
返回的持仓成本是昨日结算价格

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by noranhe** [comment]
position.price是用持仓程报PositionCost除以持仓的volume和size算出来的
