### ISSUE TITLE
save_strategy_setting保存策略参数时如果涉及枚举类例如Interval这类枚举类会序列化出错

### ISSUE THREAD

**Issue by Intgrp** [vnpy/vnpy#3497]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Enhancement

## 实际程序行为

建议给constant对象里枚举类都设置成多继承例如
class Interval(str, Enum)
如果是数字枚举则设置成如下
class Color(IntEnum)

算是特性增强吧

**Comment by vnpy** [comment]
官方文档中有强调，策略参数仅支持int/float/str/bool四种基础变量类型

https://www.vnpy.com/docs
