### ISSUE TITLE
vnpy_scripttrader的cli.py文件 中 event_engine 不需要注册 EVENT_LOG的 process_log_event函数 与主引擎重复注册导致LOG输出两遍

### ISSUE THREAD

**Issue by EzMoney-Sniper** [vnpy/vnpy#3501]
vnpy_scripttrader的cli.py文件 中 event_engine 不需要注册 EVENT_LOG的 process_log_event函数 与主引擎重复注册导致LOG输出两遍

**Comment by noranhe** [comment]
init_cli_trading是为了命令行界面使用设计的，所以收到的日志事件都是调用print函数打印输出的。而日志引擎的日志事件收到后是通过logger输出的，如果想用jupyter跑脚本，不想logger输出日志事件信息，把log.active设置为False应该就可以了
