### ISSUE TITLE
3.9.0 运行run.py报错

### ISSUE THREAD

**Issue by vingin007** [vnpy/vnpy#3503]
## 环境

* 操作系统: Ubuntu 20.04
* Python版本: python3.8.
* VeighNa版本: v3.9.0

## Issue类型
运行run.py时报错，升级了vnpy_ctastrategy也没用
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from vnpy.trader.ui import MainWindow, create_qapp
  File "/usr/local/lib/python3.8/dist-packages/vnpy/trader/ui/__init__.py", line 1, in <module>
    from .qt import QtCore, QtWidgets, QtGui, Qt, create_qapp
  File "/usr/local/lib/python3.8/dist-packages/vnpy/trader/ui/qt.py", line 10, in <module>
    from PySide6 import QtGui, QtWidgets, QtCore
ImportError: cannot import name 'QtGui' from 'PySide6' (/usr/local/lib/python3.8/dist-packages/PySide6/__init__.py)

**Comment by vnpy** [comment]
这个报错是PySide6的问题，尝试卸载重装试试吧：

`sudo pip3 install PySide6==6.3.0`

**Comment by vingin007** [comment]
> =

重装了依然还是一样的报错。

**Comment by vnpy** [comment]
那建议升级到Python 3.10试下了

**Comment by zgm0407** [comment]
x显示驱动的问题。sudo apt update && apt install -y libxkbcommon-x11-dev  libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
    libxcb-shm0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev
