### ISSUE TITLE
建议增加Dockerfile和requirements-optional.txt

### ISSUE THREAD

**Issue by zgm0407** [vnpy/vnpy#3506]
建议：
1、Dockerfile有示范安装过程的作用，能够省去不少试错和解决问题的坑，而且docker容易部署于云端服务器；
2、requirements-optional.txt可汇总install.bat中未列出的各个功能模块清单，便于选择安装；
3、sar是高效设置止损的参数，能够方便和强化软件的停止单特色，建议在utility.py中增加。

**Comment by vnpy** [comment]
1. 目前Dockerfile构建较为复杂，暂时不考虑开源
2. install.bat中包含了所有vnpy库本身运行所需的依赖，各个接口和插件模块并不是vnpy的依赖（反而是它们需要依赖vnpy），因此不适合放在requirements-optional.txt中
3. 已经添加
