### ISSUE TITLE
关于CTA回测成交记录异常的咨询

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3514]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如VeighNa Studio-3.9.0
* VeighNa版本: v3.9.0发行版

## Issue类型
三选一：Bug/Question

## 实际程序行为

**1、CTA回测成交记录异常，如下图所示，红色框框内累计开仓7手，self.pos=7（之前持仓已经全部平仓），然后策略全部平仓，怎么平仓了4手，6手，7手？根本持仓只有7手。然后又多平10手才恢复正常。**

**2、如下图所示，打印委托记录如下，发现是回测框架错误执行了策略请求，，累计开仓7手，self.pos=7（之前持仓已经全部平仓），然后策略全部平仓，怎么平仓了4手，6手，7手？ 持仓共计只有7手啊，怎么可能持仓7手，可以平仓17手出来。 这种情况很少出现，13年回测数据，只有出现2次。看了一下k线图表，如下图所示，开仓与平仓时行情很极端，都是在1分钟内开仓后然后平仓，并且平仓使用的是停止单，开仓是同时挂出平仓止损止盈的停止单。 感觉像是平仓时获取到的self.pos有延迟造成的，，这个问题该如何解决呢？ 这个是否属于回测框架的问题，还是策略逻辑的问题？**

![捕获](https://github.com/vnpy/vnpy/assets/60735134/98207467-b658-429d-a1c7-2ea4b235bd95)
![捕获](https://github.com/vnpy/vnpy/assets/60735134/319adcdd-4546-472c-9a2d-090fdb82be3d)
![捕获1](https://github.com/vnpy/vnpy/assets/60735134/fe5e4eec-f1ab-4cf4-bba1-283d2e8e99cb)

**Comment by noranhe** [comment]
可以自己去策略内打印排查是self.pos获取仓位不正确或延迟还是策略内部逻辑的问题

**Comment by rjl02468** [comment]
我使用的就是vnpy自带的海归策略

**Comment by vnpy** [comment]
CTA策略的回测引擎，在策略委托时没有对开平数量进行检查，而是基于净仓模式来执行委托撮合。

如果需要对开平数量进行控制，需要自己在策略层面来实现。
