### ISSUE TITLE
1.6.2版本CTP模块错误

### ISSUE THREAD

**Issue by angusoutlook** [vnpy/vnpy#352]
今天下了最新的1.6.2版本。运行example的run.py，发现了问题。
选用菜单进行ctp连接的时候，出现了错误。
同样的设置在1.6.1版本中没有出现过。
错误信息为：CTP：无此功能。而且不能读取账户和持仓信息。
紧急，麻烦了。

**Comment by vnpy** [comment]
请提供你的运行环境，另外问下你是否修改过安装到site-packages下的源代码？

还有请附上出错相关的截图。

**Comment by vnpy** [comment]
无更新，关闭issue。
