### ISSUE TITLE
vnpy3.9.1无法安装ta-lib

### ISSUE THREAD

**Issue by 17hao** [vnpy/vnpy#3524]
## 环境

* 操作系统: Debian GNU/Linux 12 (bookworm) x86_64
* Python版本: 3.10.14
* VeighNa版本: 3.9.1

## Issue类型
Question

## 预期程序行为
成功安装ta-lib。

## 实际程序行为
安装ta-lib报错。

## 重现步骤
`bash install.sh`

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![flameshot-2024-03-30T01-26-01](https://github.com/vnpy/vnpy/assets/18420212/8b42ec56-d51f-41a4-8513-6ea98d345c58)

**Comment by vnpy** [comment]
以上报错是由于pypi.vnpy.com源没有提供Linux安装包，目前已经补齐，请再尝试下即可。

**Comment by 17hao** [comment]
@vnpy 已经解决，非常感谢🙏
