### ISSUE TITLE
回测打印order.reference显示空白

### ISSUE THREAD

**Issue by rjl02468** [vnpy/vnpy#3525]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如VeighNa Studio-3.9.0
* VeighNa版本: v3.9.0发行版

## Issue类型
三选一：bug

## 实际程序行为

**回测打印order.reference显示空白，之前版本回测时，测试打印能够正确获取到order.reference的策略名称**
`rb888
OrderData(gateway_name='BACKTESTING', extra=None, symbol='rb888', exchange=<Exchange.SHFE: 'SHFE'>, orderid='40', type=<OrderType.LIMIT: '限价'>, direction=<Direction.LONG: '多'>, offset=<Offset.CLOSE: '平'>, price=3644.0, volume=1, traded=1, status=<Status.ALLTRADED: '全部成交'>, datetime=datetime.datetime(2023, 5, 9, 14, 45, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai')), reference='')
`

**Comment by noranhe** [comment]
回测本来就没有reference
