### ISSUE TITLE
vnpy/vnpy/trader/gateway/ctpGateway/ctpGateway.py

### ISSUE THREAD

**Issue by dotcream** [vnpy/vnpy#353]
class CtpTdApi(TdApi):
self.requireAuthentication = False

class CtpGateway(VtGateway): 
self.requireAuthentication = False  

#下面的requireAuthentication这个好像没啥用

**Comment by vnpy** [comment]
用来实现部分期货公司要求的CTP验证登录

**Comment by dotcream** [comment]
我的表述不太明白
https://github.com/vnpy/vnpy/blob/master/vnpy/trader/gateway/ctpGateway/ctpGateway.py
第95行，可以删除

**Comment by vnpy** [comment]
明白了，已经处理
