### ISSUE TITLE
MacOS+Pyrhon3.10.14+Vnpy3.9.1 安装错误（vnpy_ctp）

### ISSUE THREAD

**Issue by zhanghuahan** [vnpy/vnpy#3531]
## 环境

* 操作系统: MacOS
* Python版本: 3.10.14
* VeighNa版本: 3.9.1

## Issue类型
三选一：Question

## 预期程序行为
正常安装，流程参考https://mp.weixin.qq.com/s/OB4TpVnipueFO-pbXyz_Rg

## 实际程序行为
报错命令：python3 -m pip install vnpy_ctp --index=https://pypi.doubanio.com/simple

报错结果
<img width="791" alt="截屏2024-04-29 17 07 58" src="https://github.com/vnpy/vnpy/assets/50811072/857db1d3-dcb2-44eb-8f67-315fb497e2c1">

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by zhanghuahan** [comment]
python3 -m pip install vnpy_ctp --index=https://pypi.doubanio.com/simple vnpy_ctp==6.6.9.1
 
 执行该命令，指定版本即可

**Comment by vnpy** [comment]
https://github.com/vnpy/vnpy_ctp

请参考这里的Mac安装说明
