### ISSUE TITLE
关于翻墙

### ISSUE THREAD

**Issue by Thinkbro** [vnpy/vnpy#3535]
## 环境

* 操作系统: Windows 11
* Python版本: python 3.9
* VeighNa版本: v3.4

## Issue类型
三选一：Question

## 预期程序行为## 环境

* 操作系统: 如Windows 11
* Python版本: 3.9
* VeighNa版本: 3.4
## Issue类型
三选一：Question

使用sokces协议的v2ry不能翻墙。
自己测试网络，可以通过网址访问api。
但是使用vnpy不能访问
这是v2ry报的错误信息：2024/05/09 15:04:20 tcp:127.0.0.1:64762 rejected  proxy/socks: unknown Socks version: 67
这是pyrchram报的错误信息：aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by vnpy** [comment]
没有支持v2y的代理
