### ISSUE TITLE
使用可编辑源码模式安装vnpy_ctp报错

### ISSUE THREAD

**Issue by liuhean** [vnpy/vnpy#3539]
## 环境

* 操作系统: Ubuntu 22.04 LTS
* Python版本: 3.10
* VeighNa版本: 3.91
## Issue类型
三选一：Bug/Enhancement/Question
使用可编辑源码模式安装vnpy_ctp报错，我将vnpy_ctp的代码放在一个文件夹，使用 pip install -e 模式，始终报错 error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

## 预期程序行为
正确安装

## 重现步骤
![image](https://github.com/vnpy/vnpy/assets/19942497/3e2e7703-344b-432c-b33a-47b056ebaae9)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
报错核心是最后一句【out of memory allocating xxxx】

编译接口所需的内存不足，升级下机器配置，或者增加虚拟内存吧。

**Comment by liuhean** [comment]
机器是4G的内存，又加了4G的虚拟缓存的内存，还是不行
