### ISSUE TITLE
源码配置数据库mongodb，在pycharm中启动时报错

### ISSUE THREAD

**Issue by canghaiwolong666** [vnpy/vnpy#3541]
## 环境

* 操作系统: 如Windows 11
* Python版本: python10
* VeighNa版本: VeighNa Studio-3.9.1

![Uploading 微信截图_20240602143544.png…]()
![Uploading 微信截图_20240602143643.png…]()

**Comment by canghaiwolong666** [comment]
![微信截图_20240602143544](https://github.com/vnpy/vnpy/assets/45677867/e420d803-bf41-44c1-8d73-92f937066071)
![微信截图_20240602143643](https://github.com/vnpy/vnpy/assets/45677867/67ceea2e-3a99-4e56-98c2-ddb0114facd3)

**Comment by vnpy** [comment]
数据服务相关的datafeed字段中，不应该填写mongodb（这是数据库）
