### ISSUE TITLE
UI界面会出现奇怪的glitch

### ISSUE THREAD

**Issue by morty6688** [vnpy/vnpy#3553]
## 环境

* 操作系统: Windows 11 22631.3880
* Python版本: VeighNa Studio-3.9.2自带的
* VeighNa版本: 3.9.2

## Issue类型
三选一：Bug

## 预期程序行为
UI各项功能没有什么问题

## 实际程序行为以及重现步骤
0. 使用run.py启动程序
1. 鼠标在如图位置向上拖动
![python_0KglWMfoZL](https://github.com/user-attachments/assets/f9f93848-a229-4e97-bf0f-110d24765fee)
2. UI界面会变成如图所示：
![SOGOUSmartAssistant_ZggypoQFhV](https://github.com/user-attachments/assets/89469e31-2a32-485f-9e71-9abb7ef33976)
3. 恢复窗口再重新最大化就会变成这样，左下角日志窗口出现奇怪的glitch：
![SOGOUSmartAssistant_0Hn8tXmtqq](https://github.com/user-attachments/assets/bb02409e-dceb-4b6a-ae00-60ebc114ad8e)

**Comment by vnpy** [comment]
分辨率不足，请确保使用1920x1080以上分辨率，以及将缩放调小到合适的比例

**Comment by morty6688** [comment]
> 分辨率不足，请确保使用1920x1080以上分辨率，以及将缩放调小到合适的比例

现在是4k 300%缩放，缩放调小了看着难受。不过还有一个解决办法是把字体大小改成6，也可以解决
