### ISSUE TITLE
调整字体以后，各个组件表头字体没有变化？

### ISSUE THREAD

**Issue by morty6688** [vnpy/vnpy#3554]
## 环境

* 操作系统: Windows 11 22631.3880
* Python版本: VeighNa Studio-3.9.2自带的
* VeighNa版本: 3.9.2

## Issue类型
三选一：Bug？

## 实际程序行为
调小字号以后，除了表头以外的字体缩小了，但是表头字体没有变化
![image](https://github.com/user-attachments/assets/9c6a61f6-a6c2-4449-b321-81a2bf1df2da)

**Comment by vnpy** [comment]
表头字号目前是跟随操作系统的配置，无法通过全局设置进行调整

**Comment by vnpy** [comment]
已经修复，非常感谢

**Comment by morty6688** [comment]
> 已经修复，非常感谢

问下大佬，这个是在3.9.3修复的吗

**Comment by vnpy** [comment]
> > 已经修复，非常感谢
> 
> 问下大佬，这个是在3.9.3修复的吗

是的

**Comment by vnpy** [comment]
> > 已经修复，非常感谢
> 
> 问下大佬，这个是在3.9.3修复的吗

抱歉之前搞错了，这个问题还没有修复，我们后续来看下能否处理

**Comment by vnpy** [comment]
尝试通过QApplication.setStyleSheet来进行全局修改，但是这种方法对于表格的表头文字依然无法生效，应该需要逐个对象进行设置，无法在全局级别直接定义。
