### ISSUE TITLE
找不到数据库驱动vnpy_mongodb，使用默认的SQLite数据库

### ISSUE THREAD

**Issue by jasonudu** [vnpy/vnpy#3555]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如3.10.10
* VeighNa版本: 如v3.9.2

## Issue类型
三选一：Bug

## 实际程序行为
数据库设置为：
![image](https://github.com/user-attachments/assets/4236cfb6-5b31-4a85-96fc-aafd143ade32)
代码运行bug：找不到数据库驱动vnpy_mongodb，使用默认的SQLite数据库
![image](https://github.com/user-attachments/assets/81c88219-3062-4949-bcab-3a6dd76a838b)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
`pip install vnpy_mongodb`

安装下模块即可
