### ISSUE TITLE
是否再次考虑添加akshare数据源

### ISSUE THREAD

**Issue by liveangela** [vnpy/vnpy#3564]
原issue：#3300

貌似akshare已经添加了分钟级别的数据支持：
[期货分时数据](https://akshare.akfamily.xyz/data/futures/futures.html#id60)
[股票分时数据](https://akshare.akfamily.xyz/data/stock/stock.html#id25)

主要是已支持的这些datafeed对于学生党而言太贵了……

**Comment by vnpy** [comment]
由于往年社区用户的经验，VeighNa目前对于爬虫类的数据工具都不考虑支持（因为数据质量不稳定）。

学生用户推荐申请迅投研或者米筐RQData的免费试用账号：

https://www.ricequant.com/welcome/purchase?utm_source=vnpy
https://xuntou.net/#/signup?utm_source=vnpy

上面链接是两家公司给VeighNa社区用户开放的专属申请通道，无需上传金融机构名片，申请后可以开通14天试用权限。
