### ISSUE TITLE
ubuntu 2204,no ui ，提示：

### ISSUE THREAD

**Issue by shuangxi-wang** [vnpy/vnpy#3565]
## 环境

* 操作系统: Ubuntu 22.04
* Python版本: 3.12.4
* VeighNa版本: vnpy3.9.2

## Issue类型
三选一：Bug

## 预期程序行为
可以正常订阅tick数据

## 实际程序行为
0
Subscribed to contract: IF2410
Subscribed to contract: IC2410
subscribe is ok
docker0: Resource temporarily unavailable
Aborted (core dumped)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
核心代码启动no ui代码如下：
event_engine = EventEngine()# 初始化事件引擎
main_engine = MainEngine(event_engine)# 初始化主引擎
main_engine.add_gateway(CtpGateway,"CTP")# 添加CTP网关
ctp_setting=load_json(C.fp.ctp_autoP)# 加载CTP配置
main_engine.connect(ctp_setting, "CTP")

def process_tick_event(event):
    tick: TickData = event.data
event_engine.register(EVENT_TICK, process_tick_event)# 订阅tick事件
subscribe_dominant_contracts()# 订阅主力合约

**Comment by vnpy** [comment]
`docker0: Resource temporarily unavailable`

该信息说明你的Docker进程发生异常崩溃了，请检查镜像中的相关程序运行逻辑。
