### ISSUE TITLE
Ubuntu 20.04 no_ui运行webtrader

### ISSUE THREAD

**Issue by zhangweilun** [vnpy/vnpy#3569]
## 环境

* 操作系统: 如Windows 11或者Ubuntu 20.04
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
linux可以后台运行webtrader程序

## 实际程序行为
官方noui脚本不支持

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by flycocopig** [comment]
`
# -*- coding: utf-8 -*-
import multiprocessing
import sys
from time import sleep
from datetime import datetime, time
from logging import INFO
import json
import subprocess
import threading

from vnpy.event import EventEngine
from vnpy.trader.setting import SETTINGS
from vnpy.trader.engine import MainEngine

from vnpy_webtrader import WebTraderApp

from vnpy_ctp import CtpGateway
from vnpy_ctptest import CtptestGateway

from vnpy_ctastrategy import CtaStrategyApp
from vnpy_ctastrategy.base import EVENT_CTA_LOG

from vnpy.trader.utility import load_json, save_json, get_file_path



# 配置文件路径
config_filepath = 'config.json'
print(get_file_path(config_filepath))

DAY_START = time(8, 45)
DAY_END = time(15, 0)

NIGHT_START = time(20, 45)
NIGHT_END = time(2, 45)


ctp_setting = {
    "用户名": 'xxxx',
    "密码": 'xxxx',
    "经纪商代码": '',
    "交易服务器": '',
    "行情服务器": '',
    "产品名称": '',
    "授权编码": '',
    "产品信息": ''
}

# 读取配置文件
def load_config(filepath: str) -> dict:
    """加载配置文件"""
    with open(filepath, 'r') as f:
        config = json.load(f)
    return config

# 检查交易时段
def check_trading_period():
    """"""
    current_time = datetime.now().time()

    trading = False
    if (
        (current_time >= DAY_START and current_time <= DAY_END)
        or (current_time >= NIGHT_START)
        or (current_time <= NIGHT_END)
    ):
        trading = True

    return trading

# 子进程运行函数
def run_child(req_address: str, sub_address: str, ):
    """
    运行在子进程中。
    """
    SETTINGS["log.file"] = True

    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    # main_engine.add_gateway(CtpGateway)
    main_engine.add_gateway(CtptestGateway)
    cta_engine = main_engine.add_app(CtaStrategyApp)
    web_engine = main_engine.add_app(WebTraderApp)
    main_engine.write_log("主引擎创建成功")

    log_engine = main_engine.get_engine("log")
    event_engine.register(EVENT_CTA_LOG, log_engine.process_log_event)
    main_engine.write_log("注册日志事件监听")

    # main_engine.connect(ctp_setting, "CTP")
    main_engine.connect(ctp_setting, 'CTPTEST')
    main_engine.write_log("连接CTPTEST接口")

    sleep(10)
    web_engine.start_server(req_address, sub_address)
    sleep(10)

    cta_engine.init_engine()
    main_engine.write_log("CTA策略初始化完成")

    cta_engine.init_all_strategies()
    sleep(60)   # 留足够的时间完成策略初始化
    main_engine.write_log("CTA策略全部初始化")

    cta_engine.start_all_strategies()
    main_engine.write_log("CTA策略全部启动")

    while True:
        sleep(10)

        trading = check_trading_period()
        if not trading:
            print("关闭子进程")
            main_engine.close()
            sys.exit(0)

# 启动 Uvicorn 服务器和 RPC 服务器
def start_web_rpc_client(host: str, port: str):
    """启动Uvicorn服务器和RPC服务器"""

    # 启动Uvicorn服务器
    uvicorn_cmd = [
        sys.executable,
        "-m",
        "uvicorn",
        "vnpy_webtrader.web:app",
        f"--host={host}",
        f"--port={port}"
    ]
    uvicorn_process = subprocess.Popen(uvicorn_cmd)
    uvicorn_process.wait()

# 父进程运行函数
def run_parent():
    """
    运行在父进程中。
    """
    print("启动CTA策略守护父进程")

    child_process = None
    web_rpc_process = None

    while True:
        trading = check_trading_period()

        # 在交易时段启动子进程
        if trading and child_process is None:
            print("启动子进程")
            child_process = multiprocessing.Process(
                target=run_child,
                args=(
                    'tcp://127.0.0.1:2014',
                    'tcp://127.0.0.1:4102'
                ))
            child_process.start()
            print("子进程启动成功")

        # 非交易时段则退出子进程
        if not trading and child_process is not None:
            if not child_process.is_alive():
                child_process = None
                print("子进程关闭成功")

        # 启动 Web 服务和 RPC 服务器
        if web_rpc_process is None:
            print("启动Web服务和RPC服务器")
            # config = load_config(config_filepath)
            web_rpc_process = multiprocessing.Process(
                target=start_web_rpc_client,
                args=(
                    '127.0.0.1',
                    '8000'
                )
            )
            web_rpc_process.start()
            print("Web服务和RPC服务器启动成功")

        sleep(5)

if __name__ == "__main__":
    """ 命令行启动web trader， 未经过验证，不知道是否正确"""
    run_parent()
`

以上是我这两天写的运行webtrader的脚本，具体还没经过测试。可以一起研究看看，建议官方出一个no ui 运行webtrader的example

**Comment by vnpy** [comment]
WebTrader更多作为如何使用Web方式访问控制VeighNa系统的DEMO参考，仅推荐有前后端Web开发经验的用户使用。
