### ISSUE TITLE
[QUESTION] Is this project's .exe file supported by proton or wine for running inside linux environment ?

### ISSUE THREAD

**Issue by Greatz08** [vnpy/vnpy#3573]
On Main Website i am seeing two links which are both .exe so thought to ask if the exe is compatible with wine or proton so that we can use it in linux directly

**Comment by vnpy** [comment]
VeighNa supports Linux system, there is no need to use proton or wine.

At the moment, we provide official support for Ubuntu 22.04 LTS.
