### ISSUE TITLE
Mac M1 zsh: segmentation fault错误

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#3575]
## 环境

* 操作系统: Apple M1 Max Macos 15.0.1
* Python版本: VeighNa 最新版

## Issue类型
三选一：Question

运行Demo后, 报错zsh
python run.py

zsh: segmentation fault  python run.py

还找不到相关解决方案

**Comment by yhmickey** [comment]
python 3.10 没出现问题,  python 3.12环境出现该问题

**Comment by vnpy** [comment]
请问使用的Python是操作系统自带的吗，还是conda之类的？

**Comment by yhmickey** [comment]
使用的conda 建的环境

**Comment by vnpy** [comment]
vnpy_ctp项目的README里有强调，不能用conda环境（因为二进制链接库和官方不兼容），请换回官方Python发行版
