### ISSUE TITLE
[Bug] ubuntu下段错误 (核心已转储)

### ISSUE THREAD

**Issue by Huasushis** [vnpy/vnpy#3576]
## 环境

* 操作系统: Ubuntu 23.10
* Python版本: 3.12.7
* VeighNa版本: 3.9.3

## Issue类型
三选一：Bug

## 预期程序行为

正常运行

## 实际程序行为

在运行 `qapp = create_qapp()` 出现段错误。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

使用miniconda，安装python3.12环境

`conda install -c conda-forge ta-lib;`

下载压缩包后运行

`. install.sh python`

然后发现包不全又运行了：

`pip install vnpy_ctastrategy vnpy_ctabacktester vnpy_spreadtrading vnpy_optionmaster vnpy_portfoliostrategy vnpy_algotrading vnpy_scripttrader vnpy_paperaccount vnpy_chartwizard vnpy_portfoliomanager vnpy_rpcservice vnpy_datamanager vnpy_datarecorder vnpy_excelrtd vnpy_webtrader vnpy_rest vnpy_websocket vnpy_ctp vnpy_rqdata vnpy_tushare vnpy_ifind vnpy_riskmanager vnpy_riskmanager vnpy_sqlite vnpy_tushare`

然后qt报错又运行了：`sudo apt install libxcb-*`

最后尝试运行readme中的代码和example下的veighna_trader，python不报错了，但是都出现了段错误。在shell里面一步一步运行代码发现`qapp = create_qapp()`出错。

**Comment by vnpy** [comment]
请使用官方发布的Python（如操作系统自带版本），不要使用conda环境
