### ISSUE TITLE
希望增加工作目录变更的支持

### ISSUE THREAD

**Issue by One-sixth** [vnpy/vnpy#3577]
## 环境

* 操作系统: Windows 11
* Python版本: VeighNa Studio-3.9.2
* VeighNa版本: VeighNa Studio-3.9.2

## Issue类型
三选一：Enhancement

## 预期程序行为
希望能增加参数或函数，能手动指定 MainEngine 的工作文件夹和 配置文件夹的名字
我在本地vnpy做了这样的修改，可以贡献代码

例如这样的
```python
work_dir = 'D:/vnpy'
cfg_dir_name='.vntrader'
MainEngine(event_engine, work_dir, cfg_dir_name)
```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by noranhe** [comment]
现在版本图形界面启动前只要在【交易】界面右下角选择【运行目录】即可指定工作目录
脚本启动也只需在指定工作目录下创建.vntrader文件夹并在该目录下运行脚本即可指定工作目录

**Comment by One-sixth** [comment]
@noranhe 你好，我是想这样做的。在同一个根目录下。共享同一个策略文件夹。然后用多个 cfg_dir_name 来同时使用多个账号。
我主要是用脚本启动的。所以想用函数来容易控制一些

**Comment by vnpy** [comment]
这块使用方法和目前VeighNa平台标准用法有所区别，暂时不考虑在官方版本中添加
