### ISSUE TITLE
SimNow 模拟账户 4097 错误

### ISSUE THREAD

**Issue by jnxyatmjx** [vnpy/vnpy#3578]
## 环境

* 操作系统: 如Windows 10 64位
* Python版本: Python 3.10.9
* VeighNa版本: VeighNa Studio-3.9.3

## Issue类型
三选一：Question

## 预期程序行为
CTP正常登录

## 实际程序行为
使用SimNow账号登陆时，报错如下：
CThostFtdcUserApiImplBase::OnSessionDisconnected[00000185E2A45128][112918608][ 4097]

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://github.com/user-attachments/assets/6ed757e1-6100-400c-87c4-3c70558e181f)
![image](https://github.com/user-attachments/assets/6b240ac3-4259-488e-ba1e-0072fd978dd1)
![image](https://github.com/user-attachments/assets/c7ff8d09-2acf-4364-90b5-61548f28a6e1)
交易时段 使用以上信息登录时报错

**Comment by jnxyatmjx** [comment]
更换了最新版本ctp交易库以后，交易服务至少不报错了，不过行情服务依然报错。不知道个版本搞错了。
![image](https://github.com/user-attachments/assets/8f81a488-fed6-4b07-ae96-c0c0fc2377ab)

**Comment by jnxyatmjx** [comment]
> 更换了最新版本ctp交易库以后，交易服务至少不报错了，不过行情服务依然报错。不知道个版本搞错了。 ![image](https://private-user-images.githubusercontent.com/9018335/376846406-8f81a488-fed6-4b07-ae96-c0c0fc2377ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDAwNzMsIm5iZiI6MTcyOTAzOTc3MywicGF0aCI6Ii85MDE4MzM1LzM3Njg0NjQwNi04ZjgxYTQ4OC1mZWQ2LTRiMDctYWU5Ni1jMGMwZmMyMzc3YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDA0OTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU2ZDRlMTgwNjQ3NWFkMDdlYTY0MDg0ZDhmZGViZGFjNGYxOTE3NjhjOTAzZDdhM2FjYjVkODdhMDQ3ZWZiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FqW7qcRO2M2qE4ZCLmUENJHGsCxuBqUAFHiVlkQoYeI)

今早非交易时段行情服务连的是SimNow第二套环境测试环境

**Comment by vnpy** [comment]
检查下是否加载了其他接口，【只加载CTP接口】试试

**Comment by jnxyatmjx** [comment]
> 检查下是否加载了其他接口，【只加载CTP接口】试试

确认只加载了CTP接口 其他任何功能模块都未加载。依旧是行情报错 4097
![image](https://github.com/user-attachments/assets/48ad4f48-58e7-43a9-bf0e-512bad6e4451)

**Comment by vnpy** [comment]
经过测试，当前vnpy_ctp最新版本可以正常连接登录SimNow环境，建议重装后再试试

**Comment by disperaller** [comment]
> 同样报错4097，密码也改过了，行情、交易服务器也没用写反，试了好几次，就是报错
> 
> 好吧，我已经解决了，把环境从测试换成生产（实盘）就行了

请教下这个环境怎么改？我是用的examples/veighna_trader/run.py进去的 没看到哪里有更改环境的地方

**Comment by vnpy** [comment]
> > 同样报错4097，密码也改过了，行情、交易服务器也没用写反，试了好几次，就是报错
> > 好吧，我已经解决了，把环境从测试换成生产（实盘）就行了
> 
> 请教下这个环境怎么改？我是用的examples/veighna_trader/run.py进去的 没看到哪里有更改环境的地方

> pip install vnpy_ctp -U

升级vnpy_ctp到最新版本后,连接登录CTP的接口就能看到新的选项了
