### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by tutengdihuang** [vnpy/vnpy#3582]
## 环境

* 操作系统: Ubuntu 20.04.1 LTS
* Python版本: Python 3.8.9
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
- question

## 预期程序行为
-  点击登录能够正常进入交易界面。现在进不去

## 实际程序行为
- 五

## 重现步骤

![image](https://github.com/user-attachments/assets/cc026aee-d9a6-44c2-9e05-7e085faa80a0)

**Comment by vnpy** [comment]
看图中交易接口的登录字段，不是我们官方提供的标准接口，请联系提供方咨询。
