### ISSUE TITLE
执行 macos 安装失败

### ISSUE THREAD

**Issue by shichanglin5** [vnpy/vnpy#3587]
## 环境

* 操作系统: mac m1
* Python版本: python 3.10.0
* VeighNa版本: 社区分支 master

## Issue类型
三选一：Bug

## 预期程序行为
正常执行安装脚本

## 实际程序行为
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/a40a29bf-8ec4-47a6-938e-33dfabb6b183">

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/bce37e8f-1746-4c53-b84a-a79a2c763c38">

**Comment by vnpy** [comment]
1. 请使用www.python.org官网下载的Python环境
2. CTP接口请参考这里Mac系统的CTP接口安装说明：https://github.com/vnpy/vnpy_ctp
