### ISSUE TITLE
Bug:回测时候PlotDataItem.py文件报错

### ISSUE THREAD

**Issue by 3781100649** [vnpy/vnpy#3588]
## 环境

* 操作系统: Windows 11
* Python版本: 如VeighNa Studio-3.9.3
## Issue类型
Bug:
首先连接CTP ，选择CTA回测，如图
第一步：
![image](https://github.com/user-attachments/assets/04327341-977d-4816-9d72-a29709c39532)
第二步查看日志，会报如下错误
![image](https://github.com/user-attachments/assets/7ea9f484-3ff4-49a7-9bd7-72c8612b4fe0)

**Comment by 3781100649** [comment]
[cu2505.SHFE.csv](https://github.com/user-attachments/files/17956385/cu2505.SHFE.csv)
这是当天的走势数据

**Comment by vnpy** [comment]
看回测结果信息中，仅有一个交易日产生了成交，并在最后进行了当日盈亏统计。

PyQtGraph相关图表的正确绘图需要更多个交易日的数据，请拉长回测的时间范围。
