### ISSUE TITLE
能否跳过登录界面,直接使用veighna_station

### ISSUE THREAD

**Issue by jnxyatmjx** [vnpy/vnpy#3589]
## 环境

* 操作系统: 如Windows 11
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 如v2.9.0发行版或者dev branch 20211224（下载日期）

## Issue类型
Question
能否跳过veighna_station的登录操作，直接进入界面呢？
登录veighna_station这块功能，是否也是开源的呢？

**Comment by vnpy** [comment]
可以，参考本仓库中的examples目录，VeighNa Station本来就是为了方便新手用户开发的，所有功能都可以直接通过脚本运行。

**Comment by jnxyatmjx** [comment]
> 可以，参考本仓库中的examples目录，VeighNa Station本来就是为了方便新手用户开发的，所有功能都可以直接通过脚本运行。
ok了解你的意思。
我是想说在第一次打开veighna_station界面时，能否跳过以下登录界面直接使用后续功能。
![image](https://github.com/user-attachments/assets/1e4c67a8-66e3-44cc-9be5-f60fec99eaed)

**Comment by jnxyatmjx** [comment]
> 可以，参考本仓库中的examples目录，VeighNa Station本来就是为了方便新手用户开发的，所有功能都可以直接通过脚本运行。

试下了examples\veighna_trader\run.py里的可以直接运行。但是我这边总是想通过完整的软件界面 跳过登录注册功能。或者您这边能提供下登录用login.py的源码吗？

**Comment by jnxyatmjx** [comment]
额搞了一天，通过反编译已经把login.pyc还原了。station软件已经可以 略过登录 进入界面了。
