### ISSUE TITLE
Python3.12环境下 安装vnpy_tap失败

### ISSUE THREAD

**Issue by Ke1th4** [vnpy/vnpy#3596]
## 环境

* 操作系统:  Windows 11
* Python版本: 3.12
* 编译器: PyCharm

## Issue类型
三选一：Bug

## 预期程序行为
在运行vnpy_tap的setup.py脚本后，应该显示正常安装vnpy_tap的流程

## 实际程序行为
在运行之后报错，无法安装

## 重现步骤
安装Python3.12，安装Visual Studio 2022，下载vnpy_tap 源码，在环境中运行setup.py脚本

(venv) PS C:\Users\keith.yuan\PycharmProjects\VNPY-py12\vnpy_tap-main> python setup.py install         
running install

针对Bug类型Issue，请提供具体重现步骤以及报错截图

building 'vnpy_tap.api.vntaptd' extension
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ivnpy_tap/api/include -Ivnpy_tap/api/vntap -IC:\Users\keith.yuan\PycharmProjects\VNP
Y-py12\venv\include -IC:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\include -IC:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\
vnpy_tap/api/include\pybind11/pybind11.h(1892): error C2027: 使用了未定义类型“_frame”
C:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\include\pytypedefs.h(22): note: 参见“_frame”的声明
vnpy_tap/api/include\pybind11/pybind11.h(1895): error C2027: 使用了未定义类型“_frame”
C:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\include\pytypedefs.h(22): note: 参见“_frame”的声明
vnpy_tap/api/include\pybind11/pybind11.h(1895): error C2027: 使用了未定义类型“_frame”
C:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\include\pytypedefs.h(22): note: 参见“_frame”的声明
vnpy_tap/api/include\pybind11/pybind11.h(1894): error C2660: “PyDict_GetItem”: 函数不接受 1 个参数
C:\Users\keith.yuan\AppData\Local\Programs\Python\Python312\include\dictobject.h(22): note: 参见“PyDict_GetItem”的声明
vnpy_tap/api/include\pybind11/pybind11.h(1894): note: 尝试匹配参数列表“()”时
vnpy_tap/api/vntap/vntaptd/vntaptd.cpp(5235): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.  
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by vnpy** [comment]
确认是Pybind11版本问题，已经完成vnpy_tap模块新版本的升级和发布，请再尝试下
