### ISSUE TITLE
希望贡献新功能，vnpy_datamanager 增加对 tick 数据的支持

### ISSUE THREAD

**Issue by One-sixth** [vnpy/vnpy#3597]
## 环境

* 操作系统: Windows 11
* Python版本: python 3.11
* VeighNa版本: 3.9.3

## Issue类型
三选一：Enhancement

## 预期程序行为
希望对 vnpy_datamanager 查看更新删除 tick数据 增加支持

已经改好，可以的话我就打开一个PR
https://github.com/One-sixth/vnpy_datamanager

![image](https://github.com/user-attachments/assets/a7ef4294-0c3d-4582-89b5-ff7e86ef9ce8)

**Comment by vnpy** [comment]
TickData的数据量较大，因此不管是导入导出或者数据查看，使用DataManager都会面临非常明显的卡顿情况，这块更推荐通过代码脚本或者专用数据库客户端（如DBeaver）来实现管理。

**Comment by One-sixth** [comment]
@vnpy 大佬说的是，但确实缺少一些简便的控件来管理 TickData （更新，查看起始结束时间 和删除），卡一点但是挺好用的（比代码脚本好用）。大佬再考虑下吗。

我修改了 download_tick_data 函数，可以分段下载（每次刷新10天），这样一键更新TickData不会爆内存。
然后修改了 TickData 默认只查看最近10天的数据，只会在加载数据时卡一下，加载完后不卡，并且大概只吃1G的内存。我在期货TickData上测试了。

**Comment by vnpy** [comment]
欢迎在DataManager仓库发个PR，25年我们将开始4.0重构，到时候会看下能否借助新的UI功能解决这块问题

**Comment by StarainX** [comment]
tick十分有必要……基于tick合成的秒周期K线对策略帮助很大。
