### ISSUE TITLE
希望推出快速入门教程

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#36]
我是刚接触的，现在下载了，还不会使用。
教程可以有个示例就行。如pyalgotrade那样，新手可以照着教程做下去就可以让程序跑起来。

希望vnpy发扬光大。

**Comment by vnpy** [comment]
谢谢你的建议，vn.trader的快速入门教程在今年的项目计划里，我最近比较忙，估计年中的时候能推出来。

**Comment by vnpy** [comment]
在官网和知乎专栏已经开始发布vn.trader的快速使用教程了，请关注。
