### ISSUE TITLE
一个策略能够同时交易多个品种，怎么做呢？

### ISSUE THREAD

**Issue by nigelliyang** [vnpy/vnpy#361]

**Comment by vnpy** [comment]
CTA策略模块不允许交易多个品种。

价差交易模块会限制以价差的形式交易多个品种。

要那种可以复杂交易的需要自己开发扩展模块。

**Comment by ujfjhz** [comment]
您的意思是不支持多品种的“组合”交易吧？如果各品种独立交易，同一个策略可以支持多品种吗？

**Comment by vnpy** [comment]
可以的，这个是CTA模块自带的功能。
