### ISSUE TITLE
okcoin接口 zlib: Error -3 while decompressing data: invalid distance too far back

### ISSUE THREAD

**Issue by nigelliyang** [vnpy/vnpy#362]
如下函数在使用zlib解压缩出现错误 zlib: Error -3 while decompressing data: invalid distance too far back
  def readData(self, evt):
        """解压缩推送收到的数据"""
        # 创建解压器
        decompress = zlib.decompressobj(-zlib.MAX_WBITS)
        
        # 将原始数据解压成字符串
        inflated = decompress.decompress(evt) + decompress.flush()
        
        # 通过json解析字符串
        data = json.loads(inflated)
        
        return data

**Comment by vnpy** [comment]
请说明你遭遇这个问题的情景？比如用的系统、Python版本，做了什么操作

**Comment by vnpy** [comment]
无更新，关闭issue。

**Comment by yiyisan** [comment]
本以为报错的原因是zlib设置，后来调试才发现，原来是OKEx传过来的数据大部分是压缩的，有部分竟然是没有压缩的，没压缩的就会报这个错误，有点坑
