### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by ChenYingfeng** [vnpy/vnpy#363]
1.6.2 运行出现以下错误：

RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

安装了pyqt4

**Comment by vnpy** [comment]
建议不要同时安装PyQt4和PyQt5，否则可能导致冲突，卸载其中的一个吧
