### ISSUE TITLE
when using Xspeed gateway , the ctaengine will receive messy tick time

### ISSUE THREAD

**Issue by zzniwei** [vnpy/vnpy#364]
when start ctaStrategy using Xspeed gateway, it display randomly with massy tick time format like below ,
"
16:04:32	CTA引擎启动成功
16:04:34	策略加载成功
16:04:34	time data '20170615 99:99:99.9' does not match format '%Y%m%d %H:%M:%S.%f'
16:04:34	time data '20170615 99:99:99.9' does not match format '%Y%m%d %H:%M:%S.%f'
"
I fix the issue with code in ctaEngine.py file  processTickEvent function like below  
"
    def processTickEvent(self, event):
        """处理行情推送"""
        tick = event.dict_['data']
        # mylogger.debug("enter processTickEvent tick.date is %s, tick.time is %s " % (tick.date, tick.time))
        # 收到tick行情后，先处理本地停止单（检查是否要立即发出）
        self.processStopOrder(tick)
        
        # 推送tick到对应的策略实例进行处理
        if tick.vtSymbol in self.tickStrategyDict:
            # 将vtTickData数据转化为ctaTickData
            ctaTick = CtaTickData()
            d = ctaTick.__dict__
            for key in d.keys():
                if key != 'datetime':
                    d[key] = tick.__getattribute__(key)
            
            # 添加datetime字段
            #Xspeed 传入的tick.time 字段是'99:99:99.9'系统报错程序中断
            #self.writeCtaLog('tick.date is %s, tick.time is %s' % (tick.date, tick.time))
            try:
                ctaTick.datetime = datetime.strptime(' '.join([tick.date, tick.time]), '%Y%m%d %H:%M:%S.%f')
            except ValueError as e:
                self.writeCtaLog(e.message)
                return
            
"

**Comment by vnpy** [comment]
这个情况来源于柜台层面推送的错误数据，具体原因我也不清楚，但只存在于测试环境，我在实盘系统中目前没遇到过。

**Comment by zzniwei** [comment]
建议将捕获异常代码的添加入正式的发布中，增加程序健壮性和容错，万一收到的实盘数据有异常呢？thanks

**Comment by vnpy** [comment]
已添加
