### ISSUE TITLE
关于1.6.2的代码结构

### ISSUE THREAD

**Issue by JasonXZh** [vnpy/vnpy#365]
是不是只有vnpy目录下的代码有用？其他几个目录的代码是重复的？除vnpy目录外删掉也行？

**Comment by vnpy** [comment]
archive中的是项目老代码，但是考虑可能有些人会用到暂时保留，未来会删除
docker中的是DOCKER应用模式下的代码，和目前的结构有所区别，用不着可以删掉
examples是vn.py的使用方法示例，建议保留
tutorial中的是一些特殊的实盘应用指南，因为是过去写的所以代码版本和目前已经不再通用，用不着可以删掉

**Comment by vnpy** [comment]
1.7发布正式版前，会对目录做一次清理
