### ISSUE TITLE
做回测的时候发现，不能同时载入分钟级别和日级别的bar历史行情数据

### ISSUE THREAD

**Issue by zzniwei** [vnpy/vnpy#367]
做回测的时候发现，不能同时载入分钟级别和日级别的bar历史行情数据，回测引擎返回初始化是分钟级别的bar数据，这样的话很不方便，回测不准确，建议在回测引擎和ctaEngine里面，增加载入历史日行情数据的方法

def loadBar(self, dbName, collectionName, startDate):
        """直接返回初始化数据列表中的Bar"""
        return self.initData

 def loadDailyBar(self, dbName, collectionName, days):
        """从数据库中读取Bar数据，startDate是datetime对象"""
        startDate = self.today - timedelta(days)
        
        d = {'datetime':{'$gte':startDate}}
        barData = self.dailyDbCursor.dbQuery(dbName, collectionName, d)
        
        l = []
        for d in barData:
            bar = CtaBarData()
            bar.__dict__ = d
            l.append(bar)
        return l

**Comment by vnpy** [comment]
可以通过分钟线自行聚合为日线

**Comment by zzniwei** [comment]
难道每次需要用到历史日行情，都要自己self.onbar计算均线 ？ ：（

**Comment by vnpy** [comment]
目前是的，每天实盘在跑的时候也只有通过这个方法来不断进行计算。

vn.py的定位是实盘交易，策略开发时涉及的各种比较复杂的回测计算建议通过定制化的脚本实现。
