### ISSUE TITLE
vtEngine.py中shelve.open(self.contractFileName)出现DBNoSuchFileError

### ISSUE THREAD

**Issue by ArthurSS** [vnpy/vnpy#368]
使用pip install vnpy，安装其他所有需要的拓展，直接运行run.py会出现`bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')`，原因是vtEngine.py 334行中的`shelve.open(self.contractFileName)`

除了尝试加入try-except-pass, 请问还有其他更好的解决方案吗？`shelve.open(self.contractFileName)`为什么不能自动创立文件，之前怎么没有遇到过这个问题？

**Comment by vnpy** [comment]
shelve.open函数本身是可以创建文件的，但是如果temp文件夹不存在，它是无法创建该文件夹的，导致报错。

回头来加上一个文件夹检查的逻辑。

**Comment by vnpy** [comment]
出现这个问题的原因是用户没有权限在相应路径新建目录，用管理员身份运行即可解决。
