### ISSUE TITLE
ctpGateway中对于tick数据过滤的bug

### ISSUE THREAD

**Issue by ArthurSS** [vnpy/vnpy#369]
在`vnpy/trader/gateway/ctpGateway/ctpGateway.py`中有对于tick的过滤：

> """行情推送"""
> #忽略成交量为0的无效tick数据
> if not data['Volume']:
> return

对于普通品种，这不会出现问题。但是国内商品期权市场（例如豆粕期权）实行做市商制度，在CTP中做市商提供的报价tick只有`askPrice1, bidPrice1, askVolume1, bidVolume1`四个字段，而像`Volume, openInterest, lastPrice`等字段都是空值。只有当散户或机构户与做市商达成交易，volume有更新的情况下，tick提供的字段才是完整的。

因此，以上的过滤机制会把豆粕期权市场的做市商报价全部忽略，导致市场上的报价失真。
对于Volume直接过滤可能会引起其他问题，应该寻求更好的解决办法，或者至少加一个注释。

**Comment by vnpy** [comment]
这个确实之前没有考虑到，看来交易时间段内的所有数据都不能忽略

**Comment by vnpy** [comment]
已移除该过滤。
