### ISSUE TITLE
建议把gui/log 与策略/引擎完全剥离开来

### ISSUE THREAD

**Issue by JayDeng2837** [vnpy/vnpy#370]
目前server/client的实现思路是 gateway/engine在server strategy/gui在client....
这种方法适合私募一个服务器多个交易员。

但是对很多客户，还有另外一种需求，就是策略完全在云端跑，有成交和风控事件发出报警， 然后远程发出控制指令，比如暂停某策略，重启某策略等。 所以我建议 把gui/log这部分和策略/引擎用zmq解耦和。

那样gui端用户可以有更多种选择， 比如用户可以写一个web_gui， 或者通过微信监控交互，监听引擎的log，然后把交易信息发送到微信等等

**Comment by vnpy** [comment]
这个已经在今年的开发计划里了，v1.9

**Comment by JayDeng2837** [comment]
谢谢。 那方便提供一个简单的example 无gui 启动StrategyATRRSI的步骤么?...  直接调用CTAengine.loadStrategy()等等..

**Comment by vnpy** [comment]
好的，我在1.7发布前会加上一个这样的example

**Comment by vnpy** [comment]
已完成
