### ISSUE TITLE
请问有没有64bit的版本，是不是因为一些dll是32bit的？ 

### ISSUE THREAD

**Issue by kanaxu** [vnpy/vnpy#371]

**Comment by vnpy** [comment]
目前官方没有提供64位版本，原因：
1. 部分API只有32位接口，在64位Python中使用可能出现异常
2. 部分量化相关库的64位版本稳定性不如32位
3. 32位版本的性能对于目前的应用几乎都可以满足

**Comment by kanaxu** [comment]
明白了，谢谢。 主要是觉得用深度学习去开发策略的话可能需要用到64bit的python库。
