### ISSUE TITLE
增强 docker 支持

### ISSUE THREAD

**Issue by crystalphi** [vnpy/vnpy#374]
1、完善当前的 docker 相关脚本，支持 MacOS 宿主；
2、支持 docker 环境下的图形界面程序运行。

**Comment by vnpy** [comment]
这项任务计划在Web界面版本中完成

**Comment by Wilson-G** [comment]
大佬，web界面版本有啥计划和消息么

**Comment by vnpy** [comment]
1.8即将开始做了

**Comment by vnpy** [comment]
已完成，MAC版本请测试
