### ISSUE TITLE
dbInsert bug

### ISSUE THREAD

**Issue by JayDeng2837** [vnpy/vnpy#375]
dbInsert(self, dbName, collectionName, d)

第三个参数要能序列化才行， DataRecorder里调用这个函数是直接传VtTickData, VtBarData，会报错， 改用d.__dict__才ok...

**Comment by vnpy** [comment]
`
    #----------------------------------------------------------------------
    def insertData(self, dbName, collectionName, data):
        """插入数据到数据库（这里的data可以是VtTickData或者VtBarData）"""
        self.queue.put((dbName, collectionName, data.__dict__))
        
    #----------------------------------------------------------------------
    def run(self):
        """运行插入线程"""
        while self.active:
            try:
                dbName, collectionName, d = self.queue.get(block=True, timeout=1)
                self.mainEngine.dbInsert(dbName, collectionName, d)
            except Empty:
                pass
`

插入的是data.__dict__，而非data本身
