### ISSUE TITLE
ctp 行情订阅的一个小问题

### ISSUE THREAD

**Issue by JayDeng2837** [vnpy/vnpy#377]
ctp在第一次订阅成功的时候会马上发出一个行情报文，不管是不是交易时间段。。。
比如如果我的系统是在收盘之后，15：40连接ctp成功， 那么ctp会发送订阅合约最后一笔行情， 但是时间戳会是当前的时间戳， 比如15：40：37。 这种tick应该要过滤掉才是。。

在线比对时间戳过滤掉行情，那么可能会拖慢整个dataRecorder的速度。
如果不在每个tick收到的时候进行过滤，那么建议mongodb读取historical data最好加上时间过滤把这些错字段过滤掉。。。

**Comment by vnpy** [comment]
能否给个截图？

实盘CTP的行情服务器，在非交易时段应该返回的是同一个交易session内交易时段的最后一个tick。

举例如果是中午的话，返回的是11:30收盘的tick，下午3点后应该是3点的tick，下午3点半后可能返回一个带有结算价数据的（时间戳可能是3点20-40之类的）

**Comment by KobeZhao** [comment]
“在线比对时间戳过滤掉行情，那么可能会拖慢整个dataRecorder的速度。”，拖慢速度，有没有什么数据支持呢，我就是对比时间戳过滤行情的，目前看还可以，影响不太大啊。如果改为mongodb读的时候再处理的话，，，那我觉得数据库就显得有点不完美，自己收集的宝贵tick数据，还要再清洗才能用，有点不开心

**Comment by vnpy** [comment]
用ipython的%timeit datetime.now()，我的电脑大约是948ns，约等于1微秒，每秒1000个tick的影响才1毫秒，从这个数量级看似乎确实还好

**Comment by vnpy** [comment]
行情记录功能请参考使用examples/DataRecording中的代码，定时启动和关闭行情记录进程，通过控制程序运行的时间实现无用数据过滤。
