### ISSUE TITLE
数据记录引擎，上期所部分夜盘品种缺失早盘第一根bar的问题

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#380]
**问题**：上期所夜盘23点收盘的品种，例如rb，使用DR模块由tick生成分钟bar，缺失9：00：00的第一根bar
**分析**：早盘开盘前启动DR模块，会收到ctp传送的夜盘收盘tick，时间23：00：00，而早盘开盘后第一个tick的时间是9：00：00，不符合drEngine中新开一个bar的判断条件，导致9:00:00~9:00:59的tick数据合成到了23:00:00的bar中.
`if not bar.datetime or bar.datetime.minute != tick.datetime.minute`

**Comment by freeitaly** [comment]
补充一下，由于ctpgateway里把tick.date改成的实际日期，所以早盘登录ctp后收到的夜盘收盘tick的日期修正成了当天的日期，而他的实际日期是昨天的。
可以考虑使用08：50启动dr，然后8：57开启数据落地，非交易时间收到的tick都抛弃。

**Comment by vnpy** [comment]
收到，会在v1.7中处理

**Comment by KobeZhao** [comment]
这些商品夜盘数据的坑都要自己踩过，改过才可以，还有其他的问题，还是自己根据习惯处理比较好

**Comment by vnpy** [comment]
增加对datetime小时变化的检查
`            if (not bar.datetime or 
                bar.datetime.minute != tick.datetime.minute or
                bar.datetime.hour != tick.datetime.hour):   `
