### ISSUE TITLE
每天10:15分，11:30分，15:00 和 夜盘收盘时间的tick都单独生成的一个bar的问题

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#381]
由于CTP推送每天10:15分，11:30分，15:00 和 夜盘收盘时间的tick，按照drEngine中bar切断的判断逻辑，这些tick都会单独生成的一个bar。
大佳的fork中有对此的处理
[https://github.com/msincenselee/vnpy/blob/master/vnpy/trader/app/ctaStrategy/ctaLineBar.py#L507](url)

**Comment by vnpy** [comment]
收到，会在v1.7中处理

**Comment by KobeZhao** [comment]
bar的切割还是要看个人习惯，感觉没啥太大必要统一去处理吧

**Comment by vnpy** [comment]
在examples/DataRecording中实现了定时启动和关闭行情记录进程的功能，考虑到框架不只是用于国内的期货产品，不增加以上几个特定时间数据的过滤，有需要的用户可以自己在代码中添加。
