### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by wudixy** [vnpy/vnpy#382]
参考文档上的要求进行环境安装，目前有两个问题，方便请帮忙看下
1.安装  conda install -c quantopian ta-lib=0.4.9
报错如下：
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib
  - navigator-updater
  - ta-lib 0.4.9*
Use "conda info <package>" to see the dependencies for each package.
```

2. from vnctpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。

**Comment by vnpy** [comment]
1. 请问你的Anaconda版本是？建议用4.0.0
2. vcredist x86没装

**Comment by Ken-Con** [comment]
同样问题

**Comment by Ken-Con** [comment]
使用方法一一键安装解决了

**Comment by Ken-Con** [comment]
好吧，居然anaconda 4.00完美解决

**Comment by wudixy** [comment]
搞定了，不熟悉anaconda 虚拟环境造成。但现在连接时，总是说，CTP，不合法的登录，错误代码：3,怀疑是用户名密码错误，但试验了好几次，甚至换了账号 ，都不对，配置文件应该是对的，我随便换了IP，马上就连不上了。
{
    "brokerID": "9999", 
    "mdAddress": "tcp://180.168.146.187:10031", 
    "tdAddress": "tcp://180.168.146.187:10030", 
    "userID": "mmmm",
    "password": "password"
}

**Comment by vnpy** [comment]
问题解决，关闭issue
