### ISSUE TITLE
app目录下面是 riskmanager,ctastrategy

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#383]
我以为app是一个独立的完整的小程序。
而ctastrategy只是这个vnpy的一个功能模块而已。
感觉app改名为module或其它更合适？

**Comment by vnpy** [comment]
之前也一度纠结过命名，主要考虑到底层接口和上层应用都属于模块，所以上层模块直接用module不太合适，选择了app这个词。

独立运行的完整程序，参考了flask项目的命名方法，用的examples。

有更好的建议欢迎提出
