### ISSUE TITLE
CTPGateway调用close()方法时Python.exe停止工作

### ISSUE THREAD

**Issue by sun0x00** [vnpy/vnpy#389]
## 版本
Windows Server 2016 Datacenter x64 [版本 10.0.14393]
Python 2.7.13 
Anaconda 4.4.0 (32-bit)
MSC v.1500 32 bit (Intel)] on win32
VNPY 1.6.2
## 问题
可以正常下单，订阅行情，但当调用Gateway中close()方法的时候，Python.exe停止工作。无任何异常能被捕获到，是否是DLL调用出错?

**Comment by sun0x00** [comment]
## Windows事件记录

错误应用程序名称: python.exe，版本: 0.0.0.0，时间戳: 0x5914b680
错误模块名称: vnctptd.pyd，版本: 0.0.0.0，时间戳: 0x56da9843
异常代码: 0xc0000005
错误偏移量: 0x0005dc93
错误进程 ID: 0x578
错误应用程序启动时间: 0x01d2f550263765c2
错误应用程序路径: C:\ProgramData\Anaconda2\python.exe
错误模块路径: D:\python_project\vnpy_01\vnpy\api\ctp\vnctptd.pyd
报告 ID: dfeb58c2-a4f1-4afb-a308-46dabfab8d22
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by sun0x00** [comment]
:-p
尴尬了，应该是我触发了close之后没有解除Gateway在EventEngine中注册的事件，导致了未知异常

**Comment by vnpy** [comment]
除非退出程序，不建议直接close接口的，某些接口C++层面的资源释放并不完善，可能导致程序崩溃。一定要动态开和关接口，建议采用子进程的形式。
