### ISSUE TITLE
代码中vtSymbol与symbol时常混用，是否考虑统一

### ISSUE THREAD

**Issue by geraybos** [vnpy/vnpy#390]
vtSymbol在一些情况下不带GatewayName，和symbol等价(比如在行情记录中)，个人理解是为了例如在只使用CTP环境下，减少冗余信息。但是带来了混乱，希望可以考虑统一vtSymbol为Symbol+Gateway的格式。

**Comment by vnpy** [comment]
vtSymbol通常是Symbol.Exchange，因为大部分情况下用户不会同时登录两个交易相同标的的接口。

CTP接口主要是出于方便性考虑直接采用了Symbol，确实有考虑也改成Symbol.Exchange的形式，但是要看社区的意见。

**Comment by vnpy** [comment]
根据目前社区的使用情况暂时不考虑修改
