### ISSUE TITLE
安装中出现 UnsatisfiableError, specification conflict问题

### ISSUE THREAD

**Issue by qianhua1009** [vnpy/vnpy#392]
conda install -c quantopian ta-lC:\WINDOWS\system32>conda install -c quantopian ta-lib=0.4.9
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in
  - matplotlib
  - navigator-updater
  - ta-lib 0.4.9*
Use "conda info <package>" to see the dependencies for each package.

Anaconda 安装32位Python2.7版  为什么会有冲突呢  请教大神如何解决

**Comment by Ken-Con** [comment]
安装4.00版本

**Comment by qianhua1009** [comment]
非常感谢！ 4.0.0已解决
