### ISSUE TITLE
运行run.py　遇到找不到指定模块

### ISSUE THREAD

**Issue by zhikook** [vnpy/vnpy#393]
File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy\api\ctp\__init__.py", line 3, in <module>
    from vnctpmd import MdApi

ImportError: DLL load failed: 找不到指定的模块。

**Comment by zsluedem** [comment]
什么版本的？
D:\ProgramData\Anaconda2\lib\site-packages\vnpy\api\ctp里面有什么文件

**Comment by vnpy** [comment]
1. 检查Anaconda版本是否为4.0.0 Python 2.7 32位
2. 检查vcredist x86 2013是否安装

**Comment by zhikook** [comment]
@zsluedem thanks ,list:

__init__.py
__init__.pyc
ctp_data_type.py
ctp_data_type.pyc
thostmduserapi.dll
thostmduserapi.so
thosttraderapi.dll
thosttraderapi.so
vnctpmd.pyd
vnctptd.pyd

**Comment by zhikook** [comment]
@vnpy 谢谢，vcredist x86 2013安装版本出错，我想问题应该是这个，现在这个问题没有了，不过遇到新问题，我正在处理。

  File "D:\ProgramData\Anaconda2\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)

  File "D:\ProgramData\Anaconda2\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)

  File "D:\ProgramData\Anaconda2\lib\bsddb\__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)

DBNoSuchFileError: (2, 'No such file or directory')

**Comment by zhikook** [comment]
#----------------------------------------------------------------------
    def loadContracts(self):
        """从硬盘读取合约对象"""
        f = shelve.open(self.contractFileName)
        if 'data' in f:
            d = f['data']
            for key, value in d.items():
                self.contractDict[key] = value
        f.close()
        
请问是否要对那个文件设置读写权限，我的操作系统是ｗｉｎｄｏｗｓ７　３２

**Comment by vnpy** [comment]
需要管理员权限，用管理员账号来启动Python

**Comment by zhikook** [comment]
@vnpy 好的，谢谢。原先的电脑比较慢，等过一阵子换一个配置高的电脑再来弄。

**Comment by Hilyme** [comment]
我的系统是win10，conda是4.3.30的，python是2.7的，然后vc是2015的，还是from .vnctpmd import MdApi
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序  这个问题，这是什么原因
