### ISSUE TITLE
连接CTP 错误代码3 不合法的登录    

### ISSUE THREAD

**Issue by qianhua1009** [vnpy/vnpy#397]
[求助大神]
管理员权限运行python run.py启动后 连接CTP显示不合法的登录  
ctp_connect.json是用 sublime修改的   simnow 9999的brokerID， userID是6位数的在simnow上可以登录simnow  

截图如下

CThostFtdcUserApiImplBase::OnSessionDisconnected[0349ACA4][-2123169577][ 4097]
![image](https://user-images.githubusercontent.com/1007863/27990822-954d6a48-6495-11e7-9ae8-303a66ddb4f7.png)
![image](https://user-images.githubusercontent.com/1007863/27990824-a86c65b6-6495-11e7-8f6d-b5262ad445ae.png)
![image](https://user-images.githubusercontent.com/1007863/27990825-b7a466e6-6495-11e7-847b-2c59083f853d.png)

**Comment by vnpy** [comment]
请修改anaconda2目录下的vnpy文件夹中的CTP_connect.json，而不是你下载的那个目录下的。这个关于配置Json的问题v1.7会解决掉

**Comment by vnpy** [comment]
已经实现了优先使用程序运行目录下的json配置文件

**Comment by qianhua1009** [comment]
非常感谢您的回答，我也刚刚修改了anaconda2目录下的vnpy文件夹中的CTP_connect.json，可是问题仍旧持续
我的run.py文件放在C:\Anaconda\Anaconda2\Lib\site-packages\vnpy\trader 路径里 
放在其他路径也没有不同 一样报同样错误

**Comment by vnpy** [comment]
下个最新的Dev试试看吧，现在直接使用examples/VnTrader文件夹下的json配置文件了
