### ISSUE TITLE
问题以及建议

### ISSUE THREAD

**Issue by zuroc** [vnpy/vnpy#4]
1.

PyQT是一个图形界面库，感觉很重。
如果只是要用到定时器，是不是可以考虑
threading.Timer 
或者
sched https://docs.python.org/2/library/sched.html

2.

lts 能不能给一个hello word的example？
比如， 如何买入，卖出
现在不太明白如何用

3. 

是不是支持linux？能不能写一个安装的setup.py方便安装

4. 

是不是可以搞一个微信群或者qq群方便交流
或者 https://bearychat.com/ ，这个支持保存历史聊天记录

5.
现有的基于QT的事件搞得太复杂
不太好理解
是否可以考虑改用
http://pythonhosted.org//blinker/
基于信号驱动
使用函数式编程，而不是类编程。
这样，一个信号可以挂载多个函数。
代码更加轻量级，而且更加灵活。

**Comment by vnpy** [comment]
1. Threading.Timer是一次性运行，可能并不适合这个任务，但是你确实可以使用threading创建另一个线程的方式来执行定时器的任务。因为GIL的关系，我个人倾向于在Python里能不多开线程就不多开，Qt里的Timer应该是基于主线程的事件循环，所以没有用到另外的线程。

2. 计划的下一篇教程里会包含一些LTS的例子，最近有些忙，可能要下周发布吧，教程会发布在vnpy.org。

3. vn.lts中包含了封装的源代码，我自己没有测试过，整个开发中没有使用windows独有的库，应该也可以在linux上编译。

4. 交流群的想法挺好，目前看来github不是那么方便交流，我来看看有什么选择

5. blinker这个库我大概看了下，类似于pyqt里的signal/slot不能很好的管理event handler的执行顺序，另外也不便于在程序运行中实时创建新的事件（比如对特定下单编号的监听等等）。EventEngine本身除了Timer外没有使用Qt的事件机理，完全是纯python实现的。

**Comment by vnpy** [comment]
已经发布了hello world example，在vn.demo下面可以看到。

另外搞了个QQ群：262656087，感兴趣可以加下。
