### ISSUE TITLE
关于gateway的一点建议

### ISSUE THREAD

**Issue by JayDeng2837** [vnpy/vnpy#402]
目前的架构是TD/MD绑在一块的。如果要扩展到多账户的情况下，就我自己的经验看，以下可能是需要的，抛砖引玉哈。

1. vtSymbol 改成 symbol.Gateway的形式， 引擎自动根据vtSymbol的订阅请求加载gateway模块
2. 把TD，MD分开。 单独弄一个MD的配置文件。 这样有多个帐户的情况下，可以指定某一个帐户的MD来作为行情源。
3. 把account, subscription symbols, strategy module, 放在策略启动的配置中。那样可以一份策略代码跑多个帐户。
4. （多进程，每个策略实例启动一个进程，这样可以防止某个策略的bug让所有策略crash，不过不知道这样做多进程通信的overhead会导致整体运行时间并不能提速多少...）

**Comment by vnpy** [comment]
1. 这个考虑过，后来没做因为考虑到有些策略会涉及行情源和交易通道不是一个接口的问题
2. 多账户的东西v1.8我会做个比较完整的演示例子，基于多进程架构

**Comment by JayDeng2837** [comment]
好的 谢谢
