### ISSUE TITLE
关于日志打印的一点建议

### ISSUE THREAD

**Issue by zzniwei** [vnpy/vnpy#405]
我在编写自己的代码调测的过程中，发现系统日志打印不是很方便，自己写了个日志打印的类，在写程序
的时候可以自己打印日志，方面程序调测和数据分析，建议vnpy能不能提供一个强大日志打印模块，方便大家调测系统。

--------------------
自定义日志类
class AppLoger(object):
    """自定义日志"""
    def __init__(self):
        super(AppLoger, self).__init__()

        self.loger = logging.getLogger('test')
        
        #设置日志格式
        fmt = '%(asctime)s %(filename)s[line:%(lineno)d] %(thread)d %(levelname)s %(message)s'
        datefmt = '%a, %d %b %Y %H:%M:%S'
        self.rotation_handler =handlers.RotatingFileHandler('vnapp.log', 'a', 10*1024*1024, 5)
        rotation_handler_formater = logging.Formatter(fmt,datefmt)
        self.rotation_handler.setFormatter(rotation_handler_formater)
        #设置日志级别
        self.rotation_handler.setLevel(logging.DEBUG)
        self.loger.addHandler(self.rotation_handler)

    def get_logger(self):
        return self.loger

    def set_log_level(self, level):
        self.loger.setLevel(level)

    def set_log_format(self, para):
        self.rotation_handler.setFormatter(para)
--------------------------------
使用

from vtFunction import AppLoger
apploger = AppLoger()
apploger.set_log_level(logging.INFO)
DtpLogger = apploger.get_logger()
----------------------------------
样例

Fri, 14 Jul 2017 09:30:56 strategyDualThrustPlus.py[line:220] 22680 INFO self.range 66.000000, self.longEntry 3689.200000, self.shortEntry 3662.800000 
Fri, 14 Jul 2017 09:30:56 strategyDualThrustPlus.py[line:220] 22680 INFO self.range 66.000000, self.longEntry 3689.200000, self.shortEntry 3662.800000 
Fri, 14 Jul 2017 09:30:56 strategyDualThrustPlus.py[line:220] 22680 INFO self.range 66.000000, self.longEntry 3689.200000, self.shortEntry 3662.800000 
Fri, 14 Jul 2017 13:36:57 strategyDualThrustPlus.py[line:265] 22680 INFO open long position at 3691.200000 with orderid CtaStopOrder.1 bartime None self.pos 0
Fri, 14 Jul 2017 13:36:57 strategyDualThrustPlus.py[line:265] 22680 INFO open long position at 3691.200000 with orderid CtaStopOrder.1 bartime None self.pos 0
Fri, 14 Jul 2017 13:36:57 strategyDualThrustPlus.py[line:265] 22680 INFO open long position at 3691.200000 with orderid CtaStopOrder.1 bartime None self.pos 0
Fri, 14 Jul 2017 14:55:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6093.800000
Fri, 14 Jul 2017 14:55:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6093.800000
Fri, 14 Jul 2017 14:55:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6093.800000
Fri, 14 Jul 2017 14:55:57 strategyDualThrustPlus.py[line:339] 22680 INFO endtrading sell position at 3694.400000 with orderid CtaStopOrder.2 bartime None self.pos 2
Fri, 14 Jul 2017 14:55:57 strategyDualThrustPlus.py[line:339] 22680 INFO endtrading sell position at 3694.400000 with orderid CtaStopOrder.2 bartime None self.pos 2
Fri, 14 Jul 2017 14:55:57 strategyDualThrustPlus.py[line:339] 22680 INFO endtrading sell position at 3694.400000 with orderid CtaStopOrder.2 bartime None self.pos 2
Fri, 14 Jul 2017 14:56:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6095.400000
Fri, 14 Jul 2017 14:56:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6095.400000
Fri, 14 Jul 2017 14:56:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6095.400000
Fri, 14 Jul 2017 14:57:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6093.600000
Fri, 14 Jul 2017 14:57:57 strategyRbreaker.py[line:440] 22680 INFO cover the positon time prev_close:6108.200000, bar.close:6093.600000
------------------------

**Comment by vnpy** [comment]
问下logger的开销（耗时）大概有多大？分别以下两种情况：
1. 达到log_level后输出在屏幕上和日志里
2. 没达到log_level被抛弃

**Comment by vnpy** [comment]
简单测试了下，发现logging模块的额外开销很小，v1.8里计划将所有日志的输出使用logging模块实现

**Comment by JayDeng2837** [comment]
@vnpy logging模块打印文件开销不大的, 如果你还嫌慢可以注册到timer事件中，1秒中打印一次。 打印到屏幕比较耗时。

**Comment by lamter** [comment]
使用`logging`库的话，可以再使用`log4mongo`。`log4mongo`提供了一个`mongohandler`给`logging`，可以将日志直接保存到`MongoDB`。但是目前对需要授权登陆的`database`有BUG，需要用一些`Python`黑魔法绕过。

**Comment by vnpy** [comment]
最近在想logging模块在VnTrader中的使用价值和方式：

1. VnTrader中的日志事件目前是通过EventEngine发出的，可以注册任意函数来处理该日志（UI更新、打印、插入数据库等），其中UI更新对于logging模块是不支持的（可能需要自己实现一个Handler？）

2. 使用logging的价值不知道具体体现咋哪些方面？

**Comment by vnpy** [comment]
已完成
