### ISSUE TITLE
MongoDB数据库改成只使用一个database

### ISSUE THREAD

**Issue by lamter** [vnpy/vnpy#407]
我建议做出如题的改动：
1. MongoDB数据库改成只使用一个database

原因是：
1. MongoDB的用户权限设置是针对一个database来设置的，单一的database有利于权限管理。

方案：
1. 使用单一的database，命名为 "vnpy"。
2. 大部分 collection 命名不变，设置为保存在 "vnpy" 下。
3. drEngine 模块进行数据录入时，对应的 collection name 使用“合约名_数据粒度”这样格式命名，如“rb1801_tick"，"ZC807_1min"。

需要做出的改动
1. 由于仅只用一个database，数据录入时，对应的 collection name 需要改成“合约名_tick”这样的形式。

**Comment by vnpy** [comment]
我对数据库的了解只停留在insert、find和update上，这条涉及的更改影响比较大，想更多听听社区的意见了。

**Comment by ipqhjjybj** [comment]
对于题主的看法， 个人表示不认同。    数据库设计尽量采用分离设计的目的，就是因为不同的数据库访问频率不一样， 通过减少字段的方法，增加部分数据的访问性能。  本来mongodb性能就不是非常的好， 但是胜在方便。    单一的加在一个数据库， 基本导致后面修改成本无限上升。   基本可以认为是大退步。

**Comment by lamter** [comment]
目前我遇到的不是性能的问题，而是MongoDB访问权限的管理问题。MongoDB是针对每个`database`来授权，两个数据库`database_1`和`database_2`，如果都设置了用户`vnpy`读写权限，那么其实是两个用户`database_1.vnpy`和`database_2.vnpy`各自访问自己的`database`，而不是一个用户`vnpy`访问两个`database`。

具体到代码上，就意味着，每多一个`database`，就需要建立多一个`database`实例来验证登录。即：
```python
db1 = client.database_1
db1.authenticate(username, password)
db2 = client.database_2
db2.authenticate(username, password)
```
如果不合并成单一数据库的话，就要直接对多个`database`实例进行授权、读写方面的管理。

**Comment by mhxueshan** [comment]
个人觉得不是很必要，我自己使用过程中还没有遇到这方面的瓶颈，考虑到楼上说的权限问题，我觉得如果
自己有需要的话再抽像一个数据库连接管理模块也行，可以让使用者自己实现，因为这个功能属于纯优化。

**Comment by ujfjhz** [comment]
只有一个db的话，如果我要存放全品种的所有历史的话，好多collection啊。

**Comment by lamter** [comment]
我现在的数据录入已经改成了单个`collection`保存所有合约的数据。即一个`collection`名为`bar_1min`，保存所有合约的1分钟K线。
我这么做是因为两个原因。
1. 为了使用索引。索引可以极大地加快查询。当多个`collection`的时候，每个`collection`都会有自己的索引文件，读取大量`collection`，比如500个时，很容易就达到了系统限制的文件句柄上限，导致异常。要解决，只能更改系统的文件句柄上限。而我一般会避免为了一个项目或者工具而进行系统级的改动。目前来看，单个`colleciton`在使用索引的情况下，查询速度远超没有使用索引的多个`collection`。
2. 另一方面是为了多品种策略做准备。预想中，多品种策略更多的是要查找同一时间的多个品种的行情。多个`collection`的话，你无法确定哪些合约是有你需要的指定时间段的数据，要加上很多判断。而在单一`collection`，就可以直接查出来某一个时间段的所有品种的数据了。

**Comment by ujfjhz** [comment]
@lamter 不必系统级的修改，在mongodb的启动脚本里加上ulimit -n <newlimit>即可。
单collection用索引，查询速度肯定不如多collection且用索引的情况。而且不能只考虑读，还有数据的并发插入带来的锁以及IO的问题呢。

**Comment by lamter** [comment]
@ujfjhz 之前正是插入`tick`数据时IO性能严重不足我才逐步转向到这里的。现在`vnpy.DataRecord`是db.col.inser_one()逐条单个插入，跨网保存数据时存储消化速度远跟不上CTP推送的速度，最后内存爆掉。提高存储最直接有效的方法就是批量保存，使用db.col.insert_many()。但是在多个`collection`的情况下，即使是`insert_many`也不得不按照`collection`来逐个执行。消化速度依然吃紧，最后在单个`collection`时，只需要每次都将缓存的数据`insert_many` 一次就行了。此时性能完全没有问题，跨网保存全合约`tick`数据都没问题。

**Comment by vnpy** [comment]
社区交流后发现这个不是大众的需求，暂不修改了。
