### ISSUE TITLE
drEngin bug报告

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#410]
运行runDataRecording会报错：

> RuntimeError: threads can only be started once

必须在drEngin.start重新创建thread 新线程

**Comment by vnpy** [comment]
问下你用的vn.py版本？另外请贴下错误截图

**Comment by jieyujing** [comment]
dev版本，运行example里面的runDataRecording app报错，我的解决方法是drEngine文件下把初始化self.thread = Thread(target=self.run)   # 线程放到 start函数下。

**Comment by vnpy** [comment]
我检查了下runDataRecording.py应该是没有显式调用过DrEngine的start方法，所以不明白为什么会触发这个异常。

方便的话请提供下错误截图吧。

**Comment by jieyujing** [comment]
![Uploading 2017-07-18_231038.png…]()

**Comment by jieyujing** [comment]
![2017-07-18_231038](https://user-images.githubusercontent.com/12085501/28325225-d43d8090-6c0f-11e7-98bb-2d2e1b344422.png)

**Comment by vnpy** [comment]
找到问题了，有段代码复制粘贴的时候弄错了版本，已经修复！
