### ISSUE TITLE
策略中tick合成分钟线及5分钟线的逻辑讨论

### ISSUE THREAD

**Issue by mhxueshan** [vnpy/vnpy#411]
多谢陈老师在vnpy中写的一些示例代码，我提出来的数据合成逻辑疑问并不在vnpy的核心，是在cta策略的示例代码里面，以KkStrategy为例。我在做数据分析时采用了里面的分钟线和多分钟线合成逻辑，分析过程中发现如下一些疑问，提出来供陈老师和其他有兴趣的朋友一起讨论：
1. tick合成分钟线。在ctp的tick流中，有一些tick只是快照数据，并没有真正成交，也就是成交量为0的tick。这些tick现在是全部用作了分钟线的合成计算，我比较过一些数据，mc,tb的，他们的数据逻辑从我的逆向分析来讲应该是过滤掉了成交量为0的tick了的。
2. tick合成分钟线。只判断了Minute，这样会导致一个问题，就是今天23:00:00和明天的09:00:00的tick数据会统一当做今天23:00的分钟线，其实这这分钟的tick里面只包含了一根23:00的tick，其余的全部是明天9点的。
3. 分钟线合成多分钟线。KkStrategy里面是合成的5分钟线。我做了一个测试，比如：09:00:00,09:01:00,09:02:00,09:03:00,09:04:00,09:05:00,09:06:00 这个序列，09:00:00不会参与计算，09:01:00-09:05:00会参与一个5分钟线的计算。我比较过文华的数据，他们是09:00:00-09:04:00参与的计算。

上面3个疑问我自己已经按我的思路改了算法，当然这些小的问题可以测试一下系统的鲁棒性，我也是提出来和大家一起讨论一下，如果陈老师这边觉得可以把这些问题进行变更，我也可以贡献我的代码。

**Comment by vnpy** [comment]
多谢，我来看看具体的解决方法

**Comment by 4ever911** [comment]
我觉得可能要看自己的历史数据是什么组织方式吧， 只要都是相同的归类方式和规则，就能保证回测的时候相对准确一点。

**Comment by mhxueshan** [comment]
@4ever911  数据回放方式确实可能根据历史数据不一样会不一样，但是其实有一种最简单的方式就是把每天实际的ctp tick流保存下来，然后回放，这样对回测起来是最接近真实环境的。
其他的比如合成分钟线，对tick进行处理放在策略里面相对会合理一些，因为实际在线上跑的时候就是这些数据，不用管他合不合理，只要和真实环境相同就行，比如可能出现没有成交量的tick数据等等。

**Comment by bigdig** [comment]
@mhxueshan CTP分时间段交易，分段处就会多出一个Tick。我的处理是统一进行前闭后开处理，将分段最后的一个Tick合并到前面的Bar里。这样就不存在你说的 就是今天23:00:00和明天的09:00:00的tick数据会统一当做今天23:00的分钟线现象了

**Comment by vnpy** [comment]
准备增加一个标准k线自动合成的类来解决大部分用户不会合成k线的问题

**Comment by mhxueshan** [comment]
@vnpy 谢谢群主

**Comment by vnpy** [comment]
已完成。
