### ISSUE TITLE
使用MongoDB的insert_many接口进行批量保存

### ISSUE THREAD

**Issue by lamter** [vnpy/vnpy#412]
目前的insert_one接口效率过低。在DataRecord模块保存tick数据时，如果跨网络保存可能会有严重的瓶颈。建议将mainEngine.insert 接口改为缓存待保存数据，格式如下：
```python
cache = {
    "database_name": {
        "collection_name":  queue.Queue(document1, document2, )
    }
}
```

同时运行一个子线程，反复逐个对`collection`进行批量保存，如：
```python
while True:
    for dbn, collections in cache.items():
        for coln, tickQueue in  collections.items():
            documents = []
            while not tickQueue.empty():
                tick = tickQueue.get_nowait()
                documents.append(tick)
            client.insert_many(dbn, coln, documents)
```

这样可以极大减少反复交互的损耗。

**Comment by vnpy** [comment]
不行，你这里涉及到多线程访问同一个数据结构（字典和列表），需要加锁了，而且这个锁的被两个线程同时竞争的概率还比较大，可能会拖慢整个系统的速度。

**Comment by lamter** [comment]
如果是线程竞争的问题，可以改用 Queue() 而不是 list 来缓存tick。当多线程同时访问这个`cache`时，一次遍历确实可能因为`cache`造成`database_name`和`collection_name`这两层的遗漏，但是还会有下次遍历。用`Queue`保证`ticks`的队列不会出现竞争即可。

**Comment by vnpy** [comment]
这个Queue的方案可能会带来一定的性能提升，不过考虑到目前由于GIL的限制，增加线程会拖累程序的整体运算性能，同时跨网络保存数据也不是大部分人的需求，这里暂时不进行修改。

不过这个方案确实对于有跨网络保存需求的人来说是个不错的参考。
