### ISSUE TITLE
CTP simnow 模拟盘问题

### ISSUE THREAD

**Issue by JaysonAlbert** [vnpy/vnpy#421]
在使用CTP simnow模拟盘的时候，我发现，有时前置机会出问题，导致tick数据会从错误的时间开始回放。比如当前是10：30，收到的tick却是9：00开始，甚至是从昨天的夜盘时间开始。tick数据推送的时间间隔也不再是500ms，而是相对快一些。感觉应该是前置机出了问题，所以数据又从当日的第一个tick开始回放了。

所以在这里我有两个问题，第一有没有什么办法可以解决这个问题。
第二，如果数据接口的账户使用实盘的账号，而交易接口使用模拟盘账户的话，应该能解决这个问题。在这种情况下，vnpy会不会考虑添加对数据账户和交易账户不同的支持。

**Comment by vnpy** [comment]
SimNow只是一套质量比较普通的仿真环境，如果需要质量比较好的可以联系期货公司申请他们自运维的仿真帐号，质量会好很多
