### ISSUE TITLE
请求加入天勤行情网关接口

### ISSUE THREAD

**Issue by tianqin18** [vnpy/vnpy#424]
我尝试做了一个到天勤行情软件的接口，可以提供期货/期权的实时行情和历史数据序列。目前项目地址在
https://github.com/tianqin18/vnpy-tianqin, 希望能并入官方库以减少安装维护复杂度。

**Comment by vnpy** [comment]
看了下网站，没有详细的信息，能否介绍下？

**Comment by tianqin18** [comment]
天勤行情是一款免费行情软件，由快期提供支持，目前提供国内4家期货交易所的期货、期权及组合行情。与其它行情软件相比，有一些特性：

* 在客户端提供 dde 及 websocket 数据接口

* 数据来自交易所接口，避免了CTP接口接收行情的若干BUG

* 所有合约K线严格按交易时段补全及对齐，有专职人员进行数据清洗和每日校对

* 不仅推送报价数据，还同步推送K线数据，省去了开发者自行维护K线数据的额外成本

* 软件内图表提供了完整历史细节（图表十字光标模式下，用Ctrl+鼠标滚轮可以任意展开K线细节）

* 提供了完全的历史仿真模拟，对于外挂程序开发者，可以只写一份处理实时行情的代码，自动获得历史测试的能力，对使用半自动或手工策略的用户也同样适用

vnpy-tianqin 是我按照vnpy框架标准写的python代码，为本地运行的天勤行情软件的websocket接口提供一个简单封装和内存数据管理，方便在vnpy中调用其提供的数据。

**Comment by vnpy** [comment]
方便的话加我的QQ聊吧：418225424，请说明下是“天勤行情“

**Comment by vnpy** [comment]
已添加
