### ISSUE TITLE
找不到vn.trader目录

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#434]

**Comment by FallacyWalker** [comment]
你们的文档里说先要进入vn.trader目录，但是根本找不到这个目录啊 。
![screen shot 2017-08-07 at 11 06 20](https://user-images.githubusercontent.com/20806018/29010868-0a16f5ba-7b61-11e7-89e9-f8d571ae9bbd.png)

**Comment by vnpy** [comment]
文档还没更新完，最近正在加紧中

**Comment by FallacyWalker** [comment]
是不是可以把一些比较重要的部分先写一个简要的文档，譬如编译、运行 。

**Comment by ming076** [comment]
新的目录应该是/npy/trader，不过我也找不到vtMain.py，感觉新版应该是改了。

**Comment by vnpy** [comment]
主入口在/examples/VnTrader/run.py里

**Comment by timinGo** [comment]
在/examples/VnTrader/run.py 里运行python run.py
'''Python
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from vnpy.event import EventEngine
ImportError: No module named vnpy.event
'''

**Comment by vnpy** [comment]
看Quickstart，要先运行install.bat安装
