### ISSUE TITLE
找不到vn.api目录

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#435]
文档里有，但是工程里找不到：
![screen shot 2017-08-07 at 11 49 41](https://user-images.githubusercontent.com/20806018/29011610-0d65031e-7b67-11e7-8cbc-492e14e75c92.png)

**Comment by vnpy** [comment]
文档还没更新完，最近正在加紧中

**Comment by vnpy** [comment]
请先参考Wiki里的安装说明
