### ISSUE TITLE
活动定单应当排除状态为STATUS_REJECTED 的定单

### ISSUE THREAD

**Issue by bigdig** [vnpy/vnpy#438]
#----------------------------------------------------------------------
    def updateOrder(self, event):
        """更新委托数据"""
        order = event.dict_['data']        
        self.orderDict[order.vtOrderID] = order
        
        # 如果订单的状态是全部成交或者撤销，则需要从workingOrderDict中移除
        if order.status == STATUS_ALLTRADED or order.status == STATUS_CANCELLED:
            if order.vtOrderID in self.workingOrderDict:
                del self.workingOrderDict[order.vtOrderID]
        # 否则则更新字典中的数据        
        else:
            self.workingOrderDict[order.vtOrderID] = order

**Comment by vnpy** [comment]
OK，我会尽快修复

**Comment by vnpy** [comment]
已修复
