### ISSUE TITLE
能否升级下OKCOIN与HUOBI的接口

### ISSUE THREAD

**Issue by vista852** [vnpy/vnpy#439]
OKCOIN新增了rest的API2.0接口，支持ETC交易
HUOBI新增了支持ETH/CNY, ETC/CNY, ETH/BTC, LTC/BTC, ETC/BTC, BCC/BTC 的REST API接口，请求将VNPY的这两个接口升一下级

**Comment by vnpy** [comment]
暂时没时间做，欢迎发起PR
