### ISSUE TITLE
实盘中怎么使用历史数据？实时数据跟历史数据怎么对接？

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#44]
20160410 晚上我把PP1605的 tick,分，日，三个历史数据存入数据库

今天 20160411下午打开vnpy实盘。（如果下午开机不行，就改为上午。跟昨天历史数据接上）
我的策略运行周期是分BAR，但是需要计算60日均线，10小时线。
该怎么操作？

随着时间的推移，内存中的BARLIST离数据库中历史数据的时间越来越远。是不是说，要把接受到的数据同步存入数据库？保持数据库跟当前时间一致？（拖慢速度？）

关于实盘中使用历史数据的例子，万分感谢。

**Comment by vnpy** [comment]
你的策略涉及的时间框架比较多，整体看应该对延时要求没那么高，需要几个步骤来解决：
1. 多个时间框架的数据库表，你已经做好了
2. 每日盘前启动系统初始化时，载入三个时间框架的历史数据，分别计算对应的参数
3. 开盘后，收到TICK时，自行累加汇总成小时K线和日线，并在K线结束时间后（比如一小时结束），先判断是否要进行交易和发单，操作完成后再将K线存入数据库（这个操作可能耗时在若干毫秒，而且你在交易判断后再执行，影响可以忽略）
4. 内存里的K线数据，你可以选择一天不断往一个list里append，或者固定一个长度，超过的部分pop掉，这两者对于python而言一天的数据都几乎没有任何影响

**Comment by vnpy** [comment]
增加了vn.trader里的行情数据收集模块用于解决行情落地的问题。
