### ISSUE TITLE
请求在vnpy中新增锁仓的下单功能

### ISSUE THREAD

**Issue by yeyl** [vnpy/vnpy#442]
部分期货品种平今仓手续费远高于平昨手续费，可否考虑在vnpy中增加锁仓下单的功能，与原下单功能并存；若用户针对此策略或品种认为平今时需要锁仓，则使用锁仓的下单功能：
        锁仓的功能具体如下，需要平仓时检查该期货账户在某一品种的昨仓及今仓情况，并判断是选择平昨仓还是开仓：
其中中金所（优先平今），若持仓有今仓，平仓时则直接开仓锁仓；
上期所有昨仓直接选择平昨，当昨仓数量不够时拆分订单，部分平昨，剩余数量开仓，无昨仓则直接开仓；
大商郑商所（优先平昨）直接选择平仓，昨仓数量不够时拆分订单，部分平昨，剩余数量开仓，无昨仓则直接开仓

**Comment by bigdig** [comment]
用开仓锁仓来代替平仓，虽然能省去平今的手续费，但代价是保证金的占用。

**Comment by yeyl** [comment]
的确对于频率较高的策略会占用较多保证金；
但这是新增一种下单的方式，与原有的sendorder并存，供用户选择，
实际上在MC里也有类似的锁单功能，实现起来并不困难，只需在本地维护好对应期货品种的持仓数量、昨仓数量、今仓数量、昨仓可用、今仓可用的数量就好

**Comment by vnpy** [comment]
已完成
