### ISSUE TITLE
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#444]
File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.6.2b0-py2.7.egg\vnpy\trader\app\spreadTrading\uiStWidget.py", line 389, in initUi
    self.horizontalHeader().setResizeMode(QtWidgets.QHeaderView.Stretch)
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode',点击价差交易就出现这个错误

**Comment by zsluedem** [comment]
pyqt版本问题吧，用的是pyqt几

**Comment by xldistance** [comment]
用的是PYQT5，我把这行代码注释了可以用......

**Comment by vnpy** [comment]
恩。。。这是个pyqt版本更新导致api不兼容的问题

**Comment by mh3fly** [comment]
可以使用setSectionResizeMode替换setResizeMode
