### ISSUE TITLE
请求在ctaEngine文件的保存持仓功能中增加一个posCost字段

### ISSUE THREAD

**Issue by ztjeff** [vnpy/vnpy#445]
- [x] 在很多CTA隔夜策略中不仅需要记录当前的pos仓位大小，也需要记录pos的开仓成本，以便计算止盈和止损价位。所以恳请群主在ctaEngine.py文件中的savePosition()和loadPosition()函数中增加一个posCost字段，保存到MongoDB中，更改代码如下（已测试通过），对无需此字段的CTA程序也无影响。

![image](https://user-images.githubusercontent.com/27806909/29249583-09187f68-8065-11e7-81f3-05b2193271b7.png)
![image](https://user-images.githubusercontent.com/27806909/29249596-48c16ac6-8065-11e7-95e0-c4469c3f2565.png)
另外，在ctaTemplate.py文件中要增加一个posCost变量：
![image](https://user-images.githubusercontent.com/27806909/29249604-946be7a8-8065-11e7-94e3-4858105dd8bb.png)

如能采纳，万分感谢！

**Comment by wisfern** [comment]
其实可以发pr的

**Comment by bigdig** [comment]
我想您一定是想要存储策略的运行变量。您可以试一下如下代码

`    #----------------------------------------------------------------------
    def loadPosition(self):
        """从数据库载入策略的持仓情况"""
        for strategy in self.strategyDict.values():
            flt = {'name': strategy.name,
                   'vtSymbol': strategy.vtSymbol}
            posData = self.mainEngine.dbQuery(POSITION_DB_NAME, strategy.className, flt)
            
            for d in posData:
                strategy.pos = d['pos']

                for key,value in d.iteritems():
                    setattr(strategy,key,value)`

**Comment by bigdig** [comment]
`    #----------------------------------------------------------------------
    def savePosition(self):
        """保存所有策略的持仓情况到数据库"""
        for strategy in self.strategyDict.values():
            flt = {'name': strategy.name,
                   'vtSymbol': strategy.vtSymbol}
            
            d = {'name': strategy.name,
                 'vtSymbol': strategy.vtSymbol,
                 'pos': strategy.pos}

            if hasattr(strategy,'varList'):
                for key in strategy.varList:
                    if key not in ['inited','trading','pos','fixedSize']:
                        d.setdefault(key, getattr(strategy,key))
            
            self.mainEngine.dbUpdate(POSITION_DB_NAME, strategy.className,
                                     d, flt, True)
            
            content = '策略%s持仓保存成功' %strategy.name
            self.writeCtaLog(content)`

**Comment by vnpy** [comment]
考虑了一下这个目前不是大部分人的通用需求，建议采用@bigdig提出的方法自行修改
