### ISSUE TITLE
编译api提示command not found

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#446]
ubuntu 16.04 LTS;
python 2.7.12;
vnpy/api/ctp下运行./build.sh, 提示command not found;

**Comment by vnpy** [comment]
运行bash build.sh试试

**Comment by FallacyWalker** [comment]
管用；
但是末尾会提示：target is not a directory;
![screen shot 2017-08-17 at 09 51 06](https://user-images.githubusercontent.com/20806018/29392782-985b2714-8332-11e7-8489-c6e93e5e087a.png)

**Comment by vnpy** [comment]
那是个比较老的bug了，请试试最新的dev分支，这个是即将发布的1.7.0beta

**Comment by FallacyWalker** [comment]
Ubuntu 16.04 LTS 64bit;
clone dev branch总是失败：
![screen shot 2017-08-18 at 19 17 39](https://user-images.githubusercontent.com/20806018/29457972-80bbc29e-844f-11e7-8e15-8dd83cb74009.png)

**Comment by vnpy** [comment]
网络问题，翻墙吧。
