### ISSUE TITLE
examples下的VnTrader怎么运行呢 ？

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#448]
ubuntu 16.04 LTS;
python 2.7.12;
vnpy/examples/VnTrader运行python run.py,提示No module named vnpy.event;

**Comment by QiXuanWang** [comment]
先安装再运行，试试1.6或者1.5版本，最新的结构上感觉有些问题

**Comment by marvelousp** [comment]
win 10;
python 2.7.13
vnpy/examples/VnTrader运行python run.py，提示：ImportError: DLL load failed:找不到指定的模块

**Comment by vnpy** [comment]
@marvelousp 请安装vcredist 2013 x86

**Comment by vnpy** [comment]
@FallacyWalker 请先运行bash install.sh安装vn.py

**Comment by FallacyWalker** [comment]
install.sh在哪个目录里？我没有找到；

**Comment by vnpy** [comment]
最新的dev分支下有。

**Comment by FallacyWalker** [comment]
dev已更新到最新版；
ubuntu 16.04 LTS;
python 2.7.12;
vnpy/examples/VnTrader运行python run.py,提示ImportError:No module named qtpy.QtCore;
![screen shot 2017-08-23 at 12 20 57](https://user-images.githubusercontent.com/20806018/29598808-ef8199a4-87fd-11e7-8a71-f3c71fc72587.png)

**Comment by vnpy** [comment]
请安装Anaconda 4.0.0，不要用系统自带的Python

**Comment by FallacyWalker** [comment]
dev branch已更新到最新版；
ubuntu 16.04 LTS;
已安装 Anaconda2-4.0.0-Linux-x86_64.sh
vnpy/examples/VnTrader运行python run.py,提示ImportError:No module named vnpy.event;
![screen shot 2017-08-25 at 16 51 25](https://user-images.githubusercontent.com/20806018/29706833-caa4ff90-89b5-11e7-851f-8ea77344ed8c.png)

![screen shot 2017-08-25 at 16 46 38](https://user-images.githubusercontent.com/20806018/29706854-d84edca6-89b5-11e7-9a43-92ec4f3e6bcb.png)

**Comment by vnpy** [comment]
运行bash install.sh安装vn.py后再运行examples下的例子

**Comment by FallacyWalker** [comment]
已在vnpy目录下运行 bash install.sh ,但是不管用，还有这个问题；
![screen shot 2017-08-29 at 10 59 09](https://user-images.githubusercontent.com/20806018/29802896-fc2ccb2c-8caa-11e7-9156-bdc0b9c3f366.png)

**Comment by vnpy** [comment]
安装完后你的报错还是找不到vnpy.event吗？

安装时是否使用了sudo？如果有的话，检查你的sudo python是否指向的是Ubuntu自带的Python而非Anaconda

**Comment by llia7133** [comment]
你好，尝试run:
python run.py,
![image](https://user-images.githubusercontent.com/39557607/40423703-ae08d2c0-5ed6-11e8-8abb-54dc89a97ecf.png)
不知如何解决？

谢谢
