### ISSUE TITLE
CTP登陆遇到错误 代码3，错误信息:不合法的登陆

### ISSUE THREAD

**Issue by likenji** [vnpy/vnpy#450]
OS：Win8.1，
Anaconda：envs里装的2.7 32bit
vnpy:1.6.2

https://github.com/vnpy/vnpy/issues/397
症状和这篇一样，但这篇回答里面貌似没有提及解决方案，我是最新版本，应该不存在json配置文件的问题。

{
    "brokerID": "9999", 
    "mdAddress": "tcp://180.168.212.228:41213", 
    "tdAddress": "tcp://180.168.146.187:10000", 
    "userID": "",
    "password": ""    
}
json文件如下（用notepad++编辑的，utf-8无BOM），把userID和password抹去了，用这账号密码是可以登录http://www.simnow.com.cn/
所以问题应该在其他地方。
mdAddress和tdAddress是直接抄http://www.vnpy.org/trader-tutorial-1.html的。
以及http://www.simnow.com.cn/product.action上面的也尝试了
链接都失败了，烦请@vnpy解答一下

**Comment by vnpy** [comment]
userID不是你的simnow登录号，而是登录进去后看到的资金账号

**Comment by likenji** [comment]
谢谢您的解答，问题已经解决了！
具体方法是：把 SimNow登录账号 换成SimNow个人界面上的 InvestorID 。

顺便问一下，http://www.vnpy.org/trader-tutorial-3.html 这篇教程里，黑色的界面要怎么切换，已经pip下载了qdarkstyle了

**Comment by vnpy** [comment]
按理说你装好qdarkstyle就直接会变成黑色的了，你在python里import qdarkstyle看看有没有报错？
