### ISSUE TITLE
win7-64bit运行run.py没有显示界面，也没有报错

### ISSUE THREAD

**Issue by ming076** [vnpy/vnpy#452]
win7-64bit运行run.py没有显示界面，也没有报错
不知道是因为我没安装好，还是什么原因，很奇怪。期待vnpy1.6.2的新版说明，感觉新版改动还是很大的。

**Comment by vnpy** [comment]
在cmd里运行python run.py看看报错输出

**Comment by ming076** [comment]
报错如下，一开始说是没有装pyqt，我用pip装了之后还是报错。
C:\vnpy>python run.py
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from vnpy.event import EventEngine
  File "C:\vnpy\vnpy\event\__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event
  File "C:\vnpy\vnpy\event\eventEngine.py", line 10, in <module>
    from qtpy.QtCore import QTimer
  File "C:\Python27\lib\site-packages\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by vnpy** [comment]
请看文档，使用Anaconda 4.0.0，不要用普通的Python

**Comment by ming076** [comment]
前面说错了，我使用Anaconda安装的pyqt，4、5都装了，用conda命令，但是运行run.py还是报上面的错，我的conda版本是4.3.24，有没有问题？还是必须用4.0.0？

C:\vnpy\examples\VnTrader>conda install pyqt=4
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2:

The following packages will be DOWNGRADED:

    jpeg:    9b-vc9_0     [vc9] --> 8d-vc9_2      [vc9]
    libtiff: 4.0.6-vc9_3  [vc9] --> 4.0.6-vc9_2   [vc9]
    pillow:  4.1.1-py27_0 --> 3.4.2-py27_0
    pyqt:    5.6.0-py27_2 --> 4.11.4-py27_7
    qt:      5.6.2-vc9_4  [vc9] --> 4.8.7-vc9_9   [vc9]

Proceed ([y]/n)? y

jpeg-8d-vc9_2. 100% |###############################| Time: 0:00:01 109.54 kB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:01 205.92 kB/s
qt-4.8.7-vc9_9 100% |###############################| Time: 0:04:58 143.77 kB/s
pillow-3.4.2-p 100% |###############################| Time: 0:00:03 259.86 kB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:09 252.08 kB/s

**Comment by ming076** [comment]
我重新删了，使用Anaconda 4.0.0来安装，就在ta-lib那里报错，报CondaHTTPError，这个按QiuckStart的说法应该是网络问题。
但是很奇怪，我用浏览器打开是能打开页面的，也试过用VPN，也试过换用国内清华的tuna镜像，但是都还是一直报这个错误。
C:\vnpy\examples\VnTrader>conda install -c quantopian ta-lib=0.4.9
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Anaconda2:

The following packages will be SUPERSEDED by a higher-priority channel:

    ta-lib: 0.4.9-np110py27_0 pkgs --> 0.4.9-np110py27_0 quantopian

Proceed ([y]/n)? y


CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.an
aconda.org/quantopian/win-32/ta-lib-0.4.9-np110py27_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.


CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.an
aconda.org/quantopian/win-32/ta-lib-0.4.9-np110py27_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.


CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.an
aconda.org/quantopian/win-32/ta-lib-0.4.9-np110py27_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by ming076** [comment]
运行SET CONDA_SSL_VERIFY=false可以成功安装了，原来是这个防火墙的问题。。。

**Comment by ming076** [comment]
但是我往下运行python setup.py install，还是报错。这个又是什么回事呢？

C:\vnpy\examples\VnTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from vnpy.trader.gateway import (ctpGateway, femasGateway, xspeedGateway,
  File "C:\Anaconda2\lib\site-packages\vnpy-1.6.2b0-py2.7.egg\vnpy\trader\gatewa
y\sgitGateway\__init__.py", line 4, in <module>
    from sgitGateway import SgitGateway
  File "C:\Anaconda2\lib\site-packages\vnpy-1.6.2b0-py2.7.egg\vnpy\trader\gatewa
y\sgitGateway\sgitGateway.py", line 16, in <module>
    from vnpy.api.sgit import MdApi, TdApi, defineDict
  File "C:\Anaconda2\lib\site-packages\vnpy-1.6.2b0-py2.7.egg\vnpy\api\sgit\__in
it__.py", line 3, in <module>
    from vnsgitmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。

**Comment by ming076** [comment]
可以了，我在vnpy的根目录下新建一个run.py运行就可以了。
但是我在examples/VnTrader/下面的run.py运行则报找不到模块。

**Comment by vnpy** [comment]
你是Win10系统吧，SGIT和SHZD两个API用不了，把它们从run.py里给删掉就行了

**Comment by ming076** [comment]
我的是win7-64bit的旗舰版
OS 名称:          Microsoft Windows 7 旗舰版
OS 版本:          6.1.7601 Service Pack 1 Build 7601
OS 制造商:        Microsoft Corporation

【vnpy安装过程】
0、我安装的vnpy版本是1.6.2
1、安装必须的软件
1.1 安装Anaconda，注意必须是Python 2.7 32位版本，推荐的Anaconda版本为4.0.0，README.md和wiki都给出了链接。
1.2 安装MongoDB，Windows Server 2008 R2 64-bit and later, with SSL support x64
1.3 安装Visual C++ Redistributable Packages for VS2013 x86版本，README.md和wiki都给出链接，
#注意：
安装了Anaconda就可以不用单独安装Python了，Anaconda 是一个可用于科学计算的 Python 发行版。

2、配置MongoDB
2.1 创建保存数据用的数据库目录
(1)在C:\创建data目录
(2)在C:\data\目录下创建db和log目录
2.2创建数据库配置文件mongod.cfg
然后在C:\Program Files\MongoDB\Server\3.4\目录下创建数据库配置文件mongod.cfg，并输入以下内容后保存：

systemLog:
    destination: file
    path: c:\data\log\mongod.log
storage:
    dbPath: c:\data\db

2.3将MongoDB启动注册为Windows服务
打开cmd（命令提示符），请在cmd图标上点击鼠标右键，选择以管理员身份运行（尤其是Windows 10！）。
"C:\Program Files\MongoDB\Server\3.4\bin\mongod.exe" --config "C:\Program Files\MongoDB\Server\3.4\mongod.cfg" --install
然后启动服务：
net start MongoDB
如果看到“MongoDB服务已经启动成功”，则说明已经成功安装。

3、安装vn.py
下载代码、解压后运行install.bat自动安装（建议在cmd下执行运行，因为这样可以看到报错信息）
或者也可以编辑模式打开install.bat文件，一条一条执行三条命令（用记事本打开显示在一行，我用Sublime Text就能看到三行了）

【我遇到的问题】
1、安装talib过程中报错，先排查了防火墙和杀毒软件的影响。
后来怀疑被墙了，但是网页能够打开。网上搜到SET CONDA_SSL_VERIFY=false关掉这个防火墙后就能够安装了。

**Comment by vnpy** [comment]
如果你不用直达和飞鼠接口的话，在run.py里把这两个接口去掉就行了。

之前反应的情况都是在win10下，win7下我自己使用是没有出现过，原理还不清楚。
