### ISSUE TITLE
Crash when connect TdApi/mdApi

### ISSUE THREAD

**Issue by darwinsys** [vnpy/vnpy#457]
用vnpy连接启动ctp connect（），连接TdApi/MdApi, 系统总是崩溃：

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Starting server ....
Aborted (core dumped)

**Comment by vnpy** [comment]
请问你修改过CTP_connect.json里的帐号密码了吗？

**Comment by darwinsys** [comment]
问题解决了。 是我自己子类继承了CtpMdApi， 实现上有问题， 所以系统运行就崩溃了。

**Comment by vnpy** [comment]
OK
