### ISSUE TITLE
spreadTrading套利可以套用cta的回测框架吗

### ISSUE THREAD

**Issue by dandebin** [vnpy/vnpy#458]
目前在套利模块vnpy/vnpy/trader/app/spreadTrading/没有看到回测框架，可以套用cta的回测框架吗？由于套利模块至少有两个品种会出问题吗？

**Comment by vnpy** [comment]
不能直接套用，价差套利策略很多是半自动的，所以暂时只提供了算法，价差策略引擎可能后面看社区的需求决定是否要实现。

**Comment by HY-Scatterer** [comment]
其实还是非常迫切地需要一个套利回测的框架
