### ISSUE TITLE
为啥下单等操作不做成异步的？

### ISSUE THREAD

**Issue by 0428402001** [vnpy/vnpy#461]
这样在高频交易下 还是有些处理延迟啊！

**Comment by vnpy** [comment]
因为在Python中直接调用底层接口发单的延时，小于将委托放到队列里再由另一个线程发送出去的延时。

**Comment by 0428402001** [comment]
直接在api里面td模块做成异步呢？

**Comment by vnpy** [comment]
你可以试试看，如果比起目前的方案延时更低我来合并进去

**Comment by 4ever911** [comment]
其实还是要考虑做成异步的，因为可能同时对多个产品监控，可能同一时间会有很多下单请求，比如开盘时。放在一个队列里面还方便可以对流控做更细致的控制。

**Comment by w1dexa2p34** [comment]
这个问题是不是可以理解成除了交易所，或者大型券商 并没有这么多的业务压力？直接在python调用即可
