### ISSUE TITLE
关于1.6.2版本启动问题

### ISSUE THREAD

**Issue by ygnn008** [vnpy/vnpy#462]
我确定是按照github上的步骤安装的，用的方法1：解压后运行install.bat自动安装，但是安装完之后并没有在Anaconda2\Lib\site-packages\文件夹中找到vnpy-1.6.2b0-py2.7.egg文件夹，倒是在下载的文件中找到了CTP_connect.json文件并进行了修改，下一步保存run.py文件并运行，无论是双击还是cmd运行，都是闪一下就没反应了，该怎么解决，希望遇到同样问题的小伙伴回答一下，感激不尽

**Comment by vnpy** [comment]
运行install.bat是在cmd里输入install.bat安装，如果出错会有对应的内容输出。
