### ISSUE TITLE
ctp夜盘前需要重新登录的问题

### ISSUE THREAD

**Issue by HY-Scatterer** [vnpy/vnpy#463]
有时候vnpy部署在台式机上，而ctp夜盘开盘前需要重新连接登录。而有时候人不在电脑边上，无法点击登录。针对这个问题我想到可以用itchat这个包，用微信发信息的方式来远程登录。同时也可以用itchat做当前持仓、策略运行情况发送等交互。

**Comment by KobeZhao** [comment]
直接设个任务计划不就好了么。。

**Comment by vnpy** [comment]
也可以参考examples/CtaTrading使用守护进程的方式来实现
