### ISSUE TITLE
ctp登录CTP_connect.json用户名密码是写在哪个目录下面

### ISSUE THREAD

**Issue by gaorufeng** [vnpy/vnpy#464]
最新版的 vpny  CTP_connect.json 有4个目录同时有

C:\vnpy-1.6.2\build\lib\vnpy\trader\gateway\ctpGateway
C:\vnpy-1.6.2\tutorial\tick2trade\vn.trader_t2t\ctpGateway
C:\vnpy-1.6.2\docker\dockerTrader\gateway\ctpGateway
C:\vnpy-1.6.2\vnpy\trader\gateway\ctpGateway

我是在 C:\vnpy-1.6.2\examples\VnTrader>VnTrader.bat 运行vnpy的

ps: 其实我都改了,但是还是CTP登陆遇到错误 代码3, 登录名用的investorId, 密码在其他模拟软件上能登录买卖

**Comment by likenji** [comment]
我也遇到了这个问题，但我昨天还是能登陆的。所以我猜测是数据源方面的问题。

**Comment by ming076** [comment]
Quick Start有讲，应该是这个目录，你可以试一下。
==================================
Quick Start
找到你的Anaconda安装目录，打开Anaconda2\Lib\site-packages\vnpy-1.6.2b0-py2.7.egg\vnpy\trader\gateway\ctpGateway\CTP_connect.json，修改账号、密码、服务器等为上一步注册完成后你的信息（注意使用专门的编程编辑器，如Sublime Text等，防止json编码出错）

**Comment by vnpy** [comment]
目前登录信息的配置，直接在examples/VnTrader目录下就有
