### ISSUE TITLE
关于dev版本ctaHistoryData.py文件中的class HistoryDataEngine(object)

### ISSUE THREAD

**Issue by ygnn008** [vnpy/vnpy#466]
class HistoryDataEngine(object):
    """CTA模块用的历史数据引擎"""

    #----------------------------------------------------------------------
    def __init__(self, token):
        """Constructor"""
        self.dbClient = pymongo.MongoClient(globalSetting['mongoHost'], globalSetting['mongoPort'])
        self.datayesClient = DatayesApi(token)
请问token是什么参数类型

**Comment by vnpy** [comment]
token应该是字符串，需要在通联数据购买后才能有
