### ISSUE TITLE
方法def downloadEquityDailyBarts(self, symbol)是否属于class HistoryDataEngine(object)

### ISSUE THREAD

**Issue by ygnn008** [vnpy/vnpy#467]
看源码def downloadEquityDailyBarts(self, symbol)是不属于class HistoryDataEngine(object)的，但为什么要加上self参数，而wiki里面的教程“行情解决方案”最后的例子：创建API下载引擎实例

    e = HistoryDataEngine()
根据所要下载品种选择相应函数，如下载'000001'日行情

    e.downloadEquityDailyBarts(‘000001’)
这分明是当作类的方法来调用的，我现在就是卡在取历史数据存入mongodb这步了，不知道如何调用downloadEquityDailyBarts(self, symbol)这个方法，教程和版本不一致，学习起来费大劲了，经常因为一点小问题止步

**Comment by vnpy** [comment]
通联数据接口的内容已经比较老了，最近准备删掉

**Comment by ygnn008** [comment]
原来如此，那请问一下vnpy项目的用户主要通过什么方式取得历史数据呢，multicharts或是通达信软件导出么？数据问题我实在搞不清楚，谢谢了
