### ISSUE TITLE
新人求教

### ISSUE THREAD

**Issue by ygnn008** [vnpy/vnpy#468]
本人菜鸟最近刚刚开始研究vnpy项目，想请问已经在使用的各位前辈，你们用来回测的历史数据是通过什么方式取得并存入mongodb的，通联数据？（具体买的是哪类数据，因为要用到token凭证）还是multicharts导出数据csv（multicharts免费使用2个月），或是通达信导出数据，希望能予以解答，数据问题实在困扰，不胜感激

**Comment by vnpy** [comment]
1. 项目里自带了一个IF主力连续合约的分钟线数据，来源是MC，在examples/CtaBacktesting目录下
2. 可以使用行情记录模块每天记录、使用上海中期数据服务自动下载
3. 也在和更多的数据提供方对接，争取在年底前建立更多成熟的方案

**Comment by linshilogin** [comment]
@vnpy  您好。请问下，你说的那个自带的IF数据是指的文件 IF0000_1min.csv 么。但是这个文件似乎在运行CtaBacktesting的策略的时候，没有被读取啊

**Comment by vnpy** [comment]
运行loadCsv.py将数据插入到数据库里，后续回测都通过数据库加载
