### ISSUE TITLE
空单BUG

### ISSUE THREAD

**Issue by ayuanweiliang** [vnpy/vnpy#471]
刚开始操作VNPY时候经常会输入商品合约号直接点击发单操作，此时委托列表里面显示拒单。每日未成交委托数据限制20笔，如果操作失误，则拒单占用每个最大委托数量。

希望代码能够本地处理成交数量为0的情况或者成交量为0，拒单的委托不要放在委托列表中，占用每次最大委托单的数量。

**Comment by vnpy** [comment]
已完成
