### ISSUE TITLE
IF0000_1min.csv导入数据库出错中断

### ISSUE THREAD

**Issue by ygnn008** [vnpy/vnpy#472]
函数 loadMcCsv('IF0000_1min.csv', MINUTE_DB_NAME, 'IF0000')  每次都出错中断，而且每次断的位置不一样，有时导入了快一半的时候断掉，有时刚开始就断掉，是什么原因，期间没有任何操作
  File "C:\ProgramData\Anaconda2\lib\site-packages\ipykernel\iostream.py", line 317, in write
    self._buffer.write(string)

ValueError: I/O operation on closed file

**Comment by vnpy** [comment]
看起来你是在ipython里运行的，请直接在Python里运行

**Comment by linshilogin** [comment]
@vnpy ,我也遇到这个问题了。我是在spyder中运行的。这个是什么原因哇

**Comment by linshilogin** [comment]
@每次出现问题的记录点都不一样，我设置断点都不好设置

**Comment by vnpy** [comment]
请在Python里运行，不要用spyder或者ipython
