### ISSUE TITLE
v1.6.2 Ubuntu环境下安装问题

### ISSUE THREAD

**Issue by rivershadowy** [vnpy/vnpy#474]
新人求助，谢谢大家回答。

版本：v1.6.2
环境：Ubuntu 16.04 LTS 64-bit
Python: 装有python 2.7的Anaconda virtual environment

因为系统中已经有包含多个不同版本python虚拟环境的Anaconda，所以和安装教程唯一不同之处在于没有下载Anaconda而是建立了一个新的包含有python2.7虚拟环境。其余按照8月24日发布的《Ubuntu环境安装》wiki教程安装后，进入vnpy/examples/VnTrader，运行python run.py时报错：

from vnctpmd import MdApi
ImportError:  No module named vnctpmd

搜索了下，有类似回答：http://123.206.199.148/archiver/?tid-1637.html 是说要“自行编译vn.ctp后把两个.so文件复制到vnpy/api/ctp目录下”。

请问，
1) vn.ctp是指vnpy/api/ctp吗？这一版本内似乎没有命名为vn.ctp的文件；
2) 运行vnpy/api/ctp目录下的build.sh时报错：
    cp: target '../../vn.trader/gateway/ctpGateway/' is not a directory
    提示说没有该目录，唯一类似的目录是vnpy/trader/gateway/ctpGateway/。是我的编译方式有误吗？

**Comment by vnpy** [comment]
请参考最新文档：https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#2-%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
