### ISSUE TITLE
CTP针对上期货的昨仓问题

### ISSUE THREAD

**Issue by KobeZhao** [vnpy/vnpy#475]
昨天我做交易的时候，开盘时有10手rb，然后开了10手多单，这样今仓也是10手，总的是20；然后我平掉了5手昨仓，这时候，今仓不变，还是10手，总仓应该是15了。但是来看代码：
针对上期所持仓的今昨分条返回（有昨仓、无今仓），读取昨仓数据`
if data['YdPosition'] and not data['TodayPosition']:
            pos.ydPosition = data['Position']`
这里没理解错的话，当我开了10手今仓后，ydpos就不会再更新了，除非今仓又都平了。那这样，vnpy的昨仓还是10手，总仓是15手，而今仓成了5手。那继续这样，最后的昨仓今仓肯定是混乱的，导致平今平昨也会发生错误，不知道我有没有描述清楚。

## 另外，CTP的文档(48条)这样写的：
48. 持仓查询记录中的昨持仓是今天开盘前的一个初始值，不会因为平昨或者平仓而减少。 当前时侯的昨持仓=总持仓-今持仓。YdPosition := Position - TodayPosition。
也就是说ydpos其实是可以通过今仓来更新的，不知道vn里的data['TodayPosition']是否记录的就是今仓并且可用，是的话其实不如就直接以tdpos为基准，用pos-tdpos更新ydpos。

**Comment by KobeZhao** [comment]
可不可以直接就是`pos.tdPosition = data['TodayPosition']`，然后引擎里是`self.longToday = pos.tdPosition
self.longYd = self.longPosition - self.longToday`
这样可行吗

**Comment by vnpy** [comment]
已完成
