### ISSUE TITLE
1.7版本run.py 出现错误提示RuntimeWarning

### ISSUE THREAD

**Issue by likenji** [vnpy/vnpy#481]
(py27x86) C:\Users\User\Desktop\Python\quant\vnpy>python run.py
C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\api\ib\__init__.py:3
: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_
ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class Ord
erCondition> > > already registered; second conversion method ignored.
---------
Failed to import strategy file strategyEngine:
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\app\c
taStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\importlib\__init__.py", line 37
, in import_module
    __import__(name)
ImportError: No module named strategyEngine
还有一堆import error，不全部截取了，能成功启动vnpy，暂时不清楚该报错会影响什么功能。

安装过程比较坎坷（不清楚是否跟安装过程有关）：
原来有1.6.2版本，安装在conda环境下（py27x86）。
1.手动把vnpy的文件夹删了。
2.然后解压之前下载好的安装包。
3.激活py27x86环境后，进入解压的文件夹下,python setup.py install。
4.解压后在py27x86的site-packages下，有vnpy-1.7.0-py2.7.egg文件夹，将其中的vnpy文件夹复制到site-packages下。

二更：
仔细看了看报错信息，上面的错误提示不知道为什么少了个\（估计手抖删了），下面是更正后的错误提示：
--------------------
Failed to import strategy file strategyEngine:
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\app\c
taStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\importlib\__init__.py", line 37
, in import_module
    __import__(name)
ImportError: No module named strategyEngine

**Comment by vnpy** [comment]
C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\app\c
taStrategy\strategy_init_.py"

这个strategy_init_.py不是目前官方版本里的，你自己加的？

**Comment by likenji** [comment]
找了找文件夹，没有strategyEngine这个文件，是不是这里出错了

**Comment by likenji** [comment]
问题半解决。
解决方法：卸载后，pip install source.rar
之所以叫半解决，因为RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_
ptr,class std::allocator<class ibapi::shared_ptr > > already registered; second conversion method ignored.
仍然存在

**Comment by viponedream** [comment]
strategy\_init_.py 安装好就有这个东西。在安装目录下面。
出现这个的原因是你使用了自己的策略文件，并且这个策略文件没有存在安装目录下。
我也是同个问题。解决方案就是 把策略文件复制到 安装目录下面去。不要放在 run 目录下。
