### ISSUE TITLE
Ubuntu std::auto_ptr is deprecated.

### ISSUE THREAD

**Issue by likenji** [vnpy/vnpy#483]
之前在安装的时候，直接跳过了 sudo apt-get install mongodb libboost-all-dev cmake git 就去运行bash install.sh了，结果现在
![image](https://user-images.githubusercontent.com/18343150/30011193-23d67314-9168-11e7-84ff-c39c1f6e6dea.png)

确实是自己sb了，只求一个解决方案...

**Comment by vnpy** [comment]
执行sudo apt-get install mongodb libboost-all-dev cmake git，然后再去bash install.sh就行

**Comment by likenji** [comment]
我感觉这个问题要严重很多。目前是卡在
![image](https://user-images.githubusercontent.com/18343150/30017100-638ca47a-918a-11e7-9ba0-0f3fa81a78e0.png)
一个半小时也没跳过去，所以判断是出问题了。
而且卡在这个阶段时候，我的WinSCP的通信会断掉，不知道是不是占用了某些资源。

目前所有尝试都没能成功安装，尝试包括：
1.pip 卸载vnpy重装
2.apt install mongodb libboost-all-dev cmake git 以及 卸载cmake /libboost-all-dev重装
3.rm -f vnpy-1.7，重新解压。
4.重新下载source.tar.gz，并解压，bash install.sh，同样是卡在上面这步。

**Comment by vnpy** [comment]
你的服务器内存是多少？编译API的话会需要4G左右的内存，如果不够你可能得设置交换分区，参考：http://www.cnblogs.com/kerrycode/p/5246383.html

**Comment by likenji** [comment]
内存2G，可能是这个问题，我先看看能不能设置swap解决。

**Comment by likenji** [comment]
2G内存+设置4G交换分区，已解决！
但虚拟机1G内存，设置5G交换分区，安不了

**Comment by vnpy** [comment]
看来2G是最小限制了
