### ISSUE TITLE
天勤接口错误

### ISSUE THREAD

**Issue by szsa** [vnpy/vnpy#485]
运行 python test.py

c:\git\vnpy17\vnpy\data\tq>python test.py
ERROR:tornado.application:Future exception was never retrieved: Traceback (most
recent call last):
  File "C:\Anaconda2\lib\site-packages\tornado\gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "c:\git\vnpy17\vnpy\data\tq\vntq.py", line 194, in start
    self.on_receive_msg(msg)
  File "c:\git\vnpy17\vnpy\data\tq\vntq.py", line 229, in on_receive_msg
    while len(tick_serial) > sub_info["view_width"]:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by vnpy** [comment]
请问你启动天勤客户端了吗？

**Comment by szsa** [comment]
启动了   客户端运行正常
telnet 本机7777端口    可以发现端口正常打开了

**Comment by tianqin18** [comment]
这个bug应该已经修正了, 请更新一下代码
https://github.com/vnpy/vnpy/pull/482

**Comment by szsa** [comment]
谢谢，更新代码后已经可以使用
