### ISSUE TITLE
run.py报错：import error, version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by likenji** [vnpy/vnpy#488]
Ubuntu 16.04
Anaconda 4.3.1
PS：可能的误操作，在vnpy环境下bash install.sh之前，在root环境跑了一遍bash install.sh，不知道是不是这个错误的原因。

![image](https://user-images.githubusercontent.com/18343150/30098452-9f24ebec-9314-11e7-821c-da5a4cd7bcb5.png)
报错信息如上所示，我按照错误提示，从/usr/lib/x86_64-linux-gnu文件夹，把 libstdc++.so.6.0.21复制到/root/anaconda3/envs/vnpy/lib下，并更改快捷方式 libstdc++.so.6的指向，结果变成了如下输出，请问这个输出是正常的吗？
 
![image](https://user-images.githubusercontent.com/18343150/30098955-a772a51c-9316-11e7-95ce-2af2d10b8856.png)

**Comment by vnpy** [comment]
你这是用xshell之类的连过去的，没启动图形界面吧？自然报错无法显示了

**Comment by likenji** [comment]
ok, 我看看命令行模式下的教程。

我有点想知道 正常安装anaconda的情况下libstdc++是6.0.19版本么？我发现没issue是关于这个的，但是这个版本在运行的时候会报错。

**Comment by vnpy** [comment]
这点不清楚了，正常情况运行Python你不应该看到任何和c++有关的报错，最多有那个IB编译兼容性的提醒
