### ISSUE TITLE
能够在mac环境下工作吗？

### ISSUE THREAD

**Issue by janckerchen** [vnpy/vnpy#49]
希望提供mac环境下的教程

**Comment by vnpy** [comment]
不能，目前国内的柜台API接口只提供Windows和Linux下的接口，封装后的vn.py接口也只能在对应的操作系统使用，一定要用MAC的话就得使用Windows的虚拟机了。

**Comment by valaxy** [comment]
使用量化平台的人不一定都需要交易的接口，所以macOS由于不支持柜台API，阉割处理即可
