### ISSUE TITLE
run当前目录下，找不到放文件里的策略模块

### ISSUE THREAD

**Issue by fanchuan8848** [vnpy/vnpy#490]
https://github.com/vnpy/vnpy/blob/22311a882c465312ebad20eaa1cb607fa7b8b7af/vnpy/trader/app/ctaStrategy/strategy/__init__.py#L48
moduleName = name.replace('.py', '')
这里未考虑把策略放在专门的文件夹里的情况，放文件夹里好管理，直接放目录下多了就乱

**Comment by vnpy** [comment]
这里可以根据你自己的需求来改吧，把整个ctaStrategy目录复制到你的VnTrader目录下，然后作为你修改过的模块在run.py里加载就行。
