### ISSUE TITLE
from vnpy.event import EventEngine ImportError: No module named vnpy.event

### ISSUE THREAD

**Issue by dick7** [vnpy/vnpy#491]
运行 python run.py的时候提示出错。

**Comment by jieyujing** [comment]
先执行install

2017年9月7日 上午11:55，"dick7" <notifications@github.com>写道：

**Comment by chigimiyu** [comment]
请问上面的同学解决了么? 我已经安装过了,还是不行.

**Comment by dick7** [comment]
我安装 成功，可是我不大懂金融术语...



549119612@qq.com
 
From: chigimiyu
Date: 2018-01-04 22:29
To: vnpy/vnpy
CC: dick7; Author
Subject: Re: [vnpy/vnpy] from vnpy.event import EventEngine ImportError: No module named vnpy.event (#491)
请问上面的同学解决了么? 我已经安装过了,还是不行.

**Comment by luckyxsky** [comment]
跑一下 python setup.py install.  我 成功了。

**Comment by qq184473091** [comment]
> 跑一下 python setup.py install. 我 成功了。

thank you. it works for me.
