### ISSUE TITLE
CTP:不合法的登陆，求解答

### ISSUE THREAD

**Issue by aslinwang** [vnpy/vnpy#496]
在运行VnTrader的时候，连接CTP，错误日志出现：CTP 不合法的登陆
但是，我在`\Anaconda2\Lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\gateway\ctpGateway\CTP_connect.json`中填写的userId和password是没问题的（可以登陆上simnow），交易地址和行情地址如下：
```
"mdAddress": "tcp://180.168.146.187:10000", 
"tdAddress": "tcp://180.168.146.187:10010", 
```
应该也没问题啊

![image](https://user-images.githubusercontent.com/2310005/30236389-082267ae-954b-11e7-8a99-4d97868a6403.png)

另外，论坛vnpie，我注册之后一直是“等待会员验证”阶段，连帖子都不让看，请问怎么通过验证呢

**Comment by aslinwang** [comment]
解决了，应该修改`vnpy-1.7\examples\VnTrader\CTP_connect.json`

剩下一个问题：**论坛vnpie，我注册之后一直是“等待会员验证”阶段，连帖子都不让看，请问怎么通过验证呢**

**Comment by vnpy** [comment]
请问下你论坛注册的时间？看看你的注册邮箱里，应该有个验证邮件，找不到的话看看垃圾邮件里是否有

**Comment by aslinwang** [comment]
并没有收到验证邮件呢，垃圾箱里也没有
