### ISSUE TITLE
委托状态一直是已撤销该怎么办？

### ISSUE THREAD

**Issue by potato-cat** [vnpy/vnpy#498]
![capture](https://user-images.githubusercontent.com/21253825/30245700-29787c5c-9615-11e7-889e-05d7bf5671bc.PNG)

**Comment by xldistance** [comment]
看下交易界面的错误栏

**Comment by vnpy** [comment]
错误栏里会有详细内容输出，大概率是资金不足或者价格超过涨跌停板。
