### ISSUE TITLE
运行mdtest.py 提示非法用户

### ISSUE THREAD

**Issue by philipchung007** [vnpy/vnpy#5]
按照教程3成功编译了md接口的pyd，也已在mdtest.py内输入账号、密码、BrokerID，但是运行mdtest.py 提示“非法用户”。

修改mdtest.py「真实输入为数字，此处用X指代」：

    loginReq['UserID'] = 'XXXXXXX'                 # 参数作为字典键值的方式传入
    loginReq['Password'] = 'XXXXXX'               # 键名和C++中的结构体成员名对应
    loginReq['BrokerID'] = 'XXXX'    

在cmd内运行得到如下结果：

T:\Downloads\finance_win\vnpy\vn.lts\vnltsmd\test>python mdtest.py
Connect to 211.144.195.163:34513
Stock API(ON Session Connected[-59244543]
Session -59244543 Connected

onFrontConnected
CSecurityFtdcUserApiImplBase::RequestDirectly SessionID=-59244543
MaxOrderRef:
UserID:
TradingDay:
SessionID:0
SystemName:
BrokerID:
FrontID:0
LoginTime:
ErrorMsg:非法用户
ErrorID:-3
Send Heartbeat 1429077127
Send Heartbeat 1429077142
Heartbeat Receive Warning, CurrentTime=1429077153 LastTime=1429077132

onHeartBeatWarning
21
Send Heartbeat 1429077157
Send Heartbeat 1429077172
Send Heartbeat 1429077187
Heartbeat Receive Warning, CurrentTime=1429077196 LastTime=1429077175

**Comment by vnpy** [comment]
非法用户提示通常是：
1. 用户名和密码错了
2. 弄错了服务器地址，我这里的211.144.195.163:34513是仿真服务器，实盘服务器不同
3. 华宝的brokerid应该是2011 字符串

**Comment by philipchung007** [comment]
谢谢已解决，是服务器地址的问题，改成另外的地址后连接成功
