### ISSUE TITLE
持仓风险

### ISSUE THREAD

**Issue by Allen1203** [vnpy/vnpy#50]
有时候策略持仓，如果策略出现问题或出现系统性风险时不能及时平仓，是否考虑下在界面加上一键平仓，持仓列表加上右键平仓选项控制单个品种的及时平仓

**Comment by vnpy** [comment]
一键平仓这个功能在实盘中非常危险，尤其是对于机构的大账户而言，一旦不小心点了很可能成为又一个乌龙指，所以vn.trader不会提供。

单一合约的快速平仓功能考虑设计为双击后自动填充交易组件的内容，用户检查确认后点击再发单出去，这个接下来做进去。

**Comment by vnpy** [comment]
已完成。
