### ISSUE TITLE
为了调试实盘方便， 是否可以增加日志导出的模块

### ISSUE THREAD

**Issue by sunbjtu01** [vnpy/vnpy#501]
为了调试实盘方便， 是否可以增加日志导出的模块，用于保存相应日志。

**Comment by jieyujing** [comment]
你没看代码麽?temp目录下的log什么

2017年9月11日 下午6:08，"sunbjtu01" <notifications@github.com>写道：

**Comment by vnpy** [comment]
主引擎的日志落地已有，接下来再增加模块日志的落地
