### ISSUE TITLE
加载价差交易器，报错问题

### ISSUE THREAD

**Issue by yuqiantafuqin** [vnpy/vnpy#507]
spreadingTrading\uiStWidget.py line389, in initUi
        self.horizontalHeader().setResizeMode(QtWidgets.QHeaderView.Stretch)
AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'
这个报错该怎样解决？

**Comment by vnpy** [comment]
找到报错行的代码，注释掉就行。

因为你用的Anaconda版本较新，带的是qt5了
