### ISSUE TITLE
回测载入数据的问题

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#51]
现在是一次性全部载入的。
建议10天或20天分段载入。
碰到TICK回测，一次性载入就没办法了。
象现在这样，一年的tick，根本没办法回测。

**Comment by vnpy** [comment]
OK，我想下这个功能怎么设计，原理上不是太复杂。

**Comment by viponedream** [comment]
万能的群主，肯定有办法的。
细化一下：因为库可能存3年的tick数据。
1，而我们的策略也许在某段时间很抢眼，某段时间很差。所以读入数据可以考虑给人分段，如2015-5-10到2016-1-1，而不是默认到最近的。
2，每次读入10天或几天的（人家以策略计算周期自己判断）。这样不管库中存的数据多长都可以随意回测了。

**Comment by vnpy** [comment]
已完成，修改了回测引擎的实现，API保持和之前的版本一样。
