### ISSUE TITLE
最新的dev版vtEngine/EmsPosition没有定义

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#514]
def getPositionDetail(self, vtSymbol):
        """查询持仓细节"""
        if vtSymbol in self.detailDict:
            detail = self.detailDict[vtSymbol]
        else:
            detail = EmsPosition(vtSymbol)
            self.detailDict[vtSymbol] = detail
            
        return detail

**Comment by vnpy** [comment]
已修复，多谢！
