### ISSUE TITLE
定单转换后，sendOrder返回值由id变成了[]，需要对应相关的一些代码

### ISSUE THREAD

**Issue by bigdig** [vnpy/vnpy#516]
比如：
self.orderList.append(vtOrderID)需要变成 self.orderList.extend(vtOrderID)

**Comment by bigdig** [comment]
或者考虑将将转换后的定单ID拼接一下，形成新的字符串

**Comment by bigdig** [comment]
if not reqList:
            return ''
        
        for convertedReq in reqList:
            vtOrderID = self.mainEngine.sendOrder(convertedReq, contract.gatewayName)    # 发单
            self.orderStrategyDict[vtOrderID] = strategy                                 # 保存vtOrderID和策略的映射关系
            orderIDList.append(vtOrderID)
            
        self.writeCtaLog(u'策略%s发送委托，%s，%s，%s@%s' 
                         %(strategy.name, vtSymbol, req.direction, volume, price))
        
        return '-'.join(orderIDList)
    
    #----------------------------------------------------------------------
    def cancelOrder(self, vtOrderID):
        orders = vtOrderID.split('-')
        for order in orders:
            self.cancelOrderImp(order)

**Comment by vnpy** [comment]
之前还没全部写好，目前已完成
