### ISSUE TITLE
下单撤单异步后，成功率提高很多

### ISSUE THREAD

**Issue by 0428402001** [vnpy/vnpy#517]
我是做高频的  所以在您的代码上把python这一层给抽掉了 ，并且把队列异步的队列换成无锁的ring buffer，而且把下单，撤单也做成异步的，现在抢单的成功率到80%，简直没有撤单的，之前只有50%左右。
主要我没有时间commit一个啊  我建议作者改一下
![image](https://user-images.githubusercontent.com/6780527/30681192-dd6f4cda-9ed6-11e7-8e11-7792edeed641.png)

**Comment by vnpy** [comment]
很有意思啊，能贴下代码吗？

**Comment by 0428402001** [comment]
以ctp下单为例啊  主要改vnctptd.cpp vnctptd.h，添加一个异步的下单函数
![image](https://user-images.githubusercontent.com/6780527/30727812-347e229e-9f86-11e7-9b80-75a7b84b0a6c.png)

再添加处理函数

![image](https://user-images.githubusercontent.com/6780527/30727875-9590cfe6-9f86-11e7-8757-d171238831b8.png)

**Comment by vnpy** [comment]
明白了，再问下你的委托号orderRef是在Python中管理的吗？还有无锁的ring buffer指的是什么？

**Comment by 0428402001** [comment]
我使用你的把Python的都去掉了 所以都在c++里面管理
无锁队列看这个http://m.blog.csdn.net/zdy0_2004/article/details/70304276
里面有个国外大牛在GitHub实现的，亲测非常不错

**Comment by vnpy** [comment]
明白了，等于所有委托发单管理的东西都在C++里面实现，我看看这个锁，多谢！

**Comment by vnpy** [comment]
看了下这个无锁队列的Github说明，其中有一条潜在的风险是无法保证队列顺序的一致性，这点对于某些需要遵守严格下单顺序的策略来说是个比较大的影响因素。

另外无锁队列的实现大多是基于底层某个线程的疯狂轮询实现的，对于用不着特别低延时交易的用户而言可能导致无谓的开销以及系统的稳定性下降。

综上，这个无锁队列的改进是个对于高频用户而言很不错的改进方案，但是并不适合绝大部分用户的普遍需求，所以就不合并到项目里了，有需求的用户请根据自己的情况定制底层接口吧，也就是vnpy.api.ctp这层里的封装细节实现。
