### ISSUE TITLE
建议把本地止损单随策略持仓一起保存到数据库

### ISSUE THREAD

**Issue by HY-Scatterer** [vnpy/vnpy#518]
收盘的时候系统会保存策略持仓到本地，并在下次重开系统的时候初始化载入。但是本地止损单在关闭系统的时候就会丢失，尤其是那些和上一次成交价格有关的止损单，在下一次重开系统的时候恢复。因此建议把本地止损单跟随策略持仓一并保存到本地。 并在初始化时恢复。

**Comment by vnpy** [comment]
本地止损单目前和限价单一样，应该是每天收盘后就会自动失效，第二天开盘后策略根据当前的持仓情况和技术指标状态重新发出，并没有保存到数据库的必要。
