### ISSUE TITLE
ImportError: libthostmduserapi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ClassesOver** [vnpy/vnpy#519]
Docker Ubuntu 16.04环境下，  抛出这个错误，我该怎么解决？谢谢。

**Comment by vnpy** [comment]
目前Docker尚未开发好，根据这条报错内容你需要自行编译下CTP的接口，在vnpy.api.ctp文件夹运行build.sh，然后把编译好的.so复制到ctpGateway目录下，再启动程序

**Comment by asdgh1000** [comment]
编译后的文件没有 libthostmduserapi.so

**Comment by erichou668** [comment]
请问重新编译解決問題了嗎？
