### ISSUE TITLE
对于市场成交数据流的问题

### ISSUE THREAD

**Issue by wisfern** [vnpy/vnpy#523]
部分期货高频参考了市场成交数据流，用于判断下单量。但vnpy框架的onTrade这个貌似是为了个人帐户的成交信息做准备的，而没有一个针对市场成交数据的接口。
是这样的吗？还是我理解出错了？

**Comment by vnpy** [comment]
期货交易所提供的行情数据，只有1秒推送2次的切片，通过行情接口MdApi推送，对应的是CTA策略模块里的onTick推送的数据。

L2行情的接口是需要自己找交易所购买的。

**Comment by wisfern** [comment]
那trade数据，还是通过onTrade这个接口把市场成交数据通知策略？

**Comment by vnpy** [comment]
你自己的成交数据，是通过onTrade通知你的

**Comment by wisfern** [comment]
好的，看来市场的成交数据需要自己再扩展接口来实现。
