### ISSUE TITLE
runDataRecording运行正常，数据记录几分钟就停止了

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#525]
还有MongoDB Database Server长期占用20%左右的CPU，CPU是E3 1231V3，之前的版本没有这个问题，不知道是不是新增仓位记录的问题......

**Comment by xldistance** [comment]
数据好像还是在记录的，但是插入数据库的时间比交易所时间越来越慢

**Comment by xldistance** [comment]
用回没有添加持仓日志的DEV版本数据记录正常

**Comment by freeitaly** [comment]
也遇到了这个问题， 分析是群主用dbUpdate替换dbInsert的原因，tick数据库中数据量比较大的情况下，update会耗费比较大的时间进行查询操作，我这边的环境update一个tick要1～2秒。

**Comment by vnpy** [comment]
有可能的，当数据库中数据量太大时确实插入tick还要查询耗时会比较大

**Comment by vnpy** [comment]
下个版本看看怎么弄吧

**Comment by vnpy** [comment]
已解决，将DataRecorder中默认的数据记录方式从update改为insert
