### ISSUE TITLE
vntrader.bat 报错 ImportError: DLL load failed

### ISSUE THREAD

**Issue by yupoet** [vnpy/vnpy#526]
1. 先是报错缺乏module

>(C:\ProgramData\Anaconda2) F:\vnpy-master\examples\VnTrader>vntrader.bat
>
>(C:\ProgramData\Anaconda2) F:\vnpy-master\examples\VnTrader>python run.py
>C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api\ib\__in
>it__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi
>::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<
>class OrderCondition> > > already registered; second conversion method ignored.
>from vnib import *
>Traceback (most recent call last):
> File "run.py", line 19, in <module>
>    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway,
>  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\tra
>der\gateway\okcoinGateway\__init__.py", line 4, in <module>
>    from okcoinGateway import OkcoinGateway
>  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\tra
>der\gateway\okcoinGateway\okcoinGateway.py", line 21, in <module>
>    from vnpy.api.okcoin import vnokcoin
>  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api
>\okcoin\__init__.py", line 3, in <module>
>    from vnokcoin import OkCoinApi
>  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api
>\okcoin\vnokcoin.py", line 9, in <module>
>    import websocket
>ImportError: No module named websocket

> (C:\ProgramData\Anaconda2) F:\vnpy-master\examples\VnTrader>pip install websocke
> t
> Collecting websocket

> 
>   Downloading websocket-0.2.1.tar.gz (195kB)
>     41% |█████████████▍                  | 81kB 91kB/s eta 0:00:02
>     47% |███████████████                 | 92kB 82kB/s eta 0:00:0
>     52% |████████████████▊               | 102kB 69kB/s eta 0:0
>     57% |██████████████████▌             | 112kB 69kB/s eta 0
>     62% |████████████████████▏           | 122kB 59kB/s eta
>     68% |█████████████████████▉          | 133kB 51kB/s et
>     73% |███████████████████████▌        | 143kB 56kB/s
>     78% |█████████████████████████▏      | 153kB 59kB/
>     83% |██████████████████████████▉     | 163kB 59kB
>     89% |████████████████████████████▌   | 174kB 53
>     94% |██████████████████████████████▏ | 184kB
>     99% |███████████████████████████████▉| 194kB
>     100% |████████████████████████████████| 204k
> B 65kB/s
> Requirement already satisfied: gevent in c:\programdata\anaconda2\lib\site-packa
> ges (from websocket)
> Requirement already satisfied: greenlet in c:\programdata\anaconda2\lib\site-pac
> kages (from websocket)
> Building wheels for collected packages: websocket
>   Running setup.py bdist_wheel for websocket ... done
>   Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\f0\
> a0\e9\00f3388fdb7e211988e6b5d0ecf7037e78965e3519d03dbac8
> Successfully built websocket
> Installing collected packages: websocket
> Successfully installed websocket-0.2.1
> 

2. 问题来了，修复了#1问题后，执行，报错DLL load failed。 请教各位~

```
(C:\ProgramData\Anaconda2) F:\vnpy-master\examples\VnTrader>vntrader.bat

(C:\ProgramData\Anaconda2) F:\vnpy-master\examples\VnTrader>python run.py
C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api\ib\__in
it__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi
::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<
class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from vnpy.trader.gateway import (femasGateway, xspeedGateway,
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\tra
der\gateway\sgitGateway\__init__.py", line 4, in <module>
    from sgitGateway import SgitGateway
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\tra
der\gateway\sgitGateway\sgitGateway.py", line 16, in <module>
    from vnpy.api.sgit import MdApi, TdApi, defineDict
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api
\sgit\__init__.py", line 3, in <module>
    from vnsgitmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。

```

**Comment by vnpy** [comment]
SGIT和SHZD两个接口在win10上要额外安装vcredist的特定版本，我来从默认的run.py里移除吧

**Comment by vnpy** [comment]
呃，发现最新的分支已经移除了。

你直接在run.py里把sgitGateway和shzdGateway相关的代码删了就行

**Comment by yupoet** [comment]
哦，我是win 2012 R2 datacenter
