### ISSUE TITLE
ctaTemplate 中BarManager 的updateBar方法 合成x分钟bar不正确

### ISSUE THREAD

**Issue by wangxu666** [vnpy/vnpy#530]
应该是第5min中bar到达后，先处理5min的bar，再去推Xmin的bar

**Comment by wangxu666** [comment]
def updateBar(self, bar):
	"""1分钟K线更新"""
	newX = False      # 默认不是新的X分钟
	
	# 尚未创建对象
	if not self.xminBar:
		self.xminBar = VtBarData()
		newX = True

		
	# 初始化K线数据
	if newX:
		self.xminBar.vtSymbol = bar.vtSymbol
		self.xminBar.symbol = bar.symbol
		self.xminBar.exchange = bar.exchange
	
		self.xminBar.open = bar.open
		self.xminBar.high = bar.high
		self.xminBar.low = bar.low
	# 累加老K线
	else:
		self.xminBar.high = max(self.xminBar.high, bar.high)
		self.xminBar.low = min(self.xminBar.low, bar.low)
		
	# 通用部分
	self.xminBar.close = bar.close
	self.xminBar.datetime = bar.datetime
	self.xminBar.openInterest = bar.openInterest
	self.xminBar.volume += int(bar.volume)
	
	# X分钟已经走完
	if not bar.datetime.minute % self.xmin:   # 可以用X整除
		# 生成上一X分钟K线的时间戳
		self.xminBar.datetime = self.xminBar.datetime.replace(second=0, microsecond=0)  # 将秒和微秒设为0
		self.xminBar.date = self.xminBar.datetime.strftime('%Y%m%d')
		self.xminBar.time = self.xminBar.datetime.strftime('%H:%M:%S.%f')
		
		# 推送
		self.onXminBar(self.xminBar)
		
		# 释放xminBar对象
		self.xminBar = None

**Comment by vnpy** [comment]
这里的设计是：
1. 调用updateTick告知BM有新的tick更新，然后BM自动去合成1分钟K线，并调用回调函数
2. 显式调用updateBar告知BM有新的bar更新，然后BM自动去合成X分钟K线，并调用回调函数

**Comment by wangxu666** [comment]
恩，逻辑没问题。是否在合成的时候细节逻辑不对。5min bar 应该是在第 5个1 min bar到达时候处理bar 然后push ，目前的逻辑是5min 到达后先push 5min bar,这样导致每次5min bar的close 是第四个一分钟bar 的close.

**Comment by vnpy** [comment]
明白了，已经修复这个问题，多谢！
