### ISSUE TITLE
连接CTP无任何反应，求解答

### ISSUE THREAD

**Issue by cydrain** [vnpy/vnpy#537]
启动VtTrade.bat后能看到软件运行主界面，但点击“连接CTP”后主界面上看不到任何行情信息，“错误”和“日志”栏也没有任何输出。CTP_connect.json已经正确配置。
如果点击“连接币行”，能在主界面上看到行情信息，但无法下单。其他的所有连接都是没有任何输出。
求解答。

**Comment by vnpy** [comment]
配置文件OKCOIN_connect.json修改其中的内容为你自己的账户

**Comment by xldistance** [comment]
国内的比特币程序化API都关了，没的交易了

**Comment by cydrain** [comment]
为什么“连接CTP”看不到行情信息？

**Comment by vnpy** [comment]
连接后你得订阅行情才会有行情推送过来

**Comment by linbozhong** [comment]
启动VtTrade.bat后能看到软件运行主界面，但点击“连接CTP”后主界面上看不到任何行情信息，“错误”和“日志”栏也没有任何输出。CTP_connect.json已经正确配置。
我昨天还可以连接到ctp，今天就出现了上面这样没有任何反应的情况，请问什么原因？
