### ISSUE TITLE
有没有模拟盘的开发计划

### ISSUE THREAD

**Issue by wisfern** [vnpy/vnpy#538]
模拟盘，在我的想象中，策略发出的交易请求由模拟盘进行撮合，并模拟网关的行为，而行情数据由真实网关提供。
模拟盘记录的订单、成交、持仓数据，可以实时计算策略的绩效。
绩效显示在网页或者UI上。
不知道vnpy有没有这样的开发计划？

**Comment by vnpy** [comment]
暂时没有，这个功能通过simnow和各家的模拟柜台都能实现，而且还能提供一些后端的清算和风控功能，看不出来重复造轮子的价值
