### ISSUE TITLE
部署Centos7 上相当糟糕

### ISSUE THREAD

**Issue by wxjeacen** [vnpy/vnpy#539]
1. Docker 教程里面的command都过期了。
2. install.sh 里面虽然是基于conda,但是没有步骤去安装qt, 之类的依赖库，也包括boost, cmake等等。
3. 虽然没怎么看代码，但是感觉写的一般。bug很多。

强烈建议只用docker 一个路线部署，这样避免很多环境问题。

**Comment by zhouguangfu09** [comment]
还是建议楼上看看代码在做评论，安装的依赖库和编译的问题并不能推断出代码的质量优劣。

**Comment by vnpy** [comment]
1. centos不在官方支持计划里
2. docker现在还是开发版，v1.8发布的时候会解决过期、依赖库安装问题
