### ISSUE TITLE
关于平今和平昨的自动转换问题

### ISSUE THREAD

**Issue by DLHNET** [vnpy/vnpy#544]
## 用一个全新没有开过仓的账户（实际测试有没有昨仓都有可能报平今或者平昨错误）测试开1手rb1801合约，使用sell指令平仓时报平昨不足（测试版本：1.7.1 dev分支）：
![qq 20171015161311](https://user-images.githubusercontent.com/32806757/31582996-c32b0f34-b1c4-11e7-91f1-4f5e20ad0747.png)
## 下面截图是PyCharm的代码报错：
![qq 20171015161422](https://user-images.githubusercontent.com/32806757/31583024-39d8129e-b1c5-11e7-8013-f4220b8117ef.png)
##  附上开平测试代码：
![qq 20171015162609](https://user-images.githubusercontent.com/32806757/31583056-f49187be-b1c5-11e7-9243-2fe13476dfd1.png)
---------------------------------------------------------------------------------------------------
    def onTick(self, tick):
        """收到行情TICK推送（必须由用户继承实现）"""
        # tick计数器
        if self.trading:
            self.K += 1
        # 每累计50个tick测试开平操作
        if self.pos == 0 and self.K % 50 == 0:
            self.buy(tick.lastPrice + 5, 1)
        if self.pos == 1 and self.K % 100 == 0:
            self.sell(tick.lastPrice - 5, 1)

        self.putEvent()

**Comment by vnpy** [comment]
这个是CTA引擎里委托管理逻辑的问题，和开平仓无关，已更新了处理后的代码，请再测试下

**Comment by DLHNET** [comment]
### 相同测试代码，在新账户没有任何昨仓的情况下正常（已不会像之前一样报错）。但有多空互持的昨仓情况（锁仓或者其他策略开的相反持仓），用测试代码平完了多头持仓，再开多，平仓时仍然还是平昨，导致报平昨不足
![qq 20171016155457](https://user-images.githubusercontent.com/32806757/31601331-1d83c918-b28c-11e7-8719-88465ad93329.png)

**Comment by xldistance** [comment]
这是simnow 7X24小时接口问题，时间更新到了下一天，但是持仓还是今仓没变导致平仓出错

**Comment by vnpy** [comment]
检查了一下持仓细节缓存的实现，确实没找到有问题的地方，也猜测可能是接口问题，请试试simnow的第一组正常交易服务器或者实盘服务器把。

**Comment by DLHNET** [comment]
## 夜盘开盘后使用simnow第一套第一组服务器，测试过程如下：
同时持有rb1801多空单（柜台已经初始化为昨仓了）：
![qq 20171016210445](https://user-images.githubusercontent.com/32806757/31613889-0ac356c4-b2b7-11e7-9039-aa20fc2011bb.png)
## 再使用策略开平（有昨仓平昨是正常的）：
![image](https://user-images.githubusercontent.com/32806757/31613975-52cce728-b2b7-11e7-808e-6200aa24ae13.png)
## 关闭vnpy，再手工把昨仓多头全平了：
![image](https://user-images.githubusercontent.com/32806757/31614028-7d8ee844-b2b7-11e7-859c-3a8fa418e28b.png)
最后重新启动vnpy使用策略开仓（正常），平仓时报平昨不足：
![qq 20171016211048](https://user-images.githubusercontent.com/32806757/31614119-c4fc9550-b2b7-11e7-962b-8cad7097cb8c.png)

**Comment by vnpy** [comment]
能否帮忙看下，vn.py在昨仓平完后，是否还在显示有昨仓？

**Comment by xldistance** [comment]
平完昨仓再开今仓出现keyerror,ctp.2，simnow同步模拟盘，重新打开程序后显示平仓和开仓都是成功的

**Comment by DLHNET** [comment]
左边是vnpy持仓信息，右边是快期：
![qq 20171017114239](https://user-images.githubusercontent.com/32806757/31645807-9ddf31b6-b330-11e7-9c0b-b8ad36ea5129.png)

**Comment by vnpy** [comment]
@xldistance 请试试最新的dev分支，这个KeyError的问题应该解决了

**Comment by vnpy** [comment]
@DLHNET 你是否将rb设置为了“平今惩罚”模式？

**Comment by vnpy** [comment]
已解决！
