### ISSUE TITLE
CTP TdApi 偶尔无法退出

### ISSUE THREAD

**Issue by bigdig** [vnpy/vnpy#548]
int TdApi::exit()
{
	//该函数在原生API里没有，用于安全退出API用，原生的join似乎不太稳定
	this->api->RegisterSpi(NULL);
	this->api->Release();
	this->api = NULL;
	return 1;
};
在Release之前不需要调用RegisterSpi(NULL);注销Spi的，如果这样做了，有可能导致CTP退不出的

**Comment by vnpy** [comment]
这个是参考了官方一个demo里的实现，问下是怎么出现退出不了的情况？手动关闭VnTrader不太可能卡住吧

**Comment by vnpy** [comment]
这个是参考了官方一个demo里的实现，问下是怎么出现退出不了的情况？手动关闭VnTrader不太可能卡住吧

**Comment by bigdig** [comment]
我是在每个分段交易前10分重新连接交易服务，每一两周就会出现关闭时阻塞现象，原因定位到exit()这里，解决方法我也是在网上看一哥们说的（我也还没有确认这样就一定好使^_^）。
`        #盘前10分钟
        timesOn = ['08:50',"13:20","20:50"]
        timesOff = ['15:10','23:10']
        #重启
        reBoot = lambda: [log.debug("Stopping"), stop(), log.debug('Staring'), start(), log.debug('Restart OK')]

        #开机先起动
        start()
        #开盘前重启
        [ schedule.every().day.at(t).do( 
            lambda:reBoot() if datetime.now().isoweekday() not in [6,7] else None )
              for t in timesOn]`
