### ISSUE TITLE
DEV版本中新添加的BollChannel策略实盘模拟时出现错误

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#550]
BollChannel这个策略在实盘模拟时出现报错，似乎是因为新添加的撤单系统导致的。

![image](https://user-images.githubusercontent.com/30992082/31702757-c56ceaf8-b40b-11e7-8948-000dc57f99ca.png)

**Comment by vnpy** [comment]
dev已经解决了，请等待v1.7.2正式版发布后升级吧
