### ISSUE TITLE
How to get the data for Dow/Nasdaq?

### ISSUE THREAD

**Issue by zhenqidong** [vnpy/vnpy#552]
New to this, I will dig into it while someone may possibly provide me an answer, thanks!
Please label this as a question only, thanks!

**Comment by vnpy** [comment]
You can use ibGateway to connect to Interactive Brokers and get stock price data for Dow/Nasdaq or futures price data of the two indexes on CME.

You may also use shzdGateway to connect to Shanghai Zhida Futures for futures data.
