### ISSUE TITLE
增加飞创xone接口

### ISSUE THREAD

**Issue by leftround** [vnpy/vnpy#554]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
Issue内容要写啊，xone的使用环境比较严，目前感觉用户需求不大吧？

**Comment by leftround** [comment]
xone已经完全取代xspeed了，您说的环境比较严的情况也不存在了，所以还是有必要替换掉xspeed接口了

**Comment by vnpy** [comment]
OK，后续版本里来做

**Comment by vnpy** [comment]
和飞创方面沟通后，决定暂停XONE接口的开发，原因如下：
1. X1柜台主要定位是低延时超高频交易，这块不是vn.py的主要业务
2. X1柜台只允许在大商所的特定机房部署，而且很多期货公司要求托管服务器的用户才能访问，受众太窄
