### ISSUE TITLE
CTPgateway没有区分期货期权和个股期权

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy#557]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
在程序中合约查表得时候将个股期权赋值为7 PC_ETFOption
股票也有同样的问题

## 实际程序行为
没有正确填写productclass, 最后识别为unknown

## 重现步骤
接入CTP，查询合约

针对Bug类型Issue，请提供具体重现步骤以及报错截图

解决方案，修复ProductClassMap

**Comment by vnpy** [comment]
已修复
