### ISSUE TITLE
大商所日期调整异常

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#559]
## 环境
CTP 函数onRtnDepthMarketData
在对大商所日期调整时，有误。

## Issue类型
三选一：Bug

## 预期程序行为
大商所日期在进入夜盘后，将日期调换为第二天的日期。

## 实际程序行为
1，目前的日期受旧数据的影响，也就是登陆前，服务器可能推送几条旧数据过来，旧数据的时间会影响代码进行判断，导致日期被不正确地增加，从而得到未来好多天的日期。

2，日期的调整，不利于数据的排序，例如：
10.20日的夜盘数据，变更日期后的时间为 10.21 22:21:20，而与真正第二第的日期 如 20.21 9:30:35 在进行排序的时候，反而排到了更后面。

## 重现步骤

重跑即可。

**Comment by szsa** [comment]
把这段儿代码替换就可以了

       # 大商所日期转换
        if tick.exchange is EXCHANGE_DCE:
            newTime = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 最新tick时间戳

            #  夜盘日期减1或3
            if newTime > NIGHT_TRADING :
                actionDay = datetime.strptime(tick.date,'%Y%m%d')  # 获取自然日信息并转化为date对象
                if datetime.today().weekday() == 4:
                    actionDay += timedelta(-3)                          # 日期减3
                else:
                    actionDay += timedelta(-1)
                tick.date = actionDay.strftime('%Y%m%d')    # 生成新的日期字符串

**Comment by ShellMount** [comment]
@szsa   这个逻辑，好像没有解决，   夜盘前打开软件，服务器会向客户端推送几条旧行情（下午盘）
每一次，上面的逻辑都会被执行一次。
所以它也会成倍地变更日期。

**Comment by ShellMount** [comment]
@szsa 此外： ---》
2，日期的调整，不利于数据的排序，例如：
10.20日的夜盘数据，变更日期后的时间为 10.21 22:21:20，而与真正第二第的日期 如 20.21 9:30:35 在进行排序的时候，反而排到了更后面。

**Comment by szsa** [comment]
旧行情要靠过滤了，无效的tick过滤掉
排序的问题，原版代码是有问题，上面的给的代码已经修改了，10月20晚上的夜盘数据，现在的日期是10月20日，正好与第二天10月21日白天的排序在前面

**Comment by vnpy** [comment]
已经更新了大商所日期获取逻辑代码，请测试下。

关于垃圾tick的问题，请试试开盘前10分钟再启动程序，看看是否还会有垃圾tick过来
