### ISSUE TITLE
没有今仓的情况下平仓会触发平今

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#560]
品种螺纹钢，错误CTP:报单字段有误，多平今成交数量是空的，委托状态拒单。这个BUG不影响使用，显示平昨成功了......

**Comment by cn-ansonkai** [comment]
主要是因为SHFE的指令是 平今 和 平昨

**Comment by xldistance** [comment]
今仓为0，平仓是这样写的吗            #今仓为0,平昨
            elif re.volume > tdAvailable and tdAvailable == 0:
                reqYd = copy(req)
                reqYd.offset = OFFSET_CLOSEYESTERDAY
                reqYd.volume = req.volume - tdAvailable

                return [reqYd]
