### ISSUE TITLE
使用BarManager后，行情记录模块会丢失最后一分钟的分钟记录

### ISSUE THREAD

**Issue by szsa** [vnpy/vnpy#565]
## 环境

* 操作系统: Windows 7或者Ubuntu 16.04都是
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2发行版或者dev branch 20171020（下载日期）

## Issue类型
三选一：Bug
## 预期程序行为
完整记录分钟数据

## 实际程序行为

当收市线程终止，会出现该bug，也就是每天15点收盘和夜盘收盘，
在原来不引入BarManager情况下，最后一分钟的分钟数据会在第二天开盘来tick的时候存入数据库，
引入后，tick记录正常，但是最后一分钟的bar就丢失了
导致：如果当日行情有15:00及以后的tick，14:59的分钟数据就会记录进入数据库；如果服务器不发送15:00及以后tick数据，或者行情本身没有，那么14:59的分钟数据在下次开盘后也没有存入数据，丢失了

使用BarManeger的策略应该会遇见类似问题

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
不是丢失啊，本来最后一分钟行情就是下一分钟走完推送的

**Comment by szsa** [comment]
是的，逻辑是下一分钟推送上一分钟行情
但是目前的连续行情继续模块，收市就中断了线程，缓存里面的数据丢失了

**Comment by szsa** [comment]
好像一样的，汗……
