### ISSUE TITLE
参数调优能否输出更多内容？

### ISSUE THREAD

**Issue by JasonXZh** [vnpy/vnpy#568]
目前在做参数调优时，只输出了参数值和调优目标的值（如总利润），能否输出更多结果，比如交易次数、平均盈利、盈亏比、胜率等等，类似单独跑回测的输出结果？
或者指教一下，在哪里添加日志可以输出这些内容？

**Comment by vnpy** [comment]
我回头来给个例子吧

**Comment by vnpy** [comment]
已完成
