### ISSUE TITLE
vtMain中oandaGateway的问题

### ISSUE THREAD

**Issue by hntee** [vnpy/vnpy#57]
1. vtMain中没有验证OANDA_connect.json中的token是否正确，不管正确与否，都可以初始化成功
![image](https://cloud.githubusercontent.com/assets/1583261/14699770/0c47426c-07cd-11e6-96f1-a3125c58df70.png)

2. 在填写正确的token的情况下，连接之后不知道应该做什么，界面也没有反应，报错这里的错误信息也不太明白
![image](https://cloud.githubusercontent.com/assets/1583261/14699679/4eefe890-07cc-11e6-8352-e48b60c50ab5.png)

**Comment by hntee** [comment]
另外还有个问题，在运行vn.oanda/test.py的时候，应该怎么退出？（按ctrl+c没有作用）

**Comment by vnpy** [comment]
1. OANDA的API是基于REST的实现，没有登录验证这个过程，所以也无法知道token是否正确
2. 检查是否选择了正确的环境：测试和实盘
3. 直接杀进程（关闭cmd），这个test是用来测试和演示的，没有做退出函数

**Comment by hntee** [comment]
> 检查是否选择了正确的环境：测试和实盘

这里选择的是practice，需要实盘才可以有数据流入？

**Comment by vnpy** [comment]
没，如果你是practice，就要保证用的账户和token都是practice的，实盘也是一样，否则可能就会出错。
