### ISSUE TITLE
使用最新的CTP dll导致python程序崩溃

### ISSUE THREAD

**Issue by yc3231996** [vnpy/vnpy#570]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: latest

## Issue类型
Bug，问题

最新的官方CTP DLL版本是v6.3.6_20160715，跟git上CTP直接编译好的vnctpmd.pyd和vnctptd.pyd配合使用会导致程序崩溃。是不是还不支持最新的CTP DLL版本？

## 重现步骤
用最新的CTP dll替换git上的dll。

**Comment by vnpy** [comment]
更换API的话，有可能头文件里的函数发生了变化，需要重新编译
