### ISSUE TITLE
bar线合成的 第一根bar 成交量数据不对

### ISSUE THREAD

**Issue by ipqhjjybj** [vnpy/vnpy#571]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
成交量合成正确

## 实际程序行为
成交量数据错误

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

```
if self.lastTick:
            self.bar.volume += (tick.volume - self.lastTick.volume) # 当前K线内的成交量
```
开盘的时候，第一根tick 还是None ,但是 不会记录这根。  
这是个小问题，但是我感觉目前程序好像无法解决这个问题

然而比较后， 发现 09:00开票的合成成交量数据是对的， 但是 21:00开盘的数据是错得，很奇怪哟

**Comment by vnpy** [comment]
目前的K线成交量累加是基于tick间的volume差，因此每个交易日结束后必须清空整个程序的数据：即下午3点当日交易结束后必须关闭交易程序，在夜盘（一个新的交易日）开盘前重新启动，避免前一天的成交量数据影响第二天的统计。
