### ISSUE TITLE
价差模块上期所平今昨仍然有问题，亟待解决。

### ISSUE THREAD

**Issue by vippere** [vnpy/vnpy#572]
## 环境

* 操作系统: Windows10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.71发行版（下载日期10月18日）
问题描述：用程序自带的价差模块Sniper算法,测试上期所品种，正确触发买单后，无法自动平仓，错误信息为：平昨仓位不足，实际仓位是今仓，程序判断为昨仓，导致拒单。
![qq 20171024093300](https://user-images.githubusercontent.com/18280449/31920890-6497dfe8-b89e-11e7-9570-992dfcf9c85f.png)

**Comment by vippere** [comment]
补充，非上期所也不能平今仓。

**Comment by vippere** [comment]
补充：非上期所也部能平今。

**Comment by vippere** [comment]
补充：非上期所也不能平今。

**Comment by vnpy** [comment]
之前价差交易模块忘记修改支持自动平今、平昨了，已经加上！
