### ISSUE TITLE
建议统一vtObject.py文件里对象的日期时间属性为python的datetime格式

### ISSUE THREAD

**Issue by miyihuxi** [vnpy/vnpy#573]
建议把vtObject.py文件里对象的日期时间属性，都统一成python的datetime格式的属性，或者增加其它对象的 datetime格式属性。目前只tick和bar有 datetime格式的属性，而其它对象却没有，统一了才好做比较和运算。比如：发出委托要根据tick的时间来决定撤单动作，order的self.orderTime无法直接与tick的self.datetime作运算。

**Comment by vnpy** [comment]
这个问题考虑后决定不在底层中添加，主要原因：
1. 并非所有类型的交易应用都需要数据时间戳的比较，例如OptionMaster、SpreadTrading都无此需求
2. datetime对象的创建开销并不是特别小，因此对于每个tick都要生成的话会拖慢系统速度

有需要的用户请自行修改CtaEngine或者CtaTemplate添加吧
