### ISSUE TITLE
连续运行程序，第二天策略发不出单

### ISSUE THREAD

**Issue by JasonXZh** [vnpy/vnpy#579]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: v1.6.2

## Issue类型
三选一：Bug

## 程序行为
第一天是正常的，日志上有发单，实际上也发单了。
然后没有重启程序。
第二天，“CTA策略”这个页面上的日志有发单日志，但是实际上没有发单。

**Comment by vnpy** [comment]
VnTrader的进程每天收盘后必须关闭，第二天盘前重启；想要实现自动运维请参考examples/CtaTrading下的守护进程模式。
