### ISSUE TITLE
GITHUB上直接下载的PYD和DLL使用，确认结算出错

### ISSUE THREAD

**Issue by yc3231996** [vnpy/vnpy#580]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 直接下载的CTP的pyd和dll

## Issue类型
Question

直接使用GITHUB上下载的CTP的PYD和DLL使用，确认结算报下面的错：
TypeError: 'NoneType' object is not callable

连接的是SIMNOW环境：
交易前置 180.168.146.187:10030，行情前置：180.168.146.187:10031

可能是需要重新编译下得到最新的PYD吧，由于还不熟悉C++，是否可以请作者重新编译得到最新可用的PYD放到GITHUB上来。

**Comment by vnpy** [comment]
你必须实现所有的回调函数接口，不用的就写pass，参考test里的.py文件
