### ISSUE TITLE
1.7.1版本大商所tick.date计算有误

### ISSUE THREAD

**Issue by huqinghua109** [vnpy/vnpy#581]
ctpGateWay里面的onRspUserLogin函数获取的self.tradingDate = data['TradingDay']是交易所概念的交易日日期，而非登录时点的日期。并且“self.tradingDt += timedelta(1)# 日期加1”的算法也有问题，如果接收的tick时间顺序絮乱，则计算出来的tradingDt 是错误的

**Comment by vnpy** [comment]
多谢，尽快修复！

**Comment by vnpy** [comment]
改为使用本地时间日期的方式来获取tradingDt。

维持self.tradingDt += timedelta(1)的逻辑，考虑到实盘行情服务器的tick时间顺序绝大部分时候都是可靠的，再加上在盘前定时启动以及盘后定时关闭的逻辑，过滤掉潜在的垃圾数据推送。
