### ISSUE TITLE
同策略做多品种的时候，参数混了

### ISSUE THREAD

**Issue by JasonXZh** [vnpy/vnpy#583]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.6.2

## Issue类型
三选一：Question

## 预期程序行为
做了一个策略，想在多个品种上跑，在CTA_setting.json中就配置了多个品种，但跑起来之后，发现策略中的变量值都混了几个品种的数据在一起。

请教是不是应该设置为多线程才能跑多个品种？还是哪里设置的有问题？

**Comment by xldistance** [comment]
多品种变量都放到def __init__(self, ctaEngine, setting):下面

**Comment by vnpy** [comment]
楼上正解，所有可变数据容器，比如list/dict/numpy array都最好放在__int__函数下再初始化一下
