### ISSUE TITLE
ctaTrading 子进程关闭时保存持仓到本地

### ISSUE THREAD

**Issue by HY-Scatterer** [vnpy/vnpy#586]
1.7.1中 examples/CtaTrading中 runParentProcess会在非交易时间关闭子进程runChildProcess, 那么策略持仓回保存到本地数据库么？

**Comment by vnpy** [comment]
v1.7.1之后的策略持仓已经改为在收到成交回报的时候实时保存到数据库里了，后面再启动策略时会自动加载进来，只要数据库不挂就完全不用担心。
