### ISSUE TITLE
使用TargetPosTemplate多策略交易时下单错误

### ISSUE THREAD

**Issue by georgefeng** [vnpy/vnpy#589]
## 环境

* 操作系统: Windows Server 2008r2
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev branch (11月3日) 此问题在v1.7.1-master中也存在

## Issue类型
三选一：Bug

## 预期程序行为

策略正常下单并匹配为目标仓位

---

13:39:38	策略spsharp_i发送委托，i1801，多，1@439.0

---

## 实际程序行为

策略触发异常但持仓却保存成功

---

13:39:38	策略spsharp_i发送委托，i1801，多，1@439.0
13:39:38	策略spsharp_i触发异常已停止
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 565, in callStrategyFunc
    func(params)
  File "D:\2_SPTrade_0.2.0\strategySP.py", line 151, in onOrder
    super(MinTemplate, self).onOrder(order)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 249, in onOrder
    self.orderList.remove(order.vtOrderID)
ValueError: list.remove(x): x not in list

13:39:38	策略spsharp_i持仓保存成功，当前持仓1

---

下单部分代码：
```
def onXminBar(self, bar):
    xxxxxxxxxxxxxxx
    xxxxxxxxxx   
    if _sign['BuyOpen']:
        self.setTargetPos(1)
    elif _sign['SellOpen']:
        self.setTargetPos(-1)
```

## 重现步骤
1. 使用TargetPosTemplate模板编写策略
2. 在Backtest模块中测试正常
3. 设定策略在多品种上交易(如ni1801和ru1801, 策略名已作区分)
4. 启动run_simple.py  (另：runCtaTrading.py也会出现相同错误)
5. 初始化策略
6. 启动交易，然后出现上述问题

补充：
- 将所有仓位平掉，并在mongoDB中删除对应持仓的缓存，彻底重启系统，错误会出现。
- 使用不同策略，错误会出现。
- 使用1.7.1master和dev分支，错误均会出现。
- 有时会启动时出现错误，也有可能正常运行一会(如半小时)后出现错误。

**Comment by likenji** [comment]
给remove加一个if in的条件判断，可以解决这个问题。但问题原因我也不清楚

**Comment by vnpy** [comment]
我来处理下

**Comment by xinhuih** [comment]
我也遇到此问题，猜测是trade()函数在开头部分全部撤单时，一些order还没有更新状态，同时下一条命令就直接清空了orderList。导致onOrder函数找不到orderList里面的对应order。

**Comment by vnpy** [comment]
已修复
