### ISSUE TITLE
TdApi onRspUserLogin后不停的报错 TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by fakechris** [vnpy/vnpy#59]
触发条件，tdapi第一次登录一个账号时。删除所有*.con文件登录可以触发，代码

<pre>
class TestTdApi(TdApi):
    def onFrontConnected(self):
        """服务器连接"""
        logger.info("td connected")

        loginReq = {}                           # 创建一个空字典
        loginReq['UserID'] = FLAGS.username                 # 参数作为字典键值的方式传入
        loginReq['Password'] = FLAGS.passwd               # 键名和C++中的结构体成员名对应
        loginReq['BrokerID'] = FLAGS.brokerid
        self.reqUserLogin(loginReq, 1)

    def onRspUserLogin(self, data, error, n, last):
        logger.error("td user login")

def main():
    apitd = TestTdApi()
    apitd.createFtdcTraderApi('')
    apitd.subscribePrivateTopic(1)
    apitd.subscribePublicTopic(1)
    apitd.registerFront("tcp://180.166.103.38:41205")
    apitd.init()
</pre>

错误输出：

INFO:test_cli:td connected
eth1: Resource temporarily unavailable
INFO:test_cli:td user logined {'CZCETime': '11:18:56', 'SHFETime': '11:18:56', 'MaxOrderRef': '1', 'BrokerID': '3040', 'INETime': '--:--:--',
 'UserID': '...', 'TradingDay': '20160426', 'SessionID': -568300646, 'SystemName': 'TradingHosting', 'FFEXTime': '11:18:56', 'FrontID':
4, 'DCETime': '11:18:57', 'LoginTime': '11:18:56'}
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
....

**Comment by vnpy** [comment]
回调函数要全部实现（用不到的就写pass），否则C++层面向Python中推送数据时，会因为找不到回调函数，报TypeError: 'NoneType' object is not callable。

**Comment by fakechris** [comment]
谢谢
