### ISSUE TITLE
盈透投顾账户

### ISSUE THREAD

**Issue by guoqing82** [vnpy/vnpy#590]
## 环境
Windows server 2016,
Anaconda 4.0.0 Python 2.7 32位
vnpy1.5
* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Enhancement
## 预期程序行为
使用vnpy链接盈透顾问账户，连tws以及ibgateway

## 实际程序行为
实际可以连接历史数据和行情数据，但连接账户的时候报错

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
实际链接的时候是如下图报错
![default](https://user-images.githubusercontent.com/13774774/32361789-b058a766-c09e-11e7-8d89-75be3f1eac90.png)
但用盈透官方的demo(c++)连接的时候如下图所示
![default](https://user-images.githubusercontent.com/13774774/32361797-bcf745ea-c09e-11e7-936a-2726de31a0be.png)
但现在IB_connect.json里面填写的账号是一个U开头的账户，但投顾账户是F开头的账户，下属一个或者多个U开头的普通账户。
另外，印象中官方demo里关于顾问账户是有一些单独代码去实现的，毕竟订单类型跟普通账户不同。记得好像可以选择一种下单分配的方式，比如下10手单子，两个账户可以按照提前设定的3:7等比例分配订单，或者其中一个账户永远是固定的2手去下单。这些具体分配不用体现在代码里，但这几种分配方式的选择设定要在代码中体现。
如果有需要，群主可以使用我的模拟顾问账户，我就在群里，qq：392940030

**Comment by vnpy** [comment]
研究了下IB的FA账户功能，这块比较接近国内资产管理系统（如讯投、O32等）的业务功能 ，相关接口和目前开源版vn.py针对的交易员业务的区别相当大，决定不再继续开发。

有需求的用户可以自行定制修改ibGateway的实现，以及在上层开发一个IB的FA配置编辑工具，从而支持FA的全部功能。
