### ISSUE TITLE
策略中如何获取数据库（mongo）连接，进而做数据操作？

### ISSUE THREAD

**Issue by JasonXZh** [vnpy/vnpy#591]
## 环境

* 操作系统: 如Windows10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.6.2

## Issue类型
三选一：Question

## 预期程序行为
想在策略中保存一些中间结果到mongo，还需要在策略类的init中创建新连接吗，比如：
self.dbClient = pymongo.MongoClient(globalSetting['mongoHost'], globalSetting['mongoPort'])

有其他更方便的方法吗？

**Comment by vnpy** [comment]
理论上，策略对象里，你可以通过self.ctaEngine.mainEngine.dbInsert来向数据库插入数据，dbQuery来查询。

但是这不是个特别安全的方案，操作不好很容易出现各种问题，所以没有设计在模板里。

**Comment by JasonXZh** [comment]
但是在BacktestingEngine中好像没有mainEngine这个属性，策略里像self.ctaEngine.mainEngine这种写法是不是会导致不能回测？

**Comment by vnpy** [comment]
必然的了，如果你的策略里有涉及到数据库操作的东西，那几乎都是不能回测的

**Comment by JasonXZh** [comment]
主要是因为实盘的时候，每天要重启策略。
想把之前的运行状态保存下来，下次启动的时候直接导入，就不用重新导入历史数据计算了。

**Comment by vnpy** [comment]
这个从经验上看也不是很好的方案，如果你的策略足够稳健，那么任意时刻的状态应该是可以通过历史行情+最新持仓直接还原出来的

**Comment by JasonXZh** [comment]
嗯，想保存的是更类似position的数据。通过历史也可以倒推，但是可能因为实际过程中的一些实际原因，和理论上的不是100%完全一致。所以也懒得去写通过历史还原的逻辑，想直接保存下来。

**Comment by vnpy** [comment]
实盘可以这么干，回测上就没有办法了

**Comment by JasonXZh** [comment]
收到，谢谢！
