### ISSUE TITLE
1.71版价差交易模块平隔夜仓时，出现委托手数为非正整数，被风控模块拦截

### ISSUE THREAD

**Issue by luzhisheng1986** [vnpy/vnpy#592]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.71发行版

## `Issue类型`
三选一：Bug

## 预期程序行为
我在价差引擎文件STEngine.py中的sendOrder中加入了主引擎中的委托转函数convertOrderReq，实现上海交易所合约的自动平今功能。

## 实际程序行为
自动平今功能能够实现，但是当有隔夜持仓时，触发设定的平仓价差后，程序发送的委托数量是一个非正整数，发送的平仓单子都被风控模块拦截。

## 重现步骤
1、设置上海交易所的合约，例如铜铝锌的套利对子，建立隔夜持仓。仓位建立完毕后，单击停止按钮，关闭程序。
2、第二天触发平仓价差，算法信息框中显示程序发送平仓单子，但风控模块提示“委托数量必须大于0”

其中，STEngine.py中的sendOrder代码修改后如下：

   def sendOrder(self, vtSymbol, direction, offset, price, volume, payup=0):
        """发单"""
        contract = self.mainEngine.getContract(vtSymbol)
        if not contract:
            return ''
        
        req = VtOrderReq()
        req.symbol = contract.symbol
        req.exchange = contract.exchange
        req.vtSymbol = contract.vtSymbol
        req.direction = direction
        req.offset = offset
        req.volume = int(volume)
        req.priceType = PRICETYPE_LIMITPRICE
        
        if direction == DIRECTION_LONG:
            req.price = price + payup * contract.priceTick
        else:
            req.price = price - payup * contract.priceTick
   
        # 委托转换
        reqList = self.mainEngine.convertOrderReq(req)
       vtOrderIDList = []
        
        if not reqList:
            return vtOrderIDList
        
        for convertedReq in reqList:
            vtOrderID = self.mainEngine.sendOrder(convertedReq, contract.gatewayName)    # 发单
           
            return vtOrderID
截图如下：
![1](https://user-images.githubusercontent.com/33363195/32403290-099359f2-c171-11e7-8803-714aa55a7cae.jpg)

![2](https://user-images.githubusercontent.com/33363195/32403293-13a4e10e-c171-11e7-8f45-6cb1ea2aeac3.png)

就修改了这个函数的代码，其他代码没有改变。
以上代码的修改不知道是否存在错误，望大家指出。
最后就是想价差交易能够实现自动识别平昨平今功能。
望群主大大帮忙处理，谢谢！

**Comment by vnpy** [comment]
委托自动转换的问题，已解决
