### ISSUE TITLE
最新版dev ctaBacktesting组合回测出错

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#594]
## 环境

* 操作系统: win10
* Anaconda版本: Anaconda 5.0.0 Python 2.7 32位
* vn.py版本: v1.7.1dev   20171109

## Issue类型
三选一：Bug

## 预期程序行为
更新ctaBacktesting后组合回测出错

## 实际程序行为
engine = BacktestingEngine()
engine.setCapital(100000)
engine.showDailyResult(dfp,result = None) result怎么运行后怎么没有传入参数

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 1040, in showDailyResult
    self.output(u'首个交易日：\t%s' % result['startDate'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by vnpy** [comment]
为了实现SharpeRatio为目标函数的优化回测，修改了showDailyResult函数，还没全部开发好，尽快弄完

**Comment by xldistance** [comment]
issue看到解决办法了组和回测最后改为
engine = BacktestingEngine()
engine.setCapital(1000000)
dfp, result = engine.calculateDailyStatistics(dfp)
engine.showDailyResult(dfp, result)
