### ISSUE TITLE
建议统一cta交易模式与回测模式获取委托单对象的方法

### ISSUE THREAD

**Issue by miyihuxi** [vnpy/vnpy#598]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
在用户策略中，有时希望获得委托单的时间或其它信息，目前在交易与回测中用的如下办法。
在交易模式下，获取order对象的方式为：order = self.ctaEngine.mainEngine.getOrder(orderID)
在回测模式下，获取order对象的方式为：order = self.ctaEngine.workingLimitOrderDict[orderID]

## 实际程序行为
这样导致了用户策略，要在两种模式下工作，需要对代码进行修改。当然在用户策略中也可以根据self.engineType，来做判断。有没有更好办法呢？

**Comment by vnpy** [comment]
以上两种用法都是不对的，委托单order的对象会通过策略模板的onOrder推送过来，用户只要在策略里创建一个字典用来保存这些对象就好了。

正常开发的流程中不建议访问引擎层面的方法和数据，这个不是设计的使用方法。

**Comment by miyihuxi** [comment]
OK，还是建议给order对象加上datetime属性
                    sjjg = bar.datetime - order.datetime
                    if  sjjg.total_seconds() > 240.0:
                        self.cancelOrder(orderID)
委托时间大于4分钟未成交则撤单，这样写简洁得多，不然仅仅是合成日期就是一件很头疼的事。
