### ISSUE TITLE
K线聚合BUG

### ISSUE THREAD

**Issue by vippere** [vnpy/vnpy#599]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.71
##  BarManager类K线聚合判断条件有问题导致K线聚合结果出错。
程序1分钟K线合成时间戳每天第一根是从0分钟开始，至59分结束，在
  def updateBar(self, bar)函数中判断聚合完成的代码是：
 if not bar.datetime.minute % self.xmin:   
因为0可以被任何数整除，另外从0分开始计数至Xmin整数倍分钟聚合的K线多出来一根1分钟线，这样聚合的K线结果一定是错误的
如果改成  if not (bar.datetime.minute+1) % self.xmin:   
就可以了。

**Comment by vnpy** [comment]
已解决
