### ISSUE TITLE
关于securitytraderapi.so

### ISSUE THREAD

**Issue by philipchung007** [vnpy/vnpy#6]
完整路径：vnpy/vn.lts/ltsapi/securitytraderapi.so

请问是针对哪种platform编译的呢，mac还是linux？

**Comment by vnpy** [comment]
应该是linux，国内目前我还不知道有在mac上用的API

**Comment by philipchung007** [comment]
能否帮忙要求华宝给出针对mac环境编译的api？

**Comment by vnpy** [comment]
你可以找华宝谈谈看，我估计可能性不大。毕竟目前做交易的操作系统还是两种，客户机主要是windows，服务器是linux，mac的非常非常小众。

**Comment by philipchung007** [comment]
Thanks pal, I will see what I can do
