### ISSUE TITLE
tick回测bug

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#60]
陈总：

ctaBacktesting.py 中 newTick函数，第176行，
缺少 语句 self.dt = bar.datetime， 导致字典缺少key，回测时覆盖上一笔交易，最后结果只有1笔交易。

**Comment by vnpy** [comment]
多谢提醒bug，我会尽快修复。

**Comment by freeitaly** [comment]
应该是self.dt = tick.datetime，不好意思直接复制的没注意
