### ISSUE TITLE
出现ImportError: No module named vnxtpquote问题

### ISSUE THREAD

**Issue by SEUking** [vnpy/vnpy#600]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.1发行版
boost版本1.58
cmake版本3.5.1

## Issue类型
Question
在编译的时候出现警告：
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dvnib_EXPORTS -I/home/user/vnpy-1.7.1/vnpy/api/ib/./ibapi/linux/client -I/home/user/vnpy-1.7.1/vnpy/api/ib/IB_PATH -I/usr/include/python2.7  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o -c /home/user/vnpy-1.7.1/vnpy/api/ib/vnib/vnib/vnib.cpp
In file included from /home/user/vnpy-1.7.1/vnpy/api/ib/./ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/user/vnpy-1.7.1/vnpy/api/ib/vnib/vnib/vnib.h:25,
                 from /home/user/vnpy-1.7.1/vnpy/api/ib/vnib/vnib/vnib.cpp:5:
/home/user/vnpy-1.7.1/vnpy/api/ib/./ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/boost/function/function_base.hpp:16,
                 from /usr/include/boost/function/detail/prologue.hpp:17,
                 from /usr/include/boost/function/function_template.hpp:13,
                 from /usr/include/boost/function/detail/maybe_include.hpp:13,
                 from /usr/include/boost/function/function0.hpp:11,
                 from /usr/include/boost/python/errors.hpp:13,
                 from /usr/include/boost/python/handle.hpp:11,
                 from /usr/include/boost/python/to_python_value.hpp:12,
                 from /usr/include/boost/python/default_call_policies.hpp:10,
                 from /usr/include/boost/python/make_function.hpp:10,
                 from /usr/include/boost/python/def.hpp:11,
                 from /home/user/vnpy-1.7.1/vnpy/api/ib/vnib/vnib/vnib.h:10,
                 from /home/user/vnpy-1.7.1/vnpy/api/ib/vnib/vnib/vnib.cpp:5:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^

在运行example/VnTrader/run.py时候出现以下错误：
Traceback (most recent call last):
  File "/home/user/vnpy-1.7.1/examples/VnTrader/run.py", line 26, in <module>
    from vnpy.trader.gateway import xtpGateway
  File "/home/user/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "/home/user/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/user/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/api/xtp/__init__.py", line 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote

出现包未导入的问题。

**Comment by vnpy** [comment]
这是因为v1.7.1的ubuntu安装文件里忘记加上XTP的自动编译命令了，如果不用请先在run.py里移除xtpGateway相关的内容就行

**Comment by SEUking** [comment]
在install.sh中加入以下内容，run.py编译通过，正常启动。
pushd vnpy/api/xtp
bash build.sh
popd
