### ISSUE TITLE
现在的 log 都是固定的，不如可以自己传一个文件进去。没传才用默认那个。

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#602]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

现在的 log 都是固定的，不如可以自己传一个文件进去。没传才用默认那个。

**Comment by vnpy** [comment]
可以考虑

**Comment by vnpy** [comment]
已完成
