### ISSUE TITLE
空单持仓，收盘重启导致策略中的变量intraTradeLow无法恢复为盘前记录的数值

### ISSUE THREAD

**Issue by van88888** [vnpy/vnpy#603]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.1

## Issue类型
三选一：Bug

## 预期程序行为
收盘重启VNPY，空单持仓时，策略记录的intraTradeLow应该能够恢复成盘前的数值。

## 实际程序行为
策略初始intraTradeLow为0，空单持仓时，盘后重启VNPY，策略记录的intraTradeLow变成了0.

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
你没有记录行情数据吧

**Comment by vnpy** [comment]
谢谢，我来处理

**Comment by KobeZhao** [comment]
我是这样处理的，将intraTradeLow这些参数保存到json，盘前再读进来，懒人省事法，哈哈

**Comment by vnpy** [comment]
已经新增策略模板的syncData功能来解决该问题
@KobeZhao 将你建议的方案标准化了
