### ISSUE TITLE
 缺少“算法”和ValueError:

### ISSUE THREAD

**Issue by fluid126** [vnpy/vnpy#606]
1、按照windows 系统下的安装程序后，启动 VnTrader, 菜单栏只有 “系统”， “功能” 和“帮助”， 缺少“算法”
2、在SimNow网站上申请虚拟账号后，点开系统，连接CTP， 显示ValueError: no Jason object could be decoded。

刚接触，遇见以上两个问题，请指点，谢谢

**Comment by xldistance** [comment]
新版功能整合在功能里面，编辑json建议使用sublimetext
