### ISSUE TITLE
可以把 orderID 改为唯一的吗？如timestamp这样的

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#607]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
+++++++++++++++++++++++
在做日线策略的时候，如果要挂单到服务器上，并且不知道几天后才会成交的。似乎要用timestamp来做orderID比较好。这样可以唯一，可以根据这个单号来判断是成交，是哪次加码什么的。目前似乎偏重于日内的。

barmanager    K线生成器   似乎改名为 BarGenerator  好象是这样吧。
arrarmanager  K线管理器   改为比较直观。barManager  
不然一直搞不懂 arraymanager是干什么用的。

**Comment by vnpy** [comment]
1. BarGenerator这个建议挺好，我来修改下。Array能不能想想其他名字？BarManager其实也不太直观
2. 委托号这个主要考虑的是目前国内外常见交易系统的实现，如果策略需要保持跨交易时段的委托号唯一性，可以加上个采用datestr_timestr_orderID结合的这种形式，反正本质上都是个字符串而已

**Comment by viponedream** [comment]
1, 因为它的意思是K线放进去，指标生出来。所以可以叫K线孵化器或K线计算器。
2，唯一的ORDERID可以弄个全局数据库，每次从库中读取就不会重复了。
   可弄两个数据库，一个全局，一个策略的。
我看现在策略只保存pos信息，其实可以全存进去，需要用什么就读什么。只多一个参数而已，兼容性更好。

**Comment by viponedream** [comment]
设某一个触发点，比如仓位变化了，开单了，某个变量变化了等等就触发程序把这些变量存进去。

**Comment by viponedream** [comment]
在策略中，再由某个函数去调用某个变量。

**Comment by vnpy** [comment]
BarManager已改名为BarGenerator，数据库同步已修改
