### ISSUE TITLE
策略多周期共振回测没有信号

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#609]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3.6 64位
* vn.py版本: 如v1.7.1dev branch 20171114（下载日期）

## Issue类型
BUG

## 预期程序行为
CTP策略在30分钟聚合指标信息，在一分钟周期判断开平仓回测没有信号

## 实际程序行为
策略在onBar里面判断开平仓回测没有信号

**Comment by vnpy** [comment]
我来提供个跨周期回测的例子
