### ISSUE TITLE
求助，这个怎么办呀：libboost_python.so.1.65.1: undefined symbol

### ISSUE THREAD

**Issue by reaIws** [vnpy/vnpy#611]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 2.4.4 Python 2.7 64位
* vn.py版本: 如v1.7发行版（下载日期：20171120）

## Issue类型
三选一：Question

## 实际程序行为
程序启动成功

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
1.运行 install.sh文件
vnpy.trader.gateway.xtpGateway.xtpGateway: module references __file__
vnpy.trader.gateway.shzdGateway.shzdGateway: module references __file__
vnpy.trader.gateway.sgitGateway.sgitGateway: module references __file__
vnpy.trader.gateway.xspeedGateway.xspeedGateway: module references __file__
vnpy.trader.gateway.oandaGateway.oandaGateway: module references __file__
vnpy.trader.gateway.qdpGateway.qdpGateway: module references __file__
creating dist
creating 'dist/vnpy-1.7.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vnpy-1.7.1-py2.7.egg
creating /home/cmbc/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg
Extracting vnpy-1.7.1-py2.7.egg to /home/cmbc/anaconda2/lib/python2.7/site-packages
Adding vnpy 1.7.1 to easy-install.pth file

Installed /home/cmbc/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg
Processing dependencies for vnpy==1.7.1
Finished processing dependencies for vnpy==1.7.1

2.启动程序
\vnpy-master\examples\VnTrader\run.py

3.报错
Traceback (most recent call last):
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/examples/VnTrader/run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: /home/cmbc/anaconda2/lib/libboost_python.so.1.65.1: undefined symbol: PyUnicode_InternFromString

**Comment by vnpy** [comment]
这个的问题似乎出在boost上，请检查下安装的boost库版本是否正确

**Comment by reaIws** [comment]
@vnpy 行了

**Comment by gantians** [comment]
@reaIws  I have met the same problem. How did you solve the problem?
