### ISSUE TITLE
回测触发止损的返回信息

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#614]
现在回测中，触发了止损，它只返回了一个止损单号以及一个标志，已触发。
然后又返回了一个 onTrade，而这个 onTrade的单号是在引擎中自己生成的，我们策略中根本就不知道这个单号。
能不能在触发止损返回onStopOrder的时候就把这个单号一起返回给策略？

**Comment by vnpy** [comment]
目前不行呢，因为停止委托被触发后，实际发出去的单子是在那一刻才生成委托号的，所以在你下达停止委托的那一刻并不知道

**Comment by t0trader** [comment]
@vnpy 可以用FrontID + SessionID + OrderRef 在本地定位报单INPUT，然后和前置反馈的ORDER建立联系
