### ISSUE TITLE
vnpy可以实时聚合XBarK线，等满足XBar分钟再聚合一次吗？

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#615]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3.6 64位
* vn.py版本: v1.7.1dev branch 20171114

## Issue类型
三选一：Enhancement

## 预期程序行为
实时聚合XBarK线推送Bar可以最快的抓住行情，等满足XBar分钟再聚合错过不少利润了。可以设计成实时聚合XBarK线并推送，等满足XBar分钟的时候再聚合推送一次吗

**Comment by vnpy** [comment]
这种做法不能保证回测中的数据一致性，说白了就是可能出现所谓实盘信号闪烁的情况，算是CTA策略里一个比较初级的坑了
