### ISSUE TITLE
onTick()回调速度慢的问题

### ISSUE THREAD

**Issue by kevinlee1974** [vnpy/vnpy#616]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.3.0 Python 2.7 64位
* vn.py版本: 如v1.7.1发行版

## Issue类型
Question

## 预期程序行为
'vtGateway收到Tick数据，put进入策略的队列后，策略函数onTick()应该很快回调，的回调时间一般延后20-30毫秒
## 实际程序行为
'vtGateway收到Tick数据，put进入策略的队列后，策略函数onTick()的回调时间一般延后20-30毫秒

## 重现步骤
在'vtGateway的onTick()函数中增加打印信息
    def onTick(self, tick):
        """市场行情推送"""
        # 通用事件
        event1 = Event(type_=EVENT_TICK)
        event1.dict_['data'] = tick
        self.eventEngine.put(event1)
        print("vtGateway::onTick()",time.time(),event1.type_)
        # 特定合约代码的事件
        event2 = Event(type_=EVENT_TICK+tick.vtSymbol)
        event2.dict_['data'] = tick
        self.eventEngine.put(event2)
	print("vtGateway::onTick()",time.time(),event2.type_)

在策略MyStrategy的onTick()中增加打印信息
class MyStrategy(CtaTemplate):

    def onTick(self, tick):
        """收到行情TICK推送（必须由用户继承实现）"""
        print("MyStrategy::onTick() time:",time.time())

针对Bug类型Issue，请提供具体重现步骤以及报错截图
打印信息如下：
('vtGateway::onTick()', 1511327132.446368, 'eTick.')
('vtGateway::onTick()', 1511327132.446532, 'eTick.IF1712')
('MyStrategy::onTick() time:', 1511327132.492622)

('vtGateway::onTick()', 1511327132.936723, 'eTick.')
('vtGateway::onTick()', 1511327132.936898, 'eTick.IF1712')
('MyStrategy::onTick() time:', 1511327132.961351)

('vtGateway::onTick()', 1511327133.705335, 'eTick.')
('vtGateway::onTick()', 1511327133.705477, 'eTick.IF1712')
('MyStrategy::onTick() time:', 1511327133.746765)

('vtGateway::onTick()', 1511327133.940717, 'eTick.')
('vtGateway::onTick()', 1511327133.940854, 'eTick.IF1712')
('MyStrategy::onTick() time:', 1511327133.968843)

('vtGateway::onTick()', 1511327134.460096, 'eTick.')
('vtGateway::onTick()', 1511327134.46041, 'eTick.IF1712')
('MyStrategy::onTick() time:', 1511327134.487052)

**Comment by vnpy** [comment]
可以参考知乎专栏里的一个关于vn.py事件引擎测试的文章，目前通用版的EventEngine基本就是15-25的响应延时
