### ISSUE TITLE
CtaTrading无人值守进程显示无法找到策略交易合约

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#621]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.1

## Issue类型
三选一：Question

问题：

CtaTrading无人值守进程显示无法找到策略交易合约，之前有UI界面的交易是没有问题的。

![_20171129173754](https://user-images.githubusercontent.com/30992082/33368429-a3439f2a-d52c-11e7-9b57-7e86c58b23a1.png)

**Comment by huxunya** [comment]
这个问题我发现必须要在可以连上CTP的时候启动，否则就算后来能连CTP了也不会自动运行。

**Comment by vnpy** [comment]
看了下，这里连接上CTP后都没有CTP交易服务器登录成功、查询合约成功的回报，必然找不到交易合约了

**Comment by vnpy** [comment]
检查你的帐号、服务器地址配置是否有问题吧

**Comment by huxunya** [comment]
已经解决，谢谢

**Comment by tubu** [comment]
我也遇到同样对问题了，请问@huxunya 你是怎么解决的。我的账号服务器配置是没有问题的。在DataRecording里就可以，到CtpTrading里就不行了
![3e64a243-a625-4e5a-9e8c-4b49ceb9720b](https://user-images.githubusercontent.com/973267/38537930-0cd4f386-3cc4-11e8-88ee-3c5ee8727da6.png)

**Comment by Wc30** [comment]
交易合约找不到怎么解决的
