### ISSUE TITLE
可以交易50ETF期权吗？

### ISSUE THREAD

**Issue by 4ever911** [vnpy/vnpy#622]
对应券商的服务器地址和端口从哪儿取得呢？

**Comment by vnpy** [comment]
目前vn.py支持的50ETF期权接口：
1. 中信证券vnpy.api.cshshlp
2. CTP证券柜台vnpy.api.ctp（华西期货、南华期货）
3. 飞创证券柜台vnpy.api.sec（银河期货、兴业期货）
