### ISSUE TITLE
dev分支   bar manager  x分钟线生成的时间戳的分钟应该是第一根的时间

### ISSUE THREAD

**Issue by xueshufeng** [vnpy/vnpy#624]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
0-4分钟的bar的分钟应该是0

## 实际程序行为
0-4分钟的bar的分钟是4

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
vnpy\vnpy\trader\app\ctaStrategy\ctaTemplate.py
BarManager  的updateBar
x分钟线生成的时间戳的分钟应该是第一根的时间

**Comment by vnpy** [comment]
已解决
