### ISSUE TITLE
CTP多账户持有同一合约情况下，UI持仓信息显示冲突

### ISSUE THREAD

**Issue by sun0x00** [vnpy/vnpy#626]
## 环境

* 操作系统: ALL
* Anaconda版本: ALL
* vn.py版本: 如v1.7.1

## Issue类型
Bug

## 预期程序行为
配置多个CTP接口后，所有接口持仓信息都应该显示

## 实际程序行为
部分接口持仓显示，或只显示一个接口的持仓

## 重现步骤
配置多个CTP接口对同一个合约下单后问题会重现

个人分析后认为和PositionMonitor中设置的DataKey有关系
self.setDataKey('vtPositionName')

========================
简单搜索暂未发现其他地方引用vtPositionName

因此建议修改

在ctpGateway中
```python
posName = '.'.join([data['InstrumentID'], data['PosiDirection']])
if posName in self.posDict:
    pos = self.posDict[posName]
else:
    pos = VtPositionData()
    self.posDict[posName] = pos
    pos.gatewayName = self.gatewayName
    pos.symbol = data['InstrumentID']
    pos.vtSymbol = pos.symbol
    pos.direction = posiDirectionMapReverse.get(data['PosiDirection'], '')
    pos.vtPositionName = '.'.join([pos.vtSymbol, pos.direction]) 
```
修改以下两行
1  posName = '.'.join([data['InstrumentID'], data['PosiDirection']])
修改后posName = '.'.join([self.gatewayName, data['InstrumentID'], data['PosiDirection']])

2 pos.vtPositionName = '.'.join([pos.vtSymbol, pos.direction])
修改后 pos.vtPositionName = '.'.join([pos.gatewayName, pos.vtSymbol, pos.direction])

**Comment by ruzwdy** [comment]
多账户  实现的逻辑是怎样的 。

**Comment by qmhedging** [comment]
加个 记账系统，轮询，有字段能区分不同账户即可

**Comment by vnpy** [comment]
这个根据自己的需求来改吧，因为不能算是通用需求就不增加到框架里了
