### ISSUE TITLE
IB的标的XAUUSD可以成交但是无法增加到行情订阅中

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#631]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda2-4.4.0-Windows-x86-32位
* vn.py版本: 1.71第一版

## Issue类型
三选一：Bug

## 预期程序行为
获得XAUUSD信息后，应该在订阅行情中显示。

## 实际程序行为
XAUUSD描述获得，无报错，行情订阅中无任何数据显示。发单，成交。

## 重现步骤

一、
ib连通了，XAUUSD确认获得数据成功了（因为名称里边过来了描述信息了），但是行情里边没显示订阅过来的数据，，，没办法，我直接发单，结果成交。但是行情里边仍旧不显示XAUUSD行情数据信息的，EURUSD和USDCNH都可以的，都是IB的数据，我后来认为可能是有TWS所以就不显示IB的订阅行情，但是欧元的显示，后来又查是否行情订阅显示里边限制了不显示XAUUSD这个类别的，没找到，后来想逻辑不应该有这样的限制。（补充说明：TWS能够时时看到XAUUSD的行情数据信息，5秒钟一跳，行情在TWS中没问题的）
![1](https://user-images.githubusercontent.com/31505150/33757909-25b0bec8-dc37-11e7-96df-e9777f300f2f.png)

二、
重新测试：退出vnpy，重新进入，连接ib，然后获得合约，取得了XAUUSD的名称了，错误窗口没任何信息的
![2](https://user-images.githubusercontent.com/31505150/33757919-2e22819a-dc37-11e7-94d3-095e805d2312.jpg)

三、
又发单，直接成交的了。
![3](https://user-images.githubusercontent.com/31505150/33757929-37746dd0-dc37-11e7-8a10-775b927c7dfd.jpg)

四、
输入欧元及对应的信息，回车，信息一下就出来并且在行情中显示了，这几次操作，错误窗口都没有任何信息的。
![4](https://user-images.githubusercontent.com/31505150/33757935-415b0296-dc37-11e7-849d-dc55374bf886.jpg)

五、
另外几次操作CMD也没任何报错信息的。从头到尾检查过了。
![5](https://user-images.githubusercontent.com/31505150/33757954-538cd3d6-dc37-11e7-8c75-bdba53f98e22.jpg)

附：
需要在程序中增加自定义金属，CMDTY固定
productClassMap[PRODUCT_CMDTY] = 'CMDTY'
PRODUCT_CMDTY = u'金属'

**Comment by stone3536** [comment]
群主请抽空看下这个问题，谢谢！
另外DataRecording我测试下来也是不能记录数据的。

**Comment by vnpy** [comment]
已解决

**Comment by Chen-IMC** [comment]
> 群主请抽空看下这个问题，谢谢！
> 另外DataRecording我测试下来也是不能记录数据的。

所以请问是怎么解决的？？
