### ISSUE TITLE
市场信息监控为何禁止排序了？

### ISSUE THREAD

**Issue by wisfern** [vnpy/vnpy#632]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 2.7 64位
* vn.py版本: dev branch 20171201 (dfb23ab2f486991061df1331e0015e663bbc789b)（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
市场信息监控可以按标题排序

## 实际程序行为
不能排序了

## 重现步骤
点一下市场信息监控UI的标题

针对Bug类型Issue，请提供具体重现步骤以及报错截图
uiBasicWidget.py的第457行代码
        # 设置排序
        self.setSorting(False)

**Comment by vnpy** [comment]
两个原因：
1. 发现大部分人用不到
2. 订阅数据量过大的时候，如果不点击强制排序会导致每行乱跳的情况

索性关掉了，有需求的自己打开就行
