### ISSUE TITLE
[question] 请问在ubuntu平台上的Anaconda的版本是否有要求？x64能用吗？

### ISSUE THREAD

**Issue by zjx** [vnpy/vnpy#635]
看到有多个可用的版本：

64-Bit (x86) Installer (508 MB)
64-Bit (Power8) Installer (296 MB)
32-Bit Installer (413 MB)

**Comment by sun0x00** [comment]
在linux平台可以用64-Bit的Ananconda，默认需要Anaconda2

**Comment by zjx** [comment]
thanks @sun0x00 , x64 平台测试通过！
