### ISSUE TITLE
为什么mongdb里记录的分钟行情和其它软件里的差一分钟？

### ISSUE THREAD

**Issue by davidyangan** [vnpy/vnpy#636]
## 环境

* 操作系统: 如Windows 7 
* vn.py版本: git上12/10下的最新版
## Issue类型
三选一：Bug/Enhancement/Question
Question
## 预期程序行为
打开vntrader运行examples里的策略，开启行情记录，
查看mongdb中的一分钟数据
2017-12-11 09:39:00.000Z
VnTrader_1Min_Db rb1805
open:3955.0
high:3957  
## 实际程序行为
其它交易软件显示的数据10点39分数据为
open:3953.0
high:3955
而10点四十分的数据才为mongdb里的数据  

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
有些软件用K线起始作为时间戳，有些使用结束作为时间戳

现在已经改为使用起始位的了

**Comment by davidyangan** [comment]
好的，谢谢！我再核对下
