### ISSUE TITLE
CTP接口返回float('NaN'),导致登录后程序直接崩溃

### ISSUE THREAD

**Issue by sun0x00** [vnpy/vnpy#638]
## 环境

* 操作系统: ALL
* Anaconda版本: ALL
* vn.py版本: 所有包含vtFunction.py文件带有函数safeUnicode的版本

## Issue类型
三选一：Bug

## 实际程序行为
CtpTdApi中的onErrRtnOrderInsert方法，推送了一笔特殊数据，打印数据如下

```
symbol
    cs1805
orderID
    5
direction
    空
offset
    平仓
status
    拒单
totalVolume
    8
tradedVolume
    0
orderTime

cancelTime

price
  nan
```

--------------------------------------

最初发现问题的朋友（群里的365418110）说使用过快期之后发现此问题，但是根据单号看像是vnpy发出的错误委托，因此无法判断这笔被据单委托最初的产生来源

这笔委托被推送到OrderMonitor用于展示，OrderMonitor的父类方法safeUnicode会被执行，
检查到price字段时，在vtFunction.safeUnicode方法中触发了错误

TypeError: bad operand type for abs(): 'str'

```python
def safeUnicode(value):
    """检查接口数据潜在的错误，保证转化为的字符串正确"""
    # 检查是数字接近0时会出现的浮点数上限

    if type(value) is int or type(value) is float:
        if value > MAX_NUMBER:
            value = 0

    # 检查防止小数点位过多
    if type(value) is float:
        d = decimal.Decimal(str(value))
        if abs(d.as_tuple().exponent) > MAX_DECIMAL:  # 这一行报错！！！！！
            value = round(value, ndigits=MAX_DECIMAL)

    return unicode(value)
```
实际错误来自前一步，因为此时price字段虽然是float类型，但是value却是nan，也就是值等于float('NaN'),所以没有在前一步中被重置为0,导致后续代码报错。目前没有发现float('inf')的情况，因此建议进行以下修改

```python

def safeUnicode(value):
    """检查接口数据潜在的错误，保证转化为的字符串正确"""
    # 检查是数字接近0时会出现的浮点数上限

    if type(value) is int or type(value) is float:
        # 修改这一行，增加对nan验证，inf情况暂未遇到
        if value > MAX_NUMBER or (type(value) is float and math.isnan(value)):
            value = 0

    # 检查防止小数点位过多
    if type(value) is float:
        d = decimal.Decimal(str(value))
        if abs(d.as_tuple().exponent) > MAX_DECIMAL:
            value = round(value, ndigits=MAX_DECIMAL)

    return unicode(value)


```

## 重现步骤
重现步骤很难，这个问题比较少见，修正后登录正常，委托正常显示，暂无发现其他影响
![screenshot at 2017-12-11 16-53-41](https://user-images.githubusercontent.com/4363307/33824558-c627d742-de99-11e7-89d2-9f736fd20e3d.png)

**Comment by vnpy** [comment]
非常感谢！会尽快修复

**Comment by vnpy** [comment]
已修复
