### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by zjx** [vnpy/vnpy#639]
## 环境

* 操作系统: Ubuntu 16.04.3 LTS
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 x64
* vn.py版本: v1.7.2 release

## Issue类型
三选一：Bug/Question

~/Downloads/vnpy-1.7.2/examples/VnTrader$ python run.py

Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from vnpy.event import EventEngine
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "/home/zjx/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/event/eventEngine.py", line 4, in <module>
    from queue import Queue, Empty
ImportError: No module named queue

Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

请问这个大概是什么原因？是完整按照setup步骤来的

**Comment by sun0x00** [comment]
pip install future
这是为了兼容python3做出的修改，只需要安装future模块即可修改

**Comment by zjx** [comment]
@sun0x00 ，谢谢大神，安装future模块后解决了。后来又报snappy module 找不到，从jaqs的安装wiki中找到了安装方法：
sudo apt-get install libsnappy-dev
pip install python-snappy

然后完美运行了！

**Comment by ttys000** [comment]
@zjx 纠正一下
是pip install snappy

**Comment by linshilogin** [comment]
@zjx pip install future
这是为了兼容python3做出的修改，只需要安装future模块即可修改

请问下，vnpy不是只能用python2 么，怎么还要兼容python3呢。

**Comment by vnpy** [comment]
在慢慢做一些版本兼容的升级

**Comment by liujunhui74** [comment]
我也遇到了"No module named queue"的问题，并且pip install future也不管用。
我的解决办法是修改lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/event/eventEngine.py文件，把from queue import Queue, Empty 改为 from Queue import Queue, Empty
即小写queue改为大写的Queue

**Comment by jiangsanyin** [comment]
> pip install future
> 这是为了兼容python3做出的修改，只需要安装future模块即可修改

我安装的是python2.7.12，执行此命令安装future模块后，此问题解决

**Comment by jiangsanyin** [comment]
> pip install future
> 这是为了兼容python3做出的修改，只需要安装future模块即可修改

我安装的是python2.7.12，执行此命令安装future模块后，此问题解决，感谢！~\(≧▽≦)/~ ~\(≧▽≦)/~
