### ISSUE TITLE
Ubuntu 16.04 - 64位机 - python2 or python3

### ISSUE THREAD

**Issue by iwccsbfb** [vnpy/vnpy#640]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 64位
* vn.py版本: v1.7.2 发行版

## Issue类型
三选一：Bug

## 预期程序行为
程序正常运行；

## 实际程序行为
```$ python run.py 
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from vnpy.event import EventEngine
  File "/home/arthur/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "/home/arthur/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/event/eventEngine.py", line 4, in <module>
    from queue import Queue, Empty
ImportError: No module named queue
```
当我运行`python3 run.py`的时候，程序输出为：
```$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    reload(sys)
NameError: name 'reload' is not defined
```
所以程序中即使用了python2-specific feature, 也使用了python3-specific feature.  是我安装过程有什么问题吗？

ps: 我看到系统目录中有数个`eventEngine.py`文件，有的有python3 support，有的没有。这些文件不应该相同吗？

## 重现步骤

安装的时候，我是按照这个链接进行的：https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
安装完成之后，我运行安装页的最后一步：进入vnpy/examples/VnTrader，运行：
`python run.py`
我还尝试了
`python3 run.py`

**Comment by sun0x00** [comment]
第一，默认没有兼容python3环境，需要自己进行手动调整代码
第二，在python2环境下，是否安装了future模块
pip instal future

**Comment by iwccsbfb** [comment]
@sun0x00 after `pip install future`, also needs to run `pip install snappy`, then it worked. Thank you.
