### ISSUE TITLE
实盘加载历史数据onbar函数改变syncList

### ISSUE THREAD

**Issue by Sirius083** [vnpy/vnpy#643]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v1.7.2发行版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
在实盘初始化策略阶段(onInit)，数据库中存储的策略参数会被改变
应该在策略的saveSyncData前面加一个判断，如果是实盘交易，再改变保存的参数
if self.ctaEngine.strategyDict['KAMA Strategy'].trading:
    self.saveSyncData()

**Comment by vnpy** [comment]
收到，会修改到模板里！

**Comment by vnpy** [comment]
已完成
