### ISSUE TITLE
收数据问题

### ISSUE THREAD

**Issue by MCCCSunny** [vnpy/vnpy#645]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: vn.py 1.7.2以及之前版本都有这个问题
## Issue类型：Bug
收数据的时候，每天夜盘和日盘开始前都会重启程序，但是每天收盘后的最后一分钟数据没有合成，因为只有当下一条事件推送进来的时候才会把之前的数据合成保存到数据库中。也就是缺时用夜盘最后一分钟数据和日盘最后一分钟14：59的数据

![Uploading collectdata2_q.jpg…]()

**Comment by MCCCSunny** [comment]
这个是数据库中

收到的数据
![collectdata1_q](https://user-images.githubusercontent.com/21253192/34076037-ee24c26c-e314-11e7-81c2-02a14519b554.jpg)

**Comment by KobeZhao** [comment]
郑商所是这样的，最后收盘点的tick有时候是没有的

**Comment by vnpy** [comment]
又是郑商所......

**Comment by czonghui** [comment]
每个小节最后1min，都有可能出出现上述状况。举例说明：如10.15min，最后一个tick如果没有，就要10.30第一个tick来的时候生成。实际上晚了15分钟。可能造成bar数据生成的延时，从而进一步影响交易。
建议这里做统一处理：针对每小节最后1分钟，如果有下一分钟的第一个tick（如10.14.59时刻，能收到10.15.00的tick）把结束一分钟的初始tick并到本小节前一分钟（10.15.00并到10.14.59那1分钟，11.30.00并到11.29.59 etc.）
如果收不到下一分钟的第一个tick，则直接生成当前bar，不等到下一个小节开始才生成。举例：10.14.59，如果一段时间内（如60s），收不到10.15.00的tick，直接生成，不要等到下一个小节的开始第一个tick（10.30.00），才生成。

**Comment by vnpy** [comment]
@czonghui 你说的这个60s作为终止时间的，似乎确实是最后方案了

**Comment by czonghui** [comment]
@vnpy 上述做法还有另外一个附带的好处：避免每个小节最后1个tick，单独生成1min K线。例如：10.15.00时刻的tick，刚好是上午第一小节的最后1个tick，如果并入前一分钟，会在10.14.00的1min K线当中。否则，这个tick会单独存在在10.15.00的1min K线当中，没必要而且未必合理。

**Comment by czonghui** [comment]
class BarManager(object) 当中 def updateBar(self, bar)函数当中
        if not (bar.datetime.minute + 1) % self.xmin:   # 可以用X整除
            # 生成上一X分钟K线的时间戳
            self.xminBar.datetime = self.xminBar.datetime.replace(second=0, microsecond=0)  # 将秒和微秒设为0
            self.xminBar.date = self.xminBar.datetime.strftime('%Y%m%d')
            self.xminBar.time = self.xminBar.datetime.strftime('%H:%M:%S.%f')
            
            # 推送
            self.onXminBar(self.xminBar)
            
            # 清空老K线缓存对象
            self.xminBar = None
Xbar生成算法当中，如果每个小节收盘，可以提前生成xbar。

**Comment by vnpy** [comment]
@czonghui 思考了一段如何处理这个问题，现在尚未理清的地方：
1. 对于CTA实盘交易来说，存在上一小节的最后一根K线，在下一小节开始时生成并触发交易的需求
2. 对于K线合成器来说，需要有一个时间事件来确定某一小节的结束，如果使用本地时间可能出现和交易所时间误差的问题，如果使用交易所时间对于郑商所来说又会缺乏最后一个TICK的推送

**Comment by vnpy** [comment]
现在最简洁的解决方案是不要自己去录制行情，改为使用每天固定有清洗的各家数据服务。
