### ISSUE TITLE
QuantosDataService夜盘00:00的K线时间处理出错

### ISSUE THREAD

**Issue by Jackson1107** [vnpy/vnpy#646]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Bug

## 预期程序行为
正常下载K线数据。

## 实际程序行为
下载夜盘超过0点的品种，当时间到00:00时，K线的字符串日期为"20171214 0"，转化为datetime格式时报错：ValueError: time data '20171214 0' does not match format '%Y%m%d %H%M%S'

## 重现步骤
在vnpy\examples\QuantosDataService\config.json的SYMBOLS中填入夜盘时间超过0点的品种，如沪铜。
运行vnpy\examples\QuantosDataService\downloadData.py

**Comment by vnpy** [comment]
已修复
