### ISSUE TITLE
vnpy-1.7.2/vnpy/api/okcoin/test.py websocket好像连不上

### ISSUE THREAD

**Issue by tesla1060** [vnpy/vnpy#647]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2

## Issue类型
三选一：Bug

## 预期程序行为
试图跑 vnpy/api/okcoin/test.py 

## 实际程序行为
websocket似乎总是自动关闭

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
报错输出如下

--- request header ---
GET /websocket/okcoinapi HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: real.okcoin.com:10440
Origin: http://real.okcoin.com:10440
Sec-WebSocket-Key: 9xIhsfLiDpK3jc5yKMvjxg==
Sec-WebSocket-Version: 13

-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Mon, 18 Dec 2017 13:13:04 GMT
Connection: upgrade
upgrade: websocket
sec-websocket-accept: d1gdBfHW/sggTkI3x1GqEICHjFs=
-----------------------
onOpen
send: '\x81\xd1\x83\xd8\xb9\x02\xf8\xfa\xdbk\xed\xb9\xcb{\xa1\xe2\x99v\xf1\xad\xdc.\xa3\xfa\xdct\xe6\xb6\xcd \xb9\xf8\x9bc\xe7\xbc\xfaj\xe2\xb6\xd7g\xef\xfa\x95"\xa1\xbb\xd1c\xed\xb6\xdcn\xa1\xe2\x99 \xec\xb3\xe6q\xf6\xba\xe6q\xf3\xb7\xcdw\xf0\xbc\xe6`\xf7\xbb\xe6f\xe6\xa8\xcdj\xdc\xea\x89 \xfe'
onError
Connection is already closed.
onClose

**Comment by tesla1060** [comment]
跟另外一个网上的小伙伴聊了一下，好像都连不上wss，他们收行情基本都是轮询rest api。如果是大牛，看看他们的api到底是什么问题吧，如果是我一样的小白，先不要浪费时间，直接rest轮询先吧。

**Comment by vnpy** [comment]
由于OKCOIN的交易所已经转成OKEX，该接口将停止维护
