### ISSUE TITLE
平今惩罚模式有bug

### ISSUE THREAD

**Issue by OceanMT** [vnpy/vnpy#648]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.72

## Issue类型
三选一：Bug
## 预期程序行为
平今惩罚模式,有昨仓多,再次开多提示平昨仓位不足

## 实际程序行为
平今惩罚模式,有昨仓多,再次开多提示平昨仓位不足

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![gevvrcn0h6ye_ d ct oy1i](https://user-images.githubusercontent.com/26689299/34144825-4808b12a-e4ce-11e7-9457-204bf1d3e98a.png)
![my6xpw 1byl66si pn97gx](https://user-images.githubusercontent.com/26689299/34144828-4aff8fb6-e4ce-11e7-948e-08e409edc95a.png)

req.direction is DIRECTION_LONG      指向的不是同一个id

![hd1 1o90n opw 9asu g 0c](https://user-images.githubusercontent.com/26689299/34144865-7c676876-e4ce-11e7-82db-3a572ef94f5f.png)

unicode(self.comboDirection.currentText())   原因是这句会生成不同id

**Comment by bigdig** [comment]
应当改成 == 判断

**Comment by KobeZhao** [comment]
is 是否都应该替换成==呢

**Comment by OceanMT** [comment]
明白了，只有cta策略下单才会有开平转换（不存在id不同的情况），通过窗体下单没有经过开平转换
