### ISSUE TITLE
\vnpy-1.7.2\examples\CtaBacktesting 中的例子运行报错

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#649]
vn.py  下载后 。Windows：双击运行install.bat自动安装  安装了。

结果：：：

用spyder 运行\vnpy-1.7.2\examples\CtaBacktesting    下的runBacktesting.py。直接报很多错误
No module named chinese
print str(datetime.now()) + "\t" + content    SyntaxError: invalid syntax

自带的示例都直接报错。

请问下是为什么哇？

**Comment by vnpy** [comment]
请不要用spyder运行，直接去目录下用python运行

**Comment by linshilogin** [comment]
你好。请问下是用命令行运行么。那 想用ide调试 python程序 是不是在vnpy中实现不了啊

**Comment by linshilogin** [comment]
@vnpy

**Comment by vnpy** [comment]
可以用pycharm、wingide这类项目开发用的IDE来跑，不建议用Spyder这种做交互式开发的IDE来做
