### ISSUE TITLE
对接某些资管系统

### ISSUE THREAD

**Issue by KobeZhao** [vnpy/vnpy#651]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2

## Issue类型
三选一：Question

## 预期程序行为

有没有考虑过对接一些资管系统，比如接了笔资金，但要通过博易的资管子账户登陆交易。

**Comment by vnpy** [comment]
社区里有人开发过O32、金牛、融航的对接版本，如果某个系统的需求特别大，我也会来做开发

**Comment by qmhedging** [comment]
我认识 博易大师的资管系统开发人员，如果有需要可以联系，技术问题可以讨论。欢迎联系 手机15000906614.
