### ISSUE TITLE
ImportError: No module named vnxtpquote for win7 32

### ISSUE THREAD

**Issue by ykrank** [vnpy/vnpy#653]
## 环境

* 操作系统: Windows 7 32bit
* Anaconda版本: 如Anaconda2 5.0.1 Python 2.7 32位
* vn.py版本: dev branch 20171221（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
打开示例窗口

## 实际程序行为
命令行报错

## 重现步骤
正常的安装了全套工具，在最后测试的时候报错
`
Y:\py\vnpy\examples\VnTrader>python run.py
C:\ProgramData\Anaconda2\lib\site-packages\vnpy\api\ib\__init__.py:3: RuntimeWar
ning: to-Python converter for class std::vector<class ibapi::shared_ptr<class Or
derCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition>
 > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\gateway\xtpGatewa
y\__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\gateway\xtpGatewa
y\xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\api\xtp\__init__.py", li
ne 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote
`

**Comment by vnpy** [comment]
在run.py里把加载xtpGateway的代码去掉试试

**Comment by vnpy** [comment]
在run.py里把加载xtpGateway的代码去掉试试

**Comment by ykrank** [comment]
去掉xtpGateway可以正常打开了

**Comment by vnpy** [comment]
dev的xtpGateway还没全部弄好，后续会继续开发
