### ISSUE TITLE
银河期货飞创50期权接口记录数据DataRecording报错

### ISSUE THREAD

**Issue by abchuman77** [vnpy/vnpy#654]
## 环境
我在进行DataRecording时报错，连接飞创期权接口 

![jietu](https://user-images.githubusercontent.com/34763002/34287404-db750f08-e721-11e7-8c05-1a69a485c344.png)
![qq 20171222140656](https://user-images.githubusercontent.com/34763002/34287405-dbadb4ca-e721-11e7-892b-e170afab55e4.jpg)
![qq 20171222140724](https://user-images.githubusercontent.com/34763002/34287406-dbe455a2-e721-11e7-99ee-c5a132db8191.png)
![qq 20171222140741](https://user-images.githubusercontent.com/34763002/34287407-dc1c498a-e721-11e7-8397-4b9d30881e59.jpg)

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
针对股票类接口，DataRecorder的配置文件请使用每行请使用三个内容，分别是
symbol, gatwayName, exchange

所以用：
"10001029","SEC","SSE"
