### ISSUE TITLE
vnpy的按照是否可以 用虚拟环境来安装

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#655]
我看了官网提供的安装方法。

但是我现在已经有了其他版本的anaconda

请问下我是否可以通过conda -n 新建一个虚拟环境，然后在虚拟 环境中 安装 vnpy官网提供的那些环境。如果可以的话，要怎么修改呢。

**Comment by vnpy** [comment]
除非你自己已经是高手，否则不建议折腾
