### ISSUE TITLE
CTP触发tdpenalty一直发反手单

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#656]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3.6 64位
* vn.py版本: 1.7.2

## Issue类型
三选一：Bug

## 预期程序行为
螺纹多开触发锁仓后应该只发一次反手空单，结果一直发空开单，程序重启之后又恢复正常了。

## 实际程序行为
群里问了下也有别人遇到过这个问题，看来是偶发性BUG

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
simnow环境还是实盘环境？

simnow环境中，有时会出现数据回报的小错误，导致仓位管理出现问题，重启后恢复正常更可能是这个原因了
