### ISSUE TITLE
1.7.2版本下用默认参数的进行多进程优化结果显示全部为0

### ISSUE THREAD

**Issue by q6218271** [vnpy/vnpy#657]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本:  v1.7.2

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

运行默认多进程优化参数，以策略的最终净盈利排序

## 实际程序行为
全部结果为0

## 重现步骤

在多进程优化参数时，1.7.2版本ctaBacktesting引擎第1267、1268行修改为了calculateDailyStatistics函数，里面已经没有capital字段，所以以默认参数运行runOptimization.py时结果都是0。

应该修改优化目标setOptimizeTarget('capital')中的'capital'为calculateDailyStatistics输出中的'totalNetPnl'，或其他优化目标，或者把ctaBacktesting引擎第1267、1268行改回跟单核优化时一样的d = self.calculateBacktestingResult()
，当然最好还是不要修改引擎。。。

**Comment by xldistance** [comment]
用endBalance
