### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by water321** [vnpy/vnpy#658]
## 环境

* 操作系统: Windows 7或者Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.1发行版

## Issue类型
Question

## 预期程序行为
正常启动

## 实际程序行为
ImportError: No module named builtins

## 重现步骤
执行vnpy/example/vnTrader/run.py时出错

**Comment by vnpy** [comment]
pip install future

**Comment by water321** [comment]
谢谢
