### ISSUE TITLE
No Qt bindings could be found

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#659]
## 环境

* 操作系统: 如Windows 8
* Anaconda版本: 如利用anaconda创建的虚拟环境  Python 2.7 32位
* vn.py版本: 如v1.7.2

## Issue类型
三选一：Question

## 重现步骤

运行run.py 或者运行 runBacktesting.py  都会出现以下问题

from qtpy.QtCore import QTimer
  File "D:\common\Anaconda3.4\envs\vnpyEnv\lib\site-packages\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

关键我已经安装了pyqt 5.6 啊。

实在找不出为什么了？

**Comment by vnpy** [comment]
请使用Anaconda 4.0.0 Python 2.7

**Comment by linshilogin** [comment]
@vnpy  你好。Anaconda 4.0.0 Python 2.7 32位  如何与  其他anaconda版本并存 很存在问题。请问下，是否有成功的案例。

**Comment by vnpy** [comment]
不建议采用并存的方案，如果有需要可以用多个虚拟机，然后基于socket通讯交换信息
