### ISSUE TITLE
资金不足时，风控在开仓时没有触发，平仓触发了

### ISSUE THREAD

**Issue by Wendyfei** [vnpy/vnpy#660]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
在实际保证金占比超过风控设置占比时，限制策略开仓

## 实际程序行为
在保证金占比超过风控时，策略正常发单成交，没有触发风控，开仓后时间可用资金已经为负，于是手动平仓，此时触发了风控，不能正常平仓

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已完成
