### ISSUE TITLE
提出需求

### ISSUE THREAD

**Issue by yycyyyc321** [vnpy/vnpy#662]
例如现在RB主力合约是1805，我的策略A现在要运行在主力合约上，我的数据库里面有RB的主力合约行情数据，这个数据叫做RBM0，现在我希望我在CTA引擎初始化我的策略A的时候，数据用到我的RBM0的数据，而不是我数据库的rb1705合约的数据（因为rb1705的数据不够长，不能满足我初始化的需求，而且有主力合约变更的问题），如何做到这一点？
我现在想到的一个方法就是把数据从主力合约行情那里复制到现在的例如rb1805合约数据库里面去。

vnpy可以考虑做一个映射，例如我的策略是针对主力合约开发的，现在rb1805是主力合约，初始话onInit的时候，加载数据库rb0000的数据，我订阅这个rb1805合约之后，数据自动放入rb0000数据库里面

**Comment by KobeZhao** [comment]
实盘的话，分两种，一是低频日级别的要自己做指数复权，第二种分钟级的话，都是直接按交易代码取数据，数据不够长的话不做交易，主观做交易，你也不会只看主力连续合约去做吧

**Comment by likenji** [comment]
我印象记录数据是有数据映射的，你可以翻翻dataRecoding模块

**Comment by vnpy** [comment]
DataRecorder已经提供主力合约行情映射功能
