### ISSUE TITLE
下午收盘后，日志隔一段时间会提示“交易服务器连接成功”，然后立马又提示“交易服务器连接断开”，是什么原因呢？

### ISSUE THREAD

**Issue by water321** [vnpy/vnpy#663]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2发行版

## Issue类型
Question

**Comment by xldistance** [comment]
收盘后断开连接，程序会一直尝试重连......
