### ISSUE TITLE
修改loadSyncData的时间

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#664]
## 环境

* 操作系统: 任意
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Enhancement

## 预期程序行为

策略对象加载历史数据回放，完成策略变量初始化后，才读取数据库保存的同步数据

## 实际程序行为

策略对象创建后，立即读取了同步数据，在后续历史数据回放的过程中可能被修改导致异常

**Comment by KobeZhao** [comment]
这个是要改的，我自己是把策略加载后的那个同步数据的删掉，改为初始化后再同步。

**Comment by KobeZhao** [comment]
正确顺序应该是，历史数据回放完之后再同步数据吧

**Comment by vnpy** [comment]
对的

**Comment by vnpy** [comment]
已完成
