### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#665]
File "D:\common\Anaconda3.4\envs\test\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 688, in calculateBacktestingResult
    endPrice = self.bar.close
AttributeError: 'NoneType' object has no attribute 'close'

请问下，这是没有数据么。vnpy的例子中，没有自带数据么？

**Comment by vnpy** [comment]
1. 出现这个报错，是因为回测时没有从数据库中加载到足够的数据
2. 在examples/CtaBacktesting下，有个loadCsv.py，运行它将项目自带的测试数据插入到mongodb数据库里

**Comment by Henry-PY** [comment]
@vnpy .
3x
