### ISSUE TITLE
建议回测添加支持多进程回测

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#666]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3 64位
* vn.py版本: 如v1.7.2

## Issue类型
三选一：Enhancement

## 预期程序行为
有的策略需要大量计算，回测时只有一个进程在跑CPU使用率很低

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
回测这项业务存在严重的时间序列依赖特征，也就是说在第N天的你的交易行为很可能是和之前的N-1天中发生的事情相关的，这样的情况下如果拆分成多段数据，跑多进程回测，就无法保证数据的完整性，导致回测出错了

**Comment by stabledistribution** [comment]
那么对一个品种(vtSymbol)应用多个策略回撤呢？一个品种分一个核

**Comment by ssh352** [comment]
不建议添加这种非核心功能
