### ISSUE TITLE
ctaHistroyData.py  文件跑到哪里去了

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#668]
回测文档中有这么一段

`设置回测引擎的相关参数(回测模式，回测起始日期，数据库)。历史数据得预先存储在MongoDB中，若没有， 则可执行vnpy/vn.trader/ctaAlgo/ctaHistroyData.py里的代码，把回测数据插入到数据库中， 如下`

可是我愣是没找到ctaHistroyData.py 

我用的1.7.2版本的vnpy

**Comment by xldistance** [comment]
C:\ProgramData\Anaconda3\Lib\site-packages\vnpy-1.7.2-py3.6.egg\vnpy\trader\app\ctaStrategy里面

**Comment by linshilogin** [comment]
@xldistance  请问下，您提供的这个目录看着像安装目录哇。为什么在github的项目中找不到这个文件呢

**Comment by linshilogin** [comment]
@xldistance  我安装路径也没找到你个文件。而且，你这个路径看着像是python3.6版本，可是vnpy不是只能在2.7的python环境下么。

**Comment by likenji** [comment]
Histroy->History
