### ISSUE TITLE
盘前数据过滤问题

### ISSUE THREAD

**Issue by KobeZhao** [vnpy/vnpy#670]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2发行版

## Issue类型
三选一：Bug

## 预期程序行为

行情接收夜盘是从20:59开始，但是有些品种在开盘前会推送非交易时间或者无效tick
## 实际程序行为

盘前的数据未经过清洗，虽然历史数据可以通过其他数据源加载，但是无效数据也会进入策略中，数据差异过大将导致策略信号失真。
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![default](https://user-images.githubusercontent.com/17927525/34487731-3b0894c2-ef9b-11e7-9fda-214e7f84e5bc.PNG)

建议还是在tick接收过来时，先清洗一下，过滤掉无效或非交易时间tick。另外，针对集合竞价20:59的数据，其实好多软件是合并到21:00的k线里，当然wind的行情是20:59独立出来的，但是考虑到20:59的k线并没什么作用，故建议同时20:59合并入21:00的k线

还有一点疑问是，vnpy的k线是按分钟前的时间戳，但是k线的close就会比tick的lastprice晚了一个tick，如果策略是按close去报单，但这个时候的lastprice实际上已经变了啊。我的想法是按最新的last price去定义k线的close，才能保证close的及时性。

**Comment by vnpy** [comment]
过滤是个比较麻烦的问题，因为vn.py除了国内CTP外还应用在很多其他市场，所以把过滤规则直接写在上层功能代码里肯定不合适

**Comment by KobeZhao** [comment]
这倒是的，可以在ctpgateway里写好过滤吧，这样就不会影响其他接口了

**Comment by xldistance** [comment]
runCTADataRecording里面过滤加上夜盘前定时数据清理不就行了

**Comment by KobeZhao** [comment]
DataRecording是可以定时清理掉，但是策略里也会接收数据的吧，接收到这种19:32的数据，加到k线里，我觉得是不太妥。所以索性一步到位，在gateway里就直接清理掉。

**Comment by likenji** [comment]
看来我用的方法比较笨，我是在策略里面处理异常数据的

**Comment by KobeZhao** [comment]
笨方法写了一下
`"""增加tick行情过滤"""
        dt = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 时间戳
        # 默认为非交易时间
        TradeTime = False
        # 这里以商品期货为例
        MORNING_START = datetime(1991,1,1,8,59).time()
        MORNING_REST = datetime(1991,1,1,10,15).time()
        MORNING_RESTART = datetime(1991,1,1,10,30).time()
        MORNING_END = datetime(1991,1,1,11,30).time()
        AFTERNOON_START = datetime(1991,1,1,13,30).time()
        AFTERNOON_END = datetime(1991,1,1,15,0).time()
        NIGHT_START = datetime(1991,1,1,20,59).time()    # 为了包含集合竞价
        NIGHT_END = datetime(1991,1,1,2,30).time()
        # 在交易时间内
        if ((MORNING_START <= dt < MORNING_REST) or
            (MORNING_RESTART <= dt < MORNING_END) or
            (AFTERNOON_START <= dt < AFTERNOON_END) or
            (dt >= NIGHT_START) or
            (dt < NIGHT_END)):
            TradeTime = True
        # 如果为非交易时间则直接返回
        # TODO:暂时未考虑中金所品种的交易时间过滤
        if not TradeTime and tick.exchange is not EXCHANGE_CFFEX:
            return`

**Comment by szsa** [comment]
vnpy不仅仅针对ctp，所以自己用什么，自己处理一下就可以了，很简单，就是想仔细些就能解决
