### ISSUE TITLE
ctaBacktesting.py 变量未定义引用

### ISSUE THREAD

**Issue by stabledistribution** [vnpy/vnpy#672]
## 环境

Ubuntu 16.04

## Issue类型
三选一：Bug

## 重现步骤

vnpy/trader/app/ctaStrategy/ctaBacktesting.py

line 953:

resultDict = {k:[] for k in dailyResult.__dict__.keys()}

dailyResult 没有定义报错，resultDict应该是空集合吧。

我自己python -m * *

报错： API 'QString' has already been set to version 1，不知道怎么编译了

**Comment by vnpy** [comment]
API 'QString' has already been set to version 1
出现这句的原因，应该是你用来运行ctaBacktesting的环境中加载了PyQt，猜测是用了Spyder？
直接在terminal里运行就不会有这个报错了。

另外dailyResult的没有定义报错，因为你的回测数据不足，没有生成哪怕1笔交易，就会报错了
