### ISSUE TITLE
希望项目能够增加对于Python3的支持

### ISSUE THREAD

**Issue by pl1612127** [vnpy/vnpy#674]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
支持Python3

## 实际程序行为
只支持Python2

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
预计在2019年初3.0推出的时候支持
