### ISSUE TITLE
该写开发日志2018年项目计划了

### ISSUE THREAD

**Issue by pl1612127** [vnpy/vnpy#675]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
有开发日志2018年项目计划

## 实际程序行为
无开发日志2018年项目计划

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
哈哈哈，好的，我尽快在春节前写

**Comment by huxunya** [comment]
顺手就把价差交易的策略模板写了呗

**Comment by vnpy** [comment]
已完成
