### ISSUE TITLE
改为在初始化策略时再订阅行情

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#678]
## 环境
 vn.py版本: 1.7.2

## Issue类型
Enhancement

当前的程序在加载策略时，就自动订阅每个setting的行情，导致的问题是：
如果配置了3个setting，对应不同的品种，但是我只想跑其中一个，不想跑另外2个，而程序自动订阅了3个品种的行情，那其余我不跑的2个，其实就是多余的。
建议修改为在init时再订阅行情，这样如果我只要跑一个，那就只会订阅一个行情，不会多余

**Comment by vnpy** [comment]
已完成
