### ISSUE TITLE
请问下，vnpy中 期货回测 有自动拼接成主力连续的数据么

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#679]
如题。好多平台，提供了各个合约的数据，可是要回测的时候，需要在主力连续上回测。请问下vnpy中，是否能够主力连续上回测。

**Comment by vnpy** [comment]
vn.py是另一个思路，你可以选择将策略在所有主力合约上跑回测，然后拼接起来得到最终的盈亏曲线。

这个方法比拼接行情数据后再回测，可以彻底规避掉换月跳空导致的不准确问题。

**Comment by linshilogin** [comment]
@vnpy 你好。这个“将策略在所有主力合约上跑回测，然后拼接起来得到最终的盈亏曲线”  的过程，vnpy是已经有了模块来拼接，还是需要用户自己来自定义拼接方式呢？

**Comment by vnpy** [comment]
参考CtaBacktesting下的组合回测功能，拼接就是自己把每段回测好得到的DataFrame加起来就行了，很傻瓜

**Comment by linshilogin** [comment]
@vnpy  你好。“vn.py是另一个思路，你可以选择将策略在所有主力合约上跑回测”  这段话，也不是很好实现。比如，我要在过去3年的 czce.zc 上回测，那么 就拿到一个这么一个时间段和品种，如何去定  具体在zc的那些合约上 运行呢。

**Comment by vnpy** [comment]
1. 了解该品种的主力合约切换规律
2. 定义好3年时间里，每段时间回测要用的合约是具体哪个
3. 运行回测

**Comment by luckyxinshidai** [comment]
(⊙o⊙)…，这种方法好傻啊。。。为什么不能整个主力合约与真实合约的对照关系的这种逻辑呢？
