### ISSUE TITLE
数据库中的rawdata是什么

### ISSUE THREAD

**Issue by KobeZhao** [vnpy/vnpy#680]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2发行版

## Issue类型
三选一：Question

## 预期程序行为
数据库中无rawdata出现

## 实际程序行为
数据库中值均为null的rawData是什么，记得之前版本中没有出现过的。这个空值是不是导致插入数据重复报错的原因呢。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
查看数据库

**Comment by vnpy** [comment]
rawData是针对某些用户自行对接的交易接口，如果有特殊的字段是vtObject中的数据类所不支持的，可以直接将原始数据通过rawData传送给上层应用部分，省去修改中间引擎层的工作
