### ISSUE TITLE
vtEngine  positionDetail初始化有问题

### ISSUE THREAD

**Issue by xueshufeng** [vnpy/vnpy#682]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
当程序启动的时候有委托或者交易推送的时候，这个时候调用getPositionDetail初始化，如果这个时候contract还没获取到， PositionDetail初始化就会有问题。如果是rb，mode就不是shfe，平仓的时候区分不了平昨还是平今

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
每次VnTrader关闭时，会把系统内已有的合约信息落地到硬盘上；下次启动时会立即加载。也就是当用户连接接口前系统内就已经有了相关的配置信息，这个设计就是为了避免上述出现的情况。

理论上只有当你第一次使用VnTrader，且还是在其他客户端已经做了一堆交易后，盘中再启动VnTrader连接CTP的情况下，才可能出现上述错误，我的建议是不要这么操作...

**Comment by xueshufeng** [comment]
恩。 我是无界面跑的，可能与停止程序方式有关系，界面关闭的时候会落盘， 命令行跑都是杀进程的。 不过可以写一个无界面的停止代码，停止前做一些保存。

**Comment by vnpy** [comment]
恩恩，自己加下吧
