### ISSUE TITLE
okexGateway.py 文件中 okex_all_symbol_pairs 变量没定有定义

### ISSUE THREAD

**Issue by bigdig** [vnpy/vnpy#683]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
加上去
okex_all_symbol_pairs = ["eth_btc","ltc_btc","etc_btc","bch_btc","xrp_btc","xem_btc","xlm_btc",
                        "iota_btc","1st_btc","aac_btc","ace_btc","act_btc","aam_btc","ark_btc","ast_btc","avt_btc","bcd_btc",
                        "bnt_btc","btg_btc","btm_btc","cag_btc","cmt_btc","ctr_btc","cvc_btc","dash_btc","dat_btc","dgb_btc",
                        "dgd_btc","dna_btc","dnt_btc","dpy_btc","edo_btc","elf_btc","eng_btc","eos_btc","evx_btc","fair_btc",
                        "fun_btc","gas_btc","gnt_btc","gnx_btc","hsr_btc","icn_btc","icx_btc","itc_btc","kcash_btc","knc_btc",
                        "lend_btc","link_btc","lrc_btc","mag_btc","mana_btc","mco_btc","mda_btc","mdt_btc","mot_btc","mth_btc",
                        "mtl_btc","nas_btc","neo_btc","nuls_btc","oax_btc","omg_btc","pay_btc","ppt_btc","pro_btc","qtum_btc",
                        "qvt_btc","rcn_btc","rct_btc","rdn_btc","read_btc","req_btc","rnt_btc","salt_btc","san_btc","show_btc",
                        "smt_btc","sngls_btc","snm_btc","snt_btc","ssc_btc","storj_btc","sub_btc","swftc_btc","tnb_btc",
                        "trx_btc","ubtc_btc","ugc_btc","ukg_btc","utk_btc","vee_btc","vib_btc","wrc_btc","wtc_btc","xmr_btc",
                        "xuc_btc","yoyo_btc","zec_btc","zrx_btc",\
                        "btc_usdt","eth_usdt","ltc_usdt","etc_usdt","bch_usdt","xrp_usdt","xem_usdt","xlm_usdt",
                        "iota_usdt","1st_usdt","aac_usdt","ace_usdt","act_usdt","aam_usdt","ark_usdt","ast_usdt","avt_usdt","bcd_usdt",
                        "bnt_usdt","btg_usdt","btm_usdt","cag_usdt","cmt_usdt","ctr_usdt","cvc_usdt","dash_usdt","dat_usdt","dgb_usdt",
                        "dgd_usdt","dna_usdt","dnt_usdt","dpy_usdt","edo_usdt","elf_usdt","eng_usdt","eos_usdt","evx_usdt","fair_usdt",
                        "fun_usdt","gas_usdt","gnt_usdt","gnx_usdt","hsr_usdt","icn_usdt","icx_usdt","itc_usdt","kcash_usdt","knc_usdt",
                        "lend_usdt","link_usdt","lrc_usdt","mag_usdt","mana_usdt","mco_usdt","mda_usdt","mdt_usdt","mot_usdt","mth_usdt",
                        "mtl_usdt","nas_usdt","neo_usdt","nuls_usdt","oax_usdt","omg_usdt","pay_usdt","ppt_usdt","pro_usdt","qtum_usdt",
                        "qvt_usdt","rcn_usdt","rct_usdt","rdn_usdt","read_usdt","req_usdt","rnt_usdt","salt_usdt","san_usdt","show_usdt",
                        "smt_usdt","sngls_usdt","snm_usdt","snt_usdt","ssc_usdt","storj_usdt","sub_usdt","swftc_usdt","tnb_usdt",
                        "trx_usdt","ubtc_usdt","ugc_usdt","ukg_usdt","utk_usdt","vee_usdt","vib_usdt","wrc_usdt","wtc_usdt","xmr_usdt",
                        "xuc_usdt","yoyo_usdt","zec_usdt","zrx_usdt"]

**Comment by xldistance** [comment]
更新一波

**Comment by xldistance** [comment]
okex_all_symbol_pairs = ['ref_usdt', 'soc_usdt', 'light_usdt', 'avt_usdt', 'of_usdt', 'brd_usdt', 'ast_usdt', 'int_usdt', 'zrx_usdt', 'ctr_usdt', 'dgd_usdt', 'aidoc_usdt', 'wtc_usdt', 'swftc_usdt', 'wrc_usdt', 'sub_usdt', 'dna_usdt', 'knc_usdt', 'kcash_usdt', 'mdt_usdt', 'theta_usdt', 'ppt_usdt', 'utk_usdt', 'qvt_usdt', 'salt_usdt', 'la_usdt', 'itc_usdt', 'fair_usdt', 'yee_usdt', '1st_usdt', 'fun_usdt', 'iost_usdt', 'mkr_usdt', 'tio_usdt', 'req_usdt', 'ubtc_usdt', 'icx_usdt', 'tct_usdt', 'san_usdt', 'lrc_usdt', 'icn_usdt', 'cvc_usdt', 'eth_usdt', 'poe_usdt', 'xlm_usdt', 'iota_usdt', 'eos_usdt', 'nuls_usdt', 'mot_usdt', 'neo_usdt', 'gnx_usdt', 'dgb_usdt', 'evx_usdt', 'ltc_usdt', 'mda_usdt', 'etc_usdt', 'dpy_usdt', 'tnb_usdt', 'nas_usdt', 'btc_usdt', 'smt_usdt', 'ssc_usdt', 'oax_usdt', 'yoyo_usdt', 'snc_usdt', 'sngls_usdt', 'bch_usdt', 'mana_usdt', 'mof_usdt', 'mco_usdt', 'vib_usdt', 'topc_usdt', 'pra_usdt', 'bnt_usdt', 'xmr_usdt', 'edo_usdt', 'snt_usdt', 'eng_usdt', 'stc_usdt', 'qtum_usdt', 'key_usdt', 'ins_usdt', 'rnt_usdt', 'bcd_usdt', 'amm_usdt', 'lend_usdt', 'btm_usdt', 'elf_usdt', 'xuc_usdt', 'cag_usdt', 'snm_usdt', 'act_usdt', 'dash_usdt', 'zec_usdt', 'storj_usdt', 'pay_usdt', 'vee_usdt', 'show_usdt', 'trx_usdt', 'atl_usdt', 'ark_usdt', 'ost_usdt', 'gnt_usdt', 'dat_usdt', 'rcn_usdt', 'qun_usdt', 'mth_usdt', 'rct_usdt', 'read_usdt', 'gas_usdt', 'btg_usdt', 'mtl_usdt', 'cmt_usdt', 'xrp_usdt', 'spf_usdt', 'aac_usdt', 'can_usdt', 'omg_usdt', 'hsr_usdt', 'link_usdt', 'dnt_usdt', 'true_usdt', 'ukg_usdt', 'xem_usdt', 'ngc_usdt', 'lev_usdt', 'rdn_usdt', 'ace_usdt', 'ipc_usdt', 'ugc_usdt', 'viu_usdt', 'mag_usdt', 'hot_usdt', 'pst_usdt',\
 'ref_btc', 'soc_btc', 'light_btc', 'avt_btc', 'of_btc', 'brd_btc', 'ast_btc', 'int_btc', 'zrx_btc', 'ctr_btc', 'dgd_btc', 'aidoc_btc', 'wtc_btc', 'swftc_btc', 'wrc_btc', 'sub_btc', 'dna_btc', 'knc_btc', 'kcash_btc', 'mdt_btc', 'theta_btc', 'ppt_btc', 'utk_btc', 'qvt_btc', 'salt_btc', 'la_btc', 'itc_btc', 'fair_btc', 'yee_btc', '1st_btc', 'fun_btc', 'iost_btc', 'mkr_btc', 'tio_btc', 'req_btc', 'ubtc_btc', 'icx_btc', 'tct_btc', 'san_btc', 'lrc_btc', 'icn_btc', 'cvc_btc', 'eth_btc', 'poe_btc', 'xlm_btc', 'iota_btc', 'eos_btc', 'nuls_btc', 'mot_btc', 'neo_btc', 'gnx_btc', 'dgb_btc', 'evx_btc', 'ltc_btc', 'mda_btc', 'etc_btc', 'dpy_btc', 'tnb_btc', 'nas_btc', 'btc_btc', 'smt_btc', 'ssc_btc', 'oax_btc', 'yoyo_btc', 'snc_btc', 'sngls_btc', 'bch_btc', 'mana_btc', 'mof_btc', 'mco_btc', 'vib_btc', 'topc_btc', 'pra_btc', 'bnt_btc', 'xmr_btc', 'edo_btc', 'snt_btc', 'eng_btc', 'stc_btc', 'qtum_btc', 'key_btc', 'ins_btc', 'rnt_btc', 'bcd_btc', 'amm_btc', 'lend_btc', 'btm_btc', 'elf_btc', 'xuc_btc', 'cag_btc', 'snm_btc', 'act_btc', 'dash_btc', 'zec_btc', 'storj_btc', 'pay_btc', 'vee_btc', 'show_btc', 'trx_btc', 'atl_btc', 'ark_btc', 'ost_btc', 'gnt_btc', 'dat_btc', 'rcn_btc', 'qun_btc', 'mth_btc', 'rct_btc', 'read_btc', 'gas_btc', 'btg_btc', 'mtl_btc', 'cmt_btc', 'xrp_btc', 'spf_btc', 'aac_btc', 'can_btc', 'omg_btc', 'hsr_btc', 'link_btc', 'dnt_btc', 'true_btc', 'ukg_btc', 'xem_btc', 'ngc_btc', 'lev_btc', 'rdn_btc', 'ace_btc', 'ipc_btc', 'ugc_btc', 'viu_btc', 'mag_btc', 'hot_btc', 'pst_btc']

**Comment by vnpy** [comment]
现在有这么多货币对？！有办法通过接口自动获得么？

**Comment by vnpy** [comment]
已修改
