### ISSUE TITLE
能否增加dukascopy银行的gateway

### ISSUE THREAD

**Issue by zzniwei** [vnpy/vnpy#684]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: V1.X ???

## Issue类型
Enhancement

## 预期程序行为
能够和dukascopy银行的FIX API server完成对接，客户可以在vnpy上进行外汇，差价合约，贵金属的
交易活动，建议采用quickfix开源库加快开发进度

## 实际程序行为
无

## 重现步骤
无

**Comment by vnpy** [comment]
之前邮件联系过dukascopy那边申请开发环境，没有给我任何回复，如果能提供的话我可以来安排开发。

**Comment by zzniwei** [comment]
我得到的回复是要开户，看来只能自己玩了

Hello experts, 
As attached document mentioned , if we want to connect Dukascopy FIX API server , we must obtain below information from Dukascopy , would please share 
Me the way how to obtain connection information to Dukascopy FIX API server ? thanks!
 
------------
In order to connect to Dukascopy FIX API server, user must obtain from Dukascopy:
• TargetCompId
• two SenderCompId
• username
• password
------------



Hello,

First you need to create a regular trading account with Dukascopy and send the request for FIX connection to our support e-mail, specifying account details and environment (LIVE or DEMO). For LIVE account you will also have to sign a special agreement, your account manager will provide you with more information on that. After we set up the requested account for a FIX connection and send you mentioned details.

Kind regards,
Dmitrijs Bosnaks

**Comment by vnpy** [comment]
那确实就没办法了
