### ISSUE TITLE
可以增加OKEX期货接口吗?

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#686]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3 64位
* vn.py版本: v1.7.2发行版

## Issue类型
三选一：Enhancement

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前没时间来开发这个接口，社区有人贡献的话我很乐意合并进去

**Comment by xldistance** [comment]
群里有个OKEX期货接口但是持仓不能推送到数据库，群主看下能修复吗

**Comment by vnpy** [comment]
1.8没时间做了，1.9来看下吧

**Comment by xldistance** [comment]
群里已经有大佬修复完BUG了
