### ISSUE TITLE
安装完毕后提示  ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by Bin13** [vnpy/vnpy#689]
安装vnpy的成功后，运行examples中VnTrader中的run.py，提示如下错误:
 ImportError: No module named vnctpmd

## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.4.7 Python 2.7 64位
* vn.py版本: dev branch master（下载日期）

## Issue类型
Question

## 实际程序行为
提示： ImportError: No module named vnctpmd

我在api/ctp下面的已经编译好了vnctpmd.so   vnctptd.so这两个库，不知道为何还是不能运行。想问一下。
本人第一次接触这个，希望大家给指导指导，谢谢。

**Comment by vnpy** [comment]
用bash build.sh就可以自动编译安装了

**Comment by Bin13** [comment]
我是用 bash install.sh安装的。安装已经完毕了，但是就是找不到那个模块。所以现在比较好奇。有其他可以沟通的渠道吗，QQ群我现在加不进去了。想通过群或者其他方式详细沟通下。

**Comment by xldistance** [comment]
pip list看看vnpy有没有安装成功

**Comment by Bin13** [comment]
应该是安装成功了，我给你贴个图片看下。 @xldistance 
![76a32f833848808a4b1cafea3](https://user-images.githubusercontent.com/20624472/34977009-edec1fb2-fad3-11e7-87d8-5ceded38e3fa.png)

**Comment by vnpy** [comment]
先编译API，进入vnpy/api/ctp目录，运行bash build.sh，然后把build目录下新生成的vnctpmd.so和vnctptd.so复制到vnpy/api/ctp目录下，覆盖原有的两个so。（我估计你是这步自动编译失败了，所以才没有新的.so）

再回到vnpy根目录，运行bash build.sh安装vn.py。

**Comment by Bin13** [comment]
问题最后解决了，我换了1.7版本的代码，然后提示我如下错误：
ImportError: /home/unix/anaconda2/lib/python2.7/site-packages/
PyQt5/../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not
found (required by /home/unix/anaconda2/lib/python2.7/sitepackages/
vnpy-1.7.0-py2.7.egg/vnpy/api/ctp/vnctpmd.so)
然后我查阅了其他相关的链接，让我安装 libgcc 这个，安装完毕后问题解决了。
用的conda的安装方式。  conda install libgcc

**Comment by Bin13** [comment]
非常感谢 @vnpy ，我打算再用你的这个方式安装一遍，看下到底是哪一步出现了问题。目前出现此问题的方式我还没有完全弄清楚，我不知道是否是由于缺少了libgcc 这个导致1.7.2的安装过程失败。等我安装完毕确认没有问题后我再来补充此问题。希望以后的小伙伴不会再遇到此类问题而困扰。

**Comment by jiagengliu** [comment]
我也遇到完全一样的问题， build并copy两个.so之后问题还是那样。这里附上了安装时的报告。
[vnpy.txt](https://github.com/vnpy/vnpy/files/1645898/vnpy.txt)

**Comment by JaysonAlbert** [comment]
@jiagengliu 我安装时也遇到了， 然后先使用sudo updatedb更新文件数据库，然后使用locate命令找到那个so文件，复制到相应位置就可以了

**Comment by jiagengliu** [comment]
@JaysonAlbert 十分感谢，不过按照您的步骤，似乎还是不行，能否上传一个 bash script 帮助解决这个问题？

**Comment by tomtsang** [comment]
版本: vnpy-1.7.3
我也遇到了同样的问题....按 @vnpy 的方法, 也未解决...
难道, 没有其它人解决了这个问题, 不可思议!!!!

**Comment by tomtsang** [comment]
建议这个 issue 重新 open!

**Comment by JaysonAlbert** [comment]
![image](https://user-images.githubusercontent.com/6207775/35253130-c4217d62-001e-11e8-9b5d-f730e7fa357e.png)
@jiagengliu 我是把第二行的那个so拷到第一行那个位置，一共有两个so需要拷贝，名字很像，你看是不是另一个so没有拷贝报的错，才误以为没有成功

**Comment by vnpy** [comment]
检查后发现是v1.7.3安装文件里的bug，导致后续so复制的操作失败，着手处理下

**Comment by faithgithub** [comment]
1.8版本里问题修复了吗

**Comment by faithgithub** [comment]
还是遇到同样问题

**Comment by vnpy** [comment]
后来又发现另一个影响安装的，最新dev分支才修复掉

**Comment by chenkangcrack** [comment]
请问vnpy是否支持mac版？

**Comment by chenkangcrack** [comment]
请问vnpy是否支持mac平台？

**Comment by 799964990** [comment]
python run.py
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from vnpy.trader.gateway import (ctpGateway, ibGateway)
  File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/__init__.py", line 5, in <module>
    from .ctpGateway import CtpGateway
  File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/Users/fanren/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy/api/ctp/__init__.py", line 4, in <module>
    from .vnctpmd import MdApi
ImportError: No module named vnctpmd

**Comment by 799964990** [comment]
进入vnpy/api/ctp目录，运行bash build.sh，然后把build目录 下 找不到vnctpmd.so和vnctptd.so

**Comment by 799964990** [comment]
进入vnpy/api/ctp目录，运行bash build.sh，build目录 下 找不到vnctpmd.so和vnctptd.so
