### ISSUE TITLE
可否加入一些常用指标，比如macd, kdj

### ISSUE THREAD

**Issue by allenwwg** [vnpy/vnpy#69]
如题，可否加入一些常用指标，比如macd, kdj， 这样可以提高开发人员使用平台的效率。

**Comment by qzbysh** [comment]
在官网教程中有介绍，你看一下下面的文章。不知能否解决你的问题。
[使用TA-Lib在vn.trader上开发CTA交易策略](http://www.vnpy.org/talib-tutorial.html)

**Comment by vnpy** [comment]
建议新手可以使用TA-Lib，性能已经相当不错了，如果需要写特别高性能的指标函数的话建议自己研究cython。

**Comment by allenwwg** [comment]
多谢二位的回复， TA-Lib 可以解决我的问题了~~
