### ISSUE TITLE
关于自动切换合约

### ISSUE THREAD

**Issue by Henry-PY** [vnpy/vnpy#690]
如题，不知道VNPY,有没有现成的模块啊。

非常感谢

**Comment by vnpy** [comment]
vn.py目前不提供自动切换模块的功能，从灵活性角度考虑这块交给用户自己去控制。

**Comment by Henry-PY** [comment]
非常感谢。

另外，回测中的进出场信号标注，也是同样处理的吧？

**Comment by vnpy** [comment]
回测中的出入场交易位置，和实盘中的理论上应该都是完全一样的。
