### ISSUE TITLE
wiki image not displayed 

### ISSUE THREAD

**Issue by yurenji** [vnpy/vnpy#696]
## 环境

mac chrome & safari

## Issue类型
Bug

<img width="526" alt="2018-01-18 14 46 19" src="https://user-images.githubusercontent.com/5565266/35084617-c8789bce-fc5f-11e7-9793-b48b7a512236.png">

**Comment by vnpy** [comment]
可能是图床挂了，得联系这篇文档的作者更新下

**Comment by vnpy** [comment]
已修复
