### ISSUE TITLE
Python 3 + Anaconda 5 支持？

### ISSUE THREAD

**Issue by jiagengliu** [vnpy/vnpy#697]
现在公司用的是 Python 3.6 + Anaconda 5.0，是否可以使用 vnpy ？ 能否增加相应支持？

**Comment by xldistance** [comment]
有py3的ctp接口

**Comment by vnpy** [comment]
python3有社区贡献的CTP接口，5.0兼容方面应该没太大问题，有些小的库更新就自己修改下函数。
