### ISSUE TITLE
是否有迁移到python 3 的计划？

### ISSUE THREAD

**Issue by xarthurx** [vnpy/vnpy#698]
官方已经放出Python2两年后停止支持的消息，现在市面上大多数新的框架也都使用python3 开发。
请问vn.py是否有迁移到python3的打算呢？

还是说有些接口只能用python2对接，得等券商的update？

**Comment by PeakFish** [comment]
python3 是趋势呀，以后2都不维护了

**Comment by vnpy** [comment]
#674 重复问题，关闭
