### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by shenglinqian** [vnpy/vnpy#7]
按照教程3的方法编译了一下，vs2013在编译的时候提示
错误	4	error LNK1112: 模块计算机类型“X86”与目标计算机类型“x64”冲突
请教这个问题该如何解决

**Comment by vnpy** [comment]
看起来是项目配置中的目标计算机类型配置错误，的官方C++ API应该是只支持32位。

试试在项目配置中把目标计算机类型设置为X86。
