### ISSUE TITLE
CTA引擎需要解决上期所的平今平昨问题

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#70]

**Comment by qzbysh** [comment]
像国内常规交易软件那样优先平今如何？不知道客户持仓能否查询 今持仓和昨持仓。
不知道这个想法可行否。刚接触编程小白一个，个人陋见哈。

**Comment by vnpy** [comment]
这个方案相对比较方便，需要在程序里维护今仓和昨仓的状态，我在看具体怎么实现这个功能。

**Comment by vnpy** [comment]
已经在CTA引擎层面解决。
