### ISSUE TITLE
请问下，现在有数据，如何用来驱动vnpy

### ISSUE THREAD

**Issue by linshilogin** [vnpy/vnpy#700]
你好。现在我们有聚源提供的数据，mysql 的。请问下如何用在vnpy中。

**Comment by jieyujing** [comment]
现在项目有了，就差一个程序员。

linshilogin <notifications@github.com> 于 2018年1月19日周五 上午10:07写道：

**Comment by vnpy** [comment]
聚源提供的是什么数据，基本面数据对vn.py这种交易系统来说用不了，行情数据的话需要自己写一个数据服务

**Comment by linshilogin** [comment]
@vnpy  是行情数据。vnpy 是没有接其他数据的接口么

**Comment by vnpy** [comment]
vn.py的交易程序里不提供任何直接对接其他数据库的功能。

有独立的数据服务工具，用来每日定时将数据库中的数据更新到本地的MongoDB中，提供第二天交易使用。
