### ISSUE TITLE
example的runDataRecording.py的EVENT_ERROR处理

### ISSUE THREAD

**Issue by lajor2010** [vnpy/vnpy#702]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7  32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Question

执行example下的DataRecording下的runDataRecording.py，密码错误时，现象有
1、MD行情登录成功， 而TD登录失败
2、登录失败时，CtpTdApi的处理函数onRspUserLogin生成VtErrorData的错误对象，而VtGateway的onError进行处理，生成EVENT_ERROR的event
3、但是processLogEvent处理日志中，并无处理EVENT_ERROR的日志和VtErrorData

想请问下，如何处理EVENT_ERROR的日志和输出

**Comment by vnpy** [comment]
我来给加上

**Comment by vnpy** [comment]
已完成
