### ISSUE TITLE
eventEngine中import queue报错

### ISSUE THREAD

**Issue by desont** [vnpy/vnpy#705]
## 环境

* 操作系统: Ubuntu 14.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: pip install vnpy  2018.1.20

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
在exsample中的VnTrader： 运行python run.py

## 实际程序行为
提示eventEngine中import queue出错。

把import queue 修改为 import Queue后执行通过。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/15059175/35192539-85c23caa-fecf-11e7-955f-52279e9cdced.png)

**Comment by vnpy** [comment]
pip install future，这个已经添加到了安装文件中，请按照quickstart安装即可
