### ISSUE TITLE
centos anconda  下安装vnpy成功后，anaconda2/lib/python2.7/site-packages/vnpy没有发现example目录

### ISSUE THREAD

**Issue by baimin1** [vnpy/vnpy#708]
centos anconda  下安装vnpy成功后，anaconda2/lib/python2.7/site-packages/vnpy没有发现example目录
请问怎么办？

## 环境

* 操作系统: centos 6.5
* Anaconda版本anaconda2 Python 2.7
* vn.py版本: 如v1.7.3

**Comment by JaysonAlbert** [comment]
example目录是不会被安装的，只有项目目录里才有

**Comment by BillyZhangGuoping** [comment]
解压缩zip文档就有了，直接copy过去

**Comment by baimin1** [comment]
谢谢！

**Comment by baimin1** [comment]
cento 下能正常使用吗？

 python runDataRecording.py 
会出错：
ImportError: No module named queue
