### ISSUE TITLE
centos (非GUI) 下能正常使用吗？比如收集数据。

### ISSUE THREAD

**Issue by baimin1** [vnpy/vnpy#709]
centos (非GUI) 下能正常使用吗？比如收集数据。

python runDataRecording.py
会出错：
ImportError: No module named queue

## 环境

* 操作系统: 如WCentos 6.5
* Anaconda版本: 如Anaconda2 Python 2.7 32位
* vn.py版本: 如v1.7.3

**Comment by yesheng1984** [comment]
安装下future模块，试一下
pip install future
