### ISSUE TITLE
Pricing文件内的crr与black模型定价问题

### ISSUE THREAD

**Issue by EasyBasket** [vnpy/vnpy#711]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2
## Issue类型
Question

## 预期程序行为
对于美式看涨期货期权定价，Black76模型与CRR模型等价。

## 实际程序行为
输入参数相同，两个模型执行结果差异较大，如图所示。
![11111](https://user-images.githubusercontent.com/35676646/35276227-a9e95d48-007d-11e8-81b3-5b35aecbe622.png)

![22222](https://user-images.githubusercontent.com/35676646/35276237-b97ccaa6-007d-11e8-9ee6-4bd57302bb15.png)

# **将crr模型中的a赋值为1（期货期权），验算结果与black76相近，供参考。**

**Comment by vnpy** [comment]
CRR模型计算期货期权价值的时候， r需要调整为0。
