### ISSUE TITLE
计算gamma调用的差分函数不对

### ISSUE THREAD

**Issue by EasyBasket** [vnpy/vnpy#712]
https://github.com/vnpy/vnpy/blob/0fed1d01ad527b4c083ce39dc722f5a809074b78/vnpy/pricing/black.py#L64
vnpy/vnpy/pricing/目录下的模型均有此问题。

caculateDelta函数计算的是做1%调整后的delta，用caculateDelta函数计算的gamma与定义不符。caculateDelta函数中去掉“* (f * 0.01)”项，得到一个新函数，caculateGamma调用这个新函数计算得到的gamma（1%）才对。

**Comment by vnpy** [comment]
Gamma的定义，是1%价格变动时的Delta变动情况，验证计算后未发现错误。

请提供具体错误判断的计算过程。
