### ISSUE TITLE
冻结的挂单在成交后没有将持仓数据写入数据库pos

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#714]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2dev

## Issue类型
三选一：Bug

## 预期程序行为
冻结的挂单在成交后将持仓数据写入数据库pos

## 实际程序行为
冻结的挂单在成交后没有将持仓数据写入数据库pos，log也没有显示成交，但是UI界面是可以看到成交和增加的持仓的。策略那边是没有显示持仓变化，因此就无法触发止损逻辑运行。

**Comment by vnpy** [comment]
冻结的挂单指什么？看了下目前vn.py的数据流里没有这个概念
