### ISSUE TITLE
价差交易界面价格变动时没有做有效性检查

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy#715]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）
1.7.2
## Issue类型
三选一：Bug

## 预期程序行为
如果出现buy price 大于 sell price时，不能设置成功

## 实际程序行为
可以在运行中状态的情况下，手动设置sell price小于 buy price,会产生循环发单的现象。

## 重现步骤
可以在运行中状态的情况下，手动设置sell price小于 buy price,会产生循环发单的现象。
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
新增价差交易界面，禁止用户在算法启动时修改参数的功能（必须停止算法后才能修改，重启时会检查参数有效性）。
