### ISSUE TITLE
价差计算处理细节的问题，只有一腿数据的时候应该禁止交易

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy#716]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）
1.7.2
## Issue类型
三选一：Bug

## 预期程序行为
当计算价差时，有一条腿出现报价问题，应该禁止该方向的价差交易。
比如说，1条腿报价数据还没有收到，这时不能把整个价差的结果推送出去。
又或者说，涨停价没有ask1的情况，
又或者说，跨市场交易，一个市场开市，另外一个市场不开市的情况，两条腿必须都在目标方向可交易才能进入交易状态，否则应该禁止发单。

## 实际程序行为
初步在报价错误时把可交易量设置为了0，相当于暂时关闭了交易。
        # 遍历价差腿列表
        for n, leg in enumerate(self.allLegs):
            # 计算价格
            if leg.askPrice == leg.bidPrice and leg.bidPrice == EMPTY_FLOAT:
                # 清空价格和委托量数据
                self.bidPrice = EMPTY_FLOAT
                self.askPrice = EMPTY_FLOAT
                self.askVolume = EMPTY_INT
                self.bidVolume = EMPTY_INT
            else:

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复，基于leg.askVolume和leg.bidVolume来判断是否初始化，并在AlgoEngine中做了限制当价差行情尚未初始化时禁止推送该SpreadTick给算法去驱动交易
