### ISSUE TITLE
Syntax Error "for symbol in :"

### ISSUE THREAD

**Issue by chenziteng** [vnpy/vnpy#718]
https://github.com/vnpy/vnpy/blob/0fed1d01ad527b4c083ce39dc722f5a809074b78/vnpy/trader/gateway/okexGateway/okexGateway.py#L576

Considering the context, I guess the line should be "for symbol in SPOT_CURRENCY:"

**Comment by vnpy** [comment]
This is a bug which has already fixed in dev branch.

**Comment by vnpy** [comment]
This is a bug which has already fixed in dev branch.
