### ISSUE TITLE
qdp接口里 vnqdptd 中的 test 文件夹测试用例是 ctp 的，不是 qdh 的

### ISSUE THREAD

**Issue by DeadThein** [vnpy/vnpy#719]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 重现步骤

 vnpy/vnpy/api/qdp/vnqdptd/ 下的 test 文件夹里面的文件是ctp的接口

**Comment by vnpy** [comment]
好久没有人问QDP的问题了啊，我来处理下

**Comment by vnpy** [comment]
已移除
