### ISSUE TITLE
自建策略模块回测无法引用：No module named strategyXXX

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#720]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Question

使用runBackTesting进行回测，引用vnpy.trader.app.ctaStrategy.strategy下原有的策略文件，可以正常进行回测。
但是引用我新建的策略文件，比如：
文件名为strategyNew.py，在runBackTesting中引用：
from vnpy.trader.app.ctaStrategy.strategy.strategyNew import newStrategy
运行后，系统就会提示错误：
No module named strategyNew

很奇怪，照理来说都是vnpy.trader.app.ctaStrategy.strategy下的模块，都使用的绝对引用，为何我新建的模块就会提示找不到，请教

**Comment by vnpy** [comment]
1. 把策略文件放到安装到site-packages目录中的vnpy相关目录下，而不是你下载解压后的目录下
2. 回测的话，直接放到CtaBacktesting目录下，然后from strategyNew import newStrategy就行

**Comment by unlimitnight0** [comment]
十分感谢，回答精准，响应迅速
