### ISSUE TITLE
使用QuantOS下载镍的1805合约数据时报错

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#721]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Bug

## 实际程序行为
使用QuantOS下载镍的1805合约时报错
![image](https://user-images.githubusercontent.com/30992082/35607317-707219b2-068e-11e8-9fcf-b6d48af60752.png)

**Comment by vnpy** [comment]
是一个分钟转换的bug，dev已经修复

**Comment by huxunya** [comment]
使用新的代码后会出新的bug

![image](https://user-images.githubusercontent.com/30992082/35670285-162b1fcc-0773-11e8-97e7-ccb6e45d26b2.png)

**Comment by vnpy** [comment]
请使用最新的dev分支的代码试试
