### ISSUE TITLE
此处不适配期货期权。

### ISSUE THREAD

**Issue by EasyBasket** [vnpy/vnpy#722]
https://github.com/vnpy/vnpy/blob/0fed1d01ad527b4c083ce39dc722f5a809074b78/vnpy/pricing/crr.py#L49
建议此处修改为a = exp(b * dt)，以达到同时适应期货期权与股票期权的目的。
或干脆赋值a=1，因为CRR目前只计算期货期权。

**Comment by vnpy** [comment]
已修改
