### ISSUE TITLE
vnpy盘中kill，无保存contract文件，然后重启问题, 订单推送数据早于合约查询响应，导致获取合约信息为None   BUG

### ISSUE THREAD

**Issue by lajor2010** [vnpy/vnpy#723]
* 操作系统: Ubuntu 16.04
*  如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型 
Bug

## bug描述
前提：
# 设置数据同步模式为推送从今日开始所有数据
self.subscribePrivateTopic(0)
self.subscribePublicTopic(0)

场景：
1、vnpy盘中重启，用户登录完成后
2、onRspUserLogin会发送结算信息请求reqSettlementInfoConfirm，该请求回应后再发送查询合约reqQryInstrument
3、重启前当天有交易,在登录后就把当天所有交易数据推送回来，比如OnRtnOrder

步骤3早于步骤2的合约Rsp，最终发送EVENT_ORDER到vtEngine.py中，会调用detail = self.getPositionDetail(order.vtSymbol)

但getPositionDetail中的合约信息不存在，如IF、IH、IC等信息，该问题导致订单无法进行惩罚模式
![image](https://user-images.githubusercontent.com/11001991/35723869-c8cf8820-0836-11e8-96c1-c73fce1223e2.png)

**Comment by lajor2010** [comment]
建议在获取合约完毕后，立马save。 不等程序退出才save，避免程序中途cash掉

**Comment by vnpy** [comment]
1. 程序第一次使用时，需要从服务器获取合约数据
2. 后续每次启动时，都会先从本地加载，然后根据服务器推送获取的数据做增量更新

建议的方案是不要第一次使用程序就直接上实盘，先看看行情、调试一下，系统也会自动完成本地数据初始化，正常退出一次后再去跑策略交易
