### ISSUE TITLE
vnpy中回测引擎是以什么价格撮合的？

### ISSUE THREAD

**Issue by avincross** [vnpy/vnpy#725]
请教一个问题，载入数据为1min的K线数据
在onbar方法里发出开仓信号后，计算出了一个具体的开仓点位、手数，
在之后的k线里，会用什么价格撮合成交。（open、high、low、close）
价格点在开盘价和最高价之间的话，会成交吗，以什么点位成交？

**Comment by vnpy** [comment]
撮合的模式，接近实盘交易中的情景。

都以买入为例

限价100买入：
1. 下一根K线Low<=100，能成交，反之不能
2. 成交价格为100

停止100买入：
1. 下一根K线的High>=100，能成交，反之不能
2. 下一根K线的Open<=100，意味着K线中有机会以100的价格追入，成交价为100
3. 下一根K线的Open>100（比如105），意味着K线一开始就会触发信号，成交价为Open（即105）

**Comment by avincross** [comment]
谢谢，主要是优矿帮助文档上仅以开盘价和成交量来判断是否成交，所以想问下。

**Comment by vnpy** [comment]
优矿采用的是低频的粗粒度撮合模式，解决它针对的低频选股策略问题不大，但是对于CTA策略就精度太低了
