### ISSUE TITLE
中信证券接口轮训qryAccount, qryPosition两个接口会导致程序崩溃

### ISSUE THREAD

**Issue by shmliao** [vnpy/vnpy#726]
* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本:v1.72

三选一：Bug

中信证券接口轮训qryAccount, qryPosition两个接口会导致程序崩溃,麻烦帮忙看下是不是底层对接的有一点问题，比如内存问题，本人不懂C++，有劳了

**Comment by vnpy** [comment]
请问如何触发崩溃的？之前测试的时候做了几十笔交易开了一整天的交易时段没有遇到过。

**Comment by shmliao** [comment]
我也不知道，反正程序经常出现这个错误，0x1E07D7C9 (python27.dll) (python.exe 中)处有未经处理的异常:  0xC0000005:  读取位置 0x38313072 时发生访问冲突。

**Comment by vnpy** [comment]
请尝试触发一次错误，然后记录下这些信息：
1. 日志文件
2. cmd里错误的截图
3. 错误时屏幕的截图

另外问下你订阅了多少期权的行情，以及委托数量和频率大概是多少

**Comment by shmliao** [comment]
没有日志，没有报错，直接崩溃。。。能加个QQ不，有点问题QQ联系请教下。。。 #

**Comment by shmliao** [comment]
我没有订阅期权的行情，期权行情我是用飞创接口，然后每一秒查询account和position。。。

**Comment by vnpy** [comment]
你在QQ加我吧，著名是中信期权接口的问题就行

**Comment by shmliao** [comment]
QQ号多少

**Comment by vnpy** [comment]
418225424
