### ISSUE TITLE
策略运行回测后报错

### ISSUE THREAD

**Issue by Gemini-Nick** [vnpy/vnpy#727]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型

2018-02-06 16:25:02.756000	开始载入数据
2018-02-06 16:25:02.904000	载入完成，数据量：463950
2018-02-06 16:25:02.904000	开始回测
2018-02-06 16:25:02.904000	策略初始化完成
2018-02-06 16:25:02.904000	策略启动完成
2018-02-06 16:25:02.904000	开始回放数据

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-198f99f1abe7> in <module>()
      1 # 运行回测
----> 2 engine.runBacktesting()          # 运行回测

C:\Anaconda2\lib\site-packages\vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.pyc in runBacktesting(self)
    248             data = dataClass()
    249             data.__dict__ = d
--> 250             func(data)
    251 
    252         self.output(u'数据回放结束')

C:\Anaconda2\lib\site-packages\vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.pyc in newBar(self, bar)
    260         self.crossLimitOrder()      # 先撮合限价单
    261         self.crossStopOrder()       # 再撮合停止单
--> 262         self.strategy.onBar(bar)    # 推送K线到策略中
    263 
    264         self.updateDailyClose(bar.datetime, bar.close)

C:\Users\Gemini-Nick\Desktop\研究\vnpy-1.7.3\examples\CtaBacktesting\strategyBollingerBot.pyc in onBar(self, bar)
    158 
    159                 # 推送5分钟线数据
--> 160                 self.onFiveBar(fiveBar)
    161 
    162                 # 清空5分钟线数据缓存

C:\Users\Gemini-Nick\Desktop\研究\vnpy-1.7.3\examples\CtaBacktesting\strategyBollingerBot.pyc in onFiveBar(self, bar)
    192         # 撤销之前发出的尚未成交的委托（包括限价单和停止单）
    193         for orderID in self.orderList:
--> 194             self.cancelOrder(orderID)
    195         self.orderList = []
    196 

C:\Anaconda2\lib\site-packages\vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.pyc in cancelOrder(self, vtOrderID)
    147             self.ctaEngine.cancelStopOrder(vtOrderID)
    148         else:
--> 149             self.ctaEngine.cancelOrder(vtOrderID)
    150 
    151     #----------------------------------------------------------------------

C:\Anaconda2\lib\site-packages\vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.pyc in cancelOrder(self, vtOrderID)
    472     def cancelOrder(self, vtOrderID):
    473         """撤单"""
--> 474         if vtOrderID in self.workingLimitOrderDict:
    475             order = self.workingLimitOrderDict[vtOrderID]
    476 

TypeError: unhashable type: 'list'

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
v1.7.2后委托返回的是一个委托号的列表，而非单一委托号，因此撤单的时候要把列表里面的内容作为参数传入cancelOrder里
