### ISSUE TITLE
在企业版suse上build报错

### ISSUE THREAD

**Issue by reaIws** [vnpy/vnpy#728]
## 环境

* 操作系统:sles 12.3
* Anaconda版本: Python 2.7.13 |Anaconda 4.3.1 (64-bit)
* vn.py版本: 如v1.7.3 20180206下载

## Issue类型
三选一：Question

## 预期程序行为
cd vnpy/api/ctp
build 
成功

## 实际程序行为
编译失败

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![default](https://user-images.githubusercontent.com/23316065/35852654-6bf48802-0b66-11e8-9871-016466b347b3.png)
![default](https://user-images.githubusercontent.com/23316065/35852687-7cc4072a-0b66-11e8-9f05-a587dfbf72bc.png)
![default](https://user-images.githubusercontent.com/23316065/35852710-8945725e-0b66-11e8-8c92-c1702efc5c2f.png)

**Comment by reaIws** [comment]
![default](https://user-images.githubusercontent.com/23316065/35853142-b296236e-0b67-11e8-896a-bb4117bed0dd.png)

**Comment by vnpy** [comment]
我理解应该是在SUSE上安装boost后并不会将其自动添加到环境变量中，因此你在cmake的配置文件里需要手动指定boost所在的路径，否则编译器就无法找到相关文件，报上面的错误

**Comment by reaIws** [comment]
感谢回答，我手动找到了libboost库（/usr/lib64），并添加到了CMakeLists.txt 中，但是出这个错误
![default](https://user-images.githubusercontent.com/23316065/35896325-9c11a4bc-0bf6-11e8-9cea-0282956eec0c.png)
![default](https://user-images.githubusercontent.com/23316065/35896376-d261c038-0bf6-11e8-8fee-e77ea5c024e4.png)
![default](https://user-images.githubusercontent.com/23316065/35896415-0355fe16-0bf7-11e8-88bc-9a684189abc1.png)

**Comment by reaIws** [comment]
貌似解决了
![default](https://user-images.githubusercontent.com/23316065/35897002-058c9c0a-0bfa-11e8-9d91-f8cbaecf7481.png)
![default](https://user-images.githubusercontent.com/23316065/35897060-57704396-0bfa-11e8-9b4a-b903688acd8f.png)

**Comment by reaIws** [comment]
您好，错一个一个来的让人猝不及防呀，您能帮忙看看这个问题么
![default](https://user-images.githubusercontent.com/23316065/35898356-2ac1fa04-0c01-11e8-9f5e-c24dd8a63fdd.png)

**Comment by vnpy** [comment]
比较奇怪，你已经编译成功了，但是报错找不到boost-python的动态链接库，这个好诡异。

我的简单建议是换回ubuntu 16.04
