### ISSUE TITLE
[Question] 谁调用vtEngine.py中PositionDetail的updateTick，用于实时计算盈亏

### ISSUE THREAD

**Issue by lajor2010** [vnpy/vnpy#729]
## 环境

* Ubuntu 16.04
* Anaconda 4.0.0 Python 2.7 32位
* vn.py  1.7.3

## Issue类型
Question

## 预期程序行为
获取动态盈亏时，在持仓未同步之前，getPositionDetail后获取longPnl，发现由于没有tick的lastPrice，导致其longPnl都是亏几十万的，因为lastPrice=0无值

目前：
通过上层processTickEvent后，
调用self.mainEngine.dateEngine.getPositionDetail(vtSymbol).updateTick(tick)向下直通式赋值，但觉得有种破坏结构性。

想了解下，当前PositionDetail的updateTick，设计上在谁来触发，那里触发的？  
谢谢

**Comment by vnpy** [comment]
由DataEngine负责触发
