### ISSUE TITLE
如何统计回测结果，比如胜率，最大回撤等

### ISSUE THREAD

**Issue by allenwwg** [vnpy/vnpy#73]
请问有没有现成的库可以统计回测结果？比如胜率，最大回撤，最大连续亏损等

**Comment by vnpy** [comment]
vn.trader里面的ctaAlgo模块下有回测功能，目前提供盈利和最大回撤的统计，其他统计可以自己添加，都比较容易，据我所知目前没有什么现成的库专门统计回测结果。

**Comment by allenwwg** [comment]
好的，多谢~~
