### ISSUE TITLE
策略参数优化程序（runOptimization.py）中的targetName分配不正确，建议统一单进程和多进程

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#735]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.3 发行版

## Issue类型
三选一：Bug

## 预期程序行为
执行runOptimization.py， 按照默认优化指标capital（净盈利）排序，最优指标的参数集列第一。

## 实际程序行为
程序默认使用多线程方法runParallelOptimization, 返回结果capital都为空，result[1]为空; 改用单线程方法runOptimization，返回结果正确。

## 重现步骤
检查代码发现，优化指标capital只在对应单线程方法中指定；多线程时另外一组dict。
针对单线程的dict：
d['capital']=capital
d['maxCapital']=maxCapital
d['drawdown']=drawdown
d['totalResult']=totalResult
d['totalTurnover']=totalTurnover
d['totalCommission']=totalCommission
d['totalSlippage']=totalSlippage
d['timeList']=timeList
d['pnlList']=pnlList
d['capitalList']=capitalList
d['drawdownList']=drawdownList
d['winningRate']=winningRate
d['averageWinning']=averageWinning
d['averageLosing']=averageLosing
d['profitLossRatio']=profitLossRatio
d['posList']=posList
d['tradeTimeList']=tradeTimeList
d['resultList']=resultList

**Comment by BillyZhangGuoping** [comment]
针对多线程的dict是另外一组, key不一样，target改用totalNetPnl, 可以跑出结果。建议把单线程和多线程改一样，或者程序默认的capital改为totalNetPnl，和多线程一致。
result={
'startDate':startDate,
'endDate':endDate,
'totalDays':totalDays,
'profitDays':profitDays,
'lossDays':lossDays,
'endBalance':endBalance,
'maxDrawdown':maxDrawdown,
'maxDdPercent':maxDdPercent,
'totalNetPnl':totalNetPnl,
'dailyNetPnl':dailyNetPnl,
'totalCommission':totalCommission,
'dailyCommission':dailyCommission,
'totalSlippage':totalSlippage,
'dailySlippage':dailySlippage,
'totalTurnover':totalTurnover,
'dailyTurnover':dailyTurnover,
'totalTradeCount':totalTradeCount,
'dailyTradeCount':dailyTradeCount,
'totalReturn':totalReturn,
'annualizedReturn':annualizedReturn,
'dailyReturn':dailyReturn,
'returnStd':returnStd,
'sharpeRatio':sharpeRatio
}

**Comment by xldistance** [comment]
多进程用endBalance就好了

**Comment by vnpy** [comment]
已修复
