### ISSUE TITLE
VTEngine Line:1056 1058代码逻辑错误

### ISSUE THREAD

**Issue by bigdig** [vnpy/vnpy#738]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

                    reqClose = copy(req)
                    if self.exchange is EXCHANGE_SHFE:
                        req.offset = OFFSET_CLOSEYESTERDAY
                    else:
                        req.offset = OFFSET_CLOSE
                    reqClose.volume = ydAvailable

是否应当是

                    reqClose = copy(req)
                    if self.exchange is EXCHANGE_SHFE:
                        reqClose.offset = OFFSET_CLOSEYESTERDAY
                    else:
                        reqClose.offset = OFFSET_CLOSE
                    reqClose.volume = ydAvailable

**Comment by vnpy** [comment]
已修复
