### ISSUE TITLE
CTA策略模块策略开发 的wiki中关于类变量的说明

### ISSUE THREAD

**Issue by avincross** [vnpy/vnpy#739]
## 环境
mac && python3.5

    # 这里定义的变量是类成员，方便引擎在创建策略对象前了解一些信息
    barList = []    # 若基于TestStrategy类创建多个策略对象，他们的barList都会指向同一个列表，导致出错
    lastPrice = 0   # 数字(int、float)在Python中属于不可变对象，因此每个策略的lastPrice互不影响

    #----------------------------------------------------------------------
    def __init__(self, ctaEngine, setting):
      super(TestStrategy, self).__init__(ctaEngine, setting)

      # 这里定义的变量是对象创建后自身独有的成员

      self.barList = []   # 在这里对barList重新初始化，指向一个新建的独立列表`

不管是list或者数字类型的类变量，它们不都是共享的吗？
在init()方法中的重新声明同名变量，只不过是在类实例新定义了一个变量，原来的变量仍然存在啊，
只不过由于属性查找顺序首先查找实例对象自己，然后是类，接着是类的父类。相当于被“覆盖”了
instance.__dict 和 instance.__class__.__dict__

当然也可能是python2.7的特性不一样？？？

**Comment by vnpy** [comment]
1. 是共享的
2. init声明覆盖后，后续查找的第一个都是实例对象自身的变量，那么就达到了目的：每个实例里的算法逻辑只访问本实例自身的数据
