### ISSUE TITLE
WEB界面连接CTP时显示连接成功但左下角服务器连接状态显示未连接

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#741]
## 环境

* 操作系统: LINUX
* Anaconda版本: 最新64位
* vn.py版本: DEV版本

## Issue类型
三选一：Bug

## 预期程序行为
左下角连接后显示为：服务器已连接

## 实际程序行为
显示为：服务器未连接

## 重现步骤

WEB访问。

**Comment by cccbbbaaab** [comment]
这个问题主要是文字描述不清楚，左下角的服务器连接与否是指是否连接上后台的socket服务器，而不是CTP服务器，新的推送已经修改了文字描述
