### ISSUE TITLE
WEB页面登陆后无数据

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#742]
## 环境

* 操作系统: LINUX，CENTOS7.0
* Anaconda版本:最新64位
* vn.py版本: DEV

## Issue类型
三选一：Bug

## 预期程序行为
1,登陆连接成功后应该会展示资金持仓等信息
2，订阅显示成功，行情区域有数据

## 实际程序行为
无任何显示数据

## 重现步骤

WEB展示。无数据。

**Comment by cccbbbaaab** [comment]
能看一下后台的flask有什么输出么？

**Comment by ShellMount** [comment]
通过定时重启解决了无数据的问题。
（原因可能是run.py经常卡死，如连续跑一天。就会卡死）

**Comment by ShellMount** [comment]
但订阅，仍然不成功。

**Comment by vnpy** [comment]
@ShellMount 订阅行情，请确保在交易时段或者用24小时那套环境
@cccbbbaaab 请帮忙看下持仓盈亏的问题吧

**Comment by ShellMount** [comment]
@vnpy 是在交易时段，且是正式账号。

**Comment by vnpy** [comment]
@ShellMount 给个截图吧，然后也说明下你的操作步骤？

**Comment by ShellMount** [comment]
由于这图片上传不成功。
我把图片，放到QQ群的文件里面了，
文件名： issue369778941

**Comment by vnpy** [comment]
看了下，确实情况比较奇怪，两个建议：
1. 使用chrome浏览器
2. 试试最新的dev分支，修复了几个web的bug

**Comment by ShellMount** [comment]
WEB功能的run.py经常卡死，如连续跑一天。就会卡死

最好也能解决一下。这个我没能定位到原因。
现象就是跑过一天后，不响应服务，是大概率事件。

**Comment by vnpy** [comment]
和VnTrader一样，WebTrader每天3点后也需要关闭直到开盘前重启，不能连续不关

**Comment by ShellMount** [comment]
修改后，没有“连接CTP”了，点了无反映，服务端后台，没有显示这个动作。
