### ISSUE TITLE
如何添加okex接口？

### ISSUE THREAD

**Issue by MooreY** [vnpy/vnpy#746]
在run.py内添加me.addGateway(okexGateway)后执行显示错误cannot import name okexGateway

**Comment by xldistance** [comment]
你要先import okexGateway接口啊

**Comment by vnpy** [comment]
okexGateway移动到了beta文件夹下，要使用的话请将api和gateway分别复制到你的site-packages下的vnpy目录中对应的位置后，就能加载使用了
