### ISSUE TITLE
Runtime exception: "tick is not defined"

### ISSUE THREAD

**Issue by chenziteng** [vnpy/vnpy#747]
Please see the code snippet below, the variable "tick" is not defined (the issue also exists in the dev branch). I think it should be "self.lastTick".

https://github.com/vnpy/vnpy/blob/2646bbd07b90c8a1795001a6712e1d5d1aabda90/vnpy/trader/app/ctaStrategy/ctaTemplate.py#L284-L291

**Comment by vnpy** [comment]
Fixed. Thanks!
