### ISSUE TITLE
CTP关于上期所持仓问题以及大连郑州今昨持仓问题。

### ISSUE THREAD

**Issue by raycool** [vnpy/vnpy#748]
# 针对上期所持仓的今昨分条返回（有昨仓、无今仓），读取昨仓数据
        if data['YdPosition'] and not data['TodayPosition']:
            pos.ydPosition = data['Position']

ctpGateway中这行代码可以解决上期所今昨仓问题。
但是对于郑州和大连来说，如果持有昨仓，而无今仓，那么此条语句同样执行，可以得到昨仓的持仓数，同时下面的代码得到的总持仓数。
        # 汇总总仓
        pos.position += data['Position']
        pos.positionProfit += data['PositionProfit']
但是对于持有同时持有昨仓和今仓的大连郑州品种，如果盘中打开vnpy，那么pos.ydPosition = data['Position']的语句不会被触发，得到的总持仓数是正确的，但是此时昨持仓数为0， 那么在updatePosition 更新函数中，

            self.longPos = pos.position
            self.longYd = pos.ydPosition
            self.longTd = self.longPos - self.longYd

self.longTd的数值把昨仓和今仓一起计算了，造成昨仓今仓的数据混乱，虽然逻辑上郑州大连不分今昨仓，但是在现实中会发生混乱。
CTP文档中描述：
YdPosition 持仓查询记录中的昨持仓是今天开盘前的一个初始值，不会因为平昨或者平仓而减少。 当前时侯的昨持仓=总持仓-今持仓。YdPosition := Position - TodayPosition。

那么ctp中修改为   
        if data['YdPosition']:
            pos.ydPosition = data['Position'] - data['TodayPosition']

对于有昨仓，那么这条语句都会被执行，可以得到正确的昨仓持仓数，随后的updatePosition 函数更新得到的结果都没问题。
这是看ctp代码中感到不理解的地方，提出来自己的看法，不知道是否正确。

**Comment by vnpy** [comment]
我来检查下，这个点看得很细了

**Comment by jerrycgc** [comment]
这BUG还没有更新吗

**Comment by vnpy** [comment]
已修复
