### ISSUE TITLE
跪求开发多品种的回测

### ISSUE THREAD

**Issue by hackerwei** [vnpy/vnpy#749]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
vnpy/examples/CtaBacktesting/backtesting_portfolio.ipynb

**Comment by vnpy** [comment]
楼上正解

**Comment by hackerwei** [comment]
OK, close!
