### ISSUE TITLE
回测优化参数run optimization以后，输出对应的目标以及每个优化参数

### ISSUE THREAD

**Issue by Gemini-Nick** [vnpy/vnpy#751]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

优化多个参数结果以后，希望可以输出excel每个遍历的结果和对应目标值，方便可视化和分析

**Comment by vnpy** [comment]
目前已经可以输出每次遍历结果的所有统计数值，调用BacktestingEngine的runParallelOptimization函数后返回的结果列表中就有。

输出为EXCEL的操作建议自己用csv模块处理下，很容易。
