### ISSUE TITLE
XTP编译的问题

### ISSUE THREAD

**Issue by songhanjie** [vnpy/vnpy#752]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7dev branch 20180220（下载日期）

## Issue类型
三选一：Bug

## 重现步骤

vnxtpquote.cpp和vnxtptrader.cpp中，因为有#include "stdafx.h"，安装时候会报错。
1.7.1版本中是不存在这个#include "stdafx.h"，陈老师检查一下这里。

**Comment by vnpy** [comment]
多谢！我来处理下

**Comment by vnpy** [comment]
已完成
