### ISSUE TITLE
web 版界面登录密码输入时显示为明文。

### ISSUE THREAD

**Issue by pqctp** [vnpy/vnpy#753]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请问下建议的修改方法？

**Comment by songhanjie** [comment]
setEchoMode()可以加密
