### ISSUE TITLE
ctaTemplate->TargetPosTemplate->trade中tick使用错误

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#754]
## 环境
* vn.py版本: v1.8

## Issue类型
三选一：Bug

![image](https://user-images.githubusercontent.com/1277606/36658245-a20ca1c8-1b0a-11e8-9492-59acae7622a7.png)

tick是不是要改成self.lastTick ?

**Comment by xldistance** [comment]
是的

**Comment by vnpy** [comment]
dev分支已修复
