### ISSUE TITLE
Ubuntu17.10 ImportError: No module named qtpy.QtCore 错误

### ISSUE THREAD

**Issue by l0o0** [vnpy/vnpy#755]
## 环境

* 操作系统: Ubuntu 17.10, 64位
* Anaconda版本: conda 4.3.29， python 2.7.14， 都64位
* vn.py版本: v1.8

## Issue类型
三选一：Question

## 重现步骤
根据wiki上的ubuntu安装步骤进行安装，我是先用conda创建了一个虚拟环境，在环境中安装相应的依赖，结果最后一步运行的时候，出现错误：
```
(vn) ➜  VnTrader python run.py 
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from vnpy.event import EventEngine
  File "/home/l0o0/.miniconda2/envs/vn/lib/python2.7/site-packages/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "/home/l0o0/.miniconda2/envs/vn/lib/python2.7/site-packages/vnpy/event/eventEngine.py", line 10, in <module>
    from qtpy.QtCore import QTimer
ImportError: No module named qtpy.QtCore
```
我分别使用conda安装过PyQt4和PyQt5，不过都会出现这样的问题。
不知道是什么原因

**Comment by vnpy** [comment]
之前尝试conda虚拟环境的时候遇到过相同的问题，当时未能解决。

这里的报错是说缺失qtpy这个库，这是个PyQt4和5的兼容库，用conda安装下后再试试。

**Comment by l0o0** [comment]
@vnpy 安装了之后，后面又出现了lib库文件的问题，应该是conda安装的和系统自带的库文件对不上。我开个虚拟机试试

**Comment by Tilyp** [comment]
sudo apt-get install python-qt4      就可以解决

**Comment by KimChow** [comment]
我在安装的时候，也遇过类似的问题。

最终是按着教程上面，使用指定的Anaconda2-4.0.0的版本解决的。建议认真地看教程来搞咯。

一些新版本的确存在说不清楚的问题。

**Comment by raidsan** [comment]
应该是 PyQt4 吧？ 哪里来的 qtpy ?  快被搞糊涂了，  QtWidgets 是 PyQt5的， 不是说  pyqtgraph 要求 PyQt4吗....
   qtpy 就应该改成 PyQt5

**Comment by raidsan** [comment]
好多错，没有维护了？  QtCore.signal 应该改成 QtCore.pyqtSignal

**Comment by jcjview** [comment]
after apt-get install python-qt4,
still need pip install qtpy in conda env

**Comment by justinchou** [comment]
MacOS 出现这个问题我的解决方法是
```
brew install qtpy
pip install QtPy
```
