### ISSUE TITLE
实盘模拟中，夜盘未成交挂单无法在日盘被策略自动撤销

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#757]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.3dev

## Issue类型
Bug

## 程序行为
在SIMNOW的实盘模拟中，夜盘的未成交挂单在交易时间内没撤销，第二天日盘策略内的cancel all 不能撤掉这个挂单，必须通过UI界面的全撤按钮才能撤销。
基本是如果关闭UI前有挂单未成交并且为撤单，再次运行UI时策略无法取消掉之前的挂单，必须手动取消，或者下一个交易日才会取消。

**Comment by vnpy** [comment]
策略的cancelAll只能撤销由该策略发出的委托，UI上的全撤是撤销整个系统内所有的活动委托

检查你是否夜盘收盘后关闭了系统，日盘开盘前才启动的，这样必然策略就不知道之前的委托了

**Comment by huxunya** [comment]
对的，因为不收盘后到下次开盘需要重新启动系统，所以是否可以设置日盘开启后撤销之前的系统挂单？或者可以限制最后几分钟不挂单？

**Comment by vnpy** [comment]
第一个方法，可以写个小的定制化模块，每次日盘启动后自动全撤所有系统内委托。
第二个方法，可以直接在策略里写，比如夜盘倒数3分钟不允许交易，并全撤委托
