### ISSUE TITLE
开市价单直接撤销，开限价单就能成交，请问这是怎么回事

### ISSUE THREAD

**Issue by JohnHush** [vnpy/vnpy#758]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
Question

**Comment by JohnHush** [comment]
![screen shot 2018-02-28 at 10 15 31 am](https://user-images.githubusercontent.com/15883960/36766365-8187a9fe-1c70-11e8-9a67-5de1256ac463.png)
补充截图

**Comment by vnpy** [comment]
看下错误输出中是否有任何信息，我记得上期所的委托规则和其他交易所有所区别

**Comment by JohnHush** [comment]
错误输出没有任何信息，我用的simnow的虚拟账号，市价单直接就是“已撤销”

**Comment by JohnHush** [comment]
@vnpy

**Comment by vnpy** [comment]
https://www.zhihu.com/question/47525423/answer/106446516

上期所不支持市价单

**Comment by JohnHush** [comment]
@vnpy 原来如此，非常感谢，所以采用报涨停价来做市价买单
