### ISSUE TITLE
BarGenerator中volume计算改进建议

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#760]
## 环境

* vn.py版本: v1.8

## Issue类型
三选一：Enhancement

## 实际程序行为
当前版本中bar的volume直接用当前减上一根tick的差值进行累加：
self.bar.volume += (tick.volume - self.lastTick.volume) # x

在夜盘开盘第1根新K线时，tick.volume是很小的，而self.lastTick.volume则是上一日累计的交易量，导致计算出来的bar.volume是很大的负值
建议做如下修改：
            if tick.volume <self.lastTick.volume:
                self.bar.volume +=tick.volume #使用累加是因为盘中会有些volume为0的干扰tick，如果前面没有过滤掉的话，则要累加
            else:
                self.bar.volume += (tick.volume - self.lastTick.volume)

**Comment by vnpy** [comment]
大概理解意思，方便的话请发个PR？

**Comment by smartgang** [comment]
呃，我魔改了好多地方，不知道怎样只单独pull这一个commit。。。

**Comment by vnpy** [comment]
已修改
