### ISSUE TITLE
webTrader持仓显示不对

### ISSUE THREAD

**Issue by 80779898** [vnpy/vnpy#763]
## Issue类型
Bug

## 预期程序行为
持仓中，相同合约多空均有持仓时，分别显示多和空

## 实际程序行为
持仓中，相同合约多空均有持仓时，只显示多或者空
估计时持仓表格唯一标识只用了合约代码，而不是使用合约代码与方向的组合
![qq 20180302133447](https://user-images.githubusercontent.com/3130864/36884864-824011a6-1e1e-11e8-9ce6-55d742132d8f.png)

**Comment by cccbbbaaab** [comment]
确实有问题，现在用vtPositionName做key，已经修复了
