### ISSUE TITLE
不太确定是bug还是我环境问题

### ISSUE THREAD

**Issue by suifengpiao14** [vnpy/vnpy#764]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
不报错

## 实际程序行为
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XTPAPI_MD_LIBRARY
    linked by target "vnxtpquote" in directory /root/vnpy-1.8/vnpy/api/xtp
XTPAPI_TD_LIBRARY
    linked by target "vnxtptrader" in directory /root/vnpy-1.8/vnpy/api/xtp

## 重现步骤
vnpy-1.8 版本 在linux （centos7）下的vnpy/api/xtp 目录中运行 ./build.sh  报上述错误

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by songhanjie** [comment]
作者已经在dev版本中修复了这个问题，1.8发行版还存在这个问题，你可以手工修复下，在~\vnpy\api\xtp\vnxtpquote\vnxtpquote和\vnxtptrader中，分别对vnxtpquote.cpp和vnxtptrader.cpp进行修改，修改内容为：
将
#include "stdafx.h"
替换为
#ifdef WIN32
	#include "stdafx.h"
#endif

**Comment by suifengpiao14** [comment]
多谢陈老师，刚看到之前有人提交过同一个bug，并且已经解决了

**Comment by hongkuik** [comment]
我的已经更换为
#ifdef WIN32
#include "stdafx.h"
#endif
但是还是一样的错误提示

**Comment by vnpy** [comment]
请使用v1.8.1吧
