### ISSUE TITLE
运行install.bat时，执行一段时间命令行界面会自动关闭，结果examples/VnTrader文件夹下无法运行run.py

### ISSUE THREAD

**Issue by GitouYou** [vnpy/vnpy#767]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 5.1.0 Python 2.7 32位
* vn.py版本: 1.8

## Issue类型
三选一：Question

## 预期程序行为

examples/VnTrader文件夹下运行python vn.py，打开界面

## 实际程序行为
提示无法找到活加载 Qt platform plugin "windows"

## 重现步骤
![image](https://user-images.githubusercontent.com/18010165/36974639-4b84d1c4-20b2-11e8-9fa8-c7d9dbd9bbc2.png)

**Comment by vnpy** [comment]
1. ib的信息是一个运行时提示，并不是报错
2. 你的Python环境是否为Anaconda 4.0.0 Python2.7 32位
