### ISSUE TITLE
数据记录模块输出的时间模块还是不对

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#773]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8

## Issue类型
三选一：Bug

## 预期程序行为
数据记录日期正确

## 实际程序行为
超前的记录时间
{ "datetime" : ISODate("2018-03-18T09:00:00.600Z"),  "insertTime" : ISODate("2018-03-05T08:59:01.871Z"),  "symbol" : "i1805"}
{ "datetime" : ISODate("2018-03-18T09:00:01.100Z"),  "insertTime" : ISODate("2018-03-05T08:59:03.027Z"), "symbol" : "i1805"}

## 重现步骤

跑一下数据记录模块就出来。

**Comment by vnpy** [comment]
datetime：交易所行情服务器切片时的时间戳
insertTime：本地将数据插入数据库时的时间戳

你说的错误指的是datetime落后于insertTime？这个可能是因为本地时钟和交易所比提前了导致的

**Comment by ShellMount** [comment]
不是上面所说的问题。
这个问题起始于当然修改CTP接口的日期，把晚盘日期修正为第二的日期。造成的。一直未能修改对。

本地时钟是OK的。

**Comment by KobeZhao** [comment]
不是实盘数据吧，是不是simnow的问题

**Comment by vnpy** [comment]
这个修改CTP接口日期的逻辑，是你自己添加的吗，还是vn.py现有系统里的？

**Comment by ShellMount** [comment]
不是我添加的。
是CTP-API中的 onRtnDepthMarketData 这个函数造成的：

这个函数在日期转换时，会遇到各种问题。这是之前的一个BUG。
# 大商所日期转换
        if tick.exchange is EXCHANGE_DCE:
            newTime = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 最新tick时间戳
            
            # 如果新tick的时间小于夜盘分隔，且上一个tick的时间大于夜盘分隔，则意味着越过了12点
            if (self.tickTime and 
                newTime < NIGHT_TRADING and
                self.tickTime > NIGHT_TRADING):
                self.tradingDt += timedelta(1)                          # 日期加1
                self.tradingDate = self.tradingDt.strftime('%Y%m%d')    # 生成新的日期字符串
                
            tick.date = self.tradingDate    # 使用本地维护的日期
            
            self.tickTime = newTime         # 更新上一个tick时间

**Comment by KobeZhao** [comment]
这个好像真的是bug，假设是9:00，并且第二天早上盘前重启，
9:00<NIGHT_TRADING and 23:30>NIGHT_TRADING, tradingDt开始是今天的日期，那么+=timedelta(1)之后，日期就会叠加了。

**Comment by vnpy** [comment]
所以判断过午夜日期增加的逻辑里，用：

`newTime  < NIGHT_TRADING`

就不太合适了，应该改成比如newTime < 1:00之类的？

**Comment by ShellMount** [comment]
发现了解决方案：
造成这个原因，是因为 self.tradingDt 使用了全局变量，导致每一个合约都会让这个会是 +1

修正方案：增加变量初始化：
self.tradingDt = datetime.now()

整体代码如下：
# 大商所日期转换
        if tick.exchange is EXCHANGE_DCE:
            newTime = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 最新tick时间戳
            
            # 如果新tick的时间小于夜盘分隔，且上一个tick的时间大于夜盘分隔，则意味着越过了12点
            if (self.tickTime and 
                newTime < NIGHT_TRADING and
                self.tickTime > NIGHT_TRADING):
                self.tradingDt = datetime.now()
                self.tradingDt += timedelta(1)                          # 日期加1
                self.tradingDate = self.tradingDt.strftime('%Y%m%d')    # 生成新的日期字符串
                
                print u'日期 +1 : ', self.tradingDate, tick.vtSymbol
                
            tick.date = self.tradingDate    # 使用本地维护的日期
            
            self.tickTime = newTime         # 更新上一个tick时间

**Comment by jerrycgc** [comment]
shellMount的解决方案还是有问题吧
1. self.tradingDt 使用全局变量，逻辑是大商所跨越午夜12点时调整日期吧，不直接用self.tradingDt = datetime.now()局部变量应该是考虑到TICK时间和本地时间可能有出入，造成日期时间错位吧。这一前提是每天早盘手动开启录制程序而不是24小时运行。那是很多年以前，现在大商所都23：30之前结束，不再跨夜了，那这个逻辑就不必存在了。
2你直接取当前日期那为什么还要加1呢，那不是明显还是超前1天了？
.self.tradingDt = datetime.now()
            self.tradingDt += timedelta(1)  
=========
我想知道的是，，现在大商所都23：30之前结束，是不是这一段直接取消就可以了，大商所没有必要再单独处理？
如果怕大商所抽风再延长夜盘交易时间，要继续保存这一判断，那就要考虑全合约和连续24小时录制的情况：一是newTime还要小于日盘交易时间比如8：00，二是增加一个标记变量，不管多少合约只增加一次
不知是否正确，最好尽快更新

**Comment by ShellMount** [comment]
@jerrycgc

1, 我的处理方式：
        now = datetime.now()

        # 大商所日期转换
        if tick.exchange is EXCHANGE_DCE:
            newTime = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 最新tick时间戳
            
            # 如果新tick的时间小于夜盘分隔，且上一个tick的时间大于夜盘分隔，则意味着越过了12点
            if (self.tickTime and 
                newTime < NIGHT_TRADING and
                self.tickTime > NIGHT_TRADING):
                self.tradingDt = now
                self.tradingDate = self.tradingDt.strftime('%Y%m%d')    # 生成新的日期字符串
                
            tick.date = self.tradingDate    # 使用本地维护的日期
            
            self.tickTime = newTime         # 更新上一个tick时间
        
        # 避免脏数据
        if not tick.date:
            return
        
        dt = datetime.strptime("%s %s" % (tick.date, tick.time), '%Y%m%d %H:%M:%S.%f')
        if abs((dt - now).total_seconds()) > 200 :
            return
                
        self.gateway.onTick(tick)


2，大商所是否23:30就结束了，这一点我不清楚，受知识所限，我平常并未了解很多的合约。

3，一是newTime还要小于日盘交易时间比如8：00。这个描述是一个误区，这个值尽可能小应该。比如为8点的情况，不能防止8点前出现人工重启的情况。

**Comment by jerrycgc** [comment]
@ShellMount 
我直接注释掉了这一段。查了一下资料，主要是大商所ACTIONDAY取的是交易日的日期即夜盘取第二天（周五取下周一），郑商所在TRADINGDAY跟其它交易所又有区别。以下代码运行良好，不知道你说的人工重启会有什么情况。tick.date可能为空吗？：
        if tick.exchange is EXCHANGE_DCE:
            newTime = datetime.strptime(tick.time, '%H:%M:%S.%f').time()    # 最新tick时间戳

            """
            # 如果新tick的时间小于夜盘分隔，且上一个tick的时间大于夜盘分隔，则意味着越过了12点
            if (self.tickTime and 
                newTime < NIGHT_TRADING and
                self.tickTime > NIGHT_TRADING):
                self.tradingDt += timedelta(1)                          # 日期加1
                self.tradingDate = self.tradingDt.strftime('%Y%m%d')    # 生成新的日期字符串
            """

            #夜盘时间用本地日期
            if newTime > NIGHT_TRADING:
                tick.date = datetime.now().strftime('%Y%m%d')    # 使用本地维护的日期
            
            self.tickTime = newTime         # 更新上一个tick时间

**Comment by ShellMount** [comment]
@jerrycgc 
如果不注释， 假设夜盘分界线 NIGHT_TRADING 设置为早上8:00
需要一个前提：如果大商所，早上交易到2:30

此时，在1:30分的时候，人为重启程序（或挂掉了，重新打开），
那么，这时候，日期仍然会增加1。

解决这个CASE的情况，是将 NIGHT_TRADING 设置得更小  如早上0点5分。

**Comment by vnpy** [comment]
已修复
