### ISSUE TITLE
pythonw.exe 已停止工作， appcrash, after receiving option market data from 银河SEC接口。

### ISSUE THREAD

**Issue by tesla1060** [vnpy/vnpy#774]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
三选一：Bug

## 实际程序行为
最近一周，连接银河的SEC期权模拟接口，过10分钟后会出现 pythonw.exe 已停止工作， 
问题事件名称:	APPCRASH
  应用程序名:	pythonw.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5914b681
  故障模块名称:	DFITCSECMdApi.dll

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![appcrash](https://user-images.githubusercontent.com/1774378/37186439-7c5174e4-2380-11e8-91e2-0c411fbb6156.png)

**Comment by 10pem** [comment]
我两台win7上的程序是同时崩掉的, win10上的崩掉时间还不一样

**Comment by vnpy** [comment]
请尝试用python在cmd里运行，不要用pythonw，崩溃后截图cmd中的错误输出。
