### ISSUE TITLE
optionMaster 持仓数据不能显示

### ISSUE THREAD

**Issue by gjtrader** [vnpy/vnpy#776]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

bug

## 预期程序行为

手动交易界面能正常显示持仓数据，交易所编码柜台未能正常传送

## 实际程序行为

手动交易界面不能正常显示持仓数据

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
会来尽快修复

**Comment by Gwill** [comment]
我也发现了这个问题，而且手动下单的持仓信息中，持仓盈亏一直为0
我用的是银河 sec 的仿真账号

**Comment by vnpy** [comment]
飞创证券接口不提供持仓盈亏数据，所以显示为0
