### ISSUE TITLE
optionMaster 持仓 delta 计算错误

### ISSUE THREAD

**Issue by gjtrader** [vnpy/vnpy#777]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

bug

## 预期程序行为

希腊值监控界面 标的 delta 计算错误， 总 delta 计算错误

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
1. 请确保设置了定价波动率曲线，否则无法计算希腊值
2. 连接接口后请等待持仓信息刷出，再启动OptionMaster，否则无法加载持仓数据用于初始化
