### ISSUE TITLE
vnpy1.8 linux

### ISSUE THREAD

**Issue by Tilyp** [vnpy/vnpy#779]
严格按照教程来装的

root@vnpy:~/vnpy-1.8/examples/VnTrader# python run.py 
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 57, in main
    me.addGateway(xtpGateway)
NameError: global name 'xtpGateway' is not defined

**Comment by vnpy** [comment]
一个安装bug，请使用最新的dev分支试试吧，v1.8.1会修复掉

**Comment by iggyavocado** [comment]
@vnpy  怎么使用dev分支

**Comment by vnpy** [comment]
就直接在Github仓库页面选择dev分支，然后下载

**Comment by faithgithub** [comment]
使用dev分支还是不行

**Comment by songhanjie** [comment]
不要在root下安装。建议试试。
