### ISSUE TITLE
银河飞创 SEC API 仿真账号 tick 数据频率特别低

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#781]
## 环境

* 操作系统: Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.0发行版

## Issue类型
Question

## 预期程序行为
tick 数据更新评率 < 1秒

## 实际程序行为
tick 数据更新频率为 5-10 秒

## 重现步骤
使用仿真账号登录，开启optionMaster，观察50ETF相关期权合约数据变动

**Comment by vnpy** [comment]
仿真环境数据少是正常情况
