### ISSUE TITLE
vnpy.trader.app.optionMaster.strategy.DemoStrategy 无法停止

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#782]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.0

## Issue类型
Question、Bug

## 预期程序行为
在点击gui中的策略停止之后，策略停止，onTimer 回调关闭

## 实际程序行为
在点击gui中的策略停止之后，onTimer 回调还会被定时执行

**Comment by vnpy** [comment]
停止策略后只是禁止策略发单，并不会影响回调函数的触发
