### ISSUE TITLE
optionMaster 中 demo 策略 gui 初始化点击后 inited 依然是 False

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#783]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.0

## Issue类型
Bug

## 预期程序行为
optionMaster 中 demo 策略 gui 初始化点击后 inited 为 True

## 实际程序行为
optionMaster 中 demo 策略 gui 初始化点击后 inited 依然是 False

## 重现步骤
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
