### ISSUE TITLE
dataRecorder 会与 optionMaster 中的交易策略配置文件有冲突

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#784]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
Bug

## 实际程序行为
同时启用 optionMaster 与 dataRecorder 后，如果项目内有 strategy_setting.json 文件（给optionMaster配置交易策略用，按照 example 中的范例编写），dataRecorder 会配置加载错误。
大概是因为 dataRecorder 用到了 ctaStrategy 里的东西，ctaStrategy 会尝试加载 strategy_setting.json 所以导致错误

**Comment by vnpy** [comment]
请发一下加载错误的截图

**Comment by Gwill** [comment]
<img width="683" alt="2018-03-16 3 22 35" src="https://user-images.githubusercontent.com/692980/37508459-1ed44de2-292e-11e8-8300-a8e6817ed21c.png">

**Comment by vnpy** [comment]
为啥你的loadStrategyModule会去加载一个json文件。。。你在CTA_setting.json里写了这个strategy_setting.json吗？

**Comment by Gwill** [comment]
这个项目中没有 CTA_setting.json 文件

**Comment by Gwill** [comment]
也没有引用 trade.app.ctaStrategy ，应该是 dataRecorder 里引起的

**Comment by vnpy** [comment]
因为json名称中含有strategy字符串导致的错误，已经限制只允许加载.py结尾的策略文件
