### ISSUE TITLE
TushareDataService文件夹中文件dataService.py 中bar 参数错误，修改后报行情服务连接为空，

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy#785]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug

## 预期程序行为
下载A股一份bar数据

## 实际程序行为
文件dataService.py 中bar 参数错误ktype='1min'，应该时freq='1m'，修改后报行情服务连接为空;。
建议同样数据源的quantOS数据已经提供，可以删除这个Tushare的。

## 重现步骤

def downMinuteBarBySymbol(symbol):
    """下载某一合约的分钟线数据"""
    start = time()

    cl = db[symbol]
    cl.ensure_index([('datetime', ASCENDING)], unique=True)         # 添加索引
    
    df = ts.bar(symbol, **ktype='1min**')
    df = df.sort_index()

**Comment by vnpy** [comment]
OK，回头来修复

**Comment by vnpy** [comment]
已修复
