### ISSUE TITLE
PositionDetail中calculatePrice关于持仓均价问题 Question

### ISSUE THREAD

**Issue by lajor2010** [vnpy/vnpy#786]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版

## Issue类型
三选一：Question

    def calculatePrice(self, trade):
        """计算持仓均价（基于成交数据）"""
        # 只有开仓会影响持仓均价
        if trade.offset == OFFSET_OPEN:

为什么只有开仓影响持仓均价，平仓的时候，部分平仓，其均价为什么不会受影响。
另外，全部平仓完，其均价是否也应该为0.

**Comment by vnpy** [comment]
1. 这里计算的成本，是历史开仓价格的加权平均数，所以只考虑开仓，如果考虑平仓你就必须维护FIFO的成交历史记录，而CTP并不提供这个数据查询
2. 全部平完后，价格应当为0（即没有持仓了）
