### ISSUE TITLE
vnpy-dev版本运行run.py、run_simple.py出现Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Zeongwan** [vnpy/vnpy#789]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 5.1.0 Python 2.7 64位
* vn.py版本: 如v1.8 dev branch 20180321（下载日期）

## Issue类型
Bug

## 预期程序行为
运行examples下的run_simple.py、run.py文件

## 实际程序行为
Segmentation fault (core dumped)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/14860033/37693349-0cc2b72c-2cfa-11e8-8928-557b6595fd78.png)

**Comment by vnpy** [comment]
boost安装了吗？另外你的Anaconda版本换成4.0.0的试试

**Comment by Zeongwan** [comment]
把Anaconda换到4.0.0，安装boost以后，重新安装vnpy，依旧是跑这两个文件，然后出现的错误变为`ImportError: No module named vnpy.event`，
![image](https://user-images.githubusercontent.com/14860033/37749140-89f1aef2-2dc1-11e8-9827-926bbbee30bc.png)
尝试直接去跑vnpy/events下的eventEngine.py，报错`ImportError: No module named queue`
![image](https://user-images.githubusercontent.com/14860033/37749169-b2c3ec32-2dc1-11e8-91a1-940d94107303.png)

**Comment by vnpy** [comment]
1. pip install future
2. vnpy-1.8目录下，运行bash install.sh

**Comment by Zeongwan** [comment]
目前run_simple.py运行正常，run.py运行时会出现`NameError: global name 'xtpGateway' is not defined`

应该用dev分支？还是怎么解决？
![_20180323103420](https://user-images.githubusercontent.com/14860033/37808530-c5381892-2e85-11e8-912a-56e4d72d9d98.png)

**Comment by vnpy** [comment]
1. 可以用dev
2. 或者移除掉run.py里的xtpGateway相关代码就行

**Comment by Gwill** [comment]
@Zeongwan 一些 api gateway 不支持 linux 的，还是得用回 win7 :joy:  ，可以 close issue 了

**Comment by shupan** [comment]
这个还存在。 我下周vnpy-1.8和vnpy-1.9都存在， 是否1G的内存就安装不了？
![image](https://user-images.githubusercontent.com/9160070/45913552-32eb7200-be67-11e8-985e-fd400325e3d8.png)

**Comment by vnpy** [comment]
1G内存太小了，估计连CTP的API编译都搞不定，除非你会设置交换区
