### ISSUE TITLE
vnpy基于源码二次开发的规范建议

### ISSUE THREAD

**Issue by lamter** [vnpy/vnpy#791]
目前碰到二次开发比较烦恼的问题就是，二次开发跟随vnpy源码升级时，代码合并的问题。如果二次在源码上直接进行更改，那么想合并vnpy新的版本进来时常常会碰到大量的代码冲突，甚至可能会造成隐藏的BUG。如果规范一下二次开发的话，会好非常多。

目前我尝试的方法是，源码作为父类，二次开发从父类继承后改动。以下是我建议的二次开发规范：
1. 对于`vtEngine.py`中的 `MainEngine`类，是源码的内容。项目中任何地方都不直接使用这个类。
2. 有`svtEngine.py`文件，中也有类`MainEngine`，继承自`vtEngin.py`。初始状态，没有除了继承之外的任何内容，二次开发在此进行。项目中所有地方直接使用这个文件里的类。
3. 对于其他源码中的类采用同样的规则。

我认为这样可以有效降低二次开发升级版本的难度。实现该规范，需要对其中主要的类的`.py`文件引用进行更改。

**Comment by vnpy** [comment]
非常好的建议，本来也计划在2.0中做个解耦和更全面的框架化设计

**Comment by delonzhou** [comment]
嗯，我也是完全通过继承的方案做的二次开发，不直接修改vnpy库的任何一行代码。
