### ISSUE TITLE
QuantOS下载的数据vtSymbol都是带交易所简称的，vnpy运行时策略读不到数据

### ISSUE THREAD

**Issue by huxunya** [vnpy/vnpy#792]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.7.3dev 

## Issue类型
三选一：Bug

## 实际程序行为
最近更新了天勤客户端就下载不了数据了，而从QuantOS下载的数据vtSymbol都是带交易所简称的（例如i1805.DCE），vnpy运行读不到这种数据。

**Comment by vnpy** [comment]
OK，会尽快修复

**Comment by vnpy** [comment]
已修复
