### ISSUE TITLE
使用自带天勤数据解决方案更新历史数据

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#793]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7.2

## Issue类型
三选一：Bug

## 预期程序行为
按wiki教程使用天勤历史数据解决方案，下载了天勤客户端，配置了需下载的品种

## 实际程序行为
![qq 20180321205009](https://user-images.githubusercontent.com/35967505/37710951-369af3d4-2d4a-11e8-9007-9fccfff5d976.png)

运行后，界面一直卡在“开始下载合约分钟线数据”，等待很久程序都不能完成，也未实现数据导入。

**Comment by vnpy** [comment]
天勤最近在升级他们的客户端，可能API过段时间会升级
