### ISSUE TITLE
使用 optionMaster 持仓数据展示异常

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#798]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev 分支

## Issue类型
Bug

## 说明

使用了银行证券的飞创 SEC 的仿真账户

只开启了 SEC gateway，app 只开启了 riskManager 与 optionMaster

手动进行几笔交易以后，界面显示下列图

主界面：

<img width="1677" alt="2018-03-27 1 58 46" src="https://user-images.githubusercontent.com/692980/37962424-a264e10e-31ed-11e8-8385-1a0b2c047898.png">

持仓数据盈亏指标一直为0

手动交易界面：

<img width="909" alt="2018-03-27 2 08 24" src="https://user-images.githubusercontent.com/692980/37962454-bb5b8262-31ed-11e8-8adc-364243ac070f.png">

## 另外：

希腊字母界面指标全是零：

<img width="1675" alt="2018-03-27 1 58 27" src="https://user-images.githubusercontent.com/692980/37962487-d2c608e6-31ed-11e8-9a66-4bc32045e0f2.png">

**Comment by vnpy** [comment]
请在主界面MainWindow中的持仓信息刷新出来后，再打开OptionMaster的组件，应该就能看到持仓了。

**Comment by Gwill** [comment]
@vnpy 
主页面的持仓信息可以刷出来，但是数据展示有问题：

![image](https://user-images.githubusercontent.com/692980/38003837-fe4441a8-326b-11e8-9c28-d87a06802e6f.png)

昨持仓、冻结量都没有数据，持仓盈亏一直是 0 。

主要是这个问题。

**Comment by Gwill** [comment]
@vnpy  这个问题和 飞创 SEC API 接口有关吗？
如果想协助修改这块，大致方法是？我想研究一下，帮忙维护

**Comment by vnpy** [comment]
看了下sec接口没有持仓盈亏的数据
