### ISSUE TITLE
simNow的CTP接口手动平今后Position数值错误

### ISSUE THREAD

**Issue by lamter** [vnpy/vnpy#800]
## 环境

* 操作系统: Docker 中 Ubuntu 16.04 
* Anaconda版本: Miniconda  Python 2.7.14 
* vn.py版本: 如v1.7 dev HASH: e3598be7e06cf7e2ff9c9d3196b301f85f91d8bd

## Issue类型
Bug

## 预期程序行为
使用`simNow`接口jd1805合约，当前持仓-19。在手动平仓10手后，预期`position`对象数值应该为
```python
shortPos==9
shortTd==9
shortPosFrozen==0
shortTdFrozen==0
```

## 实际程序行为
使用`simNow`接口jd1805合约，当前持仓-19。在手动平仓10手后，`position`对象数值维持在
```python
shortPos==9
shortTd==9
shortPosFrozen==10
shortTdFrozen==10
```
重启`vnpy`后，恢复预期数值。

## 重现步骤
使用`vnpy`先开仓-10手，再开仓-9手，均为今仓。在`tradeNow`客户端中平今10手。**可能**会出现BUG状况。该BUG并不是必现，也可能跟`simNow`本身的数据异常有关。

**Comment by vnpy** [comment]
出现这种情况应该是由于没有收到平仓委托的全部成交推送，可能由于委托尚未成交或者SimNow服务器问题
