### ISSUE TITLE
怎样才能判断策略是否在运行，以系统自带的bollchannel策略为例

### ISSUE THREAD

**Issue by GGZNZ** [vnpy/vnpy#802]
## 环境

* 操作系统: 如Windows 8
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8发行版d

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
我把strategy目录下的bollchannel策略做了简单修改，比如改了className为自己起的名字，initdays 改成了8. 增加一个变量zoutput之类。
    className = 'BollChannelHuigeStrategy'
    author = u'Hg180328'
    initDays = 8     
    zoutput = 0    
以及把k线周期改成1分钟。
def __init__(self, ctaEngine, setting):
        """Constructor"""
        super(BollChannelHuigeStrategy, self).__init__(ctaEngine, setting)
        
        self.bg = BarGenerator(self.onBar, 1, self.onXminBar)        #

=*************==
加载后，显示，修改过的策略完成了初始化，和启动。 

## 实际程序行为
但是，进过一段时间以后，没有任何发单，以及，CTA页面，各个指标的输出仍然是0.

请问，这时候，策略在运行没有，怎么才能判断它在工作与否？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by BillyZhangGuoping** [comment]
![image](https://user-images.githubusercontent.com/23182421/38190106-5eb92878-3695-11e8-8f5c-0fc158c7392c.png)
注意看看这几点变量是否由更新，
因为初始化数据所有天数8天，是否这个数据还没有到，可以通过QuantOS，先下载历史数据，然后在运行
