### ISSUE TITLE
IB对接的问题

### ISSUE THREAD

**Issue by zhu4ling3** [vnpy/vnpy#806]
## 环境

* 操作系统: Ubuntu 16.04 amd64
* Anaconda版本: Anaconda 4.0.0 Python 2.7 **64位**
* vn.py版本: v1.8发行版）
* 开发IDE Pycharm2018.1社区版
* IB Gateway Version 970.1b版

## Issue类型
三选一：Question

## 问题现象
 在ubuntu下面建立的开发环境。具体环境如上所属。
目的是利用vnpy来和IB平台对接，进行策略研究。
#### （2）运行dataRecord时出席问题。详述如下：
- 自行修改runDataRecording.py 中早盘晚盘时间，让程序可以跑起来。（服务器在国外，美国时区）
- 修改DR_setting.json，如下：
```
{
    "working": true,
    "tick":
    [
        ["777", "IB", "SMART", "HKD", "STK"]
    ],
    "bar":
    [
        ["777", "IB", "SMART", "HKD", "STK"]
    ]
}

```
#### （3）通过IDE的调试模式，发现在执行完ibGateway.py->connect()->self.api.eConnect()语句没有问题，执行下一句self.api.reqCurrentTime()时报错。错误信息为：
```
错误代码：321，错误信息：Error validating request:-'bE' : cause - Please enter a valid security type
错误代码：321，错误信息：Error validating request:-'bK' : cause - Please enter a valid security type
```

#### （2）在IB Gateway一侧采集到LOG，如下：
```
3:57:54:235 -> ---54-1-DU5xxxxx-
03:57:54:235 <- 9-8-1-0----0---SMART--HKD-777--0---
03:57:54:235 -> ---V4-2-1-321-Error validating request:-'bE' : cause - Please enter a valid security type-
03:57:54:236 <- 1-11-2-0----0---SMART--HKD-777--0--0--
03:57:54:237 -> ---V4-2-2-321-Error validating request:-'bK' : cause - Please enter a valid security type-
```
第二行里面发个IB的数据包里面确实没有资产类型，但是在DR_setting.json中设置了资产类型为“STK"，对应subscribeReq.productClass。好像这个数据没有传过去给IB G/W。

### 请问（1）subscribeReq是在什么时候发送给IB的？（2）这个时间点上面，有几个工作线程？线程之间的工作时序时怎样的？

# 补充：IB报错的问题刚才自行解决了。是DR_setting.json中的配置没有写对，要按照constant.py中的定义来写。但是，上面两个疑问还是希望可以得到解答。谢谢！

**Comment by vnpy** [comment]
1. 接口API的回调函数是在C++中触发的，无法在Python中加断点
2. 工作线程在C++中有三个：请求发送、回报读取、Python推送
