### ISSUE TITLE
python2 升级到3

### ISSUE THREAD

**Issue by psikharpax** [vnpy/vnpy#807]
请问作者有升级到python 3 的计划吗？很多库会慢慢停止对python 2 的支持

Python核心团队计划在2020年停止支持Python 2。NumPy项目自2010年以来一直支持Python 2和Python 3，并且发现支持Python 2对我们有限的资源增加了负担；因此，我们最终计划将停止支持Python 2。现在，我们已经进入了社区支持的Python 2的最后几年，NumPy 项目公布了它逐步淘汰 Python 2 支持的时间表，目标是帮助下游生态系统制定计划并完成过渡。
我们目前的计划如下：
到2018年12月31日为止，所有的NumPy版本都将完全支持Python2和Python3。
从2019年1月1日开始，任何新的功能版本都只支持Python3。
最后的Python2支持版本将被指定为长期支持(LTS)版本，这意味着我们将继续合并bug修复，并使bug修复版本比平常更长。具体来说，它将在2019年12月31日前得到社区的支持。
在2020年1月1日，我们将结束对Python2支持版本最后的社区支持。然而，PyPI将会无限期地使用它，如果任何商业供应商希望将延长对LTS的支持，那么，我们将允许他们在官方NumPy存储库中使用LTS分支来协调它。

**Comment by vnpy** [comment]
年底会开始启动对3的升级
