### ISSUE TITLE
能否考虑增加条件单管理？

### ISSUE THREAD

**Issue by szsa** [vnpy/vnpy#808]
比如，能够查询当前所有有效的策略生成的条件单状态，其实就是类似专门的管理下单的组件，策略或者手动给出的指令，该组件维护并监控行情，根据实际发出到期货公司
还有就是增加手动挂条件单的接口安排
不知道是否合适，谢谢

**Comment by vnpy** [comment]
v1.9中计划增加算法交易模块来实现该功能

**Comment by vnpy** [comment]
已完成。
