### ISSUE TITLE
策略文件里面print信息没有输出

### ISSUE THREAD

**Issue by mrleex** [vnpy/vnpy#809]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8发行版

## Issue类型
三选一：Question

## 重现步骤

想一步一步的调试策略，比如在进行每次order的时候能打印出order详细信息。但是我在策略文件里面print相关信息，在pycharm里面运行的时候，根本不会打印任何信息，依然只有回测策略的那一点输出，请问如何才能调试策略呢，希望能直接print出来，谢谢

**Comment by vnpy** [comment]
请确保修改的是Anaconda目录site-packages目录下的vnpy里的代码，而不是解压目录的

**Comment by mrleex** [comment]
@vnpy 我修改的是解压目录。。原来如此，谢谢~
