### ISSUE TITLE
Tick行情数据记录 逻辑错误

### ISSUE THREAD

**Issue by qzbysh** [vnpy/vnpy#81]
1.在开启 行情数据记录后，非交易时段登陆CTP，订阅成功返回的数据为0的Tick，会被记录到数据库中。

看行情处理代码发现函数 drEngine.procecssTickEvent，没有对Tick进行过滤，现在不知道是在函数 drEngine.procecssTickEvent中对H L O C全0的数据进行过滤还是在其它位置修改会好一点。

2.每次 集合竞价 会多记录一条一分钟的数据(20:59~21:00)。我的本机时间好像慢一秒，请忽略.
20:58:59	记录Tick数据rb1701，时间:20:59:11.0, last:2050.0, bid:2050.0, ask:2054.0
20:58:59	记录分钟线数据rb1701，时间:19:37:29.0, O:2061.0, H:2061.0, L:2061.0, C:2061.0
20:59:59	记录Tick数据rb1701，时间:21:00:11.0, last:2055.0, bid:2055.0, ask:2057.0
20:59:59	记录分钟线数据rb1701，时间:20:59:11.0, O:2050.0, H:2050.0, L:2050.0, C:2050.0
21:00:00	记录Tick数据rb1701，时间:21:00:11.5, last:2057.0, bid:2055.0, ask:2058.0
21:00:00	记录Tick数据rb1701，时间:21:00:12.0, last:2054.0, bid:2054.0, ask:2056.0
21:00:00	记录Tick数据rb1701，时间:21:00:12.5, last:2057.0, bid:2055.0, ask:2060.0

**Comment by vnpy** [comment]
这个是数据质量的问题，各家交易所、各家的柜台、或者数据提供商都会有所区别，我建议自行处理，毕竟每个人的方案可能有所区别。如果方便能否请你总结个发现的规律发在这里或者群里，让其他有相同问题的人可以借鉴。

**Comment by qzbysh** [comment]
好的，谢谢
其它的交易接口没有测试不太清楚，只做了CTP的。
至于规律其实也只有两条
1.在非交易时间段登陆订阅行情，会返回一条Tick信息，需要按需处理。
2.在集合竞价时段，接受的集合竞价Tick信息，需要和一分钟后的Tick信息合并处理为第一根K线的开盘价。
