### ISSUE TITLE
安装说明是否应该更新

### ISSUE THREAD

**Issue by yurenji** [vnpy/vnpy#810]
<img width="878" alt="2018-04-08 21 21 10" src="https://user-images.githubusercontent.com/5565266/38468108-1a57564e-3b74-11e8-8aa7-9ea78661e693.png">

安装说明中提到，“Anaconda必须是Python 2.7 32位版本“。现在的机器大部分都是64位，不知道有什么特殊原因，安装的版本必须是32位？ 

安装python-snappy，默认的“pip install python_snappy-0.5.1-cp27-cp27m-win32.whl”也是32位。 

如果这个安装说明只是作者一个人的配置，建议加上说明，不然很容易产生误导。

**Comment by Gwill** [comment]
事实上在 windows 系统中你需要这样安装，建议 close 掉这个 issue

**Comment by yurenji** [comment]
可以解释一下为什么吗？ 

Anaconda不太确定，但是snappy我无法安装win32版本，重新下载了64位才可以安装。

**Comment by vnpy** [comment]
自动安装脚本可以一次性解决，过程中有下载问题的话建议翻墙
