### ISSUE TITLE
simnow无法注册

### ISSUE THREAD

**Issue by yurenji** [vnpy/vnpy#811]
issue type: question 

QuickStart里面提到在SimNow注册CTP仿真账号，并提供了链接。但是http://simnow.com.cn/ 貌似已经无法访问了，链接分享给了几个朋友也无法打开。 

不知道是不是只有我一个人遇到这个问题？  有没有替代的方案呢？

**Comment by yurenji** [comment]
又可以登录了，貌似是暂时服务器down了.

**Comment by wmltyq** [comment]
SimNow官网相当不稳定呀，就第一次可以访问，现在一直无法访问了。
