### ISSUE TITLE
交易合约无法找到

### ISSUE THREAD

**Issue by tubu** [vnpy/vnpy#813]
![3e64a243-a625-4e5a-9e8c-4b49ceb9720b](https://user-images.githubusercontent.com/973267/38538799-f1e6ed0a-3cc7-11e8-83a6-f78e820263ed.png)

在目录vnpy/examples/CtaTrading下执行
python runCtaTrading.py

配置应该是没有问题，同样的配置在DataRecord下是可以执行存储数据的。
版本1.8

**Comment by vnpy** [comment]
你的环境好像初始化有点问题，去VnTrader目录下执行run.py，然后复制contractData.vt过来。

**Comment by BillyZhangGuoping** [comment]
rb1810,  是小写；I1809，i也是小写
