### ISSUE TITLE
富途证券怎么配置那里有教程啊

### ISSUE THREAD

**Issue by eyelivermore** [vnpy/vnpy#814]
## 环境

* 操作系统: 如Windows 10 64
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8发行版

富途证券怎么配置有文档吗?一连接就 未响应

**Comment by vnpy** [comment]
1. 加入富途API群
2. 下载API版的富途牛牛
3. 启动牛牛
4. vn.py里连接
