### ISSUE TITLE
optionMaster 使用南华证券期权仿真CTP接口无法获得数据

### ISSUE THREAD

**Issue by Gwill** [vnpy/vnpy#815]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本:  dev 分支

## Issue类型
Bug

## 预期程序行为
正常获取数据

## 实际程序行为
![image](https://user-images.githubusercontent.com/692980/38654702-43f502f4-3e43-11e8-8b17-669b0040cc42.png)

**Comment by vnpy** [comment]
从日志看：
1. 行情服务器登录失败
2. 你没有连接CTP证券（用来获取50ETF行情）
