### ISSUE TITLE
策略文件加载问题

### ISSUE THREAD

**Issue by KimChow** [vnpy/vnpy#827]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Bug
## 预期程序行为
在vnpy的工作目录有strategy相关的名字会导致程序报错

## 实际程序行为
策略加载时，应该不去加载除了py以外的文件

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
随便起一个文件名为strategy_11.csv之类的，程序就会报错。

**Comment by iole05dix** [comment]
"警告 ctastrategy/var接口报错"

**Comment by vnpy** [comment]
已修复
