### ISSUE TITLE
行情数据不能被订阅？ 数据没有显示？

### ISSUE THREAD

**Issue by VincentYanJk** [vnpy/vnpy#829]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug

## 预期程序行为
连接CTP 成功， 连接MongoDB 成功， 搜索合约代码，例如IH1804 按下回车以后，名字 也可以被搜索到， 右边的行情数据应该显示出来。 

## 实际程序行为
合约代码的名字显示出来， 但是右边的行情界面没有数据。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![capture1](https://user-images.githubusercontent.com/13777038/39035616-45374922-44ad-11e8-9e42-b4ef3f742007.PNG)
![capture2](https://user-images.githubusercontent.com/13777038/39035617-457b68a0-44ad-11e8-9b1f-7b4b631d8437.PNG)
![capture3](https://user-images.githubusercontent.com/13777038/39035619-45bb2440-44ad-11e8-980d-5c2333f95149.PNG)
![capture4](https://user-images.githubusercontent.com/13777038/39035621-45fdf84c-44ad-11e8-89cc-3a4b2b46cc03.PNG)

**Comment by vnpy** [comment]
IH1804合约已经到期，试试1805吧

**Comment by VincentYanJk** [comment]
谢谢您的及时回复。 我刚刚试过了。 依然一样的。 您能帮忙看一下吗？ 没有任何拨错信息。 

![capture5](https://user-images.githubusercontent.com/13777038/39162945-bdaba6e6-47aa-11e8-9f14-ecb2d058a2fd.PNG)

**Comment by VincentYanJk** [comment]
谢谢您的及时回复。我重新搜索了一下 IH1805 ，还是没有数据。 合约名称可以自动搜索到。
您还有其他的建议吗？ 

![capture5](https://user-images.githubusercontent.com/13777038/39163018-211b53ac-47ab-11e8-9204-559ce080b45f.PNG)

**Comment by BillyZhangGuoping** [comment]
行情服务器地址检查下

**Comment by VincentYanJk** [comment]
谢谢你的回答。 行情服务地址已经 贴上去了。 如果行情地址不对的话，  我的CTP 虚拟账户的信息是不能拿到的。

**Comment by vnpy** [comment]
http://www.simnow.com.cn/product.action

试试其他组的服务器

**Comment by VincentYanJk** [comment]
不好意思 我刚刚看到了您的回复。 我按照http://www.simnow.com.cn/product.action 试了其他的服务器 结果还是一样。  您有其他的建议吗？ 18301579750 这是我的电话

**Comment by VincentYanJk** [comment]
您好， 我今天debug了一下CTP连接的程序， 发现了问题， 每次都是交易服务器连接成功，但是行情服务器连接不成功。  我把我用的CTP的服务器地址贴上去了。您能给我一些建议吗？ 万分感谢

![image](https://user-images.githubusercontent.com/13777038/39510281-cb92747a-4e1b-11e8-93d7-fb224a2dfde1.png)
![image](https://user-images.githubusercontent.com/13777038/39510309-dfc11de8-4e1b-11e8-8e1d-8240c4c9dcf8.png)
![image](https://user-images.githubusercontent.com/13777038/39510374-1c0a7a1a-4e1c-11e8-86c2-d86ef172b0df.png)

**Comment by vnpy** [comment]
账号密码上看不出什么问题，如果一直都是行情服务器连不上我建议换台机器在不同网络试试
