### ISSUE TITLE
回测引擎，不支持需要读取MongoDB的策略

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#83]
有部分策略需要需要调用loadBar、loadTick等函数，这些函数需要self.vtSymbol，
但是BacktestingEngine引擎中初始化策略时并没有获取vtSymbol，
看到ctaEngine是通过loadSetting函数实现的，
是不是BacktestingEngine中也需要loadSetting函数？
我个人是用简单的  engine.strategy.vtSymbol = 'pp_hot' 实现。

**Comment by vnpy** [comment]
不用的，在初始化策略initStrategy的时候，传入的第二个参数就是策略的setting字典（如果不传就会使用策略的默认参数），然后加载回测数据时需要用户传入合约代码（对应MongoDB中的collection名称），所以无需loadSetting。

**Comment by freeitaly** [comment]
问题解决，谢谢群主！
