### ISSUE TITLE
撤单操作会触发一个未成交状态的Onorder事件回报！

### ISSUE THREAD

**Issue by stardna** [vnpy/vnpy#831]
## 环境

* 操作系统: Windows 7 64位
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8发行版

## Issue类型
三选一：Bug

## 预期程序行为
在Onorder里执行撤单操作，应该不会接收到未成交的回报！

## 实际程序行为
在Onorder里执行撤单操作，会接收到一个未成交的回报和一个已撤销的回报！这个未成交状态导致会再次执行cancelOrder撤单操作！

## 重现步骤
测试代码如下：
    def onOrder(self, order):
        """收到委托变化推送（必须由用户继承实现）"""
        print u'OnOrder.. {} '.format(order.status)
        if order.status == STATUS_NOTTRADED or order.status == STATUS_PARTTRADED:
            self.cancelOrder(order.vtOrderID)
            print (u"未成或部成开始撤单..")

打印结果如下：
未成或部成开始撤单..
OnOrder.. 未成交
未成或部成开始撤单..
OnOrder.. 已撤销

完整的测试流程是发送一个未成交的委托单，然后会执行撤单操作，整个这个流程的Onorder回报会被触发4次，依次是，1.未知，2.未成交，3.未成交，4.已撤销。
这个未成交状态会产生歧义的，是挂单的未成交还是其他？以为order.status里只有这个字段记录了状态！

**Comment by vnpy** [comment]
用的是SimNow还是实盘环境？

**Comment by stardna** [comment]
用的是simnow，simnow有这错误？我改天用实盘试试吧！
另外重复撤单虽然对账户没有影响，但是假如实盘也出现这个问题，还是请群主改一下吧！毕竟会影响有些功能的实现！

**Comment by stardna** [comment]
我查了一下代码，发现processTradeEvent里有一段代码，是过滤已经收到的成交回报，但是在processOrderEvent里没有，是不是群主忘写了？加上是不是就能解决上述问题？
        # 过滤已经收到过的成交回报
        if trade.vtTradeID in self.tradeSet:
            return
        self.tradeSet.add(trade.vtTradeID)

**Comment by bigdig** [comment]
> 这里没有群主，上面的代码可能无法解决你的问题

- 因为您的问题不是问题，是正常的定单回报显示。
- CTP一个定单逻辑上就有两个回报：分别是发单的回报，报单结果的回报。

**Comment by stardna** [comment]
谢谢您，两个回报我明白，但是肯定是有状态能区分的出来的，现在的问题是，这两个订单的order.status都是未成交！

**Comment by bigdig** [comment]
> 报单的问题细想极其恐怖，

你收到的 未知、**未成交、未成交**、已取消，问题在于 取到的都是 order.status，其实应综合 OrderSubmitStatus 来判断。但VPNY CTP Gateway好象没有处理这个状态，这个状态也只有象您这样进行精细报单控制才会用到

**Comment by bigdig** [comment]
报单是个大体力活，很难进行全面的封装。量化策略下单大多以对价成交为主，这样简单的封装基本就够用了

**Comment by vnpy** [comment]
同意楼上得自己结合submitStatus字段来修改底层接口增加状态了
