### ISSUE TITLE
runDataRecording.py运行失败

### ISSUE THREAD

**Issue by mathprophet** [vnpy/vnpy#832]
## 环境
* vn.py版本: 1.8 master branch

## Issue类型
三选一：Bug

## 预期程序行为
python runDataRecording.py
执行后直接报语法错，发现是drEngine.py文件第249行：
self.writeDrLog(u'键值重复插入失败，报错信息：' %traceback.format_exc())
改为：
self.writeDrLog(u'键值重复插入失败，报错信息：%s' %traceback.format_exc())
即可。

**Comment by vnpy** [comment]
已修复
