### ISSUE TITLE
无界面运行问题

### ISSUE THREAD

**Issue by rhermit** [vnpy/vnpy#833]
## 环境

* 操作系统: 本地电脑Windows 7， 云端也是Windows，2012版本的

* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8

## Issue类型
三选一：Question

## 预期程序行为
同一策略，无界面和有界面的运行效果应该是一致的

## 实际程序行为
[同一策略，有界面运行正常，无界面无法平今，另外，平仓委托单子无法进入委托界面

## 重现步骤
详情请见下面文档

**Comment by rhermit** [comment]
[无界面相关问题.docx](https://github.com/vnpy/vnpy/files/1941789/default.docx)

**Comment by bigdig** [comment]
vnpy不仅需要持仓信息，还需要Contract信息，这些信息程序退出时应当在本地进行缓存。我的做法是，程充启动后就进行一次缓存，Exit时再更新一次

**Comment by vnpy** [comment]
1. 增加无界面模式下，启动CTA策略引擎前保存合约数据到硬盘的逻辑
2. 自动委托转换功能，需要获取合约数据来判断是否为上期所
3. 大部分情况下，登录CTP后会立即查询合约数据，后续有持仓更新可以正常计算
4. 若日内已有交易，此时重启系统之前的委托和成交会先于合约数据查询结果到达，那就需要加载本地之前缓存的合约数据来防止找不到合约的情况
