### ISSUE TITLE
simnow账号在非交易时间不能登录吗？

### ISSUE THREAD

**Issue by sidneyzhu** [vnpy/vnpy#834]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 最新版

## Issue类型
Question

## 预期程序行为
simnow账号在tradenow上登录成功

## 实际程序行为

tradenoew上提示连接服务器超时，用wifi和4G都不行。登录时间是下午17点43,
是不是非交易时间不能登录？
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by BillyZhangGuoping** [comment]
可以登录，没有返回市场信息，你看看登录地址是不是写错了。

**Comment by sidneyzhu** [comment]
![tradenow](https://user-images.githubusercontent.com/5105369/39185363-8d2e8da4-47f9-11e8-8521-531fa56480c0.jpg)
这上面的会员设置选什么？

**Comment by sun0x00** [comment]
Simnow每天下午16点之20点之前都会做结算，一般连不上，而且Simnow经常故障，属于常态。无特别情况下，请使用Broker 9999
