### ISSUE TITLE
登录失败？

### ISSUE THREAD

**Issue by sidneyzhu** [vnpy/vnpy#835]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 最新

## Issue类型
Question

## 预期程序行为
界面能搜索并显示合约信息

## 实际程序行为
启动界面无任何  **成功  的信息
搜任何合约代码，后台都是提示 “接口不存在”

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![jiekou](https://user-images.githubusercontent.com/5105369/39181023-f2ab1b98-47ea-11e8-8b36-a2ffc316ed55.png)

**Comment by sidneyzhu** [comment]
刚才在simnow官网上验证了账号密码是对的，为什么vntrader总是提示 接口不存在？

**Comment by vnpy** [comment]
请先连接CTP接口再订阅行情或者发单

**Comment by sidneyzhu** [comment]
![default](https://user-images.githubusercontent.com/5105369/39467903-061a2be2-4d63-11e8-9f5b-5ad3b8f70e8d.png)
为什么连接成后，立马又断开了？
我的服务器配置是：
    "brokerID": "9999", 
    "mdAddress": "tcp://218.202.237.33:10012", 
    "tdAddress": "tcp://218.202.237.33:10002",

**Comment by vnpy** [comment]
5点多服务器已经关了。。。
