### ISSUE TITLE
ctaEngine中callStrategyFunc函数处理参数为0的问题

### ISSUE THREAD

**Issue by smartgang** [vnpy/vnpy#837]
## 环境
* vn.py版本: 如v1.8

## 预期程序行为
    def callStrategyFunc(self, strategy, func, params=None):
        """调用策略的函数，若触发异常则捕捉"""
        try:
            if params :
                func(params)
            else:
                func()
如果想传递一下参数为0的int数（或者空字符），这里if params的判断是False，会调用func()，与本意不符。
建议修改为 if not (params is None):
这样就可以保留本意地传递参数过去。

**Comment by vnpy** [comment]
所有对callStrategyFunc的调用不是传空就是传数据对象，不存在0或者空字符的情况
