### ISSUE TITLE
跑回测正常但在实盘中平仓指令变成了开仓指令

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#840]
## 环境

* 操作系统: 如Windows servers 2008
* Anaconda版本: Anaconda 4.0.1 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型
三选一：Bug

## 预期程序行为
策略设置固定持仓1分钟后平仓，回测成交明细正常。
![3](https://user-images.githubusercontent.com/35967505/39501783-636aa196-4def-11e8-8798-c16757c3beb4.png)

## 实际程序行为
但是实盘中，1分钟后发出的并不是平仓指令，而是开仓指令，这样就多了一个反向的仓位。不知道问题出在哪里？
![1](https://user-images.githubusercontent.com/35967505/39501724-145fee30-4def-11e8-9482-d3673647c08b.png)
![2](https://user-images.githubusercontent.com/35967505/39501726-16ca3cb6-4def-11e8-941e-cd9433efa1b3.png)

**Comment by bigdig** [comment]
栓查下是否是做了定单转换？

**Comment by unlimitnight0** [comment]
确系订单转换问题，已修改，谢谢
