### ISSUE TITLE
交易服务器登录异常

### ISSUE THREAD

**Issue by sidneyzhu** [vnpy/vnpy#841]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev branch 20180423

## Issue类型
Question

## 预期程序行为
输入合约编号后有行情数据

## 实际程序行为
无任何行情，只提示
“行情服务器连接成功“
“交易服务器连接成功“
“行情服务器登录完成“
”接口不存在”

是不是少了“交易服务器登录完成” ？
我配置的账号在simnow的app上是可以登录的，如下图所示。
## 重现步骤

![default](https://user-images.githubusercontent.com/5105369/39503410-5ee6db68-4df8-11e8-8e09-3f5a8fb178c0.png)
![fengzhendenglu](https://user-images.githubusercontent.com/5105369/39503416-64ffa08e-4df8-11e8-9506-560e5785cf12.jpg)

**Comment by vermicelli** [comment]
![image](https://user-images.githubusercontent.com/8543293/39506632-798d08fc-4e0c-11e8-90a2-c5206e040739.png)
正常是这样的
我用的 第二组：Trade Front：180.168.146.187:10001，Market Front：180.168.146.187:10011；【电信】这个服务器。

**Comment by sidneyzhu** [comment]
谢谢，我试下你的

**Comment by sidneyzhu** [comment]
莫名其妙，自己好了
