### ISSUE TITLE
VNPY定时重连问题

### ISSUE THREAD

**Issue by rycom** [vnpy/vnpy#845]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.0

## Issue类型
三选一：Enhancement

## 预期程序行为
提供 ctpGateway disconnect函数，或VNPY关闭方法

## 实际程序行为
ctpGateway需要定时断开，定时重连。

尝试在ctpGateway下对mdApi和tdApi使用close如：
if self.tdConnected:
            self.tdApi.close()
            self.tdConnected = False
结果mdApi和tdApi使用exit（），重新连接后重建mdApi/tdApi，但原ctaEngine找不到原api，不再更新；

试过在run_simple.py 下定时关闭，但qApp.exec_一直运行，如何响应mw.close()?

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by bigdig** [comment]
逻辑上讲，断开、连接操作放到应用层比较合适

**Comment by bigdig** [comment]
在应用层添加
```java
        while True:
            #检测是否关闭DataRecord
            #Record关闭后，直到盘前进程重启才会再次打开
            if not isRecordingTime(datetime.now()):
                #避免记录无效数据
                me.getApp(dataRecorder.appName).stop()
                le.info(u'Record模块关闭成功')
                #避免发送无效数据
                me.getGateway(ctpGateway.gatewayName).close()
                le.info(u'ctpGateway模块关闭成功')

            sleep(7)
```

**Comment by rycom** [comment]
应用层没找到合适的底层接口。

需要盘后比如每天02：50， 15：20 断开ctp免得一直连接； 到8：59，20：59重新连接。不然盘后一直尝试连接ctp，到开盘时有时是假的连接状态。

现在找不到断开ctp的合适接口。

主要问题是cta，不是dataRecord；

ctaTrading只要strategy启动就会qurey ctp接口，如果调用ctpGateway的mdApi和tdApi的close函数，mdApi和tdApi就会destroy，cta无法获得event了

使用dataRecord的me.getGateway(ctpGateway.gatewayName).close()，也会导致mdApi和tdApi的destroy

**Comment by vnpy** [comment]
CTP接口的运维建议是每天下午收盘后销毁重新创建，同时最好也销毁进程重新创建，以上直接关闭退出接口的操作长期都可能导致系统异常崩溃。
