### ISSUE TITLE
群主知乎live 讲过要开发vnpy参数优化的数据内存缓存进程，不知道现在有了吗？如果有能否学习一下？

### ISSUE THREAD

**Issue by winner1986** [vnpy/vnpy#847]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已完成
