### ISSUE TITLE
策略参数initDays是自然日，修改为交易日的实现方式

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#85]
demo策略中策略初始化时，需要读取前initDays日的数据进行计算，
做策略回测时，使用initDays=5，回测到2月15日时报错，因为春节假期的原因，没有读到数据。
一年总有这两次长假期，考虑将initDays改为交易日，关于实现方式的问题请教下群主：
1. initDays赋值一个足够多的天数，然后在策略的onInit中再用实际需要的交易日数目过滤获取到的initData
2. ctaEngine中loadBar函数直接计算出实际的交易日，然后获取数据后返回initData
不知道哪种方式更好一些，谢谢

**Comment by vnpy** [comment]
建议采用1的方式，取足够多的天数，因为非交易日也没有数据，所以一般对于初始化指标计算等等并没有影响。

交易员一般选用的方式都是简单、粗暴、有效的，2虽然可能每次载入快一些，但是逻辑难写且容易出错。

**Comment by freeitaly** [comment]
谢谢，我试着改一下
