### ISSUE TITLE
使用上海中期历史数据服务，无夜盘品种的数据有问题

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#855]
使用上海中期历史数据服务更新1min，对于无夜盘的品种，如苹果，会得到一些无效的夜盘数据，见图

![qq 20180509185558](https://user-images.githubusercontent.com/35967505/39811557-a0b23362-53bb-11e8-9695-eb2b3376ead9.png)

建议在插入数据时条件判断一下当前数据的有效性

**Comment by freeitaly** [comment]
咨询过，他家数据清洗的方式是按时间对齐，考虑到一些特殊需要刻意这样设置的。
不需要的话插入数据库时筛选下。

**Comment by tanzedan** [comment]
嗯，的确，解决方法这样
更改文件 /data/shcifco/vnshcifco.py
搜索
barList.append(d)
替换成
if d['volume']!=0:
    barList.append(d)
