### ISSUE TITLE
PIP Issue

### ISSUE THREAD

**Issue by wongchunghang** [vnpy/vnpy#856]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Question

## 预期程序行为
pip install vnpy pymongo msgpack-python websocket-client qdarkstyle
This pip is not working. 

## 实际程序行为
The pip install command needs to include more package as below
pip install vnpy ipykernel pymongo msgpack-python websocket-client qdarkstyle argparse
Please update the readme.md
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cclauss** [comment]
Does __pip install -r [requirements.txt](https://github.com/vnpy/vnpy/blob/master/requirements.txt)__ work?

**Comment by wongchunghang** [comment]
I follow method 2 and did not download the requirements.txt. Suggest to enrich the method 2.
方法2

pip install vnpy pymongo msgpack-python websocket-client qdarkstyle

conda install -c quantopian ta-lib=0.4.9

**Comment by cclauss** [comment]
My recommendation would be that we abandon method 2 and recommend that users always do:
* __pip install -r [requirements.txt](https://github.com/vnpy/vnpy/blob/master/requirements.txt)__

That will be easier to document and less error prone.

**Comment by wongchunghang** [comment]
Agree. I checked method 2 still has problem on conda install ta-lib=0.4.9. Better remove method 2. On the other hands, method 1 is successfully without issue.

**Comment by vnpy** [comment]
已修改
