### ISSUE TITLE
prickTick回测实盘标准化

### ISSUE THREAD

**Issue by tanzedan** [vnpy/vnpy#859]
Enhancement

在ctaStrategy里，获取priceTick的方法在回测和实盘的环境下的代码不一致，希望能标准化一下

目前可以先这样写

>  try: 
            #实盘
            contract = self.ctaEngine.mainEngine.getContract(self.vtSymbol)
        except:
            # 回测
            contract = self.ctaEngine
        self.priceTick = contract.priceTick

**Comment by tanzedan** [comment]
目前我这段是写在strategy的init里

**Comment by vnpy** [comment]
已修改
