### ISSUE TITLE
为何日线算法测试失败？

### ISSUE THREAD

**Issue by wuyongyi** [vnpy/vnpy#860]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8（2018-05-09）

## Issue类型
三选一：question

## 预期程序行为
1，分钟级别测试KK算法正常
2，测试程序自带的strategyHaigui, strategyDoubleMa两个日级算法文件
期货1d数据从richquant导出为csv文件
执行examples/runbacktesting

## 实际程序行为
ctaBacktesting.py line 793, keyError: 'timeList'

研究发现可能是版本不兼容导致，
比如Haigui算法中有BarManager类，但是在1.8的vnpy里只有BarGenerator类

**Comment by vnpy** [comment]
1. 目前官方并未提供strategyHaigui这一策略，请检查代码来源
2. v1.8后BarManager已经改名为BarGenerator
3. timeList报错可能是因为回测时没有生成任何一笔交易，导致数据为空

**Comment by wuyongyi** [comment]
谢谢回复！
1，后来发现是typo导致的，问题已经解决，回测已经通过
2，发现一个小bug：
ctaBacktesting.py 第829行：
xindex = np.arange(0, len(tradeTimeIndex), np.int(len(tradeTimeIndex)/10))
但是如果是日线交易，有时次数小于5，那么会报被0除的错。可以改成：
if  np.int(len(tradeTimeIndex)/10) != 0: 
       xindex = np.arange(0, len(tradeTimeIndex), np.int(len(tradeTimeIndex)/10))
else:
       xindex = np.arange(0, len(tradeTimeIndex), 1)
