### ISSUE TITLE
wiki上面的图片无法展示

### ISSUE THREAD

**Issue by poloxue** [vnpy/vnpy#865]
不知道是否是个人网络问题，还是其他原因，wiki上部分文档的图片都无法显示 。

相关文档如下：
上海中期数据解决方案 https://github.com/vnpy/vnpy/wiki/%E4%B8%8A%E6%B5%B7%E4%B8%AD%E6%9C%9F%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
天勤终端数据解决方案https://github.com/vnpy/vnpy/wiki/%E5%A4%A9%E5%8B%A4%E7%BB%88%E7%AB%AF%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
应用模块GUI开发https://github.com/vnpy/vnpy/wiki/%E5%BA%94%E7%94%A8%E6%A8%A1%E5%9D%97%E5%BC%80%E5%8F%91GUI%E7%95%8C%E9%9D%A2

**Comment by vnpy** [comment]
确实是图床坏了，我来找人修复

**Comment by poloxue** [comment]
还有个问题，文档中有个链接 [天勤数据终端下载链接 ]([http://www.tq18.cn]) 地址是 https://github.com/vnpy/vnpy/www.tq18.cn，应该是写链接地址时，忘了加上协议http导致的。

**Comment by vnpy** [comment]
已经修复

**Comment by poloxue** [comment]
好像没有，天勤终端的好了，但是其他两个链接还是没有好：
上海中期数据解决方案 
https://github.com/vnpy/vnpy/wiki/%E4%B8%8A%E6%B5%B7%E4%B8%AD%E6%9C%9F%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
应用模块GUI开发https://github.com/vnpy/vnpy/wiki/%E5%BA%94%E7%94%A8%E6%A8%A1%E5%9D%97%E5%BC%80%E5%8F%91GUI%E7%95%8C%E9%9D%A2

**Comment by vnpy** [comment]
中期的也好了，请看下。

应用模块的图片还在找
