### ISSUE TITLE
策略历史持仓问题

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#87]
现在的策略 self.pos 只是它当时开仓的情况。而没办法获取历史持仓。
如果之前开的仓位，今天运行策略，它认为是0。
建议每次都会交易所获取，最少init时要从交易所获取持仓情况。

**Comment by vnpy** [comment]
这个模式是专门设计的，考虑以下几点：
1. vn.trader很多用户做的是比较高频的日内交易，收盘不会有持仓
2. 可能在某一合约上运行多个策略，因此必须每个策略管理自己的持仓情况
3. 如果要持仓隔夜，可以在策略的onStop里把持仓情况记录到数据库中，onInit时再读取出来，相关的功能函数都已经提供了

**Comment by viponedream** [comment]
万一电脑死机，重启什么的。

**Comment by vnpy** [comment]
具体的两种方案：
1. 不依赖CTA引擎维护的pos字段，自己新建一个比如myPos，然后在策略里维护持仓，这样重启时基于历史的行情数据可以算出目前的理论持仓
2. 每有一笔成交后，执行一次仓位同步，把持仓数据插入到数据库中

**Comment by viponedream** [comment]
谢谢，群主太热心了。
vtEngine.py 好像有两个地方写错了。

    #----------------------------------------------------------------------
    def qryAccount(self, gatewayName):   #原来这里好像是写错了  qryAccont
        """查询特定接口的账户"""
        if gatewayName in self.gatewayDict:
            gateway = self.gatewayDict[gatewayName]
            gateway.getAccount()
        else:
            self.writeLog(u'接口不存在：%s' %gatewayName)        
        
    #----------------------------------------------------------------------
    def qryPosition(self, gatewayName):
        """查询特定接口的持仓"""
        if gatewayName in self.gatewayDict:
            gateway = self.gatewayDict[gatewayName]
            #gateway.getPosition()   #原先的这里好像没有这个函数
            gateway.qryPosition()    # 我改成这个

**Comment by viponedream** [comment]
持仓的问题，我打算来改你原来这里。 
先发送一个请求，然后想办法把这个推送到策略去。应该 就可以了。
    #----------------------------------------------------------------------
    def processPositionEvent(self, event):
        """处理持仓推送"""
        pos = event.dict_['data']
        
        # 更新持仓缓存数据
        if pos.vtSymbol in self.tickStrategyDict:
            posBuffer = self.posBufferDict.get(pos.vtSymbol, None)
            if not posBuffer:
                posBuffer = PositionBuffer()
                posBuffer.vtSymbol = pos.vtSymbol
                self.posBufferDict[pos.vtSymbol] = posBuffer
            posBuffer.updatePositionData(pos)

**Comment by vnpy** [comment]
vtEngine那个我修复了，谢谢。

然后这个CTA里面的持仓推送，对于多个策略交易同一个合约的话，就可能造成不安全的情况，即不同策略间的持仓互相影响，所以暂时不增加到ctaEngine里了。
