### ISSUE TITLE
ImportError: No module named strategyTest

### ISSUE THREAD

**Issue by lyh404** [vnpy/vnpy#871]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.0

## Issue类型
三选一：Bug

## 预期程序行为
vnpy安装在C:\Anaconda2\lib\site-packages目录下，并且C:\Anaconda2\lib\site-packages\下有vnpy-1.8.0-py2.7.egg。
我在本地D盘新建了程序目录，如E:\vnpy-test，目录文件如下：
>vnpy-test\
>>__init__.py
>>ctaBacktesting.py
>>runBacktesting.py
>>strategy\
>>>__init__.py
>>>strategyTest.py

其中ctaBacktesting.py与安装目录下的ctaBacktesting.py内容一样，strategyTest.py是我根据样例编写的策略，运行runBacktesting.py后，先是报错：
`File "C:\Anaconda2\lib\site-packages\vnpy-1.8.0-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyTest`

然后开始载入数据、开始回测，直到跑出结果，都正常。
我的疑问是：
是不是只要跑回测，安装目录下的strategy\__init__.py都会导入strategy\下的所有策略？如果我不放在安装目录下，岂不是总是会报以上的错误？

@vnpy

**Comment by cooooo** [comment]
读一下"X:\vnpy\vnpy\trader\app\ctaStrategy\strategy\__init__.py"的代码

**Comment by vnpy** [comment]
1. ctaStrategy/strategy/__init__.py，会加载strategy目录下和当前工作目录下，所有包含strategy的.py文件中的策略对象
2. 所以如果你从vnpy.trader.app.ctaStrategy.strategy去加载任何东西的话，就有可能会倒错，但并不一定影响使用，因为你可能用不着这个策略类
