### ISSUE TITLE
onorder 和 ontrade的 race condition

### ISSUE THREAD

**Issue by rwayan** [vnpy/vnpy#872]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
由于底层接口实现不同，程序无法保证先收到OnOrder 还是 OnTrade， 在CTAengine里面对orderid的删除动作会导致后面来的ontrade逻辑无法完成，需要改在ontrade里面删除orderid ， 理论上canncel和
rejected不受影响，是否不做删除动作也正常不确定，有待进一步测试

**Comment by vnpy** [comment]
请提供下具体错误的截图。

这边检查了下，即使Order先回来，委托和策略的映射关系是通过orderStrategyDict维护的，其中内容并不会因为委托成交或者撤销发生影响。

另外目前CTP的数据推送应该是Order先于Trade到达的

**Comment by vnpy** [comment]
这个是你修改后的CtaEngine代码把，报错时候的信息是什么？？

**Comment by rwayan** [comment]
确认是OKEX的问题了
