### ISSUE TITLE
回测优化一直显示 “目标：0”

### ISSUE THREAD

**Issue by mrleex** [vnpy/vnpy#880]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
三选一：Question

## 重现步骤
策略在回测的时候能显示正常的结果，比如显示**胜率  32.27%**

但是同一个策略放到回测优化里面，同样的参数，同一个合约，将优化目标设置成胜率setting.setOptimizeTarget('winningRate')，不管什么参数组合都显示**目标：0**，类似：

参数：{'fastWindow': 10, 'profitStop': 1, 'slowWindow': 60, 'lossStop': -1}，目标：0

请教这是为什么呢？感谢~

**Comment by cooooo** [comment]
你的代码写错了，仔细检查

**Comment by vnpy** [comment]
请检查你的策略代码中，paramList添加了以上参数名。

另外回测是否跑过，有数据且结果正常

**Comment by mrleex** [comment]
@vnpy 大大，我回测跑过了，有数据而且结果正常，paramList也添加的参数。

现在我改成用自带的DoubleMaStrategy来跑回测优化，也全部显示**目标：0**

**回测代码**如下：
`
from __future__ import division

from vnpy.trader.app.ctaStrategy.ctaBacktesting import BacktestingEngine, MINUTE_DB_NAME

if __name__ == '__main__':
    from vnpy.trader.app.ctaStrategy.strategy.strategyDoubleMa import DoubleMaStrategy
    
    # 创建回测引擎
    engine = BacktestingEngine()
    
    # 设置引擎的回测模式为K线
    engine.setBacktestingMode(engine.BAR_MODE)

    # 设置回测用的数据起始日期
    engine.setStartDate('20180501')
    
    # 设置产品相关参数
    engine.setSlippage(0.2)     # 股指1跳
    engine.setRate(3/10000)     # 万0.3
    engine.setSize(100)         # 股指合约大小
    engine.setPriceTick(0.2)    # 股指最小价格变动
    
    # 设置使用的历史数据库
    engine.setDatabase(MINUTE_DB_NAME, 'HK.00700')
    
    # 在引擎中创建策略对象
    d = {}
    engine.initStrategy(DoubleMaStrategy, d)
    
    # 开始跑回测
    engine.runBacktesting()
    
    # 显示回测结果
    engine.showBacktestingResult()
    # engine.showDailyResult()`

**回测显示**：

> 2018-05-19 23:51:51.947000	开始载入数据
> 2018-05-19 23:51:51.998000	载入完成，数据量：4303
> 2018-05-19 23:51:51.998000	开始回测
> 2018-05-19 23:51:52.036000	策略初始化完成
> 2018-05-19 23:51:52.036000	策略启动完成
> 2018-05-19 23:51:52.036000	开始回放数据
> 2018-05-19 23:51:52.128000	数据回放结束
> 2018-05-19 23:51:52.128000	计算回测结果
> 2018-05-19 23:51:52.129000	------------------------------
> 2018-05-19 23:51:52.129000	第一笔交易：	2018-05-11 10:27:00
> 2018-05-19 23:51:52.129000	最后一笔交易：	2018-05-18 16:00:00
> 2018-05-19 23:51:52.129000	总交易次数：	38.0
> 2018-05-19 23:51:52.129000	总盈亏：	2,056.64
> 2018-05-19 23:51:52.129000	最大回撤: 	-1,572.93
> 2018-05-19 23:51:52.129000	平均每笔盈利：	54.12
> 2018-05-19 23:51:52.130000	平均每笔滑点：	40.0
> 2018-05-19 23:51:52.130000	平均每笔佣金：	24.51
> 2018-05-19 23:51:52.130000	胜率		36.84%
> 2018-05-19 23:51:52.130000	盈利交易平均值	392.21
> 2018-05-19 23:51:52.130000	亏损交易平均值	-143.09
> 2018-05-19 23:51:52.130000	盈亏比：	2.74

**优化回测代码**：
`
from __future__ import division

from vnpy.trader.app.ctaStrategy.ctaBacktesting import BacktestingEngine, MINUTE_DB_NAME, OptimizationSetting

if __name__ == '__main__':
    from vnpy.trader.app.ctaStrategy.strategy.strategyDoubleMa import DoubleMaStrategy

    # 创建回测引擎
    engine = BacktestingEngine()

    # 设置引擎的回测模式为K线
    engine.setBacktestingMode(engine.BAR_MODE)

    # 设置回测用的数据起始日期
    engine.setStartDate('20180501')

    # 设置产品相关参数
    engine.setSlippage(0.2)  # 股指1跳
    engine.setRate(3 / 10000)  # 万0.3
    engine.setSize(100)  # 股指合约大小
    engine.setPriceTick(0.2)  # 股指最小价格变动

    # 设置使用的历史数据库
    engine.setDatabase(MINUTE_DB_NAME, 'HK.00700')
    
    # 跑优化
    setting = OptimizationSetting()                 # 新建一个优化任务设置对象
    setting.setOptimizeTarget('winningRate')            # 设置优化排序的目标是策略净盈利
    setting.addParameter('fastWindow', 6, 10, 2)
    setting.addParameter('slowWindow', 56, 60, 2)
    
    # 性能测试环境：I7-3770，主频3.4G, 8核心，内存16G，Windows 7 专业版
    # 测试时还跑着一堆其他的程序，性能仅供参考
    import time    
    start = time.time()
    
    # 运行单进程优化函数，自动输出结果，耗时：359秒
    #engine.runOptimization(AtrRsiStrategy, setting)            
    
    # 多进程优化，耗时：89秒
    engine.runParallelOptimization(DoubleMaStrategy, setting)
    
    print u'耗时：%s' %(time.time()-start)`

**优化回测结果**：

> 2018-05-19 23:52:51.745000	优化结果：
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 6, 'slowWindow': 56}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 6, 'slowWindow': 58}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 6, 'slowWindow': 60}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 8, 'slowWindow': 56}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 8, 'slowWindow': 58}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 8, 'slowWindow': 60}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 10, 'slowWindow': 56}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 10, 'slowWindow': 58}，目标：0
> 2018-05-19 23:52:51.745000	参数：{'fastWindow': 10, 'slowWindow': 60}，目标：0

**Comment by cooooo** [comment]
@mrleex 
注意看一下你“优化回测代码”的这一部分：
```
# 运行单进程优化函数，自动输出结果，耗时：359秒
#engine.runOptimization(AtrRsiStrategy, setting)  
```

**Comment by mrleex** [comment]
@cooooo 你说的那两行代码都注释了呀，没问题吧，真正跑的时候是用多进程跑的

```
# 多进程优化，耗时：89秒
engine.runParallelOptimization(DoubleMaStrategy, setting)
```

**Comment by vnpy** [comment]
查了下，现在的参数优化已经改为使用calculateDailyStatistics的统计方法，因此支持以下字段：

`        result = {
            'startDate': startDate,
            'endDate': endDate,
            'totalDays': totalDays,
            'profitDays': profitDays,
            'lossDays': lossDays,
            'endBalance': endBalance,
            'maxDrawdown': maxDrawdown,
            'maxDdPercent': maxDdPercent,
            'totalNetPnl': totalNetPnl,
            'dailyNetPnl': dailyNetPnl,
            'totalCommission': totalCommission,
            'dailyCommission': dailyCommission,
            'totalSlippage': totalSlippage,
            'dailySlippage': dailySlippage,
            'totalTurnover': totalTurnover,
            'dailyTurnover': dailyTurnover,
            'totalTradeCount': totalTradeCount,
            'dailyTradeCount': dailyTradeCount,
            'totalReturn': totalReturn,
            'annualizedReturn': annualizedReturn,
            'dailyReturn': dailyReturn,
            'returnStd': returnStd,
            'sharpeRatio': sharpeRatio
        }
`

winningRate不在其中，最接近的应该是profitDays，如果想要百分比数字可以自己修改ctaBacktesting.py中的calculateDailyStatistics，加上一个你自己的统计指标

**Comment by mrleex** [comment]
@vnpy 果然如此，谢谢大大，也麻烦大大抽空更新下wiki吧，免得后来人踩坑~
