### ISSUE TITLE
WebTrader不友好的3个坑

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#884]
## 环境

* 操作系统: 如Windows 7或者CentOS
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1-dev beta发行版

## Issue类型
三选一：Bug/Enhancement/Question
BUG

## 预期程序行为
1，socket服务器连接： 未连接，可以随着连接状态变化而变化 
## 实际程序行为
实际未自动连接成功，状态未变化 
**本地WINDOWS测试时正常，远程LINUX测试时如上。（是否需要开放什么端口？）

## 预期程序行为
2，持仓-持仓盁亏字段，显示为盁亏数值 
## 实际程序行为
该列无数列，并被后一列的CTP接口字样替代，且接口列显示为空

## 预期程序行为
3，连接成功后，订阅合约，在行情中正常显示
## 实际程序行为
在行情中，未能正常显示。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
