### ISSUE TITLE
WebTrader run.py 运行异常

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#885]
## 环境

* 操作系统: 如Windows 7或者Centos
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1beta发行版

## Issue类型
三选一：Bug/Enhancement/Question
BUG

## 预期程序行为
WebTrader  - run.py可以正常执行

## 实际程序行为
程序运行后，会自动重启。

注释以下内容后，运行正常。
            # if not pWeb:
            #    pWeb = Process(target=runWebServer)
            #    pWeb.start()
            #    le.info(u'启动WEB服务器进程')

## 重现步骤

D:\>cd D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader

D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader>python run.py
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
2018-05-22 10:38:02,075  INFO: ------------------------------
2018-05-22 10:38:02,075  INFO: 当前时间：2018-05-22 10:38:02.076000
2018-05-22 10:38:02,076  INFO: 当前处于交易时间段
2018-05-22 10:38:02,086  INFO: 启动交易服务器进程
2018-05-22 10:38:02,096  INFO: 启动WEB服务器进程
DD:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
2018-05-22 10:38:04,644  INFO: 服务器进程启动
2018-05-22 10:38:04,645  INFO: 事件引擎创建成功
2018-05-22 10:38:04,663  INFO: 主引擎创建成功
2018-05-22 10:38:04,663  INFO: 服务器启动成功
 * Restarting with stat
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
2018-05-22 10:38:07,045  INFO: ------------------------------
2018-05-22 10:38:07,045  INFO: 当前时间：2018-05-22 10:38:07.045000
2018-05-22 10:38:07,045  INFO: 当前处于交易时间段
2018-05-22 10:38:07,055  INFO: 启动交易服务器进程
2018-05-22 10:38:07,065  INFO: 启动WEB服务器进程
DD:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
 * Debugger is active!
 * Debugger pin code: 106-709-366
2018-05-22 10:38:09,569  INFO: 服务器进程启动
2018-05-22 10:38:09,571  INFO: 事件引擎创建成功
Process Process-1:
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda22\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\ProgramFiles\Anaconda22\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\APP\VNPY\VNPYDEV20180520\examples\WebTrader\tradingServer.py", line 59, in main
    me.addApp(rpcService)
  File "D:\APP\VNPY\VNPYMASTER0225\vnpy\trader\vtEngine.py", line 86, in addApp
    self.appDict[appName] = appModule.appEngine(self, self.eventEngine)
  File "D:\APP\VNPY\VNPYMASTER0225\vnpy\trader\app\rpcService\rsEngine.py", line 32, in __init__
    self.loadSetting()
  File "D:\APP\VNPY\VNPYMASTER0225\vnpy\trader\app\rpcService\rsEngine.py", line 44, in loadSetting
    self.server = RpcServer(self.repAddress, self.pubAddress)
  File "D:\APP\VNPY\VNPYMASTER0225\vnpy\rpc\vnrpc.py", line 119, in __init__
    self.__socketREP.bind(repAddress)
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:7535)
    raise ZMQError(errno)
ZMQError: Address in use

**Comment by vnpy** [comment]
已修复
