### ISSUE TITLE
火币API API签名无效: 校验失败,HUOBI

### ISSUE THREAD

**Issue by VincentYanJk** [vnpy/vnpy#886]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
连接火币接口， 行情也能正常推送 没有错误信息

## 实际程序行为
行情可以推送 但是收到 错误信息从 HUOBI API

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

17:43:50,Trade,错误代码：api-signature-not-valid，错误信息：API签名无效: 校验失败,HUOBI
17:43:49,Trade,"GET请求触发异常，原因：HTTPSConnectionPool(host='api.huobi.pro', port=443): Read timed out. (read timeout=5)",HUOBI

**Comment by VincentYanJk** [comment]
大神 有遇到过这样的 情况吗？

**Comment by linyaohui** [comment]
遇到一样的问题

**Comment by vnpy** [comment]
这两个报错都是因为火币服务器的请求超时导致的，并不影响实际工作，已经在代码里将这两个错误信息过滤掉。
