### ISSUE TITLE
模块：spreadTrading的文件stAlgo有冗余代码

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#887]
操作系统: 如Windows 7
 Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
 vn.py版本: 如v1.8.1发行版

Issue类型
三选一：Question

预期程序行为
执行该代码

 实际程序行为
未执行

重现步骤：

模块：spreadTrading
文件：stAlgo

函数“newActiveLegTrade"""新的主动腿成交""" ”的位置已经调用了
函数“self.hedgeAllPassiveLegs()# 发出被动腿对冲委托”
，但是在函数“ updateOrder"""委托更新"""   ”的位置调用
函数“self.hedgePassiveLeg(vtSymbol) # 检查若是被动腿，且已经没有未完成委托，则执行对冲”  
两处重复。

按照如下结果进行测试：
1、代码“self.hedgePassiveLeg(vtSymbol)”调用前及调用后均加上日志，日志显示未调用该函数（但无法确认是否异常情况调用，既是否撤单或者异常错误后调用该位置发被动腿单）
2、删除代码，测试，无任何报错。
以上测试未进行被动腿的允许滑点是0（不追单）测试。（该出应该不是被动腿被撤销后再次发单位置，因为前边条件是FINISHED_STATUS了。）
 
![111](https://user-images.githubusercontent.com/31505150/40521717-9e55122e-5fff-11e8-84fe-ed7e9d35efe0.png)

**Comment by vnpy** [comment]
检查后总结代码并无冗余：
- newActiveLegTrade对应的逻辑是当主动腿有成交后，立即执行一次对冲
- updateOrder对应的则是因为某种原因（如被动腿未成交撤单）导致的被动腿委托完成（全部成交、撤单等）后，再次执行一次对冲

注意这里的hedgePassiveLeg下的sendLegOrder函数，内置了对委托数量的检查，即需要对冲数量为0则不发出任何实际委托。
