### ISSUE TITLE
有时启动vnMain.py后行情数据记录没写进mongodb

### ISSUE THREAD

**Issue by jerryw** [vnpy/vnpy#89]
有时启动vnMain.py后行情数据记录没写进mongodb。已经设置了DR_setting.json中的working为true, 启动vnMain.py有5次，中间1次没记录任何行情数据到mongodb，其它4次启动都能正常记录tick和bar数据到mongodb。运行期间行情数据记录窗口是一直有数据在滚动的，表示接收是正常的，写库逻辑可能有问题。

**Comment by vnpy** [comment]
这种情况我没有遇到过，猜测可能的原因是，订阅的合约量比较多或者硬盘速度较慢，导致数据在执行数据库插入时，数据落地到硬盘前都被缓存在内存中，此时如果关闭程序，可能导致数据丢失。

建议多做测试，5次里4次能成功说明程序逻辑本身是能工作的，问题应该出在mongodb端
