### ISSUE TITLE
FutureWarning导致查询行情时显示接口不存在

### ISSUE THREAD

**Issue by a4-gh** [vnpy/vnpy#893]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Question

## 预期程序行为
已按wiki步骤环境安装

## 实际程序行为
运行VnTrader时，出现FutureWarning，进入系统查询合约行情时，提示接口不存在

## 重现步骤

![futurewarning](https://user-images.githubusercontent.com/39108686/40588484-5a763fca-6210-11e8-9480-2923cd254f11.jpg)

**Comment by vnpy** [comment]
你的交易接口登陆后没有收到合约信息查询的回报，导致策略模块订阅行情时无法找到该合约的信息，所以报错接口不存在

**Comment by a4-gh** [comment]
![connect](https://user-images.githubusercontent.com/39108686/40604456-a60b5336-6291-11e8-9412-80e77d13d1b2.jpg)
账户设置也试过更换端口了

**Comment by vnpy** [comment]
交易服务器的宽口是10001
