### ISSUE TITLE
ctaEngine一个小建议

### ISSUE THREAD

**Issue by viponedream** [vnpy/vnpy#90]
1，有行情就直接推送到策略中去。建议初始化完成之后再推送。
2，策略初始化后，假如没有行情，建议自动订阅。感觉没必要手工先在主界面订阅。

**Comment by vnpy** [comment]
1. 可以在策略代码的onTick中，开始的时候加上一句：
`
if not self.inited:
    return
`
实现初始化前策略不对行情推送处理

2. 目前加载策略的时候loadStrategy就会自动订阅行情，不过有个前提是系统内必须已经有该合约的信息，目前应该IB不行

**Comment by viponedream** [comment]
谢谢了。
