### ISSUE TITLE
新手应该从哪开始运行这个平台呢？

### ISSUE THREAD

**Issue by wcsmomo** [vnpy/vnpy#900]
## 环境

* 操作系统: 如Windows8
* Anaconda版本: 如Anaconda 5.1.0 Python 3.5 32位
* vn.py版本: （下载日期20180531）
*工具：pycharm 

## Issue类型
Bug
运行 examples.VnTrader.run.py 报了好些错，有些是编译工具问题，有些是python版本问题，有些是程序bug,
其中程序bug有：
1. 目录 vnpy.trader.gateway.ctpGateway 下有一个与目录名称ctpGateway同名的模块ctpGateway。导致import 报错。
2.ctpGateway程序中有一条导入语句：from vnpy.api.ctp import MdApi, TdApi, defineDict，但是vnpy.api.ctp目录中并没有MdApi和TdApi模块。

## 预期程序行为
1.常用的入口程序能执行。

## 实际程序行为
1.程序中的入口程序几乎都运行不起来。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cooooo** [comment]
看wiki，还有论坛
