### ISSUE TITLE
同一进程同一线程同一交易策略发出了两个订单编号相同的订单

### ISSUE THREAD

**Issue by 80779898** [vnpy/vnpy#901]
## 环境

* 操作系统: 如Windows server2012

## Issue类型
三选一：Bug

## 预期程序行为
由于订单递增，同一进程同一线程同一交易策略每个订单的编码都应该不一样

## 实际程序行为
但目前出现了同一进程同一线程同一交易策略发出了两个订单编号相同的订单

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![qq 20180531140045](https://user-images.githubusercontent.com/3130864/40764286-0ddb3670-64db-11e8-99a5-4474d63f65f1.png)

**Comment by 80779898** [comment]
就是不知道如何重现，如果知道如何重现，我就直接处理了。也是只出现过一次。

**Comment by nice-pythoner** [comment]
没有当时的stack么？

**Comment by 80779898** [comment]
又出现了。快速连续发单会出现这个问题。不过也不是每次都出现。l连这次出现3次了。我这次在ctpgateway那里输出日志了。确实是同一个进程同一个线程，结果发了两个订单编号相同的单子。按道理ctpgateway（自增的地方）实例唯一，无论怎么发单调用发单指令，都是自增有效的才对啊。
![qq 20180712100139](https://user-images.githubusercontent.com/3130864/42608558-d552e05e-85ba-11e8-870d-62401dcb8f57.png)

**Comment by vnpy** [comment]
请尝试：
1. 在TdApi中创建一把threading.Lock锁
2. 在sendOrder函数中，修改本地缓存的委托号orderRef前，先获取这把锁，修改后释放
2. 在onOrder函数中，修改本地缓存的委托号orderRef前，先获取这把锁，修改后释放

这样应该可以解决该问题。
