### ISSUE TITLE
Spread trade

### ISSUE THREAD

**Issue by Qmarkwi** [vnpy/vnpy#903]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本:Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.1

## Issue类型
三选一：Question

## 预期程序行为
价差交易模块： 试验热卷10-01做多10对成交，反向设置做预期实现减持或清仓；
                          试验螺纹做空3对成交，反向设置预期实现减持或清仓

## 实际程序行为
   设置穿透价格也无反应，似乎只能手动分别平仓？
  

## 重现步骤

![default](https://user-images.githubusercontent.com/39785057/40832351-b379e170-65bd-11e8-949d-8444f3f4bb68.png)

Ps： 我是搞现货和期货交易的（单边，跨市，价差，跨商品对冲都交易），对Python代码不是很清楚，从个人实际交易角度看：
1.选择双向模式这个价差交易逻辑应该是区间扫荡，好像缺少逃逸区间。我的理解应该是大区间套小区间，还要有上下两个逃逸价格； 单向模式也没有找到逃逸设定。
2.自动（允许干预）、手动、限定条件值守（交易波次1-N，部分止盈止损等等）的切换和支持实际交易很需要特别是对于我们搞中低频交易的类型。
3.不知道是否扩展比值模式，实际交易中采用比值的也很多，我用比值模式比价差模式还要多一些。
4.折腾两周发现VNPY是最接近实战的开源量化项目了，祝愿项目蓬勃发展,拥趸众多。

**Comment by vnpy** [comment]
1. 确实没有逃逸区间概念，算法本身在设计上定位在半自动运行，用户可以任何时候修改相应的price阈值来控制交易
2. 这些内容属于价差交易中，比较个性化的部分，即每个交易员自己的经验和风格，很难标准化。vn.py本身定位在框架，鼓励用户根据自己的需求修改
3. 比值模式目前没有支持，欢迎贡献代码（主要我自己也没做过比值，不太确定实现细节）
4. 非常感谢 ：）
