### ISSUE TITLE
OK与HUOBI 存在的 被判拒单，但是后来查询到是正确单的问题

### ISSUE THREAD

**Issue by ipqhjjybj** [vnpy/vnpy#905]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
拒单就是拒单， 正确单就是正确单。。  

## 实际程序行为
OKEX  ， 错误返回信息时 20100， 超时处理， 但实际上他服务器正常处理了
HUOBI ， 不包含err-code的错误下单信息， 实际上是正常处理了
## 重现步骤
![image](https://user-images.githubusercontent.com/3134652/40968190-91ddc14e-68e7-11e8-8aa3-6ad7a3a9c4b5.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by ipqhjjybj** [comment]
SSLError('The read operation timed out',)

**Comment by vnpy** [comment]
尝试了一些解决方案，目前没有很好的方法。

如果采用委托历史轮询方案又会加剧流控的影响，导致速度下降明显。

只能建议降低下单的频率，还有尝试托管方案了。
