### ISSUE TITLE
BIFFiNEX接口短线后无法重连

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#906]
## 环境

* 操作系统: 如Windows 2012
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1发行版或者dev branch 20180604（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为
biffinex段线后自动重连

## 实际程序行为
无法重连，pycharm输出connection closed

## 重现步骤
开着服务器，订阅某个合约，直到短线后，行情没再更新，pycharm输出connection closed
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
