### ISSUE TITLE
biffnex 五档行情数据比官网的慢了几个挡位以上而且vnpy上的排序不对

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#907]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为

应该接近或者同步才对
## 实际程序行为
biffnex 五档行情数据比官网的满了几个挡位以上

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
