### ISSUE TITLE
IB接口无法获得配置文件指定的"accountCode"，并且把TWS的第一个子帐号给自动切成第二个子帐号了

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#908]
环境

操作系统: 如Windows 7
Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
vn.py版本: 如v1.8.1

Issue类型
三选一：Enhancement

预期程序行为
IB接口根据配置文件指定的"accountCode"获得用户名下对应的子账户

实际程序行为
获取到的是用户名下的第二个子账户，无法获得第一个账户。

重现步骤
----------------------------------------------
一：
IB配置："accountCode": "DU933268"
那么这个accountCode目前指定了是不起效果的，实际上是想获得指定的IB用户名下的对应的子账户的，配置文件中的accountCode在程序中读取到后，就没再作为参数使用过。
代码位置：
文件ibGateway.py，函数def connect(self)，代码：self.api.eConnect(self.host, self.port, self.clientId, False)

期望能够根据该配置实现获得用户名下指定的子帐号。

对于显示的账户编号，对于IB子帐号是加了货币的后缀的，查询了对应的ibGateway.py中的逻辑，是函数updateAccountValue处理的，但是没法跟进去的。

二：
另外就是TWS登陆后，TWS默认是第一个子帐号的，信息等都正确的，但是登陆vnpy后，获得的是第二个子帐号的信息，并且立刻就把TWS的登陆的第一个子帐号切换成了第二个子帐号了，多次验证确实是如此(发现时无法相信，后来两个人盯着把窗口前后放好看的，确实如此，今天早上又特意看了下，也是如此。)，与IB负责接口的同事联系过的了，他们需要具体实现的函数，但是目前从逻辑上无法准确提供给他们。

肯定群主实现该功能或指点下该如何实现该功能，谢谢！

----------------------------------------------

**Comment by stone3536** [comment]
@群主，您好
这个问题可以通过变相方式实现的，就是IB的一个登录帐号可以对应一个资金帐号。主登录帐号可以看到所有子帐号，申请一个新的登录帐号对应到相应的资金帐号就可以解决了。此问题可以关闭。
是否可以多个登录帐号（不含主登录帐号）对应一个资金帐号，没和ib进行过确认，但是按照了解下来他们的模式，应该也是可以的。
感谢您！

**Comment by stone3536** [comment]
@群主，您好
这个问题可以通过变相方式实现的，就是IB的一个登录帐号可以对应一个资金帐号。主登录帐号可以看到所有子帐号，申请一个新的登录帐号对应到相应的资金帐号就可以解决了。此问题可以关闭。
是否可以多个登录帐号（不含主登录帐号）对应一个资金帐号，没和ib进行过确认，但是按照了解下来他们的模式，应该也是可以的。
感谢您！

**Comment by vnpy** [comment]
非常感谢告知！
