### ISSUE TITLE
ctaEngine 中 initStrategy 函数中 strategy.inited = True 应推后一步

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#909]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug

## 预期程序行为
    #----------------------------------------------------------------------
    def initStrategy(self, name):
        """初始化策略"""
        if name in self.strategyDict:
            strategy = self.strategyDict[name]

            if not strategy.inited:
                self.callStrategyFunc(strategy, strategy.onInit)
                strategy.inited = True
                self.putStrategyEvent(name)
                ...

## 实际程序行为
    #----------------------------------------------------------------------
    def initStrategy(self, name):
        """初始化策略"""
        if name in self.strategyDict:
            strategy = self.strategyDict[name]

            if not strategy.inited:
                strategy.inited = True
                self.callStrategyFunc(strategy, strategy.onInit)
                ...

**Comment by vnpy** [comment]
已修复
