### ISSUE TITLE
获取单个CHAR的时候问题

### ISSUE THREAD

**Issue by wildwild** [vnpy/vnpy#91]
HedgeFlag 单个char的不要用str的模块去读取，会strcpy_s，但是会在回调的时候出错，所以
建议：
改了一下获取单个char的代码
void getSingleChar(dict d,string key, char *value)
{
	if (d.has_key(key))
	{
		object o = d[key];
		extract<string> x(o);
		if (x.check())
		{
			string s = x();
			std::cerr<<"now extract string is "<<s<<std::endl;
			const char *buffer = s.c_str();
			*value = buffer[0];
			std::cerr<<*value<<endl;
		}
	}
}

另外的一些单char的也可以更改一下

**Comment by vnpy** [comment]
WOW，终于有人发现这个历史遗留的bug了，在后来做的几个API里，单一的CHAR已经改为使用getChar，STRING改为使用getString，分成两个函数了，但是早期的API封装还没修改，准备在后续版本里弄。

**Comment by wildwild** [comment]
我自己反正用到的就先改改，不用到我也懒得改了……
群主加油~。~
