### ISSUE TITLE
Two undefined names 'evt' in ./vnpy/api/okex/vnokex.py

### ISSUE THREAD

**Issue by cclauss** [vnpy/vnpy#915]
* https://github.com/vnpy/vnpy/blob/dev/vnpy/api/okex/vnokex.py#L174-L180
* https://github.com/vnpy/vnpy/commit/762a838b3d0acaa07f29c26f4afb6eb8f0211d20#r29315125

__evt__ is an _undefined name_ in this context. The same issue is found 6 lines below.

#870 would automatically find these kind of errors.

$ __flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823__
```
./vnpy/api/okex/vnokex.py:174:15: F821 undefined name 'evt'
        print(evt)
              ^
./vnpy/api/okex/vnokex.py:180:15: F821 undefined name 'evt'
        print(evt)
              ^
```

**Comment by vnpy** [comment]
已修复
