### ISSUE TITLE
清理版本库中不必要的文件

### ISSUE THREAD

**Issue by zhu4ling3** [vnpy/vnpy#917]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Enhancement

## 预期程序行为
版本库中有很多不需要版本管理的文件，例如a.out, xx.so, xx.o等临时文件或者可以通过源码编辑的文件。
能够清理一次，然后形成新的.gitignore文件？

## 实际程序行为
每次重新安装环境编译C库之后，都需要提交一次这次临时文件。并且不易理解本项目必要文件的范围。

**Comment by vnpy** [comment]
已经移除vnpy/api/ib/build目录
