### ISSUE TITLE
dev 下 bitfinex接口数据有问题

### ISSUE THREAD

**Issue by ipqhjjybj** [vnpy/vnpy#918]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
 TICK 数据不对 

## 实际程序行为
![image](https://user-images.githubusercontent.com/3134652/41325878-31cc1982-6eef-11e8-815c-18a5f0faffc6.png)

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
具体不对的地方是？

**Comment by vnpy** [comment]
上周修改了一次BITFINEX的行情深度逻辑，请再试试最新版本是否还存在这个问题？
