### ISSUE TITLE
windows 10 VnTrader run.py错误

### ISSUE THREAD

**Issue by KrisLee** [vnpy/vnpy#923]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda2-5.2.0-Windows-x86 Python 2.7 32位
* vn.py版本: git clone的最新版本

## Issue类型
三选一：Bug

## 重现步骤

examples目录：
Python run.py出错：“ImportError: cannot import name algoTrading”，
之后通过pip install，会安装Finance-Python，然后就一直编译错误：
    C:\Users\jing\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jing\Anaconda2\libs /LIBPATH:C:\Users\jing\Anaconda2\PCbuild /LIBPATH:C:\Users\jing\Anaconda2\PC\VS9.0 /EXPORT:initSecurityValueHolders build\temp.win32-2.7\Release\PyFin/Analysis/SecurityValueHolders.obj /OUT:build\lib.win32-2.7\PyFin\Analysis\SecurityValueHolders.pyd /IMPLIB:build\temp.win32-2.7\Release\PyFin/Analysis\SecurityValueHolders.lib /MANIFESTFILE:build\temp.win32-2.7\Release\PyFin/Analysis\SecurityValueHolders.pyd.manifest
       Creating library build\temp.win32-2.7\Release\PyFin/Analysis\SecurityValueHolders.lib and object build\temp.win32-2.7\Release\PyFin/Analysis\SecurityValueHolders.exp
    SecurityValueHolders.obj : error LNK2019: unresolved external symbol _isnan referenced in function ___pyx_f_5PyFin_8Analysis_20SecurityValueHolders_25SecurityLatestValueHolder_push
    build\lib.win32-2.7\PyFin\Analysis\SecurityValueHolders.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Users\\jing\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

    ----------------------------------------
Command "C:\Users\jing\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jing\\appdata\\local\\temp\\pip-install-7r3woo\\Finance-Python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jing\appdata\local\temp\pip-record-kh6wzh\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jing\appdata\local\temp\pip-install-7r3woo\Finance-Python\

**Comment by KrisLee** [comment]
感觉是PyFin、Finance-Python版本问题，是不是有些lib太老了

**Comment by cooooo** [comment]
vnpy不需要这两个包。建议看一下wiki的说明。

**Comment by KrisLee** [comment]
dev分支的问题?
https://github.com/vnpy/vnpy/blob/dev/examples/VnTrader/run.py
33行:
# 加载上层应用
from vnpy.trader.app import (riskManager, ctaStrategy, 
                             spreadTrading, algoTrading)

**Comment by vnpy** [comment]
下载最新的dev分支后，请先安装，再运行examples下的样例，另外不要安装Finance-Python

**Comment by liangjingyang** [comment]
我也遇到了同样的错误, 已经解决, 我的问题是这样导致的:

较早的时候我搭建过 vnpy 的环境, 当时用 pip install vnpy 安装过一次, 位置在`Anaconda2\lib\site-packages\vnpy`, 今天我又从 git clone 了一份 vnpy 到`D:\`. 结果运行 `example/VnTrader/VnTrader.bat`报错如下: 

```
d:\Anaconda2\lib\site-packages\vnpy\api\ib\__init__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    from vnpy.trader.app import (riskManager, ctaStrategy,
ImportError: cannot import name algoTrading
```

解决方法:

```
pip uninstall vnpy
```

首先, 从`import`可以看出, `algoTrading` 是`vnpy`的一个包, 位于 `vnpy.trader.app`, 并不是一个第三方的库. 所以我们不应该去 `pip install algoTrading`.

在运行`example/VnTrader/VnTrader.bat` 的时候优先去了`Anaconda2\lib\site-packages\vnpy`里面查找, 而这里的 vnpy 是 pip install 的, 版本比较早, 里面没有 `algoTrading` 这个包.
