### ISSUE TITLE
（因为数量%后面漏了s）算法交易的TAWP buy时提示self.writeLog(u'委托买入%s，数量%，价格%s' %(self.vtSymbol, self.orderSize, price)) ValueError: unsupported format character '?' (0xff0c) at index 10

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#926]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
self.writeLog(u'委托买入%s，数量%，价格%s' %(self.vtSymbol, self.orderSize, price))
ValueError: unsupported format character '?' (0xff0c) at index 10

## 重现步骤
启动算法后出现以上提示

**Comment by linyaohui** [comment]
self.writeLog(u'委托买入%s，数量%，价格%s' %(self.vtSymbol, self.orderSize, price))
改为
self.writeLog(u'委托买入%s，数量%s，价格%s' %(self.vtSymbol, self.orderSize, price))

**Comment by vnpy** [comment]
已修复
