### ISSUE TITLE
STOP算法   File "C:\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\app\algoTrading\stopAlgo.py", line 51, in onTick     tick.lastPrice >= self.price): AttributeError: 'StopAlgo' object has no attribute 'price'

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#928]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
启动算法后，提示
  File "C:\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\app\algoTrading\stopAlgo.py", line 51, in onTick
    tick.lastPrice >= self.price):
AttributeError: 'StopAlgo' object has no attribute 'price'

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
