### ISSUE TITLE
安装以后未能成功运行

### ISSUE THREAD

**Issue by chenpw2088** [vnpy/vnpy#929]
## 环境

* 操作系统: 如Windows 7 64位
* Anaconda版本: 没找到4.0，下载的Anaconda2-5.2.0-Windows-x86
* mongodb-win32-x86_64-2008plus-v3.4-latest-signed
* vn.py版本: 如v1.7发行版或者dev branch 20180618（下载日期）

## Issue类型
三选一：Question
按步骤安装成功以后，运行example中的VnTrader.bat失败

## 预期程序行为
预期可以成功

## 实际程序行为
C:\vnpy>cd C:\vnpy\examples\VnTrader

C:\vnpy\examples\VnTrader>VnTrader.bat

C:\vnpy\examples\VnTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\gateway\ctpGatewa
y\__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\gateway\ctpGatewa
y\ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\api\ctp\__init__.py", li
ne 3, in <module>
    from vnctpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。

## 重现步骤

反复下载安装都是如此

**Comment by vnpy** [comment]
是否安装了vcredist x86 2013?

**Comment by chenpw2088** [comment]
安装了vcredist x86 2013

**Comment by chenpw2088** [comment]
已经正确安装了

在 2018年6月19日，上午9:59，vn.py <notifications@github.com<mailto:notifications@github.com>> 写道：


是否安装了vcredist x86 2013?

**Comment by vnpy** [comment]
以上报错主要就是两个可能：
1. Python装了64的
2. vcredist没装2013 x86

如果两者都确认没问题，那就卸载了重来一遍

**Comment by chenpw2088** [comment]
确认没安装错；卸载重装几次了；

另外，请问一下，我在虚拟机上搞的，搞好以后，可以提交给官方正式发布吗？

在 2018年6月20日，上午10:41，vn.py <notifications@github.com<mailto:notifications@github.com>> 写道：


以上报错主要就是两个可能：

  1.  Python装了64的
  2.  vcredist没装2013 x86

如果两者都确认没问题，那就卸载了重来一遍

**Comment by chenpw2088** [comment]
对着init.bat和install.bat单步执行，终于搞好了。能看到界面了，之前估计是Ta-lib没安装好。

[cid:F497AB7C-5DF5-44ED-A527-37804FA5F8E7]

谢谢了。


在 2018年6月20日，上午10:41，vn.py <notifications@github.com<mailto:notifications@github.com>> 写道：


以上报错主要就是两个可能：

  1.  Python装了64的
  2.  vcredist没装2013 x86

如果两者都确认没问题，那就卸载了重来一遍
