### ISSUE TITLE
vntrader的表头排序问题

### ISSUE THREAD

**Issue by freeitaly** [vnpy/vnpy#93]
pyqt4中使用setSortingEnabled（True）开启表头排序功能，是按照字符串的编码进行排序，如3 > 123, 导致在vntrader的Monitor中对 价格、成交量等数字类型的字段进行排序时排序结果都是错误的，有没有什么办法对数字格式进行排序么？
插入Monitor中的单元格都是转化成SafeUnicode的，试过不转化直接插入，结果也错误。

**Comment by freeitaly** [comment]
找到个解决方法
http://stackoverflow.com/questions/11938459/sorting-in-pyqt-tablewidget

定义个NumCell， 将self.setText() 换成self.setData(QtCore.Qt.DisplayRole, float(text))

**Comment by vnpy** [comment]
这个没注意过，你的方法能解决就最好了，我回头看看更新到项目里。

**Comment by freeitaly** [comment]
试过了，2楼的方法管用。
我的项目里改动太多了，不大好push，群主有空的时候修改下吧

**Comment by freeitaly** [comment]
发现个问题，BasicMonitor类的updateData函数中，已经将单元格数据转化为SafeUnicode，然后用celltype规范单元格显示。
如果加入数值类型排序的话，就需要在不同的cell定义中按需进行SafeUnicode转化了。

**Comment by vnpy** [comment]
考虑把委托、成交编号单元格用上面提到的NumCell来做（主要也就是针对这两个排序），其他的维持现状。

**Comment by vnpy** [comment]
已解决
