### ISSUE TITLE
安装以后未能成功运行run.py

### ISSUE THREAD

**Issue by daidawn19** [vnpy/vnpy#930]
## 环境

* 操作系统: 如Windows 7 64位
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.1

## Issue类型
三选一：安装后运行run.py报错说没有open_context这个module

## 实际程序行为
![capture](https://user-images.githubusercontent.com/36223686/41557369-b7150c6e-733d-11e8-9be6-f5be3a2754a3.JPG)

## 重现步骤： 同样的报错

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
这是富途接口更新导致的问题，请在run.py中移除futuGateway即可

**Comment by daidawn19** [comment]
谢谢回复！移除futuGateway后run.py运行成功，出来了交易页面。
不过新问题是，交易页面仿佛是死的，输入合约代码之后也没有反应，没有出现任何数据。请教出现这种情况是哪一步没有弄好呢？作为一个小白实在是难受
