### ISSUE TITLE
能提供下策略内使用算法单下单的示例吗？

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#931]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.2.0 Python 3.6 64位
* vn.py版本: v1.8

## Issue类型
三选一：Question

现在的算法单好像是手动，使用不方便，群主能提供下策略内使用算法单下单的示例吗

**Comment by vnpy** [comment]
目前CTA模块和AlgoTrading模块，应用领域是相反的：
* CTA模块偏向中高频的单标的交易策略，需要自己控制很多挂撤单细节
* AlgoTrading模块偏向为低频策略或者手动交易提供高效的下单解决方案

所以暂时没有在CTA中支持AlgoTrading的计划
