### ISSUE TITLE
接issue#930, 谢谢回复指导，移除futuGateway后运行成功，但是界面有些问题

### ISSUE THREAD

**Issue by daidawn19** [vnpy/vnpy#932]
## 环境

* 操作系统: Windows 7 64位
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.1

## Issue类型
三选一：交易界面无显示

## 预期程序行为
正常显示交易界面

## 实际程序行为
移除futuGateway后run.py运行成功，出来了交易页面。
不过新问题是，交易页面仿佛是死的，输入合约代码之后也没有反应，没有出现任何数据。请教出现这种情况是哪一步没有弄好呢？作为一个小白实在是难受。ps：CTP_connect也设置过了

![capture1](https://user-images.githubusercontent.com/36223686/41586930-481434cc-73ae-11e8-854b-afc83b080467.JPG)
![capture](https://user-images.githubusercontent.com/36223686/41586936-4a15a922-73ae-11e8-85dd-496685fc9056.JPG)

## 重现步骤
重新打开几次都是一样，按教程随机输入一个交易代码按回车，结果界面还是无显示。

**Comment by cooooo** [comment]
CTP连接了吗？“日志”显示什么？

**Comment by daidawn19** [comment]
点击过系统-->连接CTP了，日志显示如下：(所以是MongoDB没装好？..那要怎么做呢？只重装MongoDB还是所有都要重装？*.*)
![capture](https://user-images.githubusercontent.com/36223686/41588135-43db4050-73b1-11e8-9986-52c76b2fead6.JPG)

**Comment by cooooo** [comment]
只需要检查MongoDB的安装

**Comment by daidawn19** [comment]
谢谢回复！
刚才心急，把所有的都重新装了一下...
一样把run.py里面的futuGateway的部分去掉了只有，运行出来得到一样的结果，就是：
![capture](https://user-images.githubusercontent.com/36223686/41597503-ef549d48-73cd-11e8-9d55-643b950f7664.JPG)

特别注意了MongoDB的安装，请各位大神帮忙看下我的安装步骤，指导下哪里不对：
1. 官网下载MongoDB，按指导下了3.4版本，具体是
![capture](https://user-images.githubusercontent.com/36223686/41597550-10e891da-73ce-11e8-889e-b322b8e6aa4a.JPG)
2. 按以下指导设置：
![capture](https://user-images.githubusercontent.com/36223686/41597609-30038b6a-73ce-11e8-95e1-bcec48005194.JPG)
3. cmd 以管理员身份运行：
"C:\Program Files\MongoDB\Server\3.4\bin\mongod.exe" --config "C:\Program Files\MongoDB\Server\3.4\mongod.cfg" --install
此处未截图
4. cmd以管理员身份启动MongoDB,显示启动成功：
![capture](https://user-images.githubusercontent.com/36223686/41597753-9dadd0ee-73ce-11e8-8f31-3da080c07c2a.JPG)

以上这样是不是就算安装MongoDB没什么问题了呢?
另外，我安装MongoDB的路径跟vnpy的不一样，vnpy在D盘，MongoDB在C盘，这个有没有影响呢？

**Comment by vnpy** [comment]
从日志看，你的Windows服务管理器把MongoDB后台进程给杀掉了。

检查下是自己误操作，还是360之类的捣乱

**Comment by daidawn19** [comment]
大神可以提供下远程操作帮我看下吗，我有teamviewer 12？我真的是没辙了，MangoDB按网上的指示安装，过程中没有出现任何问题（见以上截图）。vnpy也是按指导打开的，360确实有装，但是怎么判断它有没有在捣乱啊?!*.*
纯小白，做到这一步不容易呀*.*能上vnpy才可以正儿八经的开始学习了...

**Comment by vnpy** [comment]
实在折腾不好，买个阿里云的Win2008 x64 中文服务器，在上面装了用吧，挺方便。

**Comment by daidawn19** [comment]
谢谢建议！
那哪位大神可以帮我看下我上面贴的那个装MongoDB的过程是否正确？如果正确的话那就是360的问题，我直接卸载360好了...
阿里云服务器，我刚刚也研究过了，感觉安装也是会花费一些时间（对于我这样一个没有基础的人来说...），还不知道会不会出现其他问题。现在在自己电脑上貌似就差那么一点点就能用了，如果能解决的还是想在自己电脑上面装....
