### ISSUE TITLE
TALIB  import出错

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#933]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.1

## Issue类型
三选一：Bug   在学CTA策略模块策略开发时安装talib包遇到的问题
                                                                                                              

## 预期程序行为
pip install TA_Lib-0.4.17-cp27-cp27m-win32.whl  #没有找到TA_Lib-0.4.9-cp27-none-win32.whl
然后程序里import  talib时报错
import talib
Traceback (most recent call last):
  Python Shell, prompt 2, line 1
  File "C:\Anaconda2\Lib\site-packages\talib\__init__.py", line 43, in <module>
    from ._ta_lib import (
  File "c:\vnpy\_func.pxi", line 15, in init talib._ta_lib
  File "c:\vnpy\__init__.pxd", line 1000, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
然后我就下载了 ta-lib-TA_Lib-0.4.9.zip源码，执行安装命令又报错
C:\ta-lib-TA_Lib-0.4.9>python setup.py install                                                                          setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.                                              warnings.warn('Cannot find ta-lib library, installation may fail.')                                                   running install                                                                                                         running build                                                                                                           running build_py                                                                                                        running build_ext                                                                                                       skipping 'talib\common.c' Cython extension (up-to-date)                                                                 building 'talib.common' extension                                                                                       error: Unable to find vcvarsall.bat            
   
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by xldistance** [comment]
32位直接管理员命令pip install ta-lib就能安装

**Comment by jxhuliqun138** [comment]
我的系统时64位的， 这时运行的日志
C:\Windows\system32>pip install ta-lib                                                                                  Collecting ta-lib                                                                                                         Using cached https://files.pythonhosted.org/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz                                                                                                  Requirement already satisfied: numpy in c:\anaconda2\lib\site-packages (from ta-lib) (1.10.4)                           Building wheels for collected packages: ta-lib                                                                            Running setup.py bdist_wheel for ta-lib ... error                                                                       Complete output from command c:\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-install-fpqxpu\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\admini~1\appdata\local\temp\pip-wheel-5mlfsh --python-tag cp27:                                                                                     c:\users\admini~1\appdata\local\temp\pip-install-fpqxpu\ta-lib\setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.                                                                                                       warnings.warn('Cannot find ta-lib library, installation may fail.')                                                   running bdist_wheel                                                                                                     running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build\lib.win32-2.7                                                                                            creating build\lib.win32-2.7\talib                                                                                      copying talib\abstract.py -> build\lib.win32-2.7\talib                                                                  copying talib\deprecated.py -> build\lib.win32-2.7\talib                                                                copying talib\stream.py -> build\lib.win32-2.7\talib                                                                    copying talib\test_abstract.py -> build\lib.win32-2.7\talib                                                             copying talib\test_data.py -> build\lib.win32-2.7\talib                                                                 copying talib\test_func.py -> build\lib.win32-2.7\talib                                                                 copying talib\test_pandas.py -> build\lib.win32-2.7\talib                                                               copying talib\test_stream.py -> build\lib.win32-2.7\talib                                                               copying talib\__init__.py -> build\lib.win32-2.7\talib                                                                  running build_ext                                                                                                       skipping 'talib\_ta_lib.c' Cython extension (up-to-date)                                                                building 'talib._ta_lib' extension                                                                                      creating build\temp.win32-2.7                                                                                           creating build\temp.win32-2.7\Release                                                                                   creating build\temp.win32-2.7\Release\talib                                                                             C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\anaconda2\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Ic:\anaconda2\include -Ic:\anaconda2\PC /Tctalib\_ta_lib.c /Fobuild\temp.win32-2.7\Release\talib\_ta_lib.obj                                     _ta_lib.c                                                                                                               talib\_ta_lib.c(524) : fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory              error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2                                                                                                                                                                                                           ----------------------------------------                                                                                Failed building wheel for ta-lib                                                                                        Running setup.py clean for ta-lib                                                                                     Failed to build ta-lib                                                                                                  Installing collected packages: ta-lib                                                                                     Running setup.py install for ta-lib ... error                                                                             Complete output from command c:\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-install-fpqxpu\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-record-ihe74e\install-record.txt --single-version-externally-managed --compile:                                   c:\users\admini~1\appdata\local\temp\pip-install-fpqxpu\ta-lib\setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.                                                                                                       warnings.warn('Cannot find ta-lib library, installation may fail.')                                                   running install                                                                                                         running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build\lib.win32-2.7                                                                                            creating build\lib.win32-2.7\talib                                                                                      copying talib\abstract.py -> build\lib.win32-2.7\talib                                                                  copying talib\deprecated.py -> build\lib.win32-2.7\talib                                                                copying talib\stream.py -> build\lib.win32-2.7\talib                                                                    copying talib\test_abstract.py -> build\lib.win32-2.7\talib                                                             copying talib\test_data.py -> build\lib.win32-2.7\talib                                                                 copying talib\test_func.py -> build\lib.win32-2.7\talib                                                                 copying talib\test_pandas.py -> build\lib.win32-2.7\talib                                                               copying talib\test_stream.py -> build\lib.win32-2.7\talib                                                               copying talib\__init__.py -> build\lib.win32-2.7\talib                                                                  running build_ext                                                                                                       skipping 'talib\_ta_lib.c' Cython extension (up-to-date)                                                                building 'talib._ta_lib' extension                                                                                      creating build\temp.win32-2.7                                                                                           creating build\temp.win32-2.7\Release                                                                                   creating build\temp.win32-2.7\Release\talib                                                                             C:\Users\Administrator\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\anaconda2\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Ic:\anaconda2\include -Ic:\anaconda2\PC /Tctalib\_ta_lib.c /Fobuild\temp.win32-2.7\Release\talib\_ta_lib.obj                                     _ta_lib.c                                                                                                               talib\_ta_lib.c(524) : fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory              error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2                                                                                                                                                                                                           ----------------------------------------                                                                            Command "c:\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-install-fpqxpu\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-record-ihe74e\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-install-fpqxpu\ta-lib\

**Comment by jxhuliqun138** [comment]
请问必须要装WIN10 32位系统吗

**Comment by vnpy** [comment]
https://zhuanlan.zhihu.com/p/20613026

请照着这里的方法装

**Comment by jxhuliqun138** [comment]
我一开始就是按这个链接的方法按照的，但是我点开 下面“这里”的网页里面没有TA_Lib-0.4.9，只有最接近的TA_Lib‑0.4.17‑cp27‑cp27m‑win32.whl,  你有4.吗，麻烦发下给我
##在这里下载TA_Lib-0.4.9-cp27-none-win32.whl放到桌面上，也就是vn.py建议的运行环境Anaconda 2.7 32位

**Comment by cooooo** [comment]
talib版本不同不影响使用

**Comment by jxhuliqun138** [comment]
TA_Lib‑0.4.17‑cp27‑cp27m‑win32.whl, 我安装了这个版本后， 
import talib
Traceback (most recent call last):
Python Shell, prompt 2, line 1
File "C:\Anaconda2\Lib\site-packages\talib_init_.py", line 43, in 
from ._ta_lib import (
File "c:\vnpy_func.pxi", line 15, in init talib.ta_lib
File "c:\vnpy_init.pxd", line 1000, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by vnpy** [comment]
这是你的numpy问题了。。。之前手动升级过版本吗？搞不定就删了重装吧

**Comment by jxhuliqun138** [comment]
不是Numpy的问题，我用pip install talib==0.4.9 安装了对应的版本后现在都ok了

**Comment by zhuanqizhirou** [comment]
我装的TA_Lib‑0.4.17‑cp27‑cp27m‑win32.whl，也是报错，卸载numpy重装后就好了。
pip uninstall numpy
pip install numpy
