### ISSUE TITLE
关于事件引擎依赖Qt的疑问

### ISSUE THREAD

**Issue by vermicelli** [vnpy/vnpy#935]
## Issue类型
Question

注意到事件引擎里的timer用的是qt的QTimer。事件引擎直接和GUI库建立依赖感觉有些奇怪。这里是否可以用其他定时器替代以解除对Qt的依赖？比如python自己的threading.timer。

**Comment by vnpy** [comment]
可以，eventEngine.py中的EventEngine2就是使用Threading的实现

**Comment by vermicelli** [comment]
好的，谢谢。不好意思没注意看。
我想用一下WebTrader，以为是独立的一个基于前端技术的GUI就没装qt，后来发现还有挺多地方依赖qt的。
不知未来是否考虑把qt剥离出来，让vnpy可以单独对接基于web的UI？

**Comment by vnpy** [comment]
2.0后会对整体框架再做一次解耦
