### ISSUE TITLE
Undefined name 'STATUS_FINISHED' in algoTrading/stopAlgo.py

### ISSUE THREAD

**Issue by cclauss** [vnpy/vnpy#936]
flake8 testing of https://github.com/vnpy/vnpy --branch=dev on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./vnpy/trader/app/algoTrading/stopAlgo.py:91:32: F821 undefined name 'STATUS_FINISHED'
        if self.orderStatus in STATUS_FINISHED:
                               ^
1     F821 undefined name 'STATUS_FINISHED'
1
```

__STATUS_FINISHED__ is defined at:
* https://github.com/vnpy/vnpy/blob/dev/vnpy/trader/app/ctaStrategy/ctaEngine.py#L33

**Comment by cclauss** [comment]
@vnpy Can you please propose a fix to this issue?  It is the only reason that our flake8 tests are failing on branch dev.

**Comment by stone3536** [comment]
copy “STATUS_FINISHED”(line) from ctaEngine.py file into your file "stopAlgo.py",your class define positon.

**Comment by vnpy** [comment]
已修复
