### ISSUE TITLE
vntrader登陆了仿真账户后开仓无法成交

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#937]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32
* vn.py版本: v1.7发行版

## Issue类型
三选一：Question

## 预期程序行为
预期点发单按钮 后就应该成交（限价或者市价都式过）

## 实际程序行为
发单后委托的信息 状态 一直显示已撤销， 一直不能成交

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![tim 20180620150617](https://user-images.githubusercontent.com/40389023/41642680-9c199556-749b-11e8-9369-4c869598656e.jpg)

**Comment by vnpy** [comment]
1. 看看是否没资金了
2. 平仓看看是否有仓位
3. 错误信息里似乎你一直在平自己没有的仓位....
4. 委托价格有没有超过当日涨跌停

**Comment by jxhuliqun138** [comment]
限价是能正常成交的，市价怎么也无法成家，一发单委托状态就显示  已撤销，为什么
