### ISSUE TITLE
界面无法显示数据

### ISSUE THREAD

**Issue by daidawn19** [vnpy/vnpy#939]
## 环境
* 操作系统: 如Windows 7 64位
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.1

## Issue类型
三选一：界面无法显示数据

## 预期程序行为
MongoDB连接成功后，界面正常运行

## 实际程序行为
![capture](https://user-images.githubusercontent.com/36223686/41660192-a6fe33d2-749b-11e8-8a00-4e6db7770a5b.JPG)

## 重现步骤
点击 系统 -->连接CTP，合约代码输入MA705（或者其他代码），界面一直显示“接口不存在”，无法看到任何数据。

**Comment by piaolj** [comment]
MA705 不可以的 ，可以现在的合约才可以， 如：MA808
![default](https://user-images.githubusercontent.com/37943954/41695838-7606f054-7543-11e8-82e6-7ed50b95cd38.png)

**Comment by daidawn19** [comment]
试了以上显示的好几个代码，如MA901, MA812， MA808，全部都显示接口不存在，无法显示任何数据，所以应该不是合约代码的问题，恳请指教，谢谢！
![capture](https://user-images.githubusercontent.com/36223686/41704654-1dda8dc0-7537-11e8-9074-9d08c15da026.JPG)

**Comment by vnpy** [comment]
1. 你没有连上CTP服务器，在配置文件里修改账号了吗？
2. 大商所产品代码是小写ma

**Comment by daidawn19** [comment]
谢谢各位大神的帮助，问题算是解决了，CTP服务器在办公室的网连接不了，回家用家里的网就能连上了，可能是网络的设置问题。

**Comment by wmltyq** [comment]
各位大佬，你们是怎么找到有效的合约代码的？我刚入门，一脸懵逼~
