### ISSUE TITLE
futuGateway报错

### ISSUE THREAD

**Issue by peterzcc** [vnpy/vnpy#941]
如下文件已与现版本futuquant不兼容。无法使用。
[https://github.com/vnpy/vnpy/blob/master/vnpy/trader/gateway/futuGateway/futuGateway.py](https://github.com/vnpy/vnpy/blob/master/vnpy/trader/gateway/futuGateway/futuGateway.py)

**Comment by RexLee64** [comment]
装低版本就好了，比如futuquant2.3.14

**Comment by vnpy** [comment]
新的富途接口正在开发中
