### ISSUE TITLE
QuantosDataService 数据下载失败

### ISSUE THREAD

**Issue by hongkuik** [vnpy/vnpy#943]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
数据下载成功

## 实际程序行为
无法下载

## 重现步骤
config
{
	"MONGO_HOST": "localhost",
	"MONGO_PORT": 27017,

	"DATA_SERVER": "tcp://data.tushare.org:8910",
	"USERNAME": "注册手机号码",
	"TOKEN": "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MjkyODQ0NTcxMzAiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTMzNTc4MDU4NjcifQ.iXAwZ4lwix42tRafiPz5h7TZF6a-mCsdXqlgHPb-4pA",

	"SYMBOLS": ["rb1810.SHFE", "i1808.DCE", "zc1809.ZCE"]
}

 df, msg = api.bar(symbol, freq='1M', trade_date=d)

函数，返回的df为空，这是为什么啊？
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
可能是合约代码错误，或者QuantOS服务器没有该数据，请联系下他们的团队
