### ISSUE TITLE
通过代码控制spreadtrading模块运行按钮状态后，按钮所显示文字没同步变更

### ISSUE THREAD

**Issue by linyaohui** [vnpy/vnpy#944]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 预期程序行为

按钮状态应该显示从运行中 到已停止
## 实际程序行为
按钮状态依然为运行中

## 重现步骤
在代码中调用了algo.stop()后，算法已经成功停止运行

![qq 20180621182608](https://user-images.githubusercontent.com/7878171/41713908-2d6f4696-7581-11e8-9891-5081af7cc6d3.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
SpreadTrading模块的algo停止和启动，并没有发送事件，因此界面并不会自动更新。
