### ISSUE TITLE
wingIDE 运行runbacktesting.py无法显示权益曲线图

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#945]
## 环境

操作系统: Windows 10
Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
vn.py版本: v1.8.1

## Issue类型
三选一：Question

## 预期程序行为
出现回测参数的同时应该出现权益曲线图，命令窗口运行python runbacktesing 图形能正常显示

## 实际程序行为
wingIDE运行脚本时只出来回测数据，没有出来图形

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请使用ipython notebook运行回测
