### ISSUE TITLE
Optionmaster模块出错-找不到标的物合约510050

### ISSUE THREAD

**Issue by brian0101** [vnpy/vnpy#950]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8

Question
正常连接CTP，点击Optionmaster管理，初始化出错，找不到标的物合约510050
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![image](https://user-images.githubusercontent.com/17374743/41948249-69453c0e-79ee-11e8-849c-9e5d50db307a.png)

![image](https://user-images.githubusercontent.com/17374743/41948238-58b6068e-79ee-11e8-8711-e7242274dadb.png)

**Comment by vnpy** [comment]
1. 你得有CTP期权的实盘账号
2. 得同时连上CTPSEC和CTP
