### ISSUE TITLE
数字火币 Gate  接口  延迟太严重？

### ISSUE THREAD

**Issue by VincentYanJk** [vnpy/vnpy#951]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
Gate 只加载了 Gate 相关的 组件， 策略引擎， 风控 引擎， 把一切有潜在 影响性能的组件 都没有加载。
Gate 接口正常发单，撤销发单的一些基本操作 应该很快。

## 实际程序行为

延迟非常严重。 不知道 是我的gate 接口用的不对吗？ 还是本很 Gate 交易所的 API做了限制？
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
数字货币交易所大多采用REST和Websocket API，且部分由于性能差做了严重的限流。

除了OKEX、BINANCE、BITMEX、BITFINEX、COINBASE外，其他的API的委托回报延时一般在3-10秒的水平，感觉慢是正常现象。
