### ISSUE TITLE
银河期货的实盘账户 CTP登陆失败，错误代码3

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#952]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8发行版

## Issue类型
三选一：bug
我的sinow的仿真账户是可以正常登陆的, 
我的期货账户是银河期货， 找期货公司要了相应brokenID等信息后，
我修改了C:\vnpy\examples\VnTrader\CTP_connect.json , 但是运行时报错：
CTP:不合法的登陆   错误代码：3
## 预期程序行为
预期应该正常登陆。
## 实际程序行为
点”链接CTP“时报错：CTP:不合法的登陆   错误代码：3

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by jxhuliqun138** [comment]
吖的， 怎么没人回复

**Comment by williamlfang** [comment]
不合法的登录提示你密码错误了.

**Comment by jxhuliqun138** [comment]
不好意思， 是客服给的brokerid有误 ，整了我好几天 ，郁闷
