### ISSUE TITLE
No module named open_context

### ISSUE THREAD

**Issue by wenraoliu** [vnpy/vnpy#954]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 2 Python 2.7 32位
* vn.py版本: master 20180701

## Issue类型
Bug
## 预期程序行为
正常运行

## 实际程序行为
报如下错误：
```
...Anaconda2\lib\site-packages\vnpy\trader\gateway\futuGateway\futuGateway.py", line 15, in <module>
    from futuquant.open_context import (RET_ERROR, RET_OK, PriceRegularMode,
ImportError: No module named open_context
```
## 重现步骤
```
vnpy-master\vnpy-master\examples\VnTrader>python run.py
```
针对Bug类型Issue，请提供具体重现步骤以及报错截图
![qq 20180702000313](https://user-images.githubusercontent.com/23730998/42136308-622d364c-7d8b-11e8-8e6c-2fd39a43383e.jpg)

**Comment by a4076907** [comment]
把run.py文件中和futuquant有关的代码删掉。

**Comment by wenraoliu** [comment]
这是富途接口的bug导致的吗？可是我的账户刚好是富途的呢

**Comment by a4076907** [comment]
是的

**Comment by vnpy** [comment]
已完成新的富途接口开发。
