### ISSUE TITLE
vn.crypto项目 - 阶段1

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy#958]
vn.crypto项目 - 阶段1的开发计划如下，预计将在v1.9版本中全部完成：

- [x] API接口（包括异步高性能API和统一标准Gateway）
    - [x] 火币
    - [x] OKEX
    - [x] 币安
    - [x] Bitfinex
    - [x] BitMEX
    - [x] FCoin
    - [x] BigOne
    - [x] Lbank
    - [x] Coinbase
    - [x] ccxt通用接口
- [x] 算法交易
    - [x] 算法
        - [x] TWAP（时间加权平均）
        - [x] DMA（直接委托）
        - [x] STOP（止损单）
        - [x] ST（SelfTrade 自成交刷单）
        - [x] BL（BestLimit 最优限价）
        - [x] Sniper（狙击手）
        - [x] Iceberg（冰山，可用于护盘）
    - [x] 引擎
        - [x] 基于算法配置模板快速启动算法
        - [x] 算法运行状态实时同步保存数据库
        - [x] 基于CSV文件加载一篮子算法配置模板
        - [x] 基于CSV文件启动一篮子算法
        - [x] 自动检测和加载算法功能
        - [x] 对外部程序提供RPC模式的算法交易服务
- [x] 管理功能
    - [x] 针对数字货币优化的图形交易工具CryptoTrader
    - [x] 数字货币交易的数据解决方案DataService

**Comment by xldistance** [comment]
群主啥时候添加bitmex的期货接口啊

**Comment by vnpy** [comment]
BitMEX只有期货交易功能，已经完成了

**Comment by xldistance** [comment]
我看方向映射只有buy和sell。。。。。。

**Comment by VincentYanJk** [comment]
群主这两天 我刚完成了一个Coinex 的api 和 gateway，同时写了 一个 刷单的策略 可以加进去吗？ 
也有些东西想跟你讨论一下。 方便的话 可以 加我。我就不问您的QQ了， 以防泄露了。  这是我的QQ： 601810068
![image](https://user-images.githubusercontent.com/13777038/42305490-befd9e5a-805d-11e8-93f9-48cc0bc2d567.png)
![image](https://user-images.githubusercontent.com/13777038/42305582-1f73a0b8-805e-11e8-9787-6e3b68646008.png)

**Comment by raidsan** [comment]
bitmex接口做出来了能不能先早点放上来,  币安是现货做长线持有，Bitfinex门槛有点高了，有杠杆值得做程序化比较靠谱点的平台就只有bitmex， 逐仓交易风险可控， 其他的几个平台说实话还是离远点好。如果等太久就只好自己写了……  楼上这位兄弟既然已经都做好了，也可以共享出来啊， 在 github 上 fork一个就可以发布自己的修改版了啊

**Comment by xldistance** [comment]
@raidsan dev有bitmex的接口，不过我还没实盘试过能否做空。看成交映射只有buy,sell有点懵逼

**Comment by vnpy** [comment]
@xldistance 海外的期货交易所，都是自动对冲的，也就无需管开平仓的概念。

比如现在有多单2手，你去卖4手，那么会直接变成持有空单2手。

这个才是正常的设计思路，国内的路子其实是不正常的。

**Comment by xldistance** [comment]
明白了，多谢群主解答

**Comment by vnpy** [comment]
vn.crypto第一阶段开发计划完成

**Comment by renfjnov** [comment]
棒棒棒!
