### ISSUE TITLE
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyAtrRsi

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#960]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32
* vn.py版本: v1.81

## Issue类型
三选一：Question

## 预期程序行为
可以正常加载策略

## 实际程序行为
无法加载策略

## 重现步骤
只要运行run.py就出现
启动vntrader的时候报错
![1](https://user-images.githubusercontent.com/20625763/42269694-6ced4bd0-7fb1-11e8-958d-d03dc913ba53.png)

**Comment by cooooo** [comment]
安装talib包

**Comment by psj6335490** [comment]
嗯嗯，后来搞定了
