### ISSUE TITLE
火币看不到行情

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#961]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 
* vn.py版本: 如v1.81发行版

## Issue类型
三选一：Question

## 预期程序行为
期望能像期货一样在：帮助-》合约查询 中看到信息，

## 实际程序行为
不能看到信息

## 重现步骤

连接成功但是看不到行情
![1](https://user-images.githubusercontent.com/20625763/42298222-650eb31e-8037-11e8-8079-0d82d61bc068.png)

**Comment by VincentYanJk** [comment]
你在订阅的时候 可能 exchange 或是 gateway 没有选对。 导致mainengine 在 订阅的时候找不到 huobiGateway

**Comment by psj6335490** [comment]
请问在哪里选exchange

**Comment by psj6335490** [comment]
exchange设置的是hadax啊

**Comment by VincentYanJk** [comment]
这个订阅交易对， 从前台触发 一直 到 Huobi 中间经历了很多步，出错的地方有很多，例如你订阅的 symbol 的 和你 本地数据库存的 contract 的symbol 不一致， 或是你的火币 gateway中的  接口上有问题；
总之都是 传参过程中的问题， 试着从这些方向 debug 看一下

**Comment by hello886** [comment]
怎么搞定的？
