### ISSUE TITLE
STRATEGY_CLASS 字典初始化错误

### ISSUE THREAD

**Issue by datangxiaoyaojiangjun** [vnpy/vnpy#962]
## 环境
* vn.py版本: 如v1.8.1发行版

## Issue类型
三选一：Bug
D:\Users\think\Anaconda2\Lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py  第21行 将“Strategy"改为”strategy"
## 预期程序行为
自动导入策略类，若目录下的文件名包含strategy字符

## 实际程序行为
一个也导入不了，因为文件名不是大写Strategy开头，而是小写

## 重现步骤
运行runCtaTrading，没改前找不到策略

南岳—但丁

**Comment by vnpy** [comment]
21行的内容是注释信息，修改无用
