### ISSUE TITLE
ctaEngine.loadBar()隐患

### ISSUE THREAD

**Issue by datangxiaoyaojiangjun** [vnpy/vnpy#963]
## Issue类型
Enhancement

## 预期程序行为
ctaEngine.loadBar()加载距今N天数据作为初始化数据，用来填充am，生成交易信号指标

## 存在的隐患
如数据库数据没有更新：如最近10天的数据，但是少了昨天的数据，加载不会报错，会生成不与市场同步的指标，诱发交易错误

## 改进
建议加入数据完整性检验：

**Comment by viponedream** [comment]
有效交易日的前n天。要用日历来判断了。
