### ISSUE TITLE
Vntrader交易软件显示异常

### ISSUE THREAD

**Issue by bluceGYF** [vnpy/vnpy#967]
## 环境

* 操作系统: win10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本:vnpy-1.8-2

## Issue类型
三选一：Question

Vntrader.bat运行启动 有时候一切正常 ，有时候只有连接数据库成功，行情服务器和交易服务器不显示连接

今天出现了 连接都成功但是不现实账户信息（模拟盘）

![image](https://user-images.githubusercontent.com/34001296/42366610-30974f94-8134-11e8-8ddd-732ef2446d12.png)

CTA_connection.json的配置

![image](https://user-images.githubusercontent.com/34001296/42366715-801473b2-8134-11e8-8d52-3f0fe1ddd895.png)

**Comment by vnpy** [comment]
3点后可能是SIMNOW服务器关了
