### ISSUE TITLE
问一下作者，我想把自己公司的平台接上来，不知道怎么接，作者可以提示一下么。

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#968]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

问一下作者，我想把自己公司的平台接上来，不知道怎么接，作者可以提示一下么。

**Comment by psj6335490** [comment]
就是不晓得代码写在哪里

**Comment by vnpy** [comment]
请具体说下你们公司的平台是什么？以及贵司的类型：交易所、经纪商、等等

**Comment by psj6335490** [comment]
首先感谢你的回复：
      我们是深圳的一个小公司，还没有拿到牌照，老板自己弄了一个平台，现在自己的平台上做交易，不知道怎么把自己平台的接口接到vnpy上面，

是不是按照huobi一样弄接口，然后照着你的项目里的写个这个，然后在写个这个就可以用了么。

谢谢！！

**Comment by psj6335490** [comment]
首先感谢你的回复：
      我们是深圳的一个小公司，还没有拿到牌照，老板自己弄了一个平台，现在自己的平台上做交易，不知道怎么把自己平台的接口接到vnpy上面，

是不是按照huobi一样弄接口，然后照着你的项目里的写个这个
![1](https://user-images.githubusercontent.com/20625763/42434275-27b34b96-8385-11e8-83d3-b30887e1aaaf.jpg)

，然后在写个这个
![2](https://user-images.githubusercontent.com/20625763/42434280-2b6a5734-8385-11e8-8528-f74c140eb852.jpg)
就可以用了么。

谢谢！！

**Comment by linyaohui** [comment]
是的

**Comment by linyaohui** [comment]
你们平台网址是？

**Comment by psj6335490** [comment]
平台还在建啊，linyaohui兄弟能不能加一下QQ or 微信

**Comment by psj6335490** [comment]
作者，就是要接入一个新的平台的接口道vnpy上，具体要改那些接口

**Comment by vnpy** [comment]
需要根据你们的REST和Websocket API协议，实现一个vnpy/api下的Python API封装。
然后再将其中的数据流格式，转化成VnTrader格式，实现一个vnpy/trader/gateway下的交易路由。
