### ISSUE TITLE
safeUnicode的完善

### ISSUE THREAD

**Issue by miyihuxi** [vnpy/vnpy#971]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

def safeUnicode(value):
    """检查接口数据潜在的错误，保证转化为的字符串正确"""
    #float值为nan时出错，增加一个判断。
    
    def isnan(num):
        return num != num

    # 检查是数字接近0时会出现的浮点数上限
    if type(value) is int or type(value) is float:
        if value > MAX_NUMBER or isnan(value):
            value = 0

    # 检查防止小数点位过多
    if type(value) is float:
        print(value)
        print(type(value))
        d = decimal.Decimal(str(value))
        print(d)
        print(type(d))
        if abs(d.as_tuple().exponent) > MAX_DECIMAL:
            value = round(value, ndigits=MAX_DECIMAL)

    return str(value)

**Comment by vnpy** [comment]
检查了下，目前safeUnicode只使用在显示交易接口过来的原始数据上，几乎不会出现nan这种数据。

如果用在了其他地方可能有nan的话，请根据需求来修改吧
