### ISSUE TITLE
talib 的macd指标计算出来的 diff 和dea的值与普通行情软件有差异

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#972]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.81

## Issue类型
三选一：Bug

## 预期程序行为
talib 的macd指标计算出来的 dif 和dea的值与普通行情软件的值不一样，dea和macd的值相差蛮大，请问应该如何处理

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by KobeZhao** [comment]
talib的指标和行情软件上是有可能会不一样的，建议仔细研究并比较下两者的计算方法(比如ema的参数等)。

**Comment by jxhuliqun138** [comment]
好的
