### ISSUE TITLE
CTA 策略能不能用在数字货币上

### ISSUE THREAD

**Issue by psj6335490** [vnpy/vnpy#973]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

![1](https://user-images.githubusercontent.com/20625763/42493203-921bd128-844e-11e8-87d3-603fc78005ef.png)
这里的CTA策略是专门给期货用的，还是数字货币也可以用。

**Comment by xldistance** [comment]
可以用在数字货币上
