### ISSUE TITLE
No module named vnpy.event

### ISSUE THREAD

**Issue by Zephyen** [vnpy/vnpy#980]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.81发行版

## Issue类型
Question

## 预期程序行为
能够正常运行程序，并且显示界面

## 实际程序行为
运行程序时候出现这个问题：No module named vnpy.event

## 重现步骤
[按照官方ubuntu 环境安装](https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85) 
针对Bug类型Issue，请提供具体重现步骤以及报错截图
我确定已经安装
···
bash install.sh
···
报错和环境配置如下：
![image](https://user-images.githubusercontent.com/8236466/42640803-ab421378-8625-11e8-9a91-6089bc09ec6a.png)

**Comment by Zephyen** [comment]
我使用root 去install 并且已经将root 的环境变量设置成anacoda的python了。

**Comment by vnpy** [comment]
请在vnpy目录下，运行python setup.py install，看看是否有错误信息

**Comment by wheeler18** [comment]
@Zephyen  请问你解决这个问题了吗？

**Comment by Zephyen** [comment]
@vnpy HI.我又来了。install 后未见报错
![image](https://user-images.githubusercontent.com/8236466/43030599-fb0ce36a-8cc4-11e8-9818-4d62bb67ed89.png)
进入vnTrader目录，运行失败，报No module named vnxpquote.

![image](https://user-images.githubusercontent.com/8236466/43030612-42055e46-8cc5-11e8-9cfe-542f403194a6.png)

**Comment by Zephyen** [comment]
@wheeler18 并没解决。现在还是有这个问题。

**Comment by Zephyen** [comment]
@vnpy 请问作者是日常开发用windows开发的还是ubuntu开发的。我用ubuntu两次尝试安装都是缺module了。

**Comment by maroonstar** [comment]
也有同样的问题，安装dev版本会出现`No module named vnpy.event`，master没有这种问题

**Comment by vnpy** [comment]
日常使用Windows系统，Ubuntu系统的兼容性一般在master正式版发布时会做测试

**Comment by wheeler18** [comment]
这种错怎么排查啊？排错完能把思路说一说吗？完全不知道怎么办，学习一下

**Comment by meng1j** [comment]
@zephyen 注意看你截图的python 版本，上面写的是64bit不是32bit。

**Comment by sixkingdoms** [comment]
在examples\vntraders 下面， 开一个python , 
from vnpy.event import EventEngine ，
如果不报错，那应该就是path的问题。 我建议可以从新跑一下 python setup.py install. 这个在windows 下解决了我的问题。
