### ISSUE TITLE
将ricequant平台上的海龟交易法多品种回测代码移植过来的想法

### ISSUE THREAD

**Issue by nikitazhhy** [vnpy/vnpy#982]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.1

## Issue类型
Question

## 预期程序行为
将个人ricequant平台上的多品种海龟代码移植到ricequant

## 实际程序行为

个人目前在ricequant在线平台用他们的API已经能够基本还原了海龟交易法多品种回测
基本思路是先构建一个DataFrame格式的框架，然后将基础数据更新到dataframe中并循环判断开平仓等条件。

估计用pandas交易速度会有些慢

群主之前有说过要做海龟策略的编写，不知道我这想法跟群主的思路是否一致，可以的话我先尝试着修改到vnpy平台上。

对vnpy的数据存储原理还是不太熟悉，估计做出来会bug百出~

如果群主已经要做出来vnpy平台的海龟策略，请关闭该issue，等待群主的更新~~

**Comment by vnpy** [comment]
欢迎尝试，海龟的策略会在v1.9内完成。
