### ISSUE TITLE
Tick数据回测时，一次性loadHistoryData容易导致内存不够

### ISSUE THREAD

**Issue by q6218271** [vnpy/vnpy#983]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Enhancement

## 预期程序行为

在使用Tick级别的数据进行回测时，由于数据是一次性载入（BacktestingEngine.loadHistoryData），普通配置的机器（阿里云4G）内存根本不够用。有没有啥分批载入改动思路？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by cooooo** [comment]
有人实现了依次加载csv回测，这就需要自己实现了

**Comment by vnpy** [comment]
分段回测，将回测的每日交易的DataFrame相加，再执行calculateDailyStatistics统计，参考examples/ctaBacktesting下的backtesting_portfolio方法。
