### ISSUE TITLE
No module named vnpy.event

### ISSUE THREAD

**Issue by wheeler18** [vnpy/vnpy#986]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.1
## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

正常安装。原来一模一样的过程安装，但是出现了
No module named vnpy.event
莫名其妙的错误，看到之前有一个closed issue，但是并没有看到回复说可以运行了。
试过python setup.py install，没有报错，但是运行run  webServer.py就报错

**Comment by yua3** [comment]
运行 python setup.py install

**Comment by wheeler18** [comment]
试过了

**Comment by wheeler18** [comment]
TA-lib都是一键安装的。版本没有错。以前安装过1.8,1.7都没问题。自己在腾讯云乱弄，搞坏了。然后在Windows7虚拟机下也同样的问题。。。

**Comment by wheeler18** [comment]
解决了，有些文件都是root用户的，通通chown。自己的原因，打扰大家了
