### ISSUE TITLE
float型数据比较判断出错

### ISSUE THREAD

**Issue by jxhuliqun138** [vnpy/vnpy#987]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 4.0.0 
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug

## 预期程序行为
print fastMa0 < hourMa10,  slowMa0 < hourMa10, fastMa0 == hourMa10
log: fMa0=618.000000, sMa0=617.821053, ma60=618.000000,   True True False
请问一下 为什么fastMa0 < hourMa10 会为ture， 而fastMa0 == hourMa10 会为false

**Comment by vnpy** [comment]
浮点数比较可能存在精度问题，建议round到较少的小数位后再做
