### ISSUE TITLE
连接bitmex接口无法记录行情数据

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#988]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
运行rundatarecording无法记录bitmex行情数据，dr_setting设置如下
        ["XBTU18", "BITMEX"],
        ["ETHU18", "BITMEX"],   
        ["EOSU18", "BITMEX"],  
        ["BCHU18", "BITMEX"],  
        ["LTCU18", "BITMEX"],
        ["XRPU18", "BITMEX"],  
        ["ADAU18", "BITMEX"]

**Comment by xldistance** [comment]
是不是因为缺少了tick的exchange，symbol的原因？

**Comment by xldistance** [comment]
还是因为缺少tick的high low啊，也不提示出错也不记录行情......

**Comment by vnpy** [comment]
请检查是否在BITMEX_connect.json中配置了要记录行情的合约代码，如果没有配置的话是不会订阅收到推送的。
