### ISSUE TITLE
下载的dev最新版，无法启动。NameError: name 'STATUS_ALLTRADED' is not defined

### ISSUE THREAD

**Issue by yikeshu1** [vnpy/vnpy#989]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: dev branch 20180721（下载日期）

## Issue类型
Bug

## 预期程序行为
应该启动

## 实际程序行为
无法启动

## 重现步骤
![vn_iss](https://user-images.githubusercontent.com/12369075/43037068-1ae52172-8d3b-11e8-9004-3827ce3ba421.jpg)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by yikeshu1** [comment]
启动的时候注释掉 algoTrading模块
 #me.addApp(algoTrading)
还是报错。
![isse](https://user-images.githubusercontent.com/12369075/43037708-30c9729c-8d43-11e8-855b-4afd26834319.jpg)

**Comment by vnpy** [comment]
已修复
