### ISSUE TITLE
在CentOS7上面安装时报错

### ISSUE THREAD

**Issue by simon82** [vnpy/vnpy#990]
## 环境

* 操作系统: CentOS7 (CentOS Linux release 7.5.1804 (Core) )
* Anaconda版本: Anaconda 4.0.0 Python 2.7 64位
* vn.py版本: v1.8.1

## Issue类型
Question

## 实际程序行为
不能成功安装或运行，不确定是否能在CentOS环境下安装。

## 重现步骤
[root@localhost vnpy-1.8.1]# ./install.sh 

针对Bug类型Issue，请提供具体重现步骤以及报错截图
[root@localhost vnpy-1.8.1]# ./install.sh 
/usr/local/vnpy-1.8.1/vnpy/api/ctp /usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/ctp/build /usr/local/vnpy-1.8.1/vnpy/api/ctp
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Under unix: 8
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
--   thread
--   date_time
--   system
--   chrono
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY
    linked by target "vnctpmd" in directory /usr/local/vnpy-1.8.1/vnpy/api/ctp
    linked by target "vnctptd" in directory /usr/local/vnpy-1.8.1/vnpy/api/ctp

-- Configuring incomplete, errors occurred!
See also "/usr/local/vnpy-1.8.1/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".
/usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/lts /usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/lts/build /usr/local/vnpy-1.8.1/vnpy/api/lts
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Under unix: 8
ltsapi
/usr/local/vnpy-1.8.1/vnpy/api/lts/ltsapi/libsecuritymduserapi.so
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
--   thread
--   date_time
--   system
--   chrono
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY
    linked by target "vnltsmd" in directory /usr/local/vnpy-1.8.1/vnpy/api/lts
    linked by target "vnltsqry" in directory /usr/local/vnpy-1.8.1/vnpy/api/lts
    linked by target "vnltstd" in directory /usr/local/vnpy-1.8.1/vnpy/api/lts

-- Configuring incomplete, errors occurred!
See also "/usr/local/vnpy-1.8.1/vnpy/api/lts/build/CMakeFiles/CMakeOutput.log".
/usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/xtp /usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/xtp/build /usr/local/vnpy-1.8.1/vnpy/api/xtp
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Under unix: 8
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
--   thread
--   date_time
--   system
--   chrono
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY
    linked by target "vnxtpquote" in directory /usr/local/vnpy-1.8.1/vnpy/api/xtp
    linked by target "vnxtptrader" in directory /usr/local/vnpy-1.8.1/vnpy/api/xtp
XTPAPI_MD_LIBRARY
    linked by target "vnxtpquote" in directory /usr/local/vnpy-1.8.1/vnpy/api/xtp
XTPAPI_TD_LIBRARY
    linked by target "vnxtptrader" in directory /usr/local/vnpy-1.8.1/vnpy/api/xtp

-- Configuring incomplete, errors occurred!
See also "/usr/local/vnpy-1.8.1/vnpy/api/xtp/build/CMakeFiles/CMakeOutput.log".
/usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/ib /usr/local/vnpy-1.8.1
/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux /usr/local/vnpy-1.8.1/vnpy/api/ib
/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build
/usr/bin/cmake -H/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux -B/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: 进入目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
make -f CMakeFiles/twsapi.dir/build.make CMakeFiles/twsapi.dir/depend
make[2]: 进入目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
cd /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/twsapi.dir/DependInfo.cmake --color=
Dependee "/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/twsapi.dir/DependInfo.cmake" is newer than depender "/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/twsapi.dir/depend.internal".
Dependee "/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles/twsapi.dir/depend.internal".
Scanning dependencies of target twsapi
make[2]: 离开目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
make -f CMakeFiles/twsapi.dir/build.make CMakeFiles/twsapi.dir/build
make[2]: 进入目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 1
[  4%] Building CXX object CMakeFiles/twsapi.dir/client/ContractCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/ContractCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/ContractCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 2
[  9%] Building CXX object CMakeFiles/twsapi.dir/client/DefaultEWrapper.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/DefaultEWrapper.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/DefaultEWrapper.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 3
[ 14%] Building CXX object CMakeFiles/twsapi.dir/client/EClient.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EClient.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EClient.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 4
[ 19%] Building CXX object CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 5
[ 23%] Building CXX object CMakeFiles/twsapi.dir/client/EDecoder.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EDecoder.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EDecoder.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 6
[ 28%] Building CXX object CMakeFiles/twsapi.dir/client/EMessage.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EMessage.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EMessage.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 7
[ 33%] Building CXX object CMakeFiles/twsapi.dir/client/EMutex.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EMutex.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EMutex.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 8
[ 38%] Building CXX object CMakeFiles/twsapi.dir/client/EReader.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EReader.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EReader.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 9
[ 42%] Building CXX object CMakeFiles/twsapi.dir/client/EReaderOSSignal.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EReaderOSSignal.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EReaderOSSignal.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 10
[ 47%] Building CXX object CMakeFiles/twsapi.dir/client/EReaderWMSignal.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/EReaderWMSignal.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/EReaderWMSignal.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 11
[ 52%] Building CXX object CMakeFiles/twsapi.dir/client/ESocket.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/ESocket.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/ESocket.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 12
[ 57%] Building CXX object CMakeFiles/twsapi.dir/client/MarginCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/MarginCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/MarginCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 13
[ 61%] Building CXX object CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 14
[ 66%] Building CXX object CMakeFiles/twsapi.dir/client/OrderCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/OrderCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/OrderCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 15
[ 71%] Building CXX object CMakeFiles/twsapi.dir/client/PercentChangeCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/PercentChangeCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/PercentChangeCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 16
[ 76%] Building CXX object CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 17
[ 80%] Building CXX object CMakeFiles/twsapi.dir/client/SoftDollarTier.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/SoftDollarTier.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/SoftDollarTier.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 18
[ 85%] Building CXX object CMakeFiles/twsapi.dir/client/StdAfx.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/StdAfx.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/StdAfx.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 19
[ 90%] Building CXX object CMakeFiles/twsapi.dir/client/TimeCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/TimeCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/TimeCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 20
[ 95%] Building CXX object CMakeFiles/twsapi.dir/client/VolumeCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/VolumeCondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/VolumeCondition.cpp
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 21
[100%] Building CXX object CMakeFiles/twsapi.dir/client/executioncondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -fPIC -std=c++11 -O3 -DNDEBUG -fPIC -I/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/IB_PATH    -o CMakeFiles/twsapi.dir/client/executioncondition.cpp.o -c /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/client/executioncondition.cpp
Linking CXX shared library lib/twsapi.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/twsapi.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC  -fPIC -std=c++11 -O3 -DNDEBUG   -shared -Wl,-soname,twsapi.so -o lib/twsapi.so CMakeFiles/twsapi.dir/client/ContractCondition.cpp.o CMakeFiles/twsapi.dir/client/DefaultEWrapper.cpp.o CMakeFiles/twsapi.dir/client/EClient.cpp.o CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o CMakeFiles/twsapi.dir/client/EDecoder.cpp.o CMakeFiles/twsapi.dir/client/EMessage.cpp.o CMakeFiles/twsapi.dir/client/EMutex.cpp.o CMakeFiles/twsapi.dir/client/EReader.cpp.o CMakeFiles/twsapi.dir/client/EReaderOSSignal.cpp.o CMakeFiles/twsapi.dir/client/EReaderWMSignal.cpp.o CMakeFiles/twsapi.dir/client/ESocket.cpp.o CMakeFiles/twsapi.dir/client/MarginCondition.cpp.o CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o CMakeFiles/twsapi.dir/client/OrderCondition.cpp.o CMakeFiles/twsapi.dir/client/PercentChangeCondition.cpp.o CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o CMakeFiles/twsapi.dir/client/SoftDollarTier.cpp.o CMakeFiles/twsapi.dir/client/StdAfx.cpp.o CMakeFiles/twsapi.dir/client/TimeCondition.cpp.o CMakeFiles/twsapi.dir/client/VolumeCondition.cpp.o CMakeFiles/twsapi.dir/client/executioncondition.cpp.o 
make[2]: 离开目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
/usr/bin/cmake -E cmake_progress_report /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
[100%] Built target twsapi
make[1]: 离开目录“/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build”
/usr/bin/cmake -E cmake_progress_start /usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux/build/CMakeFiles 0
/usr/local/vnpy-1.8.1/vnpy/api/ib/ibapi/linux
/usr/local/vnpy-1.8.1/vnpy/api/ib
/usr/local/vnpy-1.8.1/vnpy/api/ib/build /usr/local/vnpy-1.8.1/vnpy/api/ib
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
--   thread
--   date_time
--   system
--   chrono
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY
    linked by target "vnib" in directory /usr/local/vnpy-1.8.1/vnpy/api/ib

-- Configuring incomplete, errors occurred!
See also "/usr/local/vnpy-1.8.1/vnpy/api/ib/build/CMakeFiles/CMakeOutput.log".

**Comment by vnpy** [comment]
CentOS并不在vn.py官方支持的系统中，从报错信息来看：

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY

应该是CentOS上Python的环境变量路径名找不到，试试去手动修改下吧。
