### ISSUE TITLE
安装vnpy的ubuntu系统将无法安装其他软件

### ISSUE THREAD

**Issue by xiyanxiyan10** [vnpy/vnpy#991]
装了该软件的ubuntu将无法使用 apt-get 安装其他软件，会默认访问1.1.1.2

**Comment by vnpy** [comment]
请说明下你是怎么安装的？

**Comment by xiyanxiyan10** [comment]
https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
完全参考这个教程，主要使用脚本bash install.sh  进行安装。

**Comment by vnpy** [comment]
请提供下个1.1.1.2的IP地址报错的截图吧

**Comment by xiyanxiyan10** [comment]
已找到原因，误报，因我这边网络环境问题，将拉取apt的源转为1.1.1.2这个地址了。麻烦up主了

**Comment by xiyanxiyan10** [comment]
已解决
