### ISSUE TITLE
连接fcoin接口记录行情数据提示time数据不规范

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#992]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
打印fcoin的tick date time数据都是符合%Y%m%d %H%M%S的
![qq 20180723110041](https://user-images.githubusercontent.com/29418474/43055559-cb87ecf6-8e69-11e8-87f9-e553d63ed088.png)

**Comment by xldistance** [comment]
打印了下好像是fcoin的depth里面没有t8ck的毫秒数据，是因为这个原因吗

**Comment by vnpy** [comment]
对的，数字货币交易所的行情大多没有那么精准，在DataRecording里面做了兼容性处理

**Comment by xldistance** [comment]
改了之后提示time data ' '  dose not match format '%Y%m%d %H%M%S'

**Comment by xldistance** [comment]
这是tick的datetime  2018-07-24 09:05:42   我在fcoin gateway和drengine改为%Y-%m-%d出现提示time data ' ' dose not match format '%Y-%m-%d %H%M%S'

**Comment by xldistance** [comment]
确定是fcoin接口，进入程序是可以正确显示行情的，但是记录行情就会出错。

**Comment by psj6335490** [comment]
加我QQ 讨论一下 我也在接FCOIN

**Comment by psj6335490** [comment]
我的微信是56102515，交流一下接FCION

**Comment by xldistance** [comment]
据微信群友反映币安也有这个问题

**Comment by vnpy** [comment]
OK，我来用DR测试下

**Comment by psj6335490** [comment]
Fcoin 的tick时间只能精确到秒，而且还不是固定1秒，间隔有时时2秒或者3秒一个tick

**Comment by vnpy** [comment]
已修复，因为FCOIN的接口的时间戳只在onDepth里生成，而如果onTick先触发推送Tick时就会出现第一次没有时间戳的情形，导致报错。
