### ISSUE TITLE
中信cshshlpGateway 加载报错

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#996]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Bug 

## 预期程序行为
None

## 实际程序行为
Get This machine id203 failed!

## 重现步骤
from vnpy.trader.gateway import cshshlpGateway

针对Bug类型Issue，请提供具体重现步骤以及报错截图
![_20180725155538](https://user-images.githubusercontent.com/12085501/43187139-48e780b6-9023-11e8-9c83-04ff13d793cb.png)

**Comment by vnpy** [comment]
请先联系中信证券申请API接入的授权文件

**Comment by jieyujing** [comment]
感谢解答，我以为像ctp一样开户后就能直接使用。
