### ISSUE TITLE
Bitmex 無法讀取帳戶數據&無法下單

### ISSUE THREAD

**Issue by proerror** [vnpy/vnpy#997]
## 环境

windows server 2016 

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
Bug

## 预期程序行为
正常帳戶數據跟下單

## 实际程序行为
報價數據正確，帳戶數據錯誤 無法下單

## 重现步骤
加入API Key 以後，連接交易所bitmex

![image](https://user-images.githubusercontent.com/11917326/43187734-de1f02de-9024-11e8-9ea8-e744175c8f0e.png)

![42805d5bbaa3ac3101cd7895925b249](https://user-images.githubusercontent.com/11917326/43187709-c82b63be-9024-11e8-8bb1-de029a2ebf9a.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
测试后可用，请检查是否接口的KEY配置有误
